<?php
	$arr=array("TRENDS_SEARCH_MALE","NOTRENDS_SEARCH_MALE","TRENDS_SEARCH_FEMALE","NOTRENDS_SEARCH_FEMALE","FEMALE_TRENDS_HEAP","MALE_TRENDS_HEAP","HEAP_TRENDS_MALE","HEAP_TRENDS_FEMALE","HEAP_NOTRENDS_MALE","HEAP_NOTRENDS_FEMALE");
	for($i=0;$i<count($arr);$i++)
	{
		$str=$arr[$i];
		//passthru("echo 'truncate table $str' | /usr/bin/mysql -u localuser -pKm7Iv80l -h 172.16.3.185 matchalerts;/usr/bin/mysqldump -t -u ankit -pankit -h172.16.3.157 -P3306 matchalerts $str  | /usr/bin/mysql -u localuser -pKm7Iv80l -h 172.16.3.185 matchalerts;");
		passthru("echo 'truncate table $str' | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.65.99 -P 3308 matchalerts;/usr/local/jeevansathi/bin/mysqldump -t -u user -pCLDLRTa9 -S /tmp/mysql.sock matchalerts $str  | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.65.99 -P 3308 matchalerts;");
		passthru("echo 'truncate table $str' | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.64.207 -P 3308 matchalerts;/usr/local/jeevansathi/bin/mysqldump -t -u user -pCLDLRTa9 -S /tmp/mysql.sock matchalerts $str  | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.64.207 -P 3308 matchalerts;");
	}
	//passthru('echo "truncate table SEARCH_FEMALE" | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.65.99 -P 3308 matchalerts;/usr/local/jeevansathi/bin/mysqldump -t -u user -pCLDLRTa9 -S /tmp/mysql.sock matchalerts SEARCH_FEMALE | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.65.99 -P 3308 matchalerts;echo "truncate table SEARCH_MALE" | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.65.99 -P 3308 matchalerts;/usr/local/jeevansathi/bin/mysqldump -t -u user -pCLDLRTa9 -S /tmp/mysql.sock matchalerts SEARCH_MALE | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.65.99 -P 3308 matchalerts;echo "truncate table TRENDS" | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.65.99 -P 3308 matchalerts;/usr/local/jeevansathi/bin/mysqldump -t -u user -pCLDLRTa9 -S /tmp/mysql.sock matchalerts TRENDS | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.65.99 -P 3308 matchalerts');

	//passthru('echo "truncate table SEARCH_FEMALE" | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.64.207 -P 3308 matchalerts;/usr/local/jeevansathi/bin/mysqldump -t -u user -pCLDLRTa9 -S /tmp/mysql.sock matchalerts SEARCH_FEMALE | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.64.207 -P 3308 matchalerts;echo "truncate table SEARCH_MALE" | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.64.207 -P 3308 matchalerts;/usr/local/jeevansathi/bin/mysqldump -t -u user -pCLDLRTa9 -S /tmp/mysql.sock matchalerts SEARCH_MALE | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.64.207 -P 3308 matchalerts;echo "truncate table TRENDS" | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.64.207 -P 3308 matchalerts;/usr/local/jeevansathi/bin/mysqldump -t -u user -pCLDLRTa9 -S /tmp/mysql.sock matchalerts TRENDS | /usr/local/jeevansathi/bin/mysql -u user -pCLDLRTa9 -h 10.208.64.207 -P 3308 matchalerts');

?>
