#!/usr/bin/env bash
# Hook that checks PHP syntax
git diff --cached --name-only | while read FILE; do
if [[ "$FILE" =~ ^.+(php|inc)$ ]]; then
    # Courtesy of swytsh from the comments below.
    if [[ -f $FILE ]]; then
        php -l "$FILE" 1> /dev/null
        if [ $? -ne 0 ]; then
            echo -e "\e[1;31m\tAborting commit due to files with syntax errors. $FILE \e[0m" >&2
            exit 1
        fi
    fi
fi
done || exit $?

#declare IsCssJsChanged;
#git diff --cached --name-only |{
#        while read FILE; do
#        if [[ "$FILE" =~ ^.+(js|css)$ ]]; then
#                if [[ -f $FILE ]]; then
#                        IsCssJsChanged=1;
#                        echo "/$FILE" >> /tmp/jsCssFilelog.txt
#                fi
#        fi
#        done
#
#        if [[ "$IsCssJsChanged" == "1" ]]; then
#                echo "Committing capistrano/generate_commonfile_functions.php";
#                php capistrano/generate_commonfile_functions.php
#                echo "" > /tmp/jsCssFilelog.txt
#        fi}
git diff --cached --name-only |
{
       while read FILE; do
				if [[ -f $FILE ]]; then
           echo "/$FILE" >> /tmp/capistranochangelog.txt
				fi
       done

       echo "check for Committing /capistrano/localStorageRevision.txt";
       php capistrano/sessionStorageCheckFileChange.php
       echo "" > /tmp/capistranochangelog.txt
       
}

