export const cardData = [{
  headingBoldEng: "Why",
  headingBoldHindi: "क्यों",
  headingEng: " should you write 'About Me'",
  headingHindi: "आपको अपने बारे में लिखना चाहिए?",
  subheadingEng1: " This section helps the interested candidates to get a glimpse of your personality and things that matter you the most.",
  subheadingHindi1: "  इससे इच्छुक लोगों को आपके व्यक्तित्व और आपके लिए सबसे महत्वपूर्ण चीजों को जानने में सहायता मिलेगी।",
  cardBody: "vc_icons1 imgWidHeight"
}, {
  headingBoldEng: "How",
  headingBoldHindi: "कैसे",
  headingEng: "can you write a good 'About Me'",
  headingHindi: "आप इसे अच्छा और उचित लिख सकते हैं?",
  subheadingEng1: " You can write about your ",
  subheadingEngstrong: "interests, hobbies ",
  subheadingEng2: "and things you enjoy doing.",
  exampleTextEnglish: "View Samples",
  exampleTextHindi: "उदाहरण देखें",
  subheadingHindi1: " आप अपनी",
  subheadingHindistrong: "  रुचि, शौक  ",
  subheadingHindi2: "  और पसंदीदा चीजों के बारे में लिख सकते हैं।",
  cardBody: "vc_icons2 imgWidHeight"
}, {
  headingBoldEng: "How",
  headingBoldHindi: "कैसे",
  headingEng: "can you write a good 'About Me'",
  headingHindi: "आप इसे अच्छा और उचित लिख सकते हैं?",
  subheadingEng1: "You can write about your ",
  subheadingEngstrong: "educational background & career achievements ",
  subheadingEng2: "",
  exampleTextEnglish: "View Samples",
  subheadingHindi1: "आप अपनी",
  subheadingHindistrong: "  शिक्षा और व्यवसाय ",
  subheadingHindi2: "  के बारे में लिख सकते हैं।",
  exampleTextHindi: "उदाहरण देखें",
  cardBody: "vc_icons3 imgWidHeight"
}, {
  headingBoldEng: "How",
  headingBoldHindi: "कैसे",
  headingEng: "can you write a good 'About Me'",
  headingHindi: "आप इसे अच्छा और उचित लिख सकते हैं?",
  subheadingEng1: " You can write about the ",
  subheadingEngstrong: " kind of partner ",
  subheadingEng2: " you are looking for",
  exampleTextEnglish: "View Samples",
  subheadingHindi1: "आप ",
  subheadingHindistrong: " किस प्रकार के साथी ",
  subheadingHindi2: " की तलाश में हैं।",
  exampleTextHindi: "उदाहरण देखें",
  cardBody: "vc_icons4 imgWidHeight"
}, {
  headingEng0: "Here are some",
  headingHindi0: " कुछ ",
  headingBoldEng: "samples",
  headingBoldHindi: " उदाहरण",
  headingHindi: " ऐसे दिखते हैं।",
  subheadingEng1: " Writing about your ",
  subheadingEngstrong: " interests, hobbies and education ",
  subheadingHindi1: "अपने ",
  subheadingHindistrong: " रुचि और व्यवसाय ",
  subheadingHindi2: " के बारे में लिखना।",
  cardbodyDataHindi: "मैंने दिल्ली विश्वविद्यालय से इंजीनियरिंग की है और अभी मुंबई की एक कंपनी में काम कर रहा हूं। मुझे गाने सुनना और नए स्थानों पर जाना पसंद है।",
  cardbodyDataEnglish: "I am a fun-loving, warm &amp; caring person who loves to cook and explore new places. I have done my graduation from Delhi University and currently working as Technical Lead at a MNC in Mumbai."
}, {
  headingEng0: "Here are some",
  headingHindi0: " कुछ ",
  headingBoldEng: "samples",
  headingBoldHindi: " उदाहरण",
  headingHindi: " ऐसे दिखते हैं।",
  subheadingEng1: " Writing about your ",
  subheadingEngstrong: " partner preference ",
  subheadingHindi1: "अपने",
  subheadingHindistrong: " साथी ",
  subheadingHindi2: " के बारे में लिखना।",
  cardbodyDataHindi: "मैं एक भरोसेमंद साथी की तलाश में हूं जो दिल्ली के एक अच्छे परिवार से संबंधित हो और जीवन भर मेरा और मेरे परिवार का साथ निभाय।",
  cardbodyDataEnglish: "I am looking for an open-minded person who can be a dependable and caring partner preferably belonging to a well-established family in Delhi."
}, {
  headingEng0: "Here are some",
  headingHindi0: " कुछ ",
  headingBoldEng: "samples",
  headingBoldHindi: " उदाहरण",
  headingHindi: " ऐसे दिखते हैं।",
  subheadingEng1: " You can laso write it as a ",
  subheadingEngstrong: " regular text ",
  subheadingEng2: " you are looking for",
  subheadingHindi1: "आप",
  subheadingHindistrong: "सामान्य भाषा",
  subheadingHindi2: " में भी लिख सकते हैं।",
  cardbodyDataHindi: "Main Delhi ka rehne wala hu. Maine apni padayi Delhi University se ki hai aur abhi apna business chalata hai. Mujhe nayi jagah ghumna and movie dekhna pasand hai.",
  cardbodyDataEnglish: "Main Delhi ka rehne wala hu. Maine apni padayi Delhi University se ki hai aur abhi apna business chalata hai. Mujhe nayi jagah ghumna and movie dekhna pasand hai."
}];