export const regPage1Fields = {
  'reg[_csrf_token]': 'a4ec6e42ea632a304661bc3b8a6180cd',
  'reg[relationship]': '',
  'reg[gender]': '',
  'reg[res_status]': '',
  'reg[dtofbirth][day]': '',
  'reg[dtofbirth][month]': '',
  'reg[dtofbirth][year]': '',
  'reg[height]': '',
  'reg[country_res]': '',
  'reg[state_res]': '',
  'reg[city_res]': '',
  'reg[pincode]': '',
  'reg[mstatus]': '',
  'reg[mtongue]': '',
  'reg[sect]': '',
  'reg[jamaat]': '',
  'reg[religion]': '',
  'reg[caste]': '',
  'reg[subcaste]': '',
  'reg[edu_level_new]': '',
  'reg[employed_in]':'',
  'reg[occupation]': '',
  'reg[income]': '',
  'reg[email]': '',
  'reg[displayname]': '',
  'reg[password]': '',
  'reg[phone_mob][isd]': '',
  'reg[phone_mob][mobile]': '',
  'reg[havechild]': '',
  'reg[trackingParams]': '',
  'reg[pg_college]': '',
  'reg[degree_pg]': '',
  'reg[college]': '',
  'reg[degree_ug]': '',
  'reg[other_pg_degree]': '',
  'reg[other_ug_degree]': '',
  'reg[name_of_user]': '',
  'reg[casteNoBar]': '',
  'reg[horoscope_match]': ''
};
export const regPage2Fields = {
  'reg[_csrf_token]': 'a4ec6e42ea632a304661bc3b8a6180cd',
  'reg[trackingParams]': '',
  'reg[trackingYourInfo]': '',
  'reg[yourinfo]': ''
};
export const regPage3Fields = {
  'reg[_csrf_token]': 'a4ec6e42ea632a304661bc3b8a6180cd',
  'reg[gothra]': '',
  'reg[t_sister]': '',
  'reg[m_sister]': '',
  'reg[t_brother]': '',
  'reg[m_brother]': '',
  'reg[family_back]': '',
  'reg[mother_occ]': '',
  'reg[family_status]': '',
  'reg[family_type]': '',
  'reg[family_values]': '',
  'reg[familyinfo]': '',
  'reg[family_income]': '',
  'reg[native_country]': '',
  'reg[native_state]': '',
  'reg[native_city]': '',
  'reg[ancestral_origin]': '',
  'reg[trackingParams]': ''
};

export const incompleteAboutMe = {
  'editFieldArr[YOURINFO]': ''
};

export const regPage1FieldsMapUd = {
  'relationship': 'reg[relationship]',
  'gender': 'reg[gender]',
  'res_status': 'reg[res_status]',
  'dtofbirth_day': 'reg[dtofbirth][day]',
  'dtofbirth_month': 'reg[dtofbirth][month]',
  'dtofbirth_year': 'reg[dtofbirth][year]',
  'height': 'reg[height]',
  'country_res': 'reg[country_res]',
  'state_res': 'reg[state_res]',
  'city_res': 'reg[city_res]',
  'pincode': 'reg[pincode]',
  'mstatus': 'reg[mstatus]',
  'mtongue': 'reg[mtongue]',
  'sect': 'reg[sect]',
  'jamaat': 'reg[jamaat]',
  'religion': 'reg[religion]',
  'caste': 'reg[caste]',
  'subcaste': 'reg[subcaste]',
  'edu_level_new': 'reg[edu_level_new]',
  'employed_in':'reg[employed_in]',
  'occupation': 'reg[occupation]',
  'income': 'reg[income]',
  'email': 'reg[email]',
  'displayname': 'reg[displayname]',
  'password': 'reg[password]',
  'phone_mob': 'reg[phone_mob][mobile]',
  'havechild': 'reg[havechild]',
  // 'reg[trackingParams]': '',
  'pg_college': 'reg[pg_college]',
  'degree_pg': 'reg[degree_pg]',
  'college': 'reg[college]',
  'degree_ug': 'reg[degree_ug]',
  // 'reg[other_pg_degree]': '',
  // 'reg[other_ug_degree]': '',
  'name_of_user': 'reg[name_of_user]',
  'casteNoBar': 'reg[casteNoBar]',
  'horoscope_match': 'reg[horoscope_match]'
}

export const regPage3FieldsMapUd = {
  // 'reg[_csrf_token]': 'a4ec6e42ea632a304661bc3b8a6180cd',
  'gothra':'reg[gothra]',
  't_sister':'reg[t_sister]',
  'm_sister':'reg[m_sister]',
  't_brother':'reg[t_brother]',
  'm_brother':'reg[m_brother]',
  'family_back':'reg[family_back]',
  'mother_occ':'reg[mother_occ]',
  'family_status':'reg[family_status]',
  'family_type':'reg[family_type]',
  'family_values':'reg[family_values]',
  'familyinfo':'reg[familyinfo]',
  'family_income':'reg[family_income]',
  'native_country':'reg[native_country]',
  'native_state':'reg[native_state]',
  'native_city':'reg[native_city]',
  'ancestral_origin':'reg[ancestral_origin]',
  // 'reg[trackingParams]': ''
};

export const latestTrackParams = {
  "domain": "",
  "newsource": "",
  "tieup_source": "",
  "source": "",
  "adnetwork1": "",
  "adnetwork": "",
  "account": "",
  "campaign": "",
  "adgroup": "",
  "keyword": "",
  "match": "",
  "lmd": "",
  "reg_comp_frm_ggl": "",
  "reg_comp_frm_ggl_nri": "",
  "groupname": "",
  "secondary_source": ""
};