const errorStatements = {
  "GENDER": "Gender is missing",
  "HEIGHT": "Height is missing",
  "COUNTRY_RES": "Country is missing",
  "STATE_RES": "State and City is missing",
  "CITY_RES": "City is missing",
  "RESIDENTIAL_STATUS": "Residential status is missing",
  "MERITAL_STATUS": "Marital status is missing",
  "MOTHER_TONGUE": "Mother tongue is missing",
  "RELIGION_CASTE": "Religion caste is missing",
  "MARRIED_MUSLIM": "Choose married only for muslim male",
  "DOB_ERROR_0": "Date of birth is missing",
  "DOB_ERROR_1": "Provide valid date of birth",
  "DOB_ERROR_2": "Profile should be at least 18 years old to register",
  "DOB_ERROR_3": "Profile should be at least 21 years old to register",
  "PINCODE_ERROR_1": "Provide valid pincode",
  "PINCODE_ERROR_2": "Provide an area pincode",
  "HIGHEST_EDUCATION": "Highest qualification is missing",
  "EMPLOYED_IN": "Employed in is missing",
  "WORK_AREA": "Occupation is missing",
  "INCOME": "Annual income is missing",
  "FULL_NAME_ERROR_1": "Provide both firstname & surname",
  "FULL_NAME_ERROR_2": "Full Name is missing",
  "FULL_NAME_ERROR_3": "Please provide valid Full Name",

  "EMAIL_REQUIRED": "Email is missing",
  "EMAIL_NOT_NUMBER": "Please provide email in the valid format: example@gmail.com",
  "EMAIL_NO_SPACES": "Please remove spaces from the email",
  "EMAIL_NO_AT": "Please include an '@' in the email address",
  "EMAIL_MUL_AT": "Please include single '@' in the email address",
  "EMAIL_INVALID": "Please check & provide a valid email",
  "EMAIL_INVALID_DOMAIN": "Please change the domain",
  "EMAIL_INVALID_DOMAIN_2": "Please check the domain in email i.e text after '@'",
  "EMAIL_EXIST": "An account with this Email already exists",

  "PASSWORD_REQUIRED": "Password is missing",
  "PASSWORD_NUMERIC":"Your password should also contain letters (a-z)",
  "PASSWORD_INVALID": "Use 8 or more characters for your password",
  "PASSWORD_COMMON": "Password chosen is not secure",
  "MOBILE_REQUIRED": "Mobile number is missing",
  "MOBILE_INVALID": "Provide a valid mobile number",
  "ISD_REQUIRED": "ISD code is missing",
  "ISD_INVALID": "Provide a valid ISD code",
  "ABOUT_ME_TEXT": "Please fill atleast 100 characters",
  "SOMETHING_WRONG": "Something went wrong. Please try again later",
  "REGISTRATION_COMPLETE": "Registration Complete",
  "PRIVACY_HELP":"You will be able to manage who views your contact details",
  "PASSWORD_HELP":"Use 8 or more characters with a mix of letters(a-z) & numbers(0-9)"
};

export default errorStatements;