all:
  addBookmark:
    enable_login:  off
  ignoreProfile:
    enable_login:  off
  undoIgnoreProfile:
    enable_login:  off
  smsDownloadAndroidApp:
    enable_login:  off
  appPromotionDesktop:
    enable_login:  off
  resetPassword:
    enable_login:  off
    enable_google_analytics:  off
  updatePassword:
    enable_login:  off
  sendPasswordResetLink:
    enable_login:  off
  requestCallBack:
   enable_login:  off
  requestCallBackJSMS:
   enable_login:  off
  LogOut:
   enable_login:  off
  SendAppLink :
   enable_login:  off
  ApiVerificationDataV1:
   enable_login:  off
  ApiRequestCallbackV1:
   enable_login:  off
  MatchOtp:
   enable_login:  off
  SendOtpSMS:
   enable_login:  off

