forwardProfileLayerSuccess:
has_layout: false

appPromotionDesktopSuccess:
javascripts: [-phoneVerify_js@commonBottom]

_helpWidget:
 has_layout:  false

_jsmsReqCallback:
 has_layout:  false 

_notificationLayerJsms:
 has_layout:  false 

jspcLogoutSuccess:
  metas:
    verify-v1: y8P0QEbZI8rd6ckhDc6mIedNE4mlDMVDFD2MuWjjW9M=
    title: Matrimony, Marriage, Matrimonial Sites, Match Making, Matrimonials
    description: Most trusted Indian matrimonial website. Lakhs of verified matrimony profiles. Search by caste and community. Register now for FREE at Jeevansathi.com
    keywords: matrimony, marriage, matrimonial, matrimonial sites, match making, matrimony sites, matrimony services, matrimonial sites India, matrimonial com, matrimonial websites, bridegroom, Online Matrimonials, Indian matrimonial sites, matrimonial India, marriage sites, Indian Matrimonial, marriage websites, marriage sites in India, free matrimonial site
    robots: noodp,noydir
  stylesheets: [-*,jspc/common/headerFooterJspc_css,jspc/common/fontsJspc_css,jspc/common/commonJspc_css,jspc/logout/homecss]
  javascripts: [-*,jspc/common/hslider,jspc/common/test1,jspc/logout/hpjs]
  layout: jspcLayout

verifyLayerSuccess:
  stylesheets: [-*]
  javascripts: [-*]

failedLayerSuccess:
  stylesheets: [-*]
  javascripts: [-*]

successLayerSuccess:
  stylesheets: [-*]
  javascripts: [-*]

requestCallBackJSMSSuccess:
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*]
  layout: jsmsMobLayout

resetPasswordSuccess:
  javascripts: [jspc/settings/settings,jspc/settings/jspc_visibility,jspc/login/resetPassword_js]
  stylesheets: [jspc/settings/settings]
  layout: jspcLayout

CALJSMSSuccess:
  stylesheets: [-*,jsms/common/commoncss,jsms/myjs/CALJSMS_css]
  javascripts: [-*,jsms/myjs/CALJSMS_js]
  layout: jsmsMobLayout

_notificationLayerJSPC:
 has_layout:  false 
