use PROFILE;
CREATE TABLE `VOA_TRACKING` (
`PROFILEID` INT( 11 ) NOT NULL ,
`CHANGE_DATE` DATETIME NOT NULL ,
PRIMARY KEY ( `PROFILEID` )
);
use MIS;
CREATE TABLE LOGIN_TRACKING_OLDPROFILES (
  PROFILEID int(11) NOT NULL,
  LOGIN_DATE datetime NOT NULL,
  PRIMARY KEY (PROFILEID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;