<?
class IdToAppImagesMapping
{
	//search
	CONST EVALUE_SRP      		= 'evalue';
	CONST ERISHTA_SRP     		= 'erishta';
	CONST TICK_CONTACT    		= '008';
	CONST DISABLE_CONTACT 		= '035';
	CONST ENABLE_CONTACT  		= '001';
	CONST INCOMPLETE      		= '013';
	CONST NOT_VISIBLE			= '012';
	CONST PHONE_NOT_VERIFIED 	= '015';
	CONST SAME_GENDER     		= '017';
	CONST UNDERSCREENING  		= '016';
	CONST SHORTLISTBUTTON 		= '003';
	CONST SHORTLISTEDBUTTON		= '004';
	CONST CONTACTDETAILBUTTON	= '007';
	CONST ACCEPT 				= '085';
	CONST PHONEICON 			= '018';
	CONST MAILICON 				= '020';
	CONST DECLINE				= '088';
	CONST MESSAGE				= '086';
        CONST SEND_REMINDER		= '083';
        CONST REMINDER_SENT		= '087';
	CONST CANCEL_INTEREST           = '084';
	CONST ALBUM					= '005'; 
	CONST DISABLE_ALBUM			= '036';
	CONST MALE_ALBUM			= '006'; 
	CONST DISABLE_MALE_ALBUM	= '037';
	CONST IGNORE			= 'ignore';
	CONST UNDO_IGNORE		= 'uignore';
	CONST A_IGNORE			= '84';
	CONST A_UNDO_IGNORE		= '90';
	CONST REPORTABUSE 		= '021' ;
	CONST EADVANTAGE_SRP 	='eadvantage';
}
