<div class="terms_condition lf extracss" >
<p class="content">Jeevansathi.com is a division of Info Edge (I) Ltd. It is an online matrimonial portal endeavoring constantly to provide you with premium matrimonial services. Since we are strongly committed to your right to privacy, we have drawn have a privacy statement in place with regard to the information we collect from you.</p>
<p class="content"> We use a secure server for credit card transactions to protect the credit card information of our clients and Cookies are used to store the login information. </p>
<p class="content"><span class="b">1. What information does Jeevansathi.com collect from you?</span><br> We gather information from members and guests who apply for the various services our site offers. It includes, but may not be limited to, email address, first name, last name, a user-specified password, e-mail Id, mailing address, zip code and telephone number. Jeevansathi shall act on the basis of the information that is being provided by you, believing the same to be true and accurate. We assume the details provided are genuine and under your express consent even if they are being submitted by your family, friends, relatives or a third party on your behalf. By submitting your details, you agree to share your information with other members on Jeevansathi. Jeevansathi is under no obligation to verify the accuracy or genuineness of the information submitted by you. Any complaints arising in this regard will be your responsibility. </p>
<p class="content"> <span class="b">2. With whom the site shares the information it collects/tracks?</span><br> The information collected from our clients is shared only with members of JS or members of our partners. Any information you give us is held with the utmost care and security. We are also bound to cooperate fully should a situation arise where we are required by law or legal process to provide information about a customer. </p>
<p class="content"><span class="b">3. Do all visitors have to pay?</span><br> NO, All visitors to our site may browse the site, search the ads and view any articles or features our site has to offer without entering any personal information or paying money. </p>
<p class="content"><span class="b">4. How Jeevansathi.com team can contact you ?</span><br>The Jeevansathi.com team will contact you from time to time to apprise you on various features and functionalities of the website. They will contact you for either "Service" or "Sales" through a variety of mediums like Email, SMS, MMS, Voice IVR, USSD, WAP messages, Telephonic Calls etc. The calls made to you will be from a regular Mobile or Landline number which is not of the "140" series. </p>
<p class="content gray"> <span class="b">Notice:</span> We may change this Privacy Policy from time to time based on your comments or as a result of a change of policy in our company. If you have any questions regarding our Privacy Statement, please write in to webmaster@jeevansathi.com </p>
&nbsp;</div>
