storySuccess:
  metas:
    title:        Success Story - Matrimonial Success Stories - Matrimony Testimonials
    keywords:     Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services, online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    description:    Read the matrimonial success stories and testimonials of Jeevansathi.com users. Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
  stylesheets:    [success_story_css,jslider,style_search,search_popup_screens]

  javascripts:    [ loginSearch@bottom,sstory_js,mini_reg_js]

jspcStorySuccess:
  metas:
    title:        Success Story - Matrimonial Success Stories - Matrimony Testimonials
    keywords:     Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services, online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    description:    Read the matrimonial success stories and testimonials of Jeevansathi.com users. Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
  javascripts:    [jsms/membership/jquery_sly@bottom,jspc/success_story/imagefit@bottom,jspc/success_story/foggy@bottom,jspc/success_story/resizeIe@bottom]

  stylesheets:    [jspc/success_story/successStory]
  layout: jspcLayout

jspcCompletestorySuccess:
  metas:
    title:        Success Story - Matrimonial Success Stories - Matrimony Testimonials
    keywords:     Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services, online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    description:    Read the matrimonial success stories and testimonials of Jeevansathi.com users. Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
  javascripts:    [jsms/membership/jquery_sly@bottom,jspc/success_story/imagefit@bottom,jspc/success_story/successScroll@bottom,jspc/success_story/foggy@bottom,jspc/success_story/resizeIe@bottom]

  stylesheets:    [jspc/success_story/successStory]
  layout: jspcLayout

jspcLayerSuccess:
  metas:
    title:        Success Story - Matrimonial Success Stories - Matrimony Testimonials
    keywords:     Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services, online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    description:    Read the matrimonial success stories and testimonials of Jeevansathi.com users. Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
  javascripts:    [jsms/membership/jquery_sly@bottom,jspc/success_story/imagefit@bottom,jspc/success_story/foggy@bottom,jspc/success_story/resizeIe@bottom,jspc/utility/chosen/chosen_jquery@bottom,jspc/utility/chosen/docsupport/prism@bottom,jspc/success_story/jqueryFilestyle@bottom]

  stylesheets:    [jspc/utility/chosen/chosen_css,jspc/success_story/successStory]
  layout: jspcLayout

morestorySuccess:
  metas:
     title:        Success Story - Matrimonial Success Stories - Matrimony Testimonials
     keywords:	  Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services, online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified .
     description:	  Read the matrimonial success stories and testimonials of Jeevansathi.com users. Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
  stylesheets:    [success_story_css,jslider,style_search,search_popup_screens]

  javascripts:    [ loginSearch@bottom,sstory_js,mini_reg_js]

completestorySuccess:
  metas:
     title:        Success Story - Matrimonial Success Stories - Matrimony Testimonials
     keywords:    Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services, online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified .
     description:         Read the matrimonial success stories and testimonials of Jeevansathi.com users. Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
  stylesheets:    [success_story_css,jslider,style_search,search_popup_screens]

  javascripts:    [ loginSearch@bottom,sstory_js,mini_reg_js]

jsmsInputStorySuccess:
  metas:
    title:        Success Story - Matrimonial Success Stories - Matrimony Testimonials
    keywords:     Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services, online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    description:    Read the matrimonial success stories and testimonials of Jeevansathi.com users. Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
  stylesheets: [-*]
  javascripts: [-*]
  layout: jsmsMobLayout

jsmsSkipDeleteSuccess:
  metas:
    title:        Delete Profile
    keywords:     Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services, online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    description:    Read the matrimonial success stories and testimonials of Jeevansathi.com users. Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
  stylesheets: [-*]
  javascripts: [-*,jsms/settings/mobDeleteProfile_js]
  layout: jsmsMobLayout

jsmsSelectImageSuccess:
  metas:
    title:        Success Story - Matrimonial Success Stories - Matrimony Testimonials
    keywords:     Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services, online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    description:    Read the matrimonial success stories and testimonials of Jeevansathi.com users. Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
  stylesheets: [-*]
  javascripts: [-*]
  layout: jsmsMobLayout
