# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App
# default values
all:
  whichMachine:  'local'
  tout: 14400
  screentime: 12
  allot_time: 30 #minutes
  SITE_URL:  "<?php echo JsConstants::$siteUrl?>"
  IMG_URL:  "<?php echo JsConstants::$imgUrl?>"
  PHOTO_URL:  "<?php echo JsConstants::$unscreenedPhotoUrl?>"
  SCREENED_PHOTO_URL: "<?php echo JsConstants::$screenedPhotosUrl?>"
  screened_dir_path: "<?php echo JsConstants::$screenedPhotoDir?>"
  max_photo_size_screen: 500000
  max_photo_size: 6
  max_no_of_photos: 20
  photo_formats: 'Jpeg, Gif, Jpg'
  ftp_username: "<?php echo JsConstants::$ftpUsername?>"
  ftp_password: "<?php echo JsConstants::$ftpPassword?>"
  ftp_host: "<?php echo JsConstants::$ftpHost?>"
  .array:
        photo_formats_to_check: ["image/jpg","image/jpeg","image/gif","image/JPG","image/JPEG","image/GIF","image/pjpeg","image/PJPEG"]
        social_keywords: ["My photo", "My family", "My friends", "My office", "My home", "Others"]
  wkhtmltopdf: 'lib/utils/wkhtmltopdf-i386' 
  pdffolder: '/tmp'
