addPhotosSuccess:
  metas:
    title:        Import or Upload photos – Jeevansathi.com

  stylesheets:    [jspc/photoUpload/photoup_css,jspc/photoUpload/cropper,jspc/photoUpload/main]
  javascripts:    [jspc/common/searchDropdown_js@bottom,jspc/photoUpload/photoUpload_js,jspc/photoUpload/addPhoto_js,jspc/photoUpload/compUpload_js,jspc/photoUpload/photoFunctions_js,jspc/photoUpload/cropper@bottom,jspc/photoUpload/main@bottom, jspc/photoUpload/bootstrap@bottom, jspc/photoUpload/tooltip@bottom,jspc/common/AjaxWrapper,jspc/photoUpload/importPhotoAlbum_js]
  layout: jspcLayout

photoPrivacyLayerSuccess:
  metas:
    title:        Jeevansathi.com

  stylesheets:    []

  javascripts:    []

albumSuccess:
  metas:
    title:        My photos - Jeevansathi.com

  stylesheets:    [js_photo_studio_style, slider-small]
  robots: noindex,nofollow

newAlbumSuccess:
   has_layout: false

photoRequestSuccess:
   has_layout: false

viewAllPhotosSuccess:
  metas:
    title:        My photos - Jeevansathi.com

  stylesheets:    [js_photo_studio_style, slider-small]

  javascripts:    [photo_slider@bottom, displayFullImage@bottom, saveDetails@bottom, ajax_social@bottom]

profileLayerSuccess:
  metas:
    title:        

  stylesheets:    [profile_layer, cropper_css]

  javascripts:    [cropper_js, profileLayer, ajax_social]

compUploadSuccess:
  metas:
    title:        Select photos to upload - Jeevansathi.com

  stylesheets:    [js_photo_studio_style]

  javascripts:    [compUpload_js]

compUploadFrameSuccess:
  metas:
    title:        Select photos to upload - Jeevansathi.com

  stylesheets:    [js_photo_studio_style, upload]

  javascripts:    [mootools-core-1-3-2-full-compat@bottom, Swiff_Uploader@bottom, Fx_ProgressBar@bottom, FancyUpload2@bottom, onload@bottom, ajax_social@bottom]

compUploadNoFlashSuccess:
  metas:
    title:        Select photos to upload - Jeevansathi.com

  stylesheets:    [js_photo_studio_style, upload]

  javascripts:    [compUploadNoFlash_js@bottom]

importPermissionSuccess:
  metas:
    title:        Import Photos – Jeevansathi.com

  stylesheets:    [js_photo_studio_style]


importAlbumsSuccess:
  metas:
    title:        Select Album to Import – Jeevansathi.com

  stylesheets:    [js_photo_studio_style]

  javascripts:    []

importPhotosSuccess:
  metas:
    title:        Select Photos to import – Jeevansathi.com

  stylesheets:    [js_photo_studio_style, importPhotos]

  javascripts:    []

saveImageSuccess:
  metas:
    title:        Select profile picture, add title and keywords – Jeevansathi.com

  stylesheets:    [js_photo_studio_style]

  javascripts:    [saveDetails@bottom, ajax_social@bottom]

sliderSuccess:
  metas:
    title:        Import or Upload photos – Jeevansathi.com

  stylesheets:    [js_photo_studio_style, slider-small, fto_css]

  javascripts:    [photo_slider@bottom, ajax_social@bottom]

importFailedSuccess:
  metas:
    title:        Import failed – Jeevansathi.com

  stylesheets:    [js_photo_studio_style]

  javascripts:    []

deleteLayerSuccess:
  metas:
    title:        

  stylesheets:    [profile_layer]

  javascripts:    [saveDetails@bottom]

loadingLayerSuccess:
  metas:
    title:       

  stylesheets:    [js_photo_studio_style]

  javascripts:    []

mobileAlbumSuccess:
  metas:
    title:     View Album-Jeevansathi
  stylesheets: [photoAlbumMobile]
  javascripts: [jquery_touch, mobAlbum@bottom]
  layout: mobRegLayout

mobilePhotoRequestSuccess:
  metas:
    title:     Photo Request-Jeevansathi
  stylesheets: [photoAlbumMobile]
  javascripts: [jquery_touch, mobAlbum@bottom]
  layout: mobRegLayout
  
mobilePhotoAlbumSuccess:
  metas:
    title: Album Page
    viewport: width=device-width, initial-scale=1, maximum-scale=1, , initial-scale=1.0
  stylesheets: [jsms/photo/photoswipe,jsms/common/commoncss,jsms/common/mediaquery,jsms/photo/photoup,jsms/common/errorBar,jsms/common/disableRightClick_css]
  javascripts: [jsms/photo/mobPhotoAlbum_panzoom,jsms/photo/mobPhotoAlbum_photoSwipeInheritence,jsms/photo/mobPhotoAlbum_photoswipe,jsms/photo/mobPhotoUploadCommon_js,jsms/photo/mobPhotoAlbum_v1@bottom,jsms/common/CommonFunctions,jsms/common/disableRightClick_js]
  layout: newPhotoAlbumLayout

mobileUploadActionSuccess:
  metas: 
    title:     Photo Upload-Jeevansathi
    viewport:  width=device-width, initial-scale=1, maximum-scale=1, , initial-scale=1.0    
  stylesheets: []
  javascripts: [mobPhotoUpload]
  layout: mobRegLayout
  
mobilePhotoUploadProgressSuccess:
  metas:
    title:     Photo Upload-Jeevansathi
    viewport:   width=device-width, initial-scale=1, maximum-scale=1, , initial-scale=1.0
  stylesheets: [jsms/common/commoncss, jsms/common/mediaquery, jsms/photo/photoup, jsms/common/errorBar]
  javascripts: [jsms/photo/mobPhotoUpload_v1@bottom, jsms/photo/mobPhotoUploadCommon_js, jsms/photo/photo_upload_js,jsms/photo/photo_privacy_js, jsms/common/CommonFunctions]
  layout: newPhotoAlbumLayout
