performSuccess:
  metas:
    title:        Search Matrimonial Profile - Find Matrimony Profile - Jeevansathi.com
    robots: noindex,nofollow
  stylesheets:    [jslider,style_search,search_popup_screens, contactEngine_css]

  javascripts:    [jshashtable_src@bottom,tmpl@bottom,jquery-dependClass@bottom,draggable@bottom,jquery-slider@bottom,searchPage_js@bottom, mini_reg_js@bottom, loginSearch@bottom,json2@bottom,contactEngineLayer_js@bottom,albumLayer_js@bottom]

mobileSearchSuccess:
  metas:
    title:        Jeevansathi.com Search
    robots: noindex,nofollow
  stylesheets: [mobile_media_css,styles_css,photoRequest]
  javascripts: [tracking_js]
  layout: mobRegLayout
  
mobileSearchBandSuccess:
  metas:
    title:        Jeevansathi.com
  stylesheets: []
  javascripts: [mobSearchBand,tracking_js]
  layout: mobRegLayout

#jsms/search/mobSearchDropDown_js added by tanu to prevent error
searchSuccess:
  metas:
    title:        Search Matrimonial Profile - Find Matrimony Profile - Jeevansathi.com
    robots: noindex,nofollow
  stylesheets: [jspc/search/srpcss,jspc/search/rangeslider,jspc/common/jquerymCustomScrollbar,jspc/search/searchBand,jspc/contactEngine/contactEngine_css,jspc/common/NProgress,jspc/common/3DotLoader]
  javascripts: [jspc/search/hslider@bottom,jspc/search/test1@bottom,jspc/search/searchTuples@bottom,jspc/search/searchCommon_js@bottom,jspc/common/photoAlbum@bottom,jspc/search/saveSearch@bottom,jspc/search/relaxCriteria@bottom,jspc/search/search@bottom,jspc/search/searchClusters@bottom,jspc/photo/photoRequest_js@bottom,jspc/common/jquerymCustomScrollbarConcat@bottom,jspc/search/searchDropdowns@bottom,jspc/search/searchBand@bottom,jspc/search/common/commonSlider@bottom,jspc/search/searchSliders@bottom,jspc/search/common/ionRangeSliderPlugin@bottom,jspc/contactEngine/contactEngine@bottom,jspc/contactEngine/contactEngineButtons@bottom,jspc/common/nano]
  layout: jspcLayout

#jsms/search/mobSearchDropDown_js added by tanu to prevent error
MobSearchSuccess:
  metas:
    title:        Jeevansathi.com
  stylesheets: [-*,jsms/search/srpcss,jsms/contact_engine/contactEngine,jsms/hamburger/ham_css,jsms/search/savesearchcss,jsms/common/verificationIcon_css,jsms/common/disableRightClick_css]
  javascripts: [-*,jsms/search/MobileSearchCommon,jsms/photo/photoRequestCommon_js,jsms/search/jqueryInfiniteScroll,jsms/search/JsmsSearch,jsms/search/relaxCriteria_v1@bottom,jsms/contact_engine/contactEngine_js,jsms/search/inview,jsms/hamburger/ham_js@bottom, jsms/utility/sessionStorage_js@bottom, jsms/search/viewSimilarMax@bottom,jsms/search/overlayLayerJsms@bottom,jsms/search/savesearch_js@bottom,jsms/common/verificationIcon_js,jsms/common/disableRightClick_js]
  layout: jsmsMobLayout
  
 #jsms/search/mobSearchDropDown_js added by tanu to prevent error
MobSimilarProfilesSuccess:
  metas:
    title:        Jeevansathi.com
  stylesheets: [-*,jsms/search/srpcss,jsms/contact_engine/contactEngine,jsms/hamburger/ham_css]
  javascripts: [-*,jsms/search/MobileSearchCommon,jsms/photo/photoRequestCommon_js,jsms/search/jqueryInfiniteScroll,jsms/search/JsmsSearch,jsms/search/relaxCriteria_v1@bottom,jsms/contact_engine/contactEngine_js,jsms/search/inview,jsms/hamburger/ham_js@bottom]
  layout: jsmsMobLayout
  
moreClusterLayerSuccess:
  has_layout: false
  
viewSimilarProfileSuccess:
  metas:
    title:        jeevansathi.com
  stylesheets:    [jslider,style_search,search_popup_screens, contactEngine_css, view_similar_profile_css]
  javascripts:    [jshashtable_src@bottom,tmpl@bottom,jquery-dependClass@bottom,draggable@bottom,jquery-slider@bottom,searchPage_js@bottom, mini_reg_js@bottom, loginSearch@bottom,json2@bottom,contactEngineLayer_js@bottom,albumLayer_js@bottom,view_similar_profile_js]
 
MobTopSearchBandSuccess:
  metas:
    title:        Jeevansathi.com
  javascripts: [-*,jsms/search/mobSearchForm_js,jsms/search/mobSearchDropDown_js,jsms/hamburger/ham_js@bottom,jsms/search/savesearch_js@bottom,jsms/search/overlayLayerJsms@bottom]
  stylesheets: [-*,jsms/hamburger/ham_css,jsms/search/searchform_css,jsms/search/searchdropdown,jsms/search/savesearchcss]
  layout: jsmsMobLayout

searchByProfileIdSuccess:
  metas:
    title:        jeevansathi.com
  stylesheets:    [-*]
  javascripts:    [-*,jsms/search/searchByProfileId_js]
  layout: jsmsMobLayout
MobSaveSearchSuccess:
  metas:
    title:        Jeevansathi.com
  javascripts: [-*,jsms/hamburger/ham_js@bottom,jsms/search/overlayLayerJsms@bottom,jsms/search/savesearch_js@bottom]
  stylesheets: [-*,jsms/hamburger/ham_css,jsms/search/savesearchcss]
  layout: jsmsMobLayout


advancedSearchSuccess:
  metas:
    title:        Search Matrimonial Profile - Find Matrimony Profile - Jeevansathi.com
  stylesheets: [jspc/utility/chosen/chosen_css,jspc/search/advancedSearch,jspc/common/3DotLoader]
  javascripts: [jspc/search/hslider@bottom,jspc/utility/chosen/chosen_jquery@bottom,jspc/utility/chosen/docsupport/prism@bottom,jspc/search/advancedSearch@bottom]
  layout: jspcLayout

jspcViewSimilarProfileSuccess:
  metas:
    title:        Jeevansathi.com
  javascripts: [jspc/search/viewSimilarProfile_js@bottom,jspc/common/photoAlbum@bottom,jspc/search/searchCommon_js@bottom,jspc/photo/photoRequest_js@bottom,jspc/search/jspcSuccessStory_js@bottom,jspc/search/jspcMembershipMsg_js@bottom,jspc/success_story/resizeIe@bottom,jspc/contactEngine/contactEngine@bottom,jspc/contactEngine/contactEngineButtons@bottom,jspc/common/nano]
  stylesheets: [jspc/search/srpcss,jspc/profile/view/jspcViewProfile_css,jspc/contactEngine/contactEngine_css,jspc/common/NProgress,jspc/common/3DotLoader]
  layout: jspcLayout
