indexSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []

processInterfaceSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    [operations_validate2]


showPhotosToScreenSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    [operations_validate2]

showAppPhotoScreeningInterfaceSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    [operations_validate2]

markPhotosForScreeningSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []

getUsernameSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []

showDeletedPlusOriginalPhotosSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []

deleteCommentsSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []

skipCommentsSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []

skipProfileSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []

outputTemplateSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []

albumSuccess:
  metas:
    title:        Import or Upload photos – Jeevansathi.com

  stylesheets:    [common_css, colorbox_css]

  javascripts:    []

avgProcessingTimeQueue2Success:
   metas:
      title:	  MIS-Jeevansathi.com 
      stylesheets:	 [operations_jeevansathi]
      javascripts: 	 []

avgProcessingTimeQueueSuccess :
   metas:
      title:	  MIS-Jeevansathi.com 
      stylesheets:	 [operations_jeevansathi]
      javascripts: 	 []
