<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/09/26 08:29:26
sfConfig::add(array(
  'mod_homepage_enabled' => true,
  'mod_homepage_view_class' => 'sfSmarty',
  'mod_homepage_is_internal' => false,
  'mod_homepage_partial_view_class' => 'sfSmarty',
  'mod_homepage_default_LoggedInProfile' => 'PROFILEID,GENDER,EMAIL,USERNAME,SUBSCRIPTION,ACTIVATED,HAVEPHOTO,MOB_STATUS,LANDL_STATUS,INCOMPLETE,PHOTO_DISPLAY,GENDER,PRIVACY,HAVE_JCONTACT',
  'mod_homepage_index_enable_login' => 'off',
  'mod_homepage_loginValidation_enable_login' => 'off',
  'mod_homepage_searchByProfileidValidation_enable_login' => 'off',
));
