<?php
include("connect.inc");
$db=connect_misdb();
$db2=connect_master();

if(authenticated($cid))
{
	if($Submit)
	{
                $smarty->assign("flag",1);
                $mmarr=array('Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar');
                for($i=0;$i<31;$i++)
                {
                        $ddarr[$i]=$i+1;
                }
                $st_date=$year."-".$month."-01";
                $end_date=$year."-".$month."-31 23:59:59";
		$j=0;
		$sql1="SELECT COUNT(*) cnt,DAYOFMONTH(REPLY_DT) as dd,REPLYBY FROM feedback.TICKET_MESSAGES WHERE REPLY_DT BETWEEN '$st_date' AND '$end_date' GROUP BY REPLYBY,dd";
		$res1=mysql_query_decide($sql1,$db) or die("$sql1".mysql_error_js($db));
		$grandtotal=0;
		while($row1=mysql_fetch_array($res1))
		{
			if(is_array($replyby))
			{
				if(!in_array($row1['REPLYBY'],$replyby))
				{
					$replyby[]=$row1['REPLYBY'];
					$j++;
				}
			}
			else
			{
				$replyby[]=$row1['REPLYBY'];
				$j++;
			}
			$count[$j-1][$row1['dd']-1]['REPLYCOUNT']=$row1['cnt'];
			$totala[$j-1]+=$row1['cnt'];
			$totalb[$row1['dd']-1]+=$row1['cnt'];
			$grandtotal+=$row1['cnt'];
		}
		$smarty->assign('grandtotal',$grandtotal);
		$smarty->assign('totalb',$totalb);
		$smarty->assign('totala',$totala);
                $smarty->assign("count",$count);
                $smarty->assign("replyby",$replyby);
                $smarty->assign("ddarr",$ddarr);
                $smarty->assign("year",$year);
                $smarty->assign("month",$month);
                $smarty->assign("cid",$cid);
		$smarty->display("faq_reply.htm");		
	}
	else
	{
                for($i=0;$i<12;$i++)
                {
                        $mmarr[$i]=$i+1;
                }

                for($i=2004;$i<=date("Y");$i++)
{
        $yyarr[$i-2004]=$i;
}

                $smarty->assign("mmarr",$mmarr);
                $smarty->assign("yyarr",$yyarr);
                $smarty->assign("cid",$cid);
                $smarty->display("faq_reply.htm");
	}
}
?>
