JSPCLandingPageSuccess:
  metas:
    title: Membership Plans - Jeevansathi.com
    keywords: Jeevansathi, membership plans, value added services, payments, eRishta, eSathi, eValue, eAdvantage, jsExclusive, callback, prices, plans, payAtBranches, cheque drop, cheque pickup, inquire, compare plans, benefits, membership
  http_metas:
    content-type: text/html

  javascripts:    [jspc/membership/jspc_mem_slider@bottom,jspc/membership/jspc_mem_js@bottom,jspc/membership/jspc_mem_sweetalert@bottom,jspc/membership/jspc_mem_scrollpane@bottom,jspc/membership/jspc_mem_mousewheel@bottom,jspc/membership/jspc_mem_select_box@bottom,jspc/membership/jspc_mem_md5@bottom,jspc/membership/upgrade_mem_js@bottom]

  stylesheets:    [jspc/membership/jspc_mem_css,jspc/membership/jspc_mem_sweetalert,jspc/membership/jspc_mem_scrollpane,jspc/membership/jspc_mem_custom_select,jspc/membership/upgrade_mem_css]
  layout: jspcLayout

JSPCVasPageSuccess:
  metas:
    title: Value Added Services - Jeevansathi.com
    keywords: Jeevansathi, membership plans, value added services, payments, eRishta, eSathi, eValue, eAdvantage, jsExclusive, callback, prices, plans, payAtBranches, cheque drop, cheque pickup, inquire, compare plans, benefits, membership
  http_metas:
    content-type: text/html

  javascripts:    [jspc/membership/jspc_mem_slider@bottom,jspc/membership/jspc_mem_js@bottom,jspc/membership/jspc_mem_sweetalert@bottom,jspc/membership/jspc_mem_scrollpane@bottom,jspc/membership/jspc_mem_mousewheel@bottom,jspc/membership/jspc_mem_select_box@bottom,jspc/membership/jspc_mem_md5@bottom]

  stylesheets:    [jspc/membership/jspc_mem_css,jspc/membership/jspc_mem_sweetalert,jspc/membership/jspc_mem_scrollpane,jspc/membership/jspc_mem_custom_select]
  layout: jspcLayout

JSPCCartPageSuccess:
  metas:
    title: Finalize Cart - Jeevansathi.com
    keywords: Jeevansathi, membership plans, value added services, payments, eRishta, eSathi, eValue, eAdvantage, jsExclusive, callback, prices, plans, payAtBranches, cheque drop, cheque pickup, inquire, compare plans, benefits, membership
  http_metas:
    content-type: text/html

  javascripts:    [jspc/membership/jspc_mem_slider@bottom,jspc/membership/jspc_mem_js@bottom,jspc/membership/jspc_mem_sweetalert@bottom,jspc/membership/jspc_mem_scrollpane@bottom,jspc/membership/jspc_mem_mousewheel@bottom,jspc/membership/jspc_mem_select_box@bottom,jspc/membership/jspc_mem_md5@bottom]

  stylesheets:    [jspc/membership/jspc_mem_css,jspc/membership/jspc_mem_sweetalert,jspc/membership/jspc_mem_scrollpane,jspc/membership/jspc_mem_custom_select]
  layout: jspcLayout

JSPCChequePickupSuccessPageSuccess:
  metas:
    title: Pickup Scheduled - Jeevansathi.com
    keywords: Jeevansathi, membership plans, value added services, payments, eRishta, eSathi, eValue, eAdvantage, jsExclusive, callback, prices, plans, payAtBranches, cheque drop, cheque pickup, inquire, compare plans, benefits, membership
  http_metas:
    content-type: text/html

  javascripts:    [jspc/membership/jspc_mem_slider@bottom,jspc/membership/jspc_mem_js@bottom,jspc/membership/jspc_mem_sweetalert@bottom,jspc/membership/jspc_mem_scrollpane@bottom,jspc/membership/jspc_mem_mousewheel@bottom,jspc/membership/jspc_mem_select_box@bottom,jspc/membership/jspc_mem_md5@bottom]

  stylesheets:    [jspc/membership/jspc_mem_css,jspc/membership/jspc_mem_sweetalert,jspc/membership/jspc_mem_scrollpane,jspc/membership/jspc_mem_custom_select]
  layout: jspcLayout

JSPCTransactionSuccessPageSuccess:
  metas:
    title: Transaction Successful - Jeevansathi.com
    keywords: Jeevansathi, membership plans, value added services, payments, eRishta, eSathi, eValue, eAdvantage, jsExclusive, callback, prices, plans, payAtBranches, cheque drop, cheque pickup, inquire, compare plans, benefits, membership
  http_metas:
    content-type: text/html

  javascripts:    [jspc/membership/jspc_mem_slider@bottom,jspc/membership/jspc_mem_js@bottom,jspc/membership/jspc_mem_sweetalert@bottom,jspc/membership/jspc_mem_scrollpane@bottom,jspc/membership/jspc_mem_mousewheel@bottom,jspc/membership/jspc_mem_select_box@bottom,jspc/membership/jspc_mem_md5@bottom]

  stylesheets:    [jspc/membership/jspc_mem_css,jspc/membership/jspc_mem_sweetalert,jspc/membership/jspc_mem_scrollpane,jspc/membership/jspc_mem_custom_select]
  layout: jspcLayout

JSPCTransactionFailurePageSuccess:
  metas:
    title: Transaction Failed - Jeevansathi.com
    keywords: Jeevansathi, membership plans, value added services, payments, eRishta, eSathi, eValue, eAdvantage, jsExclusive, callback, prices, plans, payAtBranches, cheque drop, cheque pickup, inquire, compare plans, benefits, membership
  http_metas:
    content-type: text/html

  javascripts:    [jspc/membership/jspc_mem_slider@bottom,jspc/membership/jspc_mem_js@bottom,jspc/membership/jspc_mem_sweetalert@bottom,jspc/membership/jspc_mem_scrollpane@bottom,jspc/membership/jspc_mem_mousewheel@bottom,jspc/membership/jspc_mem_select_box@bottom,jspc/membership/jspc_mem_md5@bottom]

  stylesheets:    [jspc/membership/jspc_mem_css,jspc/membership/jspc_mem_sweetalert,jspc/membership/jspc_mem_scrollpane,jspc/membership/jspc_mem_custom_select]
  layout: jspcLayout

whyJeevansathiSuccess:
  metas:
    title: Membership Plans - Jeevansathi.com
  http_metas:
    content-type: text/html

  stylesheets:    [minify , style ,content]

  has_layout:     false

mem_comparisonSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css]
  javascripts: [-*]
  layout: moblayout

mem_allPlansSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css]
  javascripts: [-*,tracking_js]
  layout: moblayout

mem_planDetailsSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css]
  javascripts: [-*,tracking_js]
  layout: moblayout

mem_addCallBackSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css]
  javascripts: [-*]
  layout: moblayout

mem_paymentOptionsSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css]
  javascripts: [-*,tracking_js]
  layout: moblayout

mem_apiPaymentRedirectSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css]
  javascripts: [-*]
  layout: moblayout

jsexclusiveDetailSuccess:
  metas:
    title: JS Exclusive
  http_metas:
    content-type: text/html
  javascripts:    [memCommonJS,jspc/membership/jspc_mem_slider@bottom,jspc/membership/jspc_mem_js@bottom,jspc/membership/jspc_mem_sweetalert@bottom,jspc/membership/jspc_mem_scrollpane@bottom,jspc/membership/jspc_mem_mousewheel@bottom,jspc/membership/jspc_mem_select_box@bottom,jspc/membership/jspc_mem_md5@bottom]

  stylesheets:    [jspc/membership/jspc_mem_css,jspc/membership/jspc_mem_sweetalert,jspc/membership/jspc_mem_scrollpane,jspc/membership/jspc_mem_custom_select,jsexclusive_style]
  layout: jspcLayout

JSMSLandingPageSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*,jsms/membership/new_revamp_mobile_membership,jsms/membership/new_revamp_mobile_payment]
  layout: jsmsMobLayout

JSMSVasPageSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*,jsms/membership/new_revamp_mobile_membership,jsms/membership/new_revamp_mobile_payment]
  layout: jsmsMobLayout

JSMSCartPageSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*,jsms/membership/new_revamp_mobile_membership,jsms/membership/new_revamp_mobile_payment]
  layout: jsmsMobLayout

JSMSCouponPageSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*,jsms/membership/new_revamp_mobile_membership,jsms/membership/new_revamp_mobile_payment]
  layout: jsmsMobLayout

JSMSPaymentOptionsPageSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*,jsms/membership/new_revamp_mobile_membership,jsms/membership/new_revamp_mobile_payment]
  layout: jsmsMobLayout

JSMSChequePickupSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*,jsms/membership/new_revamp_mobile_membership,jsms/membership/new_revamp_mobile_payment]
  layout: jsmsMobLayout

JSMSChequePickupSuccessPageSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*,jsms/membership/new_revamp_mobile_membership,jsms/membership/new_revamp_mobile_payment]
  layout: jsmsMobLayout

JSMSSuccessPageSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*,jsms/membership/new_revamp_mobile_membership,jsms/membership/new_revamp_mobile_payment]
  layout: jsmsMobLayout

JSMSFailurePageSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*,jsms/membership/new_revamp_mobile_membership,jsms/membership/new_revamp_mobile_payment]
  layout: jsmsMobLayout

JSMSPayAtBranchesPageSuccess:
  metas:
    title:  Membership Plans - Jeevansathi.com
  stylesheets: [-*,jsms/membership/new_revamp_membership_css]
  javascripts: [-*,jsms/membership/new_revamp_mobile_membership,jsms/membership/new_revamp_mobile_payment]
  layout: jsmsMobLayout
