all:
  ApiCrmAuthenticateV1:
    enable_login: off
  LogCheckinCheckoutV1:
    enable_login: on
  dialerInboundCallIvr:
    enable_login: off    
  dialerIvrUpdate:
    enable_login: off
  SmsNearestBranchDetailsV1:
    enable_login: off
