page404Success:
  has_layout:  false

page500Success:
  metas:
    title:        Jeevansathi 500 Error
  javascripts:    []
  stylesheets:    []
searchIdExpireSuccess:
  metas:
    title:        Jeevansathi Your search has expired

  stylesheets:    []

logoutPageSuccess:
  metas:
    title:        Jeevansathi Matrimonials- Login

  stylesheets:    [jspc/logout/homecss]
  javascripts: [jspc/common/hslider,jspc/logout/hpjs]
  layout: jspcLayout

_callHelp:
  has_layout:  false

newLoginLayerSuccess:
  has_layout: false
  javascripts: []
  
changePassSuccess:
    metas:
      title: Change Password-Jeevansathi
    stylesheets: [-*,jsms/settings/settings_css]
    javascripts: [-*,jsms/settings/mobChangePass_js]
    layout: jsmsMobLayout

settingsSuccess:
    metas:
      title: Jeevansathi Settings
    stylesheets: [-*,jsms/settings/settings_css]
    javascripts: [-*,jsms/settings/settings_js]
    layout: jsmsMobLayout

newMobLoginSuccess:
  metas:
    title: Jeevansathi login
  stylesheets: [-*]
  javascripts: [-*,jsms/login/newMobLogin_js,jsms/hamburger/ham_js@bottom]
  layout: jsmsLoginLayout

loginLayerSuccess:
  has_layout: false

forgotPasswordLayerSuccess:
  has_layout: false

forgotPasswordSuccess:
  metas:
    title: Forgot Password-Jeevansathi
  stylesheets: [-*,jsms/login/newMobLogin_css]
  javascripts: [-*,jsms/login/mobForgotPass_js,js_common]
  layout: jsmsMobLayout
  
resetLinkSentSuccess:
    metas:
      title: Jeevansathi.com- Reset Link Sent
    stylesheets: [-*]
    layout: jsmsMobLayout
    
resetPassSuccess:
    metas:
      title: Reset Password-Jeevansathi
    stylesheets: [-*,jsms/login/newMobLogin_css]
    javascripts: [-*,jsms/login/resetPass_js]
    layout: jsmsMobLayout
    
forgotLinkExpiredSuccess:
    metas:
      title: Jeevansathi.com- Reset Link has expired
    stylesheets: [-*]
    layout: jsmsMobLayout
    
passSetCompleteSuccess:
    metas:
      title: Jeevansathi.com- Password set successfully
    stylesheets: [-*]
    layout: jsmsMobLayout

registrationLayerSuccess:
  has_layout: false
mobileloginSuccess:
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css,moblogin_css,mobile_media_css,mobCE_css]
  javascripts: [-*,showHide_js]
  layout: moblayout
mobpage500Success:
  metas:
    title:  Jeevansathi.com - Error
  stylesheets: [-*,reg_common_mobile_css]
  javascripts: [jquery_validate_js,registration_revamp_js@bottom,jsmb_page1_js]
  layout: mobRegLayout
mobsearchidexpireSuccess:
  metas:
    title:  Jeevansathi.com - Your search has expired
  stylesheets: [-*,reg_common_mobile_css]
  javascripts: [jquery_validate_js,registration_revamp_js@bottom,jsmb_page1_js]
  layout: mobRegLayout  
mob404Success:
  metas:
    title:  Jeevansathi.com - 404
  stylesheets: [-*,reg_common_mobile_css]
  javascripts: [jquery_validate_js,registration_revamp_js@bottom,jsmb_page1_js]
  layout: mobRegLayout

agentinfoSuccess:
  metas:
    title:  Verification Seal Info
    robots:  noindex, nofollow
  stylesheets: [jspc/static/kycss]
  javascripts: [jspc/common/test1]
  layout: jspcLayout
mobdisclaimerSuccess:
  metas:
    title: Terms & Condition
  stylesheets: [-*]
  javascripts: [-*]
  layout: mobRegLayout
mobprivacyfeaturesSuccess:
  metas:
    title: Jeevansathi Matrimonials- Privacy Features
  stylesheets: [-*]
  javascripts: [-*]
  layout: mobRegLayout
mobthirdpartySuccess:
  metas:
    title: Jeevansathi Matrimonials- Third Party Terms & Conditions
  stylesheets: [-*]
  javascripts: [-*]
  layout: mobRegLayout
mobprivacypolicySuccess:
  metas:
    title: Jeevansathi Matrimonials- Privacy Policy
  stylesheets: [-*]
  javascripts: [-*]
  layout: mobRegLayout
jsmsdisclaimerSuccess:
   metas:
    title: Terms & Conditions
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: [-*]
   layout: jsmsMobLayout
jsmsprivacypolicySuccess:
   metas:
    title: Jeevansathi Matrimonials- Privacy Policy
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: [-*]
   layout: jsmsMobLayout
jsmsprivacypolicyampSuccess:
   metas:
    title: Jeevansathi Matrimonials- Privacy Policy
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: [-*]
   layout: jsmsMobAmpLayout
jsmsfraudalertSuccess:
   metas:
    title: Jeevansathi Matrimonials- Fraud Alert
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: [-*]
   layout: jsmsMobLayout
jsmsthirdpartySuccess:
   metas:
    title: Jeevansathi Matrimonials- Third Party Terms & Conditions
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: [-*]
   layout: jsmsMobLayout
jsmsprivacyfeaturesSuccess:
   metas:
    title: Jeevansathi Matrimonials- Privacy Features
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: [-*]
   layout: jsmsMobLayout
disclaimerSuccess:
  metas:
    title: Jeevansathi Matrimonials- Terms and Conditions
privacyfeaturesSuccess:
  metas:
    title: Jeevansathi Matrimonials- Privacy Features
thirdpartySuccess:
  metas:
    title: Jeevansathi Matrimonials- Third Party Terms & Conditions
privacypolicySuccess:
  metas:
    title: Jeevansathi Matrimonials- Privacy Policy
advertiseSuccess:
  metas:
    title: Jeevansathi - Advertise With Us
jsmsmob404Success:
   stylesheets: [-*,jsms/hamburger/ham_css,jsms/profile/ep/mp_css]
   javascripts: [-*,jsms/hamburger/ham_js@bottom]
   layout: jsmsMobLayout
jsmsmob500Success:
   stylesheets: [-*,jsms/hamburger/ham_css,jsms/profile/ep/mp_css]
   javascripts: [-*,jsms/hamburger/ham_js@bottom]
   layout: jsmsMobLayout
jsmsMobSearchIdExpireSuccess:
  metas:
    title:  Jeevansathi.com - Your search has expired
  stylesheets: [-*,jsms/hamburger/ham_css]
  javascripts: [-*,jsms/hamburger/ham_js@bottom]
  layout: jsmsMobLayout  
AppPromoSuccess:
   stylesheets: [-*,iosprmo]
   javascripts: [-*,app_promo_js]
AppPromoIOSSuccess:
   stylesheets: [-*,iosprmo]
   javascripts: [-*,app_promo_js]

jspcStaticPageSuccess:
  http_metas:
    X-UA-Compatible:    IE=edge
  stylesheets:    [jspc/static/static_css,jspc/common/NProgress]

  javascripts:    [jspc/static/static_js]
  layout: jspcLayout

jspcEmailVerifiedSuccess:
  http_metas:
    X-UA-Compatible:    IE=edge
  stylesheets:    []
  javascripts:    []
  layout: jspcLayout

jsmsEmailVerifiedSuccess:
  stylesheets:    []
  javascripts:    [-*]
  layout: jsmsMobLayout
deleteOptionSuccess:
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: []
   layout: jsmsMobLayout 

hideOptionSuccess:
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: []
   layout: jsmsMobLayout 

unHideOptionSuccess:
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: [jsms/settings/mobHideProfile_js]
   layout: jsmsMobLayout

unHideResultSuccess:
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: []
   layout: jsmsMobLayout 

hideCheckPasswordSuccess:
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: [jsms/settings/mobHideProfile_js]
   layout: jsmsMobLayout 

hideDurationSuccess:
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: []
   layout: jsmsMobLayout

deleteReasonSuccess:
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: [jsms/settings/mobDeleteProfile_js]
   layout: jsmsMobLayout 

passCheckSuccess:
   stylesheets: [-*,jsms/settings/settings_css]
   javascripts: [jsms/settings/mobDeleteProfile_js]
   layout: jsmsMobLayout 

jsmsVerificationStaticPageSuccess:
   stylesheets: [-*,jsms/common/verificationIcon_css]
   javascripts: [jsms/common/verificationIcon_js]
   layout: jsmsMobLayout

