<?php
/* This script contains all Javascript and CSS files and included in connect.inc to avoide caching problem */
/* CSS File */
function getCssFilesArr(){
$css_arr[]=array("jsms/search/searchform_css"   => "4");
$css_arr[]=array("AppPromo" => "3");
$css_arr[]=array("reg_common_css"   => "24");
$css_arr[]=array("reg_common_new_css"   => "11");
$css_arr[]=array("mini_reg_css"   => "8");
$css_arr[]=array("search_result_css" => "6");
$css_arr[]=array("lightbox_css" => "5");
$css_arr[]=array("myjs_view_similar_css"   => "7");
$css_arr[]=array("colorbox_css"   => "7");
$css_arr[]=array("home_page_style_css"   => "9");
$css_arr[]=array("searchstyle_css" => "5");
$css_arr[]=array("chat_style_css" => "9");
$css_arr[]=array("contact_details_css_css"   => "7");
$css_arr[]=array("eoi_style_css" => "5");
$css_arr[]=array("cropper_css" => "6");
$css_arr[]=array("view_similar_css"   => "8");
$css_arr[]=array("style_css" => "6");
$css_arr[]=array("chromestyle_css" => "5");
$css_arr[]=array("comm_style_css" => "5");
$css_arr[]=array("myjs_incompleteprofile_css" => "5");
$css_arr[]=array("registerstyle_css" => "5");
$css_arr[]=array("landpage_css" => "5");
$css_arr[]=array("dropdown_css" => "5");
$css_arr[]=array("registration_revamp_css" => "5");
$css_arr[]=array("mailstyles_css" => "5");
$css_arr[]=array("registration_dpp_css" => "5");
$css_arr[]=array("hdr_css"   => "14");
$css_arr[]=array("my_js_css"   => "25");
$css_arr[]=array("mem_css"   => "7");
$css_arr[]=array("common_chat" => "6");
$css_arr[]=array("common_css"   => "12");
$css_arr[]=array("hdr_sulekha"   => "7");
$css_arr[]=array("logout_css"   => "8");
$css_arr[]=array("crsl_css1"   => "7");
$css_arr[]=array("slider_css" => "7");
$css_arr[]=array("slider_comm_css" => "5");
$css_arr[]=array("contact_center_css" => "13");
$css_arr[]=array("homepage_style_css"   => "22");
$css_arr[]=array("phonelayerStyle_css"   => "7");
$css_arr[]=array("sugarcrm_common_css" => "5");
$css_arr[]=array("seo_community_css"   => "13");
$css_arr[]=array("call_help_css"   => "8");
$css_arr[]=array("js_photo_studio_style_css"   => "8");
$css_arr[]=array("hdr_css_new"   => "12");
$css_arr[]=array("js_photo_studio_style"   => "9");
$css_arr[]=array("view_page_css"   => "12");
$css_arr[]=array("slider-small"   => "7");
$css_arr[]=array("importPhotos"   => "7");
$css_arr[]=array("profile_layer"   => "10");
$css_arr[]=array("upload" => "5");
$css_arr[]=array("edit_css"   => "11");
$css_arr[]=array("mobilejs_css"   => "16");
$css_arr[]=array("mobilejs_menu_css"   => "7");
$css_arr[]=array("mobilejs_slider_css"   => "7");
$css_arr[]=array("autoSuggest_jq_css" => "5");
$css_arr[]=array("mem_css_css"   => "7");
$css_arr[]=array("chk_drp_css"   => "7");
$css_arr[]=array("common1_css"   => "7");
$css_arr[]=array("tncLayer_css" => "5");
$css_arr[]=array("phoneVerify_css"   => "11");
$css_arr[]=array("cancer_vcare_css"   => "7");
$css_arr[]=array("jslider"   => "7");
$css_arr[]=array("minify" => "5");
$css_arr[]=array("style_search"   => "16");
$css_arr[]=array("transliteration" => "5");
$css_arr[]=array("search_embeded" => "5");
$css_arr[]=array("search_popup_screens"   => "8");
$css_arr[]=array("header-footer"   => "10");
$css_arr[]=array("revamp_filter_css"   => "9");
$css_arr[]=array("registration_page1b_css"   => "9");
$css_arr[]=array("global"   => "8");
$css_arr[]=array("contactEngine_css"   => "10");
$css_arr[]=array("fto_css"   => "7");
$css_arr[]=array("reset_css" => "5");
$css_arr[]=array("edit_layer_css"   => "7");
$css_arr[]=array("jquery_countdown_css"   => "7");
$css_arr[]=array("mobCE_css"   => "10");
$css_arr[]=array("rupeeSymbol_css"   => "7");
$css_arr[]=array("sitemap_css"   => "7");
$css_arr[]=array("photoPrivacyLayer"   => "7");
$css_arr[]=array("success_story_css"   => "7");
$css_arr[]=array("autoSelect_css"   => "10");
$css_arr[]=array("reg_common_mobile_css"   => "6");
$css_arr[]=array("mobilejs_revamp"   => "10");
$css_arr[]=array("mobile_hamburger_css"   => "6");
$css_arr[]=array("mobile_media_css"   => "7");
$css_arr[]=array("mem-interface-css"   => "21");
$css_arr[]=array("SpryAccordion" => "3");
$css_arr[]=array("minify_002" => "8");
$css_arr[]=array("style" => "3");
$css_arr[]=array("content" => "3");
$css_arr[]=array("verticaltabs" => "3");
$css_arr[]=array("photoAlbumMobile"   => "5");
$css_arr[]=array("opera_css" => "4");
$css_arr[]=array("media_css" => "3");
$css_arr[]=array("jsmbPhoneVerifyStyle_css" => "3");
$css_arr[]=array("styles_css" => "3");
$css_arr[]=array("kycAgent_css"   => "5");
$css_arr[]=array("contactus_css"   => "5");
$css_arr[]=array("customReg_css"   => "5");
$css_arr[]=array("show_app_promo_css" => "2");
$css_arr[]=array("myjsnew"   => "4");
$css_arr[]=array("app_promo_css"   => "8");
$css_arr[]=array("photoRequest"   => "5");
$css_arr[]=array("view" => "2");
$css_arr[]=array("view_similar_profile_css"   => "6");
$css_arr[]=array("gnb_css"   => "9");
$css_arr[]=array("moblogin_css"   => "5");
$css_arr[]=array("jsms/profile/ep/mp_css"   => "11");
$css_arr[]=array("mr_common_css" => "5");
$css_arr[]=array("mediaquery_css" => "5");
$css_arr[]=array("swipe_css" => "4");
$css_arr[]=array("revampMobile_common_css"   => "5");
$css_arr[]=array("jsms/myjs/jsmsMyjs_css"     => "24");
$css_arr[]=array("jsms/phone/phoneVerification_css"   => "5");
$css_arr[]=array("jsms/photo/photoswipe"   => "4");
$css_arr[]=array("jsms/common/fonts" => "3");
$css_arr[]=array("jsms/common/commoncss"      => "68");
$css_arr[]=array("jsms/common/mediaquery" => "6");
$css_arr[]=array("jsms/search/srpcss"   => "20");
$css_arr[]=array("jsms/photo/photoup" => "2");
$css_arr[]=array("jsms/membership/revamp_membership_css" => "4");
$css_arr[]=array("jsms/membership/new_revamp_membership_css"     => "19");
$css_arr[]=array("jsms/profile/ep/revamp_edit_profile_css"   => "26");
$css_arr[]=array("jsms/register/regis_css" => "15");
$css_arr[]=array("jsms/register/reg_animate" => "5");
$css_arr[]=array("jsms/profile/viewProfile/jsmsViewProfile_css"   => "29");
$css_arr[]=array("jsms/common/errorBar" => "2");
$css_arr[]=array("jsms/contacts/contact_engine" => "3");
$css_arr[]=array("mobreg_pass_css"   => "5");
$css_arr[]=array("operations_styles" => "2");
$css_arr[]=array("jsms/Seo/seoMobile_css"   => "4");
$css_arr[]=array("jsms/login/newMobLogin_css"   => "22");
$css_arr[]=array("jsms/search/searchdropdown"   => "4");
$css_arr[]=array("jsms/contact_engine/contactEngine"   => "19");
$css_arr[]=array("jsms/hamburger/ham_css" => "4");
$css_arr[]=array("jsms/common/jsmsApp_promo_css"   => "18");
$css_arr[]=array("jsms/settings/settings_css"   => "12");
$css_arr[]=array("jsmsViewProfile_css" => "2");
$css_arr[]=array("mp_css" => "2");
$css_arr[]=array("contactEngine" => "2");
$css_arr[]=array("jsmsApp_promo_css" => "2");
$css_arr[]=array("commoncss" => "2");
$css_arr[]=array("sidenav" => "2");
$css_arr[]=array("operanew" => "2");
$css_arr[]=array("fonts_css" => "2");
$css_arr[]=array("fonts" => "2");
$css_arr[]=array("jsexclusive_style"   => "11");
$css_arr[]=array("helpWidget_css"   => "20");
$css_arr[]=array("jsms/search/savesearchcss" => "11");
$css_arr[]=array("iosprmo" => "3");
$css_arr[]=array("jspc/common/commonJspc_css"        => "43");
$css_arr[]=array("jspc/registration/registrationJspc_css"   => "19");
$css_arr[]=array("jspc/myjs/myjs"     => "42");
$css_arr[]=array("jspc/common/fontsJspc_css"   => "4");
$css_arr[]=array("jspc/common/headerFooterJspc_css"      => "22");
$css_arr[]=array("jspc/search/scrollbar"   => "4");
$css_arr[]=array("jspc/search/srpcss"      => "15");
$css_arr[]=array("jspc/search/jslider"   => "4");
$css_arr[]=array("jspc/common/cssRangeSlider"   => "5");
$css_arr[]=array("jspc/search/rangeslider"   => "4");
$css_arr[]=array("jspc/common/jquerymCustomScrollbar" => "2");
$css_arr[]=array("jspc/search/searchBand"   => "4");
$css_arr[]=array("jspc/profile/edit/dpp/dppEdit_css"   => "39");
$css_arr[]=array("jspc/utility/chosen/chosen_css"   => "4");
$css_arr[]=array("jspc/logout/homecss"   => "12");
$css_arr[]=array("jspc/phone/phoneVerification_css" => "3");
$css_arr[]=array("jspc/common/colorbox_css"   => "4");
$css_arr[]=array("jspc/common/NProgress"   => "6");
$css_arr[]=array("jspc/membership/jspc_mem_css"    => "36");
$css_arr[]=array("jspc/membership/upgrade_mem_css"   => "14");
$css_arr[]=array("jspc/membership/jspc_mem_custom_scrollbar" => "2");
$css_arr[]=array("jspc/membership/jspc_mem_sweetalert"   => "4");
$css_arr[]=array("jspc/membership/jspc_mem_scrollpane" => "2");
$css_arr[]=array("jspc/membership/jspc_mem_custom_select" => "2");
$css_arr[]=array("jspc/photoUpload/photoup_css"   => "12");
$css_arr[]=array("jspc/photoUpload/cropper"   => "4");
$css_arr[]=array("jspc/photoUpload/main"   => "4");
$css_arr[]=array("jspc/inbox/contactCenter"       => "10");
$css_arr[]=array("jspc/success_story/successStory" => "2");
$css_arr[]=array("jspc/contactus/contactus_css"   => "4");
$css_arr[]=array("jspc/profile/view/jspcViewProfile_css"   => "38");
$css_arr[]=array("jspc/profile/edit/profile/jspcEditProfile_css"   => "12");
$css_arr[]=array("jspc/search/advancedSearch"   => "12");
$css_arr[]=array("jspc/faq/feedback" => "2");
$css_arr[]=array("jspc/contactEngine/contactEngine_css"   => "15");
$css_arr[]=array("jspc/profile/edit/profile/jspcCoverPhoto_css"   => "4");
$css_arr[]=array("jspc/profile/edit/profile/jspcEditProfileCompletion_css"   => "4");
$css_arr[]=array("jspc/common/mCustomScrollBar_css"   => "7");
$css_arr[]=array("jspc/profile/view/jspcNoProfile_css"   => "4");
$css_arr[]=array("jspc/seo/seo" => "8");
$css_arr[]=array("jspc/static/static_css"   => "4");
$css_arr[]=array("jspc/settings/settings" => "7");
$css_arr[]=array("jspc/static/kycss"   => "4");
$css_arr[]=array("jspc/commonInterface/VDUpload"   => "4");
$css_arr[]=array("jspc/crm/loader_css"   => "4");
$css_arr[]=array("jeevansathi_css"   => "5");
$css_arr[]=array("jspc/common/3DotLoader"   => "6");
$css_arr[]=array("jsms/common/verificationIcon_css"   => "5");
$css_arr[]=array("rippleEffectCommon_css"   => "5");
$css_arr[]=array("jsms/common/disableRightClick_css"   => "5");
$css_arr[]=array("jsms/profile/horoscope/horoscope_css"   => "4");
$css_arr[]=array("operations/showStatViewProfile_css"   => "4");
$css_arr[]=array("operations/help_module"   => "4");
$css_arr[]=array("jspc/chat/chat_css"   => "18");
$css_arr[]=array("jspc/help/JSPCHelp_css"   => "11");
$css_arr[]=array("jsms/help/JSMSHelp_css"   => "6");
$css_arr[]=array("jsms/myjs/CALJSMS_css"     => "24");
$css_arr[]=array("-1" => "4");
$css_arr[]=array(" /web/js/ /web/profile/css/my_js_css" => "2");
$css_arr[]=array("yatra_style"   => "8");
$css_arr[]=array("promotions/chatPromo/chatPromoMS_css"   => "8");
$css_arr[]=array("promotions/chatPromo/chatPromoPC_css"   => "6");
$css_arr[]=array("sathiForLife_css"   => "12");
$css_arr[]=array("widget/pop_up"    => "2");
$css_arr[]=array("sulekha_css"    => "2");
$css_arr[]=array("sugarcrm_common"    => "2");
$css_arr[]=array("pd_screen"    => "2");
$css_arr[]=array("myjs_vishwas_seal"    => "2");
$css_arr[]=array("myjs"    => "2");
$css_arr[]=array("mini_reg_v1"    => "2");
$css_arr[]=array("mini_reg"    => "2");
$css_arr[]=array("mem"    => "2");
$css_arr[]=array("crsl_css"    => "2");
$css_arr[]=array("common1"    => "2");
$css_arr[]=array("chk_drp"    => "2");
$css_arr[]=array("adr_vrfy"    => "2");
$css_arr[]=array("productmetric/icheck/green"    => "2");
$css_arr[]=array("productmetric/fonts/css/font-awesome"    => "2");
$css_arr[]=array("productmetric/datetimePicker/datetimeCss"    => "2");
$css_arr[]=array("productmetric/custom"    => "2");
$css_arr[]=array("productmetric/bootstrap"    => "2");
$css_arr[]=array("productmetric/animate"    => "2");
$css_arr[]=array("operations_jeevansathi"    => "2");
$css_arr[]=array("mmm_js/jeevansathi"    => "2");
$css_arr[]=array("mmm_js/formQuery_99"    => "2");
$css_arr[]=array("mmm_js/div"    => "2");
$css_arr[]=array("mmm_js/calendar"    => "2");
$css_arr[]=array("mmm_99/table"    => "2");
$css_arr[]=array("mmm_99/jeevansathi"    => "2");
$css_arr[]=array("mmm_99/formQuery"    => "2");
$css_arr[]=array("mmm_99/div"    => "2");
$css_arr[]=array("jspc/photoup"    => "2");
$css_arr[]=array("jquery_dateLists"    => "2");
$css_arr[]=array("calendar_css"    => "2");
$css_arr[]=array("autoSuggest_css"    => "2");
$css_arr[]=array("main"    => "2");
$css_arr[]=array("default"    => "2");
$css_arr[]=array(" /JSNotificationExtension/JSnotification/desktop-notify"    => "2");
return $css_arr;
}
/* JavaScript File */
function getJsFilesArr(){
$js_arr[]=array("jsms/common/scrollTo"   => "4");
$js_arr[]=array("jsms/search/mobSearchDropDown_js"   => "18");
$js_arr[]=array("jsms/search/mobSearchForm_js"   => "7");
$js_arr[]=array("contactEngineNew_js"   => "7");
$js_arr[]=array("registration_ajax_new_js" => "7");
$js_arr[]=array("behaviour_new_js" => "5");
$js_arr[]=array("registration_page1_new_js" => "22");
$js_arr[]=array("registration_new_page_js" => "15");
$js_arr[]=array("registration_js" => "8");
$js_arr[]=array("advance_search_js"   => "10");
$js_arr[]=array("gadget_as_js" => "11");
$js_arr[]=array("behaviour_js" => "5");
$js_arr[]=array("gadget_reg_dpp_js" => "5");
$js_arr[]=array("shared_js" => "5");
$js_arr[]=array("roster_js" => "5");
$js_arr[]=array("config_js" => "6");
$js_arr[]=array("browsercheck_js" => "5");
$js_arr[]=array("new_jsjac_js" => "5");
$js_arr[]=array("revampCommon_js" => "42");
$js_arr[]=array("ajax_revampCommon_js" => "7");
$js_arr[]=array("colorbox"   => "8");
$js_arr[]=array("cluster_js" => "5");
$js_arr[]=array("tooltip_new_js" => "5");
$js_arr[]=array("multiselect_clustering_js" => "5");
$js_arr[]=array("emoticons_js" => "5");
$js_arr[]=array("switchStyle_js" => "5");
$js_arr[]=array("util_v11_js" => "13");
$js_arr[]=array("show_hide_div_js" => "5");
$js_arr[]=array("prototype_js" => "5");
$js_arr[]=array("dragdrop_js" => "5");
$js_arr[]=array("cropper_js"   => "8");
$js_arr[]=array("builder_js" => "5");
$js_arr[]=array("scriptaculous_js" => "5");
$js_arr[]=array("ajax_js"   => "12");
$js_arr[]=array("ivrContact_js"   => "7");
$js_arr[]=array("search_similar_js"   => "11");
$js_arr[]=array("search_js" => "5");
$js_arr[]=array("jspc/search/viewSimilarProfile_js"   => "4");
$js_arr[]=array("jspc/search/jspcMembershipMsg_js"   => "4");
$js_arr[]=array("jspc/search/searchCommon_js"   => "30");
$js_arr[]=array("profile_js" => "5");
$js_arr[]=array("searchhover_js" => "7");
$js_arr[]=array("conf_layer_js" => "5");
$js_arr[]=array("dw_viewport_js" => "5");
$js_arr[]=array("dw_core_js" => "5");
$js_arr[]=array("dw_clip_js" => "5");
$js_arr[]=array("dw_wipes_js" => "5");
$js_arr[]=array("common_js" => "5");
$js_arr[]=array("google_map_api_js" => "5");
$js_arr[]=array("second_js" => "5");
$js_arr[]=array("Debugger_js" => "5");
$js_arr[]=array("chrome_js" => "5");
$js_arr[]=array("leftpanelnew_js" => "5");
$js_arr[]=array("AnchorPosition_js" => "5");
$js_arr[]=array("multiselect_top_js" => "5");
$js_arr[]=array("autosuggest_js" => "6");
$js_arr[]=array("autoSuggest_jq_js" => "9");
$js_arr[]=array("registration_pg1_new_js" => "8");
$js_arr[]=array("balloon_js" => "5");
$js_arr[]=array("banner_slide_js" => "5");
$js_arr[]=array("PopupWindow_js" => "5");
$js_arr[]=array("popunder_js" => "5");
$js_arr[]=array("google2_js" => "5");
$js_arr[]=array("google3_js" => "5");
$js_arr[]=array("google_js" => "5");
$js_arr[]=array("yahoo-dom-event_js" => "5");
$js_arr[]=array("dropdown_js" => "5");
$js_arr[]=array("date_js" => "5");
$js_arr[]=array("headnew_js" => "5");
$js_arr[]=array("incomplete_pg1_js" => "5");
$js_arr[]=array("ivrVerifyPhone_js" => "6");
$js_arr[]=array("removeBookmark_js" => "6");
$js_arr[]=array("registration_new_js" => "6");
$js_arr[]=array("jschat_js" => "10");
$js_arr[]=array("topSearchBand_js"   => "15");
$js_arr[]=array("myjs_js"    => "17");
$js_arr[]=array("mem_v2_js"   => "21");
$js_arr[]=array("mootools_js" => "5");
$js_arr[]=array("slider_js" => "6");
$js_arr[]=array("slider_comm_js" => "5");
$js_arr[]=array("seo_community_js"   => "12");
$js_arr[]=array("calendarpopup_js" => "5");
$js_arr[]=array("payment_js" => "5");
$js_arr[]=array("mini_reg_js"   => "8");
$js_arr[]=array("jquery_dimensions_js" => "5");
$js_arr[]=array("sugar_registration_new_page_js" => "6");
$js_arr[]=array("sugar_registration_page1_new_js" => "9");
$js_arr[]=array("saveDetails"   => "9");
$js_arr[]=array("profileLayer"   => "9");
$js_arr[]=array("Swiff_Uploader" => "5");
$js_arr[]=array("Fx_ProgressBar"   => "7");
$js_arr[]=array("FancyUpload2"   => "7");
$js_arr[]=array("onload" => "5");
$js_arr[]=array("photo_slider"   => "7");
$js_arr[]=array("displayFullImage"   => "7");
$js_arr[]=array("ajax_social"   => "12");
$js_arr[]=array("ajaxMultiThreading"   => "7");
$js_arr[]=array("compUpload_js"   => "10");
$js_arr[]=array("mootools-core-1-3-2-full-compat"   => "7");
$js_arr[]=array("compUploadNoFlash_js"   => "7");
$js_arr[]=array("contact_engine_js"   => "15");
$js_arr[]=array("profile_album_js"   => "13");
$js_arr[]=array("profile_tab_js"   => "17");
$js_arr[]=array("header_js"   => "17");
$js_arr[]=array("homepage_js"   => "9");
$js_arr[]=array("edit_page_js"   => "7");
$js_arr[]=array("city_country_common"   => "10");
$js_arr[]=array("tracking_js"   => "15");
$js_arr[]=array("chk_drp_js"   => "7");
$js_arr[]=array("viewSimilar_js"   => "10");
$js_arr[]=array("textbox_hinter"   => "7");
$js_arr[]=array("emailchecks"   => "7");
$js_arr[]=array("phoneVerify_js"   => "26");
$js_arr[]=array("tncLayer_js"   => "8");
$js_arr[]=array("jquery-dependClass"   => "7");
$js_arr[]=array("jquery-slider"   => "7");
$js_arr[]=array("jshashtable_src"   => "7");
$js_arr[]=array("tmpl"   => "7");
$js_arr[]=array("draggable"   => "7");
$js_arr[]=array("fadeslideshow"   => "7");
$js_arr[]=array("searchPage_js"   => "39");
$js_arr[]=array("loginSearch"   => "15");
$js_arr[]=array("albumLayer_js"   => "10");
$js_arr[]=array("json2"   => "7");
$js_arr[]=array("revamp_filter_js"   => "11");
$js_arr[]=array("reg_page1b_js"   => "8");
$js_arr[]=array("contactEngineLayer_js"   => "16");
$js_arr[]=array("jquery_countdown_js"   => "7");
$js_arr[]=array("mobCE_js"   => "7");
$js_arr[]=array("fto_js"   => "7");
$js_arr[]=array("mobSEO_js"   => "8");
$js_arr[]=array("sstory_js"   => "8");
$js_arr[]=array("jspc/crm/uploadVD_js"   => "4");
$js_arr[]=array("jspc/crm/pendingFieldVisits_js"   => "5");
$js_arr[]=array("jspc/crm/requestFieldVisit_js"   => "5");
$js_arr[]=array("jspc/crm/dateSelectionField_js"   => "5");
$js_arr[]=array("jspc/crm/exclusiveMemAllocation_js"   => "7");
$js_arr[]=array("jspc/crm/loader_js"   => "6");
$js_arr[]=array("jspc/crm/exclusiveServicingII_js"   => "9");
$js_arr[]=array("jspc/crm/changeActiveServiceInterface_js"   => "13");
$js_arr[]=array("jquery_cookie_js"   => "7");
$js_arr[]=array("registration_revamp_js"   => "18");
$js_arr[]=array("jquery_validate_js"   => "5");
$js_arr[]=array("register_common_all_js"   => "5");
$js_arr[]=array("autoSelect_js"   => "6");
$js_arr[]=array("autoMobileSelect_js"   => "6");
$js_arr[]=array("selectType_js"   => "14");
$js_arr[]=array("reg_page2_js"   => "13");
$js_arr[]=array("jsmb_page4_js"   => "14");
$js_arr[]=array("reg_page4_js"   => "5");
$js_arr[]=array("mini_reg_revamp_js"   => "5");
$js_arr[]=array("regPage5_js"   => "7");
$js_arr[]=array("mobselectType_js"   => "5");
$js_arr[]=array("html5_js"   => "6");
$js_arr[]=array("reg_page1_js"   => "12");
$js_arr[]=array("jsmb_page1_js"   => "6");
$js_arr[]=array("jsmb_page2_js"   => "5");
$js_arr[]=array("jsmb_page3_js"   => "8");
$js_arr[]=array("reg_page3_js"   => "6");
$js_arr[]=array("noautoSelect_js"   => "5");
$js_arr[]=array("modernizr_js"   => "5");
$js_arr[]=array("modernizr_p_js"   => "6");
$js_arr[]=array("boomerang_js"   => "5");
$js_arr[]=array("boomerang_tracking_js"   => "5");
$js_arr[]=array("SpryAccordion" => "3");
$js_arr[]=array("verticaltabs_pack_js" => "3");
$js_arr[]=array("memJS" => "17");
$js_arr[]=array("memCommonJS" => "11");
$js_arr[]=array("valueAddedJS"   => "19");
$js_arr[]=array("paymentOptions"   => "33");
$js_arr[]=array("jquery_cookie"   => "5");
$js_arr[]=array("mobHamburger_js"   => "11");
$js_arr[]=array("jquery_touch"   => "5");
$js_arr[]=array("mobAlbum"   => "5");
$js_arr[]=array("mobPhotoUpload"   => "6");
$js_arr[]=array("commonMob"   => "5");
$js_arr[]=array("mobBrowser_js" => "3");
$js_arr[]=array("mobSearchBand"   => "7");
$js_arr[]=array("app_promo_js"   => "63");
$js_arr[]=array("selectType_Page3_js"   => "5");
$js_arr[]=array("editNativePlace_js"   => "10");
$js_arr[]=array("mobNative_Place_selectType_js"   => "5");
$js_arr[]=array("jsmb_page5_js"   => "5");
$js_arr[]=array("mobprofile_js"   => "6");
$js_arr[]=array("jquery"   => "4");
$js_arr[]=array("zedo"   => "18");
$js_arr[]=array("view" => "2");
$js_arr[]=array("view_similar_profile_js"   => "5");
$js_arr[]=array("assisted_product" => "2");
$js_arr[]=array("pixel_js"   => "5");
$js_arr[]=array("mouseClickTracking_js"   => "5");
$js_arr[]=array("jsms/profile/ep/submitDetails_js"   => "45");
$js_arr[]=array("jsms/profile/ep/hamburger_js"   => "49");
$js_arr[]=array("jsms/profile/ep/mobedit_js"             => "71");
$js_arr[]=array("jsms/profile/ep/mobeditview_js"    => "89");
$js_arr[]=array("jsms/profile/ep/mobShow_name_js"   => "11");
$js_arr[]=array("jsms/common/disableScroll_js"   => "7");
$js_arr[]=array("jsms/utility/sessionStorage_js"   => "10");
$js_arr[]=array("jsms/myjs/touchswipemyjs_js" => "22");
$js_arr[]=array("jsms/myjs/myjs_js"      => "79");
$js_arr[]=array("showHide_js"   => "5");
$js_arr[]=array("showHideReg_js"   => "5");
$js_arr[]=array("operations_validate1"   => "10");
$js_arr[]=array("jsms/photo/mobPhotoAlbum_photoswipe"   => "6");
$js_arr[]=array("jsms/photo/mobPhotoAlbum_panzoom"   => "4");
$js_arr[]=array("jsms/photo/mobPhotoAlbum_photoSwipeInheritence"   => "4");
$js_arr[]=array("jsms/profile/ep/mobedit_validator_js"    => "28");
$js_arr[]=array("js_common"   => "5");
$js_arr[]=array("mobBrowser_js_2"   => "5");
$js_arr[]=array("jsms/membership/jquery_sly" => "3");
$js_arr[]=array("jquery_ui_min" => "3");
$js_arr[]=array("jsms/membership/jquery_animateNumber" => "2");
$js_arr[]=array("jsms/photo/photo_upload_js"   => "11");
$js_arr[]=array("jsms/photo/photo_privacy_js"   => "4");
$js_arr[]=array("jsms/membership/shimmer_js" => "2");
$js_arr[]=array("jsms/utility/vSlider_js"   => "19");
$js_arr[]=array("jsms/utility/hamSearch_js"   => "15");
$js_arr[]=array("jsms/membership/revamp_mobile_membership" => "6");
$js_arr[]=array("jsms/phone/phone_js"   => "28");
$js_arr[]=array("jsms/membership/new_revamp_mobile_membership"   => "24");
$js_arr[]=array("jsms/membership/new_revamp_mobile_payment"   => "15");
$js_arr[]=array("jsms/membership/jsms_upgrade_js"   => "11");
$js_arr[]=array("jsms/profile/ep/mobeditsave_js"     => "36");
$js_arr[]=array("jsms/photo/mobPhotoUpload_v1"   => "11");
$js_arr[]=array("jsms/search/relaxCriteria_v1"   => "4");
$js_arr[]=array("jsms/photo/mobPhotoAlbum_v1"   => "5");
$js_arr[]=array("jsms/photo/mobPhotoUploadCommon_js"   => "4");
$js_arr[]=array("jsms/common/urlParamHandling"   => "4");
$js_arr[]=array("jsms/common/CommonFunctions"            => "74");
$js_arr[]=array("jsms/common/touchswipe_js"   => "6");
$js_arr[]=array("jsms/common/history_js"   => "10");
$js_arr[]=array("jsms/photo/photoRequestCommon_js"   => "5");
$js_arr[]=array("jsms/search/jqueryInfiniteScroll"   => "69");
$js_arr[]=array("jsms/search/JsmsSearch"   => "5");
$js_arr[]=array("jsms/search/MobileSearchCommon"   => "5");
$js_arr[]=array("jsms/angular/registration/lib/angular_min" => "2");
$js_arr[]=array("jsms/angular/registration/lib/angular-animate_min" => "2");
$js_arr[]=array("jsms/angular/registration/lib/angular-resource_min" => "2");
$js_arr[]=array("jsms/angular/registration/lib/angular-route_min" => "2");
$js_arr[]=array("jsms/angular/registration/lib/angular-touch_min" => "2");
$js_arr[]=array("jsms/angular/registration/scripts/app" => "5");
$js_arr[]=array("jsms/angular/registration/scripts/controllers"   => "45");
$js_arr[]=array("jsms/angular/registration/scripts/services" => "6");
$js_arr[]=array("jsms/angular/registration/scripts/directives" => "27");
$js_arr[]=array("jsms/angular/registration/scripts/factories"   => "54");
$js_arr[]=array("jsms/angular/registration/hamburger_reg_js"   => "35");
$js_arr[]=array("jsms/contact_engine/contactEngine_js"        => "98");
$js_arr[]=array("jsms/profile/viewProfile/jsmsViewProfile_js"       => "49");
$js_arr[]=array("jsms/search/inview"   => "5");
$js_arr[]=array("jsms/login/newMobLogin_js"    => "65");
$js_arr[]=array("jsms/login/mobForgotPass_js"   => "16");
$js_arr[]=array("jsms/login/resetPass_js"   => "5");
$js_arr[]=array("jsms/hamburger/ham_js"   => "53");
$js_arr[]=array("jsms/settings/mobChangePass_js"   => "5");
$js_arr[]=array("jsms/404/mob404_js" => "2");
$js_arr[]=array("jsms/search/searchByProfileId_js"   => "8");
$js_arr[]=array("vSlider_js" => "2");
$js_arr[]=array("sessionStorage_js" => "2");
$js_arr[]=array("mobChangePass_js" => "2");
$js_arr[]=array("mobSearchForm_js" => "2");
$js_arr[]=array("jqueryInfiniteScroll" => "2");
$js_arr[]=array("jsmsViewProfile_js" => "3");
$js_arr[]=array("mobedit_js" => "2");
$js_arr[]=array("photoRequestCommon_js" => "2");
$js_arr[]=array("newMobLogin_js" => "3");
$js_arr[]=array("mobForgotPass_js" => "2");
$js_arr[]=array("ham_js" => "2");
$js_arr[]=array("contactEngine_js" => "2");
$js_arr[]=array("history_js" => "2");
$js_arr[]=array("CommonFunctions" => "2");
$js_arr[]=array("factories" => "2");
$js_arr[]=array("controllers" => "3");
$js_arr[]=array("app" => "2");
$js_arr[]=array("hamburger_reg_js" => "2");
$js_arr[]=array("touchswipemyjs_js" => "2");
$js_arr[]=array("touchswipe_js" => "2");
$js_arr[]=array("timetracker_js"   => "4");
$js_arr[]=array("hamburger_js" => "2");
$js_arr[]=array("resetPass_js" => "2");
$js_arr[]=array("jsms/search/viewSimilarMax"   => "7");
$js_arr[]=array("helpWidget_js"   => "24");
$js_arr[]=array("advance_search"   => "4");
$js_arr[]=array("jsms/search/overlayLayerJsms"   => "6");
$js_arr[]=array("jsms/search/savesearch_js"   => "11");
$js_arr[]=array("sugar/sugar_registration_page1_new_js"   => "6");
$js_arr[]=array("app_promo"   => "6");
$js_arr[]=array("sugar/registration_page1_new" => "4");
$js_arr[]=array("registration_pg2" => "4");
$js_arr[]=array("registration_pg1" => "4");
$js_arr[]=array("jsms/contactus/contactus_js" => "2");
$js_arr[]=array("jsms/common/sly"   => "5");
$js_arr[]=array("jspc/myjs/myjs_js"   => "93");
$js_arr[]=array("jspc/myjs/myjs_pcrevamp"     => "116");
$js_arr[]=array("jspc/myjs/engBarJs_js"   => "42");
$js_arr[]=array("jspc/common/nano"   => "7");
$js_arr[]=array("jspc/registration/registrationJspc_js"   => "44");
$js_arr[]=array("jspc/registration/validation_js"   => "36");
$js_arr[]=array("jspc/common/commonJspc_js"              => "59");
$js_arr[]=array("jspc/search/hslider" => "2");
$js_arr[]=array("jspc/search/jquery_1_9_0_min" => "2");
$js_arr[]=array("jspc/search/test1" => "2");
$js_arr[]=array("jspc/search/scrollBar"   => "4");
$js_arr[]=array("jspc/common/searchDropdown_js"   => "8");
$js_arr[]=array("jspc/search/searchTuples"   => "14");
$js_arr[]=array("jspc/search/jspcSuccessStory_js"   => "4");
$js_arr[]=array("jspc/inbox/contactCenter"          => "62");
$js_arr[]=array("jspc/common/jqueryRangeSlider"   => "5");
$js_arr[]=array("jspc/search/inview"   => "4");
$js_arr[]=array("jspc/photo/photoRequest_js"   => "8");
$js_arr[]=array("jspc/common/jquery_equalheights" => "2");
$js_arr[]=array("jspc/common/photoAlbum"   => "11");
$js_arr[]=array("jspc/search/saveSearch"   => "4");
$js_arr[]=array("jspc/search/relaxCriteria"   => "4");
$js_arr[]=array("jspc/search/search"   => "57");
$js_arr[]=array("jspc/search/searchClusters"   => "6");
$js_arr[]=array("jspc/search/searchBand"   => "6");
$js_arr[]=array("jspc/search/searchDropdowns"   => "6");
$js_arr[]=array("jspc/search/common/commonSlider"   => "4");
$js_arr[]=array("jspc/search/searchSliders"   => "4");
$js_arr[]=array("jspc/search/common/ionRangeSliderPlugin"   => "4");
$js_arr[]=array("jspc/common/jquerymCustomScrollbarConcat" => "2");
$js_arr[]=array("jspc/profile/edit/dpp/jspcDppEdit_js"   => "61");
$js_arr[]=array("jspc/utility/chosen/chosen_jquery" => "32");
$js_arr[]=array("jspc/utility/chosen/docsupport/prism" => "2");
$js_arr[]=array("jspc/logout/hpjs"   => "6");
$js_arr[]=array("jspc/common/hslider"   => "4");
$js_arr[]=array("jspc/common/test1"   => "4");
$js_arr[]=array("jspc/common/AjaxWrapper"   => "33");
$js_arr[]=array("jspc/phone/phone_js" => "3");
$js_arr[]=array("jspc/common/colorbox"   => "4");
$js_arr[]=array("jspc/common/phoneVeriLayers_js"   => "20");
$js_arr[]=array("jspc/membership/jspc_mem_custom_scrollbar" => "2");
$js_arr[]=array("jspc/membership/jspc_mem_slider" => "2");
$js_arr[]=array("jspc/membership/jspc_mem_js" => "40");
$js_arr[]=array("jspc/membership/upgrade_mem_js"   => "22");
$js_arr[]=array("jspc/membership/jspc_mem_sweetalert"   => "4");
$js_arr[]=array("jspc/membership/jspc_mem_scrollpane" => "2");
$js_arr[]=array("jspc/membership/jspc_mem_mousewheel" => "2");
$js_arr[]=array("jspc/membership/jspc_mem_select_box" => "2");
$js_arr[]=array("jspc/membership/jspc_mem_md5"   => "4");
$js_arr[]=array("jspc/login/loginLayer_js"   => "56");
$js_arr[]=array("jspc/photoUpload/photoUpload_js"   => "4");
$js_arr[]=array("jspc/photoUpload/addPhoto_js"   => "33");
$js_arr[]=array("jspc/photoUpload/importPhotoAlbum_js"   => "12");
$js_arr[]=array("jspc/photoUpload/compUpload_js"   => "9");
$js_arr[]=array("jspc/photoUpload/cropper"   => "4");
$js_arr[]=array("jspc/photoUpload/main"   => "11");
$js_arr[]=array("jspc/photoUpload/bootstrap"   => "4");
$js_arr[]=array("jspc/photoUpload/tooltip"   => "4");
$js_arr[]=array("jspc/photoUpload/photoFunctions_js"   => "17");
$js_arr[]=array("jspc/common/urlHandling"   => "16");
$js_arr[]=array("jspc/success_story/imagefit" => "2");
$js_arr[]=array("jspc/contactus/contactus_js"   => "4");
$js_arr[]=array("jspc/success_story/successScroll" => "2");
$js_arr[]=array("jspc/profile/edit/profile/jspcEditProfile_js"             => "129");
$js_arr[]=array("jspc/profile/view/jspcViewProfile_js"         => "77");
$js_arr[]=array("jspc/success_story/foggy"   => "4");
$js_arr[]=array("jspc/success_story/resizeIe"   => "4");
$js_arr[]=array("jspc/contactEngine/contactEngine"      => "66");
$js_arr[]=array("jspc/contactEngine/contactEngineButtons"   => "32");
$js_arr[]=array("jspc/search/advancedSearch"   => "25");
$js_arr[]=array("jspc/common/jquery_mCustomScrollbar"   => "16");
$js_arr[]=array("jspc/success_story/jqueryFilestyle"   => "4");
$js_arr[]=array("jspc/profile/edit/profile/jspcCoverPhoto_js"   => "4");
$js_arr[]=array("jspc/profile/edit/profile/jspcEditProfileCompletion_js"   => "4");
$js_arr[]=array("jspc/seo/seo" => "2");
$js_arr[]=array("jspc/static/static_js"   => "4");
$js_arr[]=array("jspc/login/changePassword_js"   => "4");
$js_arr[]=array("jspc/settings/settings" => "2");
$js_arr[]=array("jspc/settings/jspc_visibility"   => "4");
$js_arr[]=array("jspc/settings/jspc_hideDelete"   => "26");
$js_arr[]=array("jspc/login/resetPassword_js"   => "4");
$js_arr[]=array("jspc/registration/incompleteProfileJspc_js"   => "15");
$js_arr[]=array("jspc/profile/edit/profile/jspcPhoneVerifyBinding_js"   => "5");
$js_arr[]=array("jspc/profile/view/jspcNoProfile_js"   => "4");
$js_arr[]=array("customReg_js"   => "5");
$js_arr[]=array("jspc/common/jquery_mousewheel"   => "4");
$js_arr[]=array("jspc/bounceMail/bounceMailDetection_js"   => "4");
$js_arr[]=array("jspc/contactus/sw"   => "6");
$js_arr[]=array("jsms/settings/mobDeleteProfile_js"   => "19");
$js_arr[]=array("sw"   => "12");
$js_arr[]=array("commonExpiration_js"   => "12");
$js_arr[]=array("main"   => "7");
$js_arr[]=array("jsms/common/verificationIcon_js"   => "6");
$js_arr[]=array("jsms/settings/settings_js"   => "5");
$js_arr[]=array("rippleEffectCommon_js"   => "6");
$js_arr[]=array("jsms/utility/offlineTracking_js"   => "4");
$js_arr[]=array("jsms/common/disableRightClick_js"   => "5");
$js_arr[]=array("jsms/profile/horoscope/horoscope_js"   => "6");
$js_arr[]=array("common_comscore_js"   => "5");
$js_arr[]=array("jspc/chat/chatCommonConfig_js"   => "113");
$js_arr[]=array("jspc/chat/chatPCHelper_js"   => "153");
$js_arr[]=array("jspc/chat/chatPlugin_js"    => "119");
$js_arr[]=array("jspc/chat/strophieWrapper_js"   => "70");
$js_arr[]=array("jspc/chat/chatStrophieClient_js"   => "10");
$js_arr[]=array("jspc/help/JSPCHelp_js"   => "23");
$js_arr[]=array("jsms/help/JSMSHelp_js" => "15");
$js_arr[]=array("jsms/help/jsmsPostQuery_js"   => "9");
$js_arr[]=array("jsms/help/autoPopulateFreshdesk_js"   => "6");
$js_arr[]=array("jsms/myjs/CALJSMS_js"     => "40");
$js_arr[]=array("jspc/chat/customElem"   => "7");
$js_arr[]=array("jspc/chat/strophe_receipts"   => "7");
$js_arr[]=array("-1.0.2/Gruntfile" => "4");
$js_arr[]=array("jspc/chat/enc-utf16"   => "6");
$js_arr[]=array("jspc/chat/enc-base64-min"   => "6");
$js_arr[]=array("jspc/chat/core"   => "6");
$js_arr[]=array("jspc/chat/converse_js" => "4");
$js_arr[]=array("jspc/chat/aes"   => "6");
$js_arr[]=array("/web/converse" => "4");
$js_arr[]=array("reportAbuseForUser_js"   => "19");
$js_arr[]=array("/web/billing/billing_v2" => "7");
$js_arr[]=array("/web/billing/billing" => "5");
$js_arr[]=array("operations_validate2"   => "9");
$js_arr[]=array("jsms/settings/mobHideProfile_js"   => "21");
$js_arr[]=array("jspc/photoUpload/fbPage_js" => "2");
$js_arr[]=array("jspc/promotions/chatPromo/chatPromo_js"      => "8");
$js_arr[]=array("jsms/promotions/chatPromo/chatPromo_js"      => "8");
$js_arr[]=array("sathiForLife_js"   => "11");
$js_arr[]=array("widget"    => "2");
$js_arr[]=array("sulekha"    => "2");
$js_arr[]=array("sugar/sugar_registration_new_page_js"    => "2");
$js_arr[]=array("mini_reg"    => "2");
$js_arr[]=array("mem"    => "2");
$js_arr[]=array("easybill"    => "2");
$js_arr[]=array("chk_drp_v1"    => "2");
$js_arr[]=array("chk_drp"    => "2");
$js_arr[]=array(" /JSNotificationExtension/JSnotification/desktop-notify"    => "2");
$js_arr[]=array("time-tracker"    => "2");
$js_arr[]=array("textbox-hinter"    => "2");
$js_arr[]=array("productmetric/progressbar/bootstrap-progressbar"    => "2");
$js_arr[]=array("productmetric/nicescroll/jquery"    => "2");
$js_arr[]=array("productmetric/jquery"    => "2");
$js_arr[]=array("productmetric/icheck/icheck"    => "2");
$js_arr[]=array("productmetric/datetimePicker/dateTimePicker"    => "2");
$js_arr[]=array("productmetric/custom"    => "2");
$js_arr[]=array("productmetric/chartjs/chart"    => "2");
$js_arr[]=array("productmetric/bootstrap"    => "2");
$js_arr[]=array("mmm_js/writeMail_url"    => "2");
$js_arr[]=array("mmm_js/writeMail_hardcode"    => "2");
$js_arr[]=array("mmm_js/writeMail"    => "2");
$js_arr[]=array("mmm_js/urlMail"    => "2");
$js_arr[]=array("mmm_js/setTestId"    => "2");
$js_arr[]=array("mmm_js/mis"    => "2");
$js_arr[]=array("mmm_js/menu"    => "2");
$js_arr[]=array("mmm_js/hardcodeMail"    => "2");
$js_arr[]=array("mmm_js/formQuery"    => "2");
$js_arr[]=array("mmm_js/fireMenu"    => "2");
$js_arr[]=array("mmm_js/createTable2"    => "2");
$js_arr[]=array("mmm_js/createMailer"    => "2");
$js_arr[]=array("mmm_js/calendar"    => "2");
$js_arr[]=array("mmm_99/formQuery"    => "2");
$js_arr[]=array("mmm_99/99_calendar"    => "2");
$js_arr[]=array("jquery_dateLists"    => "2");
$js_arr[]=array("dns"    => "2");
$js_arr[]=array("crm_common_js"    => "2");
$js_arr[]=array("calendar_js"    => "2");
$js_arr[]=array("autoSuggest_js"    => "2");
$js_arr[]=array("/JSNotificationExtension/JSnotification/client"   => "1");
$js_arr[]=array("jsms/login/uploadDocument_js"    => "2");
$js_arr[]=array("jspc/login/uploadDoc_js"    => "2");
$js_arr[]=array(" /JSNotificationExtension/JSnotification/client"   => "1");
return $js_arr;
}
function getJavascript(){
	$js_arr = getJsFilesArr();
	for($i=0;$i<count($js_arr);$i++)
	{
		$temp=$js_arr[$i];
		foreach($temp as $key=>$val)
				if(!$JAVASCRIPT[$key])
						$JAVASCRIPT[$key]=$key."_".$val.".js";
				else
						die("DUPLICATE JAVACRIPT KEY $key");
	}
	return $JAVASCRIPT;
}
function getJavascriptFileName($jsFile){
        $js_arr = getJsFilesArr();
        for($i=0;$i<count($js_arr);$i++)
        {
                $temp=$js_arr[$i];
                foreach($temp as $key=>$val)
                                if(!$JAVASCRIPT[$key])
                                                $JAVASCRIPT[$key]=$key."_".$val;
                                else
                                                throw new jsException("","Duplicate $key javascript in commonfile");
         }
        return $JAVASCRIPT[$jsFile];
}
function getCss(){
	$css_arr = getCssFilesArr();
	for($i=0;$i<count($css_arr);$i++)
	{
		$temp=$css_arr[$i];
		
		foreach($temp as $key=>$val)
				if(!$CSS[$key])
						$CSS[$key]=$key."_".$val.".css";
				else
						die("DUPLICATE CSS KEY $key");
	}
	return $CSS;
}

function getCssFileName($cssFile){
        $css_arr = getCssFilesArr();
        for($i=0;$i<count($css_arr);$i++)
        {
                $temp=$css_arr[$i];

                foreach($temp as $key=>$val)
                                if(!$CSS[$key])
                                                $CSS[$key]=$key."_".$val;
                                else
                                                throw new jsException("","Duplicate $key css in commonfile");
        }
        return $CSS[$cssFile];
}

function assignVars($JAVASCRIPT,$CSS,$smarty){
	foreach($JAVASCRIPT as $key => $val)
	{
		$smarty->assign("$key","$val");
	}
	foreach($CSS as $key => $val)
	{
	    $smarty->assign("$key","$val");
	}
}

function getCommaSeparatedCSSFileNames($cssArray){
        $css_arr = getCssFilesArr();
        for($i=0;$i<count($css_arr);$i++)
        {
                $temp=$css_arr[$i];

                foreach($temp as $key=>$val)
                                if(!$CSS[$key])
                                                $CSS[$key]=$key."_".$val;
                                else
                                                throw new jsException("","Duplicate $key css in commonfile");
        }
        foreach($cssArray as $key=>$val)
        {
        	$result.='/css/'.$CSS[$val].".css,";
        }
return substr($result,0,-1);
}


function getCommaSeparatedJSFileNames($jsArray){
        $allJsArr = getJsFilesArr();
        for($i=0;$i<count($allJsArr);$i++)
        {
                $temp=$allJsArr[$i];

                foreach($temp as $key=>$val)
                                if(!$JS[$key])
                                                $JS[$key]=$key."_".$val;
                                else
                                                throw new jsException("","Duplicate $key css in commonfile");
        }
        foreach($jsArray as $key=>$val)
        {
        	$result.='/js/'.$JS[$val].".js,";
        }
return substr($result,0,-1);
}

?>
