<?php
/* This script contains all Javascript and CSS files and included in connect.inc to avoide caching problem */
/* CSS File */
function getCssFilesArr(){
$css_arr[]=array("jsms/search/searchform_css"  => "3");
$css_arr[]=array("AppPromo" => "3");
$css_arr[]=array("reg_common_css"  => "23");
$css_arr[]=array("reg_common_new_css"  => "10");
$css_arr[]=array("mini_reg_css"  => "7");
$css_arr[]=array("search_result_css" => "6");
$css_arr[]=array("lightbox_css" => "5");
$css_arr[]=array("myjs_view_similar_css"  => "6");
$css_arr[]=array("colorbox_css"  => "6");
$css_arr[]=array("home_page_style_css"  => "8");
$css_arr[]=array("searchstyle_css" => "5");
$css_arr[]=array("chat_style_css" => "9");
$css_arr[]=array("contact_details_css_css"  => "6");
$css_arr[]=array("eoi_style_css" => "5");
$css_arr[]=array("cropper_css" => "6");
$css_arr[]=array("view_similar_css"  => "7");
$css_arr[]=array("style_css" => "6");
$css_arr[]=array("chromestyle_css" => "5");
$css_arr[]=array("comm_style_css" => "5");
$css_arr[]=array("myjs_incompleteprofile_css" => "5");
$css_arr[]=array("registerstyle_css" => "5");
$css_arr[]=array("landpage_css" => "5");
$css_arr[]=array("dropdown_css" => "5");
$css_arr[]=array("registration_revamp_css" => "5");
$css_arr[]=array("mailstyles_css" => "5");
$css_arr[]=array("registration_dpp_css" => "5");
$css_arr[]=array("hdr_css"  => "13");
$css_arr[]=array("my_js_css"  => "24");
$css_arr[]=array("mem_css"  => "6");
$css_arr[]=array("common_chat" => "6");
$css_arr[]=array("common_css"  => "11");
$css_arr[]=array("hdr_sulekha"  => "6");
$css_arr[]=array("logout_css"  => "7");
$css_arr[]=array("crsl_css1"  => "6");
$css_arr[]=array("slider_css" => "7");
$css_arr[]=array("slider_comm_css" => "5");
$css_arr[]=array("contact_center_css" => "13");
$css_arr[]=array("homepage_style_css"  => "21");
$css_arr[]=array("phonelayerStyle_css"  => "6");
$css_arr[]=array("sugarcrm_common_css" => "5");
$css_arr[]=array("seo_community_css"  => "12");
$css_arr[]=array("call_help_css"  => "7");
$css_arr[]=array("js_photo_studio_style_css"  => "7");
$css_arr[]=array("hdr_css_new"  => "11");
$css_arr[]=array("js_photo_studio_style"  => "8");
$css_arr[]=array("view_page_css"  => "11");
$css_arr[]=array("slider-small"  => "6");
$css_arr[]=array("importPhotos"  => "6");
$css_arr[]=array("profile_layer"  => "9");
$css_arr[]=array("upload" => "5");
$css_arr[]=array("edit_css"  => "10");
$css_arr[]=array("mobilejs_css"  => "15");
$css_arr[]=array("mobilejs_menu_css"  => "6");
$css_arr[]=array("mobilejs_slider_css"  => "6");
$css_arr[]=array("autoSuggest_jq_css" => "5");
$css_arr[]=array("mem_css_css"  => "6");
$css_arr[]=array("chk_drp_css"  => "6");
$css_arr[]=array("common1_css"  => "6");
$css_arr[]=array("tncLayer_css" => "5");
$css_arr[]=array("phoneVerify_css"  => "10");
$css_arr[]=array("cancer_vcare_css"  => "6");
$css_arr[]=array("jslider"  => "6");
$css_arr[]=array("minify" => "5");
$css_arr[]=array("style_search"  => "15");
$css_arr[]=array("transliteration" => "5");
$css_arr[]=array("search_embeded" => "5");
$css_arr[]=array("search_popup_screens"  => "7");
$css_arr[]=array("header-footer"  => "9");
$css_arr[]=array("revamp_filter_css"  => "8");
$css_arr[]=array("registration_page1b_css"  => "8");
$css_arr[]=array("global"  => "7");
$css_arr[]=array("contactEngine_css"  => "9");
$css_arr[]=array("fto_css"  => "6");
$css_arr[]=array("reset_css" => "5");
$css_arr[]=array("edit_layer_css"  => "6");
$css_arr[]=array("jquery_countdown_css"  => "6");
$css_arr[]=array("mobCE_css"  => "9");
$css_arr[]=array("rupeeSymbol_css"  => "6");
$css_arr[]=array("sitemap_css"  => "6");
$css_arr[]=array("photoPrivacyLayer"  => "6");
$css_arr[]=array("success_story_css"  => "6");
$css_arr[]=array("autoSelect_css"  => "9");
$css_arr[]=array("reg_common_mobile_css"  => "5");
$css_arr[]=array("mobilejs_revamp"  => "9");
$css_arr[]=array("mobile_hamburger_css"  => "5");
$css_arr[]=array("mobile_media_css"  => "6");
$css_arr[]=array("mem-interface-css"  => "20");
$css_arr[]=array("SpryAccordion" => "3");
$css_arr[]=array("minify_002" => "8");
$css_arr[]=array("style" => "3");
$css_arr[]=array("content" => "3");
$css_arr[]=array("verticaltabs" => "3");
$css_arr[]=array("photoAlbumMobile"  => "4");
$css_arr[]=array("opera_css" => "4");
$css_arr[]=array("media_css" => "3");
$css_arr[]=array("jsmbPhoneVerifyStyle_css" => "3");
$css_arr[]=array("styles_css" => "3");
$css_arr[]=array("kycAgent_css"  => "4");
$css_arr[]=array("contactus_css"  => "4");
$css_arr[]=array("customReg_css"  => "4");
$css_arr[]=array("show_app_promo_css" => "2");
$css_arr[]=array("myjsnew"  => "3");
$css_arr[]=array("app_promo_css"  => "7");
$css_arr[]=array("photoRequest"  => "4");
$css_arr[]=array("view" => "2");
$css_arr[]=array("view_similar_profile_css"  => "5");
$css_arr[]=array("gnb_css"  => "8");
$css_arr[]=array("moblogin_css"  => "4");
$css_arr[]=array("jsms/profile/ep/mp_css"  => "10");
$css_arr[]=array("mr_common_css" => "5");
$css_arr[]=array("mediaquery_css" => "5");
$css_arr[]=array("swipe_css" => "4");
$css_arr[]=array("revampMobile_common_css"  => "4");
$css_arr[]=array("jsms/myjs/jsmsMyjs_css"    => "23");
$css_arr[]=array("jsms/phone/phoneVerification_css"  => "4");
$css_arr[]=array("jsms/photo/photoswipe"  => "3");
$css_arr[]=array("jsms/common/fonts" => "3");
$css_arr[]=array("jsms/common/commoncss"    => "66");
$css_arr[]=array("jsms/common/mediaquery" => "6");
$css_arr[]=array("jsms/search/srpcss"  => "19");
$css_arr[]=array("jsms/photo/photoup" => "2");
$css_arr[]=array("jsms/membership/revamp_membership_css" => "4");
$css_arr[]=array("jsms/membership/new_revamp_membership_css"    => "18");
$css_arr[]=array("jsms/profile/ep/revamp_edit_profile_css"  => "25");
$css_arr[]=array("jsms/register/regis_css" => "15");
$css_arr[]=array("jsms/register/reg_animate" => "5");
$css_arr[]=array("jsms/profile/viewProfile/jsmsViewProfile_css"  => "28");
$css_arr[]=array("jsms/common/errorBar" => "2");
$css_arr[]=array("jsms/contacts/contact_engine" => "3");
$css_arr[]=array("mobreg_pass_css"  => "4");
$css_arr[]=array("operations_styles" => "2");
$css_arr[]=array("jsms/Seo/seoMobile_css"  => "3");
$css_arr[]=array("jsms/login/newMobLogin_css"  => "21");
$css_arr[]=array("jsms/search/searchdropdown"  => "3");
$css_arr[]=array("jsms/contact_engine/contactEngine"  => "18");
$css_arr[]=array("jsms/hamburger/ham_css" => "4");
$css_arr[]=array("jsms/common/jsmsApp_promo_css"  => "17");
$css_arr[]=array("jsms/settings/settings_css"  => "11");
$css_arr[]=array("jsmsViewProfile_css" => "2");
$css_arr[]=array("mp_css" => "2");
$css_arr[]=array("contactEngine" => "2");
$css_arr[]=array("jsmsApp_promo_css" => "2");
$css_arr[]=array("commoncss" => "2");
$css_arr[]=array("sidenav" => "2");
$css_arr[]=array("operanew" => "2");
$css_arr[]=array("fonts_css" => "2");
$css_arr[]=array("fonts" => "2");
$css_arr[]=array("jsexclusive_style"  => "10");
$css_arr[]=array("helpWidget_css"  => "19");
$css_arr[]=array("jsms/search/savesearchcss" => "11");
$css_arr[]=array("iosprmo" => "3");
$css_arr[]=array("jspc/common/commonJspc_css"       => "42");
$css_arr[]=array("jspc/registration/registrationJspc_css"  => "18");
$css_arr[]=array("jspc/myjs/myjs"    => "41");
$css_arr[]=array("jspc/common/fontsJspc_css"  => "3");
$css_arr[]=array("jspc/common/headerFooterJspc_css"     => "21");
$css_arr[]=array("jspc/search/scrollbar"  => "3");
$css_arr[]=array("jspc/search/srpcss"     => "14");
$css_arr[]=array("jspc/search/jslider"  => "3");
$css_arr[]=array("jspc/common/cssRangeSlider"  => "4");
$css_arr[]=array("jspc/search/rangeslider"  => "3");
$css_arr[]=array("jspc/common/jquerymCustomScrollbar" => "2");
$css_arr[]=array("jspc/search/searchBand"  => "3");
$css_arr[]=array("jspc/profile/edit/dpp/dppEdit_css"  => "38");
$css_arr[]=array("jspc/utility/chosen/chosen_css"  => "3");
$css_arr[]=array("jspc/logout/homecss"  => "11");
$css_arr[]=array("jspc/phone/phoneVerification_css" => "3");
$css_arr[]=array("jspc/common/colorbox_css"  => "3");
$css_arr[]=array("jspc/common/NProgress"  => "5");
$css_arr[]=array("jspc/membership/jspc_mem_css"   => "35");
$css_arr[]=array("jspc/membership/upgrade_mem_css"  => "13");
$css_arr[]=array("jspc/membership/jspc_mem_custom_scrollbar" => "2");
$css_arr[]=array("jspc/membership/jspc_mem_sweetalert"  => "3");
$css_arr[]=array("jspc/membership/jspc_mem_scrollpane" => "2");
$css_arr[]=array("jspc/membership/jspc_mem_custom_select" => "2");
$css_arr[]=array("jspc/photoUpload/photoup_css"  => "11");
$css_arr[]=array("jspc/photoUpload/cropper"  => "3");
$css_arr[]=array("jspc/photoUpload/main"  => "3");
$css_arr[]=array("jspc/inbox/contactCenter"      => "9");
$css_arr[]=array("jspc/success_story/successStory" => "2");
$css_arr[]=array("jspc/contactus/contactus_css"  => "3");
$css_arr[]=array("jspc/profile/view/jspcViewProfile_css"  => "37");
$css_arr[]=array("jspc/profile/edit/profile/jspcEditProfile_css"  => "11");
$css_arr[]=array("jspc/search/advancedSearch"  => "11");
$css_arr[]=array("jspc/faq/feedback" => "2");
$css_arr[]=array("jspc/contactEngine/contactEngine_css"  => "14");
$css_arr[]=array("jspc/profile/edit/profile/jspcCoverPhoto_css"  => "3");
$css_arr[]=array("jspc/profile/edit/profile/jspcEditProfileCompletion_css"  => "3");
$css_arr[]=array("jspc/common/mCustomScrollBar_css"  => "6");
$css_arr[]=array("jspc/profile/view/jspcNoProfile_css"  => "3");
$css_arr[]=array("jspc/seo/seo" => "8");
$css_arr[]=array("jspc/static/static_css"  => "3");
$css_arr[]=array("jspc/settings/settings" => "7");
$css_arr[]=array("jspc/static/kycss"  => "3");
$css_arr[]=array("jspc/commonInterface/VDUpload"  => "3");
$css_arr[]=array("jspc/crm/loader_css"  => "3");
$css_arr[]=array("jeevansathi_css"  => "4");
$css_arr[]=array("jspc/common/3DotLoader"  => "5");
$css_arr[]=array("jsms/common/verificationIcon_css"  => "4");
$css_arr[]=array("rippleEffectCommon_css"  => "4");
$css_arr[]=array("jsms/common/disableRightClick_css"  => "4");
$css_arr[]=array("jsms/profile/horoscope/horoscope_css"  => "3");
$css_arr[]=array("operations/showStatViewProfile_css"  => "3");
$css_arr[]=array("operations/help_module"  => "3");
$css_arr[]=array("jspc/chat/chat_css"  => "17");
$css_arr[]=array("jspc/help/JSPCHelp_css"  => "10");
$css_arr[]=array("jsms/help/JSMSHelp_css"  => "5");
$css_arr[]=array("jsms/myjs/CALJSMS_css"    => "23");
$css_arr[]=array("-1" => "4");
$css_arr[]=array(" /web/js/ /web/profile/css/my_js_css" => "2");
$css_arr[]=array("yatra_style"  => "7");
$css_arr[]=array("promotions/chatPromo/chatPromoMS_css"  => "7");
$css_arr[]=array("promotions/chatPromo/chatPromoPC_css"  => "5");
$css_arr[]=array("sathiForLife_css"  => "11");
$css_arr[]=array("widget/pop_up"   => "1");
$css_arr[]=array("sulekha_css"   => "1");
$css_arr[]=array("sugarcrm_common"   => "1");
$css_arr[]=array("pd_screen"   => "1");
$css_arr[]=array("myjs_vishwas_seal"   => "1");
$css_arr[]=array("myjs"   => "1");
$css_arr[]=array("mini_reg_v1"   => "1");
$css_arr[]=array("mini_reg"   => "1");
$css_arr[]=array("mem"   => "1");
$css_arr[]=array("crsl_css"   => "1");
$css_arr[]=array("common1"   => "1");
$css_arr[]=array("chk_drp"   => "1");
$css_arr[]=array("adr_vrfy"   => "1");
$css_arr[]=array("productmetric/icheck/green"   => "1");
$css_arr[]=array("productmetric/fonts/css/font-awesome"   => "1");
$css_arr[]=array("productmetric/datetimePicker/datetimeCss"   => "1");
$css_arr[]=array("productmetric/custom"   => "1");
$css_arr[]=array("productmetric/bootstrap"   => "1");
$css_arr[]=array("productmetric/animate"   => "1");
$css_arr[]=array("operations_jeevansathi"   => "1");
$css_arr[]=array("mmm_js/jeevansathi"   => "1");
$css_arr[]=array("mmm_js/formQuery_99"   => "1");
$css_arr[]=array("mmm_js/div"   => "1");
$css_arr[]=array("mmm_js/calendar"   => "1");
$css_arr[]=array("mmm_99/table"   => "1");
$css_arr[]=array("mmm_99/jeevansathi"   => "1");
$css_arr[]=array("mmm_99/formQuery"   => "1");
$css_arr[]=array("mmm_99/div"   => "1");
$css_arr[]=array("jspc/photoup"   => "1");
$css_arr[]=array("jquery_dateLists"   => "1");
$css_arr[]=array("calendar_css"   => "1");
$css_arr[]=array("autoSuggest_css"   => "1");
$css_arr[]=array("main"   => "1");
$css_arr[]=array("default"   => "1");
$css_arr[]=array(" /JSNotificationExtension/JSnotification/desktop-notify"   => "1");
return $css_arr;
}
/* JavaScript File */
function getJsFilesArr(){
$js_arr[]=array("jsms/common/scrollTo"  => "3");
$js_arr[]=array("jsms/search/mobSearchDropDown_js"  => "17");
$js_arr[]=array("jsms/search/mobSearchForm_js"  => "6");
$js_arr[]=array("contactEngineNew_js"  => "6");
$js_arr[]=array("registration_ajax_new_js" => "7");
$js_arr[]=array("behaviour_new_js" => "5");
$js_arr[]=array("registration_page1_new_js" => "22");
$js_arr[]=array("registration_new_page_js" => "15");
$js_arr[]=array("registration_js" => "8");
$js_arr[]=array("advance_search_js"  => "9");
$js_arr[]=array("gadget_as_js" => "11");
$js_arr[]=array("behaviour_js" => "5");
$js_arr[]=array("gadget_reg_dpp_js" => "5");
$js_arr[]=array("shared_js" => "5");
$js_arr[]=array("roster_js" => "5");
$js_arr[]=array("config_js" => "6");
$js_arr[]=array("browsercheck_js" => "5");
$js_arr[]=array("new_jsjac_js" => "5");
$js_arr[]=array("revampCommon_js" => "42");
$js_arr[]=array("ajax_revampCommon_js" => "7");
$js_arr[]=array("colorbox"  => "7");
$js_arr[]=array("cluster_js" => "5");
$js_arr[]=array("tooltip_new_js" => "5");
$js_arr[]=array("multiselect_clustering_js" => "5");
$js_arr[]=array("emoticons_js" => "5");
$js_arr[]=array("switchStyle_js" => "5");
$js_arr[]=array("util_v11_js" => "13");
$js_arr[]=array("show_hide_div_js" => "5");
$js_arr[]=array("prototype_js" => "5");
$js_arr[]=array("dragdrop_js" => "5");
$js_arr[]=array("cropper_js"  => "7");
$js_arr[]=array("builder_js" => "5");
$js_arr[]=array("scriptaculous_js" => "5");
$js_arr[]=array("ajax_js"  => "11");
$js_arr[]=array("ivrContact_js"  => "6");
$js_arr[]=array("search_similar_js"  => "10");
$js_arr[]=array("search_js" => "5");
$js_arr[]=array("jspc/search/viewSimilarProfile_js"  => "3");
$js_arr[]=array("jspc/search/jspcMembershipMsg_js"  => "3");
$js_arr[]=array("jspc/search/searchCommon_js"  => "29");
$js_arr[]=array("profile_js" => "5");
$js_arr[]=array("searchhover_js" => "7");
$js_arr[]=array("conf_layer_js" => "5");
$js_arr[]=array("dw_viewport_js" => "5");
$js_arr[]=array("dw_core_js" => "5");
$js_arr[]=array("dw_clip_js" => "5");
$js_arr[]=array("dw_wipes_js" => "5");
$js_arr[]=array("common_js" => "5");
$js_arr[]=array("google_map_api_js" => "5");
$js_arr[]=array("second_js" => "5");
$js_arr[]=array("Debugger_js" => "5");
$js_arr[]=array("chrome_js" => "5");
$js_arr[]=array("leftpanelnew_js" => "5");
$js_arr[]=array("AnchorPosition_js" => "5");
$js_arr[]=array("multiselect_top_js" => "5");
$js_arr[]=array("autosuggest_js" => "6");
$js_arr[]=array("autoSuggest_jq_js" => "9");
$js_arr[]=array("registration_pg1_new_js" => "8");
$js_arr[]=array("balloon_js" => "5");
$js_arr[]=array("banner_slide_js" => "5");
$js_arr[]=array("PopupWindow_js" => "5");
$js_arr[]=array("popunder_js" => "5");
$js_arr[]=array("google2_js" => "5");
$js_arr[]=array("google3_js" => "5");
$js_arr[]=array("google_js" => "5");
$js_arr[]=array("yahoo-dom-event_js" => "5");
$js_arr[]=array("dropdown_js" => "5");
$js_arr[]=array("date_js" => "5");
$js_arr[]=array("headnew_js" => "5");
$js_arr[]=array("incomplete_pg1_js" => "5");
$js_arr[]=array("ivrVerifyPhone_js" => "6");
$js_arr[]=array("removeBookmark_js" => "6");
$js_arr[]=array("registration_new_js" => "6");
$js_arr[]=array("jschat_js" => "10");
$js_arr[]=array("topSearchBand_js"  => "14");
$js_arr[]=array("myjs_js"   => "16");
$js_arr[]=array("mem_v2_js"  => "20");
$js_arr[]=array("mootools_js" => "5");
$js_arr[]=array("slider_js" => "6");
$js_arr[]=array("slider_comm_js" => "5");
$js_arr[]=array("seo_community_js"  => "11");
$js_arr[]=array("calendarpopup_js" => "5");
$js_arr[]=array("payment_js" => "5");
$js_arr[]=array("mini_reg_js"  => "7");
$js_arr[]=array("jquery_dimensions_js" => "5");
$js_arr[]=array("sugar_registration_new_page_js" => "6");
$js_arr[]=array("sugar_registration_page1_new_js" => "9");
$js_arr[]=array("saveDetails"  => "8");
$js_arr[]=array("profileLayer"  => "8");
$js_arr[]=array("Swiff_Uploader" => "5");
$js_arr[]=array("Fx_ProgressBar"  => "6");
$js_arr[]=array("FancyUpload2"  => "6");
$js_arr[]=array("onload" => "5");
$js_arr[]=array("photo_slider"  => "6");
$js_arr[]=array("displayFullImage"  => "6");
$js_arr[]=array("ajax_social"  => "11");
$js_arr[]=array("ajaxMultiThreading"  => "6");
$js_arr[]=array("compUpload_js"  => "9");
$js_arr[]=array("mootools-core-1-3-2-full-compat"  => "6");
$js_arr[]=array("compUploadNoFlash_js"  => "6");
$js_arr[]=array("contact_engine_js"  => "14");
$js_arr[]=array("profile_album_js"  => "12");
$js_arr[]=array("profile_tab_js"  => "16");
$js_arr[]=array("header_js"  => "16");
$js_arr[]=array("homepage_js"  => "8");
$js_arr[]=array("edit_page_js"  => "6");
$js_arr[]=array("city_country_common"  => "9");
$js_arr[]=array("tracking_js"  => "14");
$js_arr[]=array("chk_drp_js"  => "6");
$js_arr[]=array("viewSimilar_js"  => "9");
$js_arr[]=array("textbox_hinter"  => "6");
$js_arr[]=array("emailchecks"  => "6");
$js_arr[]=array("phoneVerify_js"  => "25");
$js_arr[]=array("tncLayer_js"  => "7");
$js_arr[]=array("jquery-dependClass"  => "6");
$js_arr[]=array("jquery-slider"  => "6");
$js_arr[]=array("jshashtable_src"  => "6");
$js_arr[]=array("tmpl"  => "6");
$js_arr[]=array("draggable"  => "6");
$js_arr[]=array("fadeslideshow"  => "6");
$js_arr[]=array("searchPage_js"  => "38");
$js_arr[]=array("loginSearch"  => "14");
$js_arr[]=array("albumLayer_js"  => "9");
$js_arr[]=array("json2"  => "6");
$js_arr[]=array("revamp_filter_js"  => "10");
$js_arr[]=array("reg_page1b_js"  => "7");
$js_arr[]=array("contactEngineLayer_js"  => "15");
$js_arr[]=array("jquery_countdown_js"  => "6");
$js_arr[]=array("mobCE_js"  => "6");
$js_arr[]=array("fto_js"  => "6");
$js_arr[]=array("mobSEO_js"  => "7");
$js_arr[]=array("sstory_js"  => "7");
$js_arr[]=array("jspc/crm/uploadVD_js"  => "3");
$js_arr[]=array("jspc/crm/pendingFieldVisits_js"  => "4");
$js_arr[]=array("jspc/crm/requestFieldVisit_js"  => "4");
$js_arr[]=array("jspc/crm/dateSelectionField_js"  => "4");
$js_arr[]=array("jspc/crm/exclusiveMemAllocation_js"  => "6");
$js_arr[]=array("jspc/crm/loader_js"  => "5");
$js_arr[]=array("jspc/crm/exclusiveServicingII_js"  => "8");
$js_arr[]=array("jspc/crm/changeActiveServiceInterface_js"  => "12");
$js_arr[]=array("jquery_cookie_js"  => "6");
$js_arr[]=array("registration_revamp_js"  => "17");
$js_arr[]=array("jquery_validate_js"  => "4");
$js_arr[]=array("register_common_all_js"  => "4");
$js_arr[]=array("autoSelect_js"  => "5");
$js_arr[]=array("autoMobileSelect_js"  => "5");
$js_arr[]=array("selectType_js"  => "13");
$js_arr[]=array("reg_page2_js"  => "12");
$js_arr[]=array("jsmb_page4_js"  => "13");
$js_arr[]=array("reg_page4_js"  => "4");
$js_arr[]=array("mini_reg_revamp_js"  => "4");
$js_arr[]=array("regPage5_js"  => "6");
$js_arr[]=array("mobselectType_js"  => "4");
$js_arr[]=array("html5_js"  => "5");
$js_arr[]=array("reg_page1_js"  => "11");
$js_arr[]=array("jsmb_page1_js"  => "5");
$js_arr[]=array("jsmb_page2_js"  => "4");
$js_arr[]=array("jsmb_page3_js"  => "7");
$js_arr[]=array("reg_page3_js"  => "5");
$js_arr[]=array("noautoSelect_js"  => "4");
$js_arr[]=array("modernizr_js"  => "4");
$js_arr[]=array("modernizr_p_js"  => "5");
$js_arr[]=array("boomerang_js"  => "4");
$js_arr[]=array("boomerang_tracking_js"  => "4");
$js_arr[]=array("SpryAccordion" => "3");
$js_arr[]=array("verticaltabs_pack_js" => "3");
$js_arr[]=array("memJS" => "17");
$js_arr[]=array("memCommonJS" => "11");
$js_arr[]=array("valueAddedJS"  => "18");
$js_arr[]=array("paymentOptions"  => "32");
$js_arr[]=array("jquery_cookie"  => "4");
$js_arr[]=array("mobHamburger_js"  => "10");
$js_arr[]=array("jquery_touch"  => "4");
$js_arr[]=array("mobAlbum"  => "4");
$js_arr[]=array("mobPhotoUpload"  => "5");
$js_arr[]=array("commonMob"  => "4");
$js_arr[]=array("mobBrowser_js" => "3");
$js_arr[]=array("mobSearchBand"  => "6");
$js_arr[]=array("app_promo_js"  => "62");
$js_arr[]=array("selectType_Page3_js"  => "4");
$js_arr[]=array("editNativePlace_js"  => "9");
$js_arr[]=array("mobNative_Place_selectType_js"  => "4");
$js_arr[]=array("jsmb_page5_js"  => "4");
$js_arr[]=array("mobprofile_js"  => "5");
$js_arr[]=array("jquery"  => "3");
$js_arr[]=array("zedo"  => "17");
$js_arr[]=array("view" => "2");
$js_arr[]=array("view_similar_profile_js"  => "4");
$js_arr[]=array("assisted_product" => "2");
$js_arr[]=array("pixel_js"  => "4");
$js_arr[]=array("mouseClickTracking_js"  => "4");
$js_arr[]=array("jsms/profile/ep/submitDetails_js"  => "44");
$js_arr[]=array("jsms/profile/ep/hamburger_js"  => "48");
$js_arr[]=array("jsms/profile/ep/mobedit_js"        => "66");
$js_arr[]=array("jsms/profile/ep/mobeditview_js"  => "87");
$js_arr[]=array("jsms/profile/ep/mobShow_name_js"  => "10");
$js_arr[]=array("jsms/common/disableScroll_js"  => "6");
$js_arr[]=array("jsms/utility/sessionStorage_js"  => "9");
$js_arr[]=array("jsms/myjs/touchswipemyjs_js" => "22");
$js_arr[]=array("jsms/myjs/myjs_js"     => "78");
$js_arr[]=array("showHide_js"  => "4");
$js_arr[]=array("showHideReg_js"  => "4");
$js_arr[]=array("operations_validate1"  => "9");
$js_arr[]=array("jsms/photo/mobPhotoAlbum_photoswipe"  => "5");
$js_arr[]=array("jsms/photo/mobPhotoAlbum_panzoom"  => "3");
$js_arr[]=array("jsms/photo/mobPhotoAlbum_photoSwipeInheritence"  => "3");
$js_arr[]=array("jsms/profile/ep/mobedit_validator_js"  => "26");
$js_arr[]=array("js_common"  => "4");
$js_arr[]=array("mobBrowser_js_2"  => "4");
$js_arr[]=array("jsms/membership/jquery_sly" => "3");
$js_arr[]=array("jquery_ui_min" => "3");
$js_arr[]=array("jsms/membership/jquery_animateNumber" => "2");
$js_arr[]=array("jsms/photo/photo_upload_js"  => "10");
$js_arr[]=array("jsms/photo/photo_privacy_js"  => "3");
$js_arr[]=array("jsms/membership/shimmer_js" => "2");
$js_arr[]=array("jsms/utility/vSlider_js"  => "18");
$js_arr[]=array("jsms/utility/hamSearch_js"  => "14");
$js_arr[]=array("jsms/membership/revamp_mobile_membership" => "6");
$js_arr[]=array("jsms/phone/phone_js"  => "27");
$js_arr[]=array("jsms/membership/new_revamp_mobile_membership"  => "23");
$js_arr[]=array("jsms/membership/new_revamp_mobile_payment"  => "14");
$js_arr[]=array("jsms/membership/jsms_upgrade_js"  => "10");
$js_arr[]=array("jsms/profile/ep/mobeditsave_js"  => "33");
$js_arr[]=array("jsms/photo/mobPhotoUpload_v1"  => "10");
$js_arr[]=array("jsms/search/relaxCriteria_v1"  => "3");
$js_arr[]=array("jsms/photo/mobPhotoAlbum_v1"  => "4");
$js_arr[]=array("jsms/photo/mobPhotoUploadCommon_js"  => "3");
$js_arr[]=array("jsms/common/urlParamHandling"  => "3");
$js_arr[]=array("jsms/common/CommonFunctions"           => "73");
$js_arr[]=array("jsms/common/touchswipe_js"  => "5");
$js_arr[]=array("jsms/common/history_js"  => "9");
$js_arr[]=array("jsms/photo/photoRequestCommon_js"  => "4");
$js_arr[]=array("jsms/search/jqueryInfiniteScroll"  => "68");
$js_arr[]=array("jsms/search/JsmsSearch"  => "4");
$js_arr[]=array("jsms/search/MobileSearchCommon"  => "4");
$js_arr[]=array("jsms/angular/registration/lib/angular_min" => "2");
$js_arr[]=array("jsms/angular/registration/lib/angular-animate_min" => "2");
$js_arr[]=array("jsms/angular/registration/lib/angular-resource_min" => "2");
$js_arr[]=array("jsms/angular/registration/lib/angular-route_min" => "2");
$js_arr[]=array("jsms/angular/registration/lib/angular-touch_min" => "2");
$js_arr[]=array("jsms/angular/registration/scripts/app" => "5");
$js_arr[]=array("jsms/angular/registration/scripts/controllers"  => "44");
$js_arr[]=array("jsms/angular/registration/scripts/services" => "6");
$js_arr[]=array("jsms/angular/registration/scripts/directives" => "27");
$js_arr[]=array("jsms/angular/registration/scripts/factories"  => "53");
$js_arr[]=array("jsms/angular/registration/hamburger_reg_js"  => "34");
$js_arr[]=array("jsms/contact_engine/contactEngine_js"       => "97");
$js_arr[]=array("jsms/profile/viewProfile/jsmsViewProfile_js"      => "48");
$js_arr[]=array("jsms/search/inview"  => "4");
$js_arr[]=array("jsms/login/newMobLogin_js"   => "64");
$js_arr[]=array("jsms/login/mobForgotPass_js"  => "15");
$js_arr[]=array("jsms/login/resetPass_js"  => "4");
$js_arr[]=array("jsms/hamburger/ham_js"  => "52");
$js_arr[]=array("jsms/settings/mobChangePass_js"  => "4");
$js_arr[]=array("jsms/404/mob404_js" => "2");
$js_arr[]=array("jsms/search/searchByProfileId_js"  => "7");
$js_arr[]=array("vSlider_js" => "2");
$js_arr[]=array("sessionStorage_js" => "2");
$js_arr[]=array("mobChangePass_js" => "2");
$js_arr[]=array("mobSearchForm_js" => "2");
$js_arr[]=array("jqueryInfiniteScroll" => "2");
$js_arr[]=array("jsmsViewProfile_js" => "3");
$js_arr[]=array("mobedit_js" => "2");
$js_arr[]=array("photoRequestCommon_js" => "2");
$js_arr[]=array("newMobLogin_js" => "3");
$js_arr[]=array("mobForgotPass_js" => "2");
$js_arr[]=array("ham_js" => "2");
$js_arr[]=array("contactEngine_js" => "2");
$js_arr[]=array("history_js" => "2");
$js_arr[]=array("CommonFunctions" => "2");
$js_arr[]=array("factories" => "2");
$js_arr[]=array("controllers" => "3");
$js_arr[]=array("app" => "2");
$js_arr[]=array("hamburger_reg_js" => "2");
$js_arr[]=array("touchswipemyjs_js" => "2");
$js_arr[]=array("touchswipe_js" => "2");
$js_arr[]=array("timetracker_js"  => "3");
$js_arr[]=array("hamburger_js" => "2");
$js_arr[]=array("resetPass_js" => "2");
$js_arr[]=array("jsms/search/viewSimilarMax"  => "6");
$js_arr[]=array("helpWidget_js"  => "23");
$js_arr[]=array("advance_search"  => "3");
$js_arr[]=array("jsms/search/overlayLayerJsms"  => "5");
$js_arr[]=array("jsms/search/savesearch_js"  => "10");
$js_arr[]=array("sugar/sugar_registration_page1_new_js"  => "5");
$js_arr[]=array("app_promo"  => "5");
$js_arr[]=array("sugar/registration_page1_new" => "4");
$js_arr[]=array("registration_pg2" => "4");
$js_arr[]=array("registration_pg1" => "4");
$js_arr[]=array("jsms/contactus/contactus_js" => "2");
$js_arr[]=array("jsms/common/sly"  => "4");
$js_arr[]=array("jspc/myjs/myjs_js"  => "92");
$js_arr[]=array("jspc/myjs/myjs_pcrevamp"    => "115");
$js_arr[]=array("jspc/myjs/engBarJs_js"  => "41");
$js_arr[]=array("jspc/common/nano"  => "6");
$js_arr[]=array("jspc/registration/registrationJspc_js"  => "43");
$js_arr[]=array("jspc/registration/validation_js"  => "35");
$js_arr[]=array("jspc/common/commonJspc_js"             => "58");
$js_arr[]=array("jspc/search/hslider" => "2");
$js_arr[]=array("jspc/search/jquery_1_9_0_min" => "2");
$js_arr[]=array("jspc/search/test1" => "2");
$js_arr[]=array("jspc/search/scrollBar"  => "3");
$js_arr[]=array("jspc/common/searchDropdown_js"  => "7");
$js_arr[]=array("jspc/search/searchTuples"  => "13");
$js_arr[]=array("jspc/search/jspcSuccessStory_js"  => "3");
$js_arr[]=array("jspc/inbox/contactCenter"         => "61");
$js_arr[]=array("jspc/common/jqueryRangeSlider"  => "4");
$js_arr[]=array("jspc/search/inview"  => "3");
$js_arr[]=array("jspc/photo/photoRequest_js"  => "7");
$js_arr[]=array("jspc/common/jquery_equalheights" => "2");
$js_arr[]=array("jspc/common/photoAlbum"  => "10");
$js_arr[]=array("jspc/search/saveSearch"  => "3");
$js_arr[]=array("jspc/search/relaxCriteria"  => "3");
$js_arr[]=array("jspc/search/search"  => "56");
$js_arr[]=array("jspc/search/searchClusters"  => "5");
$js_arr[]=array("jspc/search/searchBand"  => "5");
$js_arr[]=array("jspc/search/searchDropdowns"  => "5");
$js_arr[]=array("jspc/search/common/commonSlider"  => "3");
$js_arr[]=array("jspc/search/searchSliders"  => "3");
$js_arr[]=array("jspc/search/common/ionRangeSliderPlugin"  => "3");
$js_arr[]=array("jspc/common/jquerymCustomScrollbarConcat" => "2");
$js_arr[]=array("jspc/profile/edit/dpp/jspcDppEdit_js"  => "60");
$js_arr[]=array("jspc/utility/chosen/chosen_jquery" => "32");
$js_arr[]=array("jspc/utility/chosen/docsupport/prism" => "2");
$js_arr[]=array("jspc/logout/hpjs"  => "5");
$js_arr[]=array("jspc/common/hslider"  => "3");
$js_arr[]=array("jspc/common/test1"  => "3");
$js_arr[]=array("jspc/common/AjaxWrapper"  => "32");
$js_arr[]=array("jspc/phone/phone_js" => "3");
$js_arr[]=array("jspc/common/colorbox"  => "3");
$js_arr[]=array("jspc/common/phoneVeriLayers_js"  => "19");
$js_arr[]=array("jspc/membership/jspc_mem_custom_scrollbar" => "2");
$js_arr[]=array("jspc/membership/jspc_mem_slider" => "2");
$js_arr[]=array("jspc/membership/jspc_mem_js" => "40");
$js_arr[]=array("jspc/membership/upgrade_mem_js"  => "21");
$js_arr[]=array("jspc/membership/jspc_mem_sweetalert"  => "3");
$js_arr[]=array("jspc/membership/jspc_mem_scrollpane" => "2");
$js_arr[]=array("jspc/membership/jspc_mem_mousewheel" => "2");
$js_arr[]=array("jspc/membership/jspc_mem_select_box" => "2");
$js_arr[]=array("jspc/membership/jspc_mem_md5"  => "3");
$js_arr[]=array("jspc/login/loginLayer_js"  => "55");
$js_arr[]=array("jspc/photoUpload/photoUpload_js"  => "3");
$js_arr[]=array("jspc/photoUpload/addPhoto_js"  => "32");
$js_arr[]=array("jspc/photoUpload/importPhotoAlbum_js"  => "11");
$js_arr[]=array("jspc/photoUpload/compUpload_js"  => "8");
$js_arr[]=array("jspc/photoUpload/cropper"  => "3");
$js_arr[]=array("jspc/photoUpload/main"  => "10");
$js_arr[]=array("jspc/photoUpload/bootstrap"  => "3");
$js_arr[]=array("jspc/photoUpload/tooltip"  => "3");
$js_arr[]=array("jspc/photoUpload/photoFunctions_js"  => "16");
$js_arr[]=array("jspc/common/urlHandling"  => "15");
$js_arr[]=array("jspc/success_story/imagefit" => "2");
$js_arr[]=array("jspc/contactus/contactus_js"  => "3");
$js_arr[]=array("jspc/success_story/successScroll" => "2");
$js_arr[]=array("jspc/profile/edit/profile/jspcEditProfile_js"   => "119");
$js_arr[]=array("jspc/profile/view/jspcViewProfile_js"        => "76");
$js_arr[]=array("jspc/success_story/foggy"  => "3");
$js_arr[]=array("jspc/success_story/resizeIe"  => "3");
$js_arr[]=array("jspc/contactEngine/contactEngine"     => "65");
$js_arr[]=array("jspc/contactEngine/contactEngineButtons"  => "31");
$js_arr[]=array("jspc/search/advancedSearch"  => "24");
$js_arr[]=array("jspc/common/jquery_mCustomScrollbar"  => "15");
$js_arr[]=array("jspc/success_story/jqueryFilestyle"  => "3");
$js_arr[]=array("jspc/profile/edit/profile/jspcCoverPhoto_js"  => "3");
$js_arr[]=array("jspc/profile/edit/profile/jspcEditProfileCompletion_js"  => "3");
$js_arr[]=array("jspc/seo/seo" => "2");
$js_arr[]=array("jspc/static/static_js"  => "3");
$js_arr[]=array("jspc/login/changePassword_js"  => "3");
$js_arr[]=array("jspc/settings/settings" => "2");
$js_arr[]=array("jspc/settings/jspc_visibility"  => "3");
$js_arr[]=array("jspc/settings/jspc_hideDelete"  => "25");
$js_arr[]=array("jspc/login/resetPassword_js"  => "3");
$js_arr[]=array("jspc/registration/incompleteProfileJspc_js"  => "14");
$js_arr[]=array("jspc/profile/edit/profile/jspcPhoneVerifyBinding_js"  => "4");
$js_arr[]=array("jspc/profile/view/jspcNoProfile_js"  => "3");
$js_arr[]=array("customReg_js"  => "4");
$js_arr[]=array("jspc/common/jquery_mousewheel"  => "3");
$js_arr[]=array("jspc/bounceMail/bounceMailDetection_js"  => "3");
$js_arr[]=array("jspc/contactus/sw"  => "5");
$js_arr[]=array("jsms/settings/mobDeleteProfile_js"  => "18");
$js_arr[]=array("sw"  => "11");
$js_arr[]=array("commonExpiration_js"  => "11");
$js_arr[]=array("main"  => "6");
$js_arr[]=array("jsms/common/verificationIcon_js"  => "5");
$js_arr[]=array("jsms/settings/settings_js"  => "4");
$js_arr[]=array("rippleEffectCommon_js"  => "5");
$js_arr[]=array("jsms/utility/offlineTracking_js"  => "3");
$js_arr[]=array("jsms/common/disableRightClick_js"  => "4");
$js_arr[]=array("jsms/profile/horoscope/horoscope_js"  => "5");
$js_arr[]=array("common_comscore_js"  => "4");
$js_arr[]=array("jspc/chat/chatCommonConfig_js"  => "112");
$js_arr[]=array("jspc/chat/chatPCHelper_js"  => "152");
$js_arr[]=array("jspc/chat/chatPlugin_js"   => "118");
$js_arr[]=array("jspc/chat/strophieWrapper_js"  => "69");
$js_arr[]=array("jspc/chat/chatStrophieClient_js"  => "9");
$js_arr[]=array("jspc/help/JSPCHelp_js"  => "22");
$js_arr[]=array("jsms/help/JSMSHelp_js" => "15");
$js_arr[]=array("jsms/help/jsmsPostQuery_js"  => "8");
$js_arr[]=array("jsms/help/autoPopulateFreshdesk_js"  => "5");
$js_arr[]=array("jsms/myjs/CALJSMS_js"    => "39");
$js_arr[]=array("jspc/chat/customElem"  => "6");
$js_arr[]=array("jspc/chat/strophe_receipts"  => "6");
$js_arr[]=array("-1.0.2/Gruntfile" => "4");
$js_arr[]=array("jspc/chat/enc-utf16"  => "5");
$js_arr[]=array("jspc/chat/enc-base64-min"  => "5");
$js_arr[]=array("jspc/chat/core"  => "5");
$js_arr[]=array("jspc/chat/converse_js" => "4");
$js_arr[]=array("jspc/chat/aes"  => "5");
$js_arr[]=array("/web/converse" => "4");
$js_arr[]=array("reportAbuseForUser_js"  => "18");
$js_arr[]=array("/web/billing/billing_v2" => "7");
$js_arr[]=array("/web/billing/billing" => "5");
$js_arr[]=array("operations_validate2"  => "8");
$js_arr[]=array("jsms/settings/mobHideProfile_js"  => "20");
$js_arr[]=array("jspc/photoUpload/fbPage_js" => "2");
$js_arr[]=array("jspc/promotions/chatPromo/chatPromo_js"     => "7");
$js_arr[]=array("jsms/promotions/chatPromo/chatPromo_js"     => "7");
$js_arr[]=array("sathiForLife_js"  => "10");
$js_arr[]=array("widget"   => "1");
$js_arr[]=array("sulekha"   => "1");
$js_arr[]=array("sugar/sugar_registration_new_page_js"   => "1");
$js_arr[]=array("mini_reg"   => "1");
$js_arr[]=array("mem"   => "1");
$js_arr[]=array("easybill"   => "1");
$js_arr[]=array("chk_drp_v1"   => "1");
$js_arr[]=array("chk_drp"   => "1");
$js_arr[]=array(" /JSNotificationExtension/JSnotification/desktop-notify"   => "1");
$js_arr[]=array("time-tracker"   => "1");
$js_arr[]=array("textbox-hinter"   => "1");
$js_arr[]=array("productmetric/progressbar/bootstrap-progressbar"   => "1");
$js_arr[]=array("productmetric/nicescroll/jquery"   => "1");
$js_arr[]=array("productmetric/jquery"   => "1");
$js_arr[]=array("productmetric/icheck/icheck"   => "1");
$js_arr[]=array("productmetric/datetimePicker/dateTimePicker"   => "1");
$js_arr[]=array("productmetric/custom"   => "1");
$js_arr[]=array("productmetric/chartjs/chart"   => "1");
$js_arr[]=array("productmetric/bootstrap"   => "1");
$js_arr[]=array("mmm_js/writeMail_url"   => "1");
$js_arr[]=array("mmm_js/writeMail_hardcode"   => "1");
$js_arr[]=array("mmm_js/writeMail"   => "1");
$js_arr[]=array("mmm_js/urlMail"   => "1");
$js_arr[]=array("mmm_js/setTestId"   => "1");
$js_arr[]=array("mmm_js/mis"   => "1");
$js_arr[]=array("mmm_js/menu"   => "1");
$js_arr[]=array("mmm_js/hardcodeMail"   => "1");
$js_arr[]=array("mmm_js/formQuery"   => "1");
$js_arr[]=array("mmm_js/fireMenu"   => "1");
$js_arr[]=array("mmm_js/createTable2"   => "1");
$js_arr[]=array("mmm_js/createMailer"   => "1");
$js_arr[]=array("mmm_js/calendar"   => "1");
$js_arr[]=array("mmm_99/formQuery"   => "1");
$js_arr[]=array("mmm_99/99_calendar"   => "1");
$js_arr[]=array("jquery_dateLists"   => "1");
$js_arr[]=array("dns"   => "1");
$js_arr[]=array("crm_common_js"   => "1");
$js_arr[]=array("calendar_js"   => "1");
$js_arr[]=array("autoSuggest_js"   => "1");
$js_arr[]=array("/JSNotificationExtension/JSnotification/client"   => "1");
return $js_arr;
}
function getJavascript(){
	$js_arr = getJsFilesArr();
	for($i=0;$i<count($js_arr);$i++)
	{
		$temp=$js_arr[$i];
		foreach($temp as $key=>$val)
				if(!$JAVASCRIPT[$key])
						$JAVASCRIPT[$key]=$key."_".$val.".js";
				else
						die("DUPLICATE JAVACRIPT KEY $key");
	}
	return $JAVASCRIPT;
}
function getJavascriptFileName($jsFile){
        $js_arr = getJsFilesArr();
        for($i=0;$i<count($js_arr);$i++)
        {
                $temp=$js_arr[$i];
                foreach($temp as $key=>$val)
                                if(!$JAVASCRIPT[$key])
                                                $JAVASCRIPT[$key]=$key."_".$val;
                                else
                                                throw new jsException("","Duplicate $key javascript in commonfile");
         }
        return $JAVASCRIPT[$jsFile];
}
function getCss(){
	$css_arr = getCssFilesArr();
	for($i=0;$i<count($css_arr);$i++)
	{
		$temp=$css_arr[$i];
		
		foreach($temp as $key=>$val)
				if(!$CSS[$key])
						$CSS[$key]=$key."_".$val.".css";
				else
						die("DUPLICATE CSS KEY $key");
	}
	return $CSS;
}

function getCssFileName($cssFile){
        $css_arr = getCssFilesArr();
        for($i=0;$i<count($css_arr);$i++)
        {
                $temp=$css_arr[$i];

                foreach($temp as $key=>$val)
                                if(!$CSS[$key])
                                                $CSS[$key]=$key."_".$val;
                                else
                                                throw new jsException("","Duplicate $key css in commonfile");
        }
        return $CSS[$cssFile];
}

function assignVars($JAVASCRIPT,$CSS,$smarty){
	foreach($JAVASCRIPT as $key => $val)
	{
		$smarty->assign("$key","$val");
	}
	foreach($CSS as $key => $val)
	{
	    $smarty->assign("$key","$val");
	}
}

function getCommaSeparatedCSSFileNames($cssArray){
        $css_arr = getCssFilesArr();
        for($i=0;$i<count($css_arr);$i++)
        {
                $temp=$css_arr[$i];

                foreach($temp as $key=>$val)
                                if(!$CSS[$key])
                                                $CSS[$key]=$key."_".$val;
                                else
                                                throw new jsException("","Duplicate $key css in commonfile");
        }
        foreach($cssArray as $key=>$val)
        {
        	$result.='/css/'.$CSS[$val].".css,";
        }
return substr($result,0,-1);
}


function getCommaSeparatedJSFileNames($jsArray){
        $allJsArr = getJsFilesArr();
        for($i=0;$i<count($allJsArr);$i++)
        {
                $temp=$allJsArr[$i];

                foreach($temp as $key=>$val)
                                if(!$JS[$key])
                                                $JS[$key]=$key."_".$val;
                                else
                                                throw new jsException("","Duplicate $key css in commonfile");
        }
        foreach($jsArray as $key=>$val)
        {
        	$result.='/js/'.$JS[$val].".js,";
        }
return substr($result,0,-1);
}

?>
