<?php
include("connect.inc");
connect_db();

$data=authenticated($checksum);

if($CMDSubmit)
{
	if(trim($name)=="")
        {
                $error++;
                $smarty->assign("FLAG_NAME","R");
        }
        if(trim($day)=="")
        {
                $error++;
                $smarty->assign("FLAG_DOB","R");
        }
        if(trim($month)=="")
        {
                $error++;
                $smarty->assign("FLAG_DOB","R");
        }
        if(trim($year)=="")
        {
                $error++;
                $smarty->assign("FLAG_DOB","R");
        }
        if(trim($city)=="")
        {
                $error++;
                $smarty->assign("FLAG_CITY","R");
        }
        if(trim($state)=="")
        {
                $error++;
                $smarty->assign("FLAG_STATE","R");
        }
        if(trim($country)=="")
        {
                $error++;
                $smarty->assign("FLAG_COUNTRY","R");
        }
	if(trim($pname)=="")
        {
                $error++;
                $smarty->assign("FLAG_PNAME","R");
        }
        if(trim($pday)=="")
        {
                $error++;
                $smarty->assign("FLAG_PDOB","R");
        }
        if(trim($pmonth)=="")
        {
                $error++;
                $smarty->assign("FLAG_PDOB","R");
        }
        if(trim($pyear)=="")
        {
                $error++;
                $smarty->assign("FLAG_PDOB","R");
        }
        if(trim($pcity)=="")
        {
                $error++;
                $smarty->assign("FLAG_PCITY","R");
        }
        if(trim($pstate)=="")
        {
                $error++;
                $smarty->assign("FLAG_PSTATE","R");
        }
        if(trim($pcountry)=="")
        {
                $error++;
                $smarty->assign("FLAG_PCOUNTRY","R");
        }
	if(trim($email)=="")
        {
                $error++;
                $smarty->assign("FLAG_EMAIL","R");
        }

	if($report_format=="PDF")
        {
                if(checkemail($email)==1)
                {
                        $error++;
                        $smarty->assign("FLAG_EMAIL","R");
                }
        }

        if($error==0)
        {
                $dob=$year."-".$month."-".$day;
                $tob=$hour.":".$minute;
                $pdob=$pyear."-".$pmonth."-".$pday;
                $ptob=$phour.":".$pminute;
                $sql="INSERT INTO ASTROL_MATCH(NAME,GENDER,DOB,TOB,B_CITY,B_STATE,B_COUNTRY,PNAME,PGENDER,PDOB,PTOB,PB_CITY,PB_STATE,PB_COUNTRY,RPTFORMAT,PTYPE,EMAIL) VALUES('$name','$gender','$dob','$tob','$city','$state','$country','$pname','$pgender','$pdob','$ptob','$pcity','$pstate','$pcountry','$report_format','$MOP','$email')";
                mysql_query_decide($sql) or logError("Due to a temporary problem your request could not be processed. Please try after a couple of minutes",$sql,"ShowErrTemplate");

		$smarty->assign("CHECKSUM",$checksum);
		$smarty->assign("HEAD",$smarty->fetch("head.htm"));
		$smarty->assign("FOOT",$smarty->fetch("foot.htm"));
		$smarty->assign("SUBFOOTER",$smarty->fetch("subfooter.htm"));
		$smarty->assign("TOPLEFT",$smarty->fetch("topleft.htm"));
		$smarty->assign("LEFTPANEL",$smarty->fetch("leftpanel.htm"));
		
                $smarty->display("astro_continue.htm");
        }
        if($error>0)
        {
                for($i=1;$i<=32;$i++)
                {
                        $dtarr[$i]=$i;
                }
                for($i=1;$i<=13;$i++)
                {
                        $mmarr[$i]=$i;
                }
                for($i=1925;$i<=2001;$i++)
                {
                        $j=$i-1924;
                        $yyarr[$j]=$i;
                }
                for($i=0;$i<24;$i++)
                {
                        if($i<10)
                        {
                                $hharr[$i]="0".$i;
                        }
                        else
                        {
                                $hharr[$i]=$i;
                        }
                }
                for($i=1;$i<=60;$i++)
                {
                        $minarr[$i]=$i;
                }

                $smarty->assign("day",$day);
                $smarty->assign("year",$year);
                $smarty->assign("month",$month);
                $smarty->assign("hour",$hour);
                $smarty->assign("minute",$minute);
                $smarty->assign("name",$name);
                $smarty->assign("city",$city);
                $smarty->assign("state",$state);
                $smarty->assign("country",$country);
                $smarty->assign("pday",$pday);
                $smarty->assign("pyear",$pyear);
                $smarty->assign("pmonth",$pmonth);
                $smarty->assign("phour",$phour);
                $smarty->assign("pminute",$pminute);
                $smarty->assign("pname",$pname);
                $smarty->assign("pcity",$pcity);
                $smarty->assign("pstate",$pstate);
                $smarty->assign("pcountry",$pcountry);
                $smarty->assign("email",$email);
                $smarty->assign("gender",$gender);
                $smarty->assign("report_format",$report_format);
                $smarty->assign("MOP",$MOP);

                $smarty->assign("dtarr",$dtarr);
                $smarty->assign("mmarr",$mmarr);
                $smarty->assign("yyarr",$yyarr);
                $smarty->assign("hharr",$hharr);
                $smarty->assign("minarr",$minarr);

                $smarty->assign("HEAD",$smarty->fetch("head.htm"));
                $smarty->assign("SUBFOOTER",$smarty->fetch("subfooter.htm"));
                $smarty->assign("FOOT",$smarty->fetch("foot.htm"));

                $smarty->display("order_match_astrol.htm");
        }
}
else
{
        for($i=0;$i<31;$i++)
        {
                $dtarr[$i]=$i+1;
        }
        for($i=0;$i<12;$i++)
        {
                $mmarr[$i]=$i+1;
        }
        for($i=0;$i<75;$i++)
        {
                $yyarr[$i]=$i+1925;
        }
        for($i=0;$i<24;$i++)
        {
                if($i<10)
                {
                        $hharr[$i]="0".$i;
                }
                else
                {
                        $hharr[$i]=$i;
                }
        }
        for($i=0;$i<60;$i++)
        {
                $minarr[$i]=$i;
        }

	$smarty->assign("day",1);
	$smarty->assign("month",1);
	$smarty->assign("year",1980);
	$smarty->assign("hour","00");
	$smarty->assign("minute","0");
	$smarty->assign("pday",1);
	$smarty->assign("pmonth",1);
	$smarty->assign("pyear",1980);
	$smarty->assign("phour","00");
	$smarty->assign("pminute","0");

        $smarty->assign("dtarr",$dtarr);
        $smarty->assign("mmarr",$mmarr);
        $smarty->assign("yyarr",$yyarr);
        $smarty->assign("hharr",$hharr);
        $smarty->assign("minarr",$minarr);
        $smarty->assign("HEAD",$smarty->fetch("head.htm"));
        $smarty->assign("SUBFOOTER",$smarty->fetch("subfooter.htm"));
        $smarty->assign("FOOT",$smarty->fetch("foot.htm"));

        $smarty->display("order_match_astrol.htm");
}
?>
