<?php
/*
Author: @Esha
*/
include_once("SymfonyPictureFunctions.class.php");
include_once "connect.inc";
connect_db();
echo $sql1 = "SELECT PROFILEID,ID FROM FTO.FTO_STATE_LOG  WHERE `ENTRY_DATE` >= '2013-07-27 00:00:00' AND STATE_ID IN ('8','9') AND COMMENT IN ('ELIGIBLE_TIME_UP', 'ACTIVE_TIME_UP') ";
$res1 = mysql_query_decide($sql1) or die($sql1);
while($row1 = mysql_fetch_array($res1))
{
	$profile[] = $row1[PROFILEID];
}
print_r(count($profile));
$profileStr = implode(",",$profile);
$sql = "SELECT * FROM FTO.FTO_CURRENT_STATE WHERE FTO_EXPIRY_DATE <= now() AND PROFILEID IN (".$profileStr.")";
$res = mysql_query_decide($sql) or die($sql);
while($row = mysql_fetch_array($res))
{
        $profileNotExpire[] = $row[PROFILEID];
}

echo $sql = "SELECT PROFILEID FROM FTO.FTO_STATE_LOG WHERE PROFILEID IN (".$profileStr.") AND COMMENT='MARK_DUPLICATE'";
$res = mysql_query_decide($sql) or die($sql);
while($row = mysql_fetch_array($res))
{
        $profiledup[] = $row[PROFILEID];
}
echo "\n\n";
print_r(count($profiledup));
foreach($profile as $k1=>$v1)
{
if(!in_array($v1,$profiledup) && !in_array($v1,$profileNotExpire))
{
echo $sql = "UPDATE FTO.FTO_CURRENT_STATE SET STATE_ID=1 WHERE PROFILEID ='".$v1."' LIMIT 1";
$res = mysql_query_decide($sql) or die($sql);
        $fieldsArray="PROFILEID,USERNAME,PASSWORD,GENDER,RELIGION,CASTE,SECT,MANGLIK,MTONGUE,MSTATUS,DTOFBIRTH,OCCUPATION,COUNTRY_RES,CITY_RES,HEIGHT,EDU_LEVEL,EMAIL,IPADD,ENTRY_DT,MOD_DT,RELATION,COUNTRY_BIRTH,SOURCE,INCOMPLETE,PROMO,DRINK,SMOKE,HAVECHILD,RES_STATUS,BTYPE,COMPLEXION,DIET,HEARD,INCOME,CITY_BIRTH,BTIME,HANDICAPPED,NTIMES,SUBSCRIPTION,SUBSCRIPTION_EXPIRY_DT,ACTIVATED,ACTIVATE_ON,AGE,GOTHRA,GOTHRA_MATERNAL,NAKSHATRA,MESSENGER_ID,MESSENGER_CHANNEL,PHONE_RES,PHONE_MOB,FAMILY_BACK,SCREENING,CONTACT,SUBCASTE,YOURINFO,FAMILYINFO,SPOUSE,EDUCATION,LAST_LOGIN_DT,SHOWPHONE_RES,SHOWPHONE_MOB,HAVEPHOTO,PHOTO_DISPLAY,PHOTOSCREEN,PREACTIVATED,KEYWORDS,PHOTODATE,PHOTOGRADE,TIMESTAMP,PROMO_MAILS,SERVICE_MESSAGES,PERSONAL_MATCHES,SHOWADDRESS,UDATE,SHOWMESSENGER,PINCODE,PARENT_PINCODE,PRIVACY,EDU_LEVEL_NEW,FATHER_INFO,SIBLING_INFO,WIFE_WORKING,JOB_INFO,MARRIED_WORKING,PARENT_CITY_SAME,PARENTS_CONTACT,SHOW_PARENTS_CONTACT,FAMILY_VALUES,SORT_DT,VERIFY_EMAIL,SHOW_HOROSCOPE,GET_SMS,STD,ISD,MOTHER_OCC,T_BROTHER,T_SISTER,M_BROTHER,M_SISTER,FAMILY_TYPE,FAMILY_STATUS,FAMILY_INCOME,CITIZENSHIP,BLOOD_GROUP,HIV,THALASSEMIA,WEIGHT,NATURE_HANDICAP,ORKUT_USERNAME,WORK_STATUS,ANCESTRAL_ORIGIN,HOROSCOPE_MATCH,SPEAK_URDU,PHONE_NUMBER_OWNER,PHONE_OWNER_NAME,MOBILE_NUMBER_OWNER,MOBILE_OWNER_NAME,RASHI,TIME_TO_CALL_START,TIME_TO_CALL_END,PHONE_WITH_STD,MOB_STATUS,LANDL_STATUS,PHONE_FLAG,CRM_TEAM,activatedKey,PROFILE_HANDLER_NAME,GOING_ABROAD,OPEN_TO_PET,HAVE_CAR,OWN_HOUSE,COMPANY_NAME,HAVE_JCONTACT,HAVE_JEDUCATION,SUNSIGN";

        $loggedInProfile = new Profile('',$v1);
        $loggedInProfile->getDetail('', '', $fieldsArray);
	$loggedInProfile->getPROFILE_STATE()->updateFTOState($loggedInProfile,"PATCH");
echo "\n";
}
}
?>			
