indexSuccess:
  metas:
    title: Settings - Jeevansathi.com
    keywords: Jeevansathi
  http_metas:
    content-type: text/html
  javascripts:    []
  stylesheets:    []
  layout: jspcLayout

jspcSettingsSuccess:
  metas:
    title: Settings - Jeevansathi.com
    keywords: Jeevansathi
  http_metas:
    content-type: text/html
  javascripts:    [jspc/settings/settings@bottom,jspc/settings/jspc_visibility@bottom,jspc/settings/jspc_hideDelete@bottom,jspc/login/changePassword_js@bottom]
  stylesheets:    [jspc/settings/settings]
  layout: jspcLayout

alertManagerSuccess:
  metas:
    title: Alert Manager - Jeevansathi.com
    keywords: Jeevansathi
  http_metas:
    content-type: text/html
  javascripts:    [jspc/settings/settings@bottom,jspc/settings/jspc_visibility@bottom]
  stylesheets:    [jspc/settings/settings]
  layout: jspcLayout
