CREATE TABLE `AdGroup` (
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `id` bigint(11) NOT NULL,
 `belongsToCampaignId` bigint(11) NOT NULL,
 `name` char(40) NOT NULL,
 `status` char(10) NOT NULL,
 `maxCpc` float NOT NULL,
 `maxCpm` float NOT NULL,
 `maxContentCpc` float NOT NULL,
 `proxyMaxCpc` float NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `id` (`id`),
 KEY `customerId` (`customerId`),
 KEY `belongsToCampaignId` (`belongsToCampaignId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `AdGroup_Report` (
 `Date` date NOT NULL,
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `campaignid` bigint(11) NOT NULL,
 `campaign` char(40) NOT NULL,
 `adgroupid` bigint(11) NOT NULL,
 `adgroup` char(40) NOT NULL,
 `agStatus` char(10) NOT NULL,
 `imps` int(11) NOT NULL,
 `clicks` int(11) NOT NULL,
 `ctr` double NOT NULL,
 `cpc` double NOT NULL,
 `maxCpc` double NOT NULL,
 `cpm` double NOT NULL,
 `maxCpm` double NOT NULL,
 `cost` double NOT NULL,
 `pos` double NOT NULL,
 `conv` int(11) NOT NULL,
 `convRate` double NOT NULL,
 `costPerConv` double NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `customerId` (`customerId`),
 KEY `campaignid` (`campaignid`),
 KEY `adgroupid` (`adgroupid`),
 KEY `Date` (`Date`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


CREATE TABLE `Campaign` (
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `id` bigint(11) NOT NULL,
 `name` char(40) NOT NULL,
 `status` enum('Pending','Active','Paused','Deleted','Suspended','Ended') NOT NULL,
 `startDate` date NOT NULL,
 `endDate` date NOT NULL,
 `dailyBudget` float NOT NULL,
 `languages` varchar(255) NOT NULL,
 `networkTargeting` varchar(100) NOT NULL,
 `countries` varchar(255) NOT NULL,
 `regions` varchar(255) NOT NULL,
 `metros` varchar(255) NOT NULL,
 `cities` varchar(255) NOT NULL,
 `circles` varchar(255) NOT NULL,
 `targetAll` enum('false','true') NOT NULL,
 `adScheduling_status` enum('Enabled','Disabled') NOT NULL,
 `budgetOptimizerSettings_bidCeiling` int(11) NOT NULL,
 `budgetOptimizerSettings_enabled` enum('false','true') NOT NULL,
 `budgetOptimizerSettings_takeOnOptimizedBids` enum('false','true') NOT NULL,
 `campaignNegativeKeywordCriteria` text NOT NULL,
 `campaignNegativeWebsiteCriteria` text NOT NULL,
 `isEnabledSeparateContentBids` tinyint(1) NOT NULL,
 `isEnabledOptimizedAdServing` tinyint(1) NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `id` (`id`),
 KEY `customerId` (`customerId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


CREATE TABLE `Campaign_Report` (
 `Date` date NOT NULL,
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `campaignid` bigint(11) NOT NULL,
 `campaign` char(40) NOT NULL,
 `budget` double NOT NULL,
 `campStatus` enum('Pending','Active','Paused','Deleted','Suspended','Ended') NOT NULL,
 `imps` int(11) NOT NULL,
 `clicks` int(11) NOT NULL,
 `ctr` double NOT NULL,
 `cpc` double NOT NULL,
 `maxCpc` double NOT NULL,
 `cpm` double NOT NULL,
 `maxCpm` double NOT NULL,
 `cost` double NOT NULL,
 `pos` double NOT NULL,
 `conv` int(11) NOT NULL,
 `convRate` double NOT NULL,
 `costPerConv` double NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `customerId` (`customerId`),
 KEY `Date` (`Date`),
 KEY `campaignid` (`campaignid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


CREATE TABLE `Creative_Report` (
 `Date` date NOT NULL,
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `campaignid` bigint(11) NOT NULL,
 `campaign` char(40) NOT NULL,
 `adgroupid` bigint(11) NOT NULL,
 `adgroup` char(40) NOT NULL,
 `creativeid` bigint(11) NOT NULL,
 `creativeStatus` enum('Enabled','Disabled','Paused') NOT NULL,
 `creativeType` char(10) NOT NULL,
 `creativeDestUrl` text NOT NULL,
 `imps` int(11) NOT NULL,
 `clicks` int(11) NOT NULL,
 `ctr` double NOT NULL,
 `cpc` double NOT NULL,
 `maxCpc` double NOT NULL,
 `cpm` double NOT NULL,
 `maxCpm` double NOT NULL,
 `cost` double NOT NULL,
 `pos` double NOT NULL,
 `conv` int(11) NOT NULL,
 `convRate` double NOT NULL,
 `costPerConv` double NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `Date` (`Date`),
 KEY `customerId` (`customerId`),
 KEY `campaignid` (`campaignid`),
 KEY `adgroupid` (`adgroupid`),
 KEY `creativeid` (`creativeid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `ImageAd` (
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `id` bigint(11) NOT NULL,
 `belongsToAdGroupId` bigint(11) NOT NULL,
 `belongsToCampaignId` bigint(11) NOT NULL,
 `displayUrl` char(40) NOT NULL,
 `destinationUrl` text NOT NULL,
 `status` enum('Enabled','Disabled','Paused') NOT NULL,
 `isDisapproved` tinyint(1) NOT NULL,
 `name` char(30) NOT NULL,
 `width` smallint(6) NOT NULL,
 `height` smallint(6) NOT NULL,
 `imageUrl` text NOT NULL,
 `thumbnailUrl` text NOT NULL,
 `mimeType` char(15) NOT NULL,
 `type` enum('image','dynamicImage','flash') NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `id` (`id`),
 KEY `belongsToAdGroupId` (`belongsToAdGroupId`),
 KEY `customerId` (`customerId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `KeywordCriterion` (
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `id` bigint(11) NOT NULL,
 `belongsToAdGroupId` bigint(11) NOT NULL,
 `belongsToCampaignId` bigint(11) NOT NULL,
 `text` char(80) NOT NULL,
 `type` enum('Broad','Phrase','Exact') NOT NULL,
 `criterionType` enum('Keyword','Website') NOT NULL,
 `isNegative` tinyint(1) NOT NULL,
 `isPaused` tinyint(1) NOT NULL,
 `maxCpc` float NOT NULL,
 `minCpc` float NOT NULL,
 `proxyMaxCpc` float NOT NULL,
 `status` enum('Active','InActive','Disapproved','Deleted') NOT NULL,
 `language` text NOT NULL,
 `destinationUrl` text NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `id` (`id`),
 KEY `belongsToAdGroupId` (`belongsToAdGroupId`),
 KEY `customerId` (`customerId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `KeywordCriterion_Report` (
 `Date` date NOT NULL,
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `campaignid` bigint(11) NOT NULL,
 `campaign` char(40) NOT NULL,
 `adgroupid` bigint(11) NOT NULL,
 `adgroup` char(40) NOT NULL,
 `keywordid` bigint(11) NOT NULL,
 `siteKwStatus` enum('Active','InActive','Disapproved','Deleted') NOT NULL,
 `kwSite` text NOT NULL,
 `kwSiteType` enum('Broad','Phrase','Exact') NOT NULL,
 `kwDestUrl` text NOT NULL,
 `imps` int(11) NOT NULL,
 `clicks` int(11) NOT NULL,
 `ctr` double NOT NULL,
 `cpc` double NOT NULL,
 `maxCpc` double NOT NULL,
 `cpm` double NOT NULL,
 `maxCpm` double NOT NULL,
 `cost` double NOT NULL,
 `pos` double NOT NULL,
 `conv` int(11) NOT NULL,
 `convRate` double NOT NULL,
 `costPerConv` double NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `customerId` (`customerId`),
 KEY `campaignid` (`campaignid`),
 KEY `adgroupid` (`adgroupid`),
 KEY `keywordid` (`keywordid`),
 KEY `Date` (`Date`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


CREATE TABLE `TextAd` (
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `id` bigint(11) NOT NULL,
 `belongsToAdGroupId` bigint(11) NOT NULL,
 `belongsToCampaignId` bigint(11) NOT NULL,
 `displayUrl` char(40) NOT NULL,
 `destinationUrl` text NOT NULL,
 `status` enum('Enabled','Disabled','Paused') NOT NULL,
 `isDisapproved` tinyint(1) NOT NULL,
 `headline` char(30) NOT NULL,
 `description1` char(40) NOT NULL,
 `description2` char(40) NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `id` (`id`),
 KEY `belongsToAdGroupId` (`belongsToAdGroupId`),
 KEY `customerId` (`customerId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


CREATE TABLE `WebsiteCriterion` (
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `id` bigint(11) NOT NULL,
 `belongsToAdGroupId` bigint(11) NOT NULL,
 `belongsToCampaignId` bigint(11) NOT NULL,
 `url` text NOT NULL,
 `criterionType` enum('Keyword','Website') NOT NULL,
 `isNegative` tinyint(1) NOT NULL,
 `isPaused` tinyint(1) NOT NULL,
 `maxCpm` float NOT NULL,
 `status` enum('Active','InActive','Disapproved','Deleted') NOT NULL,
 `language` text NOT NULL,
 `destinationUrl` text NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `id` (`id`),
 KEY `belongsToAdGroupId` (`belongsToAdGroupId`),
 KEY `customerId` (`customerId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `WebsiteCriterion_Report` (
 `Date` date NOT NULL,
 `primary` bigint(11) NOT NULL auto_increment,
 `customerId` bigint(11) NOT NULL,
 `campaignid` bigint(11) NOT NULL,
 `campaign` char(40) NOT NULL,
 `adgroupid` bigint(11) NOT NULL,
 `adgroup` char(40) NOT NULL,
 `websiteid` bigint(11) NOT NULL,
 `site` text NOT NULL,
 `imps` int(11) NOT NULL,
 `clicks` int(11) NOT NULL,
 `ctr` double NOT NULL,
 `cpc` double NOT NULL,
 `maxCpc` double NOT NULL,
 `cpm` double NOT NULL,
 `maxCpm` double NOT NULL,
 `cost` double NOT NULL,
 `pos` double NOT NULL,
 `conv` int(11) NOT NULL,
 `convRate` double NOT NULL,
 `costPerConv` double NOT NULL,
 PRIMARY KEY  (`primary`),
 KEY `customerId` (`customerId`),
 KEY `campaignid` (`campaignid`),
 KEY `adgroupid` (`adgroupid`),
 KEY `websiteid` (`websiteid`),
 KEY `Date` (`Date`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


