use database Assisted_Product;

ALTER TABLE `AP_AUDIT_TRAIL` CHANGE `MATCH_ID` `MATCH_ID` CHAR( 36 ) NOT NULL ;

ALTER TABLE `AP_CALL_HISTORY` CHANGE `CALL_STATUS` `CALL_STATUS` ENUM( 'Y', 'N', 'C' );

ALTER TABLE `AP_TEMP_DPP` ADD `ACTED_ON_ID` INT NOT NULL ;
