# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
     class: sfAggregateLogger
     param:
       level: err
       loggers:
#         sf_web_debug:
#           class: sfWebDebugLogger
#           param:
#             level: debug
#             condition: %SF_WEB_DEBUG%
#             xdebug_logging: true
#             web_debug_class: sfWebDebug
         sf_file_debug:
            class: sfFileLogger
            param:
              level: debug
              file: %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log

test:
  storage:
    class: sfNoStorage

dev:
  mailer:
    class: sfMailer
    param:
      delivery_strategy: realtime 
      transport:
        class: Swift_SmtpTransport
        param: 
          host:       172.0.0.1
          port:       25
          encryption: ~
          username:   ~
          password:   ~

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true
  storage:
    class: sfNoStorage

