<?php
/*
This class handles the cases when search() function of legacy code is called.
*/
class SearchBasedOnParameters extends SearchParamters
{
	private $pid;

	public function __construct($loggedInProfileObj="")
	{
		if($loggedInProfileObj && $loggedInProfileObj->getPROFILEID())
			$this->pid = $loggedInProfileObj->getPROFILEID();
		parent::__construct();
	}

	/*
	This function sets the parameters passed into the search function of legacy code
	@params - An array where index is the variable and value has the corresponding value
	*/	
	public function getSearchCriteria($paramArr)
	{
		if($paramArr["STATE"])
		{
			if(is_array($paramArr["STATE"]))
				$this->setSTATE(implode(",",$paramArr["STATE"]));
			else
				$this->setSTATE($paramArr["STATE"]);
		}
		if($paramArr["NATURE_HANDICAP"])
		{
			if(is_array($paramArr["NATURE_HANDICAP"]))
				$this->setNATURE_HANDICAP(implode(",",$paramArr["NATURE_HANDICAP"]));
			else
				$this->setNATURE_HANDICAP($paramArr["NATURE_HANDICAP"]);
		}
		if($paramArr["HIV"])
		{
			if(is_array($paramArr["HIV"]))
				$this->setHIV(implode(",",$paramArr["HIV"]));
			else
				$this->setHIV($paramArr["HIV"]);
		}
		if($paramArr["CITY_RES"])
		{
			if(is_array($paramArr["CITY_RES"]))
				$this->setCITY_RES(implode(",",$paramArr["CITY_RES"]));
			else
				$this->setCITY_RES($paramArr["CITY_RES"]);
		}
		if($paramArr["OCCUPATION"])
		{
			if(is_array($paramArr["OCCUPATION"]))
				$this->setOCCUPATION(implode(",",$paramArr["OCCUPATION"]));
			else
				$this->setOCCUPATION($paramArr["OCCUPATION"]);
		}
		if($paramArr["COUNTRY_RES"])
		{
			if(is_array($paramArr["COUNTRY_RES"]))
				$this->setCOUNTRY_RES(implode(",",$paramArr["COUNTRY_RES"]));
			else
				$this->setCOUNTRY_RES($paramArr["COUNTRY_RES"]);
		}
		if($paramArr["GENDER"])
		{
			if(is_array($paramArr["GENDER"]))
				$this->setGENDER(implode(",",$paramArr["GENDER"]));
			else
				$this->setGENDER($paramArr["GENDER"]);
		}
		if($paramArr["RELIGION"])
		{
			if(is_array($paramArr["RELIGION"]))
				$this->setRELIGION(implode(",",$paramArr["RELIGION"]));
			else
				$this->setRELIGION($paramArr["RELIGION"]);
		}
		if($paramArr["CASTE"])
		{
			$this->setCASTE($paramArr["CASTE"]);
		}
		if($paramArr["MTONGUE"])
		{
			if(is_array($paramArr["MTONGUE"]))
				$this->setMTONGUE(implode(",",$paramArr["MTONGUE"]));
			else
				$this->setMTONGUE($paramArr["MTONGUE"]);
		}
		if($paramArr["LAGE"])
		{
			if(is_array($paramArr["LAGE"]))
                		$this->setLAGE(implode(",",$paramArr["LAGE"]));
			else
                		$this->setLAGE($paramArr["LAGE"]);
		}
		if($paramArr["HAGE"])
		{
			if(is_array($paramArr["HAGE"]))
                		$this->setHAGE(implode(",",$paramArr["HAGE"]));
			else
                		$this->setHAGE($paramArr["HAGE"]);
		}
		if($paramArr["HAVEPHOTO"])
		{
			if(is_array($paramArr["HAVEPHOTO"]))
				$this->setHAVEPHOTO(implode(",",$paramArr["HAVEPHOTO"]));
			else
				$this->setHAVEPHOTO($paramArr["HAVEPHOTO"]);
		}
		if($paramArr["MANGLIK"])
		{
			if(is_array($paramArr["MANGLIK"]))
				$this->setMANGLIK(implode(",",$paramArr["MANGLIK"]));
			else
				$this->setMANGLIK($paramArr["MANGLIK"]);
		}
		if($paramArr["MSTATUS"])
		{
			if(is_array($paramArr["MSTATUS"]))
				$this->setMSTATUS(implode(",",$paramArr["MSTATUS"]));
			else
				$this->setMSTATUS($paramArr["MSTATUS"]);
		}
		if($paramArr["INCOME"])
		{
			if(is_array($paramArr["INCOME"]))
				$this->setINCOME(implode(",",$paramArr["INCOME"]));
			else
				$this->setINCOME($paramArr["INCOME"]);
		}
		if($paramArr["EDU_LEVEL_NEW"])
		{
			if(is_array($paramArr["EDU_LEVEL_NEW"]))
				$this->setEDU_LEVEL_NEW(implode(",",$paramArr["EDU_LEVEL_NEW"]));
			else
				$this->setEDU_LEVEL_NEW($paramArr["EDU_LEVEL_NEW"]);
		}
		if($paramArr["PRIVACY"])
		{
			if(is_array($paramArr["PRIVACY"]))
				$this->setPRIVACY(implode(",",$paramArr["PRIVACY"]));
			else
				$this->setPRIVACY($paramArr["PRIVACY"]);
		}
		if($paramArr["PHOTO_DISPLAY"])
		{
			if(is_array($paramArr["PHOTO_DISPLAY"]))
				$this->setPHOTO_DISPLAY(implode(",",$paramArr["PHOTO_DISPLAY"]));
			else
				$this->setPHOTO_DISPLAY($paramArr["PHOTO_DISPLAY"]);
         	}
		if($paramArr["IGNORE_PROFILES"])
		{
			$ignoreProfiles = $paramArr["IGNORE_PROFILES"];
			$this->setIgnoreProfiles($ignoreProfiles);
		}
		if($paramArr["SHOW_PROFILES"])
		{
			$showProfiles = $paramArr["SHOW_PROFILES"];
			$this->setProfilesToSHow($showProfiles);
		}
		if($paramArr["KEYWORD"])
		{
			if(is_array($paramArr["KEYWORD"]))
				$this->setKEYWORD(implode(",",$paramArr["KEYWORD"]));
			else
				$this->setKEYWORD($paramArr["KEYWORD"]);
		}
		if($paramArr["KEYWORD_TYPE"])
		{
			if(is_array($paramArr["KEYWORD_TYPE"]))
				$this->setKEYWORD_TYPE(implode(",",$paramArr["KEYWORD_TYPE"]));
			else
				$this->setKEYWORD_TYPE($paramArr["KEYWORD_TYPE"]);
		}
		if($paramArr["LENTRY_DT"])
                {
                       	$this->setLENTRY_DT($paramArr["LENTRY_DT"]);
                }
		if($paramArr["HENTRY_DT"])
                {
                       	$this->setHENTRY_DT($paramArr["HENTRY_DT"]);
                }
		if($paramArr["IS_VSP"])
                {
                       	$this->setIS_VSP(1);
                }
	}
}
?>
