<?php
include("../jsadmin/connect.inc");
if(authenticated($cid))
{
	$smarty->assign("cid",$cid);
	$smarty->display("billing.htm");
}
else
{
	$smarty->assign("CID",$cid);
        $smarty->display("jsconnectError.tpl");
}
?>
