use incentive;

ALTER TABLE `CAMPAIGN` CHANGE `ACTIVE` `ACTIVE` ENUM( 'Y', 'N', 'F' ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL 

CREATE TABLE `FTA_CSV_DATA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(10) NOT NULL,
  `USERNAME` varchar(25) NOT NULL,
  `ENTRY_DATE` date NOT NULL,
  `GENDER` char(1) NOT NULL,
  `RELATION` varchar(10) NOT NULL,
  `HAVEPHOTO` varchar(5) NOT NULL,
  `PHONE_VERIFIED` varchar(5) NOT NULL,
  `LOGIN_FREQ_PERC` int(3) NOT NULL,
  `EOI_WAITING` int(5) NOT NULL,
  `EOI_DECLINED` int(5) NOT NULL,
  `EOI_RCVD_VS_VIEWED` int(10) NOT NULL,
  `PHOTO_REQUEST_RECIEVED` int(5) NOT NULL,
  `RESPONSE_BOOSTER_ELIGIBLE` varchar(5) NOT NULL,
  `MOBILE1` varchar(11) NOT NULL,
  `MOBILE2` varchar(11) NOT NULL,
  `LANDLINE` varchar(11) NOT NULL,
  `MOBILE1_COPY` varchar(11) NOT NULL,
  `MOBILE2_COPY` varchar(11) NOT NULL,
  `LANDLINE_COPY` varchar(11) NOT NULL,
  `PRIORITY` int(1) NOT NULL,
  `CSV_ENTRY_DATE` date NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 ;

CREATE TABLE `FTA_IN_DIALER` (
  `PROFILEID` int(11) NOT NULL,
  `PRIORITY` int(2) NOT NULL,
  `ELIGIBLE` char(1) NOT NULL,
  `ENTRY_DATE` date NOT NULL,
  PRIMARY KEY (`PROFILEID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
        
