<div class="fontlig f15 color2">
<p class="fontreg">PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY .</p>
<p class="pt30">Jeevansathi.com is an intermediary as defined under sub-clause (w) of Section 2 of the Information Technology Act, 2000. Visitors to Jeevansathi.com are granted a nonexclusive, limited license to use and access the content and services offered in accordance with these Terms and Conditions (the "License").</p>
<p class="pt30">BY YOUR POSITIVE ACTS OF ACCESSING JEEVANSATHI.COM, YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS SET FORTH BELOW. IF YOU DO NOT AGREE WITH ANY OF THESE TERMS AND CONDITIONS, YOU SHOULD NOT ACCESS OR USE JEEVANSATHI.COM.</p>


<p class="pt20"> 1. This website - JeevanSathi.Com - found at the uniform resource locator (URL) id - www.jeevansathi.com - has been set up and promoted, and is maintained, by Jeevansathi Internet Services, a Division of Info Edge (India) Ltd. (hereinafter referred to as IEIL), which term shall, for the purposes hereof, be deemed to include its subsidiaries, affiliates, partners, shareholders, directors, executives, officers, employees, agents, attorneys, accountants and any person vested with any responsibility for any task relating to the affairs of the company), with its registered office currently located at Ground Floor, GF-12A, 94, Meghdoot, Nehru Place, New Delhi - 110 020.</p>
<p class="pt20"> 2. The website - JeevanSathi.Com - is intended only to serve as a preliminary medium of contact and information for its users / members / visitors who have a bona fide intention to enter into a matrimonial alliance. Jeevansathi.com does not purport to be a marriage or business bureau or a dating /contact website.</p>
<p class="pt20"> 3. IEIL presumes that each and every single member / user / visitor, who logs on to the website has an intention to get married / enter into a matrimonial alliance and not otherwise. IEIL under no circumstances shall be responsible for any loss or damage resulting from anyone's use of the Site or the Service and / or any Content posted on the web Site or transmitted to users / Members. The exchange of matrimonial profile(s) through or by IEIL should not in any way be construed as a matrimonial offer and/or recommendation from or by IEIL. IEIL shall not be responsible for any loss or damage to any individual arising in/out of, or subsequent to, matrimonial relations established pursuant to use of the service provided by IEIL.</p>
<p class="pt20"> 4. IEIL collects information / data including e-mail id, mail address, first name, last name, telephone number, date of birth, age, gender, ethnic background, appearance, religion, occupation, preferences, life style information, general geographical location from its visitors / users in order to create their unique profiles. Apart from this, certain other information including physical and mental disabilities are also collected. The said information / data collected is entered in the programme especially devised for matching profiles and which programme enable to provide matches for the visitors / users based on their pre-selected criteria. Certain private information is only displayed after taking prior consent of the visitors / users.  IEIL does not collect financial information such as credit card/debit card numbers/bank accounts numbers etc.
</p>
<p class="pt20">4a. All information uploaded by the user themselves or through any of the Jeevansathi offline centres meant to be displayed on the open website located on www.Jeevansathi.com becomes public knowledge and IEIL may at its sole discretion include all or any portion of the listing intimated by a client for display on jeevansathi.com in any other media including the matrimonial sections of other platforms including but not limited to print media, community associations, websites, television shows, DTH/IPTV Services, mobile wap sites etc. at no extra costs to the users of Jeevansathi.com and IEIL shall not be held liable for usage/publicity of such information / data.</p>
<p class="pt20"> 5. The user undertakes not to duplicate, download publish, modify and distribute material on jeevansathi.com unless specifically authorized by IEIL in this regard. The user undertakes not to establish any deep link or other connection to any specific page of jeevansathi.com other than the Home Page without obtaining prior consent of IEIL.</p>
<p class="pt20"> 6. The user undertakes to use jeevansathi.com for his/her personal purposes. Using content from jeevansathi.com for creating derivative works with a commercial motive without prior written consent from IEIL is strictly prohibited.</p>
<p class="pt20"> 7. Jeevansathi.com uses technological means to exclude Robots etc from crawling the website and scraping content. The user undertakes not to circumvent these methods.</p>
<p class="pt20"> 8. Any advice, counseling, recommendations or information provided at JeevanSathi.Com including information of Jeevansathi.com members may not be necessarily correct, true or reliable, and that any reliance placed thereon and any action taken on the basis thereof shall be entirely / solely at the risk of the person or persons placing such reliance or taking such action. Visitors wishing to use the information so provided are advised to conduct their own due diligence, in respect of the site content sought to be taken advantage of, at their own initiative, cost and effort. IEIL does not advise / recommend its users / visitors to establish any contact / interaction with any other user / member / visitor or any such Profile(s) as displayed in the website based on the data / information as furnished in such users profile / photograph etc. and the user / visitor opting to build contact or interact shall do it solely at his / her own risk. IEIL cannot be held responsible or liable, in any manner whatsoever, in respect of any reliance placed on any information displayed / placed on the website, since the same purports merely to act as indicators of the general scenario in the related behalf.</p>
<p class="pt20"> 9. IEIL does not authenticate, vet, screen, endorse or investigate any information or assertion comprised in the matrimonial listings, or any other content on the website, nor does it in any manner whatsoever certify or attest the same to be correct or true. It does not endorse matches and profiles in any manner, but an implied presumption is cast on the users / members that the information(s) furnished are exclusively / solely to curve out / frame a suitable profile for the purpose of matrimonial alliance and they are true and correct. All due diligence, effort and initiatives must be exercised by those wishing to use any information found on the website, and should take adequate precautions with the full and complete knowledge that all information contained in the matrimonial listings have been placed there directly by visitors to the website without any prior intimation, consent or verification of or by IEIL.
</p>
<p class="pt20">
The User / subscriber / visitor to Jeevansathi.com is prohibited from uploading, posting, transmitting, updating or sharing any information that:</p>
<p class="pt20">a) belongs to another person and to which the user does not have any right to;</p>
<p class="pt20">b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; harm minors in any way;</p>
<p class="pt20">c) infringes any patent, trademark, copyright or other proprietary rights;</p>
<p class="pt20">d) violates any law for the time being in force;</p>
<p class="pt20">e) deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature; impersonate another person;</p>
<p class="pt20">f) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.</p>
<p class="pt20">IEIL may, without notice in its sole discretion, and at any time, terminate or restrict your use or access to Jeevansathi.com (or any part thereof) and/or take down any content uploaded by you for any reason, including, without limitation, that IEIL based on its judgement and perception believes you have violated or acted inconsistently with the letter or spirit of these Terms and Conditions.</p>
<p class="pt20"> 10. IEIL is an on-line service provider for its members/visitors to create their own/unique profiles envisaging certain personal (optional) information(s) are to be displayed on the net/web-site, which information is used by visitors for searching and matching purposes. IEIL does not sell, rent, share, trade or give away any of your personal information except which is displayed and intended to be shared by its users / members / visitors including photographs displayed on site. Although IEIL shall take all reasonable precautions, IEIL shall not be responsible in case such public information / photograph of the member/user so displayed in the site is being unauthorisedly copied / printed / published / forged / superimposed / manipulated etc. or misused by any user / member / visitor. The user / member shall indemnify IEIL from all kind of loss / damages which IEIL may suffer from any activities carried out by any visitor/user/member through improper use of the service provided by IEIL.</p>
<p class="pt20"> 11. By listing a matrimonial profile, or a business or personal listing or a link, or any content or listing, on JeevanSathi.Com, the person or persons making or posting such listing, and the person or persons responsible for such posting or listing, shall be deemed to have agreed to hold IEIL harmless and protected against any suit or complaint, civil, pecuniary or criminal, and against any claims or damages (including, without limitation, interests, fines and penalties) which may be brought against or levied on IEIL on account of any matter arising out of, or relating to, such posting / listing or response received from such posting/listing.</p>
<p class="pt20"> 12. IEIL does not represent or endorse the accuracy or reliability of any member / visitor profile, advice, opinion, statement or other information displayed / uploaded through the service by IEIL. IEIL or any of its owners, staff or agents are not responsible under any circumstances for any action/display whether direct or indirect, which occurs as a result of online display of information in the nature of illicit material / material that may be offensive to visitors / members or is patently offensive to the on-line community or any material which may promote racism, bigotry, hatred or physical/mental harm of any kind to any group or individual or transmit any chain letters or junk mail or unsolicited mass mailing or spamming or obscene material to other users / members. IEIL does not monitor the conduct of its users/members or visitors and therefore IEIL does not take the responsibility of any conduct by its users / members or visitors who may avail / obtain / use / exploit the on-line service provided by IEIL in order to harass, abuse or harm another user/member or visitor or use the said on-line service to promote / advertise / solicit anything without their prior consent or an act in any manner which may threaten the safety of users / members.</p>
<p class="pt20"> 13. IEIL reserves the right to remove / delete any content / message / photo (s) / profile or cancel the registration / membership of such individual / user either upon a complaint received from another member / user / visitor / individual / group of individuals or upon discovery of the same on its own or based on its sole judgment and perception and it shall without notice stop providing the service entitled to a user / member and forfeit all other incidental service(s) with immediate effect along with the fee/tenure of registration as well as take appropriate legal action against such visitor / user / member. By listing a profile on the website, it is deemed that the said member/user has an intention to get married and in case it appears to IEIL that at the time of listing the profile or subsequently such user / visitor had no intention to enter into a matrimonial alliance or has changed his/her intention, then IEIL shall reserve the right to remove / delete such profile from the website and initiate prosecution under the law or take such steps as may be advised from time to time. In using the website, it is deemed that the user/member agree not to post any content or views that may be considered threatening, abusive, vulgar, obscene or otherwise objectionable or act illegally or otherwise harass another user; put wrong or misleading information in any of the details of his/her own profile; impersonate another or use the site for any commercial purposes; or interfere with or disrupt the operation of this site, or disobey any reasonable requirements, procedures or policies imposed by IEIL from time to time.</p>
<p class="pt20"> 14. Nothing comprised in the contents at JeevanSathi.Com is intended or meant to induce or persuade or convince or invite any person whatsoever to perform any action or do any such thing, or not to perform or do, where such performance or doing, or non-performance or not doing, constitute any contravention of any law or regulation in force for the time being to which such person or action may be governed.</p>
<p class="pt20"> 15. IEIL shall not be held responsible for any interactions/ passing of information(s) etc. between any user / member / visitor via e-mail, chat or any other medium with another member / user / visitor and IEIL has no obligation, to monitor any such disputes between arising between the users/members and IEIL shall not be party to such dispute/litigation etc.</p>
<p class="pt20"> 16. IEIL reserves the absolute right to modify or amend or delete, in any manner as it deems fit, any content of any matrimonial listing placed on JeevanSathi.Com in order to ensure compliance with the rules of such placement (which may include, without limitation, the efforts and initiatives by IEIL to maximize response to matrimonial listings), prima facie accuracy and the prevailing laws in force for the time being, especially those relating to prohibition of any indecent, unlawful or obscene content. IEIL reserves the absolute right to delete any profile if it finds that the same person has created multiple profiles on the Jeevansathi.com website. Even if different profiles have been created with the same contact details, IEIL will reserve the absolute right to delete all such profiles. If any member refuses to give consent to a physical address verification that IEIL has requested then IEIL will have the absolute right to either put a "Not Verified" stamp on the profile or to delete the profile.</p>
<p class="pt20"> 17. Websites to which links are given on JeevanSathi.Com and the contents thereof are the sole responsibility of the promoters of such websites and IEIL does not, in any manner whatsoever, recommend, authenticate, endorse, verify or certify these websites or any contents or links there. IEIL does not take any responsibility for the privacy practice adopted by such other websites and therefore IEIL recommends its visitors / users to read the privacy statement of each and every website that the user visits. IEIL also does not take any responsibility or endorse the authenticity of the other online services linked with IEIL which may offer various services like a lucky draw, win a free trip, win free tickets, astrology, palmistry, numerology etc. The user / member / visitor of JeevanSathi shall at its sole risk and responsibility click and surf on to such other website(s) / links which is/are being displayed in the website of JeevanSathi.com. The user shall always bear in mind that at a single stroke/click of the mouse on such links/website, it gets connected through the Transmission Control Protocol (TCP) / Internet Protocol (IP) network of the said users and not through the IP of JeevanSathi.com. IEIL also does not suggest/encourage any of its users/members to furnish personal information and specially the Profile ID / User Name of Jeevansathi to such or any other website(s).</p>
<p class="pt20"> 18. IEIL reserves the right to tie up with partners in future to come up with various other online services. However, IEIL shall never share the information / data collected from its visitors / users with such other partners without taking prior consent / permission from such visitors / users. IEIL in such circumstances suggests that its visitors / users peruse the privacy policy of such partners before giving their consent or before furnishing personal identifiable information with such other website(s). IEIL is not privy to the privacy practice adopted by its partners and does not take the responsibility in respect of the privacy policy adopted / to be adopted by such partners. IEIL also reserves the right to use / share the information / data collected from its users with its partners if a user / visitor has already made public the information / data to jeevansathi.com visitors.</p>
<p class="pt20"> 19. IEIL hereby specifically disclaims any liabilities or warranties or guarantees, express, specific or implied, which may be attributable, in any manner whatsoever, to the existence, promotion, canvassing, contents, links, information or discontinuance of JeevanSathi.Com. No claims for damages, restitution, loss-of-profits, or any other pecuniary, civil or criminal plaints, which may be said to arise out, or on account, of any matter contained or related to JeevanSathi.Com, shall lie or be deemed to be sustainable against IEIL.</p>
<p class="pt20"> 20. IEIL assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of User and/or Member communications. IEIL is not responsible for any problems or technical malfunction of any telephone network or lines, computer on-line-systems, servers or providers, computer equipment, software, failure of e-mail or players on account of technical problems or traffic congestion on the Internet or at any website or combination thereof, including injury or damage to Users and/or Members or to any other person's computer related to or resulting from participating or downloading materials /information from the web-site.</p>
<p class="pt20"> 21. Members who come to the website are classified by IEIL as Incomplete or complete profiles. Both these types could further be Free members or Paid members. IEIL reserves the absolute right to modify, amend, change, curtail or expand any privileges, rights, benefits, liabilities or responsibilities of all types of Paid Members or Free Members as it deems fit and these will be instantly applicable to all past, present and future Members. IEIL allows Free members certain benefits /privileges like initiating free contact via "Express Interest" functionality, like viewing contact details of Paid members under certain conditions etc. The quantum of these benefits and even the benefits in totality will be at the sole discretion of IEIL. IEIL will determine at its own discretion how many benefits it offers to every individual Free member. IEIL will simultaneously offer different levels of benefits to different Free members. Benefit restriction to Free members will be done via multiple means including restricting access, spam filters, quotas etc.</p>
<p class="pt20"> 22. Payments for the services offered by Jeevansathi.com shall be on a 100% advance basis. The payment for service once subscribed to by the subscriber is not refundable and any amount paid shall stand appropriated. Refund if any will be at the sole discretion of Info Edge (India) Limited and it  offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the Customers card/bank accounts.  Info Edge (India) Ltd gives no guarantees of server uptime or applications working properly. All is on a best effort basis and liability is limited to refund of amount only. Info Edge (India) Ltd. undertakes no liability for free services. Info Edge (India) Ltd. reserves its right to amend / alter or change all or any disclaimers or terms of agreements at any time without any prior notice.  All terms / disclaimers whether specifically mentioned or not shall be deemed to be included if any reference is made to them.  </p>
<p class="pt20"> 23. The User is solely and exclusively responsible for maintaining confidentiality of the User password and User identification and all activities and transmission performed by the User through his/her user identification and shall be solely responsible for carrying out any online or off-line transaction involving credit cards / debit cards or such other forms of instruments or documents for making such transactions and IEIL assumes no responsibility or liability for their improper use of information relating to such usage of credit cards / debit cards used by the subscriber online / off-line. IEIL uses the maximum care as is possible to ensure that all or any data / information does not fall in the wrong hands. (The weak link in credit card transaction is securely storing the data once received; therefore IEIL does not store or keep credit card/debit card/bank account.  For the purposes of ensuring the maximum security for the financial information of a user (such as credit card/debit card/internet banking data) all such online payment transactions are carried out directly on the secured platforms of  payment gateways and not on JeevanSathi.com.</p>
<p class="pt20"> 24. IEIL does not warrant that the Service will be uninterrupted or error-free. IEIL provides the service on an "as is" basis. However, IEIL will take all reasonable steps to provide its users with error free, uninterrupted user experience. There may be delays, omissions, and interruptions in the availability of the Service. The user/member acknowledges that use of the Service is solely at their cost and risk. IEIL is not responsible for suspension of the Service, irrespective of the reason for such interruption / suspension. Any claim shall be limited to the amount paid, if any, for use of the Service during the previous 12 months. IEIL may discontinue or change the Service or its availability at any time, and the user/member is also free to stop availing the Service at any time.</p>
<p class="pt20"> 25. Jeevansathi.com uses third party payment gateways and failures in these gateways would be communicated to the users as it is. Extra currency/conversion charges/deductions/error issues from payment gateway shall not be the responsibility of Jeevansathi.com</p>
<p class="pt20"> 26. IEIL has complete rights in the JeevanSathi.com Site and the JeevanSathi.com Service. The Site contains copyrighted material, trademarks, and other proprietary information of its owners and its licensors. Except for that information which is in the public domain or for any other information/display for which permission have not been obtained from IEIL, IEIL reserves the right to proceed/initiate appropriate steps under the prevailing law against infringement of the said proprietary rights for illegal copying, modifying, publishing, transmitting, distributing, performing, displaying, or selling of any such proprietary information.</p>
<p class="pt20"> 27. IEIL reserves the right to verify the authenticity of Content posted on the site. IEIL if circumstances warrant may call for / ask any of its members / users to provide documentary or other form of evidence supporting the information / Content posted on the site and the user / member, without any protest shall produce such documentary / other evidence in support of such information and if the member / user fails to produce such information within a reasonable or stipulated time frame, IEIL may, in its sole discretion, terminate such Membership and forfeit the advance without a refund and take appropriate steps under the provisions of law.</p>
<p class="pt20"> 28. IEIL also reserves the right to investigate and take appropriate legal action without limitation at its sole discretion against any user / member / who violates / misuses the on-line services and terminating the Membership of such violators without prior intimation who utilise thus website in any manner which brings into disrepute or impairs the interests and functioning of JeevanSathi.com or Info Edge (India) Limited. </p>
<p class="pt20"> 29. IEIL does not take the responsibility of any information posted by its users/members in the web site, any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights and in case IEIL receives/discovers any such infringement, the said member / user may be called for / asked to furnish / provide evidence / relevant information in support of such display like an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest or a description of the copyrighted work that may have been infringed or information or a written statement that the member/user under bona-fide faith belief that the disputed information does not lead to any authorized use or infringement of copyright etc, under the law or a statement that the user/member is liable to penalty of perjury in case any of the information/statement furnished is proved otherwise or a declaration that the information displayed/posted is accurate and the member /user is itself the copyright owner or authorized to act on the copyright owner's behalf.</p>
<p class="pt20"> 30. IEIL has no obligation to monitor the activities of its users/visitors. However, IEIL has the right to monitor the Site electronically from time to time and to disclose any information as necessary to satisfy any law, regulation or other governmental request, to operate the Site properly, or to protect itself or its subscribers. IEIL also reserves the right to refuse to post or to remove any information or materials, in whole or in part, that, in its sole discretion, are unacceptable, undesirable, or violative of provision of law.</p>
<p class="pt20"> 31. The usage of this website and any disputes/issues arising out of it shall be subject to the applicable laws in force for the time being in the NCT of Delhi irrespective of conflicting provisions of law and to the exclusive jurisdiction of courts located in New Delhi.</p>
<p class="pt20"> 32. All members of jeevansathi.com are restricted to the following number of contacts they can make via the "Express Interest" option on the Jeevansathi.com site.</p>

<p class="pt20"><table border="1">
<tbody><tr>
<td></td> <td>Free Member</td> <td>Paid Member</td> <td>Paid Member with Response Booster</td>
</tr>
<tr>
<td>Daily Limit</td> <td>100</td><td>200</td> <td>225</td>
</tr>
<tr>
<td>Weekly Limit</td> <td>100</td><td>400</td> <td>575</td>
</tr>
<tr>
<td>Monthly Limit</td> <td>400</td><td>800</td> <td>1400</td>
</tr>
<tr>
<td>Overall Limit</td> <td>400</td><td>Unlimited*</td> <td>Unlimited*</td>
</tr>
</tbody></table></p>
<p class="pt20">* Subject to monthly limits at the discretion of Jeevansathi.com</p>

<p class="pt20"> 33. In case IEIL receives any incriminating evidence/complaint against any of its users from other members/users/visitors of the site or if IEIL, through data available to it from its servers, suspects misbehavior on any user's part, it reserves the right to impose restrictions on the user account which include but may not be confined to preventing the user under question from making multiple contacts and restricting the user to only contact members whose desired partner profile the user satisfies.</p>
<p class="pt20"> 34. All services which are defined by Time Period indicted in months shall imply 1 month to be equal to 30 days and for any longer durations service the total duration in days will be the Number of months multiplied by 30.</p>
<p class="pt20"> 35. IEIL guidelines prohibit members to give their name and/or contact details in any form - Email, Phone nos, Messenger Ids, Postal address etc in any fields other than the specific ones where the same information is asked. If any member who puts the above information in any field other than the one meant for that purpose then the IEIL screening team will remove the same.</p>
<p class="pt20"> 36. All people who become members of Jeevansathi.com are consenting for receiving</p>
<p class="pt20">a) Membership Emails: Emails conveying the benefits of paid membership to you. These are sent to the Email address you have mentioned in your profile.</p>
<p class="pt20">b) Important Notifications from Jeevansathi - Messages which inform you on various alerts related to usage of the site by you or other members who have viewed your profile or which are initiated by the IEIL team to introduce new features, educate on existing functionality etc These will be sent to your Postal Address/Email/Messenger Ids or on your Landline/Mobile from a non-140 number via SMS/MMS/VMS/USSD/IVR/Calls etc.</p>
<p class="pt20">c) Membership SMSes/Calls: SMSes or phone calls conveying the benefits of paid membership to you. You will receive these calls or SMSes on any of the phone numbers you have mentioned in your profile, if you have subscribed to them in your alert manager settings.</p>
<p class="pt20"> 37. Promotional Mails - Messages from people who pay IEIL to access its database. These are sent to members Postal Address/Email/Messenger Ids. People who consent for promotional mails can get these mails.</p>
<p class="pt20"> 38. If a member does not wish to receive communication from Jeevansathi then he needs to go to the "Settings" section in his profile and choose/dis-able for the modes(Emails / SMS / Calls / USSD / Messenger messages / IVR) and types of communication which he either wants to or does not want to receive. Types of communication are the specific messages based on profile attribute or website interactions between members. Jeevansathi may also provide for different message types and modes, other alternative ways to unsubscribe".</p>
<p class="pt20"> 39. Users who sign up to Jeevansathi Exclusive or eSathi services allow Jeevansathi to contact people on their behalf via Telephone, SMS, profile action on Jeevansathi website, Face to face interaction or any other means/modes of communication.</p>
<p class="pt20"> 40. Creation of duplicate profile on Jeevansathi is prohibited. In case the user has forgotten his password he can use the password retrieval option. Forgetting password, User ID, reaching contact limits or any other reason for creating a 2nd profile on Jeevansathi is not allowed. Info Edge reserves the right to delete/block this profile or restrict access of this profile to use the website. Info edge at its own discretion can decide to delete/block/restrict access of 2nd profile or the original profile or both profiles in all cases where duplicate profiles have been found.</p>
<p class="pt20"> 41. Membership Renewal: People who have subscribed to eRisha, eValue, eSathi or Jeevansathi Exclusive have an option to renew their services. If the renewal happens before the expiry date, then any unused "Contact Views" available with the original pack are carried forward. Contact Views are the facility wherein members can see contact details of other members who have not filtered/rejected/ignored them. If a member renews his membership after the expiry of current membership, then its treated as a fresh membership and and unused "Contact Views" of the previous membership are not carried forward. These conditions hold even if the renewal of the subscription is bundled with a special "Renewal/Repurchase/Loyalty" offer. Purchase before or after renewal date is the only criteria which determines if unused "Contact Views" are carried forward or not.</p>
<p class="pt20"> 42. Your "Name" will be visible to other members who are Jeevansathi Paid subscribers either if they "View Your Contact Details" or if you have sent them an Acceptance. Information filled by a member is visible on the profile page. This page is indexed by Google/Ask/Bing/Yahoo and other search engines. If a search engine user types a query then your profile page may be visible in Google/Bing/Yahoo etc. search results. All details which you have put will be visible unless the same has been explicitly hidden by you using appropriate Jeevansathi.com profile privacy settings.</p>
<p class="pt20"> 43. Use of certain features on the website is governed by rules. For example if your phone number is not verified then you cannot contact other members via "Express Interest" or even if the same is happening then that privilege can be blocked by IEIL at any time without giving any notice. Similarly If your phone number is not verified then even as a person who has availed a "Paid Service" you will still not be able to view phone/email/contact details of other members via any option on the website. For verifying your phone number, there are verification prompts across the website which guide you on how to Verify your phone. If the same is not clear then it is the member's responsibility to call customer care of Jeevansathi.com from the number which he/she wishes to verify.</p>
<p class="pt20"> 44. Any paid membership like eRishta, eSathi, eClassified, eValue, JS exclusive, Trial Pack, etc. are non-transferable. Any membership which is purchased is being purchased for that individual and cannot be used for any other profile in his/her family/friends/acquaintances etc. If a profile is deleted for whatsoever reason then that persons membership lapses. Even if the person retrieves his/her profile the same will be retrieved as a free profile. Neither will paid membership be retrieved nor will any refund be made.</p>
<p class="pt20"> 45. At times when a member tries to access the phone/email of another member, he can get a message which asks him to "View Phone/Email tomorrow - Contact limits reached of recipient" or any message which means the same. In these cases the member just needs to visit the same profile again the next days and use his quota of "View Contacts"</p>
<p class="pt20"> 46. Paid members can see Phone/Email of other members subject to the total limits on "Direct Contacts" as specified on the membership page for the pack they have purchased. When you view contact details of any other member you would be able to see one or more of the following details: Email, Mobile Number and Landline number. This is deemed as a Contact View and a count is deducted from your "Direct Contacts" quota. However, there is no such limit on the views of contact details of accepted members. You will also be restricted from viewing a person’s contact details on a specific day if it has been already viewed 10 times in a day by other members. Ability to see contact details of another member is subject to the condition that you pass the filter criteria of the other members and that they have not declined your profile or deleted/hidden their own profile. The website does not guarantee that you will be able to speak/correspond with the profile on the provided Mobile, Landline or Email ID.</p>
<p class="pt20"> 47. Paid Membership is co-extensive with the profile, membership expires as soon as the profile is deleted and cannot be reactivated.</p>
<p class="pt20"> 48. In the eAdvantage/eSathi unlimited plan, Response Booster and Featured Profile services will have a validity of 1 year, and will be stopped 1 year after the purchase of eAdvantage Unlimited plan. Rest of the services available under this plan will have unlimited duration.</p>
<p class="pt20"> 49. 'Featured Profile' subscribers will be considered to be shown at the top of search results only if they regularly login to their account. If 'Featured Profile' subscribers don't access the website for more than 15 days, they will be removed from the pool of users considered for being shown at the top of Search Page.</p>
<p class="pt20"> 50. Sending of Response Booster interests on behalf of Response Booster subscribers is subject to them regularly accessing their accounts. If an account is not accessed for more than 15 days, Response Booster interests will be stopped until the subscriber accesses his/her account.</p>
<p class="fontreg pt20">Restriction / Prohibitions</p>

 

<p class="pt20">You hereby expressly agree not to :</p>

<p class="pt20">1. Use of the services of this website in a manner contrary to any law which might be applicable at the relevant time</p>

<p class="pt20">2. Access data not intended for you or log into server or account that you are not authorized to access;</p>

<p class="pt20">3. Attempt to probe, scan or test the vulnerability of a system or network;</p>

<p class="pt20">4. Attempt or breach security or authentication measures without proper authorization;</p>

<p class="pt20">5. Attempt to interfere with, access by any other user including but not limited to by submitting a virus of any kind or Trojan horse to this website, overloading, Flooding, mail bombing or crashing;</p>

<p class="pt20">6. Copy, distribute, download, display, perform, reproduce, modify, edit, alter, enhance, broadcast or tamper with in any way or otherwise use any material contained in this website except as permitted;</p>

<p class="pt20">7. Copy and distribute this information on any other server, or modify or re-use information, text, graphics, sound, etc. on this Website to any other system. No reproduction of any part of the Website may be sold or distributed for commercial gain nor shall it be modified or incorporated in any other work, publication or Website, whether in hard copy or electronic format, including postings to any other Website;</p>

<p class="pt20">8. Remove any copyright, trade mark or other intellectual property notices contained in the original material from any material copied or printed off from this website or link to this website, without our express written consent;</p>

<p class="pt20">9. Providing deeplinks into this website without prior permission of IEIL is prohibited. Extracting data from this website using any automated process such as spiders, crawlers etc. or through any manual process for a purpose which has not been authorised in writing.</p>

<p class="pt20">10. Upload, post, email, transmit or otherwise make available either directly or indirectly, any unsolicited bulk e-mail or unsolicited commercial e-mail .</p>

<p class="pt20">11. Subscribers shall under no circumstance sublicense, assign, or transfer the License, and any attempt at such sublicense, assignment or transfer is void.</p>
</div>

