-- phpMyAdmin SQL Dump
-- version 2.6.0-pl2
-- http://www.phpmyadmin.net
-- 
-- Host: localhost:3306
-- Generation Time: Sep 17, 2012 at 05:16 PM
-- Server version: 5.5.17
-- PHP Version: 5.3.8
-- 
-- Database: `newjs`
-- 

-- --------------------------------------------------------

-- 
-- Table structure for table `SMS_CONTACTS`
-- 
use newjs;

DROP TABLE IF EXISTS `SMS_CONTACTS`;
CREATE TABLE IF NOT EXISTS `SMS_CONTACTS` (
  `ID` tinyint(4) NOT NULL AUTO_INCREMENT,
  `STATE` varchar(20) NOT NULL,
  `BRANCH` varchar(20) NOT NULL,
  `LOCALITY` varchar(20) NOT NULL,
  `ADDRESS` varchar(100) DEFAULT NULL,
  `PINCODE` varchar(6) DEFAULT NULL,
  `USERNAME` varchar(20) DEFAULT NULL,
  `AGENT_NAME` varchar(10) NOT NULL,
  `SMS_NAME` varchar(10) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `SMS_MOBILE` varchar(10) NOT NULL,
  `OUTBOUND_MOBILE` varchar(10) NOT NULL,
  `LANDLINE_1` varchar(15) NOT NULL,
  `LANDLINE_2` varchar(15) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=latin1 AUTO_INCREMENT=82 ;

-- 
-- Dumping data for table `SMS_CONTACTS`
-- 

INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (1, 'Bihar', 'Patna', 'Krishna Puri', 'House no.55C ,Rajesh kumar path, near Mourya TV office, Sri Krishna puri, Patna', '800001', 'patna_1', 'Kishor', 'Kishor', 'patna@jeevansathi.com', '9771490294', '9835628966', '0612-2540253', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (2, 'Chattisgarh', 'Raipur', 'Raipur', 'F-Q,DM Plaza,Opp-Surana Bhawan,Rajiv Chowk,Chota Para (Nr Fire Station)', '492001', 'chetan.kumar', 'Chetan', 'Chetan', 'chetan.kumar@jeevansathi.com', '9752091280', '8889344844', '0771-4056092', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (3, 'Delhi', 'Delhi', 'Laxmi Nagar', 'D-100,Street No.5,Vikas Marg,Laxmi Nagar,Near Metro station', '110092', 'mallika.saxena', 'Mallika', 'Rahul', 'mallika.saxena@jeevansathi.com', '9910009327', '8447680006', '011-43051437', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (4, 'Delhi', 'Delhi', 'Nehru Place', 'GF-12A, 94, Meghdoot Buliding, Nehru Place', '110007', 'emmi.sharma', 'Emmi', 'Rahul', 'emmi.sharma@jeevansathi.com', '9910006952', '8860333040', '011-46546396', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (5, 'Delhi', 'Delhi', 'Kamla Nagar', '36-A, Ground Flr, Kamla Nagar,Near Shakti Nagar Chowk', '110007', 'isha.mehra', 'Isha', 'Rahul', 'isha.mehra@jeevansathi.com', '9910007538', '8860252554', '011-64617545', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (6, 'Delhi', 'Delhi', 'CP', 'GF-4, Indra Prakash Building,21 Barakhamba Road, CP', '110001', 'Mona.sahni', 'Mona', 'Rahul', 'mona.sahni@jeevansathi.com', '9910006958', '9999385956', '011-64728959', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (7, 'Delhi', 'Delhi', 'Laxmi Nagar', 'D-100,Street No.5,Vikas Marg,Laxmi Nagar,Near Metro station', '110092', 'survit.c', 'Survit', 'Survit', 'survit.chakravarty@jeevansathi.com', '9910006834', '9971188579', '011-43051439', '011-43051438');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (8, 'Delhi', 'Delhi', 'Malviya Nagar', 'D-88,Lower Basement,Near Costa Coffee,Malviya Nagar', '110017', 'anuradha.ghosh', 'Anuradha', 'Rahul', 'anuradha.ghosh@jeevansathi.com', '9910006538', '9971109762', '011-405298725', '011-40507325');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (9, 'Delhi', 'Delhi', 'Malviya Nagar', 'D-88,Lower Basement,Near Costa Coffee,Malviya Nagar', '110017', 'shiv.kumar', 'Shiv', 'Shiv', 'shiv.kumar@jeevansathi.com', '9910006341', '9899460063', '011-46076783', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (10, 'Delhi', 'Delhi', 'Nehru Place', 'GF-12A, 94, Meghdoot Buliding, Nehru Place', '110019', 'ritu.saini', 'Ritu', 'Rahul', 'ritu.rani@jeevansathi.com', '9910006935', '8860101138', '011-46546396', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (11, 'Delhi', 'Delhi', 'Pitampura', '801,ITL Twin Towers,B-9,NSP,Opp.Wazirpur District Centre,Pitampura', '110034', 'parul.singh2', 'Parul', 'Rahul', 'parul.singh@jeevansathi.com', '9910007594', '9716040111', '011-42470689', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (12, 'Delhi', 'Delhi', 'Rajouri Garden', 'J-198, Shop No.-1 FF  Main Najafgarh Road, Rajouri Garden,Near Metro Pillar No.419', '110027', 'neha.sahni', 'Neha', 'Rahul', 'neha.sahni@jeevansathi.com', '9910006735', '9999076827', '011-45541437', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (13, 'Delhi', 'Delhi', 'Rajouri Garden', 'J-198, Shop No.-1 FF  Main Najafgarh Road, Rajouri Garden,Near Metro Pillar No.419', '110027', 'shashank.g', 'Shashank', 'Shashank', 'shashank.ghanekar@jeevansathi.com', '9910006826', '9811011662', '', '011-45541437');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (14, 'Delhi', 'Delhi', 'Rajouri Garden', 'J-198, Shop No.-1 FF  Main Najafgarh Road, Rajouri Garden,Near Metro Pillar No.419', '110027', 'sonia.bahl', 'Sonia', 'Rahul', 'sonia.bahl@jeevansathi.com', '9910006728', '9958210343', '011-45541436', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (15, 'Delhi', 'Delhi', 'Kamla Nagar', '36-A, Ground Flr, Kamla Nagar,Near Shakti Nagar Chowk', '110007', 'abhishek.s', 'Abhishek', 'Abhishek', 'abhishek.s@jeevansathi.com', '9910006927', '9999851814', '011-45019513', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (16, 'Delhi NCR', 'Noida', 'Noida', 'B-77, Sector 5, Noida', '201301', 'vandana.patel', 'Vandana', 'Rahul', 'vandana.patel@jeevansathi.com', '9910006954', '', '0120-4303192', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (17, 'Gujarat', 'Ahmedabad', 'CG Road', '203 & 204, Shitiratna, Panchvati Circle, C. G. Road', '380006', 'rashmi.sevani', 'Rashmi', 'Rahul', 'sevani.kumar@jeevansathi.com', '8511170744', '9825800086', '079-40233621', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (18, 'Gujarat', 'Baroda', 'Baroda', 'TF/302, SOHO Complex,Above Red Chillies,Malhar Point Cross Roads,Old Padra Road, Baroda-', '390007', 'rimpy.suri', 'Rimpy', 'Rahul', 'rimpy.suri@jeevansathi.com', '8511170741', '9714826268', '0265-3257824', '0265-2311200');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (19, 'Gujarat', 'Rajkot', 'Rajkot', '205, Pramukh Swami Arcade, A wing, Malavia Chowk', '360001', 'khushbu.karia', 'Khushbu', 'Rahul', 'karia@jeevansathi.com', '8511170742', '9898977755', '0281-6640837', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (20, 'Gujarat', 'Surat', 'Surat', '303, K.G.House, Above RBS Bank, Opp Citi Bank, Ghod Dod Road', '395007', 'yatish', 'Yatish', 'Yatish', 'korat@jeevansathi.com', '8511170743', '9979885557', '0261-6545077', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (21, 'Delhi', 'Delhi', 'Malviya Nagar', 'D-88,Lower Basement,Near Costa Coffee,Malviya Nagar', '122002', 'gaurav.t', 'Gaurav', 'Gaurav', 'gaurav.tripathi@jeevansathi.com', '9971188745', '9015597955', '011-40507325', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (22, 'Jharkhand', 'Jamshedpur', 'Jamshedpur', 'Bharat Business Centre,Room-6,2nd Flr,Ram Mandir Area,Bistupur', '831001', 'khushboo.singh', 'Khushboo', 'Rahul', 'khushboo.singh@jeevansathi.com', '9771490295', '8092099929', '0657-6572351', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (23, 'Karnataka', 'Bangalore', 'Dickenson Road', 'N 203 Manipal centre (MG Road) North block Front wing', '560042', 'afshan.tabassum', 'Afshan', 'Rahul', 'afshan.tabassum@jeevansathi.com', '7259031516', '9986506238', '080-40439009', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (24, 'Karnataka', 'Bangalore', 'Dickenson Road', 'N 203 Manipal centre (MG Road) North block Front wing', '560042', 'hijli.pumpa', 'Pumpa', 'Rahul', 'hijli.pumpa@jeevansathi.com', '7259031515', '9164752087', '080-40439053', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (25, 'Karnataka', 'Bangalore', 'Koramangla', '127, 1st Flr, Raheja Arcade, 5th Block, Koramangla Industrial Layout', '560095', 'aneesa.banu', 'Aneesa', 'Rahul', 'aneesa.banu@jeevansathi.com', '7259031517', '9986124585', '080-40927728', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (26, 'Madhya Pradesh', 'Bhopal', 'Bhopal', 'Harrison House, Ground Floor 2, 6 Malviya Nagar (NEAr Airtel office)', '462003', 'pooja.tiwari1', 'Pooja', 'Rahul', 'pooja.tiwari@jeevansathi.com', '9752091287', '8964004422', '0755-4202346', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (27, 'Madhya Pradesh', 'Indore', 'Indore', '201, Royal Ratan Building, 7 MG Road', '452001', 'varsha.radhwani', 'Varsha', 'Rahul', 'varsha.radhwani@jeevansathi.com', '9752091284', '9584288887', '0731-4010310', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (28, 'Madhya Pradesh', 'Jabalpur', 'NARBADA ROAD', 'KATANGA DUPLEX NO.2, BHUMIKA STATE, NARBADA ROAD,JABALPUR', '482001', 'jabalpur_1', 'Rishin', 'Rishin', 'jabalpur@jeevansathi.com', '9752091283', '7415124111', '0761-4042028', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (29, 'Madhya Pradesh', 'Gwalior', 'Lashkar', 'c/o Engineers Combine IFO Alankar Building Hospital Road Lashkar, Gwalior', '474009', 'gwalior_1', 'Archana', 'Rahul', 'archana.gwalior@jeevansathi.com', '9752091286', '9806830300', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (30, 'Maharashtra', 'Aurangabad', 'Aurangabad', 'H.S. Kandi Center, 2nd Flr, Central Wing,Above IndusInd Bank,Jalna Road', '431005', 'maya.paikrao', 'Maya', 'Rahul', 'maya.paikrao@jeevansathi.com', '7738399770', '9765231555', '0240-6611788', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (31, 'Maharashtra', 'Mumbai', 'Andheri(West)', 'Bhavesha Bldg,No 2,Veera Desai Road,Opp Andheri Sports Complex,Andheri(W)', '400058', 'ravindra.chaudhary', 'Ravindra', 'Jai', 'jai.chauhan@jeevansathi.com', '7738399761', '9833118829', '022-65157118', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (32, 'Maharashtra', 'Mumbai', 'Andheri(West)', 'Bhavesha Bldg,No 2,Veera Desai Road,Opp Andheri Sports Complex,Andheri(W)', '400058', 'sudeepta.m', 'Sudeepta', 'Rahul', 'sudeepta.mukherjee@jeevansathi.com', '7738399759', '9820837743', '022-65157118', '022-65157119');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (33, 'Maharashtra', 'Mumbai', 'Borivilli(W)', '101, Kesar Kripa,Opp Raj Mahal Hotel, Chandravarkar Road, Borivili(W)', '400092', 'anshu.tiwari', 'Anshu', 'Rahul', 'anshu.tiwari@jeevansathi.com', '7738399754', '8879106668', '022-65298503', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (34, 'Maharashtra', 'Mumbai', 'Borivilli(W)', '101, Kesar Kripa,Opp Raj Mahal Hotel, Chandravarkar Road, Borivili(W)', '400092', 'sheetal.s', 'Sheetal', 'Rahul', 'sheetal.shah@jeevansathi.com', '7738399755', '9920911103', '022-28936861', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (35, 'Maharashtra', 'Mumbai', 'Ghatkopar(E)', '18A,Kailash Plaza,Near ICICI Bank,Vallabhbaug Lane,Garodia Nagar,Ghatkopar(E)', '400077', 'gurmeet.singh', 'Gurmeet', 'Rahul', 'gurmeet.singh@jeevansathi.com', '7738399757', '9820225985', '022-65298505', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (36, 'Maharashtra', 'Mumbai', 'Ghatkopar(E)', '18A,Kailash Plaza,Near ICICI Bank,Vallabhbaug Lane,Garodia Nagar,Ghatkopar(E)', '400077', 'vijetha', 'Vijetha', 'Rahul', 'vijetha.poojary@jeevansathi.com', '7738399756', '9867758372', '022-65298505', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (37, 'Maharashtra', 'Mumbai', 'Mulund (West)', 'No 18-20,Maruti Arcade, J.N.Road,Opp Brijwasi Sweets, Mulund(West)', '400080', 'komal1', 'Komal', 'Rahul', 'komal.thange@jeevansathi.com', '7738399752', '7738393847', '022-65258442', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (38, 'Maharashtra', 'Mumbai', 'Mulund (West)', 'No 18-20,Maruti Arcade, J.N.Road,Opp Brijwasi Sweets, Mulund(West)', '400080', 'vaibhavi.n', 'Vaibhavi', 'Rahul', 'Vaibhavi.nalavade@jeevansathi.com', '7738399751', '9833556619', '022-65258442', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (39, 'Maharashtra', 'Mumbai', 'Andheri(East)', '216, Chintamani Plaza, Near Cine Magic, Andheri Kurla Road, Andheri(E)', '400099', 'kanchan.waral', 'Kanchan', 'Rahul', 'kanchan.waral@jeevansathi.com', '7738399760', '9833976240', '022-40071721', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (40, 'Maharashtra', 'Mumbai', 'Vashi', '1401, Maithali Signet, Opp Vashi Station, Sector 30A, Vashi', '400703', 'kirti.sethi', 'Kirti ', 'Rahul', 'kirti.sethi@jeevansathi.com', '7738399758', '9833628112', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (41, 'Maharashtra', 'Mumbai', 'Worli', '203,Sumer Kendra,Pandurang Budukar Marg,Worli', '400018', 'nisha.singh1', 'Nisha', 'Rahul', 'nisha.singh@jeevansathi.com', '7738399762', '9320435992', '022-43511900', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (42, 'Maharashtra', 'Mumbai', 'Chembur', '202-203,Swastik chambers,CST Road , Chembur(E)', '400071', 'aparna.karmakar', 'Aparna', 'Rahul', 'aparna.karmakar@jeevansathi.com', '7738399763', '9320435992', '022-42555100', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (43, 'Maharashtra', 'Nagpur', 'Nagpur', 'F-9, Phase-II, Achraj Towers, Chindwara Road,Sadar', '440013', 'neha.gupta', 'Neha', 'Rahul', 'nehagupta@jeevansathi.com', '7738399771', '8888859585', '0712-3298713', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (44, 'Maharashtra', 'Nashik/ Nasik', 'Nashik', 'B-8, Kusum Pushpa Apartment,Opp. Dairy Don, College Road', '422005', 'shreyas.malve', 'Shreyas', 'Shreyas', 'shreyas.malve@jeevansathi.com', '7738399773', '9595097779', '0253-6574227', '0253-6450112');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (45, 'Maharashtra', 'Pune', 'Deccan', 'B-1,Basement,CIFCO Centre,JM Road,Near Shiv Sagar,Deccan', '411043', 'preeti.thapa', 'Preeti', 'Rahul', 'preeti.thapa@jeevansathi.com', '7738399765', '9823555182', '020-64001015', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (46, 'Maharashtra', 'Pune', 'Deccan', 'B-1,Basement,CIFCO Centre,JM Road,Near Shiv Sagar,Deccan', '411043', 'gausiya.hannure', 'Gausiya', 'Rahul', 'gausiya.hannure@jeevansathi.com', '7738399769', '8007197786', '020-64000310', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (47, 'Maharashtra', 'Pune', 'Deccan', 'B-1,Basement,CIFCO Centre,JM Road,Near Shiv Sagar,Deccan', '411043', 'kavita.dhumal', 'Kavita', 'Rahul', 'kavita.dhumal@jeevansathi.com', '7738399767', '8698950303', '020-64001016', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (48, 'Maharashtra', 'Pune', 'Deccan', 'B-1,Basement,CIFCO Centre,JM Road,Near Shiv Sagar,Deccan', '411043', 'priyanka.unde', 'Priyanka', 'Pranav', 'priyanka.unde@jeevansathi.com', '7738399764', '9923888976', '020-65008286', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (49, 'Maharashtra', 'Pune', 'Deccan', 'B-1,Basement,CIFCO Centre,JM Road,Near Shiv Sagar,Deccan', '411043', 'manisha.j', 'Manisha', 'Rahul', 'manisha.joshi@jeevansathi.com', '7738399766', '9545877755', '020-64000304', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (50, 'Maharashtra', 'Pune', 'Koregaon Park', '2nd Flr, Gera Sterling (Opp German Bakery),North Main Road, Koregaon Park', '411001', 'karishma.s', 'Karishma', 'Rahul', 'karishma.Shaikh@jeevansathi.com', '7738399768', '8007301786', '020-64000126', '020-41407170');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (51, 'Maharashtra', 'Thane', 'Thane (West)', '1st Flr, No-7,Shreeji Arcade,No.325, Almedia Road, Panchpakhadi', '400602', 'sulochana.g', 'Sulochana', 'Rahul', 'sulochana.gaikwad@jeevansathi.com', '7738399753', '7666409060', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (52, 'Orissa', 'Bhubaneshwar', 'Bhubaneshwar', 'D-5, 5th Flr, Metro House, Bani Vihar Square', '751007', 'nisha.agarwal', 'Nisha', 'Rahul', 'nisha.a@jeevansathi.com', '9163375809', '9778944422', '0674-6450203', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (53, 'Punjab', 'Chandigarh', 'Chandigarh', 'SCO 14-15, First Floor, Sector-9D', '160009', 'harnoor.bedi', 'Harnoor', 'Rahul', 'harnoor.bedi@jeevansathi.com', '9915018427', '9914143311', '0172-5062246', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (54, 'Punjab', 'Ludhiana', 'Ludhiana', 'Navrang Complex, Nr Feroz Gandhi mkt, Opp Nehru Sidhant Kendra, Pakhowal Road', '141001', 'ripsy.arora', 'Ripsy', 'Rahul', 'ripsy.arora@jeevansathi.com', '9915018550', '8968911119', '0161-5035568', '0161-5074434');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (55, 'Rajasthan', 'Jaipur', 'Jaipur', '605, Crystal Mall, S.J.S. Highway, Bani Park', '302016', 'vima.pandey', 'Vima', 'Rahul', 'vima.pandey@jeevansathi.com', '', '9928600024', '0141-4048910', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (56, 'Uttar Pradesh', 'Agra', 'Agra', '1/133,Friends Shoppe Upr Ground Flr,Hariparvat Crossing(Opp Holiday Inn),MG Road', '282004', 'kirti.singh', 'Kirti ', 'Rahul', 'kirti.singh@jeevansathi.com', '7388807733', '9368451313', '0562-4051975', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (57, 'Uttar Pradesh', 'Kanpur', 'Kanpur', 'The Mall, 14/121-B, Main Road, Parade, Opp Raymonds', '208001', 'archie.g', 'Archie', 'Rahul', 'archie.gupta@jeevansathi.com', '8853220044', '9807088989', '0512-6452028', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (58, 'Uttar Pradesh', 'Kanpur', 'Kanpur', 'The Mall, 14/121-B, Main Road, Parade, Opp Raymonds', '208001', 'pravida.s', 'Pravida', 'Rahul', 'pravida.srivastava@jeevansathi.com', '8853220055', '9918901137', '0512-6452028', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (59, 'Uttar Pradesh', 'Kanpur', 'Kanpur', 'The Mall, 14/121-B, Main Road, Parade, Opp Raymonds', '208001', 'annie.gakhar', 'Annie', 'Rahul', 'annie.gakhar@jeevansathi.com', '8853220033', '7388336699', '0512-6452028', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (60, 'Uttar Pradesh', 'Lucknow', 'Lucknow', '31/107,Ground Flr, Sahu Building, Opp Universal Booksellers, Hazratganj', '226001', 'bhawna.piplani', 'Bhawna', 'Rahul', 'bhawna.piplani@jeevansathi.com', '7388805533', '9919046111', '0522-4074927', '0522-4074925');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (61, 'Uttar Pradesh', 'Lucknow', 'Lucknow', '31/107,Ground Flr, Sahu Building, Opp Universal Booksellers, Hazratganj', '226001', 'vartika.k', 'Vartika', 'Rahul', 'vartika.kesherwani@jeevansathi.com', '7388804433', '9919846460', '0522-4074929', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (62, 'Uttar Pradesh', 'Varanasi', 'Varanasi', 'C/25,Sri Ram Machinery Market,Opp.Rita Icecream Parlour, Varanasi', '221002', 'varanasi_1', 'Rita', 'Rahul', 'varanasi@jeevansathi.com', '7388806633', '9721223355', '0542-3273355', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (63, 'West Bengal', 'Kolkata', 'Lake Town', '336,Canal street,Gr. Floor, near Pizza hut,Lake town', '700017', 'sriparna.bose', 'Sriparna', 'Rahul', 'sriparna.bose@jeevansathi.com', '9163379809', '9007723210', '033-40030941', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (64, 'West Bengal', 'Kolkata', 'Gariahat', 'Identity Building No 5,1st Flr,38 Gariahat Road South(Near Selimpur Bus Stand)', '700031', 'kumarika.b', 'Kumarika', 'Rahul', 'kumarika.b@jeevansathi.com', '9163375809', '8100003500', '033-40066730', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (65, 'West Bengal', 'Kolkata', 'AJC Bose Road', '224 A J C Bose Road,KRISHNA BUILDING- 1st Floor,Module # 107 & 108,(Near Beckbagan Crossing)', '700017', 'ishita.biswas', 'Ishita', 'Rahul', 'ishita.biswas@jeevansathi.com', '9163376809', '9903980996', '033-40021768', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (66, 'Uttranchal', 'Dehradun', 'Dehradun', '77/1, Dilaram Chowk, Rajpur Road', '248001', 'rakhi.sharma', 'Rakhi', 'Rahul', 'rakhi.sharma@jeevansathi.com', '7388873003', '7500555576', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (67, 'Delhi', 'Delhi', 'Laxmi Nagar', 'D-100,Street No.5,Vikas Marg,Laxmi Nagar,Near Metro station', '110092', 'sunanda.sarkar', 'Sunanda', 'Rahul', 'sunanda.sarkar@jeevansathi.com', '9971662150', '9582575531', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (68, 'Delhi', 'Delhi', 'Rajouri Garden', 'J-198, Shop No.-1 FF  Main Najafgarh Road, Rajouri Garden,Near Metro Pillar No.419', '110027', 'sahil.malhotra', 'Sahil', 'Sahil', 'sahil.malhotra@jeevansathi.com', '9971660808', '9582425201', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (69, 'Pathankot', 'Pathankot', 'Pathankot', 'First Floor Anglo Tower, Opposite Civil Hospital', '145001', 'pathankot_1', 'Milan', 'Milan', 'pathankot.js@jeevansathi.com', '', '9888098044', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (70, 'Delhi', 'Delhi', 'Rajouri Garden', 'J-198, Shop No.-1 FF  Main Najafgarh Road, Rajouri Garden,Near Metro Pillar No.419', '110027', 'ritu.darshi', 'Ritu', 'Rahul', 'ritu.darshi@jeevansathi.com', '9971176513', '9999184106', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (71, 'Haryana', 'Gurgaon', 'Gurgaon', 'B-15,Uper FF,Institutional Area,Sector 32, Near Louis Berger', '122002', 'aayush.singhal', 'Aayush', 'Aayush', 'aayush.singhal@jeevansathi.com', '9971188239', '', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (72, 'Haryana', 'Gurgaon', 'Gurgaon', 'SF-55, First Floor, Galleria Commercial Complex, DLF Phase 4', '122002', 'shaista.aliya', 'Shaista', 'Rahul', 'shaista.aliya@jeevansathi.com', '9971188239', '', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (73, 'Bihar', 'Ranchi ', 'Ranchi', 'Shop-111, FF,Malabar Enclave,Bariatu,Ranchi,Near DAV Public School', '834009', 'ranchi_1', 'Vikram ', 'Vikram ', 'shivani.ranchi@jeevansathi.com', '9971008753', '9097297213', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (74, 'Madhya Pradesh', 'Bilaspur ', 'Bilaspur', 'Ashish Bhawan,M/s Catmoss Kids Wear,Beside HDFC Bank Link Road(CG)', '495001', 'bilaspur_1', 'Rajeev ', 'Rajeev ', 'bilaspur@jeevansathi.com', '9971008762', '9039332007', '', '');
INSERT INTO `SMS_CONTACTS` (`ID`, `STATE`, `BRANCH`, `LOCALITY`, `ADDRESS`, `PINCODE`, `USERNAME`, `AGENT_NAME`, `SMS_NAME`, `EMAIL`, `SMS_MOBILE`, `OUTBOUND_MOBILE`, `LANDLINE_1`, `LANDLINE_2`) VALUES (75, 'Andhra Pradesh', 'Hyderabad', 'Begumpet', '6-3-1192/1/1,Office No:113 To 115,3rd Block,FF,White House,Kundan Bagh,Begumpet,Beside Life Style', '500016', 'shyam.mateti', 'Shyam', 'Shyam', 'shyam.mateti@jeevansathi.com', '', '9963902228', '040-44751033', '');
        
