use newjs;
CREATE TABLE `PHOTO_IMPORT_USERDATA` (
  `ID` mediumint(1) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(1) NOT NULL,
  `SOURCE` enum('facebook','picasa','flickr') NOT NULL,
  `UNIQUE_ID` varchar(100) NOT NULL,
  `ENTRY_DT` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_ID` (`SOURCE`,`UNIQUE_ID`,`PROFILEID`),
  KEY `PROFILEID` (`PROFILEID`),
  KEY `DATE` (`ENTRY_DT`)
) ENGINE=MYISAM;

CREATE TABLE `PICTURE_DETAILS` (
  `ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) DEFAULT NULL,
  `SIZE` mediumint(8) unsigned NOT NULL,
  `HEIGHT` mediumint(8) unsigned NOT NULL,
  `WIDTH` mediumint(8) unsigned NOT NULL,
  `FOCAL_LENGTH` mediumint(8) unsigned NOT NULL,
  `CAMERA_DATETIME` datetime NOT NULL,
  `MAKE` varchar(40) DEFAULT NULL,
  `MODEL` varchar(100) NOT NULL,
  `ENTRY_DT` date NOT NULL,
  `UNSCREENED_PICTUREID` int(11) NOT NULL,
  `SCREENED_PICTUREID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNSCREENED_PICTUREID` (`UNSCREENED_PICTUREID`,`SCREENED_PICTUREID`),
  KEY `PROFILEID` (`PROFILEID`),
  KEY `CAMERA_DATETIME` (`CAMERA_DATETIME`),
  KEY `SCREENED_PICTUREID` (`SCREENED_PICTUREID`)
) ENGINE=MyISAM;
