use bms2;
ALTER TABLE BANNER ADD BannerJsProfileCompletionState VARCHAR(20) NOT NULL;
UPDATE ZONE SET ZoneCriterias=CONCAT(ZoneCriterias,',PROFILE_COMPLETE_STATE') WHERE ZoneCriterias LIKE  '%GENDER%';
ALTER TABLE CRITERIA_MAPPING ADD  PROFILE_COMPLETE_STATE char(25) NOT NULL ;
UPDATE CRITERIA_MAPPING SET  PROFILE_COMPLETE_STATE =  'N' WHERE  CriteriaId='1';
UPDATE CRITERIA_MAPPING SET  PROFILE_COMPLETE_STATE =  'N' WHERE  CriteriaId='2';
UPDATE CRITERIA_MAPPING SET  PROFILE_COMPLETE_STATE =  'Y' WHERE  CriteriaId='3';
UPDATE CRITERIA_MAPPING SET  PROFILE_COMPLETE_STATE =  'Y' WHERE  CriteriaId='4';
