use MIS;
DROP TABLE IF EXISTS EVALUE_TRACKING;
CREATE TABLE EVALUE_TRACKING (
  ID mediumint(9) NOT NULL AUTO_INCREMENT,
  VIEWED mediumint(9) NOT NULL,
  VIEWER mediumint(9) NOT NULL,
  SUBSCRIPTION varchar(10) NOT NULL,
  `PAGE` varchar(50) DEFAULT NULL,
  `TYPE` varchar(1) NOT NULL,
  `TIME` datetime NOT NULL,
  FLAG varchar(1) NOT NULL,
  DEVICE varchar(1) NOT NULL,
  PRIMARY KEY (ID),
  KEY VIEWED (VIEWED)
)
