
use newjs;

UPDATE JPROFILE SET PROMO_MAILS='U' WHERE PROMO_MAILS='N';
UPDATE JPROFILE SET PROMO_MAILS='S' WHERE PROMO_MAILS IN ('','Q','Y');

UPDATE JPROFILE SET SERVICE_MESSAGES='U' WHERE SERVICE_MESSAGES='N';
UPDATE JPROFILE SET SERVICE_MESSAGES='S' WHERE SERVICE_MESSAGES IN ('','r','Y');

UPDATE JPROFILE SET PERSONAL_MATCHES='U' WHERE PERSONAL_MATCHES='N';
UPDATE JPROFILE SET PERSONAL_MATCHES='A' WHERE PERSONAL_MATCHES IN('','Y');
