use newjs;
create table JPROFILE_NEW like JPROFILE;
ALTER TABLE `JPROFILE_NEW` add `activatedKey` tinyint(3) NOT NULL DEFAULT '1', change `PROFILEID` `PROFILEID` int(11) unsigned NOT NULL, drop primary key, DROP INDEX `USERNAME`, DROP INDEX `EMAIL`, ADD PRIMARY KEY ( `PROFILEID` , `activatedKey` ) , ADD UNIQUE (`USERNAME` ,`activatedKey`), ADD UNIQUE (`EMAIL` ,`activatedKey`);
alter table `JPROFILE_NEW` change `PROFILEID` `PROFILEID` int(11) unsigned NOT NULL AUTO_INCREMENT;
alter table `JPROFILE_NEW` PARTITION BY LIST (`activatedKey`) (PARTITION p1 VALUES IN (1),  PARTITION p0 VALUES IN (0));
insert into JPROFILE_NEW select *,if(ACTIVATED='D',0,1) from JPROFILE;
rename table JPROFILE to JPROFILE_ARCH;rename table JPROFILE_NEW to JPROFILE;

drop trigger INSERT_SWAP;
drop trigger UPDATE_SWAP;
delimiter |
create trigger INSERT_SWAP
AFTER INSERT ON JPROFILE
FOR EACH ROW
begin
insert ignore into SWAP_JPROFILE set PROFILEID=new.PROFILEID;
end
|
create trigger UPDATE_SWAP
AFTER UPDATE ON JPROFILE
FOR EACH ROW
BEGIN IF(@DONT_UPDATE_TRIGGER is NULL) THEN INSERT ignore into newjs.SWAP_JPROFILE set PROFILEID=new.PROFILEID; END IF; 
END
|
delimiter ;

CREATE TABLE `JSARCHIVED` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `PROFILEID` int(10) unsigned NOT NULL DEFAULT '0',  `DEACTIVE_DATE` date NOT NULL DEFAULT '0000-00-00',  `USERNAME` varchar(40) DEFAULT NULL,  `EMAIL` varchar(100) DEFAULT NULL,  `STATUS` char(1) DEFAULT 'Y',  `ACT_DATE` date NOT NULL DEFAULT '0000-00-00',  PRIMARY KEY (`ID`),  KEY `PROFILEID` (`PROFILEID`),  KEY `DEACTIVE_DATE` (`DEACTIVE_DATE`),  KEY `USERNAME` (`USERNAME`),  KEY `EMAIL` (`EMAIL`),  KEY `ACT_DATE` (`ACT_DATE`));
use MIS;
CREATE TABLE `INACTIVE_USERS` (`ID` INT NOT NULL AUTO_INCREMENT ,`PROFILEID` INT NOT NULL ,`SEN_DATE` DATE NOT NULL ,`TYPE_MAIL` INT NOT NULL ,PRIMARY KEY ( `ID` ) ,INDEX ( `PROFILEID` ));
/*need to run in matchalert server only*/
CREATE TABLE matchalerts.JPROFILE like newjs.JPROFILE;
