use database newjs;

ALTER TABLE JPROFILE ADD PHONE_WITH_STD VARCHAR(105) NOT NULL default '',ADD PROFILE_STATUS VARCHAR(20) NOT NULL default '', ADD INDEX (PHONE_WITH_STD);

UPDATE JPROFILE set PHONE_WITH_STD=CONCAT(STD,PHONE_RES);

CREATE TABLE ABUSIVE_PHONE (PHONE_WITH_STD varchar(105) NOT NULL default '' PRIMARY KEY) ENGINE=MyISAM;

CREATE TABLE CALL_DIVERT (STATUS varchar(5) NOT NULL default '') ENGINE=MyISAM;

INSERT INTO CALL_DIVERT (STATUS) VALUES ('No');

use database incentive;

CREATE TABLE CAMPAIGN (CAMPAIGN VARCHAR(50),ACTIVE ENUM('Y','N')) ENGINE=MyISAM;
 
