use newjs;

CREATE TABLE `BOOKMARKS_ACTIVE` (
  `BOOKMARKER` int(11) unsigned NOT NULL default '0',
  `BOOKMARKEE` int(11) unsigned NOT NULL default '0',
  `BKDATE` datetime NOT NULL default '0000-00-00 00:00:00',
  `BKNOTE` varchar(255) NOT NULL,
  `SEEN` char(1) NOT NULL,
  UNIQUE KEY `BOOK_INDEX` (`BOOKMARKER`,`BOOKMARKEE`),
  KEY `BOOKMARKEE` (`BOOKMARKEE`)
) ENGINE=MyISAM;

CREATE TABLE `BOOKMARKS_INACTIVE` (
  `BOOKMARKER` int(11) unsigned NOT NULL default '0',
  `BOOKMARKEE` int(11) unsigned NOT NULL default '0',
  `BKDATE` datetime NOT NULL default '0000-00-00 00:00:00',
  `BKNOTE` varchar(255) NOT NULL,
  `SEEN` char(1) NOT NULL,
  UNIQUE KEY `BOOK_INDEX` (`BOOKMARKER`,`BOOKMARKEE`),
  KEY `BOOKMARKEE` (`BOOKMARKEE`)
) ENGINE=MyISAM;
