use billing;

UPDATE SERVICES SET PRICE_RS_TAX=150,PRICE_DOL=5,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R2W';
UPDATE SERVICES SET PRICE_RS_TAX=300,PRICE_DOL=9,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R1';
UPDATE SERVICES SET PRICE_RS_TAX=600,PRICE_DOL=18,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R2';
UPDATE SERVICES SET PRICE_RS_TAX=900,PRICE_DOL=27,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R3';
UPDATE SERVICES SET PRICE_RS_TAX=1200,PRICE_DOL=36,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R4';
UPDATE SERVICES SET PRICE_RS_TAX=1500,PRICE_DOL=45,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R5';
UPDATE SERVICES SET PRICE_RS_TAX=1800,PRICE_DOL=54,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R6';
UPDATE SERVICES SET PRICE_RS_TAX=2100,PRICE_DOL=63,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R7';
UPDATE SERVICES SET PRICE_RS_TAX=2400,PRICE_DOL=72,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R8';
UPDATE SERVICES SET PRICE_RS_TAX=2700,PRICE_DOL=81,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R9';
UPDATE SERVICES SET PRICE_RS_TAX=3300,PRICE_DOL=99,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R11';
UPDATE SERVICES SET PRICE_RS_TAX=3600,PRICE_DOL=108,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='R12';

INSERT IGNORE INTO newjs.SWAP_JPROFILE SELECT DISTINCT PROFILEID FROM billing.SERVICE_STATUS WHERE SERVEFOR LIKE '%R%' AND ACTIVE ='Y' AND EXPIRY_DT >= 'now()' AND ACTIVATED_ON <= 'now()'; 
