use newjs;

update JPARTNER set PARTNER_CITYRES=REPLACE(PARTNER_CITYRES,'MH07','MH24');
update JPARTNER set PARTNER_CITYRES=REPLACE(PARTNER_CITYRES,'KE01','KE06');
update JPARTNER set PARTNER_CITYRES=REPLACE(PARTNER_CITYRES,'KE02','KE13');
update JPARTNER set PARTNER_CITYRES=REPLACE(PARTNER_CITYRES,'KE03','KE13');
