use billing;

UPDATE SERVICES SET PRICE_RS_TAX=695,PRICE_DOL=17,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P2W';
UPDATE SERVICES SET PRICE_RS_TAX=795,PRICE_DOL=28,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P1';
UPDATE SERVICES SET PRICE_RS_TAX=1695,PRICE_DOL=51,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P2';
UPDATE SERVICES SET PRICE_RS_TAX=1895,PRICE_DOL=61,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P3';
UPDATE SERVICES SET PRICE_RS_TAX=2195,PRICE_DOL=71,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P4';
UPDATE SERVICES SET PRICE_RS_TAX=2445,PRICE_DOL=78,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P5';
UPDATE SERVICES SET PRICE_RS_TAX=2695,PRICE_DOL=81,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P6';
UPDATE SERVICES SET PRICE_RS_TAX=2895,PRICE_DOL=89,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P7';
UPDATE SERVICES SET PRICE_RS_TAX=3195,PRICE_DOL=98,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P8';
UPDATE SERVICES SET PRICE_RS_TAX=3395,PRICE_DOL=101,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P9';
UPDATE SERVICES SET PRICE_RS_TAX=3495,PRICE_DOL=112,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P11';
UPDATE SERVICES SET PRICE_RS_TAX=4495,PRICE_DOL=139,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P12';
UPDATE SERVICES SET PRICE_RS_TAX=5695,PRICE_DOL=151,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='PL';


UPDATE SERVICES SET PRICE_RS_TAX=895,PRICE_DOL=24,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C2W';
UPDATE SERVICES SET PRICE_RS_TAX=1045,PRICE_DOL=34,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C1';
UPDATE SERVICES SET PRICE_RS_TAX=2295,PRICE_DOL=71,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C2';
UPDATE SERVICES SET PRICE_RS_TAX=2395,PRICE_DOL=81,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C3';
UPDATE SERVICES SET PRICE_RS_TAX=2795,PRICE_DOL=91,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C4';
UPDATE SERVICES SET PRICE_RS_TAX=3095,PRICE_DOL=98,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C5';
UPDATE SERVICES SET PRICE_RS_TAX=3395,PRICE_DOL=101,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C6';
UPDATE SERVICES SET PRICE_RS_TAX=3745,PRICE_DOL=112,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C7';
UPDATE SERVICES SET PRICE_RS_TAX=4095,PRICE_DOL=118,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C8';
UPDATE SERVICES SET PRICE_RS_TAX=4295,PRICE_DOL=121,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C9';
UPDATE SERVICES SET PRICE_RS_TAX=4345,PRICE_DOL=132,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C11';
UPDATE SERVICES SET PRICE_RS_TAX=5095,PRICE_DOL=155,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C12';
UPDATE SERVICES SET PRICE_RS_TAX=5995,PRICE_DOL=171,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='CL';

UPDATE DIRECT_CALL_COUNT SET COUNT = '25' WHERE SERVICEID = 'C2' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '50' WHERE SERVICEID = 'C3' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '75' WHERE SERVICEID = 'C4' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '75' WHERE SERVICEID = 'C5' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '100' WHERE SERVICEID = 'C6' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '100' WHERE SERVICEID = 'C7' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '100' WHERE SERVICEID = 'C8' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '150' WHERE SERVICEID = 'C9' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '150' WHERE SERVICEID = 'C11' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '175' WHERE SERVICEID = 'C12' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '250' WHERE SERVICEID = 'CL' ;

UPDATE DIRECT_CALL_COUNT SET COUNT = '25' WHERE SERVICEID = 'P2' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '50' WHERE SERVICEID = 'P3' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '75' WHERE SERVICEID = 'P4' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '75' WHERE SERVICEID = 'P5' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '100' WHERE SERVICEID = 'P6' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '100' WHERE SERVICEID = 'P7' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '100' WHERE SERVICEID = 'P8' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '150' WHERE SERVICEID = 'P9' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '150' WHERE SERVICEID = 'P11' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '175' WHERE SERVICEID = 'P12' ;
UPDATE DIRECT_CALL_COUNT SET COUNT = '250' WHERE SERVICEID = 'PL' ;
