use bms2;
ALTER TABLE BANNER ADD BannerJsFtoStatus VARCHAR(20) NOT NULL;
UPDATE ZONE SET ZoneCriterias=CONCAT(ZoneCriterias,',FTO_STATE') WHERE ZoneCriterias LIKE  '%GENDER%';
ALTER TABLE CRITERIA_MAPPING ADD  FTO_STATE char(255) NOT NULL ;
UPDATE CRITERIA_MAPPING SET  FTO_STATE =  'N' WHERE  CriteriaId='1';
UPDATE CRITERIA_MAPPING SET  FTO_STATE =  'N' WHERE  CriteriaId='2';
UPDATE CRITERIA_MAPPING SET  FTO_STATE =  'Y' WHERE  CriteriaId='3';
UPDATE CRITERIA_MAPPING SET  FTO_STATE =  'Y' WHERE  CriteriaId='4';


ALTER TABLE BANNER ADD BannerJsFtoExpiry VARCHAR(20) NOT NULL;
UPDATE ZONE SET ZoneCriterias=CONCAT(ZoneCriterias,',FTO_EXPIRY') WHERE ZoneCriterias LIKE  '%GENDER%';
ALTER TABLE CRITERIA_MAPPING ADD  FTO_EXPIRY char(255) NOT NULL ;
UPDATE CRITERIA_MAPPING SET  FTO_EXPIRY =  'N' WHERE  CriteriaId='1';
UPDATE CRITERIA_MAPPING SET  FTO_EXPIRY =  'N' WHERE  CriteriaId='2';
UPDATE CRITERIA_MAPPING SET  FTO_EXPIRY =  'Y' WHERE  CriteriaId='3';
UPDATE CRITERIA_MAPPING SET  FTO_EXPIRY =  'Y' WHERE  CriteriaId='4';

