use jeevansathi_mailer;

UPDATE  `EMAIL_TYPE` SET  `HEADER_TPL` = NULL ,
`FOOTER_TPL` = NULL ,
`TEMPLATE_EX_LOCATION` = NULL ,
`SENDER_EMAILID` =  'info@jeevansathi.com',
`DESCRIPTION` = NULL ,
`REPLY_TO_ENABLED` = NULL ,
`FROM_NAME` =  'Jeevansathi Info',
`REPLY_TO_ADDRESS` = NULL ,
`MAX_COUNT_TO_BE_SENT` = NULL ,
`REQUIRE_AUTOLOGIN` = NULL ,
`PRE_HEADER` = NULL WHERE  `ID` =  '1771' LIMIT 1 ;

UPDATE  `EMAIL_TYPE` SET  `HEADER_TPL` = NULL ,
`FOOTER_TPL` = NULL ,
`TEMPLATE_EX_LOCATION` = NULL ,
`DESCRIPTION` = NULL ,
`GENDER` = NULL ,
`PHOTO_PROFILE` = NULL ,
`REPLY_TO_ENABLED` = NULL ,
`FROM_NAME` =  'Jeevansathi Info',
`REPLY_TO_ADDRESS` = NULL ,
`MAX_COUNT_TO_BE_SENT` = NULL ,
`FTO_FLAG` = NULL ,
`PRE_HEADER` = NULL WHERE  `ID` =  '1775' LIMIT 1 ;

UPDATE  `EMAIL_TYPE` SET  `HEADER_TPL` = NULL ,
`FOOTER_TPL` = NULL ,
`TEMPLATE_EX_LOCATION` = NULL ,
`REPLY_TO_ENABLED` = NULL ,
`FROM_NAME` =  'Jeevansathi Contacts',
`REPLY_TO_ADDRESS` = NULL ,
`MAX_COUNT_TO_BE_SENT` = NULL ,
`REQUIRE_AUTOLOGIN` = NULL WHERE  `ID` =  '1759' LIMIT 1 ;

UPDATE  `EMAIL_TYPE` SET  `HEADER_TPL` = NULL ,
`FOOTER_TPL` = NULL ,
`TEMPLATE_EX_LOCATION` = NULL ,
`SENDER_EMAILID` =  'visitoralert@jeevansathi.com',
`DESCRIPTION` = NULL ,
`REPLY_TO_ENABLED` = NULL ,
`FROM_NAME` =  'Jeevansathi Alerts',
`REPLY_TO_ADDRESS` = NULL ,
`MAX_COUNT_TO_BE_SENT` = NULL ,
`PRE_HEADER` = NULL WHERE  `ID` =  '1761' LIMIT 1 ;

UPDATE  `EMAIL_TYPE` SET  `GENDER` = NULL ,
`PHOTO_PROFILE` = NULL ,
`REPLY_TO_ENABLED` = NULL ,
`FROM_NAME` =  'Jeevansathi Contacts',
`REPLY_TO_ADDRESS` = NULL ,
`MAX_COUNT_TO_BE_SENT` = NULL ,
`FTO_FLAG` = NULL WHERE  `ID` =  '1754' LIMIT 1 ;

UPDATE  `EMAIL_TYPE` SET  `HEADER_TPL` = NULL ,
`TEMPLATE_EX_LOCATION` = NULL ,
`GENDER` = NULL ,
`PHOTO_PROFILE` = NULL ,
`REPLY_TO_ENABLED` = NULL ,
`FROM_NAME` =  'Jeevansathi Info' WHERE  `ID` =  '1774' LIMIT 1 ;

UPDATE  `EMAIL_TYPE` SET  `HEADER_TPL` = NULL ,
`FOOTER_TPL` = NULL ,
`TEMPLATE_EX_LOCATION` = NULL ,
`REPLY_TO_ENABLED` = NULL ,
`FROM_NAME` =  'Jeevansathi Info',
`REPLY_TO_ADDRESS` = NULL ,
`MAX_COUNT_TO_BE_SENT` = NULL ,
`PRE_HEADER` = NULL WHERE  `ID` =  '1741' LIMIT 1 ;

UPDATE  `EMAIL_TYPE` SET  `HEADER_TPL` = NULL ,
`FOOTER_TPL` = NULL ,
`TEMPLATE_EX_LOCATION` = NULL ,
`GENDER` = NULL ,
`PHOTO_PROFILE` = NULL ,
`REPLY_TO_ENABLED` = NULL ,
`FROM_NAME` =  'Jeevansathi Info',
`REPLY_TO_ADDRESS` = NULL ,
`MAX_COUNT_TO_BE_SENT` = NULL ,
`FTO_FLAG` = NULL ,
`PRE_HEADER` = NULL WHERE  `ID` =  '1743' LIMIT 1 ;

UPDATE  `EMAIL_TYPE` SET  `HEADER_TPL` = NULL ,
`FOOTER_TPL` = NULL ,
`TEMPLATE_EX_LOCATION` = NULL ,
`GENDER` = NULL ,
`PHOTO_PROFILE` = NULL ,
`REPLY_TO_ENABLED` = NULL ,
`FROM_NAME` =  'Jeevansathi Info',
`REPLY_TO_ADDRESS` = NULL ,
`MAX_COUNT_TO_BE_SENT` = NULL ,
`FTO_FLAG` = NULL ,
`PRE_HEADER` = NULL WHERE  `ID` =  '1744' LIMIT 1 ;

UPDATE  `EMAIL_TYPE` SET  `HEADER_TPL` = NULL ,
`FOOTER_TPL` = NULL ,
`TEMPLATE_EX_LOCATION` = NULL ,
`GENDER` = NULL ,
`PHOTO_PROFILE` = NULL ,
`FROM_NAME` =  'Jeevansathi Contacts',
`MAX_COUNT_TO_BE_SENT` = NULL WHERE  `ID` =  '1753' LIMIT 1 ;


UPDATE  `EMAIL_TYPE` SET  `HEADER_TPL` = NULL ,
`FOOTER_TPL` = NULL ,
`TEMPLATE_EX_LOCATION` = NULL ,
`GENDER` = NULL ,
`PHOTO_PROFILE` = NULL ,
`FROM_NAME` =  'Jeevansathi Contacts',
`MAX_COUNT_TO_BE_SENT` = NULL WHERE  `ID` =  '1751' LIMIT 1 ;
