use newjs;

ALTER TABLE `PICTURE_NEW` ADD `UNSCREENED_TITLE` VARCHAR( 40 ) NOT NULL ;

ALTER TABLE `PICTURE_NEW` CHANGE `PICTUREID` `PICTUREID` INT( 11 ) UNSIGNED DEFAULT '0' NOT NULL ,
CHANGE `PROFILEID` `PROFILEID` INT( 11 ) UNSIGNED DEFAULT '0';

ALTER TABLE `PICTURE_FOR_SCREEN_NEW` DROP `ONLY_TITLE_SCREENED`;

ALTER TABLE `PICTURE_FOR_SCREEN_NEW` CHANGE `PICTUREID` `PICTUREID` INT( 11 ) UNSIGNED DEFAULT '0' NOT NULL ,
CHANGE `PROFILEID` `PROFILEID` INT( 11 ) UNSIGNED DEFAULT '0';

INSERT INTO SMS_STATUS(SMS_KEY,STATUS) VALUES ("SI_PHOTOSCREEN_REJ","Y");

UPDATE SMS_STATUS SET STATUS = "Y" WHERE SMS_KEY = "SI_PHOTOSCREEN";

alter table SMS_DETAIL modify column SMS_KEY varchar(20);

ALTER TABLE `JPROFILE` CHANGE `PHOTOSCREEN` `PHOTOSCREEN` TINYINT UNSIGNED DEFAULT '1' 

use jsadmin;

ALTER TABLE `SCREEN_PHOTOS_FROM_MAIL` CHANGE `STATUS` `STATUS` VARCHAR( 25 );

use test;

CREATE TABLE `TEMP_PROFILEID` (
  `PROFILEID` mediumint(11) unsigned NOT NULL,
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
