--shards
use newjs;

CREATE TABLE AP_CONTACTS_DELETE LIKE CONTACTS;
CREATE TABLE AP_CONTACTS_ERROR LIKE CONTACTS;
CREATE TABLE AP_MESSAGE_LOG_DELETE LIKE MESSAGE_LOG;
CREATE TABLE newjs.AP_DELETED_MESSAGES_DELETE LIKE newjs.DELETED_MESSAGES;
CREATE TABLE newjs.AP_EOI_VIEW_LOG_DELETE LIKE newjs.EOI_VIEWED_LOG;


--Master
use Assisted_Product;
CREATE TABLE Assisted_Product.AP_BACKUP LIKE Assisted_Product.AUTOMATED_CONTACTS_TRACKING;
