use newjs;
UPDATE `EDUCATION_LEVEL_NEW` SET `OLD_VALUE` = '4' WHERE `ID` = '25' ;
UPDATE `EDUCATION_LEVEL_NEW` SET `OLD_VALUE` = '4' WHERE `ID` = '26' ;
UPDATE `EDUCATION_LEVEL_NEW` SET `OLD_VALUE` = '5' WHERE `ID` = '27' ;
