use Assisted_Product;


CREATE TABLE `DELETED_AP_CALL_HISTORY` (
 `PROFILEID` int(11) NOT NULL,
 `MATCH_ID` int(11) NOT NULL,
 `REQUEST_DATE` datetime NOT NULL,
 `CALL_DATE` datetime NOT NULL,
 `CALL_STATUS` enum('Y','N','C') NOT NULL,
 `TELECALLER` varchar(50) NOT NULL,
 `FOLDER` char(3) NOT NULL,
 PRIMARY KEY (`PROFILEID`,`MATCH_ID`)
) ENGINE=MyISAM
