CREATE DATABASE  IF NOT EXISTS `CONTACT_ENGINE` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `CONTACT_ENGINE`;
-- MySQL dump 10.13  Distrib 5.6.24, for osx10.8 (x86_64)
--
-- Host: 172.16.3.185    Database: CONTACT_ENGINE
-- ------------------------------------------------------
-- Server version	5.5.25a-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `BUTTON_RESPONSE`
--

DROP TABLE IF EXISTS `BUTTON_RESPONSE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;

CREATE TABLE `BUTTON_RESPONSE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CHANNEL` varchar(45) NOT NULL,
  `SOURCE` varchar(45) NOT NULL,
  `VIEWER` varchar(45) DEFAULT NULL,
  `TYPE` varchar(45) DEFAULT NULL,
  `BUTTONS` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=latin1 AUTO_INCREMENT=57 ;

-- 
-- Dumping data for table `BUTTON_RESPONSE`
-- 

INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (1, 'P', 'VDP', '', 'N', '[{"TYPE":"INITIATE","label":"Send Interest","active":"true","primary":"true","secondary":"true","tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"Chat","active":"true","primary":null,"secondary":null,"tracking":null,"icon":null},{"TYPE":"SHORTLIST","label":"Remove Shortlist","active":"true","primary":null,"secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (2, 'P', 'VDP', 'S', 'A', '[{"TYPE":"MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CANCEL","label":"Cancel Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"Chat","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (3, 'P', 'VDP', 'S', 'D', '[{"TYPE":"TEXT","label":"They declined interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (4, 'P', 'VDP', 'S', 'E', '[{"TYPE":"TEXT","label":"You cancelled interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"INITIATE","label":"Send Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (5, 'P', 'VDP', 'S', 'C', '[{"TYPE":"TEXT","label":"You cancelled interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"ACCEPT","label":"Accept Again","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (6, 'P', 'VDP', 'R', 'I', '[{"TYPE":"TEXT","label":"You have received interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"ACCEPT","label":"Accept","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"DECLINE","label":"Decline","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (7, 'P', 'VDP', 'R', 'A', '[{"TYPE":"MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"DECLINE","label":"Decline Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"Chat","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (8, 'P', 'VDP', 'R', 'D', '[{"TYPE":"TEXT","label":"You declined interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"ACCEPT","label":"Accept Again","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (9, 'P', 'VDP', 'R', 'C', '[{"TYPE":"TEXT","label":"They cancelled interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (10, 'P', 'VDP', 'R', 'E', '[{"TYPE":"TEXT","label":"They cancelled interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (11, 'P', 'S', '', 'N', '[{"TYPE":"INITIATE","label":"","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"SHORTLIST","label":"","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (12, 'P', 'INTEREST_RECEIVED', '', '', '[{"TYPE":"ACCEPT","label":"Accept","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"DECLINE","label":"Decline","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (13, 'P', 'INTEREST_SENT', '', '', '[{"TYPE":"REMINDER","label":"Send Reminder","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (14, 'P', 'S', '', '', '[{"TYPE":"INITIATE","label":"Send Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"Chat","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"SHORTLIST","label":"Shortlist","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (15, 'P', 'MATCH_ALERT', '', '', '[{"TYPE":"INITIATE","label":"Send Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"Chat","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"SHORTLIST","label":"Shortlist","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (16, 'P', 'ACCEPTANCES_RECEIVED', '', '', '[{"TYPE":"MESSAGE","label":"Send Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (17, 'P', 'ACCEPTANCES_SENT', '', '', '[{"TYPE":"MESSAGE","label":"Send Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (18, 'P', 'VDP', 'S', 'I', '[{"TYPE":"REMINDER","label":"Send Reminder","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CANCEL_INTEREST","label":"Cancel Interest","active":"true","primary":null,"secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"Chat","active":"true","primary":null,"secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (19, 'P', 'VDP', 'S', 'R', '[{"TYPE":"REMINDER","label":"Send Reminder","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CANCEL_INTEREST","label":"Cancel Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"Chat","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (20, 'P', 'VDP', 'S', 'B', '[{"TYPE":"IGNORE","label":"Unblock","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"TEXT","label":"You have blocked this profile","active":null,"primary":null,"secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (21, 'P', 'SHORTLIST', '', '', '[{"TYPE":"SHORTLIST","label":"Shortlisted","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (22, 'P', 'VISITORS', '', '', '[{"TYPE":"INITIATE","label":"Send Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"Chat","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"SHORTLIST","label":"Shortlist","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (23, 'P', 'IGNORED_PROFILES', '', '', '[{"TYPE":"IGNORE","label":"Unblock","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"TEXT","label":"Changed your mind?","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (24, 'P', 'NOT_INTERESTED_BY_ME', '', 'D', '[{"TYPE":"ACCEPT","label":"Accept Again","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"TEXT","label":"Changed your mind?","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (25, 'P', 'NOT_INTERESTED_BY_ME', '', 'C', '[{"TYPE":"ACCEPT","label":"Accept Again","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"TEXT","label":"Changed your mind?","active":null,"primary":null,"secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (26, 'P', 'NOT_INTERESTED_BY_ME', '', 'E', '[{"TYPE":"INITIATE","label":"Send Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"TEXT","label":"Changed your mind?","active":null,"primary":null,"secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (27, 'P', 'MY_MESSAGE', '', '', '[{"TYPE":"MESSAGE","label":"Send Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (28, 'P', 'CC', 'S', 'I', '[{"TYPE":"REMINDER","label":"Send Reminder","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (29, 'P', 'CC', 'S', 'R', '[{"TYPE":"REMINDER","label":"Send Reminder","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (30, 'P', 'CC', 'R', 'A', '[{"TYPE":"MESSAGE","label":"Send Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (31, 'P', 'CC', 'R', 'D', '[{"TYPE":"ACCEPT","label":"Accept Again","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"TEXT","label":"Changed your mind?","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (32, 'P', 'CONTACTS_VIEWED', '', 'N', '[{"TYPE":"INITIATE","label":"Send Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (33, 'P', 'PEOPLE_WHO_VIEWED_MY_CONTACTS', '', 'N', '[{"TYPE":"INITIATE","label":"Send Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (34, 'P', 'PEOPLE_WHO_VIEWED_MY_CONTACTS', 'S', 'I', '[{"TYPE":"REMINDER","label":"Send Reminder","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (35, 'P', 'PEOPLE_WHO_VIEWED_MY_CONTACTS', 'S', 'A', '[{"TYPE":"MESSAGE","label":"Send Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (36, 'P', 'PEOPLE_WHO_VIEWED_MY_CONTACTS', 'R', 'A', '[{"TYPE":"MESSAGE","label":"Send Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (37, 'P', 'PEOPLE_WHO_VIEWED_MY_CONTACTS', 'R', 'I', '[{"TYPE":"ACCEPT","label":"Accept","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"DECLINE","label":"Decline","active":"true","primary":null,"secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (38, 'P', 'CONTACTS_VIEWED', 'S', 'I', '[{"TYPE":"REMINDER","label":"Send Reminder","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (39, 'P', 'CONTACTS_VIEWED', 'S', 'A', '[{"TYPE":"MESSAGE","label":"Send Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (40, 'P', 'CONTACTS_VIEWED', 'R', 'I', '[{"TYPE":"ACCEPT","label":"Accept","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"DECLINE","label":"Decline","active":"true","primary":null,"secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (41, 'P', 'CONTACTS_VIEWED', 'R', 'A', '[{"TYPE":"MESSAGE","label":"Send Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (42, 'P', 'NOT_INTERESTED', 'S', 'D', '[{"TYPE":"TEXT","label":"They declined interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (43, 'P', 'NOT_INTERESTED', 'R', 'C', '[{"TYPE":"TEXT","label":"They cancelled interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (44, 'P', 'NOT_INTERESTED', 'R', 'E', '[{"TYPE":"TEXT","label":"They cancelled interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (45, 'P', 'FILTERED_INTEREST', '', '', '[{"TYPE":"ACCEPT","label":"Accept","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"DECLINE","label":"Decline","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (46, 'P', 'CC', 'S', 'A', '[{"TYPE":"MESSAGE","label":"Send Message","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (47, 'P', 'CC', 'S', 'D', '[{"TYPE":"TEXT","label":"They declined interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (48, 'P', 'CC', 'S', 'C', '[{"TYPE":"TEXT","label":"Changed Your Mind","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"ACCEPT","label":"Accept Again","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (49, 'P', 'CC', 'S', 'E', '[{"TYPE":"TEXT","label":"Changed Your Mind","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"INITIATE","label":"Send Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (50, 'P', 'CC', 'R', 'I', '[{"TYPE":"ACCEPT","label":"Accept","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"DECLINE","label":"Decline","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (51, 'P', 'CC', 'R', 'C', '[{"TYPE":"TEXT","label":"They cancelled interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (52, 'P', 'CC', 'R', 'E', '[{"TYPE":"TEXT","label":"They cancelled interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (53, 'P', 'CC', '', 'N', '[{"TYPE":"INITIATE","label":"Send Interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (54, 'P', 'INTRO_CALLS_COMPLETE', '', 'C', '[{"TYPE":"COMMENT","label":"View Comment","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (55, 'P', 'INTRO_CALLS_COMPLETE', '', 'N', '[{"TYPE":"COMMENT","label":"View Comments","active":"","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"TEXT","label":"No comment yet!","active":null,"primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (56, 'P', 'INTRO_CALLS', '', 'C', '[{"TYPE":"REMOVE","label":"Remove","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (57, 'P', 'VDP_VSP', 'S', 'I', '[{"TYPE":"INITIATE","label":"Interest Sent","active":null,"primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"Chat","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"SHORTLIST","label":"Shortlist","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null}]');
INSERT IGNORE INTO `BUTTON_RESPONSE` VALUES (58, 'P', 'VDP_VSP', 'S', 'R', '[{"TYPE":"REMINDER","label":"Reminder Sent","active":null,"primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"CHAT","label":"Chat","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"SHORTLIST","label":"Shortlist","active":null,"primary":"true","secondary":null,"tracking":null,"icon":null}]');
