use incentive;

CREATE TABLE  `DEALLOCATION_TRACK` (
 `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
 `PROFILEID` INT UNSIGNED NOT NULL ,
 `PROCESS_NAME` VARCHAR( 25 ) NOT NULL ,
 `DEALLOCATION_DT` TIMESTAMP NOT NULL ,
 `ALLOTED_TO` VARCHAR( 25 ) NOT NULL ,
PRIMARY KEY (  `ID` )
);
