use newjs;

LOCK TABLES FILTERS WRITE;

DROP TRIGGER IF EXISTS UPDATE_FILTERS;

delimiter //

CREATE TRIGGER UPDATE_FILTERS 
AFTER UPDATE ON FILTERS
    FOR EACH ROW
    BEGIN
        IF NEW.PROFILEID <> '' THEN   
            REPLACE INTO newjs.FILTERS_LOG(PROFILEID,FILTERID,AGE,MSTATUS,RELIGION,CASTE,COUNTRY_RES,CITY_RES,MTONGUE,INCOME,COUNT,HARDSOFT,MOD_DT) VALUES (new.PROFILEID,new.FILTERID,new.AGE,new.MSTATUS,new.RELIGION,new.CASTE,new.COUNTRY_RES,new.CITY_RES,new.MTONGUE,new.INCOME,new.COUNT,new.HARDSOFT,NOW());
        END IF;
    END;//
delimiter ;

DROP TRIGGER IF EXISTS INSERT_FILTERS;

delimiter //

CREATE TRIGGER INSERT_FILTERS 
AFTER INSERT ON FILTERS
    FOR EACH ROW
    BEGIN
        IF NEW.PROFILEID <> '' THEN
            REPLACE INTO newjs.FILTERS_LOG(PROFILEID,FILTERID,AGE,MSTATUS,RELIGION,CASTE,COUNTRY_RES,CITY_RES,MTONGUE,INCOME,COUNT,HARDSOFT,MOD_DT) VALUES (new.PROFILEID,new.FILTERID,new.AGE,new.MSTATUS,new.RELIGION,new.CASTE,new.COUNTRY_RES,new.CITY_RES,new.MTONGUE,new.INCOME,new.COUNT,new.HARDSOFT,NOW());
        END IF;
    END;//
delimiter ;

UNLOCK TABLES;
