USE incentive;
CREATE TABLE `TRANSFER_PROFILE_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `ALLOT_DT` date DEFAULT NULL,
  `TRANSFER_SUB_METHOD` char(40) NOT NULL,
  `TRANSFER_DT` datetime DEFAULT NULL,
  `TRANSFER_BY` varchar(40) NOT NULL,
  `TRANSFER_FROM` varchar(40) NOT NULL,
  `TRANSFER_TO` varchar(40) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;