ALTER TABLE  billing.`FESTIVE_LOG_REVAMP` ADD  `SERVICES` VARCHAR( 120 ) DEFAULT NULL AFTER  `LAST_ACTIVE_SERVICES` ;
ALTER TABLE  billing.`FESTIVE_LOG_REVAMP` ADD  `OFFERED_SERVICES` VARCHAR( 120 ) DEFAULT NULL AFTER  `SERVICES` ;
UPDATE billing.`FESTIVE_LOG_REVAMP` SET `SERVICES`='P4,P6,P9,C4,C6,C9,D4,D6,D9,ESP4,ESP6,ESP9', `OFFERED_SERVICES`='P5,P8,P12,C5,C8,C12,D5,D8,D12,ESP5,ESP8,ESP12' ;
