use incentive;
CREATE TABLE `SALES_CSV_DATA_DELHI` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(10) NOT NULL,
  `PRIORITY` tinyint(2) DEFAULT '0',
  `ANALYTIC_SCORE` tinyint(3) DEFAULT '0',
  `OLD_PRIORITY` tinyint(2) DEFAULT '0',
  `DIAL_STATUS` tinyint(1) DEFAULT '0',
  `AGENT` varchar(60) DEFAULT '',
  `VD_PERCENT` tinyint(3) DEFAULT '0',
  `LAST_LOGIN_DATE` datetime DEFAULT '0000-00-00 00:00:00',
  `PHONE_NO1` varchar(12) DEFAULT '',
  `PHONE_NO2` varchar(12) DEFAULT '',
  `PHOTO` char(3) DEFAULT '',
  `DOB` datetime DEFAULT '0000-00-00 00:00:00',
  `MSTATUS` varchar(40) DEFAULT '',
  `EVER_PAID` char(3) DEFAULT '',
  `GENDER` char(6) DEFAULT '',
  `POSTEDBY` varchar(40) DEFAULT '',
  `NEW_VARIABLE1` varchar(20) DEFAULT '',
  `NEW_VARIABLE2` varchar(20) DEFAULT '',
  `NEW_VARIABLE3` varchar(20) DEFAULT '',
  `PHONE_NO3` varchar(12) NOT NULL DEFAULT '',
  `PHONE_NO4` varchar(12) DEFAULT '',
  `LEAD_ID` varchar(30) DEFAULT '',
  `CSV_ENTRY_DATE` date NOT NULL DEFAULT '0000-00-00',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROFILEID` (`PROFILEID`,`CSV_ENTRY_DATE`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1 AUTO_INCREMENT=21 ;

CREATE TABLE `SALES_CSV_DATA_TEMP` (
  `PROFILEID` int(11) NOT NULL DEFAULT '0',
  `USERNAME` varchar(40) DEFAULT NULL,
  `ENTRY_DT` date NOT NULL DEFAULT '0000-00-00',
  PRIMARY KEY (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `SALES_CSV_PROFILE_LOG` (
  `PROFILEID` int(11) unsigned NOT NULL DEFAULT '0',
  `USERNAME` varchar(40) NOT NULL DEFAULT '',
  `CSV_SENT` enum('Y','N') DEFAULT NULL,
  `CAMPAIGN_NAME` char(10) DEFAULT NULL,
  `DIAL_STATUS` tinyint(1) DEFAULT NULL,
  `FILTER_NAME` varchar(40) DEFAULT NULL,
  `FILTER_VALUE` varchar(40) DEFAULT NULL,
  `ENTRY_DT` date NOT NULL DEFAULT '0000-00-00',
  KEY `ENTRY_DT` (`ENTRY_DT`),
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
