USE billing;

DELETE FROM billing.FESTIVE_OFFER_LOOKUP WHERE SERVICEID = 'X3';
DELETE FROM billing.FESTIVE_OFFER_LOOKUP WHERE SERVICEID = 'X4';
DELETE FROM billing.FESTIVE_OFFER_LOOKUP WHERE SERVICEID = 'X6';
DELETE FROM billing.FESTIVE_OFFER_LOOKUP WHERE SERVICEID = 'X12';