USE billing;

CREATE TABLE `FESTIVE_OFFER_LOOKUP` (
  `SERVICEID` char(10) NOT NULL,
  `DISCOUNT_DURATION` int(2) NOT NULL DEFAULT '0',
  `OFFERED_SERVICEID` char(10) NOT NULL,
  `DISCOUNT_PERCENT` float DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('P3', 0, 'P3', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('P4', 0, 'P4', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('P6', 0, 'P6', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('P12', 0, 'P12', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('PL', 0, 'PL', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('C3', 0, 'C3', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('C4', 0, 'C4', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('C6', 0, 'C6', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('C12', 0, 'C12', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('CL', 0, 'CL', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('D3', 0, 'D3', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('D4', 0, 'D4', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('D6', 0, 'D6', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('D12', 0, 'D12', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('DL', 0, 'DL', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('ESP3', 0, 'ESP3', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('ESP4', 0, 'ESP4', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('ESP6', 0, 'ESP6', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('ESP12', 0, 'ESP12', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('ESPL', 0, 'ESPL', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('X3', 0, 'X3', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('X4', 0, 'X4', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('X6', 0, 'X6', 0);
INSERT INTO `FESTIVE_OFFER_LOOKUP` VALUES ('X12', 0, 'X12', 0);