USE billing;

CREATE TABLE `COUPON_OFFER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COUPON_CODE` varchar(8) DEFAULT NULL,
  `START_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `END_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `USER_LIMIT` int(6) NOT NULL DEFAULT '0',
  `USED_COUNT` int(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE `COUPON_DISCOUNT_LOOKUP` (
  `COUPON_ID` int(11) DEFAULT NULL,
  `SERVICEID` varchar(6) DEFAULT NULL,
  `DISCOUNT` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `ORDERS_DEVICE` ADD `COUPON_CODE` VARCHAR(8) DEFAULT NULL ;
