use newjs;
ALTER TABLE `SWAP` ADD `OTHER_UG_DEGREE` VARCHAR( 30 ) AFTER `PG_DEGREE` ,
ADD `OTHER_PG_DEGREE` VARCHAR( 30 ) AFTER `OTHER_UG_DEGREE` ;

use newjs;
ALTER TABLE `SEARCH_MALE` ADD `OTHER_UG_DEGREE` VARCHAR( 30 ) AFTER `PG_DEGREE` ,
ADD `OTHER_PG_DEGREE` VARCHAR( 30 ) AFTER `OTHER_UG_DEGREE` ;

use newjs;
ALTER TABLE `SEARCH_FEMALE` ADD `OTHER_UG_DEGREE` VARCHAR( 30 ) AFTER `PG_DEGREE` ,
ADD `OTHER_PG_DEGREE` VARCHAR( 30 ) AFTER `OTHER_UG_DEGREE` ;