ALTER TABLE newjs.`SEARCH_AGENT` CHANGE `SEARCH_TYPE` `SEARCH_TYPE` CHAR( 3 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci;

ALTER TABLE MIS.`SEARCHQUERY` CHANGE `SEARCH_TYPE` `SEARCH_TYPE` CHAR( 3 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ;

ALTER TABLE MIS.`SEARCHQUERY_TEST` CHANGE `SEARCH_TYPE` `SEARCH_TYPE` CHAR( 2 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ;



