USE newjs;

INSERT INTO `newjs`.`CASTE_GROUP_MAPPING` ( `ID` , `GROUP_VALUE` , `CASTE_VALUE` )
VALUES ('', '25', '251'), ('', '25', '294'), ('', '25', '307');

ALTER TABLE `RELIGION` ADD `SortSearch` TINYINT( 3 ) UNSIGNED NOT NULL AFTER `SORTBY` ;


UPDATE `RELIGION` SET `SortSearch` = '1' WHERE `VALUE` = '1' LIMIT 1 ;
UPDATE `RELIGION` SET `SortSearch` = '3' WHERE `VALUE` = '2' LIMIT 1 ;
UPDATE `RELIGION` SET `SortSearch` = '5' WHERE `VALUE` = '3' LIMIT 1 ;
UPDATE `RELIGION` SET `SortSearch` = '4' WHERE `VALUE` = '4' LIMIT 1 ;
UPDATE `RELIGION` SET `SortSearch` = '7' WHERE `VALUE` = '5' LIMIT 1 ;
UPDATE `RELIGION` SET `SortSearch` = '8' WHERE `VALUE` = '6' LIMIT 1 ;
UPDATE `RELIGION` SET `SortSearch` = '6' WHERE `VALUE` = '7' LIMIT 1 ;
UPDATE `RELIGION` SET `SortSearch` = '10' WHERE `VALUE` = '8' LIMIT 1 ;
UPDATE `RELIGION` SET `SortSearch` = '2' WHERE `VALUE` = '9' LIMIT 1 ;
UPDATE `RELIGION` SET `SortSearch` = '9' WHERE `VALUE` = '10' LIMIT 1 ;



UPDATE `MTONGUE` SET `SEARCH_SORT` = '1' WHERE `ID` = '27' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '2' WHERE `ID` = '13' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '3' WHERE `ID` = '14' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '4' WHERE `ID` = '15' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '5' WHERE `ID` = '30' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '6' WHERE `ID` = '44' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '7' WHERE `ID` = '20' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '8' WHERE `ID` = '12' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '9' WHERE `ID` = '34' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '10' WHERE `ID` = '6' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '11' WHERE `ID` = '25' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '12' WHERE `ID` = '5' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '13' WHERE `ID` = '29' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '14' WHERE `ID` = '31' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '15' WHERE `ID` = '3' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '16' WHERE `ID` = '16' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '17' WHERE `ID` = '17' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '18' WHERE `ID` = '42' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '19' WHERE `ID` = '45' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '20' WHERE `ID` = '1' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '101' WHERE `ID` = '35' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '102' WHERE `ID` = '36' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '103' WHERE `ID` = '37' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '104' WHERE `ID` = '38' LIMIT 1 ;
UPDATE `MTONGUE` SET `SEARCH_SORT` = '105' WHERE `ID` = '39' LIMIT 1 ;
