use MOBILE_API;

INSERT INTO `APP_NOTIFICATIONS` VALUES (42, 'MATCH_OF_DAY', '{USERNAME_OTHER_1} is your match of the day, Connect now!.', 1, 'ALL', 'Y', 'D', '15', 0, 'SINGLE', 'Y', 86400, 'A', 'A', 'Match of the day!', 'P');

CREATE TABLE MOBILE_API.`MATCH_OF_DAY_LOG` ( `ID` int(11) NOT NULL AUTO_INCREMENT, `PROFILEID` int(11) NOT NULL, `MATCH_PROFILEID` int(11) NOT NULL, `ENTRY_DT` date NOT NULL, PRIMARY KEY (`ID`), KEY `PROFILEID` (`PROFILEID`,`MATCH_PROFILEID`,`ENTRY_DT`)) ENGINE=InnoDB;

ALTER TABLE  MOBILE_API.`SCHEDULED_APP_NOTIFICATIONS` ADD  `PROFILE_CHECKSUM` VARCHAR( 255 ) NOT NULL ;