RENAME TABLE js_crm.ONLINE_PRIORITY_LOG TO js_crm.ONLINE_PRIORITY_LOG_20161101;
RENAME TABLE js_crm.DIALER_UPDATE_LOG TO js_crm.DIALER_UPDATE_LOG_20161101;

CREATE TABLE js_crm.`ONLINE_PRIORITY_LOG` (
  `PROFILEID` int(11) DEFAULT NULL,
  `PRIORITY` tinyint(2) NOT NULL,
  `DIAL_STATUS` tinyint(1) DEFAULT NULL,
  `TIME` datetime NOT NULL,
  `ACTION` char(2) DEFAULT NULL,
  `CAMPAIGN` varchar(20) DEFAULT NULL,
  `SOURCE_TYPE` varchar(20) DEFAULT NULL,
  `ALLOTED` char(1) DEFAULT '',	
  KEY `TIME` (`TIME`),
  KEY `ACTION` (`ACTION`),
  KEY `CAMPAIGN` (`CAMPAIGN`)
) ENGINE=MyISAM;

CREATE TABLE js_crm.`DIALER_UPDATE_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `CAMPAIGN` varchar(20) NOT NULL DEFAULT '',
  `UPDATE_STRING` varchar(100) NOT NULL DEFAULT '',
  `TIME` datetime NOT NULL,
  `ACTION` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROFILEID` (`PROFILEID`),
  KEY `TIME` (`TIME`)
) ENGINE=MyISAM;

