USE billing;

ALTER TABLE billing.EXC_CALLBACK ADD PREFERRED_START_TIME_IST DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL, ADD PREFERRED_END_TIME_IST DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL ;
ALTER TABLE billing.EXC_CALLBACK ADD INDEX ( PREFERRED_START_TIME_IST , PREFERRED_END_TIME_IST ) ;