use MOBILE_API;

CREATE TABLE `NOTIFICATION_OPENED_TRACKING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MESSAGE_ID` bigint(11) NOT NULL,
  `NOTIFICATION_KEY` varchar(20) NOT NULL,
  `CHANNEL` varchar(10) NOT NULL,
  `CLICKED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE `MESSAGE_ID`(`MESSAGE_ID`),
  KEY `NOTIFICATION_KEY`(`NOTIFICATION_KEY`),
  KEY `CLICKED_DATE`(`CLICKED_DATE`)
);