use MOBILE_API;

RENAME TABLE MOBILE_API.NOTIFICATION_LOG TO MOBILE_API.NOTIFICATION_LOG_20150723;

CREATE TABLE `NOTIFICATION_LOG` (
 `PROFILEID` int(11) DEFAULT NULL,
 `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
 `MESSAGE_ID` bigint(11) DEFAULT NULL,
 `SEND_DATE` datetime DEFAULT NULL,
 `UPDATE_DATE` datetime NOT NULL,
 `SENT` char(1) NOT NULL,
 `OS_TYPE` char(1) DEFAULT NULL,
 KEY `PROFILEID` (`PROFILEID`),
 KEY `SEND_DATE` (`SEND_DATE`),
 KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
 KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=InnoDB;

insert into MOBILE_API.NOTIFICATION_LOG (`PROFILEID`,`NOTIFICATION_KEY`,`MESSAGE_ID`,`SEND_DATE`,`SENT`,`OS_TYPE`) SELECT PROFILEID,NOTIFICATION_KEY,MESSAGE_ID,SEND_DATE,SENT,OS_TYPE FROM MOBILE_API.NOTIFICATION_LOG_20150723 WHERE SEND_DATE>='2015-07-17 00:00:00';

