use incentive;

CREATE TABLE `PRE_ALLOCATION_TEMP_POOL` (
 `PROFILEID` int(11) NOT NULL DEFAULT '0',
 `CITY_RES` varchar(6) NOT NULL DEFAULT '',
 `ALLOTMENT` char(1) NOT NULL DEFAULT '',
 `ANALYTIC_SCORE` smallint(6) NOT NULL,
 UNIQUE KEY `PROFILEID` (`PROFILEID`),
 KEY `CITY_RES` (`CITY_RES`)
)ENGINE=MyISAM; 

