use billing;
CREATE TABLE `EXCLUSIVE_MEMBERS_LOG` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(12) NOT NULL,
 `ASSIGNED_TO` varchar(20) DEFAULT NULL,
 `BILLING_DT` datetime DEFAULT '0000-00-00 00:00:00',
 `BILL_ID` int(11) DEFAULT NULL,
 `ASSIGNED_DT` date DEFAULT '0000-00-00',
 `ASSIGNED` enum('Y','N') NOT NULL DEFAULT 'N',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `PROFILEID_BILLID` (`PROFILEID`,`BILL_ID`),
 KEY `ASSIGNED` (`ASSIGNED`)
) ENGINE=MyISAM;

ALTER TABLE EXCLUSIVE_MEMBERS ADD INDEX BILLING_DT(BILLING_DT);
