use incentive;

CREATE TABLE incentive.PROCESS_CSV_DATA_TEMP (
  PROFILEID int(11) NOT NULL DEFAULT '0',
  ENTRY_DT date NOT NULL DEFAULT '0000-00-00',
  `PROCESS` varchar(40) DEFAULT NULL,
  PRIMARY KEY (PROFILEID),
  KEY PROFILEID (PROFILEID,`PROCESS`)
);

CREATE TABLE incentive.PROCESS_REGULAR_LOG (
  ID int(11) NOT NULL AUTO_INCREMENT,
  `DATE` date NOT NULL DEFAULT '0000-00-00',
  FILTER varchar(100) NOT NULL DEFAULT '',
  FILTERED_PROFILES int(11) DEFAULT '0',
  COUNT int(11) NOT NULL DEFAULT '0',
  LATEST_REG_DT date DEFAULT NULL,
  LATEST_REG_FILTERED_PROFILES int(11) DEFAULT '0',
  LATEST_REG_COUNT int(11) NOT NULL DEFAULT '0',
  `PROCESS` varchar(40) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY DATE_PROCESS_FILTER (`DATE`,`PROCESS`,FILTER)
);


CREATE TABLE incentive.PROCESS_CSV_PROFILE_LOG (
  PROFILEID int(11) unsigned NOT NULL DEFAULT '0',
  USERNAME varchar(40) NOT NULL DEFAULT '',
  CSV_SENT enum('Y','N') DEFAULT NULL,
  CAMPAIGN_NAME char(10) DEFAULT NULL,
  DIAL_STATUS tinyint(1) DEFAULT NULL,
  FILTER_NAME varchar(40) DEFAULT NULL,
  FILTER_VALUE varchar(40) DEFAULT NULL,
  ENTRY_DT date NOT NULL DEFAULT '0000-00-00',
  `PROCESS` varchar(40) DEFAULT NULL,
  KEY ENTRY_DT (ENTRY_DT),
  KEY ENTRYDT_PROFILEID (ENTRY_DT,PROFILEID)
);