USE billing;

ALTER TABLE billing.EXC_CALLBACK ADD PREFERRED_START_TIME_IST DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL, ADD PREFERRED_END_TIME_IST DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL ;
ALTER TABLE billing.EXC_CALLBACK ADD INDEX ( PREFERRED_START_TIME_IST , PREFERRED_END_TIME_IST ) ;

use incentive;
UPDATE incentive.LAST_HANDLED_DATE SET SOURCE_NAME='RCB_DATA_IST_TIME' WHERE SOURCE_ID='16';
UPDATE incentive.LAST_HANDLED_DATE SET HANDLED_ID=(select MAX(ID) from incentive.SALES_CSV_DATA_RCB) WHERE SOURCE_ID='17';

