use incentive;

ALTER TABLE  `BACKEND_LINK_MAILER` RENAME  `BACKEND_LINK_MAILER_14May2016`;

CREATE TABLE `BACKEND_LINK_MAILER` (
 `PROFILEID` int(11) NOT NULL DEFAULT '0',
 `EMAIL` varchar(50) NOT NULL,
 `USERNAME` varchar(20) NOT NULL,
 `COUNTRY_RES` tinyint(4) NOT NULL,
 `SENT_DATE` date NOT NULL DEFAULT '0000-00-00',
 KEY `SENT_DATE` (`SENT_DATE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

