use MOBILE_API;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `CHANNEL` =  'M,D' WHERE  `ID` =  '5' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `CHANNEL` =  'M,D' WHERE  `ID` =  '6' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `CHANNEL` =  'M,D' WHERE  `ID` =  '7' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `CHANNEL` =  'M,D' WHERE  `ID` =  '9' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `CHANNEL` =  'M,D' WHERE  `ID` =  '10' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `CHANNEL` =  'M,D' WHERE  `ID` =  '11' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `CHANNEL` =  'M,D' WHERE  `ID` =  '12' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `CHANNEL` =  'M,D' WHERE  `ID` =  '13' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `CHANNEL` =  'M,D' WHERE  `ID` =  '8' LIMIT 1 ;