use MOBILE_API;

UPDATE  MOBILE_API.`APP_NOTIFICATIONS` SET  `MESSAGE` =  '{MESSAGE_RECEIVED}', `TTL` =  '86400', `TITLE` =  '{USERNAME_OTHER_1} has sent a message', `PHOTO_URL` =  'P' WHERE  `NOTIFICATION_KEY` =  'MESSAGE_RECEIVED';