use scoring_new;

CREATE TABLE `TEMP_SCORING_LOG`(
 `PROFILEID` int(11) NOT NULL,
 `ACTUAL_SCORE` decimal(10,4) DEFAULT NULL,
 `PERCENTILE` tinyint(4) DEFAULT '0',
 `TYPE` char(1) DEFAULT NULL,
 `ENTRY_DT` date NOT NULL,
 KEY `PROFILEID` (`ENTRY_DT`)
)ENGINE=InnoDb;
