use newjs;

CREATE TABLE `CHAT_TIMEOUT_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `COUNT` int(11) DEFAULT 1,
  `ENTRY_DT` date NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROFILEID`(`PROFILEID`,`ENTRY_DT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;