use billing;
update billing.DIRECT_CALL_COUNT SET COUNT=50 WHERE SERVICEID='P2';
update billing.DIRECT_CALL_COUNT SET COUNT=50 WHERE SERVICEID='C2';
update billing.DIRECT_CALL_COUNT SET COUNT=50 WHERE SERVICEID='ESP2';
update billing.DIRECT_CALL_COUNT SET COUNT=50 WHERE SERVICEID='X2';
