use test;

CREATE TABLE `DAILY_DIALER_REPORT_LOG` (
 `ID` int(11) NOT NULL,
 `CAMPAIGN_NAME` varchar(30) NOT NULL,
 `ACTIVE_DATA_POINTS` tinyint(5) NOT NULL,
 `TOTAL_DIAL` tinyint(5) NOT NULL,
 `UNIQUE_DIAL` tinyint(5) NOT NULL,
 `HANDLED_CALL` tinyint(5) NOT NULL,
 `MAX_CONNECTED_SCORE` tinyint(5) NOT NULL,
 `MIN_CONNECTED_SCORE` tinyint(5) NOT NULL,
 `EXECUTIVE_TOOK_CALL` tinyint(5) NOT NULL,
 `CALL_TIME` varchar(10) NOT NULL,
 PRIMARY KEY ID(`ID`),
 `ENTRY_DT` date NOT NULL, 
 KEY `CAMPAIGN_NAME` (`CAMPAIGN_NAME`),
 KEY `ENTRY_DT` (`ENTRY_DT`)
) ENGINE=MyISAM;
