CREATE TABLE incentive.`SCORE_UPDATE_LOG` (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) DEFAULT NULL,
  `SCORE` smallint(6) DEFAULT NULL,
  `ENTRY_DT` datetime DEFAULT '0000-00-00 00:00:00',
  KEY `ID` (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=51 DEFAULT CHARSET=latin1 AUTO_INCREMENT=51 ;
