use MOBILE_API;

RENAME table `NOTIFICATION_LOG` TO NOTIFICATION_LOG_Jun2015;
CREATE TABLE `NOTIFICATION_LOG` (
 `PROFILEID` int(11) DEFAULT NULL,
 `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
 `MESSAGE_ID` bigint(11) DEFAULT NULL,
 `SEND_DATE` datetime DEFAULT NULL,
 `SENT` char(1) NOT NULL,
 `OS_TYPE` char(1) DEFAULT NULL,
 KEY `PROFILEID` (`PROFILEID`),
 KEY `SEND_DATE` (`SEND_DATE`),
 KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
 KEY `MESSAGE_ID` (`MESSAGE_ID`)
)ENGINE=InnoDB;

INSERT INTO MOBILE_API.`APP_NOTIFICATIONS` VALUES (23, 'MEM_EXPIRE_A5', '{MESSAGE}', 6, 'ALL', 'Y', 'D', '', 15, 'SINGLE', 'Y', 86400, 'A', 'A', 'Renew your Membership', 'D');
INSERT INTO MOBILE_API.`APP_NOTIFICATIONS` VALUES (24, 'MEM_EXPIRE_A10', '{MESSAGE}', 6, 'ALL', 'Y', 'D', '', 15, 'SINGLE', 'Y', 86400, 'A', 'A', 'Renew your Membership', 'D');
INSERT INTO MOBILE_API.`APP_NOTIFICATIONS` VALUES (25, 'MEM_EXPIRE_A15', '{MESSAGE}', 6, 'ALL', 'Y', 'D', '', 15, 'SINGLE', 'Y', 86400, 'A', 'A', 'Renew your Membership', 'D');
INSERT INTO MOBILE_API.`APP_NOTIFICATIONS` VALUES (26, 'MEM_EXPIRE_B1', '{MESSAGE}', 6, 'ALL', 'Y', 'D', '', 15, 'SINGLE', 'Y', 86400, 'A', 'A', 'Renew your Membership', 'D');
INSERT INTO MOBILE_API.`APP_NOTIFICATIONS` VALUES (27, 'MEM_EXPIRE_B5', '{MESSAGE}', 6, 'ALL', 'Y', 'D', '', 15, 'SINGLE', 'Y', 86400, 'A', 'A', 'Renew your Membership', 'D');

INSERT INTO MOBILE_API.`APP_NOTIFICATIONS` VALUES (28, 'BUY_MEMB', '{MESSAGE_RECEIVED}', 6, 'ALL', 'Y', 'I', '', '', 'SINGLE', 'Y', 86400, 'A', 'A', 'Upgrade your Membership', 'D');

