use billing;

ALTER TABLE billing.`PAYMENT_DETAIL` MODIFY `MODE` enum('CASH','CHEQUE','ONLINE','TT','DD','OTHER','CREDIT','CCOFFLINE','BANK_TRSFR_ONLINE','IVR','GHAR_PAY_CASH','GHAR_PAY_CHEQUE','CASH_WITHOUT_RECEIPT','CHEQUE_WITHOUT_RECEIPT') DEFAULT 'CASH';
