use billing;

/*update billing.SERVICES SET SHOW_ONLINE='Y',ACTIVE='Y' WHERE SERVICEID IN('P2','C2','X2');*/
/*ALTER TABLE billing.VARIABLE_DISCOUNT_OFFER_DURATION ADD COLUMN `2` tinyint(3) DEFAULT '0' AFTER SERVICE;*/

	ALTER TABLE billing.DISCOUNT_LOOKUP ADD COLUMN `2_DISCOUNT` tinyint(3) DEFAULT '0' AFTER SERVICE;
	ALTER TABLE billing.DISCOUNT_LOOKUP_BACKUP ADD COLUMN `2_DISCOUNT` tinyint(3) DEFAULT '0' AFTER SERVICE;
	ALTER TABLE test.DISCOUNT_LOOKUP_UPLOAD ADD COLUMN `2_DISCOUNT` tinyint(3) DEFAULT '0' AFTER SERVICE;
	ALTER TABLE billing.VARIABLE_DISCOUNT_DURATION_POOL_TECH ADD COLUMN `2_DISCOUNT` tinyint(3) DEFAULT '0' AFTER SERVICE;

	ALTER TABLE billing.VARIABLE_DISCOUNT_TEMP ADD COLUMN `2` tinyint(3) DEFAULT '0' AFTER SERVICE;
	ALTER TABLE test.VD_UPLOAD_TEMP ADD COLUMN `2` tinyint(3) DEFAULT '0' AFTER SERVICE;

/*ALTER TABLE billing.VARIABLE_DISCOUNT_OFFER_DURATION_LOG ADD COLUMN `2` tinyint(3) DEFAULT '0' AFTER SERVICE;*/

RENAME TABLE billing.VARIABLE_DISCOUNT_OFFER_DURATION TO billing.VARIABLE_DISCOUNT_OFFER_DURATION_20160530_BACKUP;
RENAME TABLE billing.VARIABLE_DISCOUNT_OFFER_DURATION_20160530 TO billing.VARIABLE_DISCOUNT_OFFER_DURATION;

RENAME TABLE VARIABLE_DISCOUNT_OFFER_DURATION_LOG TO VARIABLE_DISCOUNT_OFFER_DURATION_LOG_20160530;
CREATE TABLE `VARIABLE_DISCOUNT_OFFER_DURATION_LOG` (
  `PROFILEID` int(11) unsigned NOT NULL,
  `SERVICE` char(6) NOT NULL DEFAULT '',
  `3` tinyint(3) DEFAULT '0',
  `6` tinyint(3) DEFAULT '0',
  `12` tinyint(3) DEFAULT '0',
  `L` tinyint(3) DEFAULT '0',
  `EDATE` date DEFAULT NULL,
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM;
ALTER TABLE billing.VARIABLE_DISCOUNT_OFFER_DURATION_LOG ADD COLUMN `2` tinyint(3) DEFAULT '0' AFTER SERVICE;

/*
use test;
CREATE TABLE `VD_UPLOAD_TEMP` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `SDATE` date NOT NULL,
  `EDATE` date NOT NULL,
  `SERVICE` varchar(30) NOT NULL,
  `3` tinyint(3) DEFAULT '0',
  `6` tinyint(3) DEFAULT '0',
  `12` tinyint(3) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM;

use billing;
CREATE TABLE `VARIABLE_DISCOUNT_TEMP` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `SDATE` date NOT NULL,
  `EDATE` date NOT NULL,
  `SERVICE` varchar(30) NOT NULL,
  `3` tinyint(3) DEFAULT '0',
  `6` tinyint(3) DEFAULT '0',
  `12` tinyint(3) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM;

CREATE TABLE `DISCOUNT_LOOKUP_BACKUP` (
 `SCORE_LOWER_LIMIT` tinyint(3) DEFAULT NULL,
 `SCORE_UPPER_LIMIT` tinyint(3) DEFAULT NULL,
 `GENDER` char(1) DEFAULT NULL,
 `MTONGUE` tinyint(3) DEFAULT NULL,
 `SERVICE` char(6) NOT NULL DEFAULT '',
 `3_DISCOUNT` tinyint(3) DEFAULT NULL,
 `6_DISCOUNT` tinyint(3) DEFAULT NULL,
 `12_DISCOUNT` tinyint(3) DEFAULT NULL,
 `L_DISCOUNT` tinyint(3) NOT NULL
) ENGINE=MyISAM

CREATE TABLE `DISCOUNT_LOOKUP_UPLOAD` (
 `SCORE_LOWER_LIMIT` tinyint(3) DEFAULT NULL,
 `SCORE_UPPER_LIMIT` tinyint(3) DEFAULT NULL,
 `GENDER` char(1) DEFAULT NULL,
 `MTONGUE` tinyint(3) DEFAULT NULL,
 `SERVICE` char(6) NOT NULL DEFAULT '',
 `3_DISCOUNT` tinyint(3) DEFAULT NULL,
 `6_DISCOUNT` tinyint(3) DEFAULT NULL,
 `12_DISCOUNT` tinyint(3) DEFAULT NULL,
 `L_DISCOUNT` tinyint(3) NOT NULL
) ENGINE=MyISAM

*/


