use incentive;

update incentive.ALLOCATION_BUCKET SET VALUE=7,ENTRY_DT='2016-11-01' WHERE PROCESS_ID='S' AND BUCKET_TYPE='AP';
update incentive.ALLOCATION_BUCKET SET VALUE=7,ENTRY_DT='2016-11-01' WHERE PROCESS_ID='S' AND BUCKET_TYPE='EP'; 
