use billing;

CREATE TABLE billing.`DISCOUNT_HISTORY_MAX` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `LAST_LOGIN_DATE` date NOT NULL,
 `MAX_DISCOUNT` tinyint(3) NOT NULL,
 `MAX_DISCOUNT_DATE` date NOT NULL,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `PROFILE_UNIQUE` (`PROFILEID`),
 KEY `PROFILEID` (`PROFILEID`),
 KEY `LAST_LOGIN_DATE` (`LAST_LOGIN_DATE`),
 KEY `MAX_DISCOUNT_DATE`(`MAX_DISCOUNT_DATE`)
) ENGINE=InnoDB;