use MOBILE_API;
CREATE TABLE `NOTIFICATION_MESSAGE_LOG` (
 `NOTIFICATION_KEY` varchar(20) DEFAULT '',
 `MESSAGE_ID` bigint(11) DEFAULT '0',
 `MESSAGE` varchar(200) DEFAULT '',
 `TITLE` varchar(100) DEFAULT '',
 `ENTRY_DT` datetime DEFAULT NULL,
 KEY `MESSAGE_ID` (`MESSAGE_ID`),
 KEY `ENTRY_DT` (`ENTRY_DT`)
) ENGINE=InnoDB;
