use Assisted_Product;

CREATE TABLE `AP_PROFILE_INFO_DEBUG` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `TYPE` varchar(30) NOT NULL DEFAULT '',
 `ENTRY_DT` datetime DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`ID`),
 KEY `PROFILEID` (`PROFILEID`),
 KEY `ENTRY_DT` (`ENTRY_DT`)
) ENGINE=MyISAM;

ALTER TABLE AP_PROFILE_INFO ADD ENTRY_DT datetime DEFAULT '0000-00-00 00:00:00';

