INSERT INTO `APP_NOTIFICATIONS` ( `ID` , `NOTIFICATION_KEY` , `MESSAGE` , `LANDING_SCREEN` , `OS_TYPE` , `STATUS` , `FREQUENCY` , `TIME_CRITERIA` , `PRIORITY` , `COUNT` , `COLLAPSE_STATUS` , `TTL` , `GENDER` , `SUBSCRIPTION` , `TITLE` , `PHOTO_URL` )
VALUES (
'', 'MEM_EXPIRE', '{MESSAGE}', '6', 'ALL', 'Y', 'D', NULL , '15', 'SINGLE', 'Y', '86400', 'A', 'A', 'Renew your Membership', 'D'
);

UPDATE `APP_NOTIFICATIONS` SET `STATUS` = 'N' WHERE `NOTIFICATION_KEY` = 'MEM_EXPIRE_A5' LIMIT 1 ;

UPDATE `APP_NOTIFICATIONS` SET `STATUS` = 'N' WHERE `NOTIFICATION_KEY` = 'MEM_EXPIRE_A10' LIMIT 1 ;

UPDATE `APP_NOTIFICATIONS` SET `STATUS` = 'N' WHERE `NOTIFICATION_KEY` = 'MEM_EXPIRE_A15' LIMIT 1 ;

UPDATE `APP_NOTIFICATIONS` SET `STATUS` = 'N' WHERE `NOTIFICATION_KEY` = 'MEM_EXPIRE_B1' LIMIT 1 ;

UPDATE `APP_NOTIFICATIONS` SET `STATUS` = 'N' WHERE `NOTIFICATION_KEY` = 'MEM_EXPIRE_B5' LIMIT 1 ;
 

