use MOBILE_API;

ALTER TABLE MOBILE_API.DAILY_NOTIFICATION_COUNT_LOG ADD `PUSHED_TO_IOS` int(3) DEFAULT '0' AFTER `ACCEPTED_BY_GCM`;
ALTER TABLE MOBILE_API.DAILY_NOTIFICATION_COUNT_LOG ADD `ACCEPTED_BY_IOS` int(3) DEFAULT '0' AFTER `PUSHED_TO_IOS`;
ALTER TABLE MOBILE_API.DAILY_NOTIFICATION_COUNT_LOG CHANGE `PUSH_DELIVERED_TO_USER` `PUSH_ACKNOWLEDGED` int(3) DEFAULT '0',CHANGE `LOCAL_DELIVERED_TO_USER` `LOCAL_ACKNOWLEDGED` int(3) DEFAULT '0';
