USE incentive;

DROP TABLE incentive.CRM_AGENT_CHECKIN_CHECKOUT_LOG;

CREATE TABLE incentive.CRM_AGENT_CHECKIN_CHECKOUT_LOG (
  ID int(11) NOT NULL AUTO_INCREMENT,
  AGENT_NAME varchar(30) DEFAULT NULL,
  USERNAME varchar(20) DEFAULT NULL,
  LOG_TYPE enum('CHECKIN','CHECKOUT') DEFAULT NULL,
  AGENT_LOCATION enum('OFFICE','RESIDENCE') DEFAULT NULL,
  LATITUDE varchar(20) DEFAULT NULL,
  LONGITUDE varchar(20) DEFAULT NULL,
  DATE_TIME datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (ID),
  KEY AGENT_NAME (AGENT_NAME,LOG_TYPE,DATE_TIME)
) ENGINE=InnoDB;