UPDATE  `SERVICES` SET  `PRICE_RS` =  '2628.19', `PRICE_RS_TAX` =  '2995', `PRICE_DOL` =  '89', `SHOW_ONLINE` =  'Y' WHERE  `SERVICEID` =  'C2';

UPDATE  `SERVICES` SET  `PRICE_RS` =  '2188.59', `PRICE_RS_TAX` =  '2495', `PRICE_DOL` =  '80', `SHOW_ONLINE` =  'Y' WHERE  `SERVICEID` =  'P2' ;
