use MOBILE_API;

ALTER TABLE MOBILE_API.`SCHEDULED_APP_NOTIFICATIONS` ADD PHOTO_URL VARCHAR( 100 );
UPDATE  MOBILE_API.`APP_NOTIFICATIONS` SET  `PHOTO_URL` =  'P' WHERE  `ID` IN  ('1', '6', '7', '19', '20', '5', '8', '9', '30', '31', '32');