create database js_crm;

use js_crm;

CREATE TABLE js_crm.`CAMPAIGN_ELIGIBLITY_UPDATE_STATUS` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `CAMPAIGN` char(40) NOT NULL DEFAULT '',
 `ELIGIBLE_TYPE` char(1) DEFAULT '',
 `STEP_COMPLETED` tinyint(2) DEFAULT 0,
 `ENTRY_DT` date NOT NULL DEFAULT '0000-00-00',
 PRIMARY KEY `ID`(`ID`),
 UNIQUE `ENTRY_DT`(`ENTRY_DT`,`CAMPAIGN`,`ELIGIBLE_TYPE`)
) ENGINE=InnoDB;

CREATE TABLE `DIALER_UPDATE_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `CAMPAIGN` varchar(20) NOT NULL DEFAULT '',
  `UPDATE_STRING` varchar(100) NOT NULL DEFAULT '',
  `TIME` datetime NOT NULL,
  `ACTION` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROFILEID` (`PROFILEID`),
  KEY `TIME` (`TIME`)
) ENGINE=MyISAM;

CREATE TABLE `ONLINE_PRIORITY_LOG` (
  `PROFILEID` int(11) DEFAULT NULL,
  `PRIORITY` tinyint(2) NOT NULL,
  `DIAL_STATUS` tinyint(1) DEFAULT NULL,
  `TIME` datetime NOT NULL,
  `ACTION` char(2) DEFAULT NULL,
  `CAMPAIGN` varchar(20) DEFAULT NULL,
  `TYPE` varchar(20) DEFAULT NULL,
  KEY `TIME` (`TIME`),
  KEY `ACTION` (`ACTION`),
  KEY `CAMPAIGN` (`CAMPAIGN`)
) ENGINE=MyISAM;

CREATE TABLE `DIALER_CONNECTIVITY_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `LOG_DATE` datetime NOT NULL,
  `CAMPAIGN` varchar(20) NOT NULL DEFAULT '',
  `OFFLINE_PRIORITY` tinyint(4) NOT NULL,
  `ONLINE_PRIORITY` tinyint(4) NOT NULL,
  `PRIORTIZATION_TIME` datetime NOT NULL,
  `TERMINATION_STATUS` varchar(20) NOT NULL DEFAULT '',
  `DIAL_TIME` datetime NOT NULL,
  `SCORE` smallint(6) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROFILEID` (`PROFILEID`),
  KEY `LOG_DATE` (`LOG_DATE`)
) ENGINE=MyISAM;

CREATE TABLE `last_recentusers` (
  `userID` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`userID`)
) ENGINE=MEMORY;

RENAME TABLE test.MESSAGE_LOG_SHARD1 TO js_crm.MESSAGE_LOG_SHARD1;
RENAME TABLE test.MESSAGE_LOG_SHARD2 TO js_crm.MESSAGE_LOG_SHARD2;
RENAME TABLE test.MESSAGE_LOG_SHARD3 TO js_crm.MESSAGE_LOG_SHARD3;
RENAME TABLE test.EOI_VIEWED_LOG_SHARD1 TO js_crm.EOI_VIEWED_LOG_SHARD1;
RENAME TABLE test.EOI_VIEWED_LOG_SHARD2 TO js_crm.EOI_VIEWED_LOG_SHARD2;
RENAME TABLE test.EOI_VIEWED_LOG_SHARD3 TO js_crm.EOI_VIEWED_LOG_SHARD3;
RENAME TABLE test.ANALYTIC_SCORE_POOL TO js_crm.ANALYTIC_SCORE_POOL;






