CREATE TABLE `VARIABLE_DISCOUNT_DURATION` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `SDATE` date NOT NULL,
 `EDATE` date NOT NULL,
 `ENTRY_DT` date NOT NULL,
 `STEPS_COMPLETED` varchar(5) DEFAULT '',
 `SCHEDULE_DATE` datetime NOT NULL,
 `STATUS` char(1) DEFAULT '',
 PRIMARY KEY (`ID`),
 KEY `ENTRY_DT` (`ENTRY_DT`)
)ENGINE=MyISAM;
