INSERT INTO MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` VALUES (NULL, 'MEM_EXPIRE', '{MESSAGE}', 'Renew your Membership', 'D', 'RM', 'M,D', 'Y', 'A', 'D', '', 5, 86400, 'SINGLE', 0);

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `STATUS` =  'N' WHERE  `ID` =  '9' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `STATUS` =  'N' WHERE  `ID` =  '10' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `STATUS` =  'N' WHERE  `ID` =  '11' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `STATUS` =  'N' WHERE  `ID` =  '12' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `STATUS` =  'N' WHERE  `ID` =  '13' LIMIT 1 ;