USE billing;

CREATE TABLE `APPLE_ORDERS` (
  `PROFILEID` int(11) NOT NULL,
  `ID` int(11) NOT NULL,
  `ORDERID` varchar(25) NOT NULL,
  `APPLE_ID` varchar(50) NOT NULL,
  `ENTRY_DT` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `RECEIPT_DATA` blob NOT NULL,
  PRIMARY KEY (`APPLE_ID`),
  KEY `PROFILEID` (`PROFILEID`)
);