USE billing;

UPDATE billing.SERVICES SET PRICE_RS_TAX = '5500' WHERE SERVICEID = 'P6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '6900' WHERE SERVICEID = 'C6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '12900' WHERE SERVICEID = 'CL';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '7900' WHERE SERVICEID = 'NCP6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '35900' WHERE SERVICEID = 'X6';

