use MOBILE_API;

INSERT INTO MOBILE_API.`APP_NOTIFICATIONS` VALUES (39, 'MEM_DISCOUNT', '{MESSAGE}', 6, 'AND', 'Y', 'D', 0, 0, 'SINGLE', 'Y', 86400, 'A', 'A', 'Special Offer For You', 'D');

ALTER TABLE MOBILE_API.SCHEDULED_APP_NOTIFICATIONS CHANGE TITLE TITLE varchar(60) DEFAULT NULL;

