use NOTIFICATION_NEW;

CREATE TABLE `DAILY_MATCHALERT_NOTIFICATION` (
 `ID` int(20) unsigned NOT NULL AUTO_INCREMENT,
 `RECEIVER` int(11) unsigned NOT NULL,
 `OT_PROFILEID` int(11) unsigned NOT NULL,
 `OT_PIC_URL` varchar(100) NOT NULL DEFAULT '',
 `OT_PIC_IOS_URL` varchar(100) NOT NULL DEFAULT '',
 `COUNT` tinyint(3) unsigned NOT NULL DEFAULT '0',
 `REC_LAST_LOGIN_DATE` datetime NOT NULL,
 `IST_ENTRY_DATE` datetime NOT NULL,
 `STATUS` char(1) NOT NULL DEFAULT 'N',
 PRIMARY KEY (`ID`),
 KEY `RECEIVER` (`RECEIVER`),
 KEY `IST_ENTRY_DATE` (`IST_ENTRY_DATE`)
) ENGINE=InnoDB;




