use billing;

CREATE TABLE billing.`EXCLUSIVE_FOLLOWUPS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGENT_USERNAME` varchar(20) NOT NULL,
  `CLIENT_ID` int(11) NOT NULL,
  `MEMBER_ID` int(11) NOT NULL,
  `ENTRY_DT` datetime DEFAULT NULL,
  `FOLLOWUP_1` varchar(30) DEFAULT NULL,
  `FOLLOWUP_2` varchar(30) DEFAULT NULL,
  `FOLLOWUP_3` varchar(30) DEFAULT NULL,
  `FOLLOWUP1_DT` date DEFAULT NULL,
  `FOLLOWUP2_DT` date DEFAULT NULL,
  `FOLLOWUP3_DT` date DEFAULT NULL,
 `STATUS` enum('F0','Y','N','F1','F2','F3','F4') DEFAULT 'F0',
 PRIMARY KEY (`ID`),
 KEY AGENT_USERNAME(`AGENT_USERNAME`),
 KEY CLIENT_ID(`CLIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
