use MOBILE_API;

CREATE TABLE `LOCAL_NOTIFICATION_LOG` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `REGISTRATION_ID` varchar(255) DEFAULT NULL,
 `PROFILEID` int(11) DEFAULT NULL,
 `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
 `MESSAGE_ID` bigint(11) DEFAULT NULL,
 `ENTRY_DATE` datetime DEFAULT NULL,
 `ALARM_TIME` datetime DEFAULT NULL,
 `OS_TYPE` char(1) DEFAULT NULL,
 PRIMARY KEY (`ID`),
 KEY `PROFILEID` (`PROFILEID`),
 KEY `ENTRY_DATE` (`ENTRY_DATE`),
 KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
 KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=InnoDB;

