use billing;

ALTER TABLE  `EXCLUSIVE_CLIENT_MEMBER_MAPPING` CHANGE  `SCREENED_STATUS`  `SCREENED_STATUS` ENUM(  'Y',  'N',  'P',  'E',  'S',  'D' ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT  'N';
