use billing;

CREATE TABLE billing.`LIGHTNING_DEAL_DISCOUNT` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `DISCOUNT` tinyint(4) NOT NULL,
 `SDATE` datetime NOT NULL,
 `EDATE` datetime NOT NULL,
 `ENTRY_DT` date NOT NULL,
 `VIEWED` enum('Y','N') NOT NULL DEFAULT 'N',
 `ACTIVATED` enum('Y','N') NOT NULL DEFAULT 'N',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`ENTRY_DT`),
 KEY `ENTRY_DT` (`ENTRY_DT`),
 KEY `SDATE` (`SDATE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE billing.`DISCOUNT_HISTORY_BACKUP` ( `ID` int(11) NOT NULL AUTO_INCREMENT, `PROFILEID` int(11) NOT NULL, `DATE` date NOT NULL, `P` tinyint(3) NOT NULL, `C` tinyint(3) NOT NULL, `NCP` tinyint(3) NOT NULL, `X` tinyint(3) NOT NULL, PRIMARY KEY (`ID`), UNIQUE KEY `PROFILE_DATE` (`PROFILEID`,`DATE`), KEY `PROFILEID` (`PROFILEID`), KEY `DATE` (`DATE`)) ENGINE=MYISAM;


/*archive data of DISCOUNT_HISTORY to DISCOUNT_HISTORY_BACKUP 1 month earlier*/