use billing;

UPDATE billing.SERVICES SET PRICE_DOL=79.99 WHERE SERVICEID='P3';
UPDATE billing.SERVICES SET PRICE_DOL=89.99 WHERE SERVICEID='P4';
UPDATE billing.SERVICES SET PRICE_DOL=99.99 WHERE SERVICEID='P5';
UPDATE billing.SERVICES SET PRICE_DOL=109.99 WHERE SERVICEID='P6';
UPDATE billing.SERVICES SET PRICE_DOL=119.99 WHERE SERVICEID='P8';
UPDATE billing.SERVICES SET PRICE_DOL=139.99 WHERE SERVICEID='P9';
UPDATE billing.SERVICES SET PRICE_DOL=169.99 WHERE SERVICEID='P12';
UPDATE billing.SERVICES SET PRICE_DOL=189.99 WHERE SERVICEID='PL';

UPDATE billing.SERVICES SET PRICE_DOL=94.99 WHERE SERVICEID='C3';
UPDATE billing.SERVICES SET PRICE_DOL=109.99 WHERE SERVICEID='C4';
UPDATE billing.SERVICES SET PRICE_DOL=119.99 WHERE SERVICEID='C5';
UPDATE billing.SERVICES SET PRICE_DOL=139.99 WHERE SERVICEID='C6';
UPDATE billing.SERVICES SET PRICE_DOL=149.99 WHERE SERVICEID='C8';
UPDATE billing.SERVICES SET PRICE_DOL=179.99 WHERE SERVICEID='C9';
UPDATE billing.SERVICES SET PRICE_DOL=209.99 WHERE SERVICEID='C12';
UPDATE billing.SERVICES SET PRICE_DOL=229.99 WHERE SERVICEID='CL';

UPDATE billing.SERVICES SET PRICE_DOL=119.99 WHERE SERVICEID='NCP3';
UPDATE billing.SERVICES SET PRICE_DOL=129.99 WHERE SERVICEID='NCP4';
UPDATE billing.SERVICES SET PRICE_DOL=139.99 WHERE SERVICEID='NCP5';
UPDATE billing.SERVICES SET PRICE_DOL=169.99 WHERE SERVICEID='NCP6';
UPDATE billing.SERVICES SET PRICE_DOL=179.99 WHERE SERVICEID='NCP8';
UPDATE billing.SERVICES SET PRICE_DOL=189.99 WHERE SERVICEID='NCP9';
UPDATE billing.SERVICES SET PRICE_DOL=249.99 WHERE SERVICEID='NCP12';

UPDATE billing.SERVICES SET PRICE_DOL=399.99 WHERE SERVICEID='X3';
UPDATE billing.SERVICES SET PRICE_DOL=449.99 WHERE SERVICEID='X4';
UPDATE billing.SERVICES SET PRICE_DOL=449.99 WHERE SERVICEID='X5';
UPDATE billing.SERVICES SET PRICE_DOL=599.99 WHERE SERVICEID='X6';
UPDATE billing.SERVICES SET PRICE_DOL=599.99 WHERE SERVICEID='X8';
UPDATE billing.SERVICES SET PRICE_DOL=599.99 WHERE SERVICEID='X9';
UPDATE billing.SERVICES SET PRICE_DOL=899.99 WHERE SERVICEID='X12';

UPDATE billing.SERVICES SET PRICE_DOL=26.99 WHERE SERVICEID='A6';
UPDATE billing.SERVICES SET PRICE_DOL=44.99 WHERE SERVICEID='A12';

UPDATE billing.SERVICES SET PRICE_DOL=94.99 WHERE SERVICEID='I60';
UPDATE billing.SERVICES SET PRICE_DOL=179.99 WHERE SERVICEID='I120';

UPDATE billing.SERVICES SET PRICE_DOL=12.99 WHERE SERVICEID IN('M1','M2','M3','M4','M5','M6','M7','M8','M9','M10','M11','M12','ML');