use billing;

/*ALTER TABLE billing.`PAYMENT_DETAIL` 
	MODIFY `SOURCE` enum('CASH','CHEQUE','ONLINE','TT','DD','OTHER','CREDIT','CCOFFLINE','BANK_TRSFR_ONLINE','EB_CASH','EB_CHEQUE','BANK_TRSFR_CHQ','BANK_TRSFR_CASH','IVR','BLUEDART_COD','GHAR_PAY_CASH','GHAR_PAY_CHEQUE','PayTM_ON_DELIVERY') DEFAULT 'CASH',
	MODIFY `MODE`  enum('CASH','CHEQUE','ONLINE','TT','DD','OTHER','CREDIT','CCOFFLINE','BANK_TRSFR_ONLINE','IVR','GHAR_PAY_CASH','GHAR_PAY_CHEQUE','CASH_WITHOUT_RECEIPT','CHEQUE_WITHOUT_RECEIPT','PayTM_ON_DELIVERY') DEFAULT 'CASH';
*/

ALTER TABLE billing.`PAYMENT_DETAIL` 
	MODIFY `SOURCE` varchar(100) DEFAULT 'CASH',
	MODIFY `MODE`  varchar(100) DEFAULT 'CASH';

CREATE INDEX SOURCE ON billing.`PAYMENT_DETAIL` (SOURCE);

CREATE INDEX MODE ON billing.`PAYMENT_DETAIL` (MODE);