ALTER TABLE incentive.`SALES_TARGET` ADD `FORTNIGHT` TINYINT DEFAULT '0' NOT NULL ;

ALTER TABLE incentive.`SALES_TARGET` DROP PRIMARY KEY ,ADD PRIMARY KEY ( `USERNAME` , `TARGET_MONTH` , `FORTNIGHT` );
