use billing;

CREATE TABLE billing.`COMMUNITY_WELCOME_DISCOUNT_LOG` ( `PROFILEID` int(11) DEFAULT NULL, `DISCOUNT` tinyint(4) DEFAULT NULL, `ENTRY_DT` date DEFAULT NULL, UNIQUE KEY `PROFILEID_DATE` (`PROFILEID`,`ENTRY_DT`), KEY `PROFILEID` (`PROFILEID`), KEY `ENTRY_DT` (`ENTRY_DT`)) ENGINE=InnoDB;

CREATE TABLE billing.`COMMUNITY_WELCOME_DISCOUNT` ( `ID` int(11) NOT NULL AUTO_INCREMENT, `COMMUNITY` int(3) DEFAULT NULL, `CATEGORY_ID` int(3) NOT NULL, `DISCOUNT` tinyint(4) DEFAULT NULL, `ENTRY_BY` varchar(50) DEFAULT NULL, `ENTRY_DT` datetime DEFAULT NULL, `ACTIVE` enum('Y','N') NOT NULL DEFAULT 'Y', PRIMARY KEY (`ID`), KEY `COMMUNITY` (`COMMUNITY`), KEY `ENTRY_DT` (`ENTRY_DT`)) ENGINE=InnoDB;