use billing;
ALTER TABLE billing.DISCOUNT_LOOKUP ADD COLUMN 1_DISCOUNT tinyint(3) AFTER SERVICE;

ALTER TABLE billing.VARIABLE_DISCOUNT_DURATION_POOL_TECH ADD COLUMN 1_DISCOUNT tinyint(3) AFTER SERVICE;

ALTER TABLE billing.VARIABLE_DISCOUNT_OFFER_DURATION ADD COLUMN `1` tinyint(3) AFTER SERVICE;

ALTER TABLE billing.VARIABLE_DISCOUNT_OFFER_DURATION_LOG ADD COLUMN `1` tinyint(3) AFTER SERVICE;

ALTER TABLE test.VD_UPLOAD_TEMP ADD COLUMN `1` tinyint(3) AFTER SERVICE;

ALTER TABLE billing.VARIABLE_DISCOUNT_TEMP ADD COLUMN `1` tinyint(3) AFTER SERVICE;



ALTER TABLE test.DISCOUNT_LOOKUP_UPLOAD ADD COLUMN 1_DISCOUNT tinyint(3) AFTER SERVICE;
ALTER TABLE billing.DISCOUNT_LOOKUP_BACKUP ADD COLUMN 1_DISCOUNT tinyint(3) AFTER SERVICE;
