update billing.PAYMENT_DETAIL_NEW set AMOUNT='-2800', APPLE_COMMISSION='-1200' where RECEIPTID =1681965 and STATUS = 'CANCEL';
update billing.PAYMENT_DETAIL_NEW set APPLE_COMMISSION= APPLE_COMMISSION * -1 where RECEIPTID =1108319 and STATUS = 'CANCEL';

update billing.PAYMENT_DETAIL_NEW set FRANCHISEE_COMMISSION= FRANCHISEE_COMMISSION* -1 where RECEIPTID =1108319 and STATUS = 'CANCEL';
update billing.PAYMENT_DETAIL_NEW set FRANCHISEE_COMMISSION= FRANCHISEE_COMMISSION* -1 where RECEIPTID =1657227 and STATUS = 'CANCEL';
update billing.PAYMENT_DETAIL_NEW set FRANCHISEE_COMMISSION= FRANCHISEE_COMMISSION* -1 where RECEIPTID =1660195 and STATUS = 'BOUNCE';
update billing.PAYMENT_DETAIL_NEW set FRANCHISEE_COMMISSION= FRANCHISEE_COMMISSION* -1 where RECEIPTID =1679703 and STATUS = 'CANCEL';
update billing.PAYMENT_DETAIL_NEW set FRANCHISEE_COMMISSION= FRANCHISEE_COMMISSION* -1 where RECEIPTID =1823121 and STATUS = 'CANCEL';
update billing.PAYMENT_DETAIL_NEW set FRANCHISEE_COMMISSION= FRANCHISEE_COMMISSION* -1 where RECEIPTID =1829627 and STATUS = 'CANCEL';
update billing.PAYMENT_DETAIL_NEW set FRANCHISEE_COMMISSION= FRANCHISEE_COMMISSION* -1 where RECEIPTID =1821053 and STATUS = 'BOUNCE';
update billing.PAYMENT_DETAIL_NEW set FRANCHISEE_COMMISSION= FRANCHISEE_COMMISSION* -1 where RECEIPTID =1846285 and STATUS = 'CANCEL';

