use jsadmin;

CREATE TABLE jsadmin.`HELP_USER_QUERIES` ( `ID` int(11) NOT NULL AUTO_INCREMENT, `EMAIL` varchar(100) NOT NULL, `CATEGORY` varchar(50) DEFAULT NULL, `USERNAME` varchar(40) NOT NULL, `QUERY` text NOT NULL, `ENTRY_DT` date NOT NULL, `CHANNEL` char(1) NOT NULL, PRIMARY KEY (`ID`), KEY `EMAIL` (`EMAIL`,`ENTRY_DT`)) ENGINE=InnoDB;