use incentive;

CREATE TABLE `QA_ONLINE_CSV_DATA` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `SCORE` int(2) DEFAULT '0',
 `EMAIL` varchar(100) DEFAULT '',
 `MOBILE` varchar(20) DEFAULT '0',
 `LANDLINE` varchar(20) DEFAULT '0',
 `CSV_ENTRY_DATE` date NOT NULL DEFAULT '0000-00-00',
 `TYPE` enum('N','R') DEFAULT 'N',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`CSV_ENTRY_DATE`)
) ENGINE=InnoDB;
