use MOBILE_API;
update MOBILE_API.APP_NOTIFICATIONS WHERE PHOTO_URL='P' WHERE NOTIFICATION_KEY='PROFILE_VISITOR';
update MOBILE_API.APP_NOTIFICATIONS WHERE PHOTO_URL='P' WHERE NOTIFICATION_KEY='PENDING_EOI';
update MOBILE_API.APP_NOTIFICATIONS WHERE PHOTO_URL='P' WHERE NOTIFICATION_KEY='FILTERED_EOI';
update MOBILE_API.APP_NOTIFICATIONS WHERE PHOTO_URL='P' WHERE NOTIFICATION_KEY='MATCHALERT';
