
USE table incentive;
CREATE TABLE `LOGGING_CLIENT_INFO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(40) NOT NULL,
  `REMARKS` text,
  `CRM_ID` varchar(40) NOT NULL,
  `ENTRY_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;
