use MOBILE_API;

RENAME TABLE LOCAL_NOTIFICATION_LOG TO LOCAL_NOTIFICATION_LOG_20160425;
CREATE TABLE `LOCAL_NOTIFICATION_LOG` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) DEFAULT NULL,
 `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
 `MESSAGE_ID` bigint(11) DEFAULT NULL,
 `ENTRY_DATE` datetime DEFAULT NULL,
 `UPDATE_DATE` datetime NOT NULL,
 `SENT` char(1) NOT NULL,
 `ALARM_TIME` datetime DEFAULT NULL,
 `OS_TYPE` char(1) DEFAULT NULL,
 PRIMARY KEY (`ID`),
 KEY `PROFILEID` (`PROFILEID`),
 KEY `ENTRY_DATE` (`ENTRY_DATE`),
 KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
 KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=InnoDB;

RENAME TABLE LOCAL_LOG TO LOCAL_LOG_20160425;
CREATE TABLE `LOCAL_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGISTRATION_ID` varchar(255) DEFAULT NULL,
  `APP_V` float DEFAULT NULL,
  `OS_V` float DEFAULT NULL,
  `ENTRY_DATE` datetime DEFAULT '0000-00-00 00:00:00',
  `PROFILEID` int(11) DEFAULT NULL,
  `DEVICE_BRAND` varchar(30) DEFAULT NULL,
  `DEVICE_MODEL` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ENTRY_DATE` (`ENTRY_DATE`),
  KEY `PROFIELID` (`PROFILEID`),
  KEY `REGISTRATION_ID` (`REGISTRATION_ID`)
) ENGINE=InnoDB;



