CREATE TABLE incentive.EXCLUSIVE_EMAIL_LOG(
PROFILEID int(11) DEFAULT NULL,
ENTRY_DT datetime DEFAULT NULL,
EXECUTIVE varchar(50) DEFAULT NULL);

CREATE INDEX PROFILEID ON incentive.EXCLUSIVE_EMAIL_LOG (PROFILEID,ENTRY_DT);