use NOTIFICATION_NEW;

CREATE TABLE `NOTIFICATION_LOG` (
  `PROFILEID` int(11) DEFAULT NULL,
  `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
  `MESSAGE_ID` bigint(11) DEFAULT NULL,
  `SEND_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  `SENT` char(1) NOT NULL,
  `OS_TYPE` char(1) DEFAULT NULL,
  KEY `PROFILEID` (`PROFILEID`),
  KEY `SEND_DATE` (`SEND_DATE`),
  KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
  KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=InnoDB;

CREATE TABLE `LOCAL_NOTIFICATION_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) DEFAULT NULL,
  `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
  `MESSAGE_ID` bigint(11) DEFAULT NULL,
  `ENTRY_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  `SENT` char(1) NOT NULL,
  `ALARM_TIME` datetime DEFAULT NULL,
  `OS_TYPE` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROFILEID` (`PROFILEID`),
  KEY `ENTRY_DATE` (`ENTRY_DATE`),
  KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
  KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=InnoDB;


CREATE TABLE `GCM_RESPONSE_LOG` (
  `PROFILEID` int(12) NOT NULL,
  `REGISTRATION_ID` varchar(255) NOT NULL,
  `HTTP_STATUS_CODE` int(4) NOT NULL,
  `STATUS_MESSAGE` varchar(255) DEFAULT NULL,
  `DATE` datetime NOT NULL,
  `NOTIFICATION_KEY` varchar(20) NOT NULL,
  PRIMARY KEY (`PROFILEID`,`REGISTRATION_ID`,`DATE`)
) ENGINE=InnoDB;


CREATE TABLE `IOS_RESPONSE_LOG` (
  `PROFILEID` int(12) NOT NULL,
  `REGISTRATION_ID` varchar(255) NOT NULL,
  `MESSAGE_ID` bigint(11) NOT NULL,
  `STATUS_CODE` int(4) NOT NULL,
  `STATUS_MESSAGE` varchar(255) DEFAULT NULL,
  `SEND_DATE` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `NOTIFICATION_KEY` varchar(20) NOT NULL,
  KEY `MESSAGE_ID` (`MESSAGE_ID`),
  KEY `SEND_DATE` (`SEND_DATE`),
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=InnoDB;


CREATE TABLE `NOTIFICATION_LOG_ATN` (
  `PROFILEID` int(11) DEFAULT NULL,
  `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
  `MESSAGE_ID` bigint(11) DEFAULT NULL,
  `SEND_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  `SENT` char(1) NOT NULL,
  `OS_TYPE` char(1) DEFAULT NULL,
  KEY `PROFILEID` (`PROFILEID`),
  KEY `SEND_DATE` (`SEND_DATE`),
  KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
  KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=InnoDb;


CREATE TABLE `NOTIFICATION_LOG_ETN` (
  `PROFILEID` int(11) DEFAULT NULL,
  `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
  `MESSAGE_ID` bigint(11) DEFAULT NULL,
  `SEND_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  `SENT` char(1) NOT NULL,
  `OS_TYPE` char(1) DEFAULT NULL,
  KEY `PROFILEID` (`PROFILEID`),
  KEY `SEND_DATE` (`SEND_DATE`),
  KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
  KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=InnoDb;


CREATE TABLE `NOTIFICATION_MESSAGE_LOG` (
  `NOTIFICATION_KEY` varchar(20) DEFAULT '',
  `MESSAGE_ID` bigint(11) DEFAULT '0',
  `MESSAGE` varchar(200) DEFAULT '',
  `TITLE` varchar(100) DEFAULT '',
  `ENTRY_DT` datetime DEFAULT NULL,
  KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
  KEY `MESSAGE_ID` (`MESSAGE_ID`),
  KEY `ENTRY_DT` (`ENTRY_DT`)
) ENGINE=InnoDB;

CREATE TABLE `SCHEDULED_APP_NOTIFICATIONS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(12) NOT NULL,
  `NOTIFICATION_KEY` varchar(20) NOT NULL,
  `MESSAGE` varchar(200) NOT NULL,
  `LANDING_SCREEN` int(5) DEFAULT NULL,
  `OS_TYPE` varchar(3) NOT NULL,
  `PRIORITY` float NOT NULL,
  `COLLAPSE_STATUS` varchar(1) NOT NULL,
  `TTL` int(10) NOT NULL,
  `SCHEDULED_DATE` date NOT NULL,
  `SENT` varchar(1) NOT NULL,
  `TITLE` varchar(60) DEFAULT NULL,
  `COUNT` int(11) NOT NULL,
  `MSG_ID` bigint(20) NOT NULL,
  `PHOTO_URL` varchar(100) DEFAULT NULL,
  `PROFILE_CHECKSUM` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROFILEID` (`PROFILEID`,`NOTIFICATION_KEY`,`SCHEDULED_DATE`),
  KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
  KEY `MSG_ID` (`MSG_ID`,`SENT`),
  KEY `MSG_ID_2` (`MSG_ID`,`SENT`)
) ENGINE=InnoDB;


use test;

TEMP_NOTIFICATION_LOG | CREATE TABLE `TEMP_NOTIFICATION_LOG` (
  `PROFILEID` int(11) DEFAULT NULL,
  `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TEMP_LOGIN_TRACKING` (
  `PROFILEID` int(11) NOT NULL,
  `DATE` datetime NOT NULL,
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
























