use MOBILE_API;
CREATE TABLE `CSV_NOTIFICATION_TEMP` (
 `PROFILEID` int(11) DEFAULT NULL,
 `MESSAGE` varchar(200) DEFAULT NULL,
 `URL` varchar(100) DEFAULT NULL,
 KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAMv

INSERT INTO MOBILE_API.`APP_NOTIFICATIONS` VALUES (29, 'CSV_UPLOAD', '{MESSAGE_RECEIVED}', 6, 'ALL', 'Y', 'I', '', '', 'SINGLE', 'Y', 86400, 'A', 'A', 'Exclusive Offer For You', 'D');
