use MOBILE_API;

ALTER TABLE BROWSER_NOTIFICATION CHANGE COLUMN REQUEST_DT RECEIVED_DT datetime NOT NULL default '0000-00-00 00:00:00',CHANGE COLUMN SENT_TO_CHANNEL RECEIVED_STATUS char(1) NOT NULL DEFAULT 'N',CHANGE SENT_TO_GCM  SENT_TO_FCM char(1) NOT NULL DEFAULT 'N'; 

