use billing;

CREATE TABLE billing.`VARIABLE_DISCOUNT_NOTIFICATION_LOG` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `STATUS` varchar(1) DEFAULT 'N',
 `ENTRY_DT` date NOT NULL DEFAULT '0000-00-00',
 `START_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `END_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `FLAT_COUNT` int(11) DEFAULT '0',
 `UPTO_COUNT` int(11) NOT NULL DEFAULT '0',
 `FREQUENCY` int(2) unsigned DEFAULT '0',
 `NO_OF_TIMES` int(2) unsigned DEFAULT '1',
 PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;