use newjs;

CREATE TABLE `FRESHCHAT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `RESTOREID` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROFILE` (`PROFILEID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;
