use incentive;

ALTER TABLE SALES_CSV_DATA_RENEWAL ADD COLUMN CAMPAIGN_TYPE char(30) NOT NULL AFTER LEAD_ID;
ALTER TABLE RENEWAL_IN_DIALER ADD COLUMN CAMPAIGN_TYPE char(30) NOT NULL AFTER PRIORITY, ADD INDEX CAMPAIGN_TYPE(CAMPAIGN_TYPE);
