use newjs;

CREATE TABLE `CHAT_TIMEOUT_LOG` (
  `PROFILEID` int(11) NOT NULL,
  `COUNT` int(11) DEFAULT 1,
  `ENTRY_DT` date NOT NULL,
  UNIQUE KEY `PROFILEID`(`PROFILEID`,`ENTRY_DT`)
) ENGINE=InnoDB;