use billing;

CREATE TABLE `billing.SUSPENDED_UNLIMITED_SERVICE_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `OLD_BILLID` int(11) NOT NULL,
  `OLD_SERVICEID` varchar(10) NOT NULL,
  `NEW_BILLID` int(11) NOT NULL,
  `NEW_SERVICEID` varchar(10) NOT NULL,
  `SUSPENDED_DATE` datetime NOT NULL,
  `CONTACTS_ALLOTED` smallint(3) NOT NULL,
  `CONTACTS_VIEWED` smallint(5) NOT NULL,
  `CONTACTS_CREATED` datetime NOT NULL,
  `IS_SUSPENDED` enum('Y','N') NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SUSPENSION` (`OLD_BILLID`,`NEW_BILLID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;