use MOBILE_API;

RENAME table `NOTIFICATION_LOG_ARCHIVE` TO NOTIFICATION_LOG_ARCHIVE_July2015;
CREATE TABLE `NOTIFICATION_LOG_ARCHIVE` (
 `PROFILEID` int(11) DEFAULT NULL,
 `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
 `MESSAGE_ID` bigint(11) DEFAULT NULL,
 `SEND_DATE` datetime DEFAULT NULL,
 `SENT` char(1) NOT NULL,
 `OS_TYPE` char(1) DEFAULT NULL,
 KEY `PROFILEID` (`PROFILEID`),
 KEY `SEND_DATE` (`SEND_DATE`),
 KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
 KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=MyISAM;

