use MOBILE_API;

ALTER TABLE MOBILE_API.REGISTRATION_ID ADD DEVICE_BRAND varchar(30) DEFAULT NULL,ADD DEVICE_MODEL varchar(30) DEFAULT NULL,ADD INDEX TIME(`TIME`);

RENAME TABLE `LOCAL_LOG` TO `LOCAL_LOG_20151016`;

CREATE TABLE `LOCAL_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGISTRATION_ID` varchar(255) DEFAULT NULL,
  `APP_V` int(10) DEFAULT NULL,
  `OS_V` float DEFAULT NULL,
  `ENTRY_DATE` datetime DEFAULT '0000-00-00 00:00:00',
  `PROFILEID` int(11) DEFAULT NULL,
  `DEVICE_BRAND` varchar(30) DEFAULT NULL,
  `DEVICE_MODEL` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ENTRY_DATE` (`ENTRY_DATE`),
  KEY `PROFIELID` (`PROFILEID`),
  KEY `REGISTRATION_ID` (`REGISTRATION_ID`)
) ENGINE=InnoDB;

 
