use billing;

UPDATE billing.SERVICES SET DURATION='2' WHERE SERVICEID='P2';
UPDATE billing.SERVICES SET DURATION='3' WHERE SERVICEID='P3';
UPDATE billing.SERVICES SET DURATION='4' WHERE SERVICEID='P4';
UPDATE billing.SERVICES SET DURATION='5' WHERE SERVICEID='P5';
UPDATE billing.SERVICES SET DURATION='6' WHERE SERVICEID='P6';
UPDATE billing.SERVICES SET DURATION='7' WHERE SERVICEID='P7';
UPDATE billing.SERVICES SET DURATION='8' WHERE SERVICEID='P8';

UPDATE billing.SERVICES SET DURATION='1' WHERE SERVICEID='C1';
UPDATE billing.SERVICES SET DURATION='2' WHERE SERVICEID='C2';
UPDATE billing.SERVICES SET DURATION='3' WHERE SERVICEID='C3';
UPDATE billing.SERVICES SET DURATION='4' WHERE SERVICEID='C4';
UPDATE billing.SERVICES SET DURATION='5' WHERE SERVICEID='C5';
UPDATE billing.SERVICES SET DURATION='6' WHERE SERVICEID='C6';
UPDATE billing.SERVICES SET DURATION='7' WHERE SERVICEID='C7';
UPDATE billing.SERVICES SET DURATION='8' WHERE SERVICEID='C8';

UPDATE billing.SERVICES SET DURATION='1188' WHERE SERVICEID='ESPL';













