use billing;
CREATE TABLE `SUBSCRIPTION_EXPIRY_MAILER_LOG_10DAY` (
 `PROFILEID` int(11) NOT NULL,
 `SENT` char(1) DEFAULT 'N',
 `ENTRY_DT` date NOT NULL,
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`ENTRY_DT`)
) ENGINE=InnoDB;
