use billing;


CREATE TABLE `billing.EXCLUSIVE_SERVICING_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGENT_USERNAME` varchar(20) NOT NULL,
  `CLIENT_ID` int(11) NOT NULL,
  `ASSIGNED_DT` date NOT NULL,
  `ENTRY_DT` datetime DEFAULT NULL,
  `SERVICE_DAY` enum('NA','SUN','MON','TUE','WED','THU','FRI','SAT') DEFAULT 'NA',
  `SERVICE_SET_DT` datetime DEFAULT '0000-00-00 00:00:00',
  `BIODATA_LOCATION` varchar(100) DEFAULT NULL,
  `BIODATA_UPLOAD_DT` datetime DEFAULT '0000-00-00 00:00:00',
  `SCREENED_DT` date DEFAULT '0000-00-00',
  `SCREENED_STATUS` enum('Y','N') DEFAULT 'N',
  `EMAIL_STAGE` varchar(1) DEFAULT NULL,
  `BILLID` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `COMBINATION` (`AGENT_USERNAME`,`CLIENT_ID`,`ASSIGNED_DT`),
  KEY `AGENT_USERNAME` (`AGENT_USERNAME`),
  KEY `CLIENT_ID` (`CLIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;

ALTER TABLE  `billing.EXCLUSIVE_SERVICING` ADD  `BILLID` INT( 11 ) DEFAULT  '0';
