use newjs;

CREATE TABLE `CHAT_CONTACTS_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `ACC_BY_ME` int(11) NOT NULL,
  `ACC_ME` int(11) NOT NULL,
  `AWAITING_RESPONSE` int(11) NOT NULL,
  `BOOKMARK` int(11) NOT NULL,
  `ENTRY_DT` datetime NOT NULL,
  `TYPE` varchar(10) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

ALTER TABLE `CHAT_CONTACTS_LOG` ADD UNIQUE (
`PROFILEID`
);