use incentive;

CREATE TABLE `SALES_CSV_DATA_PAID_CAMPAIGN` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(10) NOT NULL,
 `DIAL_STATUS` tinyint(1) DEFAULT '0',
 `USERNAME` varchar(100) DEFAULT '',
 `PHONE_NO1` varchar(12) DEFAULT '',
 `PHONE_NO2` varchar(12) DEFAULT '',
 `GENDER` char(6) DEFAULT '',
 `MEMBERSHIP` varchar(200) DEFAULT '',
 `ADDON` varchar(250) DEFAULT '',
 `PAYMENT_DT` date NOT NULL DEFAULT '0000-00-00',
 `LEAD_ID` varchar(30) DEFAULT '',
 `CSV_ENTRY_DATE` date NOT NULL DEFAULT '0000-00-00',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`CSV_ENTRY_DATE`)
) ENGINE=InnoDB; 
