use MOBILE_API;

CREATE TABLE `DAILY_NOTIFICATION_COUNT_LOG` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `NOTIFICATION_KEY` varchar(30) DEFAULT '',
 `TOTAL_COUNT` int(3) DEFAULT '0',
 `PUSHED_TO_GCM` int(3) DEFAULT '0',
 `ACCEPTED_BY_GCM` int(3) DEFAULT '0',
 `PUSH_DELIVERED_TO_USER` int(3) DEFAULT '0',
 `LOCAL_API_HIT_BY_DEVICE` int(3) DEFAULT '0',
 `LOCAL_SENT_TO_DEVICE` int(3) DEFAULT '0',
 `LOCAL_DELIVERED_TO_USER` int(3) DEFAULT '0',
 `ACTIVE_LOGIN_7DAY` int(3) DEFAULT '0',
 `ACTIVE_LOGIN_1DAY` int(3) DEFAULT '0',
 `ENTRY_DT` date DEFAULT NULL,
 PRIMARY KEY (`ID`),
 KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
 KEY `ENTRY_DT` (`ENTRY_DT`)
) ENGINE=InnoDB; 

CREATE TABLE test.`TEMP_NOTIFICATION_LOG` (
  `PROFILEID` int(11) DEFAULT NULL,
  `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=InnoD;

CREATE TABLE test.`TEMP_LOGIN_TRACKING` (
  `PROFILEID` int(11) NOT NULL,
  `DATE` datetime NOT NULL,
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=InnoD;


RENAME TABLE MOBILE_API.GCM_RESPONSE_LOG TO MOBILE_API.GCM_RESPONSE_LOG_20151221;
CREATE TABLE `GCM_RESPONSE_LOG` (
  `PROFILEID` int(12) NOT NULL,
  `REGISTRATION_ID` varchar(255) NOT NULL,
  `HTTP_STATUS_CODE` int(4) NOT NULL,
  `STATUS_MESSAGE` varchar(255) DEFAULT NULL,
  `DATE` datetime NOT NULL,
  `NOTIFICATION_KEY` varchar(20) NOT NULL,
  PRIMARY KEY (`PROFILEID`,`REGISTRATION_ID`,`DATE`)
) ENGINE=InnoD;

RENAME TABLE MOBILE_API.NOTIFICATION_LOG TO MOBILE_API.NOTIFICATION_LOG_20151221;
CREATE TABLE `NOTIFICATION_LOG` (
  `PROFILEID` int(11) DEFAULT NULL,
  `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
  `MESSAGE_ID` bigint(11) DEFAULT NULL,
  `SEND_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  `SENT` char(1) NOT NULL,
  `OS_TYPE` char(1) DEFAULT NULL,
  KEY `PROFILEID` (`PROFILEID`),
  KEY `SEND_DATE` (`SEND_DATE`),
  KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
  KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=InnoDB;

RENAME TABLE MOBILE_API.LOCAL_NOTIFICATION_LOG TO MOBILE_API.LOCAL_NOTIFICATION_LOG_20151221;
CREATE TABLE `LOCAL_NOTIFICATION_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGISTRATION_ID` varchar(255) DEFAULT NULL,
  `PROFILEID` int(11) DEFAULT NULL,
  `NOTIFICATION_KEY` varchar(20) DEFAULT NULL,
  `MESSAGE_ID` bigint(11) DEFAULT NULL,
  `ENTRY_DATE` datetime DEFAULT NULL,
  `ALARM_TIME` datetime DEFAULT NULL,
  `OS_TYPE` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROFILEID` (`PROFILEID`),
  KEY `ENTRY_DATE` (`ENTRY_DATE`),
  KEY `NOTIFICATION_KEY` (`NOTIFICATION_KEY`),
  KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=InnoDB;

INSERT INTO MIS.MIS_MAINPAGE(`NAME`, `MAIN_URL`, `JUMP_URL`, `PRIVILEGE`, `ACTIVE`) VALUES('Notification Mis','/operations.php/crmMis/notificationMis?cid=$cid','','P+MG+TRNG','Y'); 




 
