use jsadmin;

CREATE TABLE jsadmin.`HELP_QUESTIONS` ( `ID` int(4) NOT NULL AUTO_INCREMENT, `QUESTION` text NOT NULL, `ANSWER` text NOT NULL, `CATEGORY` varchar(50) NOT NULL, `ACTIVE` enum('Y','N') NOT NULL, PRIMARY KEY (`ID`), KEY `CATEGORY` (`CATEGORY`)) ENGINE=InnoDB;