CREATE TABLE `FIELD_SALES_LOG` (
 `PROFILEID` int(11) NOT NULL DEFAULT '0',
 `ALLOT_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 KEY `PROFILEID` (`PROFILEID`),
 KEY `ALLOT_TIME` (`ALLOT_TIME`)
) ENGINE=MyISAM
