use incentive;

CREATE TABLE `NEGATIVE_SUBMISSION_LIST` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `TYPE` char(25) NOT NULL DEFAULT '',
 `TYPE_VALUE` varchar(70) NOT NULL DEFAULT '',
 `COMMENTS` text,
 `ENTRY_DT` datetime DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`ID`),
 KEY `TYPE_VALUE` (`TYPE_VALUE`),
 KEY ENTRY_DT (`ENTRY_DT`)
) ENGINE=MyISAM;

CREATE TABLE `NEGATIVE_LIST` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL DEFAULT '0',
 `EMAIL` varchar(70) NOT NULL DEFAULT '',
 `PHONE_NUM` varchar(20) NOT NULL DEFAULT '',
 `PHONE_TYPE` char(1) NOT NULL DEFAULT '',
 `SUBMISSION_ID` int(11) NOT NULL DEFAULT '0',
 PRIMARY KEY (`ID`),
 UNIQUE PROFILEID (`PROFILEID`,`EMAIL`,`PHONE_NUM`)
) ENGINE=InnoDB;
