USE NOTIFICATION;

CREATE TABLE NOTIFICATION.APP_UNINSTALL (
  PROFILEID int(11) unsigned NOT NULL,
  REGISTRATION_ID varchar(255) ,
  ENTRY_DT datetime ,
  MAILER_SENT char(1) 
) ENGINE=InnoDB ;
CREATE INDEX ENTRY_DT ON APP_UNINSTALL (ENTRY_DT, PROFILEID); 

