use MOBILE_API;
CREATE TABLE MOBILE_API.`BROWSER_NOTIFICATION_REGISTRATION` (
 `REG_ID` varchar(255) NOT NULL,
 `PROFILEID` int(11) NOT NULL,
 `CHANNEL` enum('D','M') NOT NULL,
 `ENTRY_DT` datetime NOT NULL,
 `ACTIVATED` enum('Y','N') NOT NULL,
 `USER_AGENT` varchar(255) NOT NULL,
 `FAILURE` int(2) NOT NULL,
 PRIMARY KEY (`REG_ID`),
 KEY `PROFILEID` (`PROFILEID`,`ENTRY_DT`)
) ENGINE=InnoDB;

CREATE TABLE MOBILE_API.`BROWSER_NOTIFICATION` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `REG_ID` varchar(255) NOT NULL,
 `NOTIFICATION_KEY` varchar(20) NOT NULL,
 `NOTIFICATION_TYPE` varchar(10) NOT NULL,
 `MESSAGE` varchar(200) NOT NULL,
 `TITLE` varchar(50) NOT NULL,
 `ICON` varchar(100) NOT NULL,
 `TAG` varchar(5) NOT NULL,
 `LANDING_URL` varchar(100) NOT NULL,
 `ENTRY_DT` datetime NOT NULL,
 `REQUEST_DT` datetime NOT NULL,
 `CHANNEL` enum('D','M') NOT NULL,
 `PRIORITY` int(2) NOT NULL,
 `SENT_TO_GCM` enum('Y','N') NOT NULL,
 `STATUS` enum('S','F') NOT NULL,
 `RESPONSE` varchar(50) NOT NULL,
 `SENT_TO_CHROME` enum('Y','N') NOT NULL,
 PRIMARY KEY (`ID`),
 KEY `REG_ID` (`REG_ID`)
) ENGINE=InnoDB;

CREATE TABLE MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` (
 `ID` int(11) NOT NULL,
 `NOTIFICATION_KEY` varchar(20) NOT NULL,
 `MESSAGE` varchar(200) NOT NULL,
 `TITLE` varchar(50) NOT NULL,
 `ICON` varchar(100) NOT NULL,
 `TAG` varchar(5) NOT NULL,
 `LANDING_URL` varchar(100) NOT NULL,
 `CHANNEL` enum('D','M') NOT NULL,
 `STATUS` enum('D','M') NOT NULL,
 `SUBSCRIPTION` varchar(10) NOT NULL
) ENGINE=InnoDB;