use billing;

CREATE TABLE `RENEWAL_DISCOUNT_LOOKUP` (
 `SCORE_LOWER_LIMIT` tinyint(3) DEFAULT NULL,
 `SCORE_UPPER_LIMIT` tinyint(3) DEFAULT NULL,
 `DISCOUNT` tinyint(3) DEFAULT NULL,
 KEY `SCORE_LOWER_LIMIT` (`SCORE_LOWER_LIMIT`)
) ENGINE=MyISAM;

INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (0, 10, 60);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (11, 20, 55);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (21, 30, 50);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (31, 40, 45);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (41, 50, 40);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (51, 60, 35);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (61, 70, 30);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (71, 80, 25);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (81, 90, 20);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (91, 100, 15);

