use MOBILE_API;

CREATE TABLE MOBILE_API.`NOTIFICATION_OPENED_TRACKING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) DEFAULT NULL,
  `MESSAGE_ID` bigint(11) NOT NULL,
  `NOTIFICATION_KEY` varchar(20) NOT NULL,
  `CHANNEL` varchar(10) NOT NULL,
  `CLICKED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NOTIFICATION_KEY`(`NOTIFICATION_KEY`),
  KEY `CLICKED_DATE`(`CLICKED_DATE`),
  UNIQUE (`PROFILEID`,`MESSAGE_ID`)
);

ALTER TABLE MOBILE_API.`DAILY_NOTIFICATION_COUNT_LOG` ADD COLUMN OPENED_COUNT1 int(10) DEFAULT 0,ADD COLUMN OPENED_COUNT2 int(10) DEFAULT 0;