use MOBILE_API;


ALTER TABLE MOBILE_API.BROWSER_NOTIFICATION CHANGE COLUMN REQUEST_DT RECEIVED_DT datetime NOT NULL default '0000-00-00 00:00:00',CHANGE SENT_TO_GCM  SENT_TO_FCM char(1) NOT NULL DEFAULT 'N'; 


ALTER TABLE MOBILE_API.BROWSER_NOTIFICATION_BACKUP CHANGE COLUMN REQUEST_DT RECEIVED_DT datetime NOT NULL default '0000-00-00 00:00:00',CHANGE SENT_TO_GCM  SENT_TO_FCM char(1) NOT NULL DEFAULT 'N';

ALTER TABLE MOBILE_API.BROWSER_NOTIFICATION_REGISTRATION DROP COLUMN `FAILURE`;
ALTER TABLE MOBILE_API.BROWSER_NOTIFICATION_REGISTRATION DROP INDEX REG_ID ADD UNIQUE REG_ID (REG_ID,CHANNEL);
