use MOBILE_API;


ALTER TABLE MOBILE_API.BROWSER_NOTIFICATION CHANGE COLUMN REQUEST_DT RECEIVED_DATE datetime NOT NULL default '0000-00-00 00:00:00',CHANGE SENT_TO_GCM  SENT_TO_FCM char(1) NOT NULL DEFAULT 'N'; 

ALTER TABLE MOBILE_API.BROWSER_NOTIFICATION_BACKUP CHANGE COLUMN REQUEST_DT RECEIVED_DATE datetime NOT NULL default '0000-00-00 00:00:00',CHANGE SENT_TO_GCM  SENT_TO_FCM char(1) NOT NULL DEFAULT 'N';

ALTER TABLE MOBILE_API.BROWSER_NOTIFICATION_REGISTRATION DROP COLUMN `FAILURE`;
ALTER TABLE MOBILE_API.BROWSER_NOTIFICATION_REGISTRATION ADD UNIQUE REG_ID(REG_ID,CHANNEL);

update MOBILE_API.BROWSER_NOTIFICATION_LAYER SET MOBILE_LAST_CLICK='2017-10-01' WHERE MOBILE_LAYER='Y' AND MOBILE_LAST_CLICK>='2017-10-01';
update MOBILE_API.BROWSER_NOTIFICATION_LAYER SET DESKTOP_LAST_CLICK='2017-10-01' WHERE DESKTOP_LAYER='Y' AND DESKTOP_LAST_CLICK>='2017-10-01';

CREATE TABLE MOBILE_API.`BROWSER_NOTIFICATION_REGISTRATION_ARCHIVE` (
 `REG_ID` varchar(255) NOT NULL,
 `PROFILEID` int(11) DEFAULT NULL,
 `AGENTID` int(11) DEFAULT NULL,
 `CHANNEL` varchar(10) DEFAULT NULL,
 `ENTRY_DT` datetime NOT NULL,
 `ACTIVATED` enum('Y','N') NOT NULL,
 `USER_AGENT` varchar(255) NOT NULL,
 `DISABLED` enum('Y','N') DEFAULT 'N',
 PRIMARY KEY (`REG_ID`),
 UNIQUE KEY `REG_ID` (`REG_ID`,`CHANNEL`),
 KEY `PROFILEID` (`PROFILEID`,`ENTRY_DT`)
) ENGINE=InnoDB;

/*insert into MOBILE_API.`BROWSER_NOTIFICATION_REGISTRATION_ARCHIVE` select * from MOBILE_API.`BROWSER_NOTIFICATION_REGISTRATION`*/
/*TRUNCATE table MOBILE_API.BROWSER_NOTIFICATION_REGISTRATION; */




