use MOBILE_API;
UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `ICON` =  'P' WHERE  `ID` =  '1' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `ICON` =  'P' WHERE  `ID` =  '2' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `ICON` =  'P' WHERE  `ID` =  '5' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `ICON` =  'P' WHERE  `ID` =  '6' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `ICON` =  'P' WHERE  `ID` =  '7' LIMIT 1 ;

UPDATE  MOBILE_API.`BROWSER_NOTIFICATION_TEMPLATE` SET  `ICON` =  'P' WHERE  `ID` =  '8' LIMIT 1 ;