use MOBILE_API;

ALTER TABLE  `BROWSER_NOTIFICATION_TEMPLATE` CHANGE  `ID`  `ID` INT( 11 ) DEFAULT NULL AUTO_INCREMENT;

INSERT INTO `BROWSER_NOTIFICATION_TEMPLATE` VALUES (5, 'PENDING_EOI', 'Respond to {USERNAME_OTHER_1}, {USERNAME_OTHER_2} and {EOI_COUNT} more members waiting for your response.', 'Pending Interests', 'D', 'PI', 'M', 'Y', 'A', 'SUN', '15', 3, 0, '');
INSERT INTO `BROWSER_NOTIFICATION_TEMPLATE` VALUES (6, 'PENDING_EOI', 'Respond to {USERNAME_OTHER_1}, {USERNAME_OTHER_2} members waiting for your response.', 'Pending Interests', 'D', 'PI', 'M', 'Y', 'A', 'SUN', '15', 3, 0, '');
INSERT INTO `BROWSER_NOTIFICATION_TEMPLATE` VALUES (7, 'PENDING_EOI', 'Respond to {USERNAME_OTHER_1} who is waiting for your response.', 'Pending Interests', 'D', 'PI', 'M', 'Y', 'A', 'SUN', '15', 3, 0, '');

UPDATE  `BROWSER_NOTIFICATION_TEMPLATE` SET  `FREQUENCY` =  'THU,SUN' WHERE  `ID` =  '5' LIMIT 1 ;

UPDATE  `BROWSER_NOTIFICATION_TEMPLATE` SET  `FREQUENCY` =  'THU,SUN' WHERE  `ID` =  '6' LIMIT 1 ;

UPDATE  `BROWSER_NOTIFICATION_TEMPLATE` SET  `FREQUENCY` =  'THU,SUN' WHERE  `ID` =  '7' LIMIT 1 ;

ALTER TABLE  `BROWSER_NOTIFICATION_TEMPLATE` CHANGE  `FREQUENCY`  `FREQUENCY` VARCHAR( 30 );

UPDATE  `BROWSER_NOTIFICATION_TEMPLATE` SET  `COUNT` =  'MUL', FREQUENCY = 'Thu,Sun' WHERE  `ID` =  '5' LIMIT 1 ;

UPDATE  `BROWSER_NOTIFICATION_TEMPLATE` SET  `COUNT` =  'DOUBLE', FREQUENCY = 'Thu,Sun' WHERE  `ID` =  '6' LIMIT 1 ;

UPDATE  `BROWSER_NOTIFICATION_TEMPLATE` SET  `COUNT` =  'SINGLE', FREQUENCY = 'Thu,Sun' WHERE  `ID` =  '7' LIMIT 1 ;