USE newjs;

INSERT INTO newjs.SMS_TYPE ( ID , SMS_KEY , SMS_TYPE , PRIORITY , SUBSCRIPTION , GENDER , COUNT , TIME_CRITERIA , CUSTOM_CRITERIA , SMS_SUBSCRIPTION , STATUS , MESSAGE ) VALUES ('', 'MEM_REN_ACT_CRON', 'I', '0', 'A', 'A', 'SINGLE', '0', '0', 'SERVICE', 'Y', 'Dear User, {SERVNAME} has been activated on your profile {USERNAME}.');