USE billing;

UPDATE billing.SERVICES SET ACTIVE='N', ENABLE='N', SHOW_ONLINE='N'
WHERE SERVICEID NOT LIKE 'P%'
AND SERVICEID NOT LIKE 'C%'
AND SERVICEID NOT LIKE 'NCP%'
AND SERVICEID NOT LIKE 'X%'
AND SERVICEID NOT LIKE 'T%'
AND SERVICEID NOT LIKE 'R%'
AND SERVICEID NOT LIKE 'A%'
AND SERVICEID NOT LIKE 'I%'
AND SERVICEID NOT LIKE 'D%';

UPDATE billing.SERVICES SET ACTIVE='Y', ENABLE='Y'
WHERE SERVICEID LIKE 'P%'
AND SERVICEID LIKE 'C%'
AND SERVICEID LIKE 'NCP%'
AND SERVICEID LIKE 'X%'
AND SERVICEID LIKE 'T%'
AND SERVICEID LIKE 'R%'
AND SERVICEID LIKE 'A%'
AND SERVICEID LIKE 'I%'
AND SERVICEID LIKE 'D%';