use billing;

ALTER TABLE VARIABLE_DISCOUNT_TEMP 
MODIFY SERVICE VARCHAR(30) NOT NULL;

ALTER TABLE VARIABLE_DISCOUNT_TEMP ADD ID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

use test;

CREATE TABLE `VD_UPLOAD_TEMP` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `SDATE` date NOT NULL,
 `EDATE` date NOT NULL,
 `SERVICE` varchar(30) NOT NULL,
 `3` tinyint(3) DEFAULT '0',
 `6` tinyint(3) DEFAULT '0',
 `12` tinyint(3) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

use billing;

RENAME TABLE VARIABLE_DISCOUNT_LOG TO VARIABLE_DISCOUNT_LOG_2016_02_01;
RENAME TABLE VARIABLE_DISCOUNT_OFFER_DURATION_LOG TO VARIABLE_DISCOUNT_OFFER_DURATION_LOG_2016_02_01;

CREATE TABLE `VARIABLE_DISCOUNT_LOG` (
 `PROFILEID` int(11) NOT NULL,
 `DISCOUNT` tinyint(4) NOT NULL,
 `SDATE` date NOT NULL,
 `EDATE` date NOT NULL,
 `ENTRY_DT` date NOT NULL,
 `SENT` enum('Y','N') NOT NULL DEFAULT 'N',
 `SENT_MAIL` enum('Y','N') NOT NULL DEFAULT 'N',
 KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `VARIABLE_DISCOUNT_OFFER_DURATION_LOG` (
 `PROFILEID` int(11) unsigned NOT NULL,
 `SERVICE` char(6) NOT NULL DEFAULT '',
 `3` tinyint(3) DEFAULT '0',
 `6` tinyint(3) DEFAULT '0',
 `12` tinyint(3) DEFAULT '0',
 `L` tinyint(3) DEFAULT '0',
 `EDATE` date DEFAULT NULL,
 KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;