USE newjs;

INSERT INTO newjs.SMS_TYPE ( ID , SMS_KEY , SMS_TYPE , PRIORITY , SUBSCRIPTION , GENDER , COUNT , TIME_CRITERIA , CUSTOM_CRITERIA , SMS_SUBSCRIPTION , STATUS , MESSAGE ) VALUES ('', 'CRM_SMS_OFFER', 'I', '0', 'F,P,A', 'A', 'SINGLE', '0', '0', 'SERVICE', 'Y', 'Dear User, You are selected for a {DISCOUNT_TEXT}. LOGIN to get discount at {MEM_AUTO_LOGIN} or call us at 18004196299.');
INSERT INTO newjs.SMS_TYPE ( ID , SMS_KEY , SMS_TYPE , PRIORITY , SUBSCRIPTION , GENDER , COUNT , TIME_CRITERIA , CUSTOM_CRITERIA , SMS_SUBSCRIPTION , STATUS , MESSAGE ) VALUES ('', 'CRM_SMS_BRANCH', 'I', '0', 'F,P,A', 'A', 'SINGLE', '0', '0', 'SERVICE', 'Y', 'Your nearest Jeevansathi branch is {BRANCH_ADDRESS}.');
INSERT INTO newjs.SMS_TYPE ( ID , SMS_KEY , SMS_TYPE , PRIORITY , SUBSCRIPTION , GENDER , COUNT , TIME_CRITERIA , CUSTOM_CRITERIA , SMS_SUBSCRIPTION , STATUS , MESSAGE ) VALUES ('', 'CRM_SMS_NOT_REACH', 'I', '0', 'F,P,A', 'A', 'SINGLE', '0', '0', 'SERVICE', 'Y', 'Dear User, {CRM_AGENT} from Jeevansathi tried contacting you! Please give us a call back at the Toll Free Number.');
INSERT INTO newjs.SMS_TYPE ( ID , SMS_KEY , SMS_TYPE , PRIORITY , SUBSCRIPTION , GENDER , COUNT , TIME_CRITERIA , CUSTOM_CRITERIA , SMS_SUBSCRIPTION , STATUS , MESSAGE ) VALUES ('', 'CRM_SMS_APP_DOWNLOAD', 'I', '0', 'F,P,A', 'A', 'SINGLE', '0', '0', 'SERVICE', 'Y', 'Dear User, Download the Jeevansathi App on your Android or iPhone for the best matrimonial search experience on Mobile: {CRM_SMS_APP_URL}.');

USE incentive;

CREATE TABLE incentive.CRM_SMS_LOG (ID INT(11) NOT NULL AUTO_INCREMENT , PROFILEID INT(11) , SMS_KEY VARCHAR(50) , ENTRY_DT DATE DEFAULT '0000-00-00' NOT NULL , PRIMARY KEY (ID) , INDEX (ENTRY_DT), INDEX (PROFILEID));