USE billing;

UPDATE billing.SERVICES SET PRICE_RS=ROUND(PRICE_RS_TAX/1.14,2);

UPDATE billing.REV_MASTER SET SERVICE_TAX = ROUND(DUEAMOUNT*(14/100),2), DUEAMOUNT=DUEAMOUNT+SERVICE_TAX, TOTAL_AMT=TOTAL_AMT+SERVICE_TAX WHERE DUEAMOUNT != 0 AND TAX_RATE = 12.36;