USE billing;

ALTER TABLE billing.TRACKING_FAILED_PAYMENT CHANGE NET_AMOUNT NET_AMOUNT DOUBLE DEFAULT '0',CHANGE DISCOUNT DISCOUNT DOUBLE DEFAULT '0';

ALTER TABLE billing.TRACKING_FAILED_PAYMENT_LOG CHANGE NET_AMOUNT NET_AMOUNT DOUBLE DEFAULT '0',CHANGE DISCOUNT DISCOUNT DOUBLE DEFAULT '0';

ALTER TABLE billing.TRACKING_BILLING_REVAMP CHANGE NET_AMOUNT NET_AMOUNT DOUBLE DEFAULT '0',CHANGE DISCOUNT DISCOUNT DOUBLE DEFAULT '0';
