use billing;

ALTER TABLE billing.PAYMENT_DETAIL ADD COLUMN APPLE_COMMISSION DOUBLE DEFAULT '0' NOT NULL, ADD COLUMN FRANCHISEE_COMMISSION DOUBLE DEFAULT '0' NOT NULL;

CREATE TABLE `APPLE_COMMISSION_PERCENTAGE_LOG` (
  `PERCENTAGE` int(2) NOT NULL DEFAULT '0',
  `ENTRY_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO billing.APPLE_COMMISSION_PERCENTAGE_LOG VALUES (30,NOW());

ALTER TABLE incentive.MONTHLY_INCENTIVE_ELIGIBILITY CHANGE APPLE_COMMISSION APPLE_COMMISSION DOUBLE DEFAULT '0' NOT NULL; 