USE incentive;

ALTER TABLE incentive.BRANCH_CITY ADD CHEQUE_PICKUP CHAR(1) DEFAULT NULL ;

ALTER TABLE incentive.BRANCH_CITY ADD INDEX (CHEQUE_PICKUP) ;

UPDATE incentive.BRANCH_CITY SET CHEQUE_PICKUP = 'Y' WHERE ID IN (46,133,75,59,68,123,20,108,37);