USE incentive;

ALTER TABLE incentive.CRM_AGENT_CHECKIN_CHECKOUT_LOG CHANGE LOG_TYPE LOG_TYPE ENUM( 'CHECKIN', 'CHECKOUT') CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL;

ALTER TABLE incentive.CRM_AGENT_CHECKIN_CHECKOUT_LOG ADD USERNAME VARCHAR( 20 ) DEFAULT NULL AFTER AGENT_NAME;

ALTER TABLE incentive.CRM_AGENT_CHECKIN_CHECKOUT_LOG ADD AGENT_LOCATION ENUM( 'OFFICE', 'RESIDENCE' ) DEFAULT NULL AFTER LOG_TYPE ;