USE incentive;

ALTER TABLE incentive.MONTHLY_INCENTIVE_ELIGIBILITY ADD `SPLIT_AGENT` VARCHAR( 50 ) DEFAULT NULL ,
ADD `SPLIT_SHARE` INT( 11 ) DEFAULT '0' NOT NULL ;

ALTER TABLE incentive.MONTHLY_INCENTIVE_ELIGIBILITY CHANGE `APPLE_COMMISSION` `APPLE_COMMISSION` DOUBLE NOT NULL DEFAULT '0';