USE incentive;

CREATE TABLE incentive.DISCOUNT_NEGOTIATION_LOG (
 ID int(11) NOT NULL AUTO_INCREMENT,
 AGENT_NAME varchar(50) DEFAULT NULL,
 PROFILEID int(11) DEFAULT NULL,
 DISCOUNT int(3) DEFAULT NULL,
 ENTRY_DT datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 EXPIRY_DT datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (ID),
 KEY AGENT_NAME (AGENT_NAME),
 KEY PROFILEID (PROFILEID),
 KEY ENTRY_DT (ENTRY_DT),
 KEY EXPIRY_DT (EXPIRY_DT)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1