CREATE TABLE incentive.SUCCESS_STORY_EMAIL_LOG (
  MAILERID int(11) NOT NULL AUTO_INCREMENT,
  PROFILEID int(11) DEFAULT NULL,
  ENTRY_DT datetime DEFAULT NULL,
  `STATUS` varchar(2) DEFAULT NULL,
  KEY MAILERID_STATUS (MAILERID,`STATUS`)
); 