USE billing;

UPDATE billing.SERVICES SET PRICE_RS_TAX = '3400', PRICE_DOL = '109.99' WHERE SERVICEID = 'P3';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '3700', PRICE_DOL = '129.99' WHERE SERVICEID = 'P4';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '4000', PRICE_DOL = '139.99' WHERE SERVICEID = 'P5';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '4600', PRICE_DOL = '149.99' WHERE SERVICEID = 'P6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '5900', PRICE_DOL = '174.99' WHERE SERVICEID = 'P8';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '6200', PRICE_DOL = '179.99' WHERE SERVICEID = 'P9';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '7500', PRICE_DOL = '209.99' WHERE SERVICEID = 'P12';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '9200', PRICE_DOL = '249.99' WHERE SERVICEID = 'PL';

UPDATE billing.SERVICES SET PRICE_RS_TAX = '4000', PRICE_DOL = '119.99' WHERE SERVICEID = 'C3';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '4600', PRICE_DOL = '149.99' WHERE SERVICEID = 'C4';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '4900', PRICE_DOL = '159.99' WHERE SERVICEID = 'C5';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '5500', PRICE_DOL = '179.99' WHERE SERVICEID = 'C6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '6900', PRICE_DOL = '199.99' WHERE SERVICEID = 'C8';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '7500', PRICE_DOL = '209.99' WHERE SERVICEID = 'C9';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '9200', PRICE_DOL = '229.99' WHERE SERVICEID = 'C12';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '11500', PRICE_DOL = '249.99' WHERE SERVICEID = 'CL';

UPDATE billing.SERVICES SET PRICE_RS_TAX = '7500', PRICE_DOL = '199.99' WHERE SERVICEID = 'ESP3';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '9200', PRICE_DOL = '239.99' WHERE SERVICEID = 'ESP4';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '9900', PRICE_DOL = '249.99' WHERE SERVICEID = 'ESP5';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '11500', PRICE_DOL = '299.99' WHERE SERVICEID = 'ESP6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '11900', PRICE_DOL = '349.99' WHERE SERVICEID = 'ESP8';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '21500', PRICE_DOL = '399.99' WHERE SERVICEID = 'ESPL';

UPDATE billing.SERVICES SET PRICE_RS_TAX = '4900', PRICE_DOL = '149.99' WHERE SERVICEID = 'NCP3';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '5500', PRICE_DOL = '189.99' WHERE SERVICEID = 'NCP4';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '5900', PRICE_DOL = '199.99' WHERE SERVICEID = 'NCP5';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '6900', PRICE_DOL = '249.99' WHERE SERVICEID = 'NCP6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '7500', PRICE_DOL = '249.99' WHERE SERVICEID = 'NCP8';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '8700', PRICE_DOL = '299.99' WHERE SERVICEID = 'NCP9';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '10900', PRICE_DOL = '299.99' WHERE SERVICEID = 'NCP12';

UPDATE billing.SERVICES SET PRICE_RS_TAX = '19500', PRICE_DOL = '399.99' WHERE SERVICEID = 'X3';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '29500', PRICE_DOL = '599.99' WHERE SERVICEID = 'X6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '45500', PRICE_DOL = '899.99' WHERE SERVICEID = 'X12';

UPDATE billing.SERVICES SET PRICE_RS_TAX = '1100', PRICE_DOL = '29.99' WHERE SERVICEID = 'R3';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '1800', PRICE_DOL = '49.99' WHERE SERVICEID = 'R6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '2400', PRICE_DOL = '69.99' WHERE SERVICEID = 'R12';

UPDATE billing.SERVICES SET PRICE_RS_TAX = '1400', PRICE_DOL = '39.99' WHERE SERVICEID = 'T3';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '2200', PRICE_DOL = '64.99' WHERE SERVICEID = 'T6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '2800', PRICE_DOL = '79.99' WHERE SERVICEID = 'T12';

UPDATE billing.SERVICES SET PRICE_RS_TAX = '420', PRICE_DOL = '10.99' WHERE SERVICEID = 'B3';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '14.99' WHERE SERVICEID = 'B6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '850', PRICE_DOL = '24.99' WHERE SERVICEID = 'B12';

UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '14.99' WHERE SERVICEID = 'A3';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '1100', PRICE_DOL = '29.99' WHERE SERVICEID = 'A6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '1800', PRICE_DOL = '49.99' WHERE SERVICEID = 'A12';

UPDATE billing.SERVICES SET PRICE_RS_TAX = '1800', PRICE_DOL = '49.99' WHERE SERVICEID = 'I30';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '3400', PRICE_DOL = '99.99' WHERE SERVICEID = 'I60';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '6200', PRICE_DOL = '199.99' WHERE SERVICEID = 'I120';

UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M1';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M2';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M3';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M4';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M5';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M6';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M7';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M8';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M9';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M10';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M11';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'M12';
UPDATE billing.SERVICES SET PRICE_RS_TAX = '550', PRICE_DOL = '39.99' WHERE SERVICEID = 'ML';

UPDATE billing.SERVICES SET PRICE_RS=ROUND(PRICE_RS_TAX/(1+(14/100)),2); 