use billing;

truncate table billing.RENEWAL_DISCOUNT_LOOKUP; 

INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (0, 30, 60);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (31, 45, 55);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (46, 60, 50);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (61, 70, 45);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (71, 75, 40);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (76, 80, 35);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (81, 85, 30);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (86, 90, 25);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (91, 95, 20);
INSERT INTO `RENEWAL_DISCOUNT_LOOKUP` (`SCORE_LOWER_LIMIT`, `SCORE_UPPER_LIMIT`, `DISCOUNT`) VALUES (96, 100, 15);
