USE billing;

CREATE TABLE billing.DROPOFF_SOURCE_TRACKING (
  ID int(11) NOT NULL AUTO_INCREMENT,
  PROFILEID int(11) NOT NULL DEFAULT '0',
  PAGE int(2) NOT NULL DEFAULT '0',
  ENTRY_DT datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  SOURCE varchar(60) NOT NULL,
  COUNTRY varchar(5) NOT NULL DEFAULT 'IN',
  PRIMARY KEY (ID),
  KEY PROFILEID (PROFILEID),
  KEY ENTRY_DT (ENTRY_DT),
  KEY SOURCE (SOURCE),
  KEY COUNTRY (COUNTRY)
) ENGINE=InnoDB;