USE billing;

CREATE TABLE billing.TRACK_TRANSACTION_DISCOUNT_APPROVAL (
  BILLID int(11) DEFAULT NULL,
  PROFILEID int(11) DEFAULT NULL,
  DISCOUNT_TYPE int(3) DEFAULT '12',
  APPROVED_BY varchar(50) NOT NULL DEFAULT 'rohan.m',
  DISCOUNT_PERC int(3) NOT NULL DEFAULT '0',
  INITIAL_BILL_AMOUNT double NOT NULL DEFAULT '0',
  FINAL_BILL_AMOUNT double NOT NULL DEFAULT '0',
  SERVICES_PURCHASED varchar(100) DEFAULT NULL,
  ENTRY_DT datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
);