use billing;
CREATE TABLE `RENEWAL_DISCOUNT_LOG` (
 `PROFILEID` int(11) NOT NULL,
 `DISCOUNT` tinyint(4) DEFAULT NULL,
 `START_DT` date DEFAULT NULL,
 `EXPIRY_DT` date DEFAULT NULL,
 PRIMARY KEY (`PROFILEID`),
 KEY `EXPIRY_DT` (`EXPIRY_DT`)
) ENGINE=InnoDB
