use billing;

UPDATE COMPONENTS SET DURATION = '1' WHERE COMPID = 'M1' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '2' WHERE COMPID = 'M2' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '3' WHERE COMPID = 'M3' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '4' WHERE COMPID = 'M4' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '5' WHERE COMPID = 'M5' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '6' WHERE COMPID = 'M6' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '7' WHERE COMPID = 'M7' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '8' WHERE COMPID = 'M8' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '9' WHERE COMPID = 'M9' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '10' WHERE COMPID = 'M10' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '11' WHERE COMPID = 'M11' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '12' WHERE COMPID = 'M12' LIMIT 1;
UPDATE COMPONENTS SET DURATION = '1188' WHERE COMPID = 'ML' LIMIT 1;