USE MIS;
CREATE TABLE  `INAPPROPRIATE_USERS_LOG` (
 `PROFILEID` INT( 11 ) NOT NULL ,
 `USERNAME` VARCHAR( 10 ) NOT NULL ,
 `RELIGION_COUNT` MEDIUMINT( 6 ) NOT NULL ,
 `MSTATUS_COUNT` MEDIUMINT( 6 ) NOT NULL ,
 `AGE_COUNT` MEDIUMINT( 6 ) NOT NULL ,
 `CRITERIA1_COUNT` MEDIUMINT( 6 ) NOT NULL DEFAULT 0 ,
 `CRITERIA2_COUNT` MEDIUMINT( 6 ) NOT NULL DEFAULT 0 ,
 `TOTAL_SCORE` MEDIUMINT( 6 ) NOT NULL,
 `DATE` DATE NOT NULL ,
INDEX (  `PROFILEID` ,  `DATE` , `TOTAL_SCORE` )
)ENGINE=MyISAM DEFAULT CHARSET=latin1 ;

CREATE TABLE  `INAPPROPRIATE_USERS_REPORT` (
 `PROFILEID` INT( 11 ) NOT NULL ,
 `USERNAME` VARCHAR( 10 ) NOT NULL ,
 `RELIGION_COUNT` MEDIUMINT( 6 ) NOT NULL ,
 `MSTATUS_COUNT` MEDIUMINT( 6 ) NOT NULL ,
 `AGE_COUNT` MEDIUMINT( 6 ) NOT NULL ,
 `CRITERIA1_COUNT` MEDIUMINT( 6 ) NOT NULL DEFAULT 0 ,
 `CRITERIA2_COUNT` MEDIUMINT( 6 ) NOT NULL DEFAULT 0 ,
 `TOTAL_SCORE` MEDIUMINT( 6 ) NOT NULL,
 `DATE` DATE NOT NULL ,
INDEX (  `PROFILEID` ,  `DATE` , `TOTAL_SCORE` )
)ENGINE=MyISAM DEFAULT CHARSET=latin1 ;
