use MIS;
CREATE TABLE `EOI_DENIED_LOG` (
  `ID` mediumint(11) unsigned NOT NULL AUTO_INCREMENT,
  `VIEWER_PFID` int(11) unsigned NOT NULL,
  `VIEWED_PFID` int(11) unsigned NOT NULL,
  `DATE` date NOT NULL,
  `GENDER` char(3) NOT NULL DEFAULT 'N',
  `TYPE_BREACHED` char(6) NOT NULL DEFAULT 'N',
  `TYPE_OF_USER` char(15) NOT NULL DEFAULT 'N',
  `COUNT_BREACHED` int(11) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `VIEWER_PFID` (`VIEWER_PFID`),
  KEY `VIEWED_PFID` (`VIEWED_PFID`),
  KEY `DATE` (`DATE`),
  CONSTRAINT AVOID_EXTRA UNIQUE (VIEWER_PFID,VIEWED_PFID,DATE)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;