use PROFILE;

CREATE TABLE `DELETE_LOGS` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `DELETE_REASON` varchar(255) NOT NULL,
 `SPECIFY_REASON` varchar(255) NOT NULL,
 `USERNAME` varchar(16) NOT NULL,
 `CHANNEL` varchar(16) NOT NULL,
 `START_TIME` datetime NOT NULL,
 `END_TIME` datetime NOT NULL,
 `COMPLETE_STATUS` enum('Y','N') NOT NULL DEFAULT 'N',
 `INTERFACE` enum('F','B') NOT NULL DEFAULT 'F',
 PRIMARY KEY (`ID`),
 KEY `PROFILEID_ST_DATE` (`PROFILEID`,`START_TIME`)
) ENGINE=MyISAM;
