use newjs;
INSERT INTO  `SMS_TYPE` (  `ID` ,  `SMS_KEY` ,  `SMS_TYPE` ,  `PRIORITY` ,  `SUBSCRIPTION` ,  `GENDER` ,  `COUNT` ,  `TIME_CRITERIA` ,  `CUSTOM_CRITERIA` ,  `SMS_SUBSCRIPTION` ,  `STATUS` ,  `MESSAGE` ) 
VALUES ('',  'VIEWED_CONTACT_SMS',  'I',  '2',  'A',  'A',  'SINGLE',  '0',  '0',  'SERVICE',  'Y', 'Details of {OTHER_USERNAME} ({URL_OTHER_PROFILE}):
Phone No.(s): {ISD_PHONE_MOB}{ISD_ALT_MOB_COMMA}{ISD_LANDLINE_COMMA}
Email: {EMAIL}'
)