USE newjs;
CREATE TABLE  `EMAIL_CHANGE_LOG` (
 `ID` INT( 15 ) NOT NULL AUTO_INCREMENT ,
 `PROFILEID` INT( 11 ) UNSIGNED NOT NULL ,
 `EMAIL` VARCHAR( 100 ) NOT NULL ,
 `STATUS` CHAR( 1 ) NOT NULL ,
 `CHANGE_DATE` DATETIME NOT NULL ,
 `VERIFY_DATE` DATETIME NOT NULL ,
INDEX (  `ID` ,  `PROFILEID` )
);