use feedback;
ALTER TABLE `REPORT_ABUSE_LOG` CHANGE COLUMN `REASON` `CATEGORY` VARCHAR(100) NOT NULL;
ALTER TABLE REPORT_ABUSE_LOG ADD OTHER_REASON VARCHAR( 100 );
UPDATE  `REPORT_ABUSE_LOG` SET OTHER_REASON =  '' WHERE 1;

