USE feedback;

CREATE TABLE `REVIEW_STATUS_LOG` (
     `ID` int(11) NOT NULL AUTO_INCREMENT,
     `DATE` datetime DEFAULT NULL,
     `STATUS` char(1) NOT NULL,
     `USER` varchar(50) NOT NULL,
     `REPORT` int(11) NOT NULL,
     PRIMARY KEY (`ID`)
);

ALTER TABLE  `REPORT_ABUSE_LOG` ADD  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST ;
ALTER TABLE `REPORT_ABUSE_LOG` ADD `REVIEW_STATUS` char(1);
