use OUTBOUND	;
DROP TABLE IF EXISTS `THIRD_PARTY_CALL_LOGS`;
CREATE TABLE `THIRD_PARTY_CALL_LOGS` (
 `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 `CALLED_USER_ID` int(11) NOT NULL,
 `CALLSID` varchar(256) DEFAULT NULL,
 `EVENT_TYPE` int(5) NOT NULL,
 `CALLER_ID` varchar(16) NOT NULL,
 `DATE_TIME` datetime NOT NULL,
 `LANDING_FLOW_ID` varchar(128) NOT NULL,
 `PHONE_NUMBER` varchar(32) NOT NULL,
 `RESPONSE_FROM_THIRD_PARTY` varchar(4096) NOT NULL,
 `DIGIT_PRESSED` varchar(4) DEFAULT NULL,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `CALLSID` (`CALLSID`),
 KEY `CALLED_USER_ID` (`CALLED_USER_ID`)
) ENGINE=MyISAM
