use newjs;

DROP TABLE IF EXISTS CONTACTS_ONCE_LOG;
DROP TABLE IF EXISTS CONTACTS_ONCE_TEMP;
CREATE TABLE CONTACTS_ONCE_TEMP LIKE CONTACTS_ONCE;

RENAME TABLE CONTACTS_ONCE TO CONTACTS_ONCE_LOG, CONTACTS_ONCE_TEMP TO CONTACTS_ONCE;

INSERT INTO CONTACTS_ONCE SELECT * FROM CONTACTS_ONCE_BACKUP WHERE SENT = 'N';
