use CONTACT_ENGINE;

UPDATE  `BUTTON_RESPONSE` SET  `BUTTONS` = '[{"TYPE":"WRITE_MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":"true","tracking":null,"icon":"086"},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"007"},{"TYPE":"SHORTLIST","label":"Shortlisted","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"003"},{"TYPE":"DECLINE","label":"Decline Interest","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"084"}]' WHERE  `ID` =  '109' LIMIT 1 ;

UPDATE  `BUTTON_RESPONSE` SET  `BUTTONS` = '[{"TYPE":"WRITE_MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":"true","tracking":null,"icon":"086"},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"007"},{"TYPE":"SHORTLIST","label":"Shortlisted","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"003"},{"TYPE":"DECLINE","label":"Decline Interest","active":null,"primary":null,"secondary":"true","tracking":null,"icon":"084"}]' WHERE  `ID` =  '108' LIMIT 1 ;

UPDATE  `BUTTON_RESPONSE` SET  `BUTTONS` = '[{"TYPE":"TEXT","label":"You cancelled interest","active":"true","primary":"true","secondary":null,"tracking":null,"icon":null},{"TYPE":"ACCEPT","label":"Accept Again","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"085"},{"TYPE":"CANCEL","label":"Cancel Interest","active":null,"primary":null,"secondary":"true","tracking":null,"icon":"088"}]' WHERE  `ID` =  '102' LIMIT 1 ;


UPDATE  `BUTTON_RESPONSE` SET  `BUTTONS` = '[{"TYPE":"WRITE_MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":"true","tracking":null,"icon":"086"},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"007"},{"TYPE":"SHORTLIST","label":"Shortlisted","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"003"},{"TYPE":"CANCEL","label":"Cancel Interest","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"088"}]' WHERE  `ID` =  '100' LIMIT 1 ;

UPDATE  `BUTTON_RESPONSE` SET  `BUTTONS` = '[{"TYPE":"WRITE_MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":"true","tracking":null,"icon":"086"},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"007"},{"TYPE":"SHORTLIST","label":"Shortlisted","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"003"},{"TYPE":"DECLINE","label":"Decline Interest","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"084"}]' WHERE  `ID` =  '98' LIMIT 1 ;



UPDATE  `BUTTON_RESPONSE` SET  `BUTTONS` = '[{"TYPE":"MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":"true","tracking":null,"icon":"086"},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"007"},{"TYPE":"SHORTLIST","label":"Shortlisted","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"003"},{"TYPE":"DECLINE","label":"Decline Interest","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"084"}]' WHERE  `ID` =  '89' LIMIT 1 ;


UPDATE  `BUTTON_RESPONSE` SET  `BUTTONS` = '[{"TYPE":"WRITE_MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":"true","tracking":null,"icon":"086"},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":"true","tracking":null,"icon":null},{"TYPE":"SHORTLIST","label":"Shortlisted","active":"true","primary":null,"secondary":"true","tracking":null,"icon":null},{"TYPE":"CANCEL","label":"Cancel Interest","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"088"},{"TYPE":"REPORT_ABUSE","label":"Report Abuse","active":"true","primary":"false","secondary":"true","tracking":null,"icon":"099"}]' WHERE  `ID` =  '74' LIMIT 1 ;


UPDATE  `BUTTON_RESPONSE` SET  `BUTTONS` = '[{"TYPE":"WRITE_MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":"true","tracking":null,"icon":"086"},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"007"},{"TYPE":"SHORTLIST","label":"Shortlisted","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"003"},{"TYPE":"CANCEL","label":"Cancel Interest","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"088"}]' WHERE  `ID` =  '62' LIMIT 1 ;

UPDATE  `BUTTON_RESPONSE` SET  `BUTTONS` = '[{"TYPE":"WRITE_MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":"true","tracking":null,"icon":"086"},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"007"},{"TYPE":"SHORTLIST","label":"Shortlisted","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"003"},{"TYPE":"DECLINE","label":"Decline Interest","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"084"}]' WHERE  `ID` =  '61' LIMIT 1 ;

UPDATE  `BUTTON_RESPONSE` SET  `BUTTONS` = '[{"TYPE":"WRITE_MESSAGE","label":"Write Message","active":"true","primary":"true","secondary":"true","tracking":null,"icon":"086"},{"TYPE":"CONTACT_DETAIL","label":"View Contacts","active":"true","primary":null,"secondary":"true","tracking":null,"icon":null},{"TYPE":"SHORTLIST","label":"Shortlisted","active":"true","primary":null,"secondary":"true","tracking":null,"icon":null},{"TYPE":"DECLINE","label":"Decline Interest","active":"true","primary":null,"secondary":"true","tracking":null,"icon":"084"},{"TYPE":"REPORT_ABUSE","label":"Report Abuse","active":"true","primary":"false","secondary":"true","tracking":null,"icon":"099"}]' WHERE  `ID` =  '79' LIMIT 1 ;


