-- For Shard Sql Instance
use newjs;

CREATE TABLE `DELETED_CHATS_ELIGIBLE_FOR_RET` LIKE `CHATS`;

CREATE TABLE `ARCHIVE_DELETED_CHATS` LIKE `CHATS`;

CREATE TABLE `DELETED_CHAT_LOG_ELIGIBLE_FOR_RET` LIKE `CHAT_LOG`;

CREATE TABLE `ARCHIVE_DELETED_CHAT_LOG` LIKE `CHAT_LOG`;