use PROFILE;
CREATE TABLE `LOG_DELETION_FLOW` (
  `ID` int(15) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `TIME` datetime NOT NULL,
  `TABLE_NAME` varchar(36) NOT NULL,
  UNIQUE KEY `ID` (`ID`),
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;