use PROFILE;
CREATE TABLE `LOG_DELETION_FLOW` (
  `ID` int(15) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `TIME` datetime NOT NULL,
  `TABLE_NAME` varchar(36) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM;