use jsadmin;

CREATE TABLE `DELETED_VIEW_CONTACTS_LOG` (
 `ID` mediumint(11) NOT NULL AUTO_INCREMENT,
 `VIEWER` int(11) unsigned NOT NULL,
 `VIEWED` int(11) unsigned NOT NULL,
 `DATE` datetime NOT NULL,
 `SOURCE` char(5) NOT NULL,
 `SEEN` char(1) NOT NULL,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `VIEWER` (`VIEWER`,`VIEWED`),
 KEY `DATE` (`DATE`),
 KEY `VIEWED` (`VIEWED`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1
