use feedback;
DROP TABLE IF EXISTS ABUSE_ATTACHMENTS;
create table ABUSE_ATTACHMENTS ( 
ID BIGINT AUTO_INCREMENT PRIMARY KEY, 
DOC_1 VARCHAR(255) NOT NULL DEFAULT '', 
DOC_2 VARCHAR(255) NOT NULL DEFAULT '', 
DOC_3 VARCHAR(255) NOT NULL DEFAULT '', 
DOC_4 VARCHAR(255) NOT NULL DEFAULT '', 
DOC_5 VARCHAR(255) NOT NULL DEFAULT '') ENGINE=INNODB;

DROP TABLE IF EXISTS ABUSE_TEMP_ATTACHMENTS;
CREATE TABLE `ABUSE_TEMP_ATTACHMENTS` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `DOC_1` varchar(255) NOT NULL DEFAULT '',
 `DOC_2` varchar(255) NOT NULL DEFAULT '',
 `DOC_3` varchar(255) NOT NULL DEFAULT '',
 `DOC_4` varchar(255) NOT NULL DEFAULT '',
 `DOC_5` varchar(255) NOT NULL DEFAULT '',
 `MOD_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

ALTER TABLE REPORT_ABUSE_LOG ADD COLUMN ATTACHMENT_ID BIGINT(20) NOT NULL DEFAULT -1;
ALTER TABLE  `REPORT_ABUSE_LOG` ADD INDEX (  `ATTACHMENT_ID` )