USE newjs;
CREATE TABLE  `EMAIL_CHANGE_LOG` (
 `ID` INT( 15 ) NOT NULL AUTO_INCREMENT ,
 `PROFILEID` INT( 11 ) UNSIGNED NOT NULL ,
 `EMAIL` VARCHAR( 100 ) NOT NULL ,
 `STATUS` CHAR( 1 ) NOT NULL ,
 `CHANGE_DATE` DATETIME NOT NULL ,
 `VERIFY_DATE` DATETIME NOT NULL ,
INDEX (  `ID` ,  `PROFILEID` ) 
) ENGINE=InnoDB;

USE MAIL;
CREATE TABLE  `EMAIL_VER_MAILER` (
 `ID` INT( 11 ) NOT NULL AUTO_INCREMENT ,
 `RECEIVER` INT( 11 ) NOT NULL ,
 `TIME` DATETIME NOT NULL ,
 `SENT` VARCHAR( 4 ) NOT NULL ,
PRIMARY KEY (  `ID` ) ,
INDEX (  `RECEIVER` ) 
) ENGINE=MYISAM;

CREATE TABLE  `INACTIVE_PROFILES_TEMP` (
 `PROFILEID` INT( 11 ) NOT NULL ,
 `EMAIL` VARCHAR( 100 ) NOT NULL ,
 `STATUS` VARCHAR( 1 ) NOT NULL ,
PRIMARY KEY (  `PROFILEID` )
);




use jeevansathi_mailer;

INSERT INTO  `EMAIL_TYPE` (  `ID` ,  `MAIL_ID` ,  `TPL_LOCATION` ,  `HEADER_TPL` ,  `FOOTER_TPL` ,  `TEMPLATE_EX_LOCATION` ,  `MAIL_GROUP` ,  `CUSTOM_CRITERIA` ,  `SENDER_EMAILID` ,  `DESCRIPTION` ,  `MEMBERSHIP_TYPE` ,  `GENDER` , `PHOTO_PROFILE` ,  `REPLY_TO_ENABLED` ,  `FROM_NAME` ,  `REPLY_TO_ADDRESS` ,  `MAX_COUNT_TO_BE_SENT` ,  `REQUIRE_AUTOLOGIN` ,  `FTO_FLAG` ,  `PRE_HEADER` ,  `PARTIALS` ) 
VALUES (

'1834',  '1834',  'emailVerificationMailer.tpl',  'header.tpl',  'footer.tpl', NULL ,  '4',  '1',  'info@jeevansathi.com', NULL ,  'D',  '',  '', NULL ,  'Jeevansathi Info', NULL , NULL ,  'Y',  '',  '',  ''
)