use CONTACT_ENGINE;

UPDATE  `CONTACT_PRIVILEGE` SET  `ALLOWED` =  'P' WHERE  `ID` =  '569' LIMIT 1 ;

UPDATE  `CONTACT_PRIVILEGE` SET  `ALLOWED` =  'P' WHERE  `ID` =  '599' LIMIT 1 ;

UPDATE  `CONTACT_PRIVILEGE` SET  `ALLOWED` =  'P' WHERE  `ID` =  '119' LIMIT 1 ;
