use MIS;
CREATE TABLE `APP_LOGINTRACKING` (
  `PROFILEID` int(12) NOT NULL,
  `REGISTRATION_ID` varchar(255) NOT NULL,
  `APP_TYPE` varchar(255) NOT NULL,
  PRIMARY KEY (`PROFILEID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
