use newjs;
CREATE TABLE `PHONE_OTP` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL DEFAULT '0',
  `PHONE_WITH_ISD` varchar(20) NOT NULL,
  `OTP` varchar(4) DEFAULT NULL,
  `DATE` datetime DEFAULT NULL,
  `SMS_COUNT` int(2) DEFAULT '0',
  `TRIAL_COUNT` int(2) DEFAULT '0',
  KEY `PROFILEID` (`PROFILEID`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
