use newjs;
ALTER TABLE  `MESSAGE_LOG_GET_ID` ADD  `NO_USE_VARIABLE` CHAR( 1 ) NOT NULL ;

ALTER TABLE  `MESSAGE_LOG_GET_ID` ADD UNIQUE (
`NO_USE_VARIABLE`
);


ALTER TABLE  `CONTACTS_GET_ID` ADD  `NO_USE_VARIABLE` CHAR( 1 ) NOT NULL ;

ALTER TABLE  `CONTACTS_GET_ID` ADD UNIQUE (
`NO_USE_VARIABLE`
);


