USE feedback;

CREATE TABLE  `REVIEW_STATUS_LOG` (
 `ID` INT NOT NULL AUTO_INCREMENT ,
 `TIME` DATETIME NOT NULL ,
 `STATUS` CHAR( 1 ) NOT NULL ,
 `USER` VARCHAR( 50 ) NOT NULL ,
PRIMARY KEY (  `ID` )
);

ALTER TABLE  `REPORT_ABUSE_LOG` ADD  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST ;

