USE feedback;

CREATE TABLE  `REPORT_ABUSE_LOG` (
 `REPORTER` INT( 11 ) NOT NULL ,
 `REPORTEE` INT( 11 ) NOT NULL ,
 `DATE` DATETIME NOT NULL ,
 `REASON` VARCHAR( 100 ) NOT NULL ,
INDEX (  `REPORTER` ,  `REPORTEE` )
);