CREATE DATABASE OUTBOUND;

use OUTBOUND;

CREATE TABLE  `THIRD_PARTY_CALL_LOGS` (
 `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
 `CALLED_USER_ID` INT( 11 ) NOT NULL ,
 `EVENT_TYPE` INT( 5 ) NOT NULL ,
 `CALLER_ID` VARCHAR( 16 ) NOT NULL ,
 `DATE_TIME` DATETIME NOT NULL ,
 `LANDING_FLOW_ID` VARCHAR( 128 ) NOT NULL ,
 `PHONE_NUMBER` VARCHAR(32) NOT NULL,
 `RESPONSE_FROM_THIRD_PARTY` VARCHAR( 4096 ) NOT NULL ,
PRIMARY KEY (  `ID` ) ,
INDEX (  `CALLED_USER_ID` )
)ENGINE=MYISAM ;


CREATE TABLE `FAILURE_LOGS` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `EVENT_TYPE` int(5) NOT NULL,
  `PGID` varchar(16) NOT NULL,
  `DATE_TIME` datetime NOT NULL,
  `REASON` varchar(1000) NOT NULL,
  `STATUS` int(5) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
