CREATE TABLE `SMS_TRIGGER_LOG` (
  `SMS_KEY` varchar(20) NOT NULL,
  `DATE` date NOT NULL,
  `TOTAL_FIRED` int(10) NOT NULL,
  `TOTAL_SENT` int(10) NOT NULL,
  PRIMARY KEY (`SMS_KEY`,`DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
