use jeevansathi_mailer;

ALTER TABLE  `DAILY_MAILER_COUNT_LOG` CHANGE  `INCOMPLETE`  `INVALID_EMAIL` INT( 5 ) DEFAULT  '0';



ALTER TABLE  `DAILY_MAILER_COUNT_LOG` CHANGE  `TOTAL_COUNT`  `TOTAL_COUNT` INT( 8 ) DEFAULT  '0',
CHANGE  `SENT`  `SENT` INT( 8 ) DEFAULT  '0',
CHANGE  `BOUNCED`  `BOUNCED` INT( 8 ) DEFAULT  '0',
CHANGE  `INVALID_EMAIL`  `INCOMPLETE` INT( 8 ) DEFAULT  '0',
CHANGE  `UNSUBSCRIBE`  `UNSUBSCRIBE` INT( 8 ) DEFAULT  '0';
