use newjs;
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} on Jeevansathi wants to contact you, Accept/Decline their interest or view contact details at {EOI_PROFILE}.' WHERE `ID`='27';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} on Jeevansathi wants to contact you, Accept/Decline their interest or view contact details at {EOI_PROFILE}.' WHERE `ID`='28';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} on Jeevansathi wants to contact you, Accept/Decline their interest or view contact details at {EOI_PROFILE}.' WHERE `ID`='29';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} on Jeevansathi wants to contact you, Accept/Decline their interest or view contact details at {EOI_PROFILE}.' WHERE `ID`='79';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} on Jeevansathi wants to contact you, Accept/Decline their interest or view contact details at {EOI_PROFILE}.' WHERE `ID`='80';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} on Jeevansathi wants to contact you, Accept/Decline their interest or view contact details at {EOI_PROFILE}.' WHERE `ID`='168';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} on Jeevansathi wants to contact you, Accept/Decline their interest or view contact details at {EOI_PROFILE}.' WHERE `ID`='169';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} and {EOI_COUNT} other Jeevansathi members liked your profile. Accept/Decline all or view contact details at {URL_EOI}.' WHERE `ID`='30';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} and {EOI_COUNT} other Jeevansathi members liked your profile. Accept/Decline all or view contact details at {URL_EOI}.' WHERE `ID`='31';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} and {EOI_COUNT} other Jeevansathi members liked your profile. Accept/Decline all or view contact details at {URL_EOI}.' WHERE `ID`='32';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} and {EOI_COUNT} other Jeevansathi members liked your profile. Accept/Decline all or view contact details at {URL_EOI}.' WHERE `ID`='83';
UPDATE `newjs`.`SMS_TYPE` SET `MESSAGE`='Hi, {USERNAME} from {CITY_RES} and {EOI_COUNT} other Jeevansathi members liked your profile. Accept/Decline all or view contact details at {URL_EOI}.' WHERE `ID`='84';
