use MOBILE_API;
alter table `APP_LOGIN_PROFILES` add column DATE DATETIME ,
add column APP_TYPE CHAR(2);
ALTER TABLE `APP_LOGIN_PROFILES` ADD INDEX `DATE` (`DATE`);
ALTER TABLE `APP_LOGIN_PROFILES` ADD INDEX `APP_TYPE` (`APP_TYPE`);