CREATE DATABASE OUTBOUND;

use OUTBOUND;

CREATE TABLE  `THIRD_PARTY_CALL_LOGS` (
 `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
 `CALLED_USER_ID` INT( 11 ) NOT NULL ,
 `EVENT_TYPE` INT( 5 ) NOT NULL ,
 `CALLER_ID` VARCHAR( 16 ) NOT NULL ,
 `DATE_TIME` DATETIME NOT NULL ,
 `LANDING_FLOW_ID` VARCHAR( 128 ) NOT NULL ,
 `RESPONSE_FROM_THIRD_PARTY` VARCHAR( 4096 ) NOT NULL ,
PRIMARY KEY (  `ID` ) ,
INDEX (  `CALLED_USER_ID` )
)ENGINE=MYISAM ;
