USE feedback;

CREATE TABLE  `REPORT_ABUSE_LOG` (
 `REPORTER` VARCHAR( 20 ) NOT NULL ,
 `REPORTEE` VARCHAR( 20 ) NOT NULL ,
 `DATE` TIMESTAMP NOT NULL ,
 `REASON` VARCHAR( 100 ) NOT NULL ,
INDEX (  `REPORTER` ,  `REPORTEE` )
);
