-- For Main Sql Instance
use newjs;

CREATE TABLE `ARCHIVE_DELETED_BOOKMARKS` LIKE `BOOKMARKS`;

--For Shard Sql Instance
use newjs;

CREATE TABLE `ARCHIVE_DELETED_PHOTO_REQUEST` LIKE `PHOTO_REQUEST`;

CREATE TABLE `ARCHIVE_DELETED_HOROSCOPE_REQUEST` LIKE `HOROSCOPE_REQUEST`;

CREATE TABLE `ARCHIVE_DELETED_MESSAGE_LOG` LIKE `MESSAGE_LOG`;

CREATE TABLE `ARCHIVE_DELETED_MESSAGES` LIKE `MESSAGES`;

CREATE TABLE `ARCHIVE_DELETED_PROFILE_CONTACTS` LIKE `CONTACTS`;

CREATE TABLE `ARCHIVE_DELETED_EOI_VIEWED_LOG` LIKE `EOI_VIEWED_LOG`;

--For DB 211
use newjs;

CREATE TABLE `ARCHIVE_DELETED_VIEW_LOG` LIKE `VIEW_LOG`;

--On Main
ALTER TABLE `ARCHIVE_DELETED_BOOKMARKS` ENGINE = InnoDB;


--On Shards
ALTER TABLE `ARCHIVE_DELETED_PHOTO_REQUEST` ENGINE = InnoDB;
ALTER TABLE `ARCHIVE_DELETED_HOROSCOPE_REQUEST` ENGINE = InnoDB;
ALTER TABLE `ARCHIVE_DELETED_MESSAGE_LOG` ENGINE = InnoDB;
ALTER TABLE `ARCHIVE_DELETED_MESSAGES` ENGINE = InnoDB;
ALTER TABLE `ARCHIVE_DELETED_PROFILE_CONTACTS` ENGINE = InnoDB;
ALTER TABLE `ARCHIVE_DELETED_EOI_VIEWED_LOG` ENGINE = InnoDB;

--on DB 211
ALTER TABLE `ARCHIVE_DELETED_VIEW_LOG` ENGINE = InnoDB;