USE billing;

ALTER TABLE billing.OCB_BANNER_MESSAGE ADD PAGEID INT( 3 ) DEFAULT '6' NOT NULL;

CREATE TABLE `OCB_LOW_PRIPROTY_BANNER_MESSAGE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TOP_MSG` varchar(100) DEFAULT NULL,
  `BOTTOM_MSG` varchar(255) DEFAULT NULL,
  `START_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `END_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `PAGEID` int(3) NOT NULL DEFAULT '6',
  PRIMARY KEY (`ID`)
);
