use newjs;

UPDATE `EDUCATION_GROUPING` SET `LABEL` = 'Engineering/Design' WHERE `VALUE` = '4' LIMIT 1 ;

INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (44, 'BPT', 44, 5, 17, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (45, 'MPT', 45, 5, 17, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (46, 'DM', 46, 5, 17, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (47, 'MCh', 47, 5, 17, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (48, 'MSW', 48, 5, 17, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (49, 'BFA', 49, 5, 17, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (50, 'MFA', 50, 5, 17, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (51, 'BJMC', 51, 5, 17, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (52, 'MJMC', 52, 5, 17, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (53, 'B.Des', 53, 5, 17, 4);
INSERT INTO `EDUCATION_LEVEL_NEW` (`ID`, `LABEL`, `VALUE`, `OLD_VALUE`, `SORTBY`, `GROUPING`) VALUES (54, 'M.Des', 54, 5, 17, 4);

update EDUCATION_LEVEL_NEW target
join
(
     select ID, (@rownumber := @rownumber + 1) as rownum
     from EDUCATION_LEVEL_NEW         
     cross join (select @rownumber := 2) r
     WHERE SORTBY not in (1,2)
     order by LABEL asc
) source on target.ID = source.ID    
set SORTBY = rownum 
WHERE  SORTBY not in (1,2)