use matchalerts;

ALTER TABLE `MAILER` ADD `USER17` INT( 11 ) UNSIGNED DEFAULT '0' NOT NULL AFTER `RECOMEND_USER16` ,
ADD `USER18` INT( 11 ) UNSIGNED DEFAULT '0' NOT NULL AFTER `USER17` ,
ADD `USER19` INT( 11 ) UNSIGNED DEFAULT '0' NOT NULL AFTER `USER18` ,
ADD `USER20` INT( 11 ) UNSIGNED DEFAULT '0' NOT NULL AFTER `USER19` ;
