USE PROFILE;

ALTER TABLE  `CA_LAYER_DISPLAY_DATA` ADD  `AFTER_SAME` MEDIUMINT UNSIGNED NOT NULL AFTER  `TIMES` ;

ALTER TABLE  `CA_LAYER_DISPLAY_DATA` ADD  `AFTER_PREV` MEDIUMINT UNSIGNED NOT NULL AFTER  `AFTER_SAME` ;


UPDATE  `CA_LAYER_DISPLAY_DATA` SET  `AFTER_SAME` =  '24',`AFTER_PREV` =  '24' WHERE  `LAYERID` =  '1' LIMIT 1 ;

UPDATE  `CA_LAYER_DISPLAY_DATA` SET  `AFTER_SAME` =  '24',`AFTER_PREV` =  '24' WHERE  `LAYERID` =  '2' LIMIT 1 ;

UPDATE  `CA_LAYER_DISPLAY_DATA` SET  `TIMES` =  '255',
`AFTER_SAME` =  '168',`AFTER_PREV` =  '24' WHERE  `LAYERID` =  '3' LIMIT 1 ;

