CREATE DATABASE  `MARKETING` ;

use MARKETING;

CREATE TABLE  `PROFILE_DETAILS` (
 `SNO` MEDIUMINT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT ,
 `NAME` VARCHAR( 40 ) ,
 `AGE` TINYINT( 4 ) NOT NULL ,
 `PARTNER_NAME` VARCHAR( 40 ) NOT NULL ,
 `USERNAME` VARCHAR( 40 ) NOT NULL ,
 `PHONE` VARCHAR( 100 ) NOT NULL ,
 `EMAIL` VARCHAR( 200 ) NOT NULL ,
 `DESCRIPTION` TEXT NOT NULL ,
 `PICTURE` VARCHAR( 200 ) NOT NULL ,
 `VIDEO_URL` VARCHAR( 200 ) NOT NULL ,
 `SATHI_STORY` TEXT NOT NULL ,
 `TWITTER_HANDLE` VARCHAR( 200 ) NOT NULL ,
 `INSTA_USERNAME` VARCHAR( 200 ) NOT NULL ,
PRIMARY KEY (  `SNO` ) ,
INDEX (  `USERNAME` )
)ENGINE=InnoDB;
