use matchalerts;
ALTER TABLE `MATCHALERTS_TO_BE_SENT` ADD `LAST_LOGIN_DT` DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL ;
ALTER TABLE `MATCHALERTS_TO_BE_SENT` ADD `FROM_REG` ENUM( '1', '0' ) DEFAULT '0' NOT NULL ;
CREATE TABLE MATCHALERTS_TO_BE_SENT_REG LIKE MATCHALERTS_TO_BE_SENT