use viewSimilar;


ALTER TABLE  `TEMP_CONTACTS_CACHE_LEVEL2_FEMALE_RENAME` ADD  `PARTNER_LAGE` TINYINT DEFAULT NULL ,
ADD  `PARTNER_HAGE` TINYINT DEFAULT NULL ,
ADD  `PARTNER_LHEIGHT` TINYINT DEFAULT NULL ,
ADD  `PARTNER_HHEIGHT` TINYINT DEFAULT NULL ,
ADD  `PARTNER_MSTATUS` TEXT DEFAULT NULL ,
ADD  `PARTNER_CITYRES` TEXT DEFAULT NULL ,
ADD  `PARTNER_COUNTRYRES` TEXT DEFAULT NULL ,
ADD  `PARTNER_HANDICAPPED` TEXT DEFAULT NULL ,
ADD  `PARTNER_RELIGION` TEXT DEFAULT NULL ,
ADD  `PARTNER_CASTE` TEXT DEFAULT NULL ,
ADD  `PARTNER_ELEVEL_NEW` TEXT DEFAULT NULL ;



ALTER TABLE  `TEMP_CONTACTS_CACHE_LEVEL2_MALE_RENAME` ADD  `PARTNER_LAGE` TINYINT DEFAULT NULL ,
ADD  `PARTNER_HAGE` TINYINT DEFAULT NULL ,
ADD  `PARTNER_LHEIGHT` TINYINT DEFAULT NULL ,
ADD  `PARTNER_HHEIGHT` TINYINT DEFAULT NULL ,
ADD  `PARTNER_MSTATUS` TEXT DEFAULT NULL ,
ADD  `PARTNER_CITYRES` TEXT DEFAULT NULL ,
ADD  `PARTNER_COUNTRYRES` TEXT DEFAULT NULL ,
ADD  `PARTNER_HANDICAPPED` TEXT DEFAULT NULL ,
ADD  `PARTNER_RELIGION` TEXT DEFAULT NULL ,
ADD  `PARTNER_CASTE` TEXT DEFAULT NULL ,
ADD  `PARTNER_INCOME` TEXT DEFAULT NULL ;


ALTER TABLE  `CONTACTS_CACHE_LEVEL2_FEMALE_RENAME` CHANGE  `PARTNER_INCOME`  `PARTNER_ELEVEL_NEW` TEXT;
ALTER TABLE  `CONTACTS_CACHE_LEVEL2_MALE_RENAME` CHANGE  `PARTNER_ELEVEL_NEW`  `PARTNER_INCOME` TEXT;