use MIS;

CREATE TABLE  `CAMPAIGN_KEYWORD_TRACKING` (
 `PROFILEID` INT( 11 ) UNSIGNED NOT NULL ,
 `CAMPAIGN` VARCHAR( 50 ) ,
 `ADNAME` VARCHAR( 50 ) ,
 `KEYWORD` VARCHAR( 50 ) ,
 `ADGROUP` VARCHAR( 50 ) ,
 `MEDIUM` VARCHAR( 50 ) ,
PRIMARY KEY (  `PROFILEID` )
);
