use reg;

INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 81, '', 'JPROFILE:GOTHRA', 'Gotra', '', '');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 79, '', 'JPROFILE:FAMILYINFO', 'About Family', '', '');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 77, '', 'JPROFILE:M_SISTER', 'Of which Married', '', 'Select');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 76, '', 'JPROFILE:T_SISTER', 'Sisters', '', 'Select');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 75, '', 'JPROFILE:M_BROTHER', 'Of which Married', '', 'Select');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 74, '', 'JPROFILE:T_BROTHER', 'Brothers', '', 'Select');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 73, '', 'JPROFILE:MOTHER_OCC', 'Mother''s Occupation', '', 'Please Select');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 72, '', 'JPROFILE:FAMILY_BACK', 'Father''s Occupation', '', 'Please Select');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 71, '', 'JPROFILE:FAMILY_STATUS', 'Family Status', '', '');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 70, '', 'JPROFILE:FAMILY_TYPE', 'Family Type', '', '');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 69, '', 'JPROFILE:FAMILY_VALUES', 'Family Values', '', '');
INSERT INTO `REG_EDIT_PAGE_FIELDS` VALUES ('APP3', 117, '', 'JPROFILE:FAMILY_INCOME', 'Family Income', '', '');
