use PROFILE;

CREATE TABLE `PROFILE`.`RCB_RESPONSE` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PROFILEID` INT(11) UNSIGNED NOT NULL,
  `TIMESTAMP` DATETIME NOT NULL,
  `RESPONSE` ENUM('Y','N') NOT NULL,
  PRIMARY KEY (`ID`))Engine=MyISAM;

