CREATE DATABASE REGISTER;

USE REGISTER;

CREATE TABLE `USER_PROFILE_FIELDS` (
 `ID` smallint(6) NOT NULL AUTO_INCREMENT,
 `FIELD_NAME` varchar(100) NOT NULL,
 `TYPE` varchar(50) NOT NULL,
 `CONSTRAINT_CLASS` varchar(50) NOT NULL,
 `DEPENDENT_FIELD` smallint(6) DEFAULT NULL,
 `LABEL` varchar(50) NOT NULL,
 `BLANK_VALUE` varchar(30) DEFAULT NULL,
 `BLANK_LABEL` varchar(100) DEFAULT NULL,
 `TABLE_NAME` varchar(100) NOT NULL,
 PRIMARY KEY (`ID`)
);


INSERT INTO `USER_PROFILE_FIELDS` VALUES (1, 'EMAIL', 'text', 'email', NULL, 'Email', NULL, NULL, 'JPROFILE:EMAIL');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (2, 'PASSWORD', 'password', 'password', NULL, 'Password', NULL, NULL, 'JPROFILE:PASSWORD');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (3, 'RELATIONSHIP', 'dropdown', 'dropdown_req', NULL, 'Create Profile For', NULL, NULL, 'JPROFILE:RELATION');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (4, 'GENDER', 'radio', 'dropdown_req', 3, 'Gender', NULL, NULL, 'JPROFILE:GENDER');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (5, 'DTOFBIRTH', 'date', 'dob', NULL, 'Date of Birth', NULL, NULL, 'JPROFILE:DTOFBIRTH');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (7, 'PINCODE', 'text', 'pin', 10, 'Pincode', NULL, NULL, 'JPROFILE:PINCODE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (8, 'HEIGHT', 'dropdown', 'dropdown_req', NULL, 'Height', NULL, NULL, 'JPROFILE:HEIGHT');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (9, 'COUNTRY_RES', 'dropdown', 'dropdown_req', NULL, 'Country living in', NULL, NULL, 'JPROFILE:COUNTRY_RES');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (10, 'CITY_RES', 'dropdown', 'dropdown_req', 9, 'City', NULL, NULL, 'JPROFILE:CITY_RES');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (11, 'MSTATUS', 'dropdown', 'mstatus', NULL, 'Marital Status', NULL, NULL, 'JPROFILE:MSTATUS');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (12, 'HAVECHILD', 'dropdown', 'havechild', 11, 'Have Children', NULL, NULL, 'JPROFILE:HAVECHILD');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (13, 'MTONGUE', 'dropdown', 'dropdown_req', 14, 'Mother Tongue', NULL, NULL, 'JPROFILE:MTONGUE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (14, 'RELIGION', 'dropdown', 'dropdown_req', 11, 'Religion', NULL, NULL, 'JPROFILE:RELIGION');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (15, 'CASTE', 'dropdown', 'caste', 14, 'Caste', NULL, NULL, 'JPROFILE:CASTE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (16, 'SOURCE', 'hidden', 'string', NULL, '', NULL, NULL, 'JPROFILE:SOURCE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (17, 'RECORD_ID', 'hidden', 'string', NULL, '', NULL, NULL, 'NO_TABLE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (18, 'PHONE_MOB', 'mobile', 'mobile', 19, 'Mobile Number', NULL, NULL, 'JPROFILE:ISD-isd,PHONE_MOB-mobile');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (19, 'ISD', 'text', 'string', 9, '', NULL, NULL, '');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (20, 'STD', 'text', 'string', NULL, '', NULL, NULL, '');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (21, 'PHONE_RES', 'landline', 'landline', NULL, 'LandLine Number', NULL, NULL, 'JPROFILE:ISD-isd,STD-std,PHONE_RES-landline');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (22, 'PROMO', 'checkbox', 'string', NULL, '', NULL, NULL, 'JPROFILE:PROMO');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (23, 'TERMSANDCONDITIONS', 'hidden', 'string', NULL, '', NULL, NULL, 'NO_TABLE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (24, 'DIET', 'radio', 'dropdown_not_req', NULL, 'Diet', NULL, NULL, 'JPROFILE:DIET');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (25, 'SMOKE', 'radio', 'dropdown_not_req', NULL, 'Smoke', NULL, NULL, 'JPROFILE:SMOKE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (26, 'DRINK', 'radio', 'dropdown_not_req', NULL, 'Drink', NULL, NULL, 'JPROFILE:DRINK');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (27, 'COMPLEXION', 'radio', 'dropdown_not_req', NULL, 'Complexion', NULL, NULL, 'JPROFILE:COMPLEXION');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (28, 'BTYPE', 'radio', 'dropdown_not_req', 0, 'Body Type', NULL, NULL, 'JPROFILE:BTYPE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (30, 'OCCUPATION', 'dropdown', 'dropdown_req', NULL, 'Work Area*', NULL, NULL, 'JPROFILE:OCCUPATION');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (31, 'MANGLIK', 'radio', 'dropdown_not_req', NULL, 'Manglik', NULL, NULL, '');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (32, 'HANDICAPPED', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, '');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (33, 'AGE', 'dropdown', 'string', NULL, '', NULL, NULL, '');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (34, 'INCOME', 'dropdown', 'dropdown_req', NULL, 'Annual Income*', NULL, NULL, 'JPROFILE:INCOME');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (35, 'EDU_LEVEL_NEW', 'dropdown', 'dropdown_req', NULL, 'Highest Degree*', NULL, NULL, 'JPROFILE:EDU_LEVEL_NEW');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (36, 'CASTE_HIDDEN', 'hidden', 'string', NULL, 'Caste Hidden', NULL, NULL, '');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (37, 'RES_STATUS', 'dropdown', 'string', NULL, 'Resident Status', NULL, NULL, 'JPROFILE:RES_STATUS');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (38, 'YOURINFO', 'textarea', 'yourinfo', NULL, 'Write about your Education Work Family', NULL, NULL, 'JPROFILE:YOURINFO');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (39, 'EDUCATION', 'textarea', 'string', NULL, 'Educational Background', NULL, NULL, 'JPROFILE:EDUCATION');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (40, 'JOB_INFO', 'textarea', 'string', NULL, 'Professional Background', NULL, NULL, 'JPROFILE:JOB_INFO');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (41, 'WORK_STATUS', 'dropdown', 'string', NULL, 'Work Status', NULL, NULL, 'JPROFILE:WORK_STATUS');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (42, 'HANDICAPPED', 'dropdown', 'string', NULL, 'Challenged', NULL, NULL, 'JPROFILE:HANDICAPPED');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (43, 'BLOOD_GROUP', 'dropdown', 'string', NULL, 'Blood Group', NULL, NULL, 'JPROFILE:BLOOD_GROUP');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (44, 'HIV', 'radio', 'dropdown_not_req', NULL, 'HIV', NULL, NULL, 'JPROFILE:HIV');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (45, 'CONTACT', 'textarea', 'string', NULL, 'Your Contact Address', NULL, NULL, 'JPROFILE:CONTACT');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (46, 'MESSENGER_ID', 'text', 'messenger_id', NULL, 'Messenger ID', NULL, NULL, 'JPROFILE:MESSENGER_ID');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (47, 'SHOWMESSENGER', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JPROFILE:SHOWMESSENGER');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (48, 'SHOWADDRESS', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JPROFILE:SHOWADDRESS');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (49, 'MESSENGER_CHANNEL', 'dropdown', 'messenger_channel', NULL, 'Messenger Channel', NULL, NULL, 'JPROFILE:MESSENGER_CHANNEL');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (50, 'P_LAGE', 'dropdown', 'string', NULL, 'Age', NULL, NULL, 'JPARTNER:P_LAGE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (51, 'P_HAGE', 'dropdown', 'partner_age', NULL, '', NULL, NULL, 'JPARTNER:P_HAGE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (52, 'P_LHEIGHT', 'dropdown', 'string', NULL, 'Height', NULL, NULL, 'JPARTNER:P_LHEIGHT');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (53, 'P_HHEIGHT', 'dropdown', 'partner_height', NULL, '', NULL, NULL, 'JPARTNER:P_HHEIGHT');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (54, 'P_LRS', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPARTNER:P_LRS');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (55, 'P_HRS', 'dropdown', 'partner_rupee', NULL, '', NULL, NULL, 'JPARTNER:P_HRS');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (56, 'P_LDS', 'dropdown', 'string', NULL, 'Annual Income', NULL, NULL, 'JPARTNER:P_LDS');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (57, 'P_HDS', 'dropdown', 'partner_dollar', NULL, '', NULL, NULL, 'JPARTNER:P_HDS');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (58, 'NATURE_HANDICAP', 'dropdown', 'string', NULL, 'Nature of handicap', NULL, NULL, 'JPROFILE:NATURE_HANDICAP');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (59, 'F_AGE', 'checkbox', 'string', NULL, 'check Age filter is set or not', NULL, NULL, 'FILTERS:AGE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (60, 'F_MSTATUS', 'checkbox', 'string', NULL, 'check Mstatus filter is set or not', NULL, NULL, 'FILTERS:MSTATUS');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (61, 'F_RELIGION', 'checkbox', 'string', NULL, 'check RELIGION filter is set or not', NULL, NULL, 'FILTERS:RELIGION');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (62, 'F_CASTE', 'checkbox', 'string', NULL, 'check CASTE filter is set or not', NULL, NULL, 'FILTERS:CASTE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (63, 'F_COUNTRY_RES', 'checkbox', 'string', NULL, 'check SOUNTRY_RES filter is set or not', NULL, NULL, 'FILTERS:COUNTRY_RES');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (64, 'F_CITY_RES', 'checkbox', 'string', NULL, 'check CITY_RES filter is set or not', NULL, NULL, 'FILTERS:CITY_RES');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (65, 'F_MTONGUE', 'checkbox', 'string', NULL, 'check MTONGUE filter is set or not', NULL, NULL, 'FILTERS:MTONGUE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (66, 'F_INCOME', 'checkbox', 'string', NULL, 'check INCOME filter is set or not', NULL, NULL, 'FILTERS:INCOME');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (67, 'NAME_OF_USER', 'text', 'string', NULL, '', NULL, NULL, 'NAME_OF_USER');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (68, 'SAMPRADAY', 'dropdown', 'string', NULL, 'Sampraday', NULL, NULL, 'JP_JAIN:SAMPRADAY');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (69, 'FAMILY_VALUES', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JPROFILE:FAMILY_VALUES');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (70, 'FAMILY_TYPE', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JPROFILE:FAMILY_TYPE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (71, 'FAMILY_STATUS', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JPROFILE:FAMILY_STATUS');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (72, 'FAMILY_BACK', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPROFILE:FAMILY_BACK');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (73, 'MOTHER_OCC', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPROFILE:MOTHER_OCC');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (74, 'T_BROTHER', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPROFILE:T_BROTHER');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (75, 'M_BROTHER', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPROFILE:M_BROTHER');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (76, 'T_SISTER', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPROFILE:T_SISTER');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (77, 'M_SISTER', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPROFILE:M_SISTER');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (78, 'PARENT_CITY_SAME', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JPROFILE:PARENT_CITY_SAME');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (79, 'FAMILYINFO', 'textarea', 'string', NULL, '', NULL, NULL, 'JPROFILE:FAMILYINFO');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (80, 'SUBCASTE', 'text', 'string', NULL, '', NULL, NULL, 'JPROFILE:SUBCASTE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (81, 'GOTHRA', 'text', 'string', NULL, '', NULL, NULL, 'JPROFILE:GOTHRA');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (82, 'MANGLIK', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JPROFILE:MANGLIK');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (83, 'RASHI', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPROFILE:RASHI');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (84, 'ANCESTRAL_ORIGIN', 'text', 'string', NULL, '', NULL, NULL, 'JPROFILE:ANCESTRAL_ORIGIN');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (85, 'NAKSHATRA', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPROFILE:NAKSHATRA');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (86, 'AMRITDHARI', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_SIKH:AMRITDHARI');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (87, 'CUT_HAIR', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_SIKH:CUT_HAIR');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (88, 'TRIM_BEARD', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_SIKH:TRIM_BEARD');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (89, 'WEAR_TURBAN', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_SIKH:WEAR_TURBAN');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (90, 'CLEAN_SHAVEN', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_SIKH:CLEAN_SHAVEN');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (91, 'HOROSCOPE_MATCH', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JPROFILE:HOROSCOPE_MATCH');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (92, 'MATHTHAB', 'dropdown', 'string', NULL, '', NULL, NULL, 'JP_MUSLIM:MATHTHAB');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (93, 'NAMAZ', 'dropdown', 'string', NULL, '', NULL, NULL, 'JP_MUSLIM:NAMAZ');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (94, 'FASTING', 'dropdown', 'string', NULL, '', NULL, NULL, 'JP_MUSLIM:FASTING');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (95, 'ZAKAT', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_MUSLIM:ZAKAT');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (96, 'QURAN', 'dropdown', 'string', NULL, '', NULL, NULL, 'JP_MUSLIM:QURAN');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (97, 'UMRAH_HAJJ', 'dropdown', 'string', NULL, '', NULL, NULL, 'JP_MUSLIM:UMRAH_HAJJ');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (98, 'SUNNAH_BEARD', 'dropdown', 'string', NULL, '', NULL, NULL, 'JP_MUSLIM:SUNNAH_BEARD');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (99, 'SUNNAH_CAP', 'dropdown', 'string', NULL, '', NULL, NULL, 'JP_MUSLIM:SUNNAH_CAP');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (100, 'HIJAB', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_MUSLIM:HIJAB');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (101, 'HIJAB_MARRIAGE', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_MUSLIM:HIJAB_MARRIAGE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (102, 'WORKING_MARRIAGE', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_MUSLIM:WORKING_MARRIAGE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (103, 'SPEAK_URDU', 'checkbox', 'string', NULL, '', NULL, NULL, 'JPROFILE:SPEAK_URDU');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (104, 'DIOCESE', 'text', 'string', NULL, '', NULL, NULL, 'JP_CHRISTIAN:DIOCESE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (105, 'BAPTISED', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_CHRISTIAN:BAPTISED');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (107, 'READ_BIBLE', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_CHRISTIAN:READ_BIBLE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (108, 'OFFER_TITHE', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_CHRISTIAN:OFFER_TITHE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (109, 'SPREADING_GOSPEL', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_CHRISTIAN:SPREADING_GOSPEL');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (110, 'ZARATHUSHTRI', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_PARSI:ZARATHUSHTRI');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (111, 'PARENTS_ZARATHUSHTRI', 'radio', 'dropdown_not_req', NULL, '', NULL, NULL, 'JP_PARSI:PARENTS_ZARATHUSHTRI');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (113, 'SPOUSE', 'textarea', 'string', NULL, '', NULL, NULL, 'JPROFILE:SPOUSE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (114, 'REG_ID', 'hidden', 'string', NULL, '', NULL, NULL, 'NO_TABLE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (115, 'SHOWPHONE', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPROFILE:SHOWPHONE_RES');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (116, 'SHOWMOBILE', 'dropdown', 'string', NULL, '', NULL, NULL, 'JPROFILE:SHOWPHONE_MOB');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (117, 'FAMILY_INCOME', 'dropdown', 'dropdown_not_req', NULL, 'Family Income', NULL, NULL, 'JPROFILE:FAMILY_INCOME');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (118, 'NATIVE_COUNTRY', 'dropdown', 'dropdown_not_req', NULL, '', NULL, NULL, 'NATIVE_PLACE:NATIVE_COUNTRY');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (119, 'NATIVE_STATE', 'dropdown', 'native_place', NULL, '', NULL, NULL, 'NATIVE_PLACE:NATIVE_STATE');
INSERT INTO `USER_PROFILE_FIELDS` VALUES (120, 'NATIVE_CITY', 'dropdown', 'native_place', NULL, '', NULL, NULL, 'NATIVE_PLACE:NATIVE_CITY');
