use MOBILE_API;
CREATE TABLE `DEEP_LINKING_TRACKING` (
 `ID` int(7) unsigned NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(8) NOT NULL,
 `LOGGEDIN_PID` int(8) DEFAULT NULL,
 `DATETIME` datetime NOT NULL,
 `FLAG` char(2) NOT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=latin1
