use matchalerts;
	CREATE TABLE `LOW_TRENDS_MATCHALERTS_CHECK` (
 `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `DATE` date NOT NULL,
 `LOGICLEVEL` smallint(6) NOT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=MyISAM;



use MATCHALERT_TRACKING;

CREATE TABLE  `MATCH_ALERT_DATA_BY_LOGIC` (
 `SNO` MEDIUMINT NOT NULL AUTO_INCREMENT ,
 `DATE` DATE NOT NULL ,
 `LOGICLEVEL` SMALLINT NOT NULL ,
 `COUNT` INT NOT NULL ,
PRIMARY KEY (  `SNO` ) ,
UNIQUE (
`DATE` ,
`LOGICLEVEL`
)
)ENGINE=MYISAM;


CREATE TABLE `MATCH_ALERT_BYLOGIC_TOTAL` (
 `SNO` int(11) NOT NULL AUTO_INCREMENT,
 `DATE` DATE NOT NULL,
 `TOTALCOUNT` int(11) NOT NULL DEFAULT '0',
 PRIMARY KEY (`SNO`)
) ENGINE=MYISAM;


CREATE TABLE  `MATCH_ALERT_DATA_BY_LOGIC_RECOMMEND` (
 `SNO` INT NOT NULL AUTO_INCREMENT ,
 `DATE` DATE NOT NULL ,
 `LOGICLEVEL` SMALLINT NOT NULL ,
 `RECOMMEDCOUNT` INT NOT NULL ,
 `PIDCOUNT` INT DEFAULT  '0' NOT NULL ,
PRIMARY KEY (  `SNO` ) ,
UNIQUE (
`DATE` ,
`LOGICLEVEL` ,
`RECOMMEDCOUNT`
)
) ENGINE=MYISAM;


CREATE TABLE `MATCH_ALERT_DATA_BY_LOGIC_RECOMMEND_TOTAL` (
 `SNO` int(11) NOT NULL AUTO_INCREMENT,
 `DATE` date NOT NULL,
 `RECOMMENDCOUNT` mediumint(9) NOT NULL,
 `TOTALCOUNT` int(11) NOT NULL,
 PRIMARY KEY (`SNO`)
) ENGINE=MYISAM;
