use matchalerts;

CREATE TABLE `LOW_DPP_MATCHALERTS_CHECK` (
 `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `DATE` datetime NOT NULL,
 `SENT` char(1) DEFAULT 'N',
 PRIMARY KEY (`ID`)
) ENGINE=MYISAM AUTO_INCREMENT=26 DEFAULT CHARSET=latin1
