use REGISTER;

INSERT INTO  `USER_PROFILE_FIELDS` (  `ID` ,  `FIELD_NAME` ,  `TYPE` ,  `CONSTRAINT_CLASS` ,  `DEPENDENT_FIELD` ,  `LABEL` ,  `BLANK_VALUE` ,  `BLANK_LABEL` ,  `TABLE_NAME` ) 
VALUES (
'',  'COLLEGE',  'text',  'string', NULL ,  '', NULL , NULL ,  'JPROFILE_EDUCATION:COLLEGE'
), (
'',  'PG_COLLEGE',  'text',  'string', NULL ,  '', NULL , NULL ,  'JPROFILE_EDUCATION:PG_COLLEGE'
);

INSERT INTO  `USER_PROFILE_FIELDS` (  `ID` ,  `FIELD_NAME` ,  `TYPE` ,  `CONSTRAINT_CLASS` ,  `DEPENDENT_FIELD` ,  `LABEL` ,  `BLANK_VALUE` ,  `BLANK_LABEL` ,  `TABLE_NAME` ) 
VALUES (
'',  'DEGREE_PG',  'dropdown',  'dropdown_not_req', NULL ,  '', NULL , NULL ,  'JPROFILE_EDUCATION:PG_DEGREE'
), (
'',  'DEGREE_UG',  'dropdown',  'dropdown_not_req', NULL ,  '', NULL , NULL ,  'JPROFILE_EDUCATION:UG_DEGREE'
);

INSERT INTO  `USER_PROFILE_FIELDS` (  `ID` ,  `FIELD_NAME` ,  `TYPE` ,  `CONSTRAINT_CLASS` ,  `DEPENDENT_FIELD` ,  `LABEL` ,  `BLANK_VALUE` ,  `BLANK_LABEL` ,  `TABLE_NAME` ) 
VALUES (
'',  'OTHER_PG_DEGREE',  'text',  'string', NULL ,  '', NULL , NULL ,  'JPROFILE_EDUCATION:OTHER_PG_DEGREE'
), (
'',  'OTHER_UG_DEGREE',  'text',  'string', NULL ,  '', NULL , NULL ,  'JPROFILE_EDUCATION:OTHER_UG_DEGREE'
);
