CREATE DATABASE IF NOT EXISTS PROFILE;
USE PROFILE;
CREATE TABLE  `PROFILE_COMPLETION_SCORE` (
 `PROFILEID` INT( 11 ) UNSIGNED NOT NULL ,
 `SCORE` SMALLINT( 3 ) UNSIGNED NOT NULL ,
PRIMARY KEY (  `PROFILEID` )
)ENGINE=MYISAM;