use PROFILE;
	CREATE TABLE `TRACKIDFYPROFILES` (
 `SNO` mediumint(9) NOT NULL AUTO_INCREMENT,
 `DATE` datetime NOT NULL,
 `PROFILEID` int(11) NOT NULL,
 `EMAIL` varchar(100) NOT NULL,
 PRIMARY KEY (`SNO`)
) ENGINE=InnoDB;