use newjs;


CREATE TABLE  `FILTERS_LOG` (
 `PROFILEID` INT( 11 ) UNSIGNED NOT NULL ,
 `FILTERID` INT( 11 ) NOT NULL ,
 `AGE` CHAR( 1 ) NOT NULL,
 `MSTATUS` CHAR( 1 ) NOT NULL,
 `RELIGION` CHAR( 1 ) NOT NULL,
 `CASTE` CHAR( 1 ) NOT NULL ,
 `COUNTRY_RES` CHAR( 1 ) NOT NULL,
 `CITY_RES` CHAR( 1 ) NOT NULL ,
 `MTONGUE` CHAR( 1 ) NOT NULL,
 `INCOME` CHAR( 1 ) NOT NULL ,
 `COUNT` SMALLINT( 6 ) NOT NULL,
 `HARDSOFT` CHAR( 1 ) NOT NULL,
 `MOD_DT` DATETIME DEFAULT NULL ,
PRIMARY KEY ( PROFILEID, MOD_DT )
)ENGINE=InnoDB;

DELIMITER |

CREATE trigger INSERT_FILTERS 
AFTER INSERT ON FILTERS
FOR EACH ROW 
BEGIN

           INSERT into newjs.FILTERS_LOG(PROFILEID,FILTERID,AGE,MSTATUS,RELIGION,CASTE,COUNTRY_RES,CITY_RES,MTONGUE,INCOME,COUNT,HARDSOFT,MOD_DT) SELECT PROFILEID,FILTERID,AGE,MSTATUS,RELIGION,CASTE,COUNTRY_RES,CITY_RES,MTONGUE,INCOME,COUNT,HARDSOFT,NOW() FROM FILTERS where PROFILEID=new.PROFILEID; 
END;
|

DELIMITER ;

DELIMITER |

CREATE trigger UPDATE_FILTERS 
AFTER UPDATE ON FILTERS
FOR EACH ROW 
BEGIN

           INSERT into newjs.FILTERS_LOG(PROFILEID,FILTERID,AGE,MSTATUS,RELIGION,CASTE,COUNTRY_RES,CITY_RES,MTONGUE,INCOME,COUNT,HARDSOFT,MOD_DT) SELECT PROFILEID,FILTERID,AGE,MSTATUS,RELIGION,CASTE,COUNTRY_RES,CITY_RES,MTONGUE,INCOME,COUNT,HARDSOFT,NOW() FROM FILTERS where PROFILEID=new.PROFILEID; 
END;
|

DELIMITER ;