CREATE TABLE  `ALBUM_VIEW_LOGGING` (
 `ID` INT( 10 ) NOT NULL AUTO_INCREMENT ,
 `VIEWER_ID` INT( 10 ) NOT NULL ,
 `VIEWED_ID` INT( 10 ) NOT NULL ,
 `DATETIME` DATETIME NOT NULL ,
 `CHANNEL` VARCHAR( 2 ) NOT NULL ,
PRIMARY KEY (  `ID` )
)ENGINE=MYISAM;
