use PROFILE_VERIFICATION;

	CREATE TABLE `AADHAR_VERIFICATION` (
 `PROFILEID` int(11) unsigned NOT NULL,
 `USERNAME` varchar(40) NOT NULL,
 `DATE` datetime NOT NULL,
 `AADHAR_NO` bigint(15) unsigned NOT NULL,
 `REQUEST_ID` varchar(60) NOT NULL,
 `VERIFY_STATUS` char(1)  DEFAULT 'N',
 PRIMARY KEY (`PROFILEID`),
 UNIQUE KEY `AADHAR_NO` (`AADHAR_NO`)
) ENGINE=InnoDB;