use PROFILE:
CREATE TABLE `PROFILE`.`EDIT_LOG_UNIQUE_IDS` (
  `PROFILEID` INT(11) UNSIGNED NOT NULL,
  `PORTING_DONE` ENUM('Y','N') NOT NULL DEFAULT 'N',
  PRIMARY KEY (`PROFILEID`)
);


INSERT INTO `PROFILE`.`EDIT_LOG_UNIQUE_IDS` (`PROFILEID`) SELECT DISTINCT PROFILEID FROM `newjs`.`EDIT_LOG` ORDER BY PROFILEID ASC
