use MIS;

CREATE TABLE  `REG_TRACK_CHANNEL` (
 `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
 `PROFILEID` INT( 11 ) UNSIGNED,
 `PAGE_TYPE` VARCHAR( 15 ) ,
 `ENTRY_DT` DATETIME,
 `CHANNEL` ENUM(  "Desktop",  "MS",  "NewMS",  "Android",  "Ios",  "Offline" ) ,
PRIMARY KEY (  `ID` ) ,
UNIQUE (
 `PROFILEID` ,
 `PAGE_TYPE`
)
);


