use newjs;
CREATE TABLE `CRITICAL_INFO_CHANGED` (
`ID` INT( 11 ) NOT NULL AUTO_INCREMENT ,
`PROFILEID` INT( 11 ) NOT NULL ,
`EDITED_FIELDS` VARCHAR( 50 ) NOT NULL ,
`DATE` DATETIME NOT NULL ,
PRIMARY KEY ( `ID` ) ,
UNIQUE (
`PROFILEID`
)
);
CREATE TABLE `CRITICAL_INFO_CHANGED_DOCS` (
`ID` INT( 11 ) NOT NULL AUTO_INCREMENT ,
`PROFILEID` INT( 11 ) NOT NULL ,
`DOCUMENT_PATH` VARCHAR( 255 ) NOT NULL ,
`SCREENED_STATUS` ENUM( 'N', 'Y', 'F' ) DEFAULT 'N' NOT NULL ,
`UPLOADED_ON` DATETIME NOT NULL ,
PRIMARY KEY ( `ID` ) ,
UNIQUE (
`PROFILEID`
)
);