use MATCHALERT_TRACKING;

CREATE TABLE `MATCHALERT_FEEDBACK` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `REASON1` varchar(255) NOT NULL,
 `REASON1_TEXT` text NOT NULL,
 `REASON2` varchar(255) NOT NULL,
 `SUGGESTION_TEXT` text NOT NULL,
 `MA_DATE` datetime NOT NULL,
 `STYPE` varchar(5) NOT NULL,
 `FEEDBACK_ON` datetime NOT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
CREATE TABLE `MATCHALERT_FEEDBACK_REASONS` (
  `ID` int(11) NOT NULL,
  `REASON_ID` int(11) NOT NULL,
  `REASON_TEXT` varchar(255) NOT NULL,
  UNIQUE KEY `ID` (`ID`,`REASON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- 
-- Dumping data for table `MATCHALERT_FEEDBACK_REASONS`
-- 

INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (1, 1, 'They don''t match my partner preference as specified in my ''Desired Partner Profile''');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (1, 2, 'Matches recommended are repetitive');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (1, 3, 'They match my partner preference as specified on my ''Desired Partner Profiles'', but I still find them irrelevant (specify reason)');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (2, 1, 'AGE');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (2, 2, 'Height');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (2, 3, 'Marital Status');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (2, 4, 'Location');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (2, 5, 'Income');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (2, 6, 'Education');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (2, 7, 'Occupation');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (2, 8, 'Manglik');
INSERT INTO `MATCHALERT_FEEDBACK_REASONS` VALUES (2, 9, 'Photo');
        