use jeevansathi_mailer;
INSERT INTO  `LINK_MAILERS` (  `LINKID` ,  `APP_SCREEN_ID` ,  `LINK_NAME` ,  `LINK_URL` ,  `OTHER_GET_PARAMS` ,  `REQUIRED_AUTOLOGIN` ,  `OUTER_LINK` ) 
VALUES (
'', NULL ,  'SAVED_SEARCH',  'search/perform', NULL ,  'Y',  'N'
);

use search;
CREATE TABLE  `send_saved_search_mail` (
 `RECEIVER` INT( 11 ) UNSIGNED DEFAULT  '0',
 `USER1` INT( 11 ) UNSIGNED DEFAULT  '0',
 `USER2` INT( 11 ) UNSIGNED DEFAULT  '0',
 `USER3` INT( 11 ) UNSIGNED DEFAULT  '0',
 `USER4` INT( 11 ) UNSIGNED DEFAULT  '0',
 `USER5` INT( 11 ) UNSIGNED DEFAULT  '0',
 `USER6` INT( 11 ) UNSIGNED DEFAULT  '0',
 `USER7` INT( 11 ) UNSIGNED DEFAULT  '0',
 `USER8` INT( 11 ) UNSIGNED DEFAULT  '0',
 `USER9` INT( 11 ) UNSIGNED DEFAULT  '0',
 `USER10` INT( 11 ) UNSIGNED DEFAULT  '0',
 `SNO` MEDIUMINT( 11 ) NOT NULL AUTO_INCREMENT ,
 `SEARCH_NAME` VARCHAR( 30 ) NOT NULL ,
 `SENT` VARCHAR( 1 ) NOT NULL DEFAULT  'N',
 `SEARCH_ID` INT( 11 ) UNSIGNED NOT NULL ,
PRIMARY KEY (  `SNO` ) ,
UNIQUE KEY  `SEARCH_ID` (  `SEARCH_ID` )
) ENGINE=MyISAM DEFAULT CHARSET = latin1
