USE matchalerts;
CREATE TABLE `TwoWayVsDppCount` (
`id` INT( 11 ) NOT NULL AUTO_INCREMENT ,
`PROFILEID` INT( 11 ) NOT NULL ,
`ENTRY_DT` DATETIME NOT NULL ,
`CNT` TINYINT( 5 ) DEFAULT '0',
PRIMARY KEY ( `id` ) ,
UNIQUE (
`PROFILEID`
)
)ENGINE=MyISAM;
