use PROFILE;
CREATE TABLE `SHARE_PROFILE` (
 `PROFILEID` int(11) NOT NULL,
 `TIME` datetime NOT NULL,
 `COUNT` smallint(6) NOT NULL,
 PRIMARY KEY (`PROFILEID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

