USE PROFILE;
CREATE TABLE  JUNK_CHARACTER_TEXT (
 id INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT ,
 PROFILEID INT( 11 ) UNSIGNED NOT NULL ,
 original_text TEXT DEFAULT NULL ,
 modified_custom TEXT DEFAULT NULL ,
 modified_automate ENUM(  'JUNK',  'NOT_JUNK' ) DEFAULT NULL ,
PRIMARY KEY (  id )
) ENGINE = MYISAM ;