use PROFILE;
CREATE TABLE `VERIFICATION_DOCUMENTS` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `ID_PROOF_TYPE` enum('ID','ADDR') DEFAULT NULL,
 `PROOF_VAL` varchar(200) DEFAULT NULL,
 `PROOF_TYPE` char(1) DEFAULT NULL,
 `DELETED_FLAG` enum('Y','N') NOT NULL DEFAULT 'N',
 PRIMARY KEY (`id`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`ID_PROOF_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Stores Verification Documents uploaded from PD'
