use reg;

CREATE TABLE `LOG_REG_HITS` (
 `ID` bigint(32) unsigned NOT NULL AUTO_INCREMENT,
 `URL` varchar(255) NOT NULL,
 `ACTUAL_IP` varchar(50) DEFAULT NULL,
 `REPORTED_IP` varchar(50) DEFAULT NULL,
 `ENTRY_DT` datetime NOT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=MYISAM DEFAULT CHARSET=latin1;
