use newjs;
CREATE TABLE `SWAP_JPROFILE_LOGIN_DT` (
 `PROFILEID` int(11) unsigned NOT NULL,
 `SORT_DT` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `LAST_LOGIN_DT` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `SWAP_JPROFILE_LOGIN_DT1` (
 `PROFILEID` int(11) unsigned NOT NULL,
 `SORT_DT` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `LAST_LOGIN_DT` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TRIGGER UPDATE_SWAP;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
/*!40101 SET @collation_connection    = @@collation_connection */;
/*!40101 SET collation_connection = utf8 */;
delimiter # 
CREATE DEFINER=`root`@`localhost` TRIGGER UPDATE_SWAP AFTER UPDATE ON JPROFILE FOR EACH ROW BEGIN IF(@DONT_UPDATE_TRIGGER is NULL) THEN IF (old.LAST_LOGIN_DT  != new.LAST_LOGIN_DT) THEN REPLACE into newjs.SWAP_JPROFILE_LOGIN_DT set PROFILEID=new.PROFILEID,LAST_LOGIN_DT=new.LAST_LOGIN_DT,SORT_DT=new.SORT_DT; ELSE INSERT ignore into newjs.SWAP_JPROFILE set PROFILEID=new.PROFILEID; END IF; END IF;  REPLACE INTO test.JPROFILE_FOR_DUPLICATION (PROFILEID,BTIME,GENDER,MTONGUE,RELIGION,MSTATUS,CASTE,DTOFBIRTH,COUNTRY_RES,CITY_RES,COUNTRY_BIRTH,CITY_BIRTH,EDU_LEVEL_NEW,INCOME,AGE,LAST_LOGIN_DT,HEIGHT) VALUES (new.PROFILEID,new.BTIME,new.GENDER,new.MTONGUE,new.RELIGION,new.MSTATUS,new.CASTE,new.DTOFBIRTH,new.COUNTRY_RES,new.CITY_RES,new.COUNTRY_BIRTH,new.CITY_BIRTH,new.EDU_LEVEL_NEW,new.INCOME,new.AGE,new.LAST_LOGIN_DT,new.HEIGHT);  IF (old.INCOMPLETE !='Y' AND new.INCOMPLETE = 'Y') THEN INSERT INTO test.incomplete_profile_logging SELECT * from newjs.JPROFILE  where PROFILEID = new.PROFILEID; END IF; END;#
delimiter ;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET collation_connection = @collation_connection */;