USE REGISTER;
ALTER TABLE  `REGISTRATION_QUALITY` ADD  `OTHERS_COMMUNITY` MEDIUMINT( 9 ) DEFAULT 0 AFTER  `SCREENED_SIC`;
ALTER TABLE  `REGISTRATION_QUALITY` ADD  `SCREENED_CC` MEDIUMINT( 9 )  DEFAULT 0 AFTER  `SCREENED_SIC`;

CREATE TABLE `SOURCE_CATEGORY_MAPPING` (
  `SOURCE_GROUP` varchar(255) DEFAULT NULL,
  `SOURCE_ID` varchar(20) DEFAULT NULL,
  `SOURCE_CATEGORY` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Total', '', 'Total');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('iOSApp', '', 'Direct ios');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('MobileApp', '', 'Direct AA');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('jeevansathi', '', 'Direct PC');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('SEO_COM_PAGE_L2', '', 'Direct PC');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('mobiledirect', '', 'Direct MS');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('SEO_COM_PAGE_L1', '', 'Direct PC');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('SEO_COM_SP_L1', '', 'Direct PC');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Google_nri', '', 'Google_nri');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('YSM mobile', '', 'YSM mobile');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Yahoosearch_2008', '', 'Yahoosearch_2008');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Lucini', '', 'Lucini');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('rediff_mailer_amj_09', '', 'rediff_mailer_amj_09');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('bandhan_may10', '', 'bandhan_may10');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Tyroo_AMJ@120', '', 'Tyroo_AMJ@120');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Amarujala', '', 'Amarujala');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Innoexcel', '', 'Innoexcel');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Silverpush', '', 'Silverpush');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('SMX CPC', '', 'SMX CPC');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('SenseDigital_2015', '', 'SenseDigital_2015');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Sense Digital Ph Verified CPL', '', 'Sense Digital Ph Verified CPL');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Lucini_F', '', 'Lucini_F');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('NBT_CPC', '', 'NBT_CPC');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Opicle', '', 'Opicle');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Innovativelead', '', 'Innovativelead');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Facebook', '', 'Facebook');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('others', '', 'others');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('unknown', '', 'unknown');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('LuviaGlobal', '', 'LuviaGlobal');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Fork Media', '', 'Fork Media');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('optimedia', '', 'optimedia');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Adcanopus', '', 'Adcanopus');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('Goventures', '', 'Goventures');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('icube', '', 'icube');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Hindi May 09', 'google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Marathi May 09', 'google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Punjabi May 09', 'google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'marry59', 'google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Prof', 'google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mobile Brand', 'google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'hindi brand MS', 'google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'punjabi59', 'google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'marathi59', 'google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'hindikwds', 'google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'm_marry59', 'MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'm_prof', 'MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'h_marry59', 'MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Bengali May 09', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Tamil May 09', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Default May 09', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Christian May 09', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Gujarati May 09', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Malayalee May 09', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Muslim May 09', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Telugu May 09', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Kannada May 09', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'oriya59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'sindhi59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'brahmin59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'kayastha59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'kwdlesscampaign', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'display campaign opt', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'gmail', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'default', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'remarketing', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'remarket2', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'default59a', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'default59b', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'hindiform', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'punjabiform', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'marathiform', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'nonbrand59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'content59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_hindi', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_punjabi', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_gujarati', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_brand', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_general', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_oriya', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_marathi', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_nri', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_competition', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_citywise', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_profession', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'community59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 's_hindi', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 's_gujarati', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'content delhi', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'delhi59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'hindi Keywords', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'marathi keywords', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'competition59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Agar-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Agar-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Bnia-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Brah-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Brah-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Bride-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Del-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Del-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Groom-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Kays-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Kays-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Ksya-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Ksha-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Ksha-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mrat-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mrat-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Punj-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Punj-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Punjabi-Kya-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Hindi-Bania-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Hind-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Hind-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Bnia-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Rajp-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Rajp-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Khat-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Khat-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mara-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mara-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Jat-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Jat-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Aror-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Aror-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'non brand exp', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Budh-B-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Budh-G-Rtg', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Home Page Bouce- for', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Demo Target', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Demo_Exp', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Topic', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'C_Managed', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'New Competition', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Home Page RTG', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Retargeting Youtube', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Look A Like', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Youtube Pre-Roll', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Hindi Keywords Conte', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Comp Mobile', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_hindikey', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'hindi59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'default59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'comp59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'bengali59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'tamil59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'JS_Exclusive', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'kannada59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'dis_cam_op', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'remarketin', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'muslim59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'c_mcontent', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'telugu59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'similar', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'gujarati59', 'Rest_ google_custom');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mobile Non-Brand', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mobile Profession', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'm_Miscellaneous', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mobile Exp Non Brand', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mobile GDN', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mobile c_jeevansathi', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mobile Community', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'Mobile Content', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'm_nb59', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'm_c_brand', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'm_c_hindi', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'm_commu', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'M_COMP59', 'Rest_ MobileSEM');
INSERT INTO `SOURCE_CATEGORY_MAPPING` VALUES ('', 'mobile_JS_Exclusive', 'Rest_ MobileSEM');


USE MIS;

INSERT INTO `MIS_MAINPAGE` VALUES (116, 'City/Community/Source wise Quality Registration', '/operations.php/registerMis/communitywiseRegistration?cid=$cid', NULL, 'P+MG', 'Y', '');
