use newjs;

UPDATE newjs.EDUCATION_LEVEL_NEW SET SORTBY=SORTBY+1 WHERE SORTBY>=28

INSERT INTO newjs.EDUCATION_LEVEL_NEW (ID,LABEL,VALUE,OLD_VALUE,SORTBY,GROUPING) VALUES('43','MDS','43','5','28','2')
