use REGISTER;
CREATE TABLE `REG_QUALITY_ACTIVATED` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `PROFILE_ID` int(11) unsigned NOT NULL,
  `DATE_OF_ENTRY` date,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROFILE_ID` (`PROFILE_ID`)
);