use viewSimilar;

CREATE TABLE `VSP_MAILER_PROFILES_TO_BE_SENT` (
 `SNO` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `IS_CALCULATED` enum('N','Y') NOT NULL,
 `USER1` int(11) NOT NULL,
 `USER2` int(11) DEFAULT NULL,
 `USER3` int(11) DEFAULT NULL,
 `USER4` int(11) DEFAULT NULL,
 `USER5` int(11) DEFAULT NULL,
 `INTERESTS_SENT` smallint(6) NOT NULL,
 `TYPE` char(1) NOT NULL,
 PRIMARY KEY (`SNO`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM;


CREATE TABLE `MAILER` (
 `SNO` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL,
 `USER1` int(11) NOT NULL,
 `USER2` int(11) DEFAULT NULL,
 `USER3` int(11) DEFAULT NULL,
 `USER4` int(11) DEFAULT NULL,
 `USER5` int(11) DEFAULT NULL,
 `USER6` int(11) DEFAULT NULL,
 `USER7` int(11) DEFAULT NULL,
 `USER8` int(11) DEFAULT NULL,
 `USER9` int(11) DEFAULT NULL,
 `USER10` int(11) DEFAULT NULL,
 `USER11` int(11) DEFAULT NULL,
 `USER12` int(11) DEFAULT NULL,
 `USER13` int(11) DEFAULT NULL,
 `USER14` int(11) DEFAULT NULL,
 `USER15` int(11) DEFAULT NULL,
 `USER16` int(11) DEFAULT NULL,
 `USER17` int(11) DEFAULT NULL,
 `USER18` int(11) DEFAULT NULL,
 `USER19` int(11) DEFAULT NULL,
 `USER20` int(11) DEFAULT NULL,
 `SENT` char(1) NOT NULL,
 `INTERESTS_SENT` smallint(6) NOT NULL,
 `TYPE` char(1) NOT NULL,
 PRIMARY KEY (`SNO`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM;