use newjs;
ALTER TABLE  `JPROFILE_CONTACT` ADD  `ALT_EMAIL` VARCHAR( 100 ) ,
ADD  `ALT_EMAIL_STATUS` VARCHAR( 1 ) DEFAULT 'N' ;

CREATE TABLE `ALT_EMAIL_LOG` (
 `PROFILEID` int(11) NOT NULL,
 `ALT_EMAIL` varchar(100) NOT NULL,
 `MOD_DT` datetime NOT NULL
);