use matchalerts;
ALTER TABLE `MATCHALERTS_TO_BE_SENT` ADD `COMMUNITY_ELIGIBLE` ENUM( 'N', 'Y', 'E' ) DEFAULT 'N' NOT NULL ;
ALTER TABLE `MATCHALERTS_TO_BE_SENT_REG` ADD `COMMUNITY_ELIGIBLE` ENUM( 'N', 'Y', 'E' ) DEFAULT 'N' NOT NULL ;