use newjs;


CREATE TABLE `FILTERS_LOG` (
 `PROFILEID` int(11) unsigned NOT NULL DEFAULT '0',
 `FILTERID` int(11) NOT NULL AUTO_INCREMENT,
 `AGE` char(1) NOT NULL DEFAULT '',
 `MSTATUS` char(1) NOT NULL DEFAULT '',
 `RELIGION` char(1) NOT NULL DEFAULT '',
 `CASTE` char(1) NOT NULL,
 `COUNTRY_RES` char(1) NOT NULL DEFAULT '',
 `CITY_RES` char(1) NOT NULL,
 `MTONGUE` char(1) NOT NULL DEFAULT '',
 `INCOME` char(1) NOT NULL,
 `COUNT` smallint(6) NOT NULL DEFAULT '0',
 `HARDSOFT` char(1) NOT NULL DEFAULT 'N',
 `MOD_DT` datetime DEFAULT NULL,
 PRIMARY KEY (`FILTERID`),
 UNIQUE KEY `PROFILEID_2` (`PROFILEID`),
 KEY `PROFILEID` (`PROFILEID`)
) ENGINE=InnoDB

DELIMITER |

CREATE trigger INSERT_FILTERS 
AFTER INSERT ON FILTERS
FOR EACH ROW 
BEGIN

           INSERT into newjs.FILTERS_LOG(PROFILEID,FILTERID,AGE,MSTATUS,RELIGION,CASTE,COUNTRY_RES,CITY_RES,MTONGUE,INCOME,COUNT,HARDSOFT,MOD_DT) SELECT PROFILEID,FILTERID,AGE,MSTATUS,RELIGION,CASTE,COUNTRY_RES,CITY_RES,MTONGUE,INCOME,COUNT,HARDSOFT,NOW() FROM FILTERS where PROFILEID=new.PROFILEID; 
END;
|

DELIMITER ;

DELIMITER |

CREATE trigger UPDATE_FILTERS 
AFTER UPDATE ON FILTERS
FOR EACH ROW 
BEGIN

           INSERT into newjs.FILTERS_LOG(PROFILEID,FILTERID,AGE,MSTATUS,RELIGION,CASTE,COUNTRY_RES,CITY_RES,MTONGUE,INCOME,COUNT,HARDSOFT,MOD_DT) SELECT PROFILEID,FILTERID,AGE,MSTATUS,RELIGION,CASTE,COUNTRY_RES,CITY_RES,MTONGUE,INCOME,COUNT,HARDSOFT,NOW() FROM FILTERS where PROFILEID=new.PROFILEID; 
END;
|

DELIMITER ;