use newjs;

CREATE TABLE  `HIDDEN_DELETED_PROFILES` (
	`PROFILEID` INT( 11 ) UNSIGNED NOT NULL ,
	`LAST_UPDATED` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	 PRIMARY KEY (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
