use PICTURE;
CREATE TABLE `PROCESS_INTERFACE_UPLOAD_TRACKING` (
`SNO` INT( 5 ) UNSIGNED NOT NULL AUTO_INCREMENT ,
`LOAD_TIME_MS` INT( 11 ) UNSIGNED NOT NULL ,
`SIZE` INT( 11 ) UNSIGNED NOT NULL ,
PRIMARY KEY ( `SNO` )
) ENGINE=MyISAM;
	
