use newjs;
ALTER TABLE `SWAP` CHANGE `EDUCATION_GROUPING` `EDUCATION_GROUPING` VARCHAR( 20 ) DEFAULT NULL;
ALTER TABLE `SEARCH_FEMALE` CHANGE `EDUCATION_GROUPING` `EDUCATION_GROUPING` VARCHAR( 20 ) DEFAULT NULL;
ALTER TABLE `SEARCH_MALE` CHANGE `EDUCATION_GROUPING` `EDUCATION_GROUPING` VARCHAR( 20 ) DEFAULT NULL;
