use MIS;
CREATE TABLE SOURCE_BKP  AS (SELECT * FROM SOURCE);

CREATE TABLE PIXELCODE_BKP  AS (SELECT * FROM PIXELCODE);

CREATE TABLE `PIXELCODE_NEW` (
 `GROUPNAME` varchar(255) NOT NULL,
 `PIXELCODE` text NOT NULL,
 `PAGEID` varchar(20) NOT NULL,
 `REPLACEMENT` varchar(2) NOT NULL,
 `CONDITION` varchar(80) NOT NULL,
 `STATUS` varchar(1) NOT NULL,
 PRIMARY KEY (`GROUPNAME`)
);

INSERT INTO `PIXELCODE_NEW` VALUES ('', '<!-- Google Code for lead Conversion Page -->\r\n\r\n<script type="text/javascript">\r\n\r\n/* <![CDATA[ */\r\n\r\nvar google_conversion_id = 968376783;\r\n\r\nvar google_conversion_language = "en";\r\n\r\nvar google_conversion_format = "2";\r\n\r\nvar google_conversion_color = "ffffff";\r\n\r\nvar google_conversion_label = "37pJCJH_0AIQz4PhzQM";\r\n\r\nvar google_conversion_value = 0;\r\n\r\n/* ]]> */\r\n\r\n</script>\r\n\r\n<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n\r\n</script>\r\n\r\n<noscript>\r\n\r\n<div style="display:inline;">\r\n\r\n<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/968376783/?label=37pJCJH_0AIQz4PhzQM&amp;guid=ON&amp;script=0"/>\r\n\r\n</div>\r\n\r\n</noscript>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Adchakra_AMJ09', '<script type=''text/javascript''><!--//<![CDATA[\r\n    var p=location.protocol==''https:''?''https:'':''http:'';\r\n    var r=Math.floor(Math.random()*999999);\r\n    document.write ("<" + "script language=''JavaScript'' ");\r\n    document.write ("type=''text/javascript'' src=''"+p);\r\n    document.write ("//ads.adchakra.net/www/delivery/tjs.php");\r\n    document.write ("?trackerid=2&amp;r="+r+"''><" + "\\/script>");\r\n//]]>--></script><noscript><div id=''m3_tracker_2'' style=''position: absolute; left: 0px; top: 0px; visibility: \r\n\r\nhidden;''><img src=''http://ads.adchakra.net/www/delivery/ti.php?trackerid=2&amp;cb=%%RANDOM_NUMBER%%'' \r\n\r\nwidth=''0'' height=''0'' alt='''' /></div></noscript>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Adchakra_AMJ11', '<!-- Begin ZEDO --> \r\n<iframe src = "http://c1.zedo.com/up/1287/400083/n.html" frameborder=0 marginheight=0 marginwidth=0 scrolling="no" allowTransparency="true" ></iframe>\r\n<!-- End ZEDO -->', '', '', '', 'D');
INSERT INTO `PIXELCODE_NEW` VALUES ('Admagnet', '<script type=''text/javascript''>\r\n    var p=location.protocol==''https:''?''https://n.admagnet.net/c/js/'':''http://n.admagnet.net/c/js/'';\r\n    var r=Math.floor(Math.random()*999999);\r\n    document.write ("<" + "script language=''JavaScript'' ");\r\n    document.write ("type=''text/javascript'' src=''"+p);\r\n    document.write ("?trackerid=733&amp;r="+r+"''><" + "/script>");\r\n</script><noscript><div id=''m3_tracker_733'' style=''position: absolute; left: 0px; top: 0px; visibility: hidden;''><img src=''http://n.admagnet.net/c/vi/?trackerid=733&amp;adid=&amp;cb=%%RANDOM_NUMBER%%'' width=''0'' height=''0'' alt='''' /></div></noscript>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('bandhan_may10', '<img src="http://www.bandhan.com/jstrack.jsp?profileid=~$USERNAME`">', 'JSPCR4', '1', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('cloveindia', '<iframe src="http://www.clovedirect.com/livetracking_clovedirectpixel.php?cid=1091&id=<!-- Clove Direct SUBID -->&advid=<!-- ADVSUBID or CustomerID -->&optionalinfo=<!-- OPTIONALINFO HERE -->" frameborder="0" width="1" height="1"></iframe>\r\n\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('DGM_80cpa_Feb09', '        <img height="1" width="3" src="http://www.s2d6.com/x/?x=a&amp;h=17773&amp;o=$USERNAME" alt=""/>\r\n        <img height="1" width="3" src="http://www.s2d6.com/x/?x=r&amp;h=17773&amp;o=$USERNAME&amp;g=158411869957&amp;s=0&amp;q=1"/>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('DGM_amj_08_cpa', '<img height="1" width="3" src="http://www.s2d6.com/x/?x=s&amp;h=17773&amp;o=ORDERID&amp;s=0.00" alt="" />', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('DGM_JFM13', '<iframe src ="https://pixel.affcamp.co.in/jeevansathi.php?o=~$PROFILEID`&g=registration " width="0" height="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>', '', '', '', 'D');
INSERT INTO `PIXELCODE_NEW` VALUES ('DGM_NRI_Feb09', '        <img height="1" width="3" src="http://www.s2d6.com/x/?x=a&amp;h=17773&amp;o=$USERNAME" alt=""/>\r\n        <img height="1" width="3" src="http://www.s2d6.com/x/?x=r&amp;h=17773&amp;o=$USERNAME&amp;g=429378795544&amp;s=0&amp;q=1"/>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('DrivePM_NRI_JFM09', '<img src="http://switch.atdmt.com/action/Jeevansathi_NRI_Confirm_Feb09" height="1" width="1">', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('DrivePM_RI_JFM09', '<img src="http://switch.atdmt.com/action/Jeevansathi_RI_Confirm_Feb09" height="1" width="1">', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('facebook', '<script>(function() {\r\nvar _fbq = window._fbq || (window._fbq = []);\r\nif (!_fbq.loaded) {\r\nvar fbds = document.createElement(''script'');\r\nfbds.async = true;\r\nfbds.src = ''//connect.facebook.net/en_US/fbds.js'';\r\nvar s = document.getElementsByTagName(''script'')[0];\r\ns.parentNode.insertBefore(fbds, s);\r\n_fbq.loaded = true;\r\n}\r\n_fbq.push([''addPixelId'', ''569447716516417'']);\r\n})();\r\nwindow._fbq = window._fbq || [];\r\nwindow._fbq.push([''track'', ''PixelInitialized'', {}]);\r\n</script>\r\n<noscript><img height=""1"" width=""1"" alt="""" style=""display:none"" src=""https://www.facebook.com/tr?id=569447716516417&amp;ev=PixelInitialized"" /></noscript>', 'JSPCR4', '', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('facebook_nov10', '<!-- Facebook Conversion Code for Jeevansathi_Registration -->\r\n<script>(function() {\r\nvar _fbq = window._fbq || (window._fbq = []);\r\nif (!_fbq.loaded) {\r\nvar fbds = document.createElement(''script'');\r\nfbds.async = true;\r\nfbds.src = ''//connect.facebook.net/en_US/fbds.js'';\r\nvar s = document.getElementsByTagName(''script'')[0];\r\ns.parentNode.insertBefore(fbds, s);\r\n_fbq.loaded = true;\r\n}\r\n})();\r\nwindow._fbq = window._fbq || [];\r\nwindow._fbq.push([''track'', ''6024985072280'', {''value'':''0.00'',''currency'':''INR''}]);\r\n</script>\r\n<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6024985072280&amp;cd[value]=0.00&amp;cd[currency]=INR&amp;noscript=1" /></noscript>\r\n', '', '', '', 'N');
INSERT INTO `PIXELCODE_NEW` VALUES ('Glispa_sep11', '<script src="http://ads.glispa.com/lead_third/3140/OPTIONAL_INFORMATION"></script><noscript><img src="http://ads.glispa.com/track_lead/3140/OPTIONAL_INFORMATION"></noscript>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('google hindi', '<!-- Google Code for 2 page conversion Conversion Page -->\r\n<script type="text/javascript">\r\n/* <![CDATA[ */\r\nvar google_conversion_id = 970747267;\r\nvar google_conversion_language = "en";\r\nvar google_conversion_format = "1";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "nn0zCKWytwMQg9vxzgM";\r\nvar google_conversion_value = 0;\r\n/* ]]> */\r\n</script>\r\n<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<div style="display:inline;">\r\n<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/970747267/?label=nn0zCKWytwMQg9vxzgM&amp;guid=ON&amp;script=0"/>\r\n</div>\r\n</noscript>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('google marathi', '<!-- Google Code for 2 page conversion Conversion Page -->\r\n<script type="text/javascript">\r\n/* <![CDATA[ */\r\nvar google_conversion_id = 969738306;\r\nvar google_conversion_language = "en";\r\nvar google_conversion_format = "1";\r\nvar google_conversion_color = "000000";\r\nvar google_conversion_label = "D_P6CIap9wIQwpC0zgM";\r\nvar google_conversion_value = 0;\r\n/* ]]> */\r\n</script>\r\n<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<div style="display:inline;">\r\n<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969738306/?label=D_P6CIap9wIQwpC0zgM&amp;guid=ON&amp;script=0"/>\r\n</div>\r\n</noscript>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Google NRI US', '<!-- Google Code for Registration Conversion Page -->\r\n<script language="JavaScript" type="text/javascript">\r\n<!--\r\nvar google_conversion_id = 1046502896;\r\nvar google_conversion_language = "en_US";\r\nvar google_conversion_format = "3";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "k-_UCLKkiQEQ8LuB8wM";\r\n//-->\r\n</script>\r\n<script language="JavaScript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<img height="1" width="1" border="0" src="http://www.googleadservices.com/pagead/conversion/1046502896/?label=k-_UCLKkiQEQ8LuB8wM&amp;guid=ON&amp;script=0"/>\r\n</noscript>                <!-- Google Code for lead Conversion Page -->\r\n                <script language="JavaScript" type="text/javascript">\r\n                        var google_conversion_id = 1046502896;\r\n                        var google_conversion_language = "en_US";\r\n                        var google_conversion_format = "1";\r\n                        var google_conversion_color = "666666";\r\n                        if (1)\r\n                        {\r\n                                var google_conversion_value = 1;\r\n                        }\r\n                        var google_conversion_label = "lead";\r\n                </script>\r\n\r\n                <script language="JavaScript" src="http://www.googleadservices.com/pagead/conversion.js"></script>\r\n                <noscript>\r\n                        <img height="1" width="1" border="0" src="http://www.googleadservices.com/pagead/conversion/1046502896/imp.gif?value=1&amp;label=lead&amp;script=0" />\r\n                </noscript>\r\n\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('google punjabi', '<!-- Google Code for 2 page registration Conversion Page -->\r\n<script type="text/javascript">\r\n/* <![CDATA[ */\r\nvar google_conversion_id = 969127741;\r\nvar google_conversion_language = "en";\r\nvar google_conversion_format = "1";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "QflvCLOEigMQve6OzgM";\r\nvar google_conversion_value = 0;\r\n/* ]]> */\r\n</script>\r\n<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<div style="display:inline;">\r\n<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969127741/?label=QflvCLOEigMQve6OzgM&amp;guid=ON&amp;script=0"/>\r\n</div>\r\n</noscript>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('google_custom', '<!-- Google Code for Convert Conversion Page -->\r\n<script type="text/javascript">\r\n/* <![CDATA[ */\r\nvar google_conversion_id = 1056682264;\r\nvar google_conversion_language = "en";\r\nvar google_conversion_format = "2";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "BBBVCLCkwwEQmOLu9wM";\r\nvar google_conversion_value = 1.00;\r\nvar google_conversion_currency = "INR";\r\nvar google_remarketing_only = false;\r\n/* ]]> */\r\n</script>\r\n<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<div style="display:inline;">\r\n<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1056682264/?value=1.00&amp;currency_code=INR&amp;label=BBBVCLCkwwEQmOLu9wM&amp;guid=ON&amp;script=0"/>\r\n</div>\r\n</noscript>\r\n', 'JSPCR4', '', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('Google_JS5_Punjabi', '<!-- Google Code for Registration Conversion Page -->\r\n<script type="text/javascript">\r\n/* <![CDATA[ */\r\nvar google_conversion_id = 969127741;\r\nvar google_conversion_language = "en";\r\nvar google_conversion_format = "2";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "8nKVCOvqggMQve6OzgM";\r\nvar google_conversion_value = 0;\r\n/* ]]> */\r\n</script>\r\n<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<div style="display:inline;">\r\n<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969127741/?label=8nKVCOvqggMQve6OzgM&amp;guid=ON&amp;script=0"/>\r\n</div>\r\n</noscript>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('google_js6', '<!-- Google Code for lead Conversion Page -->\r\n\r\n<script type="text/javascript">\r\n\r\n/* <![CDATA[ */\r\n\r\nvar google_conversion_id = 968376783;\r\n\r\nvar google_conversion_language = "en";\r\n\r\nvar google_conversion_format = "2";\r\n\r\nvar google_conversion_color = "ffffff";\r\n\r\nvar google_conversion_label = "37pJCJH_0AIQz4PhzQM";\r\n\r\nvar google_conversion_value = 0;\r\n\r\n/* ]]> */\r\n\r\n</script>\r\n\r\n<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n\r\n</script>\r\n\r\n<noscript>\r\n\r\n<div style="display:inline;">\r\n\r\n<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/968376783/?label=37pJCJH_0AIQz4PhzQM&amp;guid=ON&amp;script=0"/>\r\n\r\n</div>\r\n\r\n</noscript>\r\n\r\n\r\n<!-- Google Code for lead Conversion Page -->\r\n<script type="text/javascript">\r\n/* <![CDATA[ */\r\nvar google_conversion_id = 974052043;\r\nvar google_conversion_language = "en";\r\nvar google_conversion_format = "2";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "hJFSCP3O0QIQy7W70AM";\r\nvar google_conversion_value = 0;\r\n/* ]]> */\r\n</script>\r\n<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<div style="display:inline;">\r\n<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/974052043/?label=hJFSCP3O0QIQy7W70AM&amp;guid=ON&amp;script=0"/>\r\n</div>\r\n</noscript>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Google_mobile', '<!-- Google Code for Mobile Lead Conversion Page -->\r\n<script type="text/javascript">\r\n/* <![CDATA[ */\r\nvar google_conversion_id = 1056682264;\r\nvar google_conversion_language = "en";\r\nvar google_conversion_format = "1";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "8IxQCNSi6gMQmOLu9wM";\r\nvar google_conversion_value = 0;\r\n/* ]]> */\r\n</script>\r\n<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<div style="display:inline;">\r\n<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1056682264/?value=0&amp;label=8IxQCNSi6gMQmOLu9wM&amp;guid=ON&amp;script=0"/>\r\n</div>\r\n</noscript>\r\n', '', '', '', 'D');
INSERT INTO `PIXELCODE_NEW` VALUES ('Google_NRI', '<!-- Google Code for Registration Conversion Page -->\r\n<script type="text/javascript">\r\n/* <![CDATA[ */\r\nvar google_conversion_id = 1046502896;\r\nvar google_conversion_language = "en_US";\r\nvar google_conversion_format = "3";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "k-_UCLKkiQEQ8LuB8wM";\r\nvar google_conversion_value = 1.00;\r\nvar google_conversion_currency = "INR";\r\nvar google_remarketing_only = false;\r\n/* ]]> */\r\n</script>\r\n<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<div style="display:inline;">\r\n<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1046502896/?value=1.00&amp;currency_code=INR&amp;label=k-_UCLKkiQEQ8LuB8wM&amp;guid=ON&amp;script=0"/>\r\n</div>\r\n</noscript>\r\n', 'JSPCR4', '', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('I4C_May09_RI', '<!-- Google Code for Lead Conversion Page -->\r\n<script language="JavaScript" type="text/javascript">\r\n<!--\r\nvar google_conversion_id = 1033995319;\r\nvar google_conversion_language = "en_US";\r\nvar google_conversion_format = "1";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "4WmECO-QlAEQt4iG7QM";\r\n//-->\r\n</script>\r\n<script language="JavaScript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<img height="1" width="1" border="0" src="http://www.googleadservices.com/pagead/conversion/1033995319/?label=4WmECO-QlAEQt4iG7QM&amp;guid=ON&amp;script=0"/>\r\n</noscript>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Ibibo_amj_08_cpa', '<script type="text/javascript">\r\n/*<![CDATA[*/\r\nOAS_rn = new String (Math.random());\r\nOAS_rns = OAS_rn.substring (2, 11);\r\ndocument.write(''<img alt="" SRC="http://oasc07.247realmedia.com/RealMedia/ads/adstream.track/1''+OAS_rns+''?XE&epmAccountKey=1167&epmXTransKey=60&epmXtransStep=999&epmXtransCategory=&epmXtransItem=&epmXtransQuantity=&epmXTransRevenue=&XE" [^] style="width:0px;height:0px;border:none" />'');\r\n/*]]>*/\r\n</script>\r\n<IMG SRC="http://www.adwinks.in/track_lead/217/$USERNAME">', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('ibibo_JAS2011', '<div id=''m3_tracker_132'' style=''position: absolute; left: 0px; top: 0px; visibility: hidden;''><img src=''http://ads.ibibo.com/ad/www/delivery/ti.php?trackerid=132&amp;Profile_ID=~$USERNAME`&amp;city=~$CITY`&amp;cb=%%RANDOM_NUMBER%%'' width=''0'' height=''0'' alt='''' /></div>', '', '', '', 'D');
INSERT INTO `PIXELCODE_NEW` VALUES ('Ibibo_JFM09_NRI', '<IMG SRC="http://www.adwinks.in/track_lead/218/$USERNAME">', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('IBIBO_July10', '<div id=''m3_tracker_132'' style=''position: absolute; left: 0px; top: 0px; visibility: hidden;''><img src=''http://ads.ibibo.com/ad/www/delivery/ti.php?trackerid=132&amp;Profile_ID=%%PROFILE_ID_VALUE%%&amp;cb=%%RANDOM_NUMBER%%'' width=''0'' height=''0'' alt='''' /></div>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('IndianRail_Sep08_CPA', '<SCRIPT language="JavaScript">\r\n<!--\r\nvar RN = new String (Math.random());\r\nvar RNS = RN.substring (2,11);\r\ndocument.write(''<iframe src="http://adstil.indiatimes.com/RealMedia/ads/adstream_sx.ads/www.timesofindia.com/homepage/1''+RNS+''@x91?" WIDTH=1 HEIGHT=1 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0 scrolling=no bordercolor="000000"> </iframe>'')\r\n//-->\r\n</SCRIPT>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('India_Today_AMJ12', '<!-- Begin ZEDO -->\r\n<script language="JavaScript" type="text/javascript">\r\nvar zzp=new Image();\r\nif (location.protocol == "https:") {\r\nzzp.src="https://ss1.zedo.com/ads2/t?o=450876;h=1443276;z="+Math.random();\r\n} else {\r\nzzp.src="http://xads.zedo.com/ads2/t?o=450876;h=1443276;z="+Math.random();\r\n}\r\n</script>\r\n<!-- End ZEDO -->\r\n"<!-- Begin ZEDO -->\r\n<script language="JavaScript" type="text/javascript">\r\nvar zzp=new Image();\r\nif (location.protocol == "https:") {\r\nzzp.src="https://ss1.zedo.com/ads2/t?o=450876;h=1443276;z="+Math.random();\r\n} else {\r\nzzp.src="http://xads.zedo.com/ads2/t?o=450876;h=1443276;z="+Math.random();\r\n}\r\n</script>\r\n<!-- End ZEDO -->"\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Innoexcel', '<img src="https://innoexcel.oneffect.us/affiliate/track/363/[TRACK_ID]/" \r\nheight="1" width="1" />\r\n', '', '', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('Integrid_CPA_08', '<!-- Advertiser ''91  Naukri'',  Include user in segment ''Jeevansathi'' â€“ DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n                <img src="http://ad.adserverplus.com/pixel?id=99680&amp;t=2" width="1" height="1" />\r\n                <!-- End of segment tag -->', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('komli_amj_08_cpa', '<script src="http://partners.komli.com/lead_third/10009/~$USERNAME`"></script>\r\n<noscript><img src="http://partners.komli.com/track_lead/10009/~$USERNAME`"></noscript>\r\n', 'JSPCR4', '1', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('Komli_CPC', 'Not Secure (Http://) Pixel\r\n********************************\r\n\r\n<script type="text/javascript" src="http://http://trk.atomex.net/cgi-bin/tracker.fcgi/conv?px=10272&ty=1"></script>\r\n\r\n\r\nNot Secure (Https://) Pixel\r\n********************************\r\n\r\n<script type="text/javascript" src="https://http://trk.atomex.net/cgi-bin/tracker.fcgi/conv?px=10272&ty=1"></script>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Komli_NRI_JFM09', '        <!-- Advertiser ''Infoedge - IN'',  Include user in conversion ''Feb 09 Jeevansathi.com NRI'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n        <script src="http://ads.komli.com/pixel?id=316805&t=1" type="text/javascript"></script>\r\n        <!-- End of conversion tag -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('mediaturf', '                <!--Enhance Conversion Tracking (Lead) -->\r\n                <img src="http://c.enhance.com/t?cid=1059840&amp;filltype=5 " width="1" height="1" border="0" />\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('mediaturf_aug_2008', '<iframe src="http://adchakra.net/tracking/jeevansathi/pixel_tracking.htm" frameborder="0" height="1" width="1" scrolling="no" ></iframe>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('MobileSEM', '<!-- Google Code for Convert Conversion Page -->\r\n<script type="text/javascript">\r\n/* <![CDATA[ */\r\nvar google_conversion_id = 1056682264;\r\nvar google_conversion_language = "en";\r\nvar google_conversion_format = "2";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "BBBVCLCkwwEQmOLu9wM";\r\nvar google_conversion_value = 1.00;\r\nvar google_conversion_currency = "INR";\r\nvar google_remarketing_only = false;\r\n/* ]]> */\r\n</script>\r\n<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<div style="display:inline;">\r\n<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1056682264/?value=1.00&amp;currency_code=INR&amp;label=BBBVCLCkwwEQmOLu9wM&amp;guid=ON&amp;script=0"/>\r\n</div>\r\n</noscript>\r\n', 'JSPCR4', '', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('NBT_CPC', '<!-- Activity name for this tag: Adtech_Jeevansathi -->\r\n<script type=''text/javascript''>\r\nvar axel = Math.random()+"";\r\nvar a = axel * 10000000000000;\r\ndocument.write(''<img src="http://pubads.g.doubleclick.net/activity;xsp=187059;ord=''+ a +''?" width=1 height=1 border=0/>'');\r\n</script>\r\n<noscript>\r\n<img src="http://pubads.g.doubleclick.net/activity;xsp=187059;ord=1?" width=1 height=1 border=0/>\r\n</noscript>\r\n', 'JSPCR4', '', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('networkplay_NRI@275_amj11', '<script src="http://ads.networkplay.in/lead_third/14/OPTIONAL_INFORMATION"></script>\r\n<noscript><img src="http://ads.networkplay.in/track_lead/14/OPTIONAL_INFORMATION"></noscript>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('networkplay_RI@125_amj11', '<script src="http://ads.networkplay.in/lead_third/13/~$USERNAME`"></script>\r\n<noscript><img src="http://ads.networkplay.in/track_lead/13/~$USERNAME`"></noscript>\r\n', '', '', '', 'D');
INSERT INTO `PIXELCODE_NEW` VALUES ('networkplay_RI@175_amj11', '<script src="http://ads.networkplay.in/lead_third/13/OPTIONAL_INFORMATION"></script>\r\n<noscript><img src="http://ads.networkplay.in/track_lead/13/OPTIONAL_INFORMATION"></noscript>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('New Google', '<!-- Google Code for Registration Conversion Page -->\r\n<script language="JavaScript" type="text/javascript">\r\n<!--\r\nvar google_conversion_id = 1056682264;\r\nvar google_conversion_language = "en_US";\r\nvar google_conversion_format = "3";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "JjZuCLyLiQEQmOLu9wM";\r\n//-->\r\n</script>\r\n<script language="JavaScript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<img height="1" width="1" border="0" src="http://www.googleadservices.com/pagead/conversion/1056682264/?label=JjZuCLyLiQEQmOLu9wM&amp;guid=ON&amp;script=0"/>\r\n</noscript>\r\n', '', '', '', 'D');
INSERT INTO `PIXELCODE_NEW` VALUES ('new_google_structure', '<!-- Google Code for Registration Conversion Page -->\r\n<script language="JavaScript" type="text/javascript">\r\n<!--\r\nvar google_conversion_id = 1039085133;\r\nvar google_conversion_language = "en_US";\r\nvar google_conversion_format = "3";\r\nvar google_conversion_color = "ffffff";\r\nvar google_conversion_label = "j58PCKPIdxDN3LzvAw";\r\n//-->\r\n</script>\r\n<script language="JavaScript" src="http://www.googleadservices.com/pagead/conversion.js">\r\n</script>\r\n<noscript>\r\n<img height="1" width="1" border="0" src="http://www.googleadservices.com/pagead/conversion/1039085133/?label=j58PCKPIdxDN3LzvAw&amp;guid=ON&amp;script=0"/>\r\n</noscript>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Nexzenpro', '<!-- Offer Conversion: Jeevansathi  -->\r\n<img src="http://nexzenpro.go2cloud.org/SL5K" width="1" height="1" />\r\n<!-- // End Offer Conversion -->', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('ozonemedia_AMJ_09_RI', '<!-- Advertiser ''Jeevansathi Ind'',  Conversion tracking ''Jeevansathi Ind Leads'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=1197290&t=2" width="1" height="1" />\r\n<!-- End of conversion tag -->', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Ozonemedia_AMJ_2010', '<!-- Advertiser ''Jeevansathi Ind'',  Conversion tracking ''Jeevansathi Leads'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<script src="http://ad.yieldmanager.com/pixel?id=1197290&t=1" type="text/javascript"></script>\r\n<!-- End of conversion tag -->', '', '', '', 'N');
INSERT INTO `PIXELCODE_NEW` VALUES ('Ozonemedia_AMJ_2010_NRI', '<!-- Conversion Pixel - JS_NRI_Pixel - DO NOT MODIFY -->\r\n<script src="http://ads.ozonemedia.com/px?id=29617&t=1" type="text/javascript"></script>\r\n<!-- End of Conversion Pixel -->', '', '', '', 'D');
INSERT INTO `PIXELCODE_NEW` VALUES ('ozonemedia_aug_2008', '<!-- xxxxx Tracking code - OzoneMedia -->\r\n<img width="1" height="1" src="http://ads.ozonemedia.co.in/TrackAction/ADVID=233"/>\r\n<!-- End xxxxxx Code -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('ozonemedia_JFM_09_nri', '<!-- Begin Action Tracking code - OzoneMedia  -->\r\n<script language="JavaScript" type="text/javascript">\r\nvar zzp=new Image();\r\nif (location.protocol == "https:") {\r\nzzp.src="https://tt1.zedo.com/ads2/t?o=227533;h=847471;z="+Math.random();\r\n} else {\r\nzzp.src="http://yads.zedo.com/ads2/t?o=227533;h=847471;z="+Math.random();\r\n}\r\n</script>\r\n<!-- End Action Tracking Code - OzoneMedia -->\r\n\r\n<!-- xxxxx  Tracking code - OzoneMedia -->\r\n\r\n\r\n<img width="1" height="1" src="http://ads.ozonemedia.co.in/TrackAction/ADVID=233"/>\r\n\r\n\r\n<!-- End xxxxxx Code -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('PrecisionMatch_JAS13', '<!-- Google Tag Manager -->\r\n<<script>\r\n        dataLayer = [{\r\n            ''AdvId'': ''ADVNC169'', ''ADVNC169_PageType'':''Thank-you''\r\n        }];\r\n      </script>\r\n<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-KTMRSJ"\r\nheight="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>\r\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({''gtm.start'':\r\nnew Date().getTime(),event:''gtm.js''});var f=d.getElementsByTagName(s)[0],\r\nj=d.createElement(s),dl=l!=''dataLayer''?''&l=''+l:'''';j.async=true;j.src=\r\n''//www.googletagmanager.com/gtm.js?id=''+i+dl;f.parentNode.insertBefore(j,f);\r\n})(window,document,''script'',''dataLayer'',''GTM-KTMRSJ'');</script>\r\n<!-- End Google Tag Manager -->\r\n', '', '', '', 'N');
INSERT INTO `PIXELCODE_NEW` VALUES ('Shoogloo_Jul10', '<script src="http://partners.shoogloonetwork.com/lead_third/29/~$PROFILEID`"></script>\r\n\r\n<noscript><img src="http://partners.shoogloonetwork.com/track_lead/29/~$PROFILEID`"></noscript>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Silverpush', '<NOSCRIPT><img src="https://pix.silverpush.co/checkout?cid={CID}&pubid={PUB_ID}&rid=~$RID`&txnid={TXNID}” style=”display:none”></NOSCRIPT>', 'JSPCR4', '2', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('SMX CPC', '<iframe src="http://smxindia.in/p.ashx?a=133&t=TRANSACTION_ID" height="1" width="1" frameborder="0"></iframe>', 'JSPCR4', '', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tribal@90_June09', '<img src=''http://a.tribalfusion.com/ti.ad?client=301103&ev=1'' width=''1'' height=''1'' border=''0''>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tribal@CPA90_June09', '<img src=''http://a.tribalfusion.com/ti.ad?client=286403&ev=1'' width=''1'' height=''1'' border=''0''>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tribalfusion_JS_NRI_feb09', '<img src=''http://a.tribalfusion.com/ti.ad?client=301103&ev=1'' width=''1'' height=''1'' border=''0''>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('TribalFusion_OND08_CPA@90', '<img src=''http://a.tribalfusion.com/ti.ad?client=286403&ev=1'' width=''1'' height=''1'' border=''0''>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tribal_JAS13', '<img src=''http://a.tribalfusion.com/ti.ad?client=286403&ev=1'' width=''1'' height=''1'' border=''0''>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tribal_NRI_ 506_Jan11', '<img src=''http://a.tribalfusion.com/ti.ad?client=301103&ev=1'' width=''1'' height=''1'' border=''0''>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tyroo_AMJ@120_OLD', '<script src="http://affiliates.tyroodr.com/lead_third/77/~$USERNAME`,~$AGE`,~$GENDER`,~$CITY`"></script>\r\n\r\n<noscript><img src="http://affiliates.tyroodr.com/track_lead/77/~$USERNAME`,~$AGE`,~$GENDER`,~$CITY`"></noscript>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tyroo_amj_CPA', '<!-- Advertiser ''JeevanSathi'' -->\r\n<script src="http://ext.tyroo.com/pixel?id=112686&t=1" type="text/javascript"></script>\r\n<!-- End of conversion tag -->\r\n<!-- Advertiser ''JeevanSathi'',  Include user in segment ''Jeevansathi Tyroo conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ext.tyroo.com/pixel?id=112686&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->\r\n', '', '', '', 'D');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tyroo_India_JFM08', '<script type="text/javascript" src="http://tq.tyroo.com:8080/acquire/tyr_aqui.js"></script>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tyroo_NRI_JFM08', '<script type="text/javascript" src="http://tq.tyroo.com:8080/acquire/tyr_aqui.js"></script>', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tyroo_NRI_JFM09', '<!-- Advertiser ''Jeevansathi NRI Feb'',  Include user in conversion ''Jeevansathi NRI Conversion Pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<script src="http://ext.tyroo.com/pixel?id=316458&t=1" type="text/javascript"></script>\r\n<!-- End of conversion tag -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('VCommission_May10', '<!-- Offer Conversion: Jeevansathi CPL -->\r\n<iframe src="https://tracking.vcommission.com/SL1t2?adv_sub=SUB_ID" scrolling="no" frameborder="0" width="1" height="1"></iframe>\r\n<!-- // End Offer Conversion -->', 'JSPCR4', '', 'AGE_F22_M25|CITY', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('Vizury_AMJ13_OLD', '<iframe src="http://www.vizury.com/analyze/analyze.php?account_id=VIZVRM782&param=e500&orderid=&orderprice=&pid1=&catid1=&quantity1=&price1=&pid2=&catid2=&quantity2=&price2=&pid3=&catid3=&quantity3=&price3=&currency=&section=1&level=1" scrolling="no" width="1" height="1" marginheight="0" marginwidth="0" frameborder="0"></iframe>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('wchutney', '                <script language="JavaScript" src="http://www.webchutney.net/chutneytrack/js/iqtracker.js"></script>\r\n                <script language="JavaScript">\r\n                        var clntid = "JVNSTHI";\r\n                        trackThisPage();\r\n                </script>\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo display', '<script type="application/javascript">(function(w,d,t,r,u){w[u]=w[u]||[];w[u].push({''projectId'':''10001619333563'',''properties'':{''pixelId'':''405264''}});var s=d.createElement(t);s.src=r;s.async=true;s.onload=s.onreadystatechange=function(){var y,rs=this.readyState,c=w[u];if(rs&&rs!="complete"&&rs!="loaded"){return}try{y=YAHOO.ywa.I13N.fireBeacon;w[u]=[];w[u].push=function(p){y([p])};y(c)}catch(e){}};var scr=d.getElementsByTagName(t)[0],par=scr.parentNode;par.insertBefore(s,scr)})(window,document,"script","https://s.yimg.com/wi/ytc.js","dotq");</script>', '', '', '', 'N');
INSERT INTO `PIXELCODE_NEW` VALUES ('yahooCPA@100_Oct08_dCPM', '<!-- Advertiser ''INFO EDGE INDIA PVT. LTD'', Include user in segment ''706910_1x1 pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=225428&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('YahooCPA@105Retargeting_June09', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('YahooCPA@105_June09', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('YahooCPA@90Retargeting_June09', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('YahooCPA@90_June09', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('yahooCPA@90_Sep08', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('yahoosearch_2008', '<script type="application/javascript">(function(w,d,t,r,u){w[u]=w[u]||[];w[u].push({''projectId'':''10001619333563'',''properties'':{''pixelId'':''15043''}});var s=d.createElement(t);s.src=r;s.async=true;s.onload=s.onreadystatechange=function(){var y,rs=this.readyState,c=w[u];if(rs&&rs!="complete"&&rs!="loaded"){return}try{y=YAHOO.ywa.I13N.fireBeacon;w[u]=[];w[u].push=function(p){y([p])};y(c)}catch(e){}};var scr=d.getElementsByTagName(t)[0],par=scr.parentNode;par.insertBefore(s,scr)})(window,document,"script","https://s.yimg.com/wi/ytc.js","dotq");</script><noscript><img src="https://sp.analytics.yahoo.com/spp.pl?a=10001619333563&.yp=15043"/></noscript>', 'JSPCR4', '', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('YSM Mobile', '<script type="application/javascript">(function(w,d,t,r,u){w[u]=w[u]||[];w[u].push({''projectId'':''10001619333563'',''properties'':{''pixelId'':''15043''}});var s=d.createElement(t);s.src=r;s.async=true;s.onload=s.onreadystatechange=function(){var y,rs=this.readyState,c=w[u];if(rs&&rs!="complete"&&rs!="loaded"){return}try{y=YAHOO.ywa.I13N.fireBeacon;w[u]=[];w[u].push=function(p){y([p])};y(c)}catch(e){}};var scr=d.getElementsByTagName(t)[0],par=scr.parentNode;par.insertBefore(s,scr)})(window,document,"script","https://s.yimg.com/wi/ytc.js","dotq");</script><noscript><img src="https://sp.analytics.yahoo.com/spp.pl?a=10001619333563&.yp=15043"/></noscript>', 'JSPCR4', '', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_AMJ11_CPA100', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Conversion tracking ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of conversion tag -->', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_CPA@105_May09', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_CPA@90_May10', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_CPA_oct', '<script language="JavaScript" type="text/javascript">\r\nif(!alreadyCalledPixel)\r\n{\r\n	(function($){\r\n	if($)\r\n	{\r\n	$(document).ready(function(){\r\n	setTimeout(function(){\r\n	if(location.protocol == "https:"){\r\n		          var script_src=''https://s.yimg.com/wi/ytc.js'';\r\n		        }\r\n		        else{\r\n		          var script_src=''http://d.yimg.com/wi/ytc.js'';\r\n		        }\r\n	$.ajax({\r\n	  url: script_src,\r\n	  dataType: ''script'',\r\n	  cache: true, \r\n	  async: true,\r\n	  success: function() {\r\n	var scripttag=document.createElement\r\n			var g_YWA_funcs = {\r\n			  doSiteRetargeting: function(){\r\n			    try{\r\n			      YAHOO.ywa.I13N.fireBeacon([\r\n				{\r\n				  "projectId" : "10001619333563",\r\n				  "coloId" : "SP",\r\n				  "properties" : {\r\n				    "pixelId" : "15706",\r\n				    "qstrings" : {}\r\n				  }\r\n				}\r\n			      ]);\r\n			//RT_pixel\r\n			    }catch(e){\r\n			      if (window.console && window.console.warn) {\r\n				window.console.warn(e.message || "Unknown error");\r\n			      }\r\n			      return;\r\n			    }\r\n			  },\r\n			  doConversion: function(){\r\n			    try{\r\n			      YAHOO.ywa.I13N.fireBeacon([\r\n				{\r\n				  "projectId" : "10001619333563",\r\n				  "coloId" : "SP",\r\n				  "properties" : {\r\n				    "pixelId" : "15043",\r\n				    "qstrings" : {}\r\n				  }\r\n				}\r\n			      ]);\r\n			//CV_pixel\r\n			    }catch(e){\r\n			      if (window.console && window.console.warn) {\r\n				window.console.warn(e.message || "Unknown error");\r\n			      }\r\n			      return;\r\n			    }\r\n			  }\r\n			};\r\n			g_YWA_funcs.doConversion();\r\n	  }\r\n	});\r\n	},4000);\r\n	});\r\n	}\r\n	})(jQuery);\r\n}\r\nvar alreadyCalledPixel=1;\r\n</script>\r\n\r\n<!-- Advertiser ''INFO EDGE (I) LTD'',  Conversion tracking ''1382446_jeevansathi_conversionpixel_101212'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="https://ads.yahoo.com/pixel?id=2080988&t=2" width="1" height="1" />\r\n<!-- End of conversion tag -->', '', '', '', 'N');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_CPC', '<img src="https://sp.analytics.yahoo.com/spp.pl?a=10001619333563&.yp=15043&js=no"/>', '', '', '', 'N');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_CPM_180_150', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_FemaleTargeting_Apr10', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_NRI@350_Oct09', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n        <img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n        <!-- End of segment tag -->', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_RI_Aug10', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_RI_MaleOCt10', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_State_tgt_feb09', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Include user in segment ''JS Conversion pixel'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=495588&t=2" width="1" height="1" />\r\n<!-- End of segment tag -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_US_CPA@200_Sep08', '<img src="http://ad.yieldmanager.com/pixel?id=137012&t=2" width="1" height="1" />', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Yahoo_YAN', '<!-- Advertiser ''INFO EDGE (I) LTD'',  Conversion tracking ''1382446_jeevansathi_conversionpixel_101212'' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->\r\n<img src="http://ad.yieldmanager.com/pixel?id=2080988&t=2" width="1" height="1" />\r\n<!-- End of conversion tag -->', '', '', '', 'N');
INSERT INTO `PIXELCODE_NEW` VALUES ('Youmint_JSRI_Feb11', '<img src="http://www.youmint.com/track/pixeltracking.php?mx=6246" height="1" width="1">\r\n<!-- YouMint Tracking Code For Jeevan Sathi   -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Youmint_JS_NRI_Feb11', '<img src="http://www.youmint.com/track/pixeltracking.php?mx=6246" height="1" width="1">\r\n<!-- YouMint Tracking Code For Jeevan Sathi   -->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('YouMint_Oct10', '<!--  Youmint Tracking for B_300x250_Male_04Oct Code-->\r\n  <img src="http://www.youmint.com/track/pixeltracking.php?mx=6165 <http://www.youmint.com/track/pixeltracking.php?mx=6168> " height="1" width="1">\r\n<!--   YouMint Tracking  Code-->\r\n', '', '', '', '');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tyroo_del', '<script src="https://www.s2d6.com/js/globalpixel.js?x=sp&a=1295&h=67036&o=~$USERNAME`&g=&s=0.00&q=1"></script>', 'JSPCR4', '1', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('Tyroo_AMJ@120', '<script src="https://www.s2d6.com/js/globalpixel.js?x=sp&a=879&h=67036&o=~$USERNAME`&g=&s=0.00&q=1"></script>', 'JSPCR6', '1', 'AGE_F22_M25|CITY', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('SenseDigital_2015', '<script src="https://track.sensedigital.in/conversion.php?id=174&txn_id=~$USERNAME`&sub_id={aff_id}"></script>', 'JSPCR6', '1', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('Sense Digital Ph Verified CPL', '<script src="https://track.sensedigital.in/conversion.php?id=174&txn_id=~$USERNAME`&sub_id={aff_id}"></script>', 'JSPCR6', '1', '', 'Y');
INSERT INTO `PIXELCODE_NEW` VALUES ('OMG', ' <script type="text/javascript" src="https://track.in.omgpm.com/841525/transaction.asp?MID=841525&PID=15955&status="></script><noscript><img src="https://track.in.omgpm.com/apptag.asp?MID=841525&PID=15955&status=" border="0" height="1" width="1"></noscript>', 'JSPCR6', '', '', 'Y');

RENAME TABLE PIXELCODE TO PIXELCODE_BKP1,PIXELCODE_NEW TO PIXELCODE;
