use MOBILE_API;

UPDATE  `APP_NOTIFICATIONS` SET  `NOTIFICATION_KEY` =  'JUST_JOIN' WHERE NOTIFICATION_KEY="MATCHALERT";
INSERT INTO `APP_NOTIFICATIONS` VALUES (19, 'MATCHALERT', 'Contact these {MATCHALERT_COUNT} new matches for today which have been handpicked by us based on your preferences', 7, 'ALL', 'Y', 'D', '8|2', 40, 'MUL', 'Y', 0, 'A', 'A', 'Match Alerts', 'D');
INSERT INTO `APP_NOTIFICATIONS` VALUES (20, 'MATCHALERT', 'Contact the new match for today which have been handpicked by us based on your preferences', 7, 'ALL', 'Y', 'D', '8|2', 40, 'SINGLE', 'Y', 0, 'A', 'A', 'Match Alerts', 'D');
        
        
CREATE TABLE `ALARM_TIME` (
 `PROFILEID` int(11) NOT NULL,
 `ALARM_TIME` time DEFAULT NULL,
 PRIMARY KEY (`PROFILEID`)
);

UPDATE  `APP_NOTIFICATIONS` SET  `PRIORITY` =  '10' WHERE NOTIFICATION_KEY='PENDING_EOI';
UPDATE  `APP_NOTIFICATIONS` SET  `PRIORITY` =  '20' WHERE NOTIFICATION_KEY='VISITOR';
UPDATE  `APP_NOTIFICATIONS` SET  `PRIORITY` =  '30' WHERE NOTIFICATION_KEY='JUST_JOIN';
UPDATE  `APP_NOTIFICATIONS` SET  `PRIORITY` =  '40' WHERE NOTIFICATION_KEY='MATCHALERT';

CREATE TABLE `MAX_ALARM_TIME` (
  `MAX_ALARM_TIME` time NOT NULL
);
ALTER TABLE  `SCHEDULED_APP_NOTIFICATIONS` ADD  `MSG_ID` BIGINT( 20 ) NOT NULL ;
ALTER TABLE  `REGISTRATION_ID` ADD  `APP_VERSION` INT( 10 ) NOT NULL ,
ADD  `OS_VERSION` FLOAT NOT NULL ;
