/**
Important : for table MAIN_MAILER_NEW we need to set auto increment key for MAILER_ID from the value which is last in single click mailer table in property db of 99acres. do not set auto increment from 1.
**/

use mmmjs;
CREATE TABLE `TEST_MAILERS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(50) DEFAULT NULL,
  `SITE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL` (`EMAIL`)
) ENGINE=MyISAM;

CREATE TABLE `TEST_MAILERS_TEMP` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(50) NOT NULL,
  `MAILER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL` (`EMAIL`,`MAILER_ID`)
) ENGINE=MyISAM ;

CREATE TABLE `MAIN_MAILER_NEW` (
  `MAILER_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CTIME` datetime NOT NULL,
  `RTIME` datetime DEFAULT NULL,
  `MAILER_NAME` varchar(40) DEFAULT NULL,
  `CLIENT_NAME` varchar(40) DEFAULT NULL,
  `STATUS` enum('NEW','FQ','WM','TR','TC','DC','F','R','RC','S','MS') DEFAULT NULL,
  `MAIL_TYPE` enum('hcm','tpm','urm') DEFAULT NULL,
  `RESPONSE_TYPE` enum('o','i','sc','fm') DEFAULT NULL,
  `COMPANY_NAME` varchar(40) DEFAULT NULL,
  `MAILER_FOR` enum('J','9') NOT NULL,
  `TABLE_NAME` varchar(30) NOT NULL,
  `PERIOD_OF_STAY` tinyint(4) NOT NULL,
  `UNIQUEID` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`MAILER_ID`)
) ENGINE=MyISAM ;

CREATE TABLE `MAIL_OPEN_AND_UNSUBSCRIBE` (
  `MAILER_ID` int(11) NOT NULL,
  `DATE` date NOT NULL,
  `GMAIL_OP` int(11) NOT NULL,
  `YAHOO_OP` int(11) NOT NULL,
  `HOTMAIL_OP` int(11) NOT NULL,
  `REDIFF_OP` int(11) NOT NULL,
  `OTHERS_OP` int(11) NOT NULL,
  `TOTAL_OPEN` int(11) NOT NULL,
  `TOTAL_UNSUBSCRIBE` int(11) DEFAULT NULL,
  PRIMARY KEY (`MAILER_ID`,`DATE`)
) ENGINE=MyISAM ;


CREATE TABLE `MAILER_SPECS_JS` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `MAILER_ID` int(11) unsigned NOT NULL,
  `TYPE` varchar(1) NOT NULL,
  `GENDER` char(1) DEFAULT NULL,
  `CASTE` text,
  `MANGLIK` varchar(20) DEFAULT NULL,
  `MTONGUE` text,
  `MSTATUS` varchar(20) DEFAULT NULL,
  `HAVECHILD` varchar(20) DEFAULT NULL,
  `MIN_AGE` tinyint(1) unsigned NOT NULL,
  `MAX_AGE` tinyint(1) unsigned NOT NULL,
  `MIN_HEIGHT` tinyint(1) NOT NULL,
  `MAX_HEIGHT` tinyint(1) NOT NULL,
  `BTYPE` varchar(20) DEFAULT NULL,
  `COMPLEXION` varchar(20) DEFAULT NULL,
  `DIET` varchar(20) DEFAULT NULL,
  `SMOKE` char(1) DEFAULT NULL,
  `DRINK` char(1) DEFAULT NULL,
  `HANDICAPPED` varchar(20) DEFAULT NULL,
  `OCCUPATION` varchar(300) NOT NULL,
  `COUNTRY_RES` text NOT NULL,
  `CITY_RES` text,
  `COUNTRY_BIRTH` text NOT NULL,
  `RES_STATUS` varchar(20) DEFAULT NULL,
  `EDU_LEVEL` varchar(20) NOT NULL,
  `RELATION` varchar(20) NOT NULL,
  `HAVEPHOTO` char(1) DEFAULT NULL,
  `INCOMPLETE` char(1) DEFAULT NULL,
  `SHOWPHONE_RES` char(1) DEFAULT NULL,
  `SHOWPHONE_MOB` char(1) DEFAULT NULL,
  `SUBSCRIPTION` char(1) DEFAULT NULL,
  `LINCOME` tinyint(1) DEFAULT NULL,
  `HINCOME` tinyint(1) DEFAULT NULL,
  `LINCOME_DOL` tinyint(1) DEFAULT NULL,
  `HINCOME_DOL` tinyint(1) DEFAULT NULL,
  `ENTRY_DT1` date DEFAULT NULL,
  `ENTRY_DT2` date DEFAULT NULL,
  `MODIFY_DT1` varchar(20) DEFAULT NULL,
  `MODIFY_DT2` varchar(20) DEFAULT NULL,
  `LASTLOGIN_DT1` varchar(20) DEFAULT NULL,
  `LASTLOGIN_DT2` varchar(20) DEFAULT NULL,
  `UPPER_LIMIT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `MAILER_ID` (`MAILER_ID`)
) ENGINE=MyISAM;

CREATE TABLE `MAILER_SPECS_99` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `MAILER_ID` int(11) unsigned DEFAULT NULL,
  `RECIPIENT_TYPE` char(1) DEFAULT NULL,
  `SCREENING` char(1) DEFAULT NULL,
  `ACTIVATED` char(1) DEFAULT NULL,
  `SUB_PROMO` char(1) DEFAULT NULL,
  `SUB_PARTNERS` char(1) DEFAULT NULL,
  `BUYER_RESCOM` char(1) DEFAULT NULL,
  `BUYER_PREFERENCE_BUY` char(2) DEFAULT NULL,
  `BUYER_PREFERENCE_RENT` char(2) DEFAULT NULL,
  `BUYER_PREFERENCE_LEASE` char(2) DEFAULT NULL,
  `BUYER_PREFERENCE_PG` char(2) DEFAULT NULL,
  `BUYER_PROP_CITY` varchar(30) DEFAULT NULL,
  `BUYER_PROPERTY_TYPE` varchar(30) DEFAULT NULL,
  `BUDGET_MIN` bigint(10) unsigned DEFAULT NULL,
  `BUDGET_MAX` bigint(10) unsigned DEFAULT NULL,
  `BUYER_COUNTRY_SOURCE` char(1) DEFAULT NULL,
  `BUYER_UPPER_LIMIT` int(20) DEFAULT NULL,
  `SELLER_UPPER_LIMIT` int(20) DEFAULT NULL,
  `SELLER_CLASS_AGENT` char(2) DEFAULT NULL,
  `SELLER_CLASS_BUILDER` char(2) DEFAULT NULL,
  `SELLER_CLASS_OWNER` char(2) DEFAULT NULL,
  `SELLER_RESCOM` char(1) DEFAULT NULL,
  `SELLER_PREFERENCE_ALL` char(2) DEFAULT NULL,
  `BUYER_PREFERENCE_ALL` char(2) DEFAULT NULL,
  `SELLER_PROPERTY_TYPE` varchar(30) DEFAULT NULL,
  `SELLER_PROP_CITY` varchar(30) DEFAULT NULL,
  `SELLER_COUNTRY_SOURCE` char(1) DEFAULT NULL,
  `CITY` varchar(30) DEFAULT NULL,
  `SELLER_PREFERENCE_SELL` char(2) DEFAULT NULL,
  `SELLER_PREFERENCE_RENT` char(2) DEFAULT NULL,
  `SELLER_PREFERENCE_LEASE` char(2) DEFAULT NULL,
  `SELLER_PREFERENCE_PG` char(2) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `MAILER_ID` (`MAILER_ID`)
) ENGINE=MYISAM;

CREATE TABLE `MAIL_DATA_NEW` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEMPLATE_NAME` varchar(25) NOT NULL DEFAULT '',
  `MAILER_ID` int(11) NOT NULL DEFAULT '0',
  `F_EMAIL` varchar(35) NOT NULL DEFAULT '',
  `F_NAME` varchar(35) NOT NULL DEFAULT 'jeevansathi.com',
  `SUBJECT` varchar(250) NOT NULL DEFAULT '',
  `DATA` text,
  `DUMP` enum('Y','N') DEFAULT 'N',
  `STATIC_DATA` text NOT NULL,
  `BROWSERURL` varchar(200) DEFAULT NULL,
  `STAGGER` tinyint(11) DEFAULT '1',
  `ACTIVE` char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `MAILER_ID` (`MAILER_ID`)
) ENGINE=MyISAM;

CREATE TABLE `MAIL_OPEN_INDIVIDUAL_NEW` (
  `SNO` int(11) NOT NULL AUTO_INCREMENT,
  `DATE` date NOT NULL DEFAULT '0000-00-00',
  `MAILER_ID` int(11) NOT NULL DEFAULT '0',
  `OPEN_COUNT` int(11) NOT NULL DEFAULT '0',
  `EMAIL` varchar(100) NOT NULL DEFAULT '0',
  `time` datetime NOT NULL,
  PRIMARY KEY (`SNO`),
  UNIQUE KEY `MAILER_ID` (`MAILER_ID`,`DATE`,`EMAIL`)
) ENGINE=MyISAM;

CREATE TABLE `MAIL_UNSUBSCRIBE_NEW` (
  `SNO` int(11) NOT NULL AUTO_INCREMENT,
  `DATE` date NOT NULL DEFAULT '0000-00-00',
  `MAILER_ID` int(11) NOT NULL DEFAULT '0',
  `OPEN_COUNT` int(11) NOT NULL DEFAULT '0',
  `UN_COUNT` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`SNO`),
  UNIQUE KEY `MAILER_ID` (`MAILER_ID`,`DATE`)
) ENGINE=MyISAM;

CREATE TABLE `MAIL_SENT_NEW` (
 `SNO` mediumint(11) unsigned NOT NULL AUTO_INCREMENT,
 `DATE` date NOT NULL DEFAULT '0000-00-00',
 `MAILER_ID` mediumint(11) unsigned NOT NULL DEFAULT '0',
 `SENT` mediumint(11) unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY (`SNO`),
 UNIQUE KEY `MAILER_ID` (`MAILER_ID`,`DATE`)
) ENGINE=MyISAM;

CREATE TABLE `MAILER_STOPED` (
  `MAILER_ID` mediumint(9) NOT NULL,
  `STATUS` char(1) DEFAULT 'N',
  `ENTRY_DT` datetime DEFAULT NULL
) ENGINE=InnoDB;
