ALTER TABLE  `SCHEDULED_APP_NOTIFICATIONS` DROP PRIMARY KEY ,
ADD UNIQUE (
`PROFILEID` ,
`NOTIFICATION_KEY` ,
`SCHEDULED_DATE`
);
ALTER TABLE  `SCHEDULED_APP_NOTIFICATIONS` ADD  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST ;
