USE billing;

CREATE TABLE `ORDERS_DEVICE` (
  `PROFILEID` int(11) NOT NULL,
  `ID` int(11) NOT NULL,
  `ORDERID` varchar(25) NOT NULL,
  `SOURCE` varchar(25) NOT NULL,
  `BILLID` int(11) NOT NULL DEFAULT '0',
  `ENTRY_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;