use newjs;

CREATE TABLE `PICTURE_NEW` (
 `PICTUREID` int(11) unsigned NOT NULL DEFAULT '0',
 `PROFILEID` int(11) unsigned DEFAULT '0',
 `ORDERING` int(1) DEFAULT NULL,
 `TITLE` varchar(40) DEFAULT NULL,
 `KEYWORD` varchar(20) DEFAULT NULL,
 `UPDATED_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `MainPicUrl` varchar(200) DEFAULT NULL,
 `ProfilePicUrl` varchar(200) DEFAULT NULL,
 `ThumbailUrl` varchar(200) DEFAULT NULL,
 `Thumbail96Url` varchar(200) DEFAULT NULL,
 `PICFORMAT` varchar(10) DEFAULT NULL,
 `SearchPicUrl` varchar(200) DEFAULT NULL,
 `UNSCREENED_TITLE` varchar(40) NOT NULL,
 PRIMARY KEY (`PICTUREID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`ORDERING`)
) ENGINE=InnoDB;

CREATE TABLE `PICTURE_FOR_SCREEN_NEW` (
 `PICTUREID` int(11) unsigned NOT NULL DEFAULT '0',
 `PROFILEID` int(11) unsigned DEFAULT '0',
 `ORDERING` int(1) DEFAULT NULL,
 `TITLE` varchar(40) DEFAULT NULL,
 `KEYWORD` varchar(20) DEFAULT NULL,
 `UPDATED_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `MainPicUrl` varchar(200) DEFAULT NULL,
 `ProfilePicUrl` varchar(200) DEFAULT NULL,
 `ThumbailUrl` varchar(200) DEFAULT NULL,
 `Thumbail96Url` varchar(200) DEFAULT NULL,
 `PICFORMAT` varchar(10) DEFAULT NULL,
 PRIMARY KEY (`PICTUREID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`ORDERING`)
) ENGINE=InnoDB;

CREATE TABLE `PICTURE_AUTOINCREMENT` (
 `AUTO_ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
 `NO_USE_VARIABLE` char(1) NOT NULL DEFAULT 'N',
 PRIMARY KEY (`AUTO_ID`),
 UNIQUE KEY `NO_USE_VARIABLE` (`NO_USE_VARIABLE`)
) ENGINE=MyISAM;

CREATE TABLE `PHOTO_URL` (
 `PROFILEID` int(11) unsigned DEFAULT NULL,
 `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
 `LARGE_URL` varchar(200) NOT NULL,
 `PHOTO_NO` mediumint(9) NOT NULL,
 `IMPORTSITE` varchar(10) NOT NULL,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`LARGE_URL`,`PHOTO_NO`)
) ENGINE=MyISAM;

INSERT INTO SMS_STATUS(SMS_KEY,STATUS) VALUES ("SI_PHOTOSCREEN_REJ","Y");

UPDATE SMS_STATUS SET STATUS = "Y" WHERE SMS_KEY = "SI_PHOTOSCREEN";

alter table SMS_DETAIL modify column SMS_KEY varchar(20);

ALTER TABLE `JPROFILE` CHANGE `PHOTOSCREEN` `PHOTOSCREEN` TINYINT UNSIGNED DEFAULT '1' 

use MIS;

CREATE TABLE `IMPORT_PAGES_TRACKING` (
 `PROFILEID` int(11) unsigned NOT NULL DEFAULT '0',
 `DATE` date NOT NULL DEFAULT '0000-00-00',
 `IMPORT_SITE` varchar(20) NOT NULL DEFAULT '',
 `PERMISSION_PAGE` smallint(3) unsigned DEFAULT '0',
 `ALBUM_PAGE` smallint(3) unsigned DEFAULT '0',
 `PHOTO_PAGE` smallint(3) unsigned DEFAULT '0',
 `ZERO_ALBUMS` smallint(3) unsigned DEFAULT '0',
 `IMPORT_FAILED` smallint(3) unsigned DEFAULT '0',
 `NO_PICASA_ACCOUNT` smallint(3) unsigned DEFAULT '0',
 PRIMARY KEY (`PROFILEID`,`IMPORT_SITE`,`DATE`),
 KEY `DATE` (`DATE`)
) ENGINE=MyISAM;

CREATE TABLE `IMPORT_UPLOAD_TRACKING` (
 `PROFILEID` int(11) unsigned DEFAULT NULL,
 `PHOTO_SOURCE` varchar(20) DEFAULT NULL,
 `NO_OF_PHOTOS` tinyint(3) unsigned DEFAULT '0',
 `DATE` date DEFAULT NULL,
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`PHOTO_SOURCE`,`DATE`),
 KEY `DATE` (`DATE`)
) ENGINE=MyISAM;

CREATE TABLE `PHOTO_DELETE_TRACKING` (
 `PICTUREID` int(11) unsigned DEFAULT NULL,
 `PROFILEID` int(11) unsigned DEFAULT NULL,
 `DATE` date DEFAULT NULL,
 `SOURCE` varchar(10) NOT NULL,
 `PICTURE_TYPE` varchar(11) NOT NULL,
 KEY `PROFILEID` (`PROFILEID`),
 KEY `DATE` (`DATE`)
) ENGINE=MyISAM;

CREATE TABLE `INVALID_SCREENING_ENTRIES_TRACKING` (
 `PROFILEID` int(11) unsigned DEFAULT NULL,
 `DATE` date NOT NULL
) ENGINE=MyISAM;

CREATE TABLE `PHOTO_CRON_ERROR` (
 `PROFILEID` int(11) unsigned DEFAULT NULL,
 `TYPE` varchar(20) NOT NULL
) ENGINE=MyISAM;

ALTER TABLE `PHOTO_SCREEN_STATS` ADD `DEL_MAIL_PHOTOS` INT( 5 ) DEFAULT '0' NOT NULL AFTER `DEL_MAIL` ;

use jsadmin;

ALTER TABLE `SCREEN_PHOTOS_FROM_MAIL` CHANGE `STATUS` `STATUS` VARCHAR( 25 );

use test;

CREATE TABLE `TEMP_PROFILEID` (
  `PROFILEID` mediumint(11) unsigned NOT NULL,
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
