use PICTURE;
CREATE TABLE  `PIC_URL_RESPONSE_CHECK` (
 `PICTUREID` INT( 11 ) UNSIGNED NOT NULL ,
 `URLTYPE` VARCHAR( 20 ) NOT NULL ,
 `COMPLETEURL` VARCHAR( 200 ) NOT NULL ,
 `HTTPCODE` SMALLINT( 6 ) NOT NULL ,
PRIMARY KEY (  `PICTUREID` ,  `URLTYPE` )
);