use search;
CREATE TABLE `SEARCH_SOLR_ANALYSIS` (
  `ID` int(2) unsigned NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `SEARCH_TYPE` varchar(3) DEFAULT NULL,
  `LIMIT_SEARCHED` int(5) DEFAULT NULL,
  `TIME_EXECUTION` int(10) NOT NULL,
  `CURRENT_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=MYISAM;
