DELETE FROM SMS_TYPE WHERE SMS_KEY = 'MATCH_ALERT';

INSERT INTO  `SMS_TYPE` (  `ID` ,  `SMS_KEY` ,  `SMS_TYPE` ,  `PRIORITY` ,  `SUBSCRIPTION` ,  `GENDER` ,  `COUNT` ,  `TIME_CRITERIA` ,  `CUSTOM_CRITERIA` ,  `SMS_SUBSCRIPTION` ,  `STATUS` ,  `MESSAGE` ) 
 VALUES ('', 'MATCH_ALERT', 'D', 102, 'P', 'A', 'SINGLE', 30, 0, 'SERVICE', 'Y', 'Match of the Day-{AGE} yrs,{HEIGHT},{CASTE},{OWN_HOUSE}{CITY_RES},{EDU_LEVEL},{INCOME},{OCCUPATION}{COMPANY}. Click {URL_PROFILE} to contact')
, ('', 'MATCH_ALERT', 'D', 102, 'F', 'A', 'SINGLE', 30, 0, 'SERVICE', 'Y', 'Match of the Day-{AGE} yrs,{HEIGHT},{CASTE},{OWN_HOUSE}{CITY_RES},{EDU_LEVEL},{INCOME},{OCCUPATION}{COMPANY}. Click {URL_PROFILE} /Call:{TOLLNO}')
, ('', 'MATCH_ALERT', 'D', 102, 'P', 'A', 'SINGLE', 30, 1, 'SERVICE', 'Y', 'Match of the Day-{AGE} yrs,{CASTE},{OWN_HOUSE}{CITY_RES},{FAMILY_INCOME},{OCCUPATION}{COMPANY}. Click {URL_PROFILE} to contact')
, ('', 'MATCH_ALERT', 'D', 102, 'F', 'A', 'SINGLE', 30, 1, 'SERVICE', 'Y', 'Match of the Day-{AGE} yrs,{HEIGHT}{CASTE},{OWN_HOUSE}{CITY_RES},{FAMILY_INCOME},{OCCUPATION} {COMPANY}. Click {URL_PROFILE}/CAll:{TOLLNO}')
