
use crawler;

ALTER TABLE `crawler_search_results` CHANGE `SEARCH_ID` `SEARCH_ID` INT( 11 ) DEFAULT NULL ,
CHANGE `SITE_ID` `SITE_ID` INT( 11 ) DEFAULT NULL ,
CHANGE `COMPETITION_ID` `COMPETITION_ID` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `DETAIL_VIEW_PARSED` `DETAIL_VIEW_PARSED` CHAR( 1 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `CONTACT_DETAILS_PARSED` `CONTACT_DETAILS_PARSED` CHAR( 1 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `se` `se` VARCHAR( 50 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `QUALITY` `QUALITY` CHAR( 1 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `NAME` `NAME` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `DTOFBIRTH` `DTOFBIRTH` DATE DEFAULT NULL ,
CHANGE `BTIME` `BTIME` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `CITY_BIRTH` `CITY_BIRTH` VARCHAR( 250 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `COUNTRY_BIRTH` `COUNTRY_BIRTH` TINYINT( 3 ) DEFAULT NULL ,
CHANGE `GENDER` `GENDER` CHAR( 1 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `MSTATUS` `MSTATUS` CHAR( 2 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `AGE` `AGE` TINYINT( 4 ) DEFAULT NULL ,
CHANGE `BLOOD_GROUP` `BLOOD_GROUP` CHAR( 2 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `MTONGUE` `MTONGUE` TINYINT( 3 ) DEFAULT NULL ,
CHANGE `CITIZENSHIP` `CITIZENSHIP` SMALLINT( 5 ) DEFAULT NULL ,
CHANGE `RELIGION` `RELIGION` TINYINT( 3 ) DEFAULT NULL ,
CHANGE `CASTE` `CASTE` MEDIUMINT( 9 ) DEFAULT NULL ,
CHANGE `COUNTRY_RES` `COUNTRY_RES` MEDIUMINT( 9 ) DEFAULT NULL ,
CHANGE `CITY_RES` `CITY_RES` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `EDU_LEVEL_NEW` `EDU_LEVEL_NEW` MEDIUMINT( 9 ) DEFAULT NULL ,
CHANGE `T_BROTHER` `T_BROTHER` TINYINT( 3 ) DEFAULT NULL ,
CHANGE `T_SISTER` `T_SISTER` TINYINT( 3 ) DEFAULT NULL ,
CHANGE `DIET` `DIET` CHAR( 1 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `DRINK` `DRINK` CHAR( 1 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `SMOKE` `SMOKE` CHAR( 1 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `GOTHRA` `GOTHRA` VARCHAR( 250 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `SUBCASTE` `SUBCASTE` VARCHAR( 250 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `HEIGHT` `HEIGHT` TINYINT( 3 ) DEFAULT NULL ,
CHANGE `STD` `STD` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `PHONE_RES` `PHONE_RES` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `PHONE_MOB` `PHONE_MOB` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `EMAIL` `EMAIL` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `DE_DUPED` `DE_DUPED` CHAR( 1 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ;

UPDATE `crawler_JS_competition_caste_values_mapping` SET `JS_FIELD_VALUE` = '159' WHERE `SITE_ID` = '2' AND CONVERT( `COMPETITION_FIELD_LABEL` USING utf8 ) = 'Sikh - Khatri' AND CONVERT( `COMPETITION_FIELD_VALUE` USING utf8 ) = '' AND `JS_FIELD_VALUE` = '78' LIMIT 1 ;

UPDATE `crawler_JS_competition_caste_values_mapping` SET `JS_FIELD_VALUE` = '159' WHERE `SITE_ID` = '3' AND CONVERT( `COMPETITION_FIELD_LABEL` USING utf8 ) = 'Sikh - Khatri' AND CONVERT( `COMPETITION_FIELD_VALUE` USING utf8 ) = '' AND `JS_FIELD_VALUE` = '78' LIMIT 1 ;

INSERT INTO `crawler_JS_competition_field_name_mapping` ( `SITE_ID` , `COMPETITION_FIELD_NAME` , `JS_FIELD_NAME` , `MAPPING_REQUIRED` , `ACTION` )
VALUES (
'1', 'Gothra', 'GOTHRA', '', 'detail_view'
);

INSERT INTO `crawler_JS_competition_field_name_mapping` ( `SITE_ID` , `COMPETITION_FIELD_NAME` , `JS_FIELD_NAME` , `MAPPING_REQUIRED` , `ACTION` )
VALUES (
'1', 'Name', 'NAME', '', 'detail_view'
);

INSERT INTO `crawler_JS_competition_field_name_mapping` ( `SITE_ID` , `COMPETITION_FIELD_NAME` , `JS_FIELD_NAME` , `MAPPING_REQUIRED` , `ACTION` )
VALUES (
'2', 'Gothra', 'GOTHRA', '', 'detail_view'
);

CREATE TABLE `TRACK_SUGAR_LEAD_CREATION` (
 `SITE_ID` tinyint(4) NOT NULL,
 `COMPETITION_ID` varchar(255) NOT NULL,
 `RESPONSE` varchar(255) NOT NULL,
 `DATE` date NOT NULL
) ENGINE=MyISAM;
