use billing;

UPDATE SERVICES SET NAME = 'e-Sathi Confidential - 3 Months',PRICE_RS = '4528.55',PRICE_RS_TAX = '4995',PRICE_DOL = '105' WHERE SERVICEID = 'ES3' LIMIT 1 ;

UPDATE SERVICES SET NAME = 'e-Sathi Confidential - 6 Months',PRICE_RS = '8155.03',PRICE_RS_TAX = '8995',PRICE_DOL = '195' WHERE SERVICEID = 'ES6' LIMIT 1 ;

UPDATE SERVICES SET NAME = 'e-Sathi Confidential - Unlimited',PRICE_RS = '13594.74',PRICE_RS_TAX = '14995',PRICE_DOL = '295' WHERE SERVICEID = 'ES12' LIMIT 1 ;

UPDATE SERVICES SET NAME = 'e-Sathi Classified - 3 Months',PRICE_RS = '4528.55',PRICE_RS_TAX = '4995',PRICE_DOL = '105' WHERE SERVICEID = 'ESP3' LIMIT 1 ;

UPDATE SERVICES SET NAME = 'e-Sathi Classified - 6 Months',PRICE_RS = '8155.03',PRICE_RS_TAX = '8995',PRICE_DOL = '195' WHERE SERVICEID = 'ESP6' LIMIT 1 ;

UPDATE SERVICES SET NAME = 'e-Sathi Classified - Unlimited',PRICE_RS = '13594.74',PRICE_RS_TAX = '14995',PRICE_DOL = '295' WHERE SERVICEID = 'ESP12' LIMIT 1 ;

UPDATE PACK_COMPONENTS SET COMPID = 'PL' WHERE PACKID = 'PES12' LIMIT 1 ;

UPDATE PACK_COMPONENTS SET COMPID = 'PL' WHERE PACKID = 'PESP12' LIMIT 1 ;

//Bug-51267

UPDATE `SERVICES` SET `SERVICEID` = 'ESL' WHERE `SERVICEID` = 'ES12' LIMIT 1 ;

UPDATE `SERVICES` SET `SERVICEID` = 'ESPL' WHERE `SERVICEID` = 'ESP12' LIMIT 1 ;

//Bug-51356

UPDATE `PACK_COMPONENTS` SET `COMPID` = 'A12' WHERE `ID` = '101' LIMIT 1 ;

UPDATE `PACK_COMPONENTS` SET `COMPID` = 'A12' WHERE `ID` = '119' LIMIT 1 ;


