USE incentive;

CREATE TABLE `SALES_CSV_DATA_MOBILE_APP_REGISTRATIONS` (
  `PHONE_MOB` varchar(100) NOT NULL,
  `USERNAME` varchar(40) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `PROFILEID` int(11) NOT NULL DEFAULT '0',
  `SCORE` mediumint(6) NOT NULL DEFAULT '0',
  `PRIORITY` int(1) NOT NULL DEFAULT '0',
  `DNC` int(1) NOT NULL DEFAULT '0',
  `CSV_ENTRY_DT` date DEFAULT '0000-00-00'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;