/* Creating Table in test database */

use test;

CREATE TABLE JPROFILE_FOR_DUPLICATION (
  PROFILEID int(11) unsigned NOT NULL DEFAULT '0',
  GENDER char(1) DEFAULT NULL,
  RELIGION tinyint(3) unsigned DEFAULT '0',
  CASTE smallint(8) unsigned DEFAULT '0',
  MTONGUE tinyint(3) unsigned DEFAULT '0',
  MSTATUS char(2) DEFAULT NULL,
  DTOFBIRTH date DEFAULT '0000-00-00',
  COUNTRY_RES tinyint(3) unsigned DEFAULT '0',
  CITY_RES varchar(4) DEFAULT NULL,
  HEIGHT tinyint(3) unsigned DEFAULT '0',
  COUNTRY_BIRTH tinyint(3) unsigned DEFAULT '0',
  CITY_BIRTH varchar(250) DEFAULT NULL,
  BTIME varchar(5) DEFAULT NULL,
  AGE tinyint(4) DEFAULT '0',
  EDU_LEVEL_NEW tinyint(3) unsigned DEFAULT '0',
  INCOME tinyint(3) unsigned DEFAULT '0',
  LAST_LOGIN_DT date DEFAULT '0000-00-00',
  PRIMARY KEY (PROFILEID),
  KEY LAST_LOGIN_DT (LAST_LOGIN_DT),
  KEY DTOFBIRTH (DTOFBIRTH),
  KEY CASTE (CASTE,MTONGUE)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;





/* Creating triggers */

use newjs;

/* Execute drop  only if required */
drop trigger INSERT_SWAP;
drop trigger UPDATE_SWAP;


delimiter |
create trigger INSERT_SWAP
AFTER INSERT ON JPROFILE
FOR EACH ROW
begin
insert ignore into SWAP_JPROFILE set PROFILEID=new.PROFILEID;
REPLACE INTO test.JPROFILE_FOR_DUPLICATION (PROFILEID,BTIME,GENDER,MTONGUE,RELIGION,MSTATUS,CASTE,DTOFBIRTH,COUNTRY_RES,CITY_RES,COUNTRY_BIRTH,CITY_BIRTH,EDU_LEVEL_NEW,INCOME,AGE,LAST_LOGIN_DT,HEIGHT) VALUES (new.PROFILEID,new.BTIME,new.GENDER,new.MTONGUE,new.RELIGION,new.MSTATUS,new.CASTE,new.DTOFBIRTH,new.COUNTRY_RES,new.CITY_RES,new.COUNTRY_BIRTH,new.CITY_BIRTH,new.EDU_LEVEL_NEW,new.INCOME,new.AGE,new.LAST_LOGIN_DT,new.HEIGHT);
end
|
create trigger UPDATE_SWAP
AFTER UPDATE ON JPROFILE
FOR EACH ROW
BEGIN
 IF(@DONT_UPDATE_TRIGGER is NULL) THEN INSERT ignore into newjs.SWAP_JPROFILE set PROFILEID=new.PROFILEID; END IF;
 REPLACE INTO test.JPROFILE_FOR_DUPLICATION (PROFILEID,BTIME,GENDER,MTONGUE,RELIGION,MSTATUS,CASTE,DTOFBIRTH,COUNTRY_RES,CITY_RES,COUNTRY_BIRTH,CITY_BIRTH,EDU_LEVEL_NEW,INCOME,AGE,LAST_LOGIN_DT,HEIGHT) VALUES (new.PROFILEID,new.BTIME,new.GENDER,new.MTONGUE,new.RELIGION,new.MSTATUS,new.CASTE,new.DTOFBIRTH,new.COUNTRY_RES,new.CITY_RES,new.COUNTRY_BIRTH,new.CITY_BIRTH,new.EDU_LEVEL_NEW,new.INCOME,new.AGE,new.LAST_LOGIN_DT,new.HEIGHT);
END
|
delimiter ;

/* One time query*/

use test;


REPLACE INTO test.JPROFILE_FOR_DUPLICATION (PROFILEID,BTIME,GENDER,MTONGUE,RELIGION,MSTATUS,CASTE,DTOFBIRTH,COUNTRY_RES,CITY_RES,COUNTRY_BIRTH,CITY_BIRTH,EDU_LEVEL_NEW,INCOME,AGE,LAST_LOGIN_DT,HEIGHT) SELECT PROFILEID,BTIME,GENDER,MTONGUE,RELIGION,MSTATUS,CASTE,DTOFBIRTH,COUNTRY_RES,CITY_RES,COUNTRY_BIRTH,CITY_BIRTH,EDU_LEVEL_NEW,INCOME,AGE,LAST_LOGIN_DT,HEIGHT FROM newjs.JPROFILE AS J WHERE J.LAST_LOGIN_DT > '2012-12-27';

