-- --------------------------------------------------------

-- 
-- Table structure for table `BRANCHES`
-- 

CREATE TABLE `BRANCHES` (
  `ID` int(11) NOT NULL auto_increment,
  `VALUE` varchar(4) NOT NULL default '',
  `NAME` varchar(100) NOT NULL default '',
  `REGION` char(1) NOT NULL default '',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=42 DEFAULT CHARSET=latin1 AUTO_INCREMENT=42 ;

-- 
-- Dumping data for table `BRANCHES`
-- 

INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (1, 'UP25', 'NOIDA', 'N');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (2, 'MH04', 'MUMBAI', 'W');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (3, 'TN02', 'CHENNAI', 'S');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (4, 'AP03', 'HYDERABAD', 'S');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (5, 'WB05', 'KOLKATA', 'N');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (6, 'MH08', 'PUNE', 'W');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (7, 'GU01', 'AHMEDABAD', 'W');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (8, 'PH00', 'CHANDIGARH', 'N');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (9, 'KA02', 'BANGALORE', 'S');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (10, 'MP08', 'INDORE', 'W');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (11, 'GU04', 'BARODA', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (12, 'KE03', 'KOCHI', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (13, 'TN04', 'COIMBATORE', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (14, 'DE00', 'DELHI', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (15, 'RA07', 'JAIPUR', 'W');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (16, 'UP01', 'AGRA', 'N');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (17, 'GU10', 'SURAT', 'W');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (18, 'MP02', 'BHOPAL', 'W');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (19, 'MH02', 'AURANGABAD', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (20, 'MH05', 'NAGPUR', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (21, 'AP11', 'VISAKHAPATNAM', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (22, 'KE08', 'TRIVANDRUM', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (23, 'UP19', 'LUCKNOW', 'N');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (24, 'HA03', 'GURGAON', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (25, 'PU07', 'LUDHIANA', 'N');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (26, 'BI04', 'JAMSHEDPUR', 'W');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (27, 'MP12', 'RAIPUR', 'W');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (28, 'UP18', 'KANPUR', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (29, 'OR01', 'BHUBANESHWAR', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (30, 'BI07', 'RANCHI', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (31, 'BI06', 'PATNA', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (32, 'AS03', 'GUWAHATI', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (33, 'GU09', 'RAJKOT', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (34, 'KA09', 'MYSORE', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (35, 'AP10', 'VIJAYWADA', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (36, 'PO00', 'PONDICHERRY', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (37, 'MH24', 'NASIK', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (38, 'GO00', 'GOA', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (39, 'BA01', 'BAHRAIN', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (40, '893', 'DUBAI', '');
INSERT INTO `BRANCHES` (`ID`, `VALUE`, `NAME`, `REGION`) VALUES (41, '2261', 'RIYADH', '');


-- --------------------------------------------------------

-- 
-- Table structure for table `BRANCH_CITY`
-- 

CREATE TABLE `BRANCH_CITY` (
  `ID` tinyint(3) unsigned NOT NULL auto_increment,
  `LABEL` varchar(150) NOT NULL default '',
  `VALUE` varchar(4) NOT NULL default '',
  `TYPE` enum('CITY','STATE') NOT NULL default 'CITY',
  `SORTBY` tinyint(3) unsigned NOT NULL default '0',
  `NEAR_BRANCH` varchar(4) NOT NULL default '',
  `PRIORITY` varchar(50) NOT NULL default '',
  `PICKUP` char(1) default NULL,
  `IN_REGION` char(1) NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `VALUE` (`VALUE`)
) ENGINE=MyISAM AUTO_INCREMENT=226 DEFAULT CHARSET=latin1 AUTO_INCREMENT=226 ;

-- 
-- Dumping data for table `BRANCH_CITY`
-- 

INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (1, 'Agra', 'UP01', 'CITY', 2, 'UP25', 'UP01', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (2, 'Agartala', 'TR01', 'CITY', 1, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (3, 'Ahmedabad', 'GU01', 'CITY', 3, 'UP25', 'GU01', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (4, 'Aizwal', 'MI01', 'CITY', 5, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (5, 'Ajmer', 'RA01', 'CITY', 6, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (6, 'Akola', 'MH01', 'CITY', 7, 'MH08', 'MH08', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (7, 'Aligarh', 'UP02', 'CITY', 8, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (8, 'Allahabad', 'UP03', 'CITY', 9, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (9, 'Alwar', 'RA02', 'CITY', 10, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (10, 'Ambala', 'HA01', 'CITY', 11, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (11, 'Amethi', 'UP04', 'CITY', 12, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (12, 'Amritsar', 'PU01', 'CITY', 13, 'PH00', 'PH00', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (13, 'Anand', 'GU02', 'CITY', 14, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (14, 'Ankleshwar', 'GU03', 'CITY', 16, 'MH04', 'MH04', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (15, 'Ankola', 'KA01', 'CITY', 17, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (16, 'Arcot', 'TN01', 'CITY', 18, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (17, 'Asansol', 'WB01', 'CITY', 20, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (18, 'Aurangabad', 'MH02', 'CITY', 22, 'MH08', 'MH02', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (19, 'Ayodhya', 'UP05', 'CITY', 23, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (20, 'Bangalore', 'KA02', 'CITY', 25, 'KA02', 'KA02', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (21, 'Barddhaman', 'WB02', 'CITY', 26, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (22, 'Bareilly', 'UP06', 'CITY', 27, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (23, 'Baroda', 'GU04', 'CITY', 28, 'UP25', 'GU04', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (24, 'Bathinda', 'PU02', 'CITY', 29, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (25, 'Belgaum', 'KA03', 'CITY', 30, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (26, 'Bharatpur', 'RA03', 'CITY', 31, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (27, 'Bhilai', 'MP01', 'CITY', 33, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (28, 'Bhilwara', 'RA04', 'CITY', 34, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (29, 'Bhopal', 'MP02', 'CITY', 35, 'UP25', 'MP02', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (30, 'Bhubaneshwar', 'OR01', 'CITY', 36, 'UP25', 'OR01', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (31, 'Bidar', 'KA04', 'CITY', 37, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (32, 'Bikaner', 'RA05', 'CITY', 39, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (33, 'Bilaspur', 'MP03', 'CITY', 40, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (34, 'Bokaro', 'BI01', 'CITY', 41, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (36, 'Chandigarh', 'PH00', 'CITY', 42, 'PH00', 'PH00', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (37, 'Chennai', 'TN02', 'CITY', 43, 'TN02', 'TNO2', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (38, 'Chhindwara', 'MP04', 'CITY', 45, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (39, 'Chidambaram', 'TN03', 'CITY', 46, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (40, 'Coimbatore', 'TN04', 'CITY', 47, 'UP25', 'TN04', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (41, 'Cuddalore', 'TN05', 'CITY', 48, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (42, 'Cuddapah', 'AP01', 'CITY', 49, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (43, 'Cuttack', 'OR02', 'CITY', 50, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (44, 'Dalhousie', 'HP01', 'CITY', 52, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (45, 'DehraDun', 'UP07', 'CITY', 54, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (46, 'Delhi', 'DE00', 'CITY', 55, 'UP25', 'DE00', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (47, 'Deora', 'MP05', 'CITY', 56, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (48, 'Dhanbad', 'BI02', 'CITY', 57, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (49, 'Dharwad', 'KA05', 'CITY', 58, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (50, 'Dibrugarh', 'AS01', 'CITY', 59, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (51, 'Dimapur', 'NA01', 'CITY', 60, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (52, 'Dispur', 'AS02', 'CITY', 61, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (53, 'Durg', 'MP06', 'CITY', 63, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (54, 'Durgapur', 'WB03', 'CITY', 64, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (56, 'Erode', 'TN06', 'CITY', 65, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (57, 'Etawah', 'UP08', 'CITY', 66, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (58, 'Faizabad', 'UP09', 'CITY', 67, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (59, 'Faridabad', 'HA02', 'CITY', 68, 'UP25', 'DE00', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (60, 'Faridkot', 'PU03', 'CITY', 69, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (61, 'Fatehpur', 'UP10', 'CITY', 70, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (62, 'Ferozpur', 'PU04', 'CITY', 71, 'PH00', 'PH00', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (63, 'Firozabad', 'UP11', 'CITY', 72, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (64, 'Gandhinagar', 'GU05', 'CITY', 73, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (65, 'Ganganagar', 'RA06', 'CITY', 74, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (66, 'Gangtok', 'SI01', 'CITY', 75, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (67, 'Gaya', 'BI03', 'CITY', 76, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (68, 'Ghaziabad', 'UP12', 'CITY', 77, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (69, 'Goa', 'GO00', 'CITY', 78, 'MH04', 'MH04', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (70, 'Gorakhpur', 'UP13', 'CITY', 79, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (71, 'Gulbarga', 'KA06', 'CITY', 81, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (72, 'Gulmarg', 'JK01', 'CITY', 82, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (73, 'Guntur', 'AP02', 'CITY', 83, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (74, 'Gurdaspur', 'PU05', 'CITY', 84, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (75, 'Gurgaon', 'HA03', 'CITY', 85, 'UP25', 'HA03', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (76, 'Guwahati', 'AS03', 'CITY', 86, 'UP25', 'AS03', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (77, 'Gwalior', 'MP07', 'CITY', 87, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (78, 'Hapur', 'UP14', 'CITY', 88, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (79, 'Haridwar', 'UP15', 'CITY', 89, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (80, 'Hoshiarpur', 'PU06', 'CITY', 92, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (81, 'Hubli', 'KA07', 'CITY', 93, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (82, 'Hyderabad', 'AP03', 'CITY', 94, 'AP03', 'AP03', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (83, 'Imphal', 'MA01', 'CITY', 95, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (84, 'Indore', 'MP08', 'CITY', 96, 'UP25', 'MP08', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (85, 'Itanagar', 'AR01', 'CITY', 97, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (86, 'Jabalpur', 'MP09', 'CITY', 98, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (87, 'Jaipur', 'RA07', 'CITY', 99, 'UP25', 'RA07', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (88, 'Jaisalmer', 'RA11', 'CITY', 100, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (89, 'Jalandhar', 'PU10', 'CITY', 101, 'PH00', 'PH00', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (90, 'Jammu', 'JK04', 'CITY', 102, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (91, 'Jamshedpur', 'BI04', 'CITY', 104, 'UP25', 'BI04', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (92, 'Jhansi', 'UP16', 'CITY', 105, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (93, 'Jodhpur', 'RA08', 'CITY', 107, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (94, 'Jorhat', 'AS04', 'CITY', 108, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (95, 'Junagadh', 'GU06', 'CITY', 109, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (96, 'Kakinada', 'AP04', 'CITY', 110, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (97, 'Kandla', 'GU07', 'CITY', 111, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (98, 'Kannauj', 'UP17', 'CITY', 112, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (99, 'Kanniyakumari', 'TN07', 'CITY', 113, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (100, 'Kanpur', 'UP18', 'CITY', 114, 'UP25', 'UP18', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (101, 'Kasauli', 'HP02', 'CITY', 116, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (102, 'Khajuraho', 'MP10', 'CITY', 118, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (103, 'Kharagpur', 'WB04', 'CITY', 119, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (105, 'Kodaikanal', 'TN08', 'CITY', 120, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (106, 'Kohima', 'NA02', 'CITY', 121, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (107, 'Kolhapur', 'MH03', 'CITY', 122, 'MH04', 'MH04', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (108, 'Kolkata', 'WB05', 'CITY', 123, 'WB05', 'WB05', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (109, 'Kota', 'RA09', 'CITY', 124, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (110, 'Kottayam', 'KE04', 'CITY', 125, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (111, 'Kovalam', 'KE05', 'CITY', 126, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (112, 'Kozhikode', 'KE06', 'CITY', 127, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (113, 'Kurnool', 'AP05', 'CITY', 128, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (114, 'Leh', 'JK02', 'CITY', 130, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (115, 'Lucknow', 'UP19', 'CITY', 131, 'UP25', 'UP19', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (116, 'Ludhiana', 'PU07', 'CITY', 132, 'UP25', 'PU07', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (117, 'Machilipatnam', 'AP06', 'CITY', 133, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (118, 'Madurai', 'TN09', 'CITY', 135, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (119, 'Mangalore', 'KA08', 'CITY', 137, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (120, 'Mathura', 'UP20', 'CITY', 139, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (121, 'Meerut', 'UP21', 'CITY', 140, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (122, 'Moradabad', 'UP22', 'CITY', 143, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (123, 'Mumbai', 'MH04', 'CITY', 144, 'MH04', 'MH04', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (124, 'Mussoorie', 'UP23', 'CITY', 145, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (125, 'Muzaffarnagar', 'UP24', 'CITY', 146, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (126, 'Muzaffarpur', 'BI05', 'CITY', 147, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (127, 'Mysore', 'KA09', 'CITY', 148, 'UP25', 'KA09', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (128, 'Nagpur', 'MH05', 'CITY', 150, 'MH04', 'MH05', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (129, 'Nanded', 'MH06', 'CITY', 151, 'MH08', 'MH08', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (131, 'Nilgiri', 'TN10', 'CITY', 155, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (132, 'Nellore', 'AP07', 'CITY', 154, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (133, 'Noida', 'UP25', 'CITY', 156, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (134, 'Palakkad', 'KE07', 'CITY', 159, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (135, 'Palampet', 'AP08', 'CITY', 160, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (136, 'Palanpur', 'GU08', 'CITY', 161, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (137, 'Paradeep', 'OR03', 'CITY', 164, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (138, 'Pathankot', 'PU08', 'CITY', 165, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (139, 'Patiala', 'PU09', 'CITY', 166, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (140, 'Patna', 'BI06', 'CITY', 167, 'UP25', 'BI06', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (141, 'Periyar', 'TN11', 'CITY', 168, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (142, 'Pondicherry', 'PO00', 'CITY', 169, 'UP25', 'PO00', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (143, 'Pune', 'MH08', 'CITY', 170, 'MH08', 'MH08', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (144, 'Rae Bareli', 'UP26', 'CITY', 172, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (145, 'Rajahmundry', 'TN12', 'CITY', 174, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (146, 'Rajkot', 'GU09', 'CITY', 176, 'UP25', 'GU09', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (147, 'Rameswaram', 'TN13', 'CITY', 177, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (148, 'Ranchi', 'BI07', 'CITY', 178, 'UP25', 'BI07', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (149, 'Rishikesh', 'UP27', 'CITY', 179, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (150, 'Rohtak', 'HA04', 'CITY', 181, 'UP25', 'DE00', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (151, 'Roorkee', 'UP28', 'CITY', 182, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (152, 'Rourkela', 'OR04', 'CITY', 183, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (153, 'Saharanpur', 'UP29', 'CITY', 184, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (154, 'Salem', 'TN14', 'CITY', 186, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (155, 'Sangli', 'MH09', 'CITY', 187, 'MH08', 'MH08', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (156, 'Shillong', 'ME01', 'CITY', 189, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (157, 'Shimla', 'HP03', 'CITY', 190, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (158, 'Shirdi', 'MH10', 'CITY', 191, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (159, 'Silchar', 'AS05', 'CITY', 193, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (160, 'Sirsa', 'HA05', 'CITY', 194, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (161, 'Solapur', 'MH11', 'CITY', 195, 'MH08', 'MH08', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (162, 'Srinagar', 'JK03', 'CITY', 196, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (163, 'Surat', 'GU10', 'CITY', 197, 'UP25', 'GU10', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (164, 'Thane', 'MH12', 'CITY', 199, 'MH04', 'MH04', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (165, 'Thanjavur', 'TN15', 'CITY', 200, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (166, 'Thiruvananthapuram', 'KE08', 'CITY', 201, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (167, 'Tiruchirapalli', 'TN16', 'CITY', 202, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (168, 'Tirunelvelli', 'TN17', 'CITY', 203, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (169, 'Tuticorin', 'TN18', 'CITY', 207, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (170, 'Udaipur', 'RA10', 'CITY', 208, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (171, 'Ujjain', 'MP11', 'CITY', 209, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (172, 'Ulhasnagar', 'MH13', 'CITY', 210, 'MH04', 'MH04', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (173, 'Vadodara', 'GU11', 'CITY', 213, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (174, 'Varanasi', 'UP30', 'CITY', 215, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (175, 'Vellore', 'TN19', 'CITY', 216, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (176, 'Vijaywada', 'AP10', 'CITY', 217, 'AP03', 'AP10', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (177, 'Vishakhapatnam', 'AP11', 'CITY', 218, 'AP03', 'AP11', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (178, 'Warangal', 'AP09', 'CITY', 219, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (179, 'Andhra Pradesh', 'AP', 'STATE', 15, 'AP03', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (180, 'Arunachal Pradesh', 'AR', 'STATE', 19, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (181, 'Assam', 'AS', 'STATE', 21, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (182, 'Bihar', 'BI', 'STATE', 38, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (183, 'Chhattisgarh', 'CH', 'STATE', 44, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (184, 'Dadra & Nagar Haveli', 'DN', 'STATE', 51, 'MH08', 'MH08', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (185, 'Daman & Diu', 'DD', 'STATE', 53, 'MH08', 'MH08', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (186, 'Gujarat', 'GU', 'STATE', 80, 'UP25', 'UP25', 'Y', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (187, 'Haryana', 'HA', 'STATE', 90, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (188, 'Himachal Pradesh', 'HP', 'STATE', 91, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (189, 'Jammu & Kashmir', 'JK', 'STATE', 103, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (190, 'Jharkhand', 'JH', 'STATE', 106, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (191, 'Karnataka', 'KA', 'STATE', 115, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (192, 'Kerala', 'KE', 'STATE', 117, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (193, 'Lakshadweep', 'LA', 'STATE', 129, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (194, 'Madhya Pradesh', 'MP', 'STATE', 134, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (195, 'Maharashtra', 'MH', 'STATE', 136, 'MH04', 'MH04', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (196, 'Manipur', 'MA', 'STATE', 138, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (197, 'Meghalaya', 'ME', 'STATE', 141, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (198, 'Mizoram', 'MI', 'STATE', 142, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (199, 'Nagaland', 'NA', 'STATE', 149, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (200, 'Orissa', 'OR', 'STATE', 157, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (201, 'Punjab', 'PU', 'STATE', 171, 'PH00', 'PH00', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (202, 'Rajasthan', 'RA', 'STATE', 175, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (203, 'Sikkim', 'SI', 'STATE', 192, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (204, 'Tamil Nadu', 'TN', 'STATE', 198, 'TN02', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (205, 'Tripura', 'TR', 'STATE', 205, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (206, 'Uttar Pradesh', 'UP', 'STATE', 211, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (207, 'Uttaranchal', 'UT', 'STATE', 212, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (208, 'West Bengal', 'WB', 'STATE', 220, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (210, 'Others', 'OTHR', 'CITY', 158, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (211, 'Ahmednagar', 'UP31', 'CITY', 4, 'MH04', 'MH04', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (212, 'Panipat', 'HA06', 'CITY', 163, 'UP25', 'UP25', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (213, 'Trichy', 'TN20', 'CITY', 204, 'UP25', 'UP25', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (214, 'Vapi', 'GU12', 'CITY', 214, 'MH04', 'MH04', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (215, 'Raipur', 'MP12', 'CITY', 173, 'UP25', 'MP12', NULL, '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (216, 'Pandalam', 'KE09', 'CITY', 162, '', '', NULL, 'S');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (217, 'Trivandrum', 'TN20', 'CITY', 206, 'TN20', 'TN20', '', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (218, 'Nasik', 'MH24', 'CITY', 152, 'MH24', 'MH24', '', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (219, 'Navi Mumbai', 'MH28', 'CITY', 153, 'MH04', 'MH04', '', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (220, 'Bhayander', 'MH29', 'CITY', 32, 'MH04', 'MH04', '', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (221, 'Secunderabad', 'AP03', 'CITY', 188, 'AP03', 'AP03', '', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (222, 'Sahibabad', 'UP48', 'CITY', 185, 'DE00', 'DE00', '', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (223, 'Bahrain', 'BA01', 'CITY', 24, 'BA01', 'BA01', '', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (224, 'Dubai', '893', 'CITY', 62, '893', '893', '', '');
INSERT INTO `BRANCH_CITY` (`ID`, `LABEL`, `VALUE`, `TYPE`, `SORTBY`, `NEAR_BRANCH`, `PRIORITY`, `PICKUP`, `IN_REGION`) VALUES (225, 'Riyadh', '2261', 'CITY', 180, '2261', '2261', '', '');


