use MIS;
CREATE TABLE `PHOTO_FACEDETECTION_STATS` (
  `DATE` date NOT NULL,
  `PROCESSED_IMAGE_COUNT` smallint(5) unsigned DEFAULT NULL,
  `FACEDETECTED_IMAGE_COUNT` smallint(5) unsigned DEFAULT NULL,
  PRIMARY KEY (`DATE`)
) ENGINE=MYISAM DEFAULT CHARSET=latin1;

