use incentive;	

CREATE TABLE `FIELD_SALES_CITY` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `VALUE` varchar(4) DEFAULT NULL,
 `NAME` varchar(100) DEFAULT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=MyISAM;

INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (1, 'UP01', 'AGRA');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (2, 'UP06', 'BAREILLY');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (3, 'UK05', 'DEHRADUN');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (4, 'HA02', 'FARIDABAD');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (5, 'UP12', 'GHAZIABAD');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (6, 'UP47', 'GREATER NOIDA');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (7, 'HA03', 'GURGAON');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (8, 'UP21', 'MEERUT');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (9, 'RA07', 'JAIPUR');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (10, 'DE00', 'NEW DELHI');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (11, 'UP25', 'NOIDA');
INSERT INTO `FIELD_SALES_CITY` (`ID`, `VALUE`, `NAME`) VALUES (12, 'UP48', 'SAHIBABAD');

INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('Central Delhi', 'DE0010' ,'DE00');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('North Delhi', 'DE0011' ,'DE00');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('North West Delhi', 'DE0012' ,'DE00');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('South West Delhi', 'DE0013' ,'DE00');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('South Delhi', 'DE0014' ,'DE00');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('West Delhi', 'DE0015' ,'DE00');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('East Delhi', 'DE0016' ,'DE00');

use jsadmin;
ALTER TABLE `AGENT_ALLOTED` ADD CENTER varchar(50) DEFAULT ''; 

INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'AGRA');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'BAREILLY');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'DEHRADUN');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'FARIDABAD');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'GHAZIABAD');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'GURGAON');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'MEERUT');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'JAIPUR');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'NOIDA');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'Central Delhi');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'North Delhi');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'North West Delhi');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'South West Delhi');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'South Delhi');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'West Delhi');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`) VALUES ('', 'FIELD_SALES', 'East Delhi');

use incentive;
INSERT INTO `LAST_HANDLED_DATE` VALUES (10, 'FIELD_SALES', '0000-00-00 00:00:00', 0);

use jsadmin;
ALTER TABLE jsadmin.AGENT_ALLOTED ADD ALLOCATION_LIMIT tinyint(4) default 0;
ALTER TABLE jsadmin.PSWRDS ADD FIRST_NAME varchar(50);
ALTER TABLE jsadmin.PSWRDS ADD LAST_NAME varchar(50);
update jsadmin.AGENT_ALLOTED SET ALLOCATION_LIMIT='100' WHERE METHOD='FIELD_SALES';
ALTER TABLE jsadmin.PSWRDS ADD PHOTO_URL varchar(100) default '';


