use newjs;

ALTER TABLE  `SEARCHQUERY` ADD  `ISEARCH_PROFILEID` INT( 11 ) UNSIGNED NOT NULL ,ADD  `TRACKING_COOKIE_ID` VARCHAR( 20 ) NOT NULL ;

use MIS;

ALTER TABLE  `SEARCHQUERY_TEMP` ADD  `ISEARCH_PROFILEID` INT( 11 ) UNSIGNED NOT NULL ,ADD  `TRACKING_COOKIE_ID` VARCHAR( 20 ) NOT NULL ;

ALTER TABLE  `SEARCHQUERY` RENAME  `SEARCHQUERY_UPTO_MIDJULY2013` ;

CREATE TABLE SEARCHQUERY LIKE newjs.SEARCHQUERY
