use billing;

UPDATE `SERVICES` SET `NAME` = 'e-Rishta -15 days',`PRICE_RS` = '630.01',`PRICE_RS_TAX` = '695',`PRICE_DOL` = '14' WHERE SERVICEID='P2W';

UPDATE `COMPONENTS` SET `DURATION` = '0.5' WHERE COMPID='F2W';

UPDATE `SERVICES` SET `NAME` = 'JustPay-Special Offer',`PRICE_RS` = '452.4',`PRICE_RS_TAX` = '499',`PRICE_DOL` = '10' WHERE SERVICEID='C1W';

UPDATE `COMPONENTS` SET `DURATION` = '0.07',`RIGHTS` = 'F' WHERE COMPID='D1W';

UPDATE `DIRECT_CALL_COUNT` SET `COUNT` = '0' where SERVICEID='C1W' LIMIT 1;

UPDATE `DIRECT_CALL_COUNT` SET `COUNT` = '0' where SERVICEID='P1W' LIMIT 1;
