use newjs;

CREATE TABLE `UNMATCHED_NAKSHATRA_MATCHASTRO` (
  `ID` int(3) NOT NULL auto_increment,
  `NAME` varchar(50) default NULL,
  `PROFILEID` mediumint(11) unsigned default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM;

CREATE TABLE `UNMATCHED_RASHI_MATCHASTRO` (
  `ID` int(3) NOT NULL auto_increment,
  `NAME` varchar(50) default NULL,
  `PROFILEID` mediumint(11) unsigned default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM;


CREATE TABLE `NAKSHATRA_MATCHASTRO` (
  `ID` int(3) NOT NULL auto_increment,
  `NAME` varchar(50) default NULL,
  `VALUE` int(3) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM;
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (1, 'Revati', 20);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (2, 'Dhanishtha', 8);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (3, 'Jyeshtha', 10);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (4, 'Mrigasira', 14);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (5, 'Chitra', 7);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (6, 'Hasta', 9);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (7, 'Visakha', 28);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (8, 'Punarvasu', 18);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (9, 'Purvabhadrapada', 15);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (10, 'Svati', 24);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (11, 'Aswini', 5);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (12, 'Uttaraphalguni', 26);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (13, 'Bharani', 6);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (14, 'Sravana', 23);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (15, 'Rohini', 21);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (16, 'Purvaphalguni', 17);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (17, 'Uttarabhadrapada', 25);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (18, 'Mula', 13);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (19, 'Anuradha', 2);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (20, 'Satabhishak', 22);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (21, 'Krittika', 11);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (22, 'Ardra', 3);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (23, 'Purvashadha', 16);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (24, 'Uttarashadha', 27);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (25, 'Magha', 12);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (26, 'Pushya', 19);
INSERT INTO `NAKSHATRA_MATCHASTRO` VALUES (27, 'Aslesha', 4);
        



CREATE TABLE `RASHI_MATCHASTRO` (
  `ID` int(3) NOT NULL auto_increment,
  `NAME` varchar(50) default NULL,
  `VALUE` int(3) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM;
INSERT INTO `RASHI_MATCHASTRO` VALUES (1, 'Don''t Know', 1);
INSERT INTO `RASHI_MATCHASTRO` VALUES (2, 'Mesh', 2);
INSERT INTO `RASHI_MATCHASTRO` VALUES (3, 'Vrishabh', 3);
INSERT INTO `RASHI_MATCHASTRO` VALUES (4, 'Mithun', 4);
INSERT INTO `RASHI_MATCHASTRO` VALUES (5, 'Kark', 5);
INSERT INTO `RASHI_MATCHASTRO` VALUES (6, 'Simh', 6);
INSERT INTO `RASHI_MATCHASTRO` VALUES (7, 'Kanya', 7);
INSERT INTO `RASHI_MATCHASTRO` VALUES (8, 'Tula', 8);
INSERT INTO `RASHI_MATCHASTRO` VALUES (9, 'Vrischik', 9);
INSERT INTO `RASHI_MATCHASTRO` VALUES (10, 'Dhanu', 10);
INSERT INTO `RASHI_MATCHASTRO` VALUES (11, 'Makar', 11);
INSERT INTO `RASHI_MATCHASTRO` VALUES (12, 'Kumbh', 12);
INSERT INTO `RASHI_MATCHASTRO` VALUES (13, 'Meen', 13);

use MIS;
CREATE TABLE `TRACK_ASTRO_DETAILS` (
  `ID` int(5) NOT NULL auto_increment,
  `PROFILEID` mediumint(11) unsigned default NULL,
  `OLD_RASHI` varchar(20) default NULL,
  `OLD_MANGLIK` varchar(20) default NULL,
  `OLD_NAKSHATRA` varchar(20) default NULL,
  `OLD_SUNSIGN` varchar(20) default NULL,
  `CHANGE_DATE` datetime default '0000-00-00 00:00:00',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM;

