use jsadmin;
ALTER TABLE `SCREENING_LOG` ADD `PROFILE_HANDLER_NAME` varchar(40),
        ADD `GOTHRA_MATERNAL` varchar(250),
        ADD `COMPANY_NAME` text,
		ADD `FAV_MOVIE` text,
        ADD `FAV_TVSHOW` text,
        ADD `FAV_FOOD` text,
        ADD `FAV_BOOK` text,
        ADD `FAV_VAC_DEST` text,
        ADD `BLACKBERRY` Varchar(10),
        ADD `LINKEDIN_URL` text,
        ADD `FB_URL` text,
        ADD `ALT_MOBILE_OWNER_NAME` varchar(40),
        ADD `ALT_MESSENGER_ID` Varchar(50),
        ADD `PG_COLLEGE` text,
        ADD `OTHER_UG_DEGREE` varchar(250),
        ADD `OTHER_PG_DEGREE` varchar(250),
        ADD `SCHOOL` text,
        ADD `COLLEGE` text,
		MODIFY `SCREENING` BIGINT( 15 ) UNSIGNED DEFAULT '0';
ALTER TABLE `SCREENING_LOG1` ADD `PROFILE_HANDLER_NAME` varchar(40),
        ADD `GOTHRA_MATERNAL` varchar(250),
        ADD `COMPANY_NAME` text,
		ADD `FAV_MOVIE` text,
        ADD `FAV_TVSHOW` text,
        ADD `FAV_FOOD` text,
        ADD `FAV_BOOK` text,
        ADD `FAV_VAC_DEST` text,
        ADD `BLACKBERRY` Varchar(10),
        ADD `LINKEDIN_URL` text,
        ADD `FB_URL` text,
        ADD `ALT_MOBILE_OWNER_NAME` varchar(40),
        ADD `ALT_MESSENGER_ID` Varchar(50),
        ADD `PG_COLLEGE` text,
        ADD `OTHER_UG_DEGREE` varchar(250),
        ADD `OTHER_PG_DEGREE` varchar(250),
        ADD `SCHOOL` text,
        ADD `COLLEGE` text,
		MODIFY `SCREENING` BIGINT( 15 ) UNSIGNED DEFAULT '0';
ALTER TABLE `SCREENING_LOG2` ADD `PROFILE_HANDLER_NAME` varchar(40),
        ADD `GOTHRA_MATERNAL` varchar(250),
        ADD `COMPANY_NAME` text,
		ADD `FAV_MOVIE` text,
        ADD `FAV_TVSHOW` text,
        ADD `FAV_FOOD` text,
        ADD `FAV_BOOK` text,
        ADD `FAV_VAC_DEST` text,
        ADD `BLACKBERRY` Varchar(10),
        ADD `LINKEDIN_URL` text,
        ADD `FB_URL` text,
        ADD `ALT_MOBILE_OWNER_NAME` varchar(40),
        ADD `ALT_MESSENGER_ID` Varchar(50),
        ADD `PG_COLLEGE` text,
        ADD `OTHER_UG_DEGREE` varchar(250),
        ADD `OTHER_PG_DEGREE` varchar(250),
        ADD `SCHOOL` text,
        ADD `COLLEGE` text,
		MODIFY `SCREENING` BIGINT( 15 ) UNSIGNED DEFAULT '0';
ALTER TABLE `SCREEN_TEMP_CHECK` ADD `PROFILE_HANDLER_NAME` varchar(40),
        ADD `GOTHRA_MATERNAL` varchar(250),
        ADD `COMPANY_NAME` text,
		ADD `FAV_MOVIE` text,
        ADD `FAV_TVSHOW` text,
        ADD `FAV_FOOD` text,
        ADD `FAV_BOOK` text,
        ADD `FAV_VAC_DEST` text,
        ADD `BLACKBERRY` Varchar(10),
        ADD `LINKEDIN_URL` text,
        ADD `FB_URL` text,
        ADD `ALT_MOBILE_OWNER_NAME` varchar(40),
        ADD `ALT_MESSENGER_ID` Varchar(50),
        ADD `PG_COLLEGE` text,
        ADD `OTHER_UG_DEGREE` varchar(250),
        ADD `OTHER_PG_DEGREE` varchar(250),
        ADD `SCHOOL` text,
        ADD `COLLEGE` text;
