use newjs;
ALTER TABLE SEARCHQUERY ADD LVERIFY_ACTIVATED_DT DATETIME NOT NULL , ADD HVERIFY_ACTIVATED_DT DATETIME NOT NULL ;

use MIS;
RENAME TABLE SEARCHQUERY TO SEARCHQUERY_AUGUST2014;
CREATE TABLE SEARCHQUERY LIKE SEARCHQUERY_AUGUST2014;
ALTER TABLE SEARCHQUERY_TEMP ADD LVERIFY_ACTIVATED_DT DATETIME NOT NULL , ADD HVERIFY_ACTIVATED_DT DATETIME NOT NULL ;

CREATE DATABASE search;
use search;
CREATE TABLE JUST_JOINED_LAST_USED (
 PROFILEID int(11) unsigned NOT NULL,
 LAST_USED_DT datetime NOT NULL,
 PRIMARY KEY (PROFILEID)
) ENGINE=MYISAM;
