use MIS;
CREATE TABLE `MOBILE_ACTIVITY_LOG` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_id` varchar(50) NOT NULL,
  `user_id` int(10) DEFAULT NULL,
  `activity_type` varchar(50) NOT NULL,
  `activity_type_value` varchar(50) NOT NULL,
  `user_agent` varchar(1000) NOT NULL,
  `current_url` varchar(500) NOT NULL,
  `ref_url` varchar(500) NOT NULL,
  `perceived_loadtime_page` float DEFAULT NULL,
  `time_head_page_ready` float DEFAULT NULL,
  `time_head_page_first_byte` float DEFAULT NULL,
  `boomr_pageid` varchar(50) DEFAULT NULL,
  `t_head` float DEFAULT NULL,
  `t_body` float DEFAULT NULL,
  `server_p_time` float DEFAULT NULL,
  `bandwidth` float DEFAULT NULL,
  `bandwidth_err` float DEFAULT NULL,
  `latency` float DEFAULT NULL,
  `latency_err` float DEFAULT NULL,
  `hml5applicationcache` int(1) DEFAULT '0',
  `hml5canvas` int(1) DEFAULT '0',
  `hml5frmdate` int(1) DEFAULT '0',
  `hml5frmsautofocus` int(1) DEFAULT '0',
  `hml5geolocation` int(1) DEFAULT '0',
  `hml5history` int(1) DEFAULT '0',
  `hml5localstorage` int(1) DEFAULT '0',
  `hml5video` int(1) DEFAULT '0',
  `hml5webworkers` int(1) DEFAULT '0',
  `ip_address` int(50) DEFAULT NULL,
  `logged_at` datetime NOT NULL,
  `noscript` int(1) NOT NULL DEFAULT '0',
   `PD` VARCHAR( 20 ),
   `SW` VARCHAR( 20 ),
    PO varchar(20),
  PRIMARY KEY (`id`)
);

CREATE TABLE `MOBILE_ACTIVITY_CSSLOG` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_id` varchar(50) NOT NULL,
  `user_id` int(10) DEFAULT NULL,
  `activity_type` varchar(50) NOT NULL,
  `user_agent` varchar(1000) NOT NULL,
  `mediaqueries` int(1) DEFAULT '0',
  `fontface` int(1) DEFAULT '0',
  `borderimage` int(1) DEFAULT '0',
  `borderradius` int(1) DEFAULT '0',
  `boxshadow` int(1) DEFAULT '0',
  `flexbox` int(1) DEFAULT '0',
  `opacity` int(1) DEFAULT '0',
  `cssanimations` int(1) DEFAULT '0',
  `cssgradients` int(1) DEFAULT '0',
  `cssreflections` int(1) DEFAULT '0',
  `csstransforms` int(1) DEFAULT '0',
  `csstransitions` int(1) DEFAULT '0',
  `logged_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
);

