use billing;

ALTER TABLE `PAYMENT_DETAIL` CHANGE `SOURCE` `SOURCE` ENUM( 'CASH', 'CHEQUE', 'ONLINE', 'TT', 'DD', 'OTHER', 'CREDIT', 'CCOFFLINE', 'BANK_TRSFR_ONLINE', 'EB_CASH', 'EB_CHEQUE', 'BANK_TRSFR_CHQ', 'BANK_TRSFR_CASH', 'IVR', 'BLUEDART_COD' ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'CASH';
