use MIS;
CREATE TABLE `FTA_EFFICIENCY` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `TYPE` char(15) DEFAULT NULL,
  `EXECUTIVE` varchar(50) NOT NULL,
  `DATE` datetime NOT NULL,
  `ENTRY_DT` datetime DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROFILEID` (`PROFILEID`,`TYPE`,`EXECUTIVE`)
) ENGINE=MyISAM AUTO_INCREMENT=41 DEFAULT CHARSET=latin1;

use incentive;

CREATE TABLE `FTA_DATA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) NOT NULL,
  `CALLED_DATE` datetime NOT NULL,
  `EXECUTIVE` varchar(25) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
