use mmmjs;

alter table MAILERYN add USER6 int, add USER7 INT, ADD USER8 INT, CHANGE USER1 USER1 INT, CHANGE USER2 USER2 INT, CHANGE USER3 USER3 INT, CHANGE USER4 USER4 INT, CHANGE USER5 USER5 INT, CHANGE RECEIVER RECEIVER INT;

alter table EMAILSUM2S1 CHANGE PROFILEID PROFILEID INT;
