use MIS;
CREATE TABLE `MONTHLY_INCENTIVE_ELIGIBILITY` (
 `RECEIPTID` int(11) NOT NULL,
 `BILLID` int(11) NOT NULL,
 `PROFILEID` int(11) NOT NULL,
 `ALLOTED_TO` varchar(50) NOT NULL,
 `CENTER` varchar(50) DEFAULT NULL,
 `AMOUNT` int(11) NOT NULL,
 `ENTRY_DT` datetime NOT NULL,
 UNIQUE KEY `RECEIPTID` (`RECEIPTID`,`BILLID`),
 KEY `ENTRY_DT` (`ENTRY_DT`),
 KEY `ALLOTED_TO` (`ALLOTED_TO`)
) ENGINE=InnoDB
