use newjs;
create table COMMUNITY_PAGES_JAN select * from COMMUNITY_PAGES;
create table COMMUNITY_PAGES_MAPPING_JAN select * from COMMUNITY_PAGES_MAPPING;
update COMMUNITY_PAGES set TITLE=concat_ws(" ",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Matrimonials – Matrimony Services for",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"-",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Marriage"),DESCRIPTION=concat_ws(" ","Search",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"brides and grooms in India's leading matrimony site, Jeevansathi.com . Find from lakhs of registered profiles from India and abroad and get matchmaking services."),KEYWORDS="" where PAGE_SOURCE='N';
update COMMUNITY_PAGES set TITLE=concat_ws(" ",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Brides -",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Girls -",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Bride -",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Girl -",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Matrimonials"),DESCRIPTION=concat_ws(" ","Find",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Bride in India's leading matrimony site, Jeevansathi.com . Register now and search from thousands of profiles of",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"brides"),KEYWORDS="" where PAGE_SOURCE="B";
update COMMUNITY_PAGES set TITLE=concat_ws(" ",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Grooms -",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Boys -",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Groom -",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Boy -",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Matrimonials"),DESCRIPTION=concat_ws(" ","Complete your matrimony search for",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Groom in Jeevansathi.com , India's leading matrimonial site. Join free & search for suitable",REPLACE(REPLACE(REPLACE(IF(SMALL_LABEL!="",  SMALL_LABEL,LABEL_NAME),"/"," "),"-"," "),":",""),"Grooms"),KEYWORDS="" where PAGE_SOURCE="G";

UPDATE  `COMMUNITY_PAGES_MAPPING` SET  `MAPPED_LABEL` =  'Rohilla/Tank' WHERE  `ID` =  '3639' ;
UPDATE  `COMMUNITY_PAGES_MAPPING` SET  `MAPPED_LABEL` =  'Rohilla/Tank' WHERE  `ID` =  '5319' ;
UPDATE  `COMMUNITY_PAGES_MAPPING` SET  `MAPPED_LABEL` =  'Rohilla/Tank' WHERE  `ID` =  '6993' ;
update COMMUNITY_PAGES_MAPPING set PARENT_LABEL='Parsi' where PARENT_VALUE=5 and PARENT_TYPE='RELIGION';
update COMMUNITY_PAGES_MAPPING set TITLE=concat_ws(" ",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Matrimonials – Matrimony Services for",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"-",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Marriage"), DESCRIPTION=concat_ws(" ","Search",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"brides and grooms in India's leading matrimony site, Jeevansathi.com . Find from lakhs of registered profiles from India and abroad and get matchmaking services."), KEYWORDS="" where PAGE_SOURCE='N';
update COMMUNITY_PAGES_MAPPING set TITLE=concat_ws(" ",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Brides -",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Girls -",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Bride -",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Girl -",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Matrimonials"),DESCRIPTION=concat_ws(" ","Find",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Bride in India's leading matrimony site, Jeevansathi.com . Register now and search from thousands of profiles of",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"brides"),KEYWORDS="" where PAGE_SOURCE='B';
update COMMUNITY_PAGES_MAPPING set TITLE=concat_ws(" ",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Grooms -",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Boys -",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Groom -",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Boy -",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Matrimonials"),DESCRIPTION=concat_ws(" ","Complete your matrimony search for",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Groom in Jeevansathi.com , India's leading matrimonial site. Join free & search for suitable",REPLACE(REPLACE(concat_ws(" ",PARENT_LABEL,MAPPED_LABEL),"/"," "),"-"," "),"Grooms"),KEYWORDS="" where PAGE_SOURCE="G";
