use jsadmin;

CREATE TABLE `PROFILE_VERIFICATION_DOC_AUTOINCREMENT` (
  `AUTO_ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `NO_USE_VARIABLE` char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`AUTO_ID`),
  UNIQUE KEY `NO_USE_VARIABLE` (`NO_USE_VARIABLE`)
) ENGINE=MyISAM ;

CREATE TABLE `PROFILE_VERIFICATION_DOCUMENTS_SCREENING_TRACKING` (
  `DOCUMENT_ID` int(11) NOT NULL DEFAULT '0',
  `SCREENED_BY` varchar(20) DEFAULT NULL,
  `SCREENING_TIME` datetime NOT NULL,
  PRIMARY KEY (`DOCUMENT_ID`)
) ENGINE=MyISAM;

CREATE TABLE `PROFILE_VERIFICATION_DOCUMENTS_SCREENING` (
  `PROFILEID` int(11) NOT NULL DEFAULT '0',
  `ALLOTED_TIME` datetime DEFAULT '0000-00-00 00:00:00',
  `ASSIGNED_TO` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`PROFILEID`)
) ENGINE=MyISAM ;

CREATE TABLE `PROFILE_VERIFICATION_DOCUMENTS` (
  `DOCUMENT_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `PROFILEID` int(11) unsigned DEFAULT NULL,
  `ATTRIBUTE` enum('DOB','ADDRESS','PARENT_ADDRESS','HIGHEST_QUALIFICATION','INCOME','DIVORCE') DEFAULT NULL,
  `UPLOADED_DATE` datetime DEFAULT NULL,
  `DOCUMENT_TYPE` enum('PAN_CARD','DL','PASSPORT','CLASSX_PASSING_CERT','OTHER','VOTER_ID','RATION_CARD','PROPERTY_TAX_RECEIPT','RENT_AGREEMENT','MARKSHEET','DEGREE_CERT','TRANSCRIPT','SALARY_SLIP','OFFER_LTR','JOINING_LTR','INCREMENT_LTR','FORM16','ITR','COURT_ORDER') DEFAULT NULL,
  `DOC_FORMAT` enum('jpg','jpeg','gif') DEFAULT NULL,
  `VERIFIED_FLAG` enum('Y','N','U') NOT NULL DEFAULT 'U',
  `DELETED_FLAG` enum('Y','N') DEFAULT 'N',
  `DOCURL` varchar(200) DEFAULT NULL,
  `UPLOADED_BY` varchar(20) DEFAULT NULL,
  `VERIFICATION_VALUE` text,
  PRIMARY KEY (`DOCUMENT_ID`),
  KEY `PROFILEID` (`PROFILEID`),
  KEY `VERIFIED_FLAG` (`VERIFIED_FLAG`)
) ENGINE=MyISAM;

CREATE TABLE `DELETED_PROFILE_VERIFICATION_DOCUMENTS` (
  `DOCUMENT_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `DELETED_DATE` datetime DEFAULT NULL,
  `DELETED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`DOCUMENT_ID`)
) ENGINE=MyISAM;

set session sql_log_bin=0;
ALTER TABLE `DELETED_PROFILE_VERIFICATION_DOCUMENTS` ENGINE = INNODB;
ALTER TABLE `PROFILE_VERIFICATION_DOCUMENTS` ENGINE = INNODB;
set session sql_log_bin=1;
