use profileInformation;
DROP TABLE IF EXISTS `ContactCenterAPP_CONFIG`;
CREATE TABLE `ContactCenterAPP_CONFIG` (
  `ID` tinyint(1) NOT NULL AUTO_INCREMENT,
  `INFO_TYPE` varchar(30) DEFAULT NULL,
  `SORT_ORDER` tinyint(1) unsigned DEFAULT NULL,
  `COUNT` tinyint(1) unsigned DEFAULT NULL,
  `TUPLE` varchar(25) DEFAULT NULL,
  `TUPLE_ORDER` varchar(25) DEFAULT NULL,
  `ACTIVE_FLAG` char(1) DEFAULT NULL,
  `AJAX_FLAG` char(1) DEFAULT NULL,
  `CALLOUT_MESSAGES` varchar(100) DEFAULT NULL,
  `VIEW_ALL_LINK` varchar(100) DEFAULT NULL,
  `TITLE` varchar(50) DEFAULT NULL,
  `SUBTITLE` varchar(50) DEFAULT NULL,
  `ICONS` varchar(50) DEFAULT NULL,
  `BUTTONS` varchar(50) DEFAULT NULL,
  `TRACKING` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `INFO_TYPE` (`INFO_TYPE`)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=latin1 AUTO_INCREMENT=10 ;

-- 
-- Dumping data for table `ContactCenterAPP_CONFIG`
-- 

INSERT INTO `ContactCenterAPP_CONFIG` VALUES (1, 'INTEREST_RECEIVED', NULL, 10, 'INBOX_EOI_APP', 'TIME', 'Y', 'N', NULL, NULL, 'People to Respond to', NULL, '', 'ACCEPT|DECLINE', 'responseTracking=11');
INSERT INTO `ContactCenterAPP_CONFIG` VALUES (2, 'ACCEPTANCES_RECEIVED', NULL, 10, 'INBOX_APP', NULL, 'Y', 'N', NULL, NULL, 'Accepted Members', 'Who Accepted me', NULL, 'MESSAGE|CONTACT', '');
INSERT INTO `ContactCenterAPP_CONFIG` VALUES (3, 'ACCEPTANCES_SENT', NULL, 10, 'INBOX_APP', NULL, 'Y', 'N', NULL, NULL, 'Accepted Members', 'Accepted By Me', NULL, 'MESSAGE|CONTACT', '');
INSERT INTO `ContactCenterAPP_CONFIG` VALUES (4, 'MY_MESSAGE', NULL, 10, 'MYJS_MESSAGE_APP', NULL, 'Y', 'N', NULL, NULL, 'My Messages', NULL, NULL, NULL, '');
INSERT INTO `ContactCenterAPP_CONFIG` VALUES (5, 'VISITORS', NULL, 10, 'INBOX_APP', NULL, 'Y', 'N', NULL, NULL, 'Recent Profile Visitors', NULL, NULL, 'INITIATE|SHORTLIST|PHOTO|CONTACT', 'stype=AV');
INSERT INTO `ContactCenterAPP_CONFIG` VALUES (6, 'INTEREST_SENT', NULL, 10, 'INBOX_APP', NULL, 'Y', 'N', NULL, NULL, 'Interests Sent', NULL, NULL, 'REMINDER|CANCEL|CONTACT', '');
INSERT INTO `ContactCenterAPP_CONFIG` VALUES (7, 'MATCH_ALERT', NULL, 10, 'INBOX_APP', NULL, 'Y', 'N', NULL, NULL, 'Match Alerts', NULL, NULL, 'INITIATE|SHORTLIST|PHOTO|CONTACT', 'stype=AM');
INSERT INTO `ContactCenterAPP_CONFIG` VALUES (8, 'SHORTLIST', NULL, 10, 'SHORTLIST_APP', 'TIME', 'Y', 'N', NULL, NULL, 'Shortlisted Profiles', NULL, NULL, NULL, 'stype=AS&responseTracking=12');
INSERT INTO `ContactCenterAPP_CONFIG` VALUES (9, 'PHOTO_REQUEST_RECEIVED', NULL, 10, 'INBOX_APP', NULL, 'Y', 'N', NULL, NULL, 'Photo Request Received', NULL, NULL, NULL, '');
