CREATE TABLE MIS.SUMMARY_RESPONSE_TRACKING (
 `CONTACT_TYPE` enum('A','D','C','E') NOT NULL DEFAULT 'A',
 `TRACKING_STRING` varchar(11) NOT NULL,
 `COUNT` smallint(5) unsigned DEFAULT NULL,
 `DATE` date NOT NULL,
 PRIMARY KEY (`CONTACT_TYPE`,`TRACKING_STRING`,`DATE`),
 KEY `DATE` (`DATE`)
);
