use mailer;

CREATE TABLE `PA_MAILER_POOL` (
 `RECEIVER` int(11) NOT NULL DEFAULT '0',
 `SENDER` int(11) DEFAULT NULL,
 `SENT` char(2) DEFAULT NULL,
 PRIMARY KEY (`RECEIVER`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1
?>
