CREATE DATABASE PICTURE;
USE PICTURE;

CREATE TABLE `PHOTOSCREEN_MASTER_TRACKING` (
 `PROFILEID` int(11) NOT NULL,
 `PROFILE_TYPE` enum('E','N') DEFAULT NULL,
 `UPLOADDATE` datetime NOT NULL,
 `PREPROCESS_COMPLETION_TIME` datetime NOT NULL,
 `ACCEPT_REJECT_Q_COMPLETION_TIME` datetime DEFAULT NULL,
 `PROCESS_Q_COMPLETION_TIME` datetime DEFAULT NULL,
 `SCREENING_COMPLETION_QUEUE_NAME` enum('AR','PROCESS') DEFAULT NULL,
 KEY `PROFILEID` (`PROFILEID`,`PROFILE_TYPE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

USE MIS;
ALTER TABLE `PHOTO_SCREEN_STATS` ADD `INTERFACE_NAME` ENUM( 'AR', 'PROCESS' ) ;

ALTER TABLE `PHOTO_SCREEN_STATS` ADD INDEX ( `SCREENED_BY` , `INTERFACE_NAME` , `DATE` ) ;

ALTER TABLE `PHOTO_SCREEN_STATS` ADD `NEW_MARKED_FOR_EDITING` INT( 5 ) DEFAULT '0' AFTER `EDIT_DEL_PHOTOS` ,
ADD `EDIT_MARKED_FOR_EDITING` INT( 5 )  DEFAULT '0' AFTER `NEW_MARKED_FOR_EDITING` ;
