UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'P2' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'B2' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'D2' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'C2' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'A2' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'T2' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'M2' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'L2' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'I20' LIMIT 1 ;

UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'P3' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'B3' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'D3' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'C3' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'A3' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'T3' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'M3' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'L3' LIMIT 1 ;

UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'P4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'B4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'D4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'C4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'A4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'T4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'M4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'L4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'N' WHERE `SERVICEID` = 'I40' LIMIT 1 ;
