use newjs;
CREATE TABLE `JPROFILE_ALERTS_LOG` (
 `PROFILEID` int(11) NOT NULL,
 `MEMB_CALLS` char(1) NOT NULL,
 `OFFER_CALLS` char(1) NOT NULL,
 `SERV_CALLS_SITE` char(1) NOT NULL,
 `SERV_CALLS_PROF` char(1) NOT NULL,
 `MEMB_MAILS` char(1) NOT NULL,
 `CONTACT_ALERT_MAILS` char(1) NOT NULL,
 `KUNDLI_ALERT_MAILS` char(1) NOT NULL,
 `PHOTO_REQUEST_MAILS` char(1) NOT NULL,
 `NEW_MATCHES_MAILS` char(1) DEFAULT NULL,
 `SERVICE_SMS` char(1) NOT NULL,
 `SERVICE_MMS` char(1) NOT NULL,
 `SERVICE_USSD` char(1) NOT NULL,
 `PROMO_USSD` char(1) NOT NULL,
 `SERVICE_MAILS` char(1) NOT NULL,
 `PROMO_MMS` char(1) NOT NULL,
 `FROM_PAGE` char(1) NOT NULL,
 `MOD_DT` datetime NOT NULL,
 KEY `PROFILEID` (`PROFILEID`)
) ;
