use reg;
UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Caste :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '15' AND CONVERT(`GROUP` USING utf8) = 'c' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:CASTE' AND CONVERT(`LABEL` USING utf8) = 'Caste<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = '' LIMIT 1;

UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Religion :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '14' AND CONVERT(`GROUP` USING utf8) = 'c' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:RELIGION' AND CONVERT(`LABEL` USING utf8) = 'Religion<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = '' LIMIT 1;



UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Marital Status :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '11' AND CONVERT(`GROUP` USING utf8) = 'c' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:MSTATUS' AND CONVERT(`LABEL` USING utf8) = 'Marital Status<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = 'Please Select' LIMIT 1;



UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'City :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '10' AND CONVERT(`GROUP` USING utf8) = 'b' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:CITY_RES' AND CONVERT(`LABEL` USING utf8) = 'City<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = '' LIMIT 1;


UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Country living in :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '9' AND CONVERT(`GROUP` USING utf8) = 'b' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:COUNTRY_RES' AND CONVERT(`LABEL` USING utf8) = 'Country living in<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = '' LIMIT 1;

UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Height :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '8' AND CONVERT(`GROUP` USING utf8) = 'b' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:HEIGHT' AND CONVERT(`LABEL` USING utf8) = 'Height<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = 'Please Select' LIMIT 1;

UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Email :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '1' AND CONVERT(`GROUP` USING utf8) = 'a' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:EMAIL' AND CONVERT(`LABEL` USING utf8) = 'Email<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = '' LIMIT 1;

UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Password :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '2' AND CONVERT(`GROUP` USING utf8) = 'a' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:PASSWORD' AND CONVERT(`LABEL` USING utf8) = 'Password<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = '' LIMIT 1;



UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Create Profile For :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '3' AND CONVERT(`GROUP` USING utf8) = 'a' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:RELATION' AND CONVERT(`LABEL` USING utf8) = 'Create Profile For<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = 'Please Select' LIMIT 1;


UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Gender :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '4' AND CONVERT(`GROUP` USING utf8) = 'b' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:GENDER' AND CONVERT(`LABEL` USING utf8) = 'Gender<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = '' LIMIT 1;


UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Date of Birth :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '5' AND CONVERT(`GROUP` USING utf8) = 'b' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:DTOFBIRTH' AND CONVERT(`LABEL` USING utf8) = 'Date of Birth<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = '' LIMIT 1;


UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Mobile Number :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '18' AND CONVERT(`GROUP` USING utf8) = 'd' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:ISD-isd,PHONE_MOB-mobile' AND CONVERT(`LABEL` USING utf8) = 'Mobile Number<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = '' LIMIT 1;

 UPDATE `REG_EDIT_PAGE_FIELDS` SET `LABEL` = 'Pincode :' WHERE CONVERT(`PAGE` USING utf8) = 'DP1' AND `FIELD_ID` = '7' AND CONVERT(`GROUP` USING utf8) = 'b' AND CONVERT(`TABLE_NAME` USING utf8) = 'JPROFILE:PINCODE' AND CONVERT(`LABEL` USING utf8) = 'Pincode<u>*</u> :' AND CONVERT(`BLANK_VALUE` USING utf8) = '' AND CONVERT(`BLANK_LABEL` USING utf8) = '' LIMIT 1;

UPDATE  `REG_EDIT_PAGE_FIELDS` SET  `LABEL` =  'Native Place/ Hometown' WHERE CONVERT(  `PAGE` USING utf8 ) =  'DP3' AND  `FIELD_ID` =  '84' AND CONVERT(  `GROUP` USING utf8 ) =  '' AND CONVERT( `TABLE_NAME` USING utf8 ) =  'JPROFILE:ANCESTRAL_ORIGIN' AND CONVERT(  `LABEL` USING utf8 ) =  'Ancestral Origin <b style=\\"font-weight:normal;\\">( Native )</b> :' AND CONVERT(  `BLANK_VALUE` USING utf8 ) =  '' AND CONVERT(  `BLANK_LABEL` USING utf8 ) =  '' LIMIT 1 ;
