use matchalerts;

ALTER TABLE  `SEARCH_MALE` ADD  `MTONGUE_ZONE` CHAR( 1 ) NOT NULL ,ADD  `CITY_ZONE` CHAR( 1 ) NOT NULL ,ADD  `MSTATUS_MATCHALERT` CHAR( 1 ) NOT NULL ;
ALTER TABLE  `SEARCH_FEMALE` ADD  `MTONGUE_ZONE` CHAR( 1 ) NOT NULL ,ADD  `CITY_ZONE` CHAR( 1 ) NOT NULL ,ADD  `MSTATUS_MATCHALERT` CHAR( 1 ) NOT NULL ;
ALTER TABLE  `TRENDS_SEARCH_MALE` ADD  `MTONGUE_ZONE` CHAR( 1 ) NOT NULL ,ADD  `CITY_ZONE` CHAR( 1 ) NOT NULL ,ADD  `MSTATUS_MATCHALERT` CHAR( 1 ) NOT NULL ;
ALTER TABLE  `TRENDS_SEARCH_FEMALE` ADD  `MTONGUE_ZONE` CHAR( 1 ) NOT NULL ,ADD  `CITY_ZONE` CHAR( 1 ) NOT NULL ,ADD  `MSTATUS_MATCHALERT` CHAR( 1 ) NOT NULL ;
ALTER TABLE  `NOTRENDS_SEARCH_MALE` ADD  `MTONGUE_ZONE` CHAR( 1 ) NOT NULL ,ADD  `CITY_ZONE` CHAR( 1 ) NOT NULL ,ADD  `MSTATUS_MATCHALERT` CHAR( 1 ) NOT NULL ;
ALTER TABLE  `NOTRENDS_SEARCH_FEMALE` ADD  `MTONGUE_ZONE` CHAR( 1 ) NOT NULL ,ADD  `CITY_ZONE` CHAR( 1 ) NOT NULL ,ADD  `MSTATUS_MATCHALERT` CHAR( 1 ) NOT NULL ;

ALTER TABLE `SEARCH_MALE` ADD INDEX (EDU_LEVEL), ADD INDEX (INCOME), ADD INDEX (BTYPE), ADD INDEX (MTONGUE_ZONE), ADD INDEX (CITY_ZONE), ADD INDEX (MSTATUS_MATCHALERT);
ALTER TABLE `SEARCH_FEMALE` ADD INDEX (EDU_LEVEL), ADD INDEX (INCOME), ADD INDEX (BTYPE), ADD INDEX (MTONGUE_ZONE), ADD INDEX (CITY_ZONE), ADD INDEX (MSTATUS_MATCHALERT);
ALTER TABLE `TRENDS_SEARCH_MALE` ADD INDEX (EDU_LEVEL), ADD INDEX (OCCUPATION), ADD INDEX (BTYPE), ADD INDEX (MTONGUE_ZONE), ADD INDEX (CITY_ZONE), ADD INDEX (MSTATUS_MATCHALERT), ADD INDEX (HEIGHT), ADD INDEX (AGE);
ALTER TABLE `TRENDS_SEARCH_FEMALE` ADD INDEX (EDU_LEVEL), ADD INDEX (OCCUPATION), ADD INDEX (BTYPE), ADD INDEX (MTONGUE_ZONE), ADD INDEX (CITY_ZONE), ADD INDEX (MSTATUS_MATCHALERT), ADD INDEX (HEIGHT), ADD INDEX (AGE);

ALTER TABLE `NOTRENDS_SEARCH_MALE` ADD INDEX (EDU_LEVEL), ADD INDEX (OCCUPATION), ADD INDEX (BTYPE), ADD INDEX (MTONGUE_ZONE), ADD INDEX (CITY_ZONE), ADD INDEX (MSTATUS_MATCHALERT), ADD INDEX (HEIGHT), ADD INDEX (AGE);
ALTER TABLE `NOTRENDS_SEARCH_FEMALE` ADD INDEX (EDU_LEVEL), ADD INDEX (OCCUPATION), ADD INDEX (BTYPE), ADD INDEX (MTONGUE_ZONE), ADD INDEX (CITY_ZONE), ADD INDEX (MSTATUS_MATCHALERT), ADD INDEX (HEIGHT), ADD INDEX (AGE);

UPDATE `SEARCH_MALE` SET `MSTATUS_MATCHALERT` = IF(MSTATUS='N','N','M');
UPDATE `SEARCH_FEMALE` SET `MSTATUS_MATCHALERT` = IF(MSTATUS='N','N','M');
UPDATE `TRENDS_SEARCH_MALE` SET `MSTATUS_MATCHALERT` = IF(MSTATUS='N','N','M');
UPDATE `TRENDS_SEARCH_FEMALE` SET `MSTATUS_MATCHALERT` = IF(MSTATUS='N','N','M');
UPDATE `NOTRENDS_SEARCH_MALE` SET `MSTATUS_MATCHALERT` = IF(MSTATUS='N','N','M');
UPDATE `NOTRENDS_SEARCH_FEMALE` SET `MSTATUS_MATCHALERT` = IF(MSTATUS='N','N','M');

UPDATE SEARCH_MALE SET CITY_ZONE = IF(COUNTRY_RES=51,'','F');
UPDATE SEARCH_FEMALE SET CITY_ZONE = IF(COUNTRY_RES=51,'','F');
UPDATE TRENDS_SEARCH_MALE SET CITY_ZONE = IF(COUNTRY_RES=51,'','F');
UPDATE TRENDS_SEARCH_FEMALE SET CITY_ZONE = IF(COUNTRY_RES=51,'','F');
UPDATE NOTRENDS_SEARCH_MALE SET CITY_ZONE = IF(COUNTRY_RES=51,'','F');
UPDATE NOTRENDS_SEARCH_FEMALE SET CITY_ZONE = IF(COUNTRY_RES=51,'','F');

UPDATE SEARCH_MALE S,zone_mapping_table Z SET S.CITY_ZONE = Z.ZONE_CODE WHERE S.COUNTRY_RES = 51 AND SUBSTRING(S.CITY_RES,1,2) = Z.VALUE;
UPDATE SEARCH_FEMALE S,zone_mapping_table Z SET S.CITY_ZONE = Z.ZONE_CODE WHERE S.COUNTRY_RES = 51 AND SUBSTRING(S.CITY_RES,1,2) = Z.VALUE;
UPDATE TRENDS_SEARCH_MALE S,zone_mapping_table Z SET S.CITY_ZONE = Z.ZONE_CODE WHERE S.COUNTRY_RES = 51 AND SUBSTRING(S.CITY_RES,1,2) = Z.VALUE;
UPDATE TRENDS_SEARCH_FEMALE S,zone_mapping_table Z SET S.CITY_ZONE = Z.ZONE_CODE WHERE S.COUNTRY_RES = 51 AND SUBSTRING(S.CITY_RES,1,2) = Z.VALUE;
UPDATE NOTRENDS_SEARCH_MALE S,zone_mapping_table Z SET S.CITY_ZONE = Z.ZONE_CODE WHERE S.COUNTRY_RES = 51 AND SUBSTRING(S.CITY_RES,1,2) = Z.VALUE;
UPDATE NOTRENDS_SEARCH_FEMALE S,zone_mapping_table Z SET S.CITY_ZONE = Z.ZONE_CODE WHERE S.COUNTRY_RES = 51 AND SUBSTRING(S.CITY_RES,1,2) = Z.VALUE;

UPDATE matchalerts.SEARCH_MALE S, newjs.MTONGUE M SET S.MTONGUE_ZONE = IF(M.REGION=4,'N',IF(M.REGION=3,'W',IF(M.REGION=2,'S',IF(M.REGION=1,'E','F')))) WHERE M.REGION!=5 AND S.MTONGUE = M.VALUE;
UPDATE matchalerts.SEARCH_FEMALE S, newjs.MTONGUE M SET S.MTONGUE_ZONE = IF(M.REGION=4,'N',IF(M.REGION=3,'W',IF(M.REGION=2,'S',IF(M.REGION=1,'E','F')))) WHERE M.REGION!=5 AND S.MTONGUE = M.VALUE;
UPDATE matchalerts.TRENDS_SEARCH_MALE S, newjs.MTONGUE M SET S.MTONGUE_ZONE = IF(M.REGION=4,'N',IF(M.REGION=3,'W',IF(M.REGION=2,'S',IF(M.REGION=1,'E','F')))) WHERE M.REGION!=5 AND S.MTONGUE = M.VALUE;
UPDATE matchalerts.TRENDS_SEARCH_FEMALE S, newjs.MTONGUE M SET S.MTONGUE_ZONE = IF(M.REGION=4,'N',IF(M.REGION=3,'W',IF(M.REGION=2,'S',IF(M.REGION=1,'E','F')))) WHERE M.REGION!=5 AND S.MTONGUE = M.VALUE;
UPDATE matchalerts.NOTRENDS_SEARCH_MALE S, newjs.MTONGUE M SET S.MTONGUE_ZONE = IF(M.REGION=4,'N',IF(M.REGION=3,'W',IF(M.REGION=2,'S',IF(M.REGION=1,'E','F')))) WHERE M.REGION!=5 AND S.MTONGUE = M.VALUE;
UPDATE matchalerts.NOTRENDS_SEARCH_FEMALE S, newjs.MTONGUE M SET S.MTONGUE_ZONE = IF(M.REGION=4,'N',IF(M.REGION=3,'W',IF(M.REGION=2,'S',IF(M.REGION=1,'E','F')))) WHERE M.REGION!=5 AND S.MTONGUE = M.VALUE;
