use duplicates;
CREATE TABLE `SCREENED_PICTUREIDS_FOR_DUPLICATION` (
  `PROFILEID` mediumint(8) unsigned NOT NULL,
  `PICTUREID` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`PICTUREID`),
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM;

ALTER TABLE  `PROBABLE_DUPLICATES` CHANGE  `REASON`  `REASON` SET(  'EMAIL',  'CRAWLER',  'MESSENGER',  'IPADDRESS',  'PHOTO',  'TEXT',  'PHONE',  'ID_PROOF',  'LINKEDIN',  'FACEBOOK',  'BLACKBERRY',  'EMAIL_PREFIX',  'PHOTO-ATTRIBUTE' ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL;

ALTER TABLE  `DUPLICATE_PROFILE_LOG` CHANGE  `REASON`  `REASON` SET(  'EMAIL',  'CRAWLER',  'MESSENGER',  'IPADDRESS',  'PHOTO',  'TEXT',  'PHONE',  'ID_PROOF',  'LINKEDIN',  'FACEBOOK',  'BLACKBERRY',  'EMAIL_PREFIX','NONE', 'PHOTO-ATTRIBUTE' ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL;
