/** MIS query will take time **/
use newjs;
ALTER TABLE  SEARCHQUERY ADD  MATCHALERTS_DATE_CLUSTER VARCHAR( 20 ) NOT NULL ;
ALTER TABLE  SEARCHQUERY ADD  KUNDLI_DATE_CLUSTER VARCHAR( 20 ) NOT NULL ;
INSERT INTO  SEARCH_CLUSTERS (  DISPLAY_LABEL ,  SOLR_LABEL ,  VALUE ,  ACTIVE )  VALUES ('Date Sent',  'MATCHALERTS_DATE_CLUSTER',  '30',  'Y');

use MIS;
ALTER TABLE  SEARCHQUERY ADD  MATCHALERTS_DATE_CLUSTER VARCHAR( 20 ) NOT NULL ;
ALTER TABLE  SEARCHQUERY ADD  KUNDLI_DATE_CLUSTER VARCHAR( 20 ) NOT NULL ;
ALTER TABLE  SEARCHQUERY_TEMP ADD  MATCHALERTS_DATE_CLUSTER VARCHAR( 20 ) NOT NULL ;
ALTER TABLE  SEARCHQUERY_TEMP ADD  KUNDLI_DATE_CLUSTER VARCHAR( 20 ) NOT NULL ;

