use newjs;

CREATE TABLE `FACEBOOK_ALBUM_DETAILS` (
 `PROFILEID` int(11) NOT NULL,
 `ALBUM_ID` varchar(100) NOT NULL,
 `NO_OF_PHOTOS` int(11) NOT NULL,
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`ALBUM_ID`)
) ENGINE=InnoDB;
