USE newjs;
ALTER TABLE `COMMUNITY_PAGES` MODIFY TYPE varchar(20);
ALTER TABLE `COMMUNITY_PAGES` MODIFY VALUE varchar(20);

INSERT INTO `COMMUNITY_PAGES` VALUES (1435, 'Leucoderma/Vitiligo/White Patches/White Spots ', 'Leucoderma', 'SPECIAL_CASES', 'Leucoderma', 1, '/leucoderma-vitiligo-white-patches-white-spots-grooms-boys', 'Y', 'L1_SP_1435', 'Male members suffering from skin disorders such as Leucoderma or Vitiligo usually face rejection in matrimonial alliances. Many feel that marrying persons with skin disorders will lead to the spread of disease. This is not often true and medical science does not approve of it. Persons suffering from skin disorders are not lagging in professional and personal qualities. Grooms with skin disorders are engaged in high profile careers. Here is a list of prospective grooms searching for life partner', 'Leucoderma Grooms - Vitiligo Boys - White Patches Groom - White Spots Boy - Leucoderma Matrimony - Leucoderma Matrimonials', 'Looking for Leucoderma Brides or Leucoderma Girls? Find Leucoderma Bride, Leucoderma Girl, Vitiligo Matrimony in the leading Leucoderma Matrimonials site for Indian & NRI White Patches Marriage. Join Free & Add your White Spots Matrimonial Profile Now! Find suitable Indian & NRI Leucoderma brides and grooms from our online Leucoderma matrimonial and matchmaking services.', 'Leucoderma Grooms matrimony, Vitiligo Grooms matrimonials, White Patches Grooms matrimonial, Leucoderma Grooms Grooms, White Spots Grooms groom, Leucoderma Grooms boys, Leucoderma Grooms boy, Leucoderma Grooms matchmaking services, grooms, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified', 'Leucoderma Grooms', 'Y', 'leucoderma-vitiligo-white-patches-white-spots-grooms-boys.jpg', 'Leucoderma Vitiligo White Patches White Spots Grooms Boys', 'G');
INSERT INTO `COMMUNITY_PAGES` VALUES (1434, 'Diabetic ', '', 'SPECIAL_CASES', 'Diabetic', 1, '/diabetic-grooms-boys', 'Y', 'L1_SP_1434', 'Millions suffer from diabetes worldwide. Persons with diabetes faces rejections in getting married as there are misconceptions persist in the society. A diabetic person has to maintain a healthy lifestyle, healthy eating and have regular medications. Diabetic persons can do all things as a normal person can do. Prospective diabetic grooms are engaged in financially sound professions. Belonging to diverse background and culture, here is a list of prospective diabetic grooms', 'Diabetic Grooms - Diabetic Boys - Diabetic Groom - Diabetic Boy - Diabetic Matrimony - Diabetic Matrimonials', 'Looking for Diabetic Grooms or Diabetic Boys? Find Diabetic Groom, Diabetic Boy, Diabetic Matrimony in the leading Diabetic Matrimonials site for Indian & NRI Diabetic Marriage. Join Free & Add your Diabetic Matrimonial Profile Now! Find suitable Indian & NRI Diabetic Grooms from our online Diabetic matrimonial and matchmaking services.', 'Diabetic matrimony, Diabetic matrimonials, Diabetic matrimonial, Diabetic Grooms, Diabetic groom, Diabetic boys, Diabetic boy, Diabetic matchmaking services, grooms, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified', 'Diabetic Grooms ', 'Y', 'diabetic-grooms-boys.jpg', 'Diabetic Grooms Boys', 'G');
INSERT INTO `COMMUNITY_PAGES` VALUES (1433, 'Cancer Survivor ', '', 'SPECIAL_CASES', 'Cancer Survivor', 1, '/cancer-survivor-grooms-boys', 'Y', 'L1_SP_1433', 'Cancer survivor people have overcome the death threatening disease and have a new inner strength. Many want to start life afresh and marriage is surely a great thing. Many prospective cancer survivor grooms are engaged in successful professions. With proper care, a cancer survivor groom can live a normal life. Here is a list of cancer survivors with personal & professional background. ', 'Cancer Survivor Grooms - Cancer Survivor Boys - Cancer Survivor Groom - Cancer Survivor Boy - Cancer Survivor Matrimony - Cancer Survivor Matrimonials', 'Looking for Cancer Survivor Grooms or Cancer Survivor Boys? Find Cancer Survivor Groom, Cancer Survivor Boy, Cancer Survivor Matrimony in the leading Cancer Survivor Matrimonials site for Indian & NRI Cancer Survivor Marriage. Join Free & Add your Cancer Survivor Matrimonial Profile Now! Find suitable Indian & NRI Cancer Survivor Grooms from our online Cancer Survivor matrimonial and matchmaking services.', 'Cancer Survivor matrimony, Cancer Survivor matrimonials, Cancer Survivor matrimonial, Cancer Survivor Grooms, Cancer Survivor groom, Cancer Survivor boys, Cancer Survivor boy, Cancer Survivor matchmaking services, grooms, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified', 'Cancer Survivor Grooms ', 'Y', 'cancer-survivor-grooms-boys.jpg', 'Cancer Survivor Grooms Boys', 'G');
INSERT INTO `COMMUNITY_PAGES` VALUES (1432, 'Handicapped', '', 'SPECIAL_CASES', 'Handicapped', 1, '/handicapped-grooms-boys', 'Y', 'L1_SP_1432', 'Handicapped Persons can lead a happy married life. Physically challenge persons have the same heart & feelings just like others. The closed minds of society are opening and many are accepting handicapped matrimony. Handicapped grooms may suffer from physical disability but their strong will power can help them to do many activities on own. Many persons with physical disability are engaged in successful careers. Handicapped grooms may belong to any religion but they too want start life anew.', 'Handicapped Grooms - Handicapped Boys - Physically challenged Groom - Physically challenged Boy - Handicapped Matrimony - Handicapped Matrimonials', 'Looking for Handicapped Grooms or Handicapped Boys? Find Handicapped Groom, Handicapped Boy, Physically challenged grooms in the leading Physically challenged Matrimonials site for Indian & NRI Handicapped Marriage. Join Free & Add your Handicapped Matrimonial Profile Now! Find suitable Indian & NRI Handicapped Grooms from our online Handicapped matrimonial and matchmaking services.', 'Handicapped matrimony, Handicapped matrimonials, Physically challenged matrimonial, Handicapped Grooms, Handicapped groom, Cripple boys, Handicapped boy, Handicapped matchmaking services, grooms, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified', 'Handicapped Grooms ', 'Y', 'handicapped-grooms-boys.jpg', 'Handicapped Grooms Boys', 'G');
INSERT INTO `COMMUNITY_PAGES` VALUES (1431, 'Visually Impaired', '', 'SPECIAL_CASES', 'Blind', 1, '/blind-grooms-boys', 'Y', 'L1_SP_1431', 'About 15 million of India\'s population is blind. Persons with blindness or are partially blind have overcome their fate of destiny with the special education for blind people. With the advancement of medical science, there is treatment of corneal blindness. Moreover, with eye donation, many can see the beautiful world. The blind grooms only need love and affection. Many blind people are engaged in successful professions including creative art. Here is a list of blind grooms seeking partner', 'Blind Grooms - Blind Boys - Blind Groom - Blind Boy - Blind Matrimony - Blind Matrimonials', 'Looking for Blind Grooms or Blind Boys? Find Blind Groom, Blind Boy, Blind Matrimony in the leading Blind Matrimonials site for Indian & NRI Blind Marriage. Join Free & Add your Blind Matrimonial Profile Now! Find suitable Indian & NRI Blind Grooms from our online Blind matrimonial and matchmaking services.', 'Blind matrimony, Blind matrimonials, Blind matrimonial, Blind Grooms, Blind groom, Blind boys, Blind boy, Blind matchmaking services, grooms, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified', 'Blind Grooms ', 'Y', 'blind-grooms-boys.jpg', 'Blind Grooms Boys', 'G');
INSERT INTO `COMMUNITY_PAGES` VALUES (1429, 'Hearing Impaired', '', 'SPECIAL_CASES', 'Deaf', 1, '/deaf-grooms-boys', 'Y', 'L1_SP_1429', 'Deafness is a common congenital disabilities and WHO reports about 300 million deaf people. About one in 12 persons in India has hearing loss. With many organizations providing Deaf training and education, people with hearing loss have reached commendable heights. Deaf grooms are smart, good looking and efficient worker, just like normal people. Many deaf grooms are in profession of medicine, business, IT, and research and development work', 'Deaf Grooms - Deaf Boys - Deaf Groom - Deaf Boy - Deaf Matrimony - Deaf Matrimonials', 'Looking for Deaf Grooms or Deaf Boys? Find Deaf Groom, Deaf Boy, Deaf Matrimony in the leading Deaf Matrimonials site for Indian & NRI Deaf Marriage. Join Free & Add your Deaf Matrimonial Profile Now! Find suitable Indian & NRI Deaf Grooms from our online Deaf matrimonial and matchmaking services.', 'Deaf matrimony, Deaf matrimonials, Deaf matrimonial, Deaf Grooms, Deaf groom, Deaf boys, Deaf boy, Deaf matchmaking services, grooms, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified', 'Deaf Grooms ', 'Y', 'deaf-grooms-boys.jpg', 'Deaf Grooms Boys', 'G');
INSERT INTO `COMMUNITY_PAGES` VALUES (1430, 'Speech Impaired', '', 'SPECIAL_CASES', 'Dumb', 1, '/dumb-grooms-boys', 'Y', 'L1_SP_1430', 'People born with speech impairment are equally talented and successful in life as normal healthy persons. With education and special courses for dumb (speech-impaired) persons, many have shaped their career path successfully. With sign gestures used to communicate, a Dumb person have a similar lifestyle as regular persons. Dumb Grooms are engaged in sound financial professions. Given below is a list of Dumb Grooms belonging from diverse family background and communities of India', 'Dumb Grooms - Dumb Boys - Dumb Groom - Dumb Boy - Dumb Matrimony - Dumb Matrimonials', 'Looking for Dumb Grooms or Dumb Boys? Find Dumb Groom, Dumb Boy, Dumb Matrimony in the leading Dumb Matrimonials site for Indian & NRI Dumb Marriage. Join Free & Add your Dumb Matrimonial Profile Now! Find suitable Indian & NRI Dumb Grooms from our online Dumb matrimonial and matchmaking services.', 'Dumb matrimony, Dumb matrimonials, Dumb matrimonial, Dumb Grooms, Dumb groom, Dumb boys, Dumb boy, Dumb matchmaking services, grooms, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified', 'Dumb Grooms ', 'Y', 'dumb-grooms-boys.jpg', 'Dumb Grooms Boys', 'G');
INSERT INTO `COMMUNITY_PAGES` VALUES (1427, 'HIV Positive ', '', 'SPECIAL_CASES', 'HIV', 1, '/hiv-positive-grooms-boys', 'Y', 'L1_SP_1427', 'Marriage brings hopes in lives of many and so is for HIV Positive persons. HIV+ people are looking to start life anew. Getting married help HIV Positive Grooms fight back the dreaded ailment together. The grooms want partners who can share their pain and joys. Earlier, lack of acceptance from society kept these persons away from nuptial knot. Many NGOs are spreading the message that with proper medications, the child does not carry the virus; Here is a list of HIV Grooms, searching for partner', 'HIV positive Grooms - HIV positive Boys - HIV positive Groom - HIV positive Boy - HIV positive Matrimony - HIV positive Matrimonials', 'Looking for HIV positive Grooms or HIV positive Boys? Find HIV positive Groom, HIV positive Boy, HIV positive Matrimony in the leading HIV positive Matrimonials site for Indian & NRI HIV positive Marriage. Join Free & Add your HIV positive Matrimonial Profile Now! Find suitable Indian & NRI HIV positive Grooms from our online HIV positive matrimonial and matchmaking services.', 'HIV positive matrimony, HIV positive matrimonials, HIV positive matrimonial, HIV positive Grooms, HIV positive groom, HIV positive boys, HIV positive boy, HIV positive matchmaking services, grooms, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified', 'HIV positive Grooms ', 'Y', 'hiv-positive-grooms-boys.jpg', 'HIV positive Grooms Boys', 'G');
INSERT INTO `COMMUNITY_PAGES` VALUES (1428, 'Thalassemia Major ', '', 'SPECIAL_CASES', 'Thalassemia', 1, '/thalassemia-major-grooms-boys', 'Y', 'L1_SP_1428', 'Life with a thalassemia major is very similar like just living with any other human beings. However, they have to careful with the treatments and medicines. Thalassemia major people can marry and have a happy life. They also want to share their happiness with someone special. Prospective Thalassemic major grooms have the same intelligence and smartness, like normal grooms. With advanced treatments available for Thalassemic Major, it is now curable', 'Thalassemia Major Grooms - Thalassemia Major Boys - Thalassemia Major Groom - Thalassemia Major Boy - Thalassemia Major Matrimony - Thalassemia Major Matrimonials', 'Looking for Thalassemia Major Grooms or Thalassemia Major Boys? Find Thalassemia Major Groom, Thalassemia Major Boy, Thalassemia Major Matrimony in the leading Thalassemia Major Matrimonials site for Indian & NRI Thalassemia Major Marriage. Join Free & Add your Thalassemia Major Matrimonial Profile Now! Find suitable Indian & NRI Thalassemia Major Grooms from our online Thalassemia Major matrimonial and matchmaking services.', 'Thalassemia Major matrimony, Thalassemia Major matrimonials, Thalassemia Major matrimonial, Thalassemia Major Grooms, Thalassemia Major groom, Thalassemia Major boys, Thalassemia Major boy, Thalassemia Major matchmaking services, grooms, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified', 'Thalassemia Major Grooms ', 'Y', 'thalassemia-major-grooms-boys.jpg', 'Thalassemia Major Grooms Boys', 'G');
INSERT INTO `COMMUNITY_PAGES` VALUES (1425, 'Diabetic ', '', 'SPECIAL_CASES', 'Diabetic', 1, '/diabetic-brides-girls', 'Y', 'L1_SP_1425', 'A person may develop diabetes at any age, so one cannot predict about this disease. It is a collective of metabolic diseases where a person suffers from high blood sugar as the body could not produce insulin to control sugar level in the body. The diabetic patients lead the normal life just that they have to take care of sugar intake in their diet. A number of profiles of well qualified diabetic brides are listed on our matrimonial site and seek suitable diabetic or normal matches for lifetime', 'Diabetic Brides - Diabetic Girls - Diabetic Bride - Diabetic Girl - Diabetic Matrimony - Diabetic Matrimonials', 'Looking for Diabetic Brides or Diabetic Girls? Find Diabetic Bride, Diabetic Girl, Diabetic Matrimony in the leading Diabetic Matrimonials site for Indian & NRI Diabetic Marriage. Join Free & Add your Diabetic Matrimonial Profile Now! Find suitable Indian & NRI Diabetic brides and grooms from our online Diabetic matrimonial and matchmaking services.', 'Diabetic matrimony, Diabetic matrimonials, Diabetic matrimonial, Diabetic brides, Diabetic bride, Diabetic girls, Diabetic girl, Diabetic matchmaking services, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified, brides', 'Diabetic Brides ', 'Y', 'diabetic-brides-girls.jpg', 'Diabetic Brides Girls', 'B');
INSERT INTO `COMMUNITY_PAGES` VALUES (1426, 'Leucoderma/Vitiligo/White Patches/White Spots ', 'Leucoderma', 'SPECIAL_CASES', 'Leucoderma', 1, '/leucoderma-vitiligo-white-patches-white-spots-brides-girls', 'Y', 'L1_SP_1426', 'Leucoderma is a medical condition where the person suffers from white patches on the skin. As believed by many, leucoderma is not a communicable disease and it does not transfer from one person to another. The disease is a cutaneous problem, where melanin pigment is not present in some localized skin areas. The disease may occur because of skin inflammation, burns or post-dermabrasion. The well qualified and settled Leucoderma brides on our matrimonial list seek perfect matches for themselves', 'Leucoderma Brides - Vitiligo Girls - Leucoderma Bride - White Patches Girl - White Spots Matrimony - Leucoderma Matrimonials', 'Looking for Leucoderma Brides or Leucoderma Girls? Find Vitiligo Bride, Leucoderma Girl, White Patches Matrimony in the leading Leucoderma Matrimonials site for Indian & NRI White Spots Marriage. Join Free & Add your Leucoderma Matrimonial Profile Now! Find suitable Indian & NRI Leucoderma brides and grooms from our online Leucoderma matrimonial and matchmaking services.', 'Leucoderma matrimony, Vitiligo matrimonials, Leucoderma matrimonial, Leucoderma brides, White Patches bride, Leucoderma girls, White Spots girl, Leucoderma matchmaking services, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified, brides', 'Leucoderma Brides', 'Y', 'leucoderma-vitiligo-white-patches-white-spots-brides-girls.jpg', 'Leucoderma Vitiligo White Patches White Spots Brides  Girls', 'B');
INSERT INTO `COMMUNITY_PAGES` VALUES (1424, 'Cancer Survivor', '', 'SPECIAL_CASES', 'Cancer Survivor', 1, '/cancer-survivor-brides-girls', 'Y', 'L1_SP_1424', 'Life of a cancer survivor is tough and they need extra care in their life. If detected in the earlier stages, cancer is curable and person may lead a normal life despite severe health problems faced. People who have fought from cancer are fighters indeed. There are a number of profiles of cancer survivor brides on our website who can prove to be great life partners.', 'Cancer Survivor Brides - Cancer Survivor Girls - Cancer Survivor Bride - Cancer Survivor Girl - Cancer Survivor Matrimony - Cancer Survivor Matrimonials', 'Looking for Cancer Survivor Brides or Cancer Survivor Girls? Find Cancer Survivor Bride, Cancer Survivor Girl, Cancer Survivor Matrimony in the leading Cancer Survivor Matrimonials site for Indian & NRI Cancer Survivor Marriage. Join Free & Add your Cancer Survivor Matrimonial Profile Now! Find suitable Indian & NRI Cancer Survivor brides and grooms from our online Cancer Survivor matrimonial and matchmaking services.', 'Cancer Survivor matrimony, Cancer Survivor matrimonials, Cancer Survivor matrimonial, Cancer Survivor brides, Cancer Survivor bride, Cancer Survivor girls, Cancer Survivor girl, Cancer Survivor matchmaking services, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified, brides', 'Cancer Survivor Brides ', 'Y', 'cancer-survivor-brides-girls.jpg', 'Cancer Survivor Brides Girls', 'B');
INSERT INTO `COMMUNITY_PAGES` VALUES (1423, 'Handicapped', '', 'SPECIAL_CASES', 'Handicapped', 1, '/handicapped-brides-girls', 'Y', 'L1_SP_1423', 'The problems suffered by the handicapped people are mobility impairment, visual impairment and/or hearing impairment. The causes for the handicapped condition of a person may be due to many reasons, whether from the birth or because of some external injuries. The handicapped matrimonial sites have various profiles of physically challenged brides who are well educated and have excelled in different fields, and can be perfect matches for even the normal people. These people can lead normal life.', 'Handicapped Brides - Handicapped Girls - Physically challenged Bride - Physically challenged Girl - Handicapped Matrimony - Handicapped Matrimonials', 'Looking for Handicapped Brides or Handicapped Girls? Find Handicapped Bride, Handicapped Girl, Physically challenged Matrimony in the leading Handicapped Matrimonials site for Indian & NRI Handicapped Marriage. Join Free & Add your Handicapped Matrimonial Profile Now! Find suitable Indian & NRI Handicapped brides and grooms from our online Handicapped matrimonial and matchmaking services.', 'Handicapped matrimony, Handicapped matrimonials, Physically challenged matrimonial, Physically challenged brides, Handicapped bride, Handicapped girls, Handicapped girl, Handicapped matchmaking services, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified, brides', 'Handicapped Brides ', 'Y', 'handicapped-brides-girls.jpg', 'Handicapped Brides Girls', 'B');
INSERT INTO `COMMUNITY_PAGES` VALUES (1422, 'Visually Impaired', '', 'SPECIAL_CASES', 'Blind', 1, '/blind-brides-girls', 'Y', 'L1_SP_1422', 'It is said that love is blind, so don\'t blind people have the right to live that ecstatic feeling of love! Definitely they have, and this is the reason why perfect matches for people with visually impaired are available on our matrimonial site. Since visually impaired people require lot of care, they require a life partner for that, hence profiles from healthy people are welcome for the blind brides. There are treatments available for partially blind people that can lead to a normal life later', 'Blind Brides - Blind Girls - Blind Bride - Blind Girl - Blind Matrimony - Blind Matrimonials', 'Looking for Blind Brides or Blind Girls? Find Blind Bride, Blind Girl, Blind Matrimony in the leading Blind Matrimonials site for Indian & NRI Blind Marriage. Join Free & Add your Blind Matrimonial Profile Now! Find suitable Indian & NRI Blind brides and grooms from our online Blind matrimonial and matchmaking services.', 'Blind matrimony, Blind matrimonials, Blind matrimonial, Blind brides, Blind bride, Blind girls, Blind girl, Blind matchmaking services, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified, brides', 'Blind Brides ', 'Y', 'blind-brides-girls.jpg', 'Blind Brides Girls', 'B');
INSERT INTO `COMMUNITY_PAGES` VALUES (1420, 'Hearing Impaired', '', 'SPECIAL_CASES', 'Deaf', 1, '/deaf-brides-girls', 'Y', 'L1_SP_1420', 'Love sees no boundaries or languages. Even deaf people have emotions and they can share those very well too with the help of advanced hearing aids. Love works in mysterious ways and attracts people with opposite traits. It is seen that the matrimonial relationships among the deaf brides (hearing impaired) and the hearing partners as well as vice versa have been successful as they can very well understand each other\'s languages and communicate properly together while with others too', 'Deaf Brides - Deaf Girls - Deaf Bride - Deaf Girl - Deaf Matrimony - Deaf Matrimonials', 'Looking for Deaf Brides or Deaf Girls? Find Deaf Bride, Deaf Girl, Deaf Matrimony in the leading Deaf Matrimonials site for Indian & NRI Deaf Marriage. Join Free & Add your Deaf Matrimonial Profile Now! Find suitable Indian & NRI Deaf brides and grooms from our online Deaf matrimonial and matchmaking services.', 'Deaf matrimony, Deaf matrimonials, Deaf matrimonial, Deaf brides, Deaf bride, Deaf girls, Deaf girl, Deaf matchmaking services, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified, brides', 'Deaf Brides ', 'Y', 'deaf-brides-girls.jpg', 'Deaf Brides Girls', 'B');
INSERT INTO `COMMUNITY_PAGES` VALUES (1421, 'Speech Impaired', '', 'SPECIAL_CASES', 'Dumb', 1, '/dumb-brides-girls', 'Y', 'L1_SP_1421', 'Two people who understand each other do not require language to communicate with each other. This can be clearly seen with the case of dumb or speech impaired people and speaking population. Sign languages are effective ways of communication for the dumb or speech impaired people. There are a number of dumb brides who are waiting for their perfect matches to lead a happier life in future. For such matrimonial alliances, speaking deaf partners have been proven to be perfect match ', 'Dumb Brides - Dumb Girls - Dumb Bride - Dumb Girl - Dumb Matrimony - Dumb Matrimonials', 'Looking for Dumb Brides or Dumb Girls? Find Dumb Bride, Dumb Girl, Dumb Matrimony in the leading Dumb Matrimonials site for Indian & NRI Dumb Marriage. Join Free & Add your Dumb Matrimonial Profile Now! Find suitable Indian & NRI Dumb brides and grooms from our online Dumb matrimonial and matchmaking services.', 'Dumb matrimony, Dumb matrimonials, Dumb matrimonial, Dumb brides, Dumb bride, Dumb girls, Dumb girl, Dumb matchmaking services, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified, brides', 'Dumb Brides ', 'Y', 'dumb-brides-girls.jpg', 'Dumb Brides Girls', 'B');
INSERT INTO `COMMUNITY_PAGES` VALUES (1418, 'HIV Positive ', '', 'SPECIAL_CASES', 'HIV', 1, '/hiv-positive-brides-girls', 'Y', 'L1_SP_1418', 'An HIV person has to lead a tough life as the society is still skeptical towards the HIV positive people and consider them to be AIDS patients. It is quite a big challenge to find the perfect match for the HIV positive brides. They need not to live in despair as there are a number of online matrimonial sites where there are HIV positive singles sharing the same problem. Finding a life partner who can understand the mental condition can be the best psychological succor', 'HIV positive Brides - HIV positive Girls - HIV positive Bride - HIV positive Girl - HIV positive Matrimony - HIV positive Matrimonials', 'Looking for HIV positive Brides or HIV positive Girls? Find HIV positive Bride, HIV positive Girl, HIV positive Matrimony in the leading HIV positive Matrimonials site for Indian & NRI HIV positive Marriage. Join Free & Add your HIV positive Matrimonial Profile Now! Find suitable Indian & NRI HIV positive brides and grooms from our online HIV positive matrimonial and matchmaking services.', 'HIV positive matrimony, HIV positive matrimonials, HIV positive matrimonial, HIV positive brides, HIV positive bride, HIV positive girls, HIV positive girl, HIV positive matchmaking services, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified, brides', 'HIV positive Brides ', 'Y', 'hiv-positive-brides-girls.jpg', 'HIV positive Brides Girls', 'B');
INSERT INTO `COMMUNITY_PAGES` VALUES (1419, 'Thalassemia Major ', '', 'SPECIAL_CASES', 'Thalassemia', 1, '/thalassemia-major-brides-girls', 'Y', 'L1_SP_1419', 'Thalassemia major is an autosomal recessive blood disease that is genetic. There is a very small population of Thalassemia major patients in India, and some of them are definitely eligible thalassemic major brides. A thalassemic major patient is anemic and they often need to go for blood transfusions every 2-4 weeks. Bone Marrow Transplant (BMT) has emerged as a boon that has prolonged the longevity of the patients and allow them to lead normal life', 'Thalassemia Major Brides - Thalassemia Major Girls - Thalassemia Major Bride - Thalassemia Major Girl - Thalassemia Major Matrimony - Thalassemia Major Matrimonials', 'Looking for Thalassemia Major Brides or Thalassemia Major Girls? Find Thalassemia Major Bride, Thalassemia Major Girl, Thalassemia Major Matrimony in the leading Thalassemia Major Matrimonials site for Indian & NRI Thalassemia Major Marriage. Join Free & Add your Thalassemia Major Matrimonial Profile Now! Find suitable Indian & NRI Thalassemia Major brides and grooms from our online Thalassemia Major matrimonial and matchmaking services.', 'Thalassemia Major matrimony, Thalassemia Major matrimonials, Thalassemia Major matrimonial, Thalassemia Major brides, Thalassemia Major bride, Thalassemia Major girls, Thalassemia Major girl, Thalassemia Major matchmaking services, matrimonials, matrimony, matrimony services, Indian marriage, match making, matchmaker, marriage bureau, matchmaking services, matrimonial profiles, matrimony classified, brides', 'Thalassemia Major Brides ', 'Y', 'thalassemia-major-brides-girls.jpg', 'Thalassemia Major Brides Girls', 'B');
INSERT INTO `COMMUNITY_PAGES` VALUES (1417, 'Leucoderma/Vitiligo/White Patches/White Spots', 'Leucoderma', 'SPECIAL_CASES', 'Leucoderma', 1, '/leucoderma-vitiligo-white-patches-white-spots-matrimony-matrimonials', 'Y', 'L1_SP_1417', 'Leucoderma/Vitiligo/White Patches/White Spots are skin diseases where de-pigmentation happens. In India, the incidence of these skin disorders is more as it is common in darker skin tones. Many persons suffering from white patches conditions have problems getting married. Many have fear of child acquiring the disease; which is not proved by medical science. This platform unites persons suffering with skin disorders for matrimonial purposes', 'Leucoderma Matrimony - Vitiligo Matrimonial - White Patches Matrimonials - White Spots Marriage - Online Leucoderma Matrimonials - Matrimonial Services', 'Search Leucoderma Matrimony, Vitiligo Matrimonial, Leucoderma Matrimonials, White Patches Marriage, White Spots Matrimonial Profiles in the leading Leucoderma Matrimonials site for Indian and NRI Leucoderma Marriage. Join Free & Add your Leucoderma Matrimonial Profile Now! Find suitable Indian & NRI Leucoderma brides and grooms from our online Leucoderma matrimonial and matchmaking services.', 'Leucoderma matrimony, Vitiligo matrimonials, White Patches matrimonial, matrimonials, matrimony, matrimony services, online White Spots matrimonials, Indian marriage, match making, matchmaker, Leucoderma profiles, marriage bureau , Leucoderma marriage bureau, matchmaking services, matrimonial profiles, Leucoderma bride, Leucoderma groom, matrimony classified, brides, grooms', 'Leucoderma Matrimonials', 'Y', 'leucoderma-vitiligo-white-patches-white-spots-matrimonials.jpg', 'Leucoderma Vitiligo White Patches White Spots Matrimony', 'N');
INSERT INTO `COMMUNITY_PAGES` VALUES (1416, 'Diabetic', '', 'SPECIAL_CASES', 'Diabetic', 1, '/diabetic-matrimony-matrimonials', 'Y', 'L1_SP_1416', 'According to the World Health Statistics 2012 Report one in 20 individual in India is diabetic making it maximum number of diabetic people in the world. Though with rising awareness in the society, wrong notions are dispelling yet many diabetic persons face matrimonial problems. A diabetic person does not find a partner for getting married. Diabetes, Type 1 and 2, is treatable with insulin and medications. Find likeminded people interested in diabetic matrimony', 'Diabetic Matrimony - Diabetic Matrimonial - Diabetic Matrimonials - Diabetic Marriage - Online Diabetic Matrimonials - Matrimonial Services', 'Search Diabetic Matrimony, Diabetic Matrimonial, Diabetic Matrimonials, Diabetic Marriage, Diabetic Matrimonial Profiles in the leading Diabetic Matrimonials site for Indian and NRI Diabetic Marriage. Join Free & Add your Diabetic Matrimonial Profile Now! Find suitable Indian & NRI Diabetic brides and grooms from our online Diabetic matrimonial and matchmaking services.', 'Diabetic matrimony, Diabetic matrimonials, Diabetic matrimonial, matrimonials, matrimony, matrimony services, online Diabetic matrimonials, Indian marriage, match making, matchmaker, Diabetic profiles, marriage bureau , Diabetic marriage bureau, matchmaking services, matrimonial profiles, Diabetic bride, Diabetic groom, matrimony classified, brides, grooms', 'Diabetic Matrimonials', 'Y', 'diabetic-matrimonials.jpg', 'Diabetic Matrimony', 'N');
INSERT INTO `COMMUNITY_PAGES` VALUES (1415, 'Cancer Survivor', '', 'SPECIAL_CASES', 'Cancer Survivor', 1, '/cancer-survivor-matrimony-matrimonials', 'Y', 'L1_SP_1415', 'A Cancer Survivor has seen the worst period of life. Millions around the world have overcome cancer with medical treatment. They now want to start life afresh and getting married is certainly one of them. Cancer Survivor Matrimony is noble idea for many. With the perfect partner, life''s journey becomes a smooth one. Find cancer survivor partners ready for matrimonial alliance.', 'Cancer Survivor Matrimony - Cancer Survivor Matrimonial - Cancer Survivor Matrimonials - Cancer Survivor Marriage - Online Cancer Survivor Matrimonials - Matrimonial Services', 'Search Cancer Survivor Matrimony, Cancer Survivor Matrimonial, Cancer Survivor Matrimonials, Cancer Survivor Marriage, Cancer Survivor Matrimonial Profiles in the leading Cancer Survivor Matrimonials site for Indian and NRI Cancer Survivor Marriage. Join Free & Add your Cancer Survivor Matrimonial Profile Now! Find suitable Indian & NRI Cancer Survivor brides and grooms from our online Cancer Survivor matrimonial and matchmaking services.', 'Cancer Survivor matrimony, Cancer Survivor matrimonials, Cancer Survivor matrimonial, matrimonials, matrimony, matrimony services, online Cancer Survivor matrimonials, Indian marriage, match making, matchmaker, Cancer Survivor profiles, marriage bureau , Cancer Survivor marriage bureau, matchmaking services, matrimonial profiles, Cancer Survivor bride, Cancer Survivor groom, matrimony classified, brides, grooms', 'Cancer Survivor Matrimonials', 'Y', 'cancer-survivor-matrimonials.jpg', 'Cancer Survivor Matrimony', 'N');
INSERT INTO `COMMUNITY_PAGES` VALUES (1414, 'Handicapped', '', 'SPECIAL_CASES', 'Handicapped', 1, '/handicapped-matrimony-matrimonials', 'Y', 'L1_SP_1414', 'A person with a physical disability because of illness or accident is termed as \'Handicapped\'. These people get government assistance to start income generating activities. Even the Handicapped persons, just like healthy persons, want to share their joys and sorrows with someone special. Handicapped Matrimony is a dignified gesture, as people with physical disability wants to tie the nuptial knot and lead a happy life. This platform unites likeminded persons for physically challenged matrimony. ', 'Handicapped Matrimony - Handicapped Matrimonial - Physically challenged Matrimonials - Physically challenged Marriage - Online Handicapped Matrimonials - Matrimonial Services', 'Search Handicapped Matrimony, Handicapped Matrimonial, Physically challenged Matrimonials, Physically challenged Marriage, Cripple Matrimonial Profiles in the leading Handicapped Matrimonials site for Indian and NRI Handicapped Marriage. Join Free & Add your Handicapped Matrimonial Profile Now! Find suitable Indian & NRI Handicapped brides and grooms from our online Handicapped matrimonial and matchmaking services.', 'Handicapped matrimony, Handicapped matrimonials, Physically challenged matrimonial, matrimonials, matrimony, matrimony services, online Physically challenged matrimonials, Indian marriage, match making, matchmaker, Cripple profiles, marriage bureau , Handicapped marriage bureau, matchmaking services, matrimonial profiles, Handicapped bride, Handicapped groom, matrimony classified, brides, grooms', 'Handicapped Matrimonials', 'Y', 'handicapped-matrimonials.jpg', 'Handicapped Matrimony', 'N');
INSERT INTO `COMMUNITY_PAGES` VALUES (1412, 'Speech Impaired', '', 'SPECIAL_CASES', 'Dumb', 1, '/dumb-matrimony-matrimonials', 'Y', 'L1_SP_1412', 'Out of 5% of Indian population which is suffering from speaking disorders, a large population is mute or speaking impaired. Dumb matrimony in India is not that impossible concern as it is not any infectious disease and people generally lead a normal life. The matrimonial alliances between deaf and dumb people have been successful as they can complement each other\'s disability or problems and provide their support. They can communicate in sign languages and understand each other\'s emotions well', 'Dumb Matrimony - Dumb Matrimonial - Dumb Matrimonials - Dumb Marriage - Online Dumb Matrimonials - Matrimonial Services', 'Search Dumb Matrimony, Dumb Matrimonial, Dumb Matrimonials, Dumb Marriage, Dumb Matrimonial Profiles in the leading Dumb Matrimonials site for Indian and NRI Dumb Marriage. Join Free & Add your Dumb Matrimonial Profile Now! Find suitable Indian & NRI Dumb brides and grooms from our online Dumb matrimonial and matchmaking services.', 'Dumb matrimony, Dumb matrimonials, Dumb matrimonial, matrimonials, matrimony, matrimony services, online Dumb matrimonials, Indian marriage, match making, matchmaker, Dumb profiles, marriage bureau , Dumb marriage bureau, matchmaking services, matrimonial profiles, Dumb bride, Dumb groom, matrimony classified, brides, grooms', 'Dumb Matrimonials', 'Y', 'dumb-matrimonials.jpg', 'Dumb Matrimony', 'N');
INSERT INTO `COMMUNITY_PAGES` VALUES (1413, 'Visually Impaired', '', 'SPECIAL_CASES', 'Blind', 1, '/blind-matrimony-matrimonials', 'Y', 'L1_SP_1413', 'The data of visually impaired people in India is shocking as out of every 3 such people, 1 belongs to India. The marriages are quite tough to arrange and it is important that one of the partners should be able to see as the blind people need extra care which only a life partner can do. There are matrimony sites for blind people that can help to seek them most suitable matches. Blind matrimony is really a noble thing and people can change their lives by finding the perfect match', 'Blind Matrimony - Blind Matrimonial - Blind Matrimonials - Blind Marriage - Online Blind Matrimonials - Matrimonial Services', 'Search Blind Matrimony, Blind Matrimonial, Blind Matrimonials, Blind Marriage, Blind Matrimonial Profiles in the leading Blind Matrimonials site for Indian and NRI Blind Marriage. Join Free & Add your Blind Matrimonial Profile Now! Find suitable Indian & NRI Blind brides and grooms from our online Blind matrimonial and matchmaking services.', 'Blind matrimony, Blind matrimonials, Blind matrimonial, matrimonials, matrimony, matrimony services, online Blind matrimonials, Indian marriage, match making, matchmaker, Blind profiles, marriage bureau , Blind marriage bureau, matchmaking services, matrimonial profiles, Blind bride, Blind groom, matrimony classified, brides, grooms', 'Blind Matrimonials', 'Y', 'blind-matrimonials.jpg', 'Blind Matrimony', 'N');
INSERT INTO `COMMUNITY_PAGES` VALUES (1411, 'Hearing Impaired', '', 'SPECIAL_CASES', 'Deaf', 1, '/deaf-matrimony-matrimonials', 'Y', 'L1_SP_1411', 'In India, there are more than 3 million deaf (Hearing Impaired) people. Deafness is no infectious disease and they also deserve to lead a normal life like others. Among the large population of deaf and dumb in India, many of them are still unmarried and can form perfect matches for each other as they will understand each other\'s emotions and problems well. Deaf matrimony is all about uniting two people who can complement each other\'s life well and make life easy', 'Deaf Matrimony - Deaf Matrimonial - Deaf Matrimonials - Deaf Marriage - Online Deaf Matrimonials - Matrimonial Services', 'Search Deaf Matrimony, Deaf Matrimonial, Deaf Matrimonials, Deaf Marriage, Deaf Matrimonial Profiles in the leading Deaf Matrimonials site for Indian and NRI Deaf Marriage. Join Free &amp; Add your Deaf Matrimonial Profile Now! Find suitable Indian &amp; NRI Deaf brides and grooms from our online Deaf matrimonial and matchmaking services.', 'Deaf matrimony, Deaf matrimonials, Deaf matrimonial, matrimonials, matrimony, matrimony services, online Deaf matrimonials, Indian marriage, match making, matchmaker, Deaf profiles, marriage bureau , Deaf marriage bureau, matchmaking services, matrimonial profiles, Deaf bride, Deaf groom, matrimony classified, brides, grooms', 'Deaf Matrimonials', 'Y', 'deaf-matrimonials.jpg', 'Deaf Matrimony', 'N');
INSERT INTO `COMMUNITY_PAGES` VALUES (1409, 'HIV Positive', '', 'SPECIAL_CASES', 'HIV', 1, '/hiv-positive-matrimony-matrimonials', 'Y', 'L1_SP_1409', 'At some stage, the life demands someone as a partner to share both happy and sad moments. Approximately 1.4-1.6 million people in India are HIV positive and among which many of them are still unmarried. It is definitely a noble thought to unite two souls who are suffering with the same problem. Being HIV positive does not mean that the the life is about to end. There is still way long and HIV positive matrimony can definitely bring happiness to the lives of HIV positive people', 'HIV Positive Matrimony - HIV Positive Matrimonial - HIV Positive Matrimonials - HIV Positive Marriage - Online HIV Positive Matrimonials - Matrimonial Services', 'Search HIV Positive Matrimony, HIV Positive Matrimonial, HIV Positive Matrimonials, HIV Positive Marriage, HIV Positive Matrimonial Profiles in the leading HIV Positive Matrimonials site for Indian and NRI HIV Positive Marriage. Join Free & Add your HIV Positive Matrimonial Profile Now! Find suitable Indian & NRI HIV Positive brides and grooms from our online HIV Positive matrimonial and matchmaking services.', 'HIV Positive matrimony, HIV Positive matrimonials, HIV Positive matrimonial, matrimonials, matrimony, matrimony services, online HIV Positive matrimonials, Indian marriage, match making, matchmaker, HIV Positive profiles, marriage bureau , HIV Positive marriage bureau, matchmaking services, matrimonial profiles, HIV Positive bride, HIV Positive groom, matrimony classified, brides, grooms', 'HIV positive Matrimonials ', 'Y', 'hiv-positive-matrimonials.jpg', 'HIV positive Matrimony', 'N');
INSERT INTO `COMMUNITY_PAGES` VALUES (1410, 'Thalassemia Major', '', 'SPECIAL_CASES', 'Thalassemia', 1, '/thalassemia-major-matrimony-matrimonials', 'Y', 'L1_SP_1410', 'Thalassemia Major is a blood disorder, where the people suffer from insufficient hemoglobin. It is not an infectious disease as believed by many. A person suffering from Thalassemic Major is equally eligible to get married & live happily. Only 3-4% of the Indian population suffers from Thalassemic and since the number is less, it\'s tough to find the suitable match. It would be a wise decision to search for the perfect match on the online matrimonial sites that assure Thalassemia Major Matrimony', 'Thalassemia Major Matrimony - Thalassemic Major Matrimonial - Thalassemia Major Matrimonials - Thalassemia Major Marriage - Online Thalassemia Major Matrimonials - Matrimonial Services', 'Search Thalassemia Major Matrimony, Thalassemia Major Matrimonial, Thalassemic Major Matrimonials, Thalassemia Major Marriage, Thalassemic Major Matrimonial Profiles in the leading Thalassemia Major Matrimonials site for Indian and NRI Thalassemia Major Marriage. Join Free & Add your Thalassemia Major Matrimonial Profile Now! Find suitable Indian & NRI Thalassemia Major brides and grooms from our online Thalassemia Major matrimonial and matchmaking services.', 'Thalassemia Major matrimony, Thalassemic Major matrimonials, Thalassemic Major matrimonial, matrimonials, matrimony, matrimony services, online Thalassemic Major matrimonials, Indian marriage, match making, matchmaker, Thalassemia Major profiles, marriage bureau , Thalassemia Major marriage bureau, matchmaking services, matrimonial profiles, Thalassemia Major bride, Thalassemia Major groom, matrimony classified, brides, grooms', 'Thalassemia Major Matrimonials', 'Y', 'Thalassemia-major-matrimonials.jpg', 'Thalassemia Major Matrimony', 'N');
 

CREATE TABLE `SPECIAL_CASES_PROFILES` (
  `PROFILEID` int(11) NOT NULL,
  `DISEASE` varchar(255) NOT NULL,
  `GENDER` char(2) NOT NULL
);

INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2001608, 'Cancer Survivor', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5894389, 'Cancer Survivor', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7172909, 'Cancer Survivor', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7783914, 'Cancer Survivor', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7907764, 'Cancer Survivor', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (159496, 'Cancer Survivor', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3194787, 'Cancer Survivor', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4245835, 'Cancer Survivor', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4758250, 'Cancer Survivor', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7889678, 'Cancer Survivor', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8047358, 'Cancer Survivor', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (120894, 'Cancer Survivor', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5913580, 'Cancer Survivor', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8011038, 'Cancer Survivor', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7838348, 'Cancer Survivor', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7624692, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7645293, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3781664, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7896788, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4035438, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5538487, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5570978, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7942052, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5856336, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8080580, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6082337, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6025095, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6566124, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6691004, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7120576, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7290119, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7784089, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7864997, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2135946, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8034271, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2878264, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4172883, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8094612, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8054205, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5438657, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (106065, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3209410, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4269533, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8050845, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6555126, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7790200, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7626295, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6129586, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7151005, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8073957, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8017281, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (225439, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6951021, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3205061, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7723252, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7952022, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6919504, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7867233, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6690250, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7347065, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7632749, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7512205, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7658922, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7899622, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5140672, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3470404, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1545024, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5914665, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7467246, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (627389, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7288875, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7440331, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7573725, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (488638, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4920368, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1636666, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7928340, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (180378, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5367827, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5424792, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6719848, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7770589, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6765078, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7091657, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7210941, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7760792, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6418471, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5849289, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4860030, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7976625, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5960611, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7352813, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7692750, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4191914, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7561590, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7519852, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7541144, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (917269, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1022042, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4534618, 'Diabetic', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5980427, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2734292, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4682729, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7914540, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2149645, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5301901, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6983864, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7993664, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6628618, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6839313, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8017724, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4901852, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7664026, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (963282, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7973029, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2573095, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4523620, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6645582, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5929009, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6558535, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3769462, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6277706, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7178571, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4676939, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7676475, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7831450, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7864545, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3114515, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (217900, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7630788, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5435509, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7534915, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7591685, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6305967, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7832434, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4554434, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4219383, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3885973, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7560318, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6297734, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7234609, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8059683, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1809776, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6414624, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7442080, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6088556, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6728031, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6786314, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5853585, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6530384, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6732800, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6756195, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7683603, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5830723, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5496387, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4960100, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5265625, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7652116, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6940872, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7936855, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7978791, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7182740, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (593303, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7782070, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5034792, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3001451, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7454186, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5931900, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3458226, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5482634, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3296611, 'Diabetic', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7446765, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7655405, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7750091, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (67024, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (128509, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7568076, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7631460, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7496102, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7546078, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7596578, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7589934, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7571326, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7442699, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7530332, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7505971, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (692896, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8059262, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7512359, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7460838, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1218444, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1300313, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1526685, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1781862, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1803965, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1809309, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1870373, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1945195, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2079187, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2088645, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2223365, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7889987, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2369656, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2440299, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2591565, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2700112, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2784946, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2905061, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2960467, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8050269, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7859686, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3238404, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3241474, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3278180, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3326828, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3351948, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3375885, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3400409, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3405009, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8061548, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3433236, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3486715, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3490737, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3534213, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3597338, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7568415, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3655946, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3726973, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3733012, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7935938, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3759847, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3807356, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3835949, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3886965, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3891845, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3899501, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7996945, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3916081, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4017346, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4068767, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4167899, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4191406, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4269653, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8088717, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4285686, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4291563, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4359363, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4423037, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4427214, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4438279, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4445741, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4485708, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4495040, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4519173, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4528676, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4701757, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4790241, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4915671, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4916357, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4922953, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4967637, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5036307, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7969255, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8037184, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7781831, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5290283, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5303626, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5355270, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5415809, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5447206, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5488795, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8079773, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5509104, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5526481, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5528857, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7688201, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8058572, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5647878, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5656567, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5676280, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7673058, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5707552, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5728352, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5793381, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5821393, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5836766, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7957796, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7200682, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7921008, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8105829, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8101901, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8096883, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8095434, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5988356, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5989603, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7789330, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6014260, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7954036, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6020429, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6028667, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6050409, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7954454, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8031450, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6072771, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6081419, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6103873, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6120874, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6143345, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6167892, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6173584, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6196315, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7938939, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6231212, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7711764, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7370043, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6302323, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7924696, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6304428, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6333727, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6345425, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6359099, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7460879, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6390744, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8020694, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6414113, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6423947, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6424545, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6431087, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8000711, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6478329, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6500740, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6511462, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8085547, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6513804, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6529930, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6543993, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6550790, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6592074, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6599540, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6619693, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6635109, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6642489, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6666160, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6676082, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6696437, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6706928, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6712444, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6712845, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6754998, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6757927, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6771591, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6786690, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6818206, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6861583, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6907050, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6915054, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6937645, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6947056, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6976580, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6978834, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6980526, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6987019, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7011308, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7015219, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7565629, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7028768, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7032452, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7036182, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8072911, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7039171, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7039431, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7040055, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7041267, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7704744, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7058096, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7062559, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7657878, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7084994, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7588824, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7786805, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7100506, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7119717, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7121386, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7134903, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7140916, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7153690, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7194622, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7219119, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7234546, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7236520, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7246074, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7282284, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7288164, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7290183, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7294977, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7296582, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7300580, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7305804, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7712823, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7340738, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8029633, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7666132, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7660929, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7662862, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7664684, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7689154, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7689766, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7692322, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (293597, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7701771, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7708954, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7725674, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8069774, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7783601, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7738669, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7748879, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7749610, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7752287, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7755384, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7761101, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7763133, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7772169, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7776574, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7779097, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8013621, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7795261, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7798546, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7799980, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7805406, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7808226, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7810827, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7827011, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7828898, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7843525, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7862403, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7867407, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7871242, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7876528, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7886918, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7906289, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7909695, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7916627, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1701758, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7833004, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6111297, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7702640, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7585799, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7406516, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7862674, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7894132, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8060898, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7532468, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7725132, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (1218444, 'Leucoderma', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7824846, 'Leucoderma', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8025416, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7887334, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8026981, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6340845, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7120564, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8029809, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8031497, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8012807, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8035060, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8036718, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8037053, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8042696, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8043764, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8044489, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8038396, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8049333, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8038457, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8055705, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8039949, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8059586, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8060483, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8060744, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8069912, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8072578, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8076607, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8077294, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8071514, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8089207, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8102183, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8104893, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6552355, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8083968, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6871068, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8112712, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6844975, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8117773, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7211204, 'Thalassemia', 'F');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7887533, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8025950, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8026269, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7887384, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8026373, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898901, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8029236, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8029293, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8029305, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8029511, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898904, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7995344, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8030094, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898804, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8030295, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8030364, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8030863, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898964, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898840, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8022332, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7962997, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8032726, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7187989, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8035051, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8038178, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8038293, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8038385, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8038849, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8018356, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8039075, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8037573, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898758, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898637, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898465, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898384, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898366, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8036519, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8040027, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7391800, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8041331, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7887243, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8041991, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8042260, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8042435, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8008250, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8044091, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7575122, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8045828, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8021002, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8046493, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8046622, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8046931, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8047411, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8047667, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7726161, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4873956, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8051068, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7528758, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8053163, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8040632, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8053409, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7990435, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7865401, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8055685, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8015930, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8055824, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8055319, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8056301, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8057850, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (614220, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8058357, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8058441, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8059414, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8059171, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7988486, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8059968, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8060433, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7735975, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8063421, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8064037, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8063733, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8064472, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8064884, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8064940, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8055270, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8060723, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8018852, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8068087, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8068228, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8068982, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8066466, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8070898, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8070998, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8071245, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8067250, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8028776, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8072678, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8073289, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8072203, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8072750, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6966232, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8034916, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8078645, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8069096, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8079628, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8080314, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8073713, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8077234, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8083250, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8083270, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5575056, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8083536, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8083556, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8084204, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8084635, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8085406, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8085642, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8085842, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7695232, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5525739, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8087821, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8088543, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8088910, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8087361, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8083940, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (5091032, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7883622, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (6228796, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8092035, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8020249, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8093069, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8093748, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8094344, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8090488, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8095117, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8023722, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8088867, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7986639, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8098634, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8077889, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8098545, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7169992, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8101797, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8101384, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8096619, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8104033, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8104779, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8098930, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8013274, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8106637, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7769017, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8100629, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8085959, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8108617, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7738367, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (3480299, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7659754, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7395246, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8111246, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8112288, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7370331, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7771401, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (2261234, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8083422, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8113977, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8095340, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898963, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898928, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7273587, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898889, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7634489, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7898849, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7571644, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8114991, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7350694, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8116641, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8116706, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8117819, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8118406, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8118499, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8118718, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8110431, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7991342, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8112819, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8121181, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (4851395, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8122985, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8123893, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7678295, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8125403, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (7701779, 'Thalassemia', 'M');
INSERT INTO `SPECIAL_CASES_PROFILES` VALUES (8049643, 'Thalassemia', 'M');

ALTER TABLE `SEARCH_MALE_TEXT` ADD INDEX ('HIV'),ADD INDEX ('NATURE_HANDICAP');

ALTER TABLE `SEARCH_FEMALE_TEXT` ADD INDEX ('HIV'),ADD INDEX ('NATURE_HANDICAP');

USE MIS;
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1409', 'L1_SP_1409', 'SEO_COM_SP_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1410', 'L1_SP_1410', 'SEO_COM_SP_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1411', 'L1_SP_1411', 'SEO_COM_SP_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1412', 'L1_SP_1412', 'SEO_COM_SP_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1413', 'L1_SP_1413', 'SEO_COM_SP_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1414', 'L1_SP_1414', 'SEO_COM_SP_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1415', 'L1_SP_1415', 'SEO_COM_SP_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1416', 'L1_SP_1416', 'SEO_COM_SP_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1417', 'L1_SP_1417', 'SEO_COM_SP_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1418', 'L1_SP_1418', 'SEO_COM_SP_B_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1419', 'L1_SP_1419', 'SEO_COM_SP_B_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1420', 'L1_SP_1420', 'SEO_COM_SP_B_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1421', 'L1_SP_1421', 'SEO_COM_SP_B_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1422', 'L1_SP_1422', 'SEO_COM_SP_B_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1423', 'L1_SP_1423', 'SEO_COM_SP_B_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1424', 'L1_SP_1424', 'SEO_COM_SP_B_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1425', 'L1_SP_1425', 'SEO_COM_SP_B_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1426', 'L1_SP_1426', 'SEO_COM_SP_B_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1427', 'L1_SP_1427', 'SEO_COM_SP_G_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1428', 'L1_SP_1428', 'SEO_COM_SP_G_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1429', 'L1_SP_1429', 'SEO_COM_SP_G_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1430', 'L1_SP_1430', 'SEO_COM_SP_G_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1431', 'L1_SP_1431', 'SEO_COM_SP_G_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1432', 'L1_SP_1432', 'SEO_COM_SP_G_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1433', 'L1_SP_1433', 'SEO_COM_SP_G_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1434', 'L1_SP_1434', 'SEO_COM_SP_G_L1', 'Y', 0, '', '', '', 0);
INSERT INTO `SOURCE` (SourceID, SourceName, GROUPNAME , ACTIVE , CPC, FORCE_EMAIL , NOREG , SourceGifType ,PID) VALUES ('L1_SP_1435', 'L1_SP_1435', 'SEO_COM_SP_G_L1', 'Y', 0, '', '', '', 0);

        
