DROP TABLE IF EXISTS MIS.TRACK_DUPLICATE_EMAIL;

CREATE TABLE `TRACK_DUPLICATE_EMAIL` (
 `EMAIL` varchar(100) NOT NULL,
 `IP` varchar(16) NOT NULL,
 `TIME` datetime NOT NULL,
 `PAGE` varchar(7) DEFAULT NULL,
 `FLAG` varchar(1) NOT NULL,
 KEY `TIME` (`TIME`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1
