use newjs;

CREATE TABLE `PICTURE_DELETE_NEW` (
 `PROFILEID` int(11) NOT NULL,
 `PICTUREID` int(11) NOT NULL,
 `MAIN_PHOTO_URL` varchar(200) NOT NULL,
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`PICTUREID`)
) ENGINE=InnoDB;
