use incentive;

CREATE TABLE `SALES_REGISTRATION_CSV_DATA`(
 `PROFILEID` int(10) NOT NULL,
 `USERNAME` varchar(40) NOT NULL, 
 `ENTRY_DT` datetime DEFAULT '0000-00-00 00:00:00',
 `GENDER` char(1) DEFAULT '',
 `RELATION` varchar(40) DEFAULT '',
 `CITY_RES` varchar(40) DEFAULT '',
 `LOCALITY` varchar(40) DEFAULT '',
 `MOBILE1` varchar (12) DEFAULT '',
 `LANDLINE` varchar(12) DEFAULT '',
 `MOBILE2` varchar(12) DEFAULT '',
 `CSV_ENTRY_DATE` date DEFAULT '0000-00-00',
 PRIMARY KEY (`PROFILEID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`CSV_ENTRY_DATE`)
)ENGINE=InnoDB;

CREATE TABLE `SALES_REGISTRATION_CSV_DATA_TEMP` (
 `PROFILEID` int(11) unsigned NOT NULL,
 `USERNAME` varchar(40) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
 `GENDER` char(1) DEFAULT '',
 `AGE` tinyint(4) DEFAULT 0,
 `SUBSCRIPTION` varchar(10) DEFAULT '',
 `ENTRY_DT` datetime DEFAULT '0000-00-00 00:00:00',
 `RELATION` char(2) DEFAULT '',
 `CITY_RES` varchar(4) DEFAULT '',
 `PHONE_MOB` varchar(15) DEFAULT '',
 `PHONE_WITH_STD` varchar(15) DEFAULT '',
 `PINCODE` int(6) NOT NULL,
 PRIMARY KEY (`PROFILEID`)
)ENGINE=InnoDB;

