use newjs;


/**
* DOWNTIME Around 20 minutes for 51 lac records
**/
ALTER TABLE `newjs`.`PICTURE_NEW` ADD
`ProfilePic120Url` VARCHAR( 200 ) NOT NULL AFTER MobileAppPicUrl,
ADD `ProfilePic235Url` VARCHAR( 200 ) NOT NULL AFTER ProfilePic120Url,
ADD `ProfilePic450Url` VARCHAR( 200 ) NOT NULL AFTER ProfilePic235Url,
ADD `OriginalPicUrl` VARCHAR( 200 ) NOT NULL  AFTER ProfilePic450Url;
 


/**
* Very Low DOWNTIME,few entries
**/
ALTER TABLE `newjs`.`PICTURE_FOR_SCREEN_NEW` ADD `ProfilePic120Url` VARCHAR( 200 ) NOT NULL AFTER `Thumbail96Url` ,
ADD `ProfilePic235Url` VARCHAR( 200 ) NOT NULL AFTER `ProfilePic120Url` ,
ADD `ProfilePic450Url` VARCHAR( 200 ) NOT NULL AFTER `ProfilePic235Url` ,
ADD `OriginalPicUrl` VARCHAR( 200 ) NOT NULL AFTER `ProfilePic450Url` ;

ALTER TABLE `newjs`.`PICTURE_FOR_SCREEN_NEW` ADD `MobileAppPicUrl` VARCHAR( 200 ) NOT NULL AFTER `Thumbail96Url` ;

ALTER TABLE `newjs`.`PICTURE_FOR_SCREEN_NEW` ADD `SCREEN_BIT` VARCHAR( 10 ) DEFAULT '0000000' NOT NULL AFTER `OriginalPicUrl` ;

ALTER TABLE `newjs`.`PICTURE_DELETE_NEW` ADD `TYPE` VARCHAR( 2 ) DEFAULT 'S' NOT NULL ,
ADD `REASON` VARCHAR( 40 ) NOT NULL ;
