use MIS;

CREATE TABLE `MOB_VERIFY` (
 `PROFILEID` int(11) NOT NULL,
 `MOBILE_NO` varchar(20) NOT NULL,
 `GUID` varchar(50) NOT NULL,
 `DATE_OF_ENTRY` date NOT NULL,
 `INVALID` char(1) NOT NULL,
 `DATE_OF_VERIF` date NOT NULL,
 `MESSAGE_TYPE` varchar(20) NOT NULL,
 KEY `PROFILEID` (`PROFILEID`),
 KEY `GUID` (`GUID`),
 KEY `DATE_OF_ENTRY` (`DATE_OF_ENTRY`),
 KEY `DATE_OF_VERIF` (`DATE_OF_VERIF`),
 KEY `MOBILE_NO` (`MOBILE_NO`)
) ENGINE=MyISAM;

CREATE TABLE `INVALID_NOS` (
 `MOBILE_NO` varchar(20) NOT NULL,
 `DATE` date NOT NULL,
 PRIMARY KEY  (`MOBILE_NO`)
) ENGINE=MyISAM;
