use billing;

INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`, `MOST_POPULAR`, `FREEBIES`, `ENABLE`) VALUES ('', 'ESJA3', 'JS Assisted - 3 Months', '', 3, 0, '6995', '135','Y','','PESJA3','N', '155','N', 'Y', 'Y','N','');

UPDATE SERVICES SET PRICE_RS=ROUND(PRICE_RS_TAX/1.1236,2) WHERE SERVICEID='ESJA3';

INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESJA3', 'P3');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESJA3', 'T3');
