use duplicates;

CREATE TABLE DUPLICATE_CHECKS_FIELDS_LEGACY 
SELECT PROFILEID, 'N' AS FLAG, CURRENT_TIMESTAMP() AS TIMESTAMP FROM newjs.JPROFILE WHERE LAST_LOGIN_DT > DATE_SUB( CURDATE( ) , INTERVAL 6 MONTH );
