INSERT INTO incentive.LOCATION(`VALUE`,`NAME`,`STATE`,`REGION`,`SPECIAL_CITY`) VALUES('MH28','Navi Mumbai','MH','S','');
INSERT INTO incentive.LOCATION(`VALUE`,`NAME`,`STATE`,`REGION`,`SPECIAL_CITY`) VALUES('MH12','Thane','MH','S','');

update incentive.SUB_LOCATION SET PRIORITY='MH28' WHERE VALUE='MH28';
update incentive.SUB_LOCATION SET PRIORITY='MH12' WHERE VALUE='MH12';

INSERT INTO incentive.FIELD_SALES_CITY (`VALUE`,`NAME`) VALUES('UP28','Navi Mumbai');
INSERT INTO incentive.FIELD_SALES_CITY (`VALUE`,`NAME`) VALUES('UP12','Thane');
