CREATE TABLE `SALES_TARGET` (
  `USERNAME` varchar(100) NOT NULL DEFAULT '',
  `INDIVIDUAL_TARGET` int(11) DEFAULT '0',
  `FINAL_TARGET` int(11) DEFAULT '0',
  `TARGET_MONTH` varchar(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`USERNAME`,`TARGET_MONTH`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `SALES_TARGET` ADD COLUMN `MONTHWISE_ORDER` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `SALES_TARGET` ADD COLUMN `MONTHWISE_LEVEL` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `SALES_TARGET` ADD COLUMN `HAS_DIRECT_REPORTEE` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `SALES_TARGET` DROP PRIMARY KEY, ADD PRIMARY KEY (`USERNAME`,`TARGET_MONTH`,`MONTHWISE_ORDER`);
ALTER TABLE `SALES_TARGET` DROP PRIMARY KEY, ADD PRIMARY KEY (`USERNAME`,`TARGET_MONTH`);
