use MIS;

CREATE TABLE `PHOTO_PRIVACY_LAYER_LOG` (
 `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(10) unsigned NOT NULL,
 `FROM_PAGE` varchar(20) NOT NULL,
 `TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `OPTION_SELECTED` tinyint(4) NOT NULL,
 PRIMARY KEY (`ID`),
 KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM;
