use billing;

UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'P4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'B4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'D4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'C4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'A4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'T4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'M4' LIMIT 1 ;
UPDATE `SERVICES` SET `SHOW_ONLINE` = 'Y' WHERE `SERVICEID` = 'L4' LIMIT 1 ;

