DROP TABLE IF EXISTS `BEST_MATCH_SMS_LOG`;
CREATE TABLE IF NOT EXISTS `BEST_MATCH_SMS_LOG` (
  `ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `PROFILEID` mediumint(9) NOT NULL,
  `BEST_MATCH` mediumint(9) NOT NULL,
  `DATE` date NOT NULL,
  `SCORE` float DEFAULT NULL,
  `SENT` char(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROFILEID` (`PROFILEID`,`BEST_MATCH`)
)


ALTER TABLE  `SMS_TEMP_TABLE` ADD  `OWN_HOUSE` CHAR( 1 ) NOT NULL ,
ADD  `FAMILY_INCOME` TINYINT( 3 ) NOT NULL ,
ADD  `COMPANY_NAME` TEXT NOT NULL ,
ADD  `VIEW_COUNT` FLOAT( 4 ) NOT NULL ;



INSERT INTO  `SMS_TYPE` (  `ID` ,  `SMS_KEY` ,  `SMS_TYPE` ,  `PRIORITY` ,  `SUBSCRIPTION` ,  `GENDER` ,  `COUNT` ,  `TIME_CRITERIA` ,  `CUSTOM_CRITERIA` ,  `SMS_SUBSCRIPTION` ,  `STATUS` ,  `MESSAGE` ) 
VALUES ('', 'MATCH_ALERT', 'D', 102, 'P', 'A', 'SINGLE', 30, 0, 'SERVICE', 'Y', 'Match of the Day-{AGE} yrs,{HEIGHT},{CASTE},{OWN_HOUSE}{CITY_RES},{EDU_LEVEL},{INCOME},{OCCUPATION}{COMPANY}. Click {URL_EOI} to contact'), ('', 'MATCH_ALERT', 'D', 102, 'F', 'A', 'SINGLE', 30, 0, 'SERVICE', 'Y', 'Match of the Day-{AGE} yrs,{HEIGHT},{CASTE},{OWN_HOUSE}{CITY_RES},{EDU_LEVEL},{INCOME},{OCCUPATION}{COMPANY}. Click {URL_EOI} /Call:{TOLLNO}'),
 ('', 'MATCH_ALERT', 'D', 102, 'P', 'A', 'SINGLE', 30, 1, 'SERVICE', 'Y', 'Match of the Day-{AGE} yrs,{CASTE},{OWN_HOUSE}{CITY_RES},{FAMILY_INCOME},{OCCUPATION}{COMPANY}. Click {URL_EOI} to contact'), ('', 'MATCH_ALERT', 'D', 102, 'F', 'A', 'SINGLE', 30, 1, 'SERVICE', 'Y', 'Match of the Day-{AGE} yrs,{HEIGHT}{CASTE},{OWN_HOUSE}{CITY_RES},{FAMILY_INCOME},{OCCUPATION} {COMPANY}. Click {URL_EOI}/CAll:{TOLLNO}');


