use incentive;

INSERT INTO `CRM_DISPOSITION` (`DISPOSOTION_VALUE`, `DISPOSOTION_LABEL`, `ACTIVE`) VALUES ('MA', 'Manual Allocation', 'Y');
INSERT INTO `CRM_DISPOSITION_VALIDATION` (`DISPOSITION`, `VALIDATION_VALUE`, `VALIDATION_LABEL`) VALUES ('MA', 'MA1', 'Call Source');
