use newjs;

ALTER TABLE `EDUCATION_LEVEL_NEW_CLUSTER` RENAME `EDUCATION_LEVEL_NEW_CLUSTER_NOUSE` ;

DROP TABLE IF EXISTS EDUCATION_LEVEL_NEW;

CREATE TABLE `EDUCATION_LEVEL_NEW` (
  `ID` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `LABEL` varchar(150) NOT NULL DEFAULT '',
  `VALUE` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `OLD_VALUE` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `SORTBY` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `GROUPING` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `VALUE` (`VALUE`)
) ENGINE=MyISAM AUTO_INCREMENT=43 DEFAULT CHARSET=latin1 AUTO_INCREMENT=43 ;

-- 
-- Dumping data for table `EDUCATION_LEVEL_NEW`
-- 

INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (1, 'B.A', 1, 4, 3, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (2, 'B.Com', 2, 4, 5, 5);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (3, 'B.E/B.Tech', 3, 4, 6, 4);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (4, 'B.Pharma', 4, 4, 9, 4);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (5, 'B.Sc', 5, 4, 10, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (6, 'BL/LLB', 6, 4, 17, 7);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (7, 'CA', 7, 5, 19, 5);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (8, 'CS', 8, 5, 21, 5);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (9, 'Diploma', 9, 3, 22, 1);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (10, 'ICWA', 10, 5, 23, 5);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (11, 'M.A', 11, 5, 24, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (12, 'M.Com', 12, 5, 26, 5);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (13, 'M.E/M.Tech', 13, 5, 28, 4);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (14, 'M.Pharma', 14, 5, 30, 4);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (15, 'M.Sc', 15, 5, 34, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (16, 'MBA/PGDM', 16, 5, 35, 6);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (17, 'MBBS', 17, 4, 36, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (18, 'MCA/PGDCA', 18, 5, 37, 3);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (19, 'M.D.', 19, 6, 27, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (20, 'ML/LLM', 20, 5, 38, 7);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (21, 'Ph. D', 21, 6, 40, 9);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (22, 'Other', 22, 0, 41, 10);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (23, 'High School', 23, 1, 1, 1);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (24, 'Trade School', 24, 2, 2, 1);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (25, 'BAMS', 25, 4, 11, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (26, 'BHMS', 26, 4, 16, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (28, 'BDS', 28, 4, 14, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (29, 'M.S. (Engineering)', 29, 5, 32, 4);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (30, 'M.S. (Medicine)', 30, 6, 33, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (31, 'MVSc.', 31, 5, 39, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (32, 'BVSc.', 32, 4, 18, 2);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (33, 'BCA', 33, 4, 13, 3);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (34, 'B.IT', 34, 4, 8, 3);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (35, 'B.Arch', 35, 4, 4, 4);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (36, 'M.Arch', 36, 5, 25, 4);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (37, 'CFA', 37, 5, 20, 5);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (38, 'BBA', 38, 4, 12, 6);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (39, 'BHM', 39, 4, 15, 6);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (40, 'B.Ed', 40, 4, 7, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (41, 'M.Ed', 41, 5, 29, 8);
INSERT INTO `EDUCATION_LEVEL_NEW` VALUES (42, 'M.Phil', 42, 5, 31, 9);

CREATE TABLE `EDUCATION_GROUPING` (
  `LABEL` varchar(50) NOT NULL,
  `VALUE` tinyint(2) NOT NULL,
  `SORTBY` tinyint(2) NOT NULL,
  PRIMARY KEY (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- 
-- Dumping data for table `EDUCATION_GROUPING`
-- 

INSERT INTO `EDUCATION_GROUPING` VALUES ('Non-Graduate', 1, 9);
INSERT INTO `EDUCATION_GROUPING` VALUES ('Medicine', 2, 5);
INSERT INTO `EDUCATION_GROUPING` VALUES ('Computers', 3, 2);
INSERT INTO `EDUCATION_GROUPING` VALUES ('Engineering', 4, 1);
INSERT INTO `EDUCATION_GROUPING` VALUES ('Finance/Commerce', 5, 3);
INSERT INTO `EDUCATION_GROUPING` VALUES ('Management', 6, 4);
INSERT INTO `EDUCATION_GROUPING` VALUES ('Law', 7, 6);
INSERT INTO `EDUCATION_GROUPING` VALUES ('Arts/Science', 8, 7);
INSERT INTO `EDUCATION_GROUPING` VALUES ('Doctorate', 9, 8);
INSERT INTO `EDUCATION_GROUPING` VALUES ('Other', 10, 10);

use MIS;

ALTER TABLE `REVAMP_LAYER_CHECK` ADD `OLD_EDUCATION` SMALLINT( 5 ) NOT NULL AFTER `OLD_PROFESSION` ;

DELETE FROM `REVAMP_LAYER_CHECK` WHERE CASTE_REVAMP_FLAG =0;

use bms2;

DROP TABLE IF EXISTS EDUCATION;

CREATE TABLE EDUCATION LIKE newjs.EDUCATION_LEVEL_NEW;

INSERT INTO EDUCATION SELECT * FROM newjs.EDUCATION_LEVEL_NEW;
