use incentive;

CREATE TABLE `ALLOCATION_BUCKET` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROCESS_ID` enum('S','FTO','U','R') DEFAULT NULL,
  `BUCKET_TYPE` enum('AP','EP','AL','EL') DEFAULT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `VALUE` int(11) DEFAULT NULL,
  `ENTRY_BY` varchar(50) NOT NULL,
  `ENTRY_DT` date NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROCESS_ID` (`PROCESS_ID`,`BUCKET_TYPE`)
) ENGINE=InnoDB;

INSERT INTO `ALLOCATION_BUCKET` (`ID`, `PROCESS_ID`, `BUCKET_TYPE`, `NAME`, `VALUE`, `ENTRY_BY`, `ENTRY_DT`) VALUES (1, 'S', 'AP', 'Sales Allocation Period', 15, '', now());
INSERT INTO `ALLOCATION_BUCKET` (`ID`, `PROCESS_ID`, `BUCKET_TYPE`, `NAME`, `VALUE`, `ENTRY_BY`, `ENTRY_DT`) VALUES (2, 'S', 'EP', 'Sales Extension Period', 15, '', now());
INSERT INTO `ALLOCATION_BUCKET` (`ID`, `PROCESS_ID`, `BUCKET_TYPE`, `NAME`, `VALUE`, `ENTRY_BY`, `ENTRY_DT`) VALUES (3, 'S', 'AL', 'Sales Allocation Limit', 265, '', now());
INSERT INTO `ALLOCATION_BUCKET` (`ID`, `PROCESS_ID`, `BUCKET_TYPE`, `NAME`, `VALUE`, `ENTRY_BY`, `ENTRY_DT`) VALUES (10, 'R', 'AP', 'Renewal Allocation Period', 10, '', now());
INSERT INTO `ALLOCATION_BUCKET` (`ID`, `PROCESS_ID`, `BUCKET_TYPE`, `NAME`, `VALUE`, `ENTRY_BY`, `ENTRY_DT`) VALUES (11, 'U', 'AP', 'Upsell Allocation Period', 15, '', now());


ALTER TABLE incentive.MAIN_ADMIN DROP CONTACTS_ACC,DROP CONTACTS_RCV;
ALTER TABLE incentive.PROFILE_ALLOCATION_TECH MODIFY HANDLED enum('N','Y'),MODIFY STATUS enum('N'),MODIFY PROFILE_TYPE enum('N','O'); 

ALTER TABLE incentive.CRM_DAILY_ALLOT ADD `DE_ALLOCATION_DT` date NOT NULL,ADD `ALLOCATION_DAYS` int(11) NOT NULL,ADD KEY DE_ALLOCATION_DT(`DE_ALLOCATION_DT`);
UPDATE incentive.CRM_DAILY_ALLOT SET ALLOCATION_DAYS=30 WHERE ALLOT_TIME<'2009-11-01';
UPDATE incentive.CRM_DAILY_ALLOT SET ALLOCATION_DAYS=15 WHERE ALLOT_TIME>='2009-11-01';
UPDATE incentive.CRM_DAILY_ALLOT SET DE_ALLOCATION_DT=DATE_ADD(ALLOT_TIME,INTERVAL (ALLOCATION_DAYS+RELAX_DAYS) DAY);
CREATE INDEX PHOTODATE ON newjs.JPROFILE (`PHOTODATE`);

