CREATE TABLE billing.`OFFER_DISCOUNT` (
 `PROFILEID` mediumint(11) NOT NULL,
 `SERVICEID` varchar(40) NOT NULL,
 `DISCOUNT` tinyint(4) NOT NULL,
 `EXPIRY_DT` date NOT NULL,
 PRIMARY KEY (`PROFILEID`),
 KEY `EXPIRY_DT` (`EXPIRY_DT`)
) ENGINE=MyISAM;


CREATE TABLE billing.`OFFER_DISCOUNT_TEMP` (
 `PROFILEID` mediumint(11) NOT NULL,
 `SERVICEID` varchar(40) NOT NULL,
 `DISCOUNT` tinyint(4) NOT NULL,
 `EXPIRY_DT` date NOT NULL,
 PRIMARY KEY (`PROFILEID`),
 KEY `EXPIRY_DT` (`EXPIRY_DT`)
) ENGINE=MyISAM;

UPDATE SERVICES SET SHOW_ONLINE='S',SORTBY=1 WHERE SERVICEID='P1' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='S',SORTBY=2 WHERE SERVICEID='C1' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='S',SORTBY=5 WHERE SERVICEID='A1' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='S',SORTBY=4 WHERE SERVICEID='M1' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='S',SORTBY=6 WHERE SERVICEID='T1' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='S',SORTBY=3 WHERE SERVICEID='B1' LIMIT 1;

INSERT INTO `DIRECT_CALL_COUNT` VALUES ('P1', 10);
INSERT INTO `DIRECT_CALL_COUNT` VALUES ('C1', 10);
