use newjs;
UPDATE SMS_TYPE
SET MESSAGE = REPLACE(MESSAGE, 'AMOBILE', 'TOLLNO')
WHERE ID IN (19,20,21,22,23)

use newjs;
UPDATE SMS_TYPE
SET MESSAGE = REPLACE(MESSAGE, 'TOLLNO', 'AMOBILE')
WHERE ID IN (19,20,21,22,23)
