use incentive;

CREATE TABLE `TEMP_NEW_REGISTRATION_SALES` (
 `PROFILEID` int(11) unsigned NOT NULL,
 `USERNAME` varchar(40) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
 `GENDER` char(1) DEFAULT '',
 `ENTRY_DT` datetime DEFAULT '0000-00-00 00:00:00',
 `RELATION` char(2) DEFAULT '',
 `CITY_RES` varchar(4) DEFAULT '',
 `MOBILE1` varchar(15) DEFAULT '',
 `MOBILE2` varchar(15) DEFAULT '',
 `LANDLINE` varchar(15) DEFAULT '',
 PRIMARY KEY (`PROFILEID`)
);

CREATE TABLE `NEW_REGISTRATION_SALES_LOG` (
 `PROFILEID` int(11) unsigned NOT NULL,
 PRIMARY KEY (`PROFILEID`)
);

