use billing;

INSERT INTO `SERVICES` (`SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`) VALUES ('X12', 'JS Exclusive - 12 months', '', 12, 27590.78, 31001, 601, 'N', 'X12', '', 'Y', 141, 'N', 'Y');

INSERT INTO `COMPONENTS` (`COMPID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_DOL`, `RIGHTS`, `TYPE`, `ACC_COUNT`) VALUES ('X12', 'JS Exclusive - 12 months', '', 12, 31001, 601, 'X', 'D', 0);
