USE MIS;
CREATE TABLE `TRENDS_FILTERS_PERFORMANCE` (
  `ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `SENDER` int(10) unsigned NOT NULL,
  `RECEIVER` int(10) unsigned NOT NULL,
  `AGE` char(1) NOT NULL,
  `CASTE` char(1) NOT NULL,
  `MTONGUE` char(1) NOT NULL,
  `CITY_RES` char(1) NOT NULL,
  `COUNTRY_RES` char(1) NOT NULL,
  `MSTATUS` char(1) NOT NULL,
  `RELIGION` char(1) NOT NULL,
  `INCOME` char(1) NOT NULL,
  `TRENDS_EXISTS` char(1) NOT NULL,
  `SPAM_TRACKED_BY_TRENDS` char(1) DEFAULT NULL,
  `DATE` date NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SENDER` (`SENDER`,`RECEIVER`,`DATE`),
  KEY `DATE` (`DATE`)
) ENGINE=MyISAM;
