use incentive;

ALTER TABLE SALES_CSV_DATA_TEMP ADD `ENTRY_DT` date NOT NULL DEFAULT '0000-00-00';

CREATE TABLE `SALES_REGULAR_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE` date NOT NULL DEFAULT '0000-00-00',
  `FILTER` varchar(100) NOT NULL DEFAULT '',
  `FILTERED_PROFILES` int(11) DEFAULT '0',
  `COUNT` int(11) NOT NULL DEFAULT '0',
  `LATEST_REG_DT` date DEFAULT NULL,
  `LATEST_REG_FILTERED_PROFILES` int(11) DEFAULT '0',
  `LATEST_REG_COUNT` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DATE` (`DATE`,`FILTER`)
) ENGINE=InnoDB;

