use incentive;
ALTER TABLE incentive.MAIN_ADMIN MODIFY REASON varchar(40) NOT NULL;
ALTER TABLE incentive.HISTORY MODIFY VALIDATION varchar(40) NOT NULL;
ALTER TABLE incentive.MANUAL_ALLOT MODIFY CALL_SOURCE varchar(40) NOT NULL;
