USE newjs;

UPDATE  `SMS_TYPE` SET  `MESSAGE` =  'Match of the Day-{AGE} yrs,{HEIGHT},{CASTE},{OWN_HOUSE}{CITY_RES},{EDU_LEVEL},{INCOME},{OCCUPATION}{COMPANY}. Profile ID-{OTHER_USERNAME} /Call:{TOLLNO}' WHERE  `ID` = '86' LIMIT 1 ;

UPDATE  `SMS_TYPE` SET  `MESSAGE` =  'Match of the Day-{AGE} yrs,{HEIGHT}{CASTE},{OWN_HOUSE}{CITY_RES},{FAMILY_INCOME},{OCCUPATION} {COMPANY}. Profile ID-{OTHER_USERNAME} /CAll:{TOLLNO}' WHERE  `ID` =  '88' LIMIT 1 ;

UPDATE  `SMS_TYPE` SET  `MESSAGE` =  'Match of the Day-{AGE}yrs, {HEIGHT}, {WEIGHT}, {CASTE}, {MTONGUE}, {OCCUPATION} in {CITY_RES}. Profile ID-{OTHER_USERNAME} /Call:{TOLLNO}' WHERE  `ID` =  '158' LIMIT 1 ;

UPDATE  `SMS_TYPE` SET  `MESSAGE` =  'Match of the Day-{AGE}yrs, {HEIGHT}, {FAMILY_INCOME}, {EDU_LEVEL}, {CASTE}, {OCCUPATION} in {CITY_RES}. Profile ID-{OTHER_USERNAME} /Call:{TOLLNO}' WHERE  `ID` =  '160' LIMIT 1 ;
