use billing;

CREATE TABLE `VARIABLE_DISCOUNT_POOL_TECH`(
  `PROFILEID` int(11) NOT NULL DEFAULT 0,
  `SCORE` tinyint(3) DEFAULT 0,
  `GENDER` char(1) DEFAULT '',
  `MTONGUE` tinyint(3) DEFAULT 0,
  `DISCOUNT` tinyint(3) DEFAULT 0,
  `VD_GIVEN` char(1) DEFAULT 'N',
  UNIQUE KEY `PROFILEID` (`PROFILEID`),
  KEY `SCORE` (`SCORE`) 
) ENGINE=InnoDB;

CREATE TABLE `DISCOUNT_LOOKUP` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SCORE_LOWER_LIMIT` tinyint(3) DEFAULT 0,
  `SCORE_UPPER_LIMIT` tinyint(3) DEFAULT 0,
  `GENDER` char(1) DEFAULT '',
  `MTONGUE` tinyint(3) DEFAULT 0,
  `DISCOUNT_BASE` tinyint(3) DEFAULT 0,
  `DISCOUNT_OTHER` tinyint(3) DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `VARIABLE_DISCOUNT_DURATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SDATE` date NOT NULL,	 
  `EDATE` date NOT NULL,
  `ENTRY_DT` date NOT NULL,
  `STEPS_COMPLETED` varchar(5) DEFAULT '',
   PRIMARY KEY (`ID`),
   KEY `ENTRY_DT` (`ENTRY_DT`)	
) ENGINE=InnoDB;

CREATE TABLE `VD_GIVEN_LASTTIME` (
  `PROFILEID` int(11) NOT NULL DEFAULT 0,
   UNIQUE KEY `PROFILEID` (`PROFILEID`)				
) ENGINE=InnoDB;



