use sugarcrm;

CREATE TABLE `SUGAR_DIALER_DISPOSITION_MAPPING` (
  `DIALER_DISP` varchar(100) NOT NULL,
  `SUGAR_STATUS` varchar(100) NOT NULL,
  `STATUS_VALUE` tinyint(4) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Already Married', 'Engaged / Married', 18);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Already Paid in JS', 'Registered', 26);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Answering Machine', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Blank Call', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Branch Details', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Call Back', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Call Disconnected', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Client Busy', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Complaints', 'Lead Not Interested', 14);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Deceased', 'Lead Not Interested', 14);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Incomplete Profile', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Incorrect Number', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Irrelevant', 'Lead Not Interested', 14);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Language Barrier', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Multiple Inactive Profiles', 'Lead Not Interested', 14);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Multiple Profiles', 'Lead Not Interested', 14);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('New Registration', 'Registered', 26);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('No Answer', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Non Serious Profile', 'Lead Not Interested', 14);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Not At home', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Not interested', 'Lead Not Interested', 14);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Not reachable', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Number Changed', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Offline Query', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Paid on another profile', 'Registered', 26);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Profile registered by Matchpoint', 'Registered', 26);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Registered', 'Registered', 26);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Schedule Call Back', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Service Query', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Test Profile', 'Lead Not Interested', 14);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Wrong Person', 'Lead Not Interested', 14);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Blank', 'Lead Auto-follow up', 13);
INSERT INTO `SUGAR_DIALER_DISPOSITION_MAPPING` VALUES ('Busy Number', 'Lead Auto-follow up', 13);
