use jsadmin;
CREATE TABLE `AGENT_ALLOTED` (
  `USER` varchar(50) NOT NULL DEFAULT '',
  `METHOD` varchar(50) NOT NULL DEFAULT '' 
);
INSERT INTO `AGENT_ALLOTED` VALUES ('', 'UPSELL');
INSERT INTO `AGENT_ALLOTED` VALUES ('', 'RENEWAL');
INSERT INTO `AGENT_ALLOTED` VALUES ('', 'NEW_FAILED_PAYMENT');

use billing;
DROP TABLE TRACKING_FAILED_PAYMENT;
CREATE TABLE `TRACKING_FAILED_PAYMENT` (
 `PROFILEID` int(11) unsigned NOT NULL,
 `SERVICES` varchar(100) DEFAULT '',
 `ENTRY_DT` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `NET_AMOUNT` int(4) DEFAULT '0',
 `DISCOUNT` int(4) DEFAULT '0',
 `CURRENCY` char(3) DEFAULT '',
 `PAYMENT_TAB_CLICK` char(1) DEFAULT '',
 UNIQUE KEY `PROFILEID` (`PROFILEID`),
 KEY `ENTRY_DT` (`ENTRY_DT`)
)

CREATE TABLE `TRACKING_FAILED_PAYMENT_LOG` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) unsigned NOT NULL,
 `SERVICES` varchar(100) DEFAULT '',
 `ENTRY_DT` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `NET_AMOUNT` int(4) DEFAULT '0',
 `DISCOUNT` int(4) DEFAULT '0',
 `CURRENCY` char(3) DEFAULT '',
 `PAYMENT_TAB_CLICK` char(1) DEFAULT '',
 PRIMARY KEY (`ID`),
 KEY `PROFILEID` (`PROFILEID`),
 KEY `ENTRY_DT` (`ENTRY_DT`)
) ENGINE=InnoDB

ALTER TABLE TRACKING_FAILED_PAYMENT CHANGE PAYMENT_TAB_CLICK PAYMENT_OPTION_SELECTED varchar(25) DEFAULT '' 
ALTER TABLE TRACKING_FAILED_PAYMENT_LOG CHANGE PAYMENT_TAB_CLICK PAYMENT_OPTION_SELECTED varchar(25) DEFAULT ''

