use incentive;

ALTER TABLE incentive.IN_DIALER ADD `PRIORITY` tinyint(2) NULL,ADD ENTRY_DATE date NULL DEFAULT '0000-00-00';

CREATE TABLE `SALES_CSV_DATA_TEMP`(
 `PROFILEID` int(10) NOT NULL,
 `ANALYTIC_SCORE` tinyint(3) NULL DEFAULT 0,
 PRIMARY KEY (`PROFILEID`)
)ENGINE=InnoDB

CREATE TABLE `SALES_CSV_DATA_NOIDA`(
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(10) NOT NULL,
 `PRIORITY` tinyint(2) DEFAULT 0,
 `ANALYTIC_SCORE` tinyint(3) DEFAULT 0,
 `OLD_PRIORITY` tinyint(2) DEFAULT 0,
 `DIAL_STATUS` tinyint(1) DEFAULT 0,
 `AGENT` varchar(60) NULL DEFAULT '',
 `VD_PERCENT` tinyint(3) DEFAULT 0,
 `LAST_LOGIN_DATE` date NULL DEFAULT '0000-00-00',
 `PHONE_NO1` varchar(12) NULL DEFAULT '',
 `PHONE_NO2` varchar(12) NULL DEFAULT '',
 `PHOTO` char(3) NULL DEFAULT '',
 `DOB` date NULL DEFAULT '0000-00-00',
 `MSTATUS` varchar(40) NULL DEFAULT '',
 `EVER_PAID` char(3)  NULL DEFAULT '',
 `GENDER` char(6) NULL DEFAULT '',
 `POSTEDBY` varchar(40) NULL DEFAULT '',
 `NEW_VARIABLE1` varchar(20) NULL DEFAULT '',
 `NEW_VARIABLE2` varchar(20) NULL DEFAULT '',
 `NEW_VARIABLE3` varchar(20) NULL DEFAULT '',
 `PHONE_NO3` varchar(12) NOT NULL DEFAULT '',
 `PHONE_NO4` varchar(12)  NULL DEFAULT '',
 `LEAD_ID` varchar(30) NULL DEFAULT '',
 `CSV_ENTRY_DATE` date NOT NULL DEFAULT '0000-00-00',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`CSV_ENTRY_DATE`)
)ENGINE=InnoDB;

CREATE TABLE `SALES_CSV_DATA_PUNE`(
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(10) NOT NULL,
 `PRIORITY` tinyint(2) DEFAULT 0,
 `ANALYTIC_SCORE` tinyint(3) DEFAULT 0,
 `OLD_PRIORITY` tinyint(2) DEFAULT 0,
 `DIAL_STATUS` tinyint(1) DEFAULT 0,
 `AGENT` varchar(60) NULL DEFAULT '',
 `VD_PERCENT` tinyint(3) DEFAULT 0,
 `LAST_LOGIN_DATE` date NULL DEFAULT '0000-00-00',
 `PHONE_NO1` varchar(12) NULL DEFAULT '',
 `PHONE_NO2` varchar(12) NULL DEFAULT '',
 `PHOTO` char(3) NULL DEFAULT '',
 `DOB` date NULL DEFAULT '0000-00-00',
 `MSTATUS` varchar(40) NULL DEFAULT '',
 `EVER_PAID` char(3)  NULL DEFAULT '',
 `GENDER` char(6) NULL DEFAULT '',
 `POSTEDBY` varchar(40) NULL DEFAULT '',
 `NEW_VARIABLE1` varchar(20) NULL DEFAULT '',
 `NEW_VARIABLE2` varchar(20) NULL DEFAULT '',
 `NEW_VARIABLE3` varchar(20) NULL DEFAULT '',
 `PHONE_NO3` varchar(12) NOT NULL DEFAULT '',
 `PHONE_NO4` varchar(12)  NULL DEFAULT '',
 `LEAD_ID` varchar(30) NULL DEFAULT '',
 `CSV_ENTRY_DATE` date NOT NULL DEFAULT '0000-00-00',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`CSV_ENTRY_DATE`)
)ENGINE=InnoDB;

CREATE TABLE `SALES_CSV_DATA_MUMBAI`(
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(10) NOT NULL,
 `PRIORITY` tinyint(2) DEFAULT 0,
 `ANALYTIC_SCORE` tinyint(3) DEFAULT 0,
 `OLD_PRIORITY` tinyint(2) DEFAULT 0,
 `DIAL_STATUS` tinyint(1) DEFAULT 0,
 `AGENT` varchar(60) NULL DEFAULT '',
 `VD_PERCENT` tinyint(3) DEFAULT 0,
 `LAST_LOGIN_DATE` date NULL DEFAULT '0000-00-00',
 `PHONE_NO1` varchar(12) NULL DEFAULT '',
 `PHONE_NO2` varchar(12) NULL DEFAULT '',
 `PHOTO` char(3) NULL DEFAULT '',
 `DOB` date NULL DEFAULT '0000-00-00',
 `MSTATUS` varchar(40) NULL DEFAULT '',
 `EVER_PAID` char(3)  NULL DEFAULT '',
 `GENDER` char(6) NULL DEFAULT '',
 `POSTEDBY` varchar(40) NULL DEFAULT '',
 `NEW_VARIABLE1` varchar(20) NULL DEFAULT '',
 `NEW_VARIABLE2` varchar(20) NULL DEFAULT '',
 `NEW_VARIABLE3` varchar(20) NULL DEFAULT '',
 `PHONE_NO3` varchar(12) NOT NULL DEFAULT '',
 `PHONE_NO4` varchar(12)  NULL DEFAULT '',
 `LEAD_ID` varchar(30) NULL DEFAULT '',
 `CSV_ENTRY_DATE` date NOT NULL DEFAULT '0000-00-00',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`CSV_ENTRY_DATE`)
)ENGINE=InnoDB;


CREATE TABLE `SALES_CSV_DATA_NRI`(
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(10) NOT NULL,
 `PRIORITY` tinyint(2) DEFAULT 0,
 `ANALYTIC_SCORE` tinyint(3) DEFAULT 0,
 `OLD_PRIORITY` tinyint(2) DEFAULT 0,
 `DIAL_STATUS` tinyint(1) DEFAULT 0,
 `AGENT` varchar(60) NULL DEFAULT '',
 `VD_PERCENT` tinyint(3) DEFAULT 0,
 `LAST_LOGIN_DATE` date NULL DEFAULT '0000-00-00',
 `PHONE_NO1` varchar(12) NULL DEFAULT '',
 `PHONE_NO2` varchar(12) NULL DEFAULT '',
 `PHOTO` char(3) NULL DEFAULT '',
 `DOB` date NULL DEFAULT '0000-00-00',
 `MSTATUS` varchar(40) NULL DEFAULT '',
 `EVER_PAID` char(3)  NULL DEFAULT '',
 `GENDER` char(6) NULL DEFAULT '',
 `POSTEDBY` varchar(40) NULL DEFAULT '',
 `NEW_VARIABLE1` varchar(20) NULL DEFAULT '',
 `NEW_VARIABLE2` varchar(20) NULL DEFAULT '',
 `NEW_VARIABLE3` varchar(20) NULL DEFAULT '',
 `PHONE_NO3` varchar(12) NOT NULL DEFAULT '',
 `PHONE_NO4` varchar(12)  NULL DEFAULT '',
 `LEAD_ID` varchar(30) NULL DEFAULT '',
 `CSV_ENTRY_DATE` date NOT NULL DEFAULT '0000-00-00',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `PROFILEID` (`PROFILEID`,`CSV_ENTRY_DATE`)
)ENGINE=InnoDB;

