-- Table structure for table `RENEWAL_AGENT` in jsadmin DATABASE
-- 


CREATE TABLE jsadmin.`UPSELL_AGENT` (
  `USER` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`USER`)
) ENGINE=MyISAM;


CREATE TABLE jsadmin.`UPSELL_AGENT_ALLOTED` (
 `USER` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '', PRIMARY KEY (`USER`)) ENGINE=MyISAM;
