use CONTACT_ENGINE; 	

INSERT INTO `TEMPLATE_NAME` ( `CONTACT_TYPE` , `PROFILE_STATE` , `TO_BE_STATUS` , `ENGINE_TYPE` , `PAGE` , `TEMPLATE_NAME` , `SENDER_RECEIVER` , `ACTION_TYPE` )
VALUES (
'I', 'F', 'I', 'EOI', 'MOBILE', 'profile_eoi_eni_post', '', 'POST'
);
