use newjs;

ALTER TABLE  `PICTURE_FOR_SCREEN_APP` ADD INDEX (  `PROFILEID` );

CREATE TABLE `PICTURE_FOR_SCREEN_APP_LEGACY` (
  `PROFILEID` int(11) unsigned NOT NULL,
  `LAST_LOGIN_DT` date NOT NULL,
  `STATUS` char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`PROFILEID`),
  KEY `STATUS` (`STATUS`)
) ENGINE=MyISAM;
