use bms2;
ALTER TABLE BANNER ADD BannerJsRegistrationStatus VARCHAR( 255 ) NOT NULL;
UPDATE ZONE SET ZoneCriterias=CONCAT(ZoneCriterias,',REGISTRATION_STATUS') WHERE ZoneCriterias LIKE  '%GENDER%';

ALTER TABLE CRITERIA_MAPPING ADD  REGISTRATION_STATUS ENUM(  'Y',  'N' ) NOT NULL ;
UPDATE CRITERIA_MAPPING SET  REGISTRATION_STATUS =  'N' WHERE  CriteriaId='1';
UPDATE CRITERIA_MAPPING SET  REGISTRATION_STATUS =  'N' WHERE  CriteriaId='2';
UPDATE CRITERIA_MAPPING SET  REGISTRATION_STATUS =  'Y' WHERE  CriteriaId='3';
UPDATE CRITERIA_MAPPING SET  REGISTRATION_STATUS =  'Y' WHERE  CriteriaId='4';

INSERT INTO `SUBSCRIPTION` ( `ID` , `LABEL` , `VALUE` , `SORTBY` , `VISIBLE` )
VALUES (
'', 'Paid Members Renewal Due In 1 Month', '7', '7', 'Y'
), (
'', 'Paid Members without Add-on', '8', '8', 'Y'
);

