use newjs;
ALTER TABLE  `SEARCH_FEMALE` CHANGE  `CITY_RES`  `CITY_RES` VARCHAR( 5 );
ALTER TABLE  `SEARCH_MALE` CHANGE  `CITY_RES`  `CITY_RES` VARCHAR( 5 );
ALTER TABLE  `SWAP` CHANGE  `CITY_RES`  `CITY_RES` VARCHAR( 5 );
