use newjs;

DELETE FROM newjs.PINCODE_MAPPING WHERE LOCALITY IN('South Mumbai','East Mumbai','North Mumbai','West Mumbai','East Central Mumbai','West Central Mumbai'); 

INSERT INTO `PINCODE_MAPPING` VALUES ('400001', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400002', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400003', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400004', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400005', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400006', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400007', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400008', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400009', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400010', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400011', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400012', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400013', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400014', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400015', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400016', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400017', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400018', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400019', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400020', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400021', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400023', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400024', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400025', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400026', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400027', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400028', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400029', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400030', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400031', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400032', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400033', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400034', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400035', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400036', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400037', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400038', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400039', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400040', 'South Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400041', 'South Mumbai');

INSERT INTO `PINCODE_MAPPING` VALUES ('400079', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400086', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400088', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400089', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400090', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400094', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400085', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400070', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400071', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400073', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400074', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400077', 'East Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400075', 'East Mumbai');

INSERT INTO `PINCODE_MAPPING` VALUES ('400092', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400066', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400101', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400067', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('401303', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('401208', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400068', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400097', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400064', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400051', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400052', 'North Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400065', 'North Mumbai');

INSERT INTO `PINCODE_MAPPING` VALUES ('400047', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400049', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400050', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400045', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400046', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400043', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400044', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400102', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400096', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400042', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400072', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400087', 'West Mumbai');
INSERT INTO `PINCODE_MAPPING` VALUES ('400076', 'West Mumbai');

use incentive;
INSERT INTO incentive.SUB_LOCATION(`LABEL`,`VALUE`,`PRIORITY`) VALUES('West Mumbai','MH0415','MH04');
DELETE FROM incentive.SUB_LOCATION WHERE VALUE IN('MH0411','MH0412');

use jsadmin;
DELETE FROM jsadmin.AGENT_ALLOTED WHERE CENTER IN('West Central Mumbai','East Central Mumbai') AND METHOD='FIELD_SALES';
INSERT INTO jsadmin.AGENT_ALLOTED(`USER`,`METHOD`,`CENTER`,`ALLOCATION_LIMIT`) VALUES('','FIELD_SALES','West Mumbai','10');


