use newjs;


ALTER TABLE `PROFILE_DEL_REASON` CHANGE `DEL_REASON` `DEL_REASON` ENUM( 'I found my match on Jeevansathi.com', 'I found my match elsewhere', 'I am unhappy with Jeevansathi.com services', 'I found my match on another matrimonial site', 'Other reasons' ), add index(DEL_REASON);

ALTER TABLE `INDIVIDUAL_STORIES` CHANGE `SID` `SID` MEDIUMINT( 6 ) UNSIGNED DEFAULT NULL AUTO_INCREMENT ,
add `HOME_PIC_URL` varchar(200) NOT NULL,
add `MAIN_PIC_URL` varchar(200) NOT NULL,
add `FRAME_PIC_URL` varchar(200) NOT NULL,
CHANGE `STORYID` `STORYID` MEDIUMINT( 6 )UNSIGNED  DEFAULT NULL ,
CHANGE `NAME1` `NAME1` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci,
CHANGE `NAME2` `NAME2` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci,
CHANGE `YEAR` `YEAR` SMALLINT( 4 ) DEFAULT NULL ;

ALTER TABLE `SUCCESS_STORIES` CHANGE `ID` `ID` MEDIUMINT( 6 ) UNSIGNED DEFAULT NULL AUTO_INCREMENT ,
add `PIC_URL` varchar(200) NOT NULL,
CHANGE `NAME_H` `NAME_H` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ,
CHANGE `NAME_W` `NAME_W` VARCHAR( 100 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL ;

UPDATE newjs.INDIVIDUAL_STORIES set STORY = REPLACE(STORY, '–', '-') WHERE STORY LIKE '%–%';
UPDATE newjs.INDIVIDUAL_STORIES SET STATUS = 'A' WHERE STATUS = '' AND (YEAR = '2004' OR YEAR ='2005');

set session sql_log_bin=0;

ALTER TABLE SUCCESS_STORIES ENGINE = innodb;
ALTER TABLE INDIVIDUAL_STORIES ENGINE = innodb;
set session sql_log_bin=1;

USE MIS;
INSERT INTO `SOURCE`(SourceID, SourceName,GROUPNAME,ACTIVE,CPC,FORCE_EMAIL,NOREG,SourceGifType,PID) VALUES ('ss_reg', 'SS_REG', 'SS_REG', 'Y', 0, '', '', '', 0);
