use billing;

INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`, `MOST_POPULAR`, `FREEBIES`, `ENABLE`) VALUES ('', 'ESP4', 'e-Sathi Classified - 4 Months', '', 4, 0, 8995, 170, 'Y', '', 'PESP4', 'N', 0, 'N', 'Y', 'N', 'NULL', 'N');
INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`, `MOST_POPULAR`, `FREEBIES`, `ENABLE`) VALUES ('', 'ESP5', 'e-Sathi Classified - 5 Months', '', 5, 0, 9995, 190, 'Y', '', 'PESP5', 'N', 0, 'N', 'Y', 'N', 'NULL', 'N');
INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`, `MOST_POPULAR`, `FREEBIES`, `ENABLE`) VALUES ('', 'ESP8', 'e-Sathi Classified - 8 Months', '', 8, 0, 13995, 270, 'Y', '', 'PESP8', 'N', 0, 'N', 'Y', 'N', 'NULL', 'N');


INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`, `MOST_POPULAR`, `FREEBIES`, `ENABLE`) VALUES ('', 'D8', 'e-Classifieds -8 Months', '', 8, 0, 2145, 71, 'Y', '', 'PD8', 'N', 0, 'N', 'Y', 'N', 'NULL', 'N');
INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`, `MOST_POPULAR`, `FREEBIES`, `ENABLE`) VALUES ('', 'D9', 'e-Classifieds -9 Months', '', 9, 0, 2295, 77, 'Y', '', 'PD9', 'N', 0, 'N', 'Y', 'N', 'NULL', 'N');


UPDATE SERVICES SET PRICE_RS=ROUND(PRICE_RS_TAX/(1+(12.36/100)),2) WHERE SERVICEID IN('ESP4','ESP5','ESP8','D8','D9');
UPDATE SERVICES SET SORTBY=ID WHERE SERVICEID IN('ESP4','ESP5','ESP8','D8','D9');

INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP4', 'P4');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP4', 'A4');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP4', 'R4');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP4', 'T4');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP4', 'D4');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP4', 'I40');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP5', 'P5');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP5', 'A5');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP5', 'R5');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP5', 'T5');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP5', 'D5');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP5', 'I50');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP8', 'P8');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP8', 'A8');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP8', 'R8');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP8', 'T8');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP8', 'D8');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PESP8', 'I80');

INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PD8', 'D8');
INSERT INTO `PACK_COMPONENTS` VALUES ('', 'PD9', 'D9');




delete from DIRECT_CALL_COUNT where SERVICEID LIKE 'ESP%';
INSERT INTO `DIRECT_CALL_COUNT` VALUES ('ESP3', 60);
INSERT INTO `DIRECT_CALL_COUNT` VALUES ('ESP4', 75);
INSERT INTO `DIRECT_CALL_COUNT` VALUES ('ESP5', 100);
INSERT INTO `DIRECT_CALL_COUNT` VALUES ('ESP6', 125);
INSERT INTO `DIRECT_CALL_COUNT` VALUES ('ESP8', 155);
INSERT INTO `DIRECT_CALL_COUNT` VALUES ('ESPL', 250);

