use newjs;

DELETE FROM CASTE WHERE VALUE = 419;
DELETE FROM CASTE_GROUP_MAPPING WHERE ID = 70;
UPDATE CASTE_GROUP_MAPPING SET CASTE_VALUE = 296 WHERE CASTE_VALUE = 419;
DELETE FROM MAPPING_CASTE_CASTE_MTONGUE WHERE NEW_CASTE = 419;
