use billing;

update billing.SERVICES SET PRICE_RS='351.55',PRICE_RS_TAX='395',PRICE_DOL='12' WHERE SERVICEID='M9';
update billing.SERVICES SET PRICE_RS='351.55',PRICE_RS_TAX='395',PRICE_DOL='12' WHERE SERVICEID='M12';
update billing.SERVICES SET PRICE_RS='351.55',PRICE_RS_TAX='395',PRICE_DOL='12' WHERE SERVICEID='ML';

INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`, `MOST_POPULAR`, `FREEBIES`, `ENABLE`) VALUES ('', 'M7', 'Matri-Profile', '', 0, '351.55', 395, 12, 'N', 'M7', '', 'Y', 0, 'Y', 'Y', 'N', NULL, 'Y');
INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`, `MOST_POPULAR`, `FREEBIES`, `ENABLE`) VALUES ('', 'M8', 'Matri-Profile', '', 0, '351.55', 395, 12, 'N', 'M8', '', 'Y', 0, 'Y', 'Y', 'N', NULL, 'Y');
INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`, `MOST_POPULAR`, `FREEBIES`, `ENABLE`) VALUES ('', 'M10', 'Matri-Profile', '', 0, '351.55', 395, 12, 'N', 'M10', '', 'Y', 0, 'Y', 'Y', 'N', NULL, 'Y');
INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`, `MOST_POPULAR`, `FREEBIES`, `ENABLE`) VALUES ('', 'M11', 'Matri-Profile', '', 0, '351.55', 395, 12, 'N', 'M11', '', 'Y', 0, 'Y', 'Y', 'N', NULL, 'Y');

UPDATE SERVICES SET SORTBY=ID WHERE SERVICEID IN('M7','M8','M10','M11');

update billing.COMPONENTS SET DURATION='1' WHERE COMPID LIKE 'M%';

INSERT INTO `COMPONENTS` (`ID`, `COMPID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_DOL`, `RIGHTS`, `TYPE`, `ACC_COUNT`) VALUES ('', 'M7', 'Matri Profile - 7 month', '', '1', 0, 0, 'M', 'D', 0);
INSERT INTO `COMPONENTS` (`ID`, `COMPID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_DOL`, `RIGHTS`, `TYPE`, `ACC_COUNT`) VALUES ('', 'M8', 'Matri Profile - 8 month', '', '1', 0, 0, 'M', 'D', 0);
INSERT INTO `COMPONENTS` (`ID`, `COMPID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_DOL`, `RIGHTS`, `TYPE`, `ACC_COUNT`) VALUES ('', 'M10', 'Matri Profile - 10 month', '', '1', 0, 0, 'M', 'D', 0);
INSERT INTO `COMPONENTS` (`ID`, `COMPID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_DOL`, `RIGHTS`, `TYPE`, `ACC_COUNT`) VALUES ('', 'M11', 'Matri Profile - 11 month', '', '1', 0, 0, 'M', 'D', 0);



