use incentive;

CREATE TABLE `FTA_MESSAGE_LOG_LAST_ID` (
 `LAST_ID` int(11) DEFAULT '0',
 `SHARD` tinyint(3) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO  `FTA_MESSAGE_LOG_LAST_ID` (  `LAST_ID` ,  `SHARD` ) VALUES ('0',  '0');
INSERT INTO  `FTA_MESSAGE_LOG_LAST_ID` (  `LAST_ID` ,  `SHARD` ) VALUES ('0',  '1');
INSERT INTO  `FTA_MESSAGE_LOG_LAST_ID` (  `LAST_ID` ,  `SHARD` ) VALUES ('0',  '2');
