use incentive;

INSERT INTO `CRM_DISPOSITION` (`DISPOSOTION_VALUE`, `DISPOSOTION_LABEL`, `ACTIVE`) VALUES ('FVD', 'Field Visit Done', 'Y');
INSERT INTO `CRM_DISPOSITION_VALIDATION` (`DISPOSITION`, `VALIDATION_VALUE`, `VALIDATION_LABEL`) VALUES ('FVD', 'FVD1', 'Payment and Verification Done');
INSERT INTO `CRM_DISPOSITION_VALIDATION` (`DISPOSITION`, `VALIDATION_VALUE`, `VALIDATION_LABEL`) VALUES ('FVD', 'FVD2', 'Payment Done but Verification Incomplete');
INSERT INTO `CRM_DISPOSITION_VALIDATION` (`DISPOSITION`, `VALIDATION_VALUE`, `VALIDATION_LABEL`) VALUES ('FVD', 'FVD3', 'Payment Not Done but Verification Done');
INSERT INTO `CRM_DISPOSITION_VALIDATION` (`DISPOSITION`, `VALIDATION_VALUE`, `VALIDATION_LABEL`) VALUES ('FVD', 'FVD4', 'Payment Not Done and Verification Incomplete');
