use MOBILE_API;


CREATE TABLE  `APP_LOGIN_PROFILES` (
 `PROFILEID` INT( 11 ) NOT NULL ,
PRIMARY KEY (  `PROFILEID` )
) COMMENT =  'profileId''s having app installed or they have atelast once login through app';


INSERT INTO MOBILE_API.APP_LOGIN_PROFILES (PROFILEID) SELECT DISTINCT (
PROFILEID
)
FROM  MIS.LOGIN_TRACKING
WHERE  `WEBSITE_VERSION` LIKE CONVERT( _utf8 'A'
USING latin1 ) 
