use incentive;
INSERT INTO `FIELD_SALES_CITY` (`VALUE`, `NAME`) VALUES ('UP19', 'LUCKNOW');
INSERT INTO `FIELD_SALES_CITY` (`VALUE`, `NAME`) VALUES ('UP18', 'KANPUR');
INSERT INTO `FIELD_SALES_CITY` (`VALUE`, `NAME`) VALUES ('UP13', 'GORAKHPUR');
INSERT INTO `FIELD_SALES_CITY` (`VALUE`, `NAME`) VALUES ('UP30', 'VARANASI');
INSERT INTO `FIELD_SALES_CITY` (`VALUE`, `NAME`) VALUES ('UP03', 'ALLAHABAD');

use jsadmin;
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'Lucknow','100');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'Kanpur','100');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'Gorakhpur','100');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'Varanasi','100');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'Allahabad','100');

