use newjs;

CREATE TABLE `ASTRO_PULLING_REQUEST_ONETIME_ERROR` (
  `PROFILEID` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `PENDING` char(2) NOT NULL DEFAULT '',
  `TYPE` char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (`PROFILEID`),
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


INSERT INTO newjs.ASTRO_PULLING_REQUEST_ONETIME_ERROR(PROFILEID,PENDING,TYPE) SELECT PROFILEID,'Y','E' FROM newjs.JPROFILE WHERE ENTRY_DT > "2012-02-15 00:00:00"; 
