use MIS;
CREATE TABLE  `LOGIN_BY_USERNAME` (
 `PID` INT( 11 ) NOT NULL ,
 `DATE` DATETIME NOT NULL ,
 `IP` VARCHAR( 16 ) NOT NULL ,
KEY `PID` (`PID`),
KEY `DATE` (`DATE`)
) COMMENT =  'Track users login by USERNAME';
