UPDATE  `SERVICES` SET  `PRICE_DOL` =  '195' WHERE  `SERVICEID` =  'ES3' LIMIT 1 ;

UPDATE  `SERVICES` SET  `PRICE_DOL` =  '295' WHERE  `SERVICEID` =  'ES6' LIMIT 1 ;

UPDATE  `SERVICES` SET  `PRICE_DOL` =  '395' WHERE  `SERVICEID` =  'ESL' LIMIT 1 ;

UPDATE  `SERVICES` SET  `PRICE_DOL` =  '195' WHERE  `SERVICEID` =  'ESP3' LIMIT 1 ;

UPDATE  `SERVICES` SET  `PRICE_DOL` =  '295' WHERE  `SERVICEID` =  'ESP6' LIMIT 1 ;

UPDATE  `SERVICES` SET  `PRICE_DOL` =  '395' WHERE  `SERVICEID` =  'ESPL' LIMIT 1 ;
