use newjs;

ALTER TABLE  `JPROFILE_ALERTS` ADD  `NEW_MATCHES_MAILS` CHAR( 1 ) DEFAULT NULL AFTER  `PHOTO_REQUEST_MAILS`;

ALTER TABLE  `SEARCHQUERY` ADD  `MANGLIK_IGNORE` VARCHAR( 10 ) ,ADD  `MSTATUS_IGNORE` VARCHAR( 20 ) ,ADD  `HIV_IGNORE` VARCHAR( 10 ) ,ADD  `HANDICAPPED_IGNORE` VARCHAR( 20 );

use MIS;

CREATE TABLE `NEW_MATCHES_EMAILS_TRACKING` (
  `DATE` date NOT NULL,
  `PROFILES_CONSIDERED` int(11) NOT NULL,
  `PROFILES_MAIL_SENT` int(11) NOT NULL,
  `MAIL_OPEN` int(11) NOT NULL,
  `UNSUBSCRIPTION` int(11) NOT NULL,
  `1_MATCH` int(11) NOT NULL,
  `2_MATCH` int(11) NOT NULL,
  `3_MATCH` int(11) NOT NULL,
  `4_MATCH` int(11) NOT NULL,
  `5_MATCH` int(11) NOT NULL,
  `6_MATCH` int(11) NOT NULL,
  `7_MATCH` int(11) NOT NULL,
  `8_MATCH` int(11) NOT NULL,
  `9_MATCH` int(11) NOT NULL,
  `10_MATCH` int(11) NOT NULL,
  PRIMARY KEY (`DATE`)
) ENGINE=MyISAM;

ALTER TABLE  `SEARCHQUERY` RENAME  `SEARCHQUERY_BEFORE_NEW_MATCHES_MAILER` ;

CREATE TABLE SEARCHQUERY LIKE newjs.SEARCHQUERY;
