use MIS;
CREATE TABLE `VIEW_ALBUM_LOG` (`PROFILEID` int(11) NOT NULL DEFAULT '0',`VIEWER_PROFILEID` int(11) NOT NULL DEFAULT '0', `DATE` date NOT NULL DEFAULT '0000-00-00', `SOURCE` char(1) NOT NULL DEFAULT 'S',`PHOTO_COUNT` tinyint(1) DEFAULT '0', PRIMARY KEY (`PROFILEID`,`VIEWER_PROFILEID`,`DATE`,`SOURCE`)) ENGINE=MYISAM;
