use incentive;
CREATE TABLE `SALES_CSV_PROFILE_LOG` (
 `PROFILEID` int(11) unsigned NOT NULL DEFAULT '0',
 `USERNAME` varchar(40) NOT NULL DEFAULT '',
 `CSV_SENT` enum('Y','N') DEFAULT NULL,
 `CAMPAIGN_NAME` char(10) DEFAULT NULL,
 `DIAL_STATUS` tinyint(1) DEFAULT NULL,
 `FILTER_NAME` varchar(40) DEFAULT NULL,
 `FILTER_VALUE` varchar(40) DEFAULT NULL,
 `ENTRY_DT` date NOT NULL DEFAULT '0000-00-00',
 KEY `ENTRY_DT` (`ENTRY_DT`),
 KEY `PROFILEID` (`PROFILEID`)
) ENGINE=InnoDB;

drop table `SALES_CSV_DATA_TEMP`;
CREATE TABLE `SALES_CSV_DATA_TEMP` (
 `PROFILEID` int(11) NOT NULL DEFAULT '0',
 `USERNAME` varchar(40) DEFAULT NULL,
 `ENTRY_DT` date NOT NULL DEFAULT '0000-00-00',
 PRIMARY KEY (`PROFILEID`)
) 
