use billing;
ALTER TABLE SERVICES ADD COLUMN ENABLE enum('Y','N');
ALTER TABLE SERVICES ADD COLUMN MOST_POPULAR enum('Y','N');
ALTER TABLE SERVICES ADD COLUMN FREEBIES varchar(20);

UPDATE `SERVICES` set ENABLE='Y' WHERE 1;
