use billing;

ALTER TABLE billing.REV_PAYMENT ADD SERVICE_TAX double;

UPDATE billing.REV_PAYMENT RP INNER JOIN billing.REV_MASTER RM ON RP.SALEID = RM.SALEID SET RP.SERVICE_TAX = RM.SERVICE_TAX;

UPDATE billing.REV_MASTER SET SERVICE_TAX = ROUND(DUEAMOUNT*(12.36/100),2), DUEAMOUNT=DUEAMOUNT+SERVICE_TAX, TOTAL_AMT=TOTAL_AMT+SERVICE_TAX WHERE DUEAMOUNT != 0 AND SERVICE_TAX = 0;

UPDATE billing.REV_PAYMENT SET SERVICE_TAX = ROUND((AMOUNT+TDS)/(1.1236),2) WHERE SERVICE_TAX!=0;
