use MIS;
CREATE TABLE `AUTOLOGIN_TRACKING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXECUTIVE_NAME` varchar(20) NOT NULL,
  `PROFILEID` int(11) NOT NULL,
  `IP` varchar(15) NOT NULL,
  `TIME` datetime NOT NULL,
  PRIMARY KEY (`ID`)
);
