/**
* 1. We have to make changes on SOLR - add verification seal & Remove vishwas seal
* 2. The cron swap_jprofile might stop, but that will not cause any issue.
*/
use newjs;

ALTER TABLE `SWAP` ADD `VERIFICATION_SEAL` varchar(20) DEFAULT '0';

ALTER TABLE `SEARCH_FEMALE` ADD `VERIFICATION_SEAL` varchar(20) DEFAULT '0';

ALTER TABLE `SEARCH_MALE` ADD `VERIFICATION_SEAL` varchar(20) DEFAULT '0';




CREATE DATABASE `PROFILE_VERIFICATION` ;
CREATE TABLE `PROFILE_VERIFICATION`.`DOCUMENTS` (
`DOCUMENT_ID` int( 11 ) unsigned NOT NULL DEFAULT '0',
`PROFILEID` int( 11 ) unsigned DEFAULT NULL ,
`ATTRIBUTE` enum( 'DOB', 'ADDRESS', 'PARENT_ADDRESS', 'HIGHEST_QUALIFICATION', 'INCOME', 'DIVORCE' ) DEFAULT NULL ,
`UPLOADED_DATE` datetime DEFAULT NULL ,
`DOCUMENT_TYPE` enum( 'PAN_CARD', 'DL', 'PASSPORT', 'CLASSX_PASSING_CERT', 'OTHER', 'VOTER_ID', 'RATION_CARD', 'PROPERTY_TAX_RECEIPT', 'RENT_AGREEMENT', 'MARKSHEET', 'DEGREE_CERT', 'TRANSCRIPT', 'SALARY_SLIP', 'OFFER_LTR', 'JOINING_LTR', 'INCREMENT_LTR', 'FORM16', 'ITR', 'COURT_ORDER' ) DEFAULT NULL ,
`DOC_FORMAT` enum( 'jpg', 'jpeg', 'gif' ) DEFAULT NULL ,
`VERIFIED_FLAG` enum( 'Y', 'N', 'U' ) NOT NULL DEFAULT 'U',
`DELETED_FLAG` enum( 'Y', 'N' ) DEFAULT 'N',
`DOCURL` varchar( 200 ) DEFAULT NULL ,
`UPLOADED_BY` varchar( 20 ) DEFAULT NULL ,
`VERIFICATION_VALUE` text,
PRIMARY KEY ( `DOCUMENT_ID` ) ,
KEY `PROFILEID` ( `PROFILEID` ) ,
KEY `VERIFIED_FLAG` ( `VERIFIED_FLAG` )
) ENGINE = MyISAM DEFAULT CHARSET = latin1;

INSERT INTO `PROFILE_VERIFICATION`.`DOCUMENTS`
SELECT *
FROM `jsadmin`.`PROFILE_VERIFICATION_DOCUMENTS` ;










CREATE TABLE `PROFILE_VERIFICATION`.`DOCUMENTS_SCREENING` (
`PROFILEID` int( 11 ) NOT NULL DEFAULT '0',
`ALLOTED_TIME` datetime DEFAULT '0000-00-00 00:00:00',
`ASSIGNED_TO` varchar( 40 ) DEFAULT NULL ,
PRIMARY KEY ( `PROFILEID` )
) ENGINE = MYISAM DEFAULT CHARSET = latin1;

INSERT INTO `PROFILE_VERIFICATION`.`DOCUMENTS_SCREENING`
SELECT *
FROM `jsadmin`.`PROFILE_VERIFICATION_DOCUMENTS_SCREENING` ;







CREATE TABLE `PROFILE_VERIFICATION`.`DOCUMENTS_SCREENING_TRACKING` (
`DOCUMENT_ID` int( 11 ) NOT NULL DEFAULT '0',
`SCREENED_BY` varchar( 20 ) DEFAULT NULL ,
`SCREENING_TIME` datetime NOT NULL ,
PRIMARY KEY ( `DOCUMENT_ID` )
) ENGINE = MYISAM DEFAULT CHARSET = latin1;

INSERT INTO `PROFILE_VERIFICATION`.`DOCUMENTS_SCREENING_TRACKING`
SELECT *
FROM `jsadmin`.`PROFILE_VERIFICATION_DOCUMENTS_SCREENING_TRACKING` ;









CREATE TABLE `PROFILE_VERIFICATION`.`DOC_AUTOINCREMENT` (
`AUTO_ID` int( 11 ) unsigned NOT NULL AUTO_INCREMENT ,
`NO_USE_VARIABLE` char( 1 ) NOT NULL DEFAULT 'N',
PRIMARY KEY ( `AUTO_ID` ) ,
UNIQUE KEY `NO_USE_VARIABLE` ( `NO_USE_VARIABLE` )
) ENGINE = MYISAM DEFAULT CHARSET = latin1;

INSERT INTO `PROFILE_VERIFICATION`.`DOC_AUTOINCREMENT`
SELECT *
FROM `jsadmin`.`PROFILE_VERIFICATION_DOC_AUTOINCREMENT` ;











-- 
-- Table structure for table `PROFILE_VERIFICATION_FSO`
-- 

CREATE TABLE `PROFILE_VERIFICATION`.`FSO` (
  `PROFILEID` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`PROFILEID`),
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM;

-- 
-- Table structure for table `PROFILE_VERIFICATION_FSO_DELETION`
-- 

CREATE TABLE `PROFILE_VERIFICATION`.`FSO_DELETION` (
  `PROFILEID` int(11) NOT NULL DEFAULT '0',
  `DELETE_REASON` int(4) DEFAULT NULL,
  `DELETE_REASON_DETAIL` varchar(40) NOT NULL,
  `DELETED_BY` varchar(20) DEFAULT NULL,
  `DELETION_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PROFILEID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;




ALTER TABLE `newjs`.`SWAP` DROP `VISHWAS_SEAL`
ALTER TABLE `newjs`.`SEARCH_MALE` DROP `VISHWAS_SEAL` 
ALTER TABLE `newjs`.`SEARCH_FEMALE` DROP `VISHWAS_SEAL`


INSERT INTO `PROFILE_VERIFICATION`.`FSO` SELECT PROFILEID FROM `incentive`.`MAIN_ADMIN` WHERE WILL_PAY = "FVD" ;
INSERT INTO `newjs`.`SWAP_JPROFILE` SELECT PROFILEID FROM `PROFILE_VERIFICATION`.`FSO` ;


/* DROPPING WILL BE PERFORMED After proper verification check
DROP TABLE `jsadmin`.`PROFILE_VERIFICATION_DOCUMENTS_SCREENING_TRACKING`;
DROP TABLE `jsadmin`.`PROFILE_VERIFICATION_DOCUMENTS_SCREENING` ;
DROP TABLE `jsadmin`.`PROFILE_VERIFICATION_DOCUMENTS` ;
DROP TABLE `jsadmin`.`PROFILE_VERIFICATION_DOC_AUTOINCREMENT` ;
*/

set session sql_log_bin=0;
alter table  `PROFILE_VERIFICATION`.`DOCUMENTS` engine=innodb;
set session sql_log_bin=1;
