--comment the revamp layer part in mainmenu.php before making live and then execute the onetime cron.

use newjs;

DROP TABLE IF EXISTS OCCUPATION;

CREATE TABLE `OCCUPATION` (
  `ID` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `LABEL` varchar(100) NOT NULL DEFAULT '',
  `VALUE` tinyint(3) NOT NULL DEFAULT '0',
  `SORTBY` tinyint(3) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `VALUE` (`VALUE`)
) ENGINE=MyISAM AUTO_INCREMENT=64 DEFAULT CHARSET=latin1 AUTO_INCREMENT=64 ;

-- 
-- Dumping data for table `OCCUPATION`
-- 

INSERT INTO `OCCUPATION` VALUES (45, 'Looking for a job', 44, 1);
INSERT INTO `OCCUPATION` VALUES (36, 'Not working', 36, 2);
INSERT INTO `OCCUPATION` VALUES (5, 'Actor/Model', 5, 3);
INSERT INTO `OCCUPATION` VALUES (2, 'Advertising Professional', 2, 4);
INSERT INTO `OCCUPATION` VALUES (3, 'Agent', 3, 5);
INSERT INTO `OCCUPATION` VALUES (32, 'Agriculture/Dairy', 32, 6);
INSERT INTO `OCCUPATION` VALUES (47, 'Air Hostess', 46, 7);
INSERT INTO `OCCUPATION` VALUES (6, 'Architect', 6, 8);
INSERT INTO `OCCUPATION` VALUES (7, 'Banking Professional', 7, 9);
INSERT INTO `OCCUPATION` VALUES (40, 'Beautician', 40, 10);
INSERT INTO `OCCUPATION` VALUES (8, 'BPO/ITES', 8, 11);
INSERT INTO `OCCUPATION` VALUES (13, 'Businessperson', 13, 12);
INSERT INTO `OCCUPATION` VALUES (33, 'Civil Services (IAS/ IFS/ IPS/ IRS)', 33, 13);
INSERT INTO `OCCUPATION` VALUES (51, 'Consultant', 50, 14);
INSERT INTO `OCCUPATION` VALUES (10, 'Corporate Communication', 10, 15);
INSERT INTO `OCCUPATION` VALUES (11, 'Corporate Planning Professional', 11, 16);
INSERT INTO `OCCUPATION` VALUES (12, 'Customer Services', 12, 17);
INSERT INTO `OCCUPATION` VALUES (34, 'Defence', 34, 18);
INSERT INTO `OCCUPATION` VALUES (58, 'Doctor', 57, 19);
INSERT INTO `OCCUPATION` VALUES (61, 'Education Professional', 60, 20);
INSERT INTO `OCCUPATION` VALUES (27, 'Engineer - Non IT', 27, 21);
INSERT INTO `OCCUPATION` VALUES (14, 'Export/Import', 14, 22);
INSERT INTO `OCCUPATION` VALUES (15, 'Fashion Designer', 15, 23);
INSERT INTO `OCCUPATION` VALUES (1, 'Financial Services/Accounting', 1, 24);
INSERT INTO `OCCUPATION` VALUES (39, 'Fitness Professional', 39, 25);
INSERT INTO `OCCUPATION` VALUES (35, 'Govt. Services', 35, 26);
INSERT INTO `OCCUPATION` VALUES (21, 'Hardware/Telecom', 21, 27);
INSERT INTO `OCCUPATION` VALUES (24, 'Healthcare Professional', 24, 28);
INSERT INTO `OCCUPATION` VALUES (48, 'Hotels/Hospitality Professional', 47, 29);
INSERT INTO `OCCUPATION` VALUES (19, 'HR Professional', 19, 30);
INSERT INTO `OCCUPATION` VALUES (52, 'Interior Designer', 51, 31);
INSERT INTO `OCCUPATION` VALUES (9, 'Journalist', 9, 32);
INSERT INTO `OCCUPATION` VALUES (22, 'Lawyer/Legal Professional', 22, 33);
INSERT INTO `OCCUPATION` VALUES (23, 'Logistics/SCM Professional', 23, 34);
INSERT INTO `OCCUPATION` VALUES (50, 'Marketing Professional', 49, 35);
INSERT INTO `OCCUPATION` VALUES (55, 'Media Professional', 54, 36);
INSERT INTO `OCCUPATION` VALUES (42, 'Merchant Navy', 42, 37);
INSERT INTO `OCCUPATION` VALUES (38, 'NGO/Social Services', 38, 38);
INSERT INTO `OCCUPATION` VALUES (54, 'Nurse', 53, 39);
INSERT INTO `OCCUPATION` VALUES (46, 'Pilot', 45, 40);
INSERT INTO `OCCUPATION` VALUES (57, 'Police', 56, 41);
INSERT INTO `OCCUPATION` VALUES (25, 'Printing/Packaging', 25, 42);
INSERT INTO `OCCUPATION` VALUES (59, 'Professor/Lecturer', 58, 43);
INSERT INTO `OCCUPATION` VALUES (30, 'Project Manager - IT', 30, 44);
INSERT INTO `OCCUPATION` VALUES (60, 'Project Manager - Non IT', 59, 45);
INSERT INTO `OCCUPATION` VALUES (62, 'Research Professional', 61, 46);
INSERT INTO `OCCUPATION` VALUES (18, 'Restaurateur', 18, 47);
INSERT INTO `OCCUPATION` VALUES (37, 'Retired', 37, 48);
INSERT INTO `OCCUPATION` VALUES (28, 'Sales Professional', 28, 49);
INSERT INTO `OCCUPATION` VALUES (63, 'Scientist', 62, 50);
INSERT INTO `OCCUPATION` VALUES (16, 'Secretary/Front Office', 16, 51);
INSERT INTO `OCCUPATION` VALUES (29, 'Security Professional', 29, 52);
INSERT INTO `OCCUPATION` VALUES (53, 'Self Employed', 52, 53);
INSERT INTO `OCCUPATION` VALUES (26, 'Service Engineering', 26, 54);
INSERT INTO `OCCUPATION` VALUES (20, 'Software Professional', 20, 55);
INSERT INTO `OCCUPATION` VALUES (56, 'Sportsperson', 55, 56);
INSERT INTO `OCCUPATION` VALUES (41, 'Student', 41, 57);
INSERT INTO `OCCUPATION` VALUES (31, 'Teacher', 31, 58);
INSERT INTO `OCCUPATION` VALUES (49, 'Top Management (CXO, M.D. etc.)', 48, 59);
INSERT INTO `OCCUPATION` VALUES (4, 'Travel/Ticketing', 4, 60);
INSERT INTO `OCCUPATION` VALUES (17, 'Web/Graphic Design', 17, 61);
INSERT INTO `OCCUPATION` VALUES (43, 'Others', 43, 62);

ALTER TABLE `OCCUPATION_CLUSTER` RENAME `OCCUPATION_CLUSTER_NOUSE` ;

use MIS;

CREATE TABLE CASTE_UPDATE_PROFILEID_DUMP LIKE CASTE_UPDATE_PROFILEID;

INSERT INTO CASTE_UPDATE_PROFILEID_DUMP SELECT * FROM CASTE_UPDATE_PROFILEID WHERE CASTE_REVAMP_FLAG = 0;

ALTER TABLE `CASTE_UPDATE_PROFILEID` ADD `OLD_PROFESSION` SMALLINT( 5 ) NOT NULL ,
ADD `REVAMP_VALUE` VARCHAR( 20 ) NOT NULL ;

DELETE FROM `CASTE_UPDATE_PROFILEID` WHERE CASTE_REVAMP_FLAG =0;

UPDATE CASTE_UPDATE_PROFILEID SET REVAMP_VALUE = CASTE_REVAMP_FLAG;

UPDATE `CASTE_UPDATE_PROFILEID` SET CASTE_REVAMP_FLAG =2;

ALTER TABLE `CASTE_UPDATE_PROFILEID` RENAME `REVAMP_LAYER_CHECK`;

use bms2;

DROP TABLE IF EXISTS OCCUPATION;

CREATE TABLE bms2.OCCUPATION LIKE newjs.OCCUPATION;

INSERT INTO bms2.OCCUPATION SELECT * FROM newjs.OCCUPATION;

use jsmailer;

DROP TABLE IF EXISTS OCCUPATION;

CREATE TABLE jsmailer.OCCUPATION LIKE newjs.OCCUPATION;

INSERT INTO jsmailer.OCCUPATION SELECT * FROM newjs.OCCUPATION;
