use incentive;

INSERT INTO incentive.LOCATION(`VALUE`,`NAME`,`STATE`,`REGION`,`SPECIAL_CITY`) VALUES('UP47','GREATER NOIDA','UP','N','');

INSERT INTO incentive.SUB_LOCATION (`LABEL`,`VALUE`,`PRIORITY`) VALUES('GREATER NOIDA','UP47','UP47');

INSERT INTO jsadmin.AGENT_ALLOTED (`USER`,`METHOD`,`CENTER`,`ALLOCATION_LIMIT`) VALUES('','FIELD_SALES','GREATER NOIDA','100');

