use incentive;

CREATE TABLE `EMAIL_DATA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) NOT NULL DEFAULT '',
  `MESSAGE` text NOT NULL,
  `FLAG` char(1) NOT NULL DEFAULT '',
  `DISPLAY` char(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=67 DEFAULT CHARSET=latin1 AUTO_INCREMENT=67 ;

-- 
-- Dumping data for table `EMAIL_DATA`
-- 

INSERT INTO `EMAIL_DATA` VALUES (1, 'We tried reaching you!', 'I tried reaching you today. Hope you are finding jeevansathi.com useful in your search.', 'H', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (2, 'It was nice talking to you!', 'It was good talking to you today. Hope it was useful for you and jeevansathi.com is helping you in your search.', 'H', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (4, 'Upload Photograph', 'I hope you understand the importance of photographs in matrimonial alliances. We have observed that users who upload several photographs get up to 8 times more response than the ones who don’t. Hence, I strongly recommend you to upload as many photographs as you can to make your profile more interesting for other users. Please <a href="http://www.jeevansathi.com/social/addPhotos?checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">click here</a> to upload photos now.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (8, 'Add family background', 'Family backgrounds and values are core decision making parameters for prospects. Add more details about your family to help others better understand your background. Please <a href="http://www.jeevansathi.com/profile/viewprofile.php?EditWhatNew=FamilyDetails&ownview=1&checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">click here</a> to edit.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (20, 'Footer', 'Do let me know if you need any help and I will be happy to assist.', 'F', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (6, 'Login frequently & respond to incoming interests', 'I will like to recommend that you should login more frequently. Quick response on the interests or acceptances that you have received helps taking this forward. In addition, the more often you login, the more you get pushed up in the search results of other members. So, logging in regularly helps. To login now, <a href="http://www.jeevansathi.com/profile/mainmenu.php?checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">click here</a>.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (14, 'Failed Payment Tries', 'I observed that you had tried to subscribe to our membership plans but the transaction did not go through. Please let me know if there is something that is troubling or try payment again by <a href="http://www.jeevansathi.com/profile/mem_comparison.php?from_source=crm_mailer&checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">clicking here</a>', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (7, 'Add hobbies and interests', 'I have noticed that you have not filled in all your hobbies and interests. Partners looking for you are interesting to know about you before they send you interests. It will be great if you can add more information here. To add now, please <a href="http://www.jeevansathi.com/profile/viewprofile.php?EditWhatNew=Interests&ownview=1&checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">click here</a>.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (3, 'Edit DPP', 'I would like to emphasize once again that setting your desired partner preferences correctly is very important to get appropriate response. Please edit your preferences so that the match recommendations we send are according to what you are looking for. Please <a href="http://www.jeevansathi.com/profile/advance_search.php?FLAG=partner&checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">click here</a> to edit your preferences.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (5, 'Manage Filters', 'Managing filters appropriately is very important. This will ensure that you get the right people to reach out to you by interests or calls. Please edit filters that have been applied in your profiles by <a href ="http://www.jeevansathi.com/register/page6?checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">clicking here</a>.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (10, 'Use my matches and search', 'I recommend that you should search profiles that match your expectations and send interests to them. This will expedite the search. Use advanced search for any specific search criteria you may want to use. Mutual matches will give you profiles which you should like and they also are looking for someone like you.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (11, 'Explain membership', 'Turbo-charge your search by subscribing to one of our membership plans. They allow you to contact other members on the website the way you want, whenever you want. Some plans allow others to reach out to you as well. Different durations give you the flexibility to choose plans that best fit your needs. Please <a href="http://www.jeevansathi.com/profile/mem_comparison.php?from_source=crm_mailer&checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">click here</a> to know more about our plans.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (12, 'Explain renewal of membership - with renewal discount', 'Your current membership plan expires on <Date of Expiry>. Please renew your subscription to get uninterrupted service of the plan features and benefits. <a href="http://www.jeevansathi.com/profile/mem_comparison.php?from_source=crm_mailer&checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">Click here</a> to renew. We appreciate your association with us and will offer you a 15% price reduction on all our plans. This offer will be available till <Subscription expiry/discount expiry>.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (13, 'Explain renewal of membership - without renewal discount', 'Your  membership plan expired on <Date of Expiry>. Please renew your subscription to avail plan features and benefits. <a href="http://www.jeevansathi.com/profile/mem_comparison.php?from_source=crm_mailer&checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">Click here</a> to renew.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (19, 'Jeevansathi Branch Details', 'We have our offices across India and you can visit any of them to understand about our website better. The nearest center for you will be ', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (15, 'Festive Offer', 'I wished to inform you that Jeevansathi is offering discounts to users in this festive season. We are offering additional months of membership with some plans purchased during this membership or cash discounts on others. This is the best time to subscribe to one of our plans. <a href="http://www.jeevansathi.com/profile/mem_comparison.php?from_source=crm_mailer&checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">Click here</a> to know more. Offer valid till ', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (16, 'Other offers', 'I wished to inform you that Jeevansathi is offering a discount of up to <Max % Value> on membership plans. This is the best time to subscribe to one of our plans. <a href="http://www.jeevansathi.com/profile/mem_comparison.php?from_source=crm_mailer&checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">Click here</a> to know more. Offer valid till ', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (17, 'Download app', 'We have noticed that you are accessing Jeevansathi from out mobile site. Do download our android app for making your experience richer and more convenient. <a href="http://www.jeevansathi.com/common/appPromotionDesktop" target="_blank">Click here</a> to download the app.', 'B', 'Y');
INSERT INTO `EMAIL_DATA` VALUES (18, 'Reset Password', 'If you are having trouble logging in, please reset your password by <a href="http://www.jeevansathi.com/profile/revamp_change_password.php?checksum=<CHECKSUM>&echecksum=<ECHECKSUM>" target="_blank">clicking here</a>', 'B', 'Y');
 
