use MIS;

CREATE TABLE `SEM_GACODE` (
  `ID` int(10) NOT NULL auto_increment,
  `URL` varchar(100) default NULL,
  `GA_CODE` text,
  `ACTIVE` enum('Y','N') NOT NULL default 'Y',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=latin1 AUTO_INCREMENT=7 ;

-- 
-- Dumping data for table `SEM_GACODE`
-- 

INSERT INTO `SEM_GACODE` VALUES (1, 'jeevansathi.co.in', '<!-- GA Code for Jeevansathi.co.in -->\r\n\r\n<script type="text/javascript">\r\n\r\n  var _gaq = _gaq || [];\r\n  _gaq.push([''_setAccount'', ''UA-20941176-1'']);\r\n  _gaq.push([''_setDomainName'', ''.jeevansathi.co.in'']);\r\n  _gaq.push([''_trackPageview'']);\r\n	\r\n  (function() {\r\n    var ga = document.createElement(''script''); ga.type = ''text/javascript''; ga.async = true;\r\n    ga.src = (''https:'' == document.location.protocol ? ''https://ssl'' : ''http://www'') + ''.google-analytics.com/ga.js'';\r\n    var s = document.getElementsByTagName(''script'')[0]; s.parentNode.insertBefore(ga, s);\r\n  })();\r\n	\r\n</script> ', 'Y');
INSERT INTO `SEM_GACODE` VALUES (2, 'hindijeevansathi.in', '<!-- GA Code for hindijeevansathi.in -->\r\n\r\n<script type="text/javascript">\r\n  var _gaq = _gaq || [];\r\n  _gaq.push([''_setAccount'', ''UA-20942264-1'']);\r\n  _gaq.push([''_setDomainName'', ''.hindijeevansathi.in'']);\r\n  _gaq.push([''_trackPageview'']);\r\n	\r\n  (function() {\r\n    var ga = document.createElement(''script''); ga.type = ''text/javascript''; ga.async = true;\r\n    ga.src = (''https:'' == document.location.protocol ? ''https://ssl'' : ''http://www'') + ''.google-analytics.com/ga.js'';\r\n    var s = document.getElementsByTagName(''script'')[0]; s.parentNode.insertBefore(ga, s);\r\n  })();\r\n	\r\n</script> ', 'Y');
INSERT INTO `SEM_GACODE` VALUES (3, 'marathijeevansathi.in', '<!-- GA Code for marathijeevansathi.in -->\r\n\r\n<script type="text/javascript">\r\n\r\n  var _gaq = _gaq || [];\r\n  _gaq.push([''_setAccount'', ''UA-20941180-1'']);\r\n  _gaq.push([''_setDomainName'', ''.marathijeevansathi.in'']);\r\n  _gaq.push([''_trackPageview'']);\r\n	\r\n  (function() {\r\n    var ga = document.createElement(''script''); ga.type = ''text/javascript''; ga.async = true;\r\n    ga.src = (''https:'' == document.location.protocol ? ''https://ssl'' : ''http://www'') + ''.google-analytics.com/ga.js'';\r\n    var s = document.getElementsByTagName(''script'')[0]; s.parentNode.insertBefore(ga, s);\r\n  })();\r\n	\r\n</script> ', 'Y');
INSERT INTO `SEM_GACODE` VALUES (4, 'punjabijeevansathi.in', '<!-- GA Code for punjabijeevansathi.in -->\r\n\r\n<script type="text/javascript">\r\n\r\n	  var _gaq = _gaq || [];\r\n	  _gaq.push([''_setAccount'', ''UA-20941669-1'']);\r\n	  _gaq.push([''_setDomainName'', ''.punjabijeevansathi.in'']);\r\n	  _gaq.push([''_trackPageview'']);\r\n	\r\n	  (function() {\r\n	    var ga = document.createElement(''script''); ga.type = ''text/javascript''; ga.async = true;\r\n	    ga.src = (''https:'' == document.location.protocol ? ''https://ssl'' : ''http://www'') + ''.google-analytics.com/ga.js'';\r\n	    var s = document.getElementsByTagName(''script'')[0]; s.parentNode.insertBefore(ga, s);\r\n	  })();\r\n\r\n</script> ', 'Y');
INSERT INTO `SEM_GACODE` VALUES (5, 'hindujeevansathi.com', '<!-- GA Code for hindujeevansathi.com -->\r\n\r\n<script type="text/javascript">\r\n\r\n 	  var _gaq = _gaq || [];\r\n	  _gaq.push([''_setAccount'', ''UA-20940866-1'']);\r\n	  _gaq.push([''_setDomainName'', ''.hindujeevansathi.com'']);\r\n	  _gaq.push([''_trackPageview'']);\r\n	\r\n	  (function() {\r\n	    var ga = document.createElement(''script''); ga.type = ''text/javascript''; ga.async = true;\r\n	    ga.src = (''https:'' == document.location.protocol ? ''https://ssl'' : ''http://www'') + ''.google-analytics.com/ga.js'';\r\n	    var s = document.getElementsByTagName(''script'')[0]; s.parentNode.insertBefore(ga, s);\r\n	  })(); \r\n\r\n</script> ', 'Y');
INSERT INTO `SEM_GACODE` VALUES (6, 'punjabijeevansathi.com', '<!-- GA Code for punjabijeevansathi.com -->\r\n\r\n<script type="text/javascript">\r\n\r\n 	  var _gaq = _gaq || [];\r\n	  _gaq.push([''_setAccount'', ''UA-20941670-1'']);\r\n	  _gaq.push([''_setDomainName'', ''.punjabijeevansathi.com'']);\r\n	  _gaq.push([''_trackPageview'']);\r\n	\r\n	  (function() {\r\n	    var ga = document.createElement(''script''); ga.type = ''text/javascript''; ga.async = true;\r\n	    ga.src = (''https:'' == document.location.protocol ? ''https://ssl'' : ''http://www'') + ''.google-analytics.com/ga.js'';\r\n	    var s = document.getElementsByTagName(''script'')[0]; s.parentNode.insertBefore(ga, s);\r\n	  })(); \r\n\r\n</script> ', 'Y');
        
