Use MIS;

ALTER TABLE  `SOURCE_MEMBERS` ADD  `HAVEPHOTO` CHAR( 1 ) NOT NULL ,
ADD  `PHONE_STATUS` CHAR( 1 ) NOT NULL, ADD  `DUPLICATE` CHAR( 1 ) NOT NULL;


CREATE TABLE `SOURCE_MEMBERS_PAID` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `ENTRY_DT` date NOT NULL DEFAULT '0000-00-00',
 `SOURCEID` varchar(10) NOT NULL DEFAULT '',
 `SOURCEGP` varchar(255) NOT NULL DEFAULT '',
 `ACTIVATED` char(1) NOT NULL DEFAULT '',
 `INCOMPLETE` char(1) NOT NULL DEFAULT '',
 `ENTRY_MODIFY` enum('E','M') NOT NULL DEFAULT 'E',
 `AGE` int(11) NOT NULL DEFAULT '0',
 `GENDER` char(1) NOT NULL DEFAULT '',
 `CITY_RES` varchar(4) NOT NULL DEFAULT '',
 `COUNTRY_RES` int(11) NOT NULL DEFAULT '0',
 `MTONGUE` int(11) NOT NULL DEFAULT '0',
 `MSTATUS` char(1) NOT NULL DEFAULT '',
 `RELATION` char(1) NOT NULL DEFAULT '',
 `COUNT45` int(11) DEFAULT '0',
 `COUNT90` int(11) DEFAULT '0',
 `SEC_SOURCE` char(1) DEFAULT NULL,
 `HAVEPHOTO` char(1) NOT NULL,
 `PHONE_STATUS` char(1) NOT NULL,
 `DUPLICATE` char(1) DEFAULT NULL,
 PRIMARY KEY (`ID`),
 KEY `ENTRY_DT` (`ENTRY_DT`),
 KEY `SOURCEID` (`SOURCEID`),
 KEY `SOURCEGP` (`SOURCEGP`),
 KEY `CITY_RES` (`CITY_RES`),
 KEY `COUNTRY_RES` (`COUNTRY_RES`),
 KEY `COMMUNITY` (`MTONGUE`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1
