use incentive;

INSERT INTO `FIELD_SALES_CITY` (`VALUE`, `NAME`) VALUES ('MH04', 'MUMBAI');

INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('North Mumbai', 'MH0410' ,'MH04');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('West Central Mumbai', 'MH0411' ,'MH04');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('East Central Mumbai', 'MH0412' ,'MH04');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('East Mumbai', 'MH0413' ,'MH04');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('South Mumbai', 'MH0414' ,'MH04');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('North Pune', 'MH0805' ,'MH08');
INSERT INTO `SUB_LOCATION` (`LABEL`, `VALUE`, `PRIORITY`) VALUES ('South Pune', 'MH0806' ,'MH08');

use jsadmin;
DELETE FROM AGENT_ALLOTED WHERE CENTER='PUNE' AND METHOD='FIELD_SALES';

INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'North Mumbai','100');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'West Central Mumbai','100');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'East Central Mumbai','100');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'East Mumbai','100');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'South Mumbai','100');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'North Pune','100');
INSERT INTO `AGENT_ALLOTED` (`USER`, `METHOD`, `CENTER`, `ALLOCATION_LIMIT`) VALUES ('', 'FIELD_SALES', 'South Pune','100');

