use jsadmin;
INSERT IGNORE INTO NON_SERIOUS_PROFILES (PROFILEID) VALUES ('136580');
use newjs;
ALTER TABLE SWAP ADD POPULAR FLOAT NOT NULL ;
DELETE FROM SEARCH_FEMALE WHERE PROFILEID = '136580';
DELETE FROM SEARCH_MALE WHERE PROFILEID = '136580';
