-- Database: `billing`

INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`) VALUES ('', 'P10', 'e-Rishta - 10 months', '', 10, '','','','Y', '', 'PF10', 'N', '', 'N', 'Y');

INSERT INTO `SERVICES` (`ID`, `SERVICEID`, `NAME`, `DESCRIPTION`, `DURATION`, `PRICE_RS`, `PRICE_RS_TAX`, `PRICE_DOL`, `PACKAGE`, `COMPID`, `PACKID`, `ADDON`, `SORTBY`, `SHOW_ONLINE`, `ACTIVE`) VALUES ('', 'C10', 'e-Value Pack - 10 months', '', 10, '','','', 'Y', '', 'PC10', 'N', '', 'N', 'Y');


INSERT INTO `PACK_COMPONENTS` ( `ID` , `PACKID` , `COMPID` ) VALUES ('', 'PF10', 'F10' ), ('', 'PC10', 'D10' ), ('', 'PC10', 'F10' );
 
INSERT INTO `COMPONENTS` ( `ID` , `COMPID` , `NAME` , `DESCRIPTION` , `DURATION` , `PRICE_RS` , `PRICE_DOL` , `RIGHTS` , `TYPE` , `ACC_COUNT` ) VALUES ('', 'D10', 'Display Contact Details - 10 months','', '10', '0', '0', 'D', 'D', '0' );  

INSERT INTO `COMPONENTS` ( `ID` , `COMPID` , `NAME` , `DESCRIPTION` , `DURATION` , `PRICE_RS` , `PRICE_DOL` , `RIGHTS` , `TYPE` , `ACC_COUNT` ) VALUES ('' , 'F10', 'Full Contact - 10 months','', '10', '0', '0', 'F', 'D', '0' ); 


UPDATE SERVICES SET PRICE_RS_TAX=495,PRICE_DOL=9,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P1W' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=695,PRICE_DOL=19,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P2W' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=995,PRICE_DOL=29,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P1' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=1895,PRICE_DOL=59,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P2' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=2295,PRICE_DOL=75,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P3' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=2695,PRICE_DOL=89,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P4' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=3095,PRICE_DOL=99,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P5' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=3495,PRICE_DOL=109,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P6' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=3495,PRICE_DOL=109,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P7' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=3495,PRICE_DOL=109,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P8' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=3495,PRICE_DOL=109,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P9' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4595,PRICE_DOL=119,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P10' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4795,PRICE_DOL=129,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P11' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4995,PRICE_DOL=139,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P12' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=5995,PRICE_DOL=159,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='PL' LIMIT 1;

UPDATE SERVICES SET PRICE_RS_TAX=695,PRICE_DOL=19,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C1W' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=995,PRICE_DOL=29,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C2W' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=1495,PRICE_DOL=45,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C1' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=2495,PRICE_DOL=79,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C2' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=2895,PRICE_DOL=95,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C3' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=3395,PRICE_DOL=115,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C4' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=3895,PRICE_DOL=125,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C5' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4495,PRICE_DOL=139,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C6' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4495,PRICE_DOL=139,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C7' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4495,PRICE_DOL=139,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C8' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4495,PRICE_DOL=139,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C9' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=5495,PRICE_DOL=155,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C10' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=5795,PRICE_DOL=165,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C11' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=5995,PRICE_DOL=175,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C12' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=7495,PRICE_DOL=199,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='CL' LIMIT 1;


UPDATE SERVICES SET PRICE_RS_TAX=195,PRICE_DOL=5,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='A1' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=195,PRICE_DOL=5,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='B1' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=195,PRICE_DOL=5,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='T1' LIMIT 1;
INSERT INTO DIRECT_CALL_COUNT values('P10','150'),('C10','150');
