SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

USE `MIS`;

CREATE TABLE IF NOT EXISTS `MIS_MAINPAGE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) COLLATE utf8_bin NOT NULL,
  `MAIN_URL` varchar(250) COLLATE utf8_bin NOT NULL,
  `JUMP_URL` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `PRIVILEGE` varchar(250) COLLATE utf8_bin NOT NULL,
  `ACTIVE` enum('Y','N') COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`ID`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=95;

INSERT IGNORE INTO `MIS_MAINPAGE` (`ID`, `NAME`, `MAIN_URL`, `JUMP_URL`, `PRIVILEGE`, `ACTIVE`) VALUES
("1","Profile-wise Dispatch report","/mis/ap_mis_profile_dis.php?cid=$cid&role=DIS&MGR=1","/mis/ap_mis_profile_dis.php?cid=$cid&role=DIS&outside=Y&MGR=1","MGR","Y"),
("2","Queue Report","/mis/ap_queue_report.php?cid=$cid",NULL,"MGR","Y"),
("3","Offline Transaction Wise MIS","/mis/offline_collection_status.php?cid=$cid&user=$user",NULL,"OA","Y"),
("4","Visitor Alert Record","/mis/va_profile_sent.php?checksum=$cid&user=$user",NULL,"MC1","Y"),
("5","Total Collection MIS","/mis/collectionmis.php?checksum=$cid&user=$user","/mis/collectionmis.php?checksum=$cid&user=$user&outside=Y","MC1","Y"),
("6","Delete Profile Pipeline MIS","/mis/delete_profiles.php?checksum=$cid&user=$user",NULL,"MC1","Y"),
("7","Contact Search Flow Details","/mis/dailySearchCount.php?checksum=$cid&user=$user","/mis/dailySearchCount.php?checksum=$cid&user=$user&outside=Y","MC1","Y"),
("8","Mobile Verification Details","/mis/mobile_verification_count.php?checksum=$cid&user=$user","/mis/mobile_verification_count.php?checksum=$cid&user=$user&outside=Y","MC1","Y"),
("9","Cheque Details MIS","/mis/cheque_details.php?cid=$cid&user=$user",NULL,"MC1","Y"),
("10","Refund Details","/mis/refund_details.php?checksum=$cid&user=$user",NULL,"MC1+MA+MB","Y"),
("11","Refund User Details","/mis/refund_user_details.php?checksum=$cid&user=$user",NULL,"MC1+MA+MB","Y"),
("12","Gateway Wise (Collection)","/mis/gateway_wise.php?checksum=$cid&user=$user",NULL,"MC1","Y"),
("13","Ticket Distribution Service-wise","/mis/servicesmis.php?cid=$cid&user=$user","/mis/servicesmis.php?cid=$cid&user=$user&CMDGo=1&type=D&reportType=S&profileType=&branch=","MC1","Y"),
("14","Track Views MIS","/mis/view_for_mis_main.php?cid=$cid&user=$user",NULL,"MC1","Y"),
("15","Payment Wise MIS","/mis/paynext.php?checksum=$cid&user=$user",NULL,"MC1","Y"),
("16","Total Month Record (Collection)","/mis/month_record_acc.php?checksum=$cid&user=$user",NULL,"MC1","Y"),
("17","Bank Deposit Slips","/mis/cheque_dd_list.php?cid=$cid&user=$user",NULL,"MC1","Y"),
("18","Unique Paid User","/mis/unique_paid_members.php?cid=$cid&user=$user",NULL,"MC1","Y"),
("19","Response Details","/mis/responseCount.php?checksum=$cid&user=$user","/mis/responseCount.php?checksum=$cid&user=$user&outside=Y","MC1","Y"),
("20","Search for Users eligible for 40 % discount  ","/mis/special_discount_check.php?cid=$cid&user=$user",NULL,"BA","Y"),
("21","Misc Revenue Billing MIS","/mis/rev_billing_mis.php?cid=$cid&user=$user",NULL,"ACCU+ACCA","Y"),
("22","Misc Outstanding MIS","/mis/rev_dueamount_mis.php?cid=$cid&user=$user",NULL,"ACCU+ACCA","Y"),
("23","Payment Collection Status (For Accounts)","/mis/collection_status.php?cid=$cid&user=$user",NULL,"ACCU+ACCA","Y"),
("24","Deferral MIS monthwise","/mis/deferred_monthwise.php?cid=$cid&user=$user",NULL,"ACCU+ACCA","Y"),
("25","Source Wise conversion/relevant / Members MIS","/mis/source_brief_conv.php?checksum=$cid&user=$user",NULL,"MC2","Y"),
("26","Source Wise Hits / Members MIS","/mis/sourcehits.php?checksum=$cid&user=$user",NULL,"MC2","Y"),
("27","Source Wise Hits / Members Percentage MIS","/mis/sourcehitspercent.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("28","Source-Age-Location Wise Members MIS","/mis/ageloc_sourcehits.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("29","Irrelevant Profiles MIS","/mis/irrelevant_profiles_mis.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("30","Contact MIS","/mis/contactsmis.php?checksum=$cid&user=$user",NULL,"MC2","Y"),
("31","Contact MIS (Detail View)","/mis/daily_contact_count.php?cid=$cid&user=$user","/mis/daily_contact_count.php?cid=$cid&user=$user&outside=Y ","MC2","Y"),
("32","Direct Call MIS","/mis/directCallMis.php?cid=$cid&user=$user","/mis/directCallMis.php?cid=$cid&user=$user&outside=Y ","MC2","Y"),
("33","Source Wise Paid Members MIS","/mis/source_members.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("34","Registered Photo MIS","/mis/photomis.php?checksum=$cid&user=$user",NULL,"MC2","Y"),
("35","Registered Members MIS (City-wise/Country-wise)","/mis/registered_members.php?checksum=$cid&user=$user",NULL,"MC2","Y"),
("36","Tickets and Sales distribution - Gender, Posted By, Currency, City, Country-wise","/mis/paid_n_percentages.php?cid=$cid&user=$user","/mis/paid_n_percentages.php?cid=$cid&user=$user&outside=Y","MC2","Y"),
("37","Daily Login Count","/mis/daily_login_count.php?cid=$cid&user=$user","/mis/daily_login_count.php?cid=$cid&user=$user&outside=Y","MC2","Y"),
("38","Search Query Results","/mis/search_query.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("39","Male/Female Count MIS","/mis/male_female_count.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("40","Community Count MIS","/mis/community_count.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("41","Age-Gender/Community MIS Category","/mis/payments_MAINPAGE_LATEST.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("42","Registered/Paid Percentage MIS Category","/mis/regpay_MAINPAGE_LATEST.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("43","FAQ MIS","/mis/faqmis.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("44","Detailed Horoscope Stats","/mis/horoscopemis.php?cid=$cid&user=$user","/mis/horoscopemis.php?cid=$cid&user=$user&outside=Y","MC2","Y"),
("45","Membership Renewal MIS","/mis/resubscribe_status.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("46","Incomplete to Complete Conversion MIS","/mis/incomplete_reg.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("47","JS Indicators","/mis/indicator_index.php?checksum=$cid&user=$user",NULL,"MC2","Y"),
("48","Horoscope Request Count","/mis/requesthoroscopemis.php?cid=$cid&user=$user","/mis/requesthoroscopemis.php?cid=$cid&user=$user&outside=Y","MC2","Y"),
("49","Astro Compatibility Revenue MIS","/mis/astro_compatibility_mis.php?cid=$cid&user=$user","/mis/astro_compatibility_mis.php?cid=$cid&user=$user&outside=Y","MC2+ASTR","Y"),
("50","Cost Per Paid Profile MIS","/mis/profile_acqstn_source_revenue.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("51","3D Trends","/mis/3d_trends.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("52","SMS mis","/mis/sms_mis.php?cid=$cid&user=$user","/mis/sms_mis.php?cid=$cid&user=$user&outside=Y","MC2","Y"),
("53","Search Results And Type ","/mis/search_matrix.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("54","Success Stories","/mis/success_story_count.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("55","Feedback MIS","/mis/feedback_mis.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("56","Contact Breakdown MIS","/mis/contact_breakdown.php?cid=$cid&user=$user",NULL,"MC2","Y"),
("57","Field Sales Executive Performance MIS","/operations.php/crmMis/fieldSalesExecutivePerformanceMis?cid=$cid","/operations.php/crmMis/fieldSalesExecutivePerformanceMis?cid=$cid&outside=Y","ExcFld+SupFld+MgrFld+SLHDO+TRNG+P+MG","Y"),
("58","Field Sales Executive Efficiency MIS","/operations.php/crmMis/fieldSalesExecutiveEfficiencyMis?cid=$cid","/operations.php/crmMis/fieldSalesExecutiveEfficiencyMis?cid=$cid&outside=Y","ExcFld+SupFld+MgrFld+SLHDO+TRNG+P+MG","Y"),
("59","Matri Profile MIS","/mis/matri_profile_mis.php?cid=$cid&user=$user","/mis/matri_profile_mis.php?cid=$cid&user=$user&outside=Y","MC2+MC4","Y"),
("60","Deleted Profiles","/mis/delete_profile_count.php?cid=$cid&user=$user",NULL,"MC2+MC4","Y"),
("61","CONTACT LIMIT EXCEED USERS LIST","/mis/contact_limit_hit.php?cid=$cid&user=$user",NULL,"MC2+MC3","Y"),
("62","Chat related MIS","/mis/chat_mis.php?cid=$cid&user=$user",NULL,"MC2+MC3","Y"),
("63","CRM Handled Revenue MIS","/operations.php/crmMis/crmHandledRevenueMis?cid=$cid","/operations.php/crmMis/crmHandledRevenueMis?cid=$cid&outside=Y","ExcSl+SLMNTR+SLSUP+SLMGR+SLSMGR+SLHD+SLHDO+TRNG+P+MG","Y"),
("64","Sales Follow-up Status MIS","/operations.php/crmMis/fieldSalesFollowUpStatusMis?cid=$cid",NULL,"ExcSl+SLMNTR+SLSUP+SLMGR+SLSMGR+SLHD+SLHDO+TRNG+P+MG","Y"),
("65","Renewal Follow-up Status MIS","/operations.php/crmMis/renewalFollowUpStatusMis?cid=$cid",NULL,"ExcSl+SLMNTR+SLSUP+SLMGR+SLSMGR+SLHD+SLHDO+TRNG+P+MG","Y"),
("66","CRM Users Daily Work MIS","/mis/crm_daily_work_mis.php?cid=$cid",NULL,"MC3+MA+MB+MC","Y"),
("67","Executive-wise Revenue for Incentive Calculation","/mis/ni_handled_incentive_calc.php?cid=$cid&user=$user","/mis/ni_handled_incentive_calc.php?cid=$cid&user=$user&outside=Y","MC3+IUI","Y"),
("68","CRM DailyWork / Revenue / Conversion MIS","/mis/crm_monthly_revenue_mis.php?cid=$cid&user=$user",NULL,"MC3","Y"),
("69","CRM Community wise Conversion MIS","/mis/crm_conversion_community_wise.php?cid=$cid&user=$user",NULL,"MC3","Y"),
("70","Unanswered FAQ Count","/mis/faq_noanswer.php?cid=$cid&user=$user",NULL,"MC3+IA","Y"),
("71","FTA Executive Efficiency MIS","/operations.php/crmMis/ftaRegular?cid=$cid&user=$misname","/operations.php/crmMis/ftaRegular?cid=$cid&user=$misname&outside=Y","MG+TRNG+P+ExcFTA+FTASup","Y"),
("72","Executive Sales Allocation MIS","/mis/crm_sales_allocation.php?cid=$cid&user=$user",NULL,"TRNG+MG+P+IUO+IUI+SLMNTR+SLSUP+SLHD","Y"),
("73","Discount Heads MIS","/operations.php/crmMis/discountHeadsMis?cid=$cid","/operations.php/crmMis/discountHeadsMis?cid=$cid&outside=Y","OPM+OSM+OFSM+MgrFld+SLMGR+SLSMGR+SUP+OPS+OSS+OFSS+SLSUP+LTFSUP+FPSUP+INBSUP+SUPPRM+OPSSUP+UpSSup+RnwSup+PDSSUP+FTASup+CSSUP+LTFVSp+SupFld+SupVDS+SLSMGR+SLHD+LTFHD+OPSHD+SLHDO","Y"),
("74","View Operators Work MIS","/mis/adminusers.php?checksum=$cid&user=$user",NULL,"MC4","Y"),
("75","Operators Work ZONE","/mis/zone.php?checksum=$cid&user=$user",NULL,"MC4","Y"),
("76","Operators Work ZONE - New","/mis/workzone.php?checksum=$cid&user=$user",NULL,"MC4","Y"),
("77","Operators Work ZONE MIS - New/Edit","/mis/new_edit_mis.php?checksum=$cid&user=$user",NULL,"MC4","Y"),
("78","Deleted Profiles Count Details","/mis/deleted_profiles_count.php?checksum=$cid&user=$user","/mis/deleted_profiles_count.php?checksum=$cid&user=$user&outside=Y","MC4","Y"),
("79","MIS for Newspaper feeding","/mis/aff_np_records_count.php?checksum=$cid&user=$user",NULL,"MC4","Y"),
("80","QC Grades Mis","/mis/qc_grades_mis.php?checksum=$cid&user=$user",NULL,"MC4","Y"),
("81","Avg Screen Time MIS","/mis/avg_screen_time.php?cid=$cid&user=$user",NULL,"MC4","Y"),
("82","Profile Screening Efficiency Mis","/mis/live_profile_count.php?cid=$cid&user=$user&type=new","/mis/live_profile_count.php?cid=$cid&user=$user&outside=Y","MC4","Y"),
("83","Photo Screening Efficiency MIS","/mis/photo_screen_eff.php?cid=$cid&user=$user","/mis/photo_screen_eff.php?cid=$cid&user=$user&outside=Y","MC4","Y"),
("84","Photo Screening MIS","/mis/photo_screen_stats.php?checksum=$cid&user=$user","/mis/photo_screen_stats.php?checksum=$cid&user=$user&outside=Y","MC4","Y"),
("85","Order Conversion MIS","/mis/order_conversion.php?checksum=$cid&user=$user","/mis/order_conversion.php?checksum=$cid&user=$user&outside=Y","SLSUP+FPSUP+SLHD+P+MG","Y"),
("86","Failed Payment Leads","/mis/order_conversion_leads.php?checksum=$cid&user=$user",NULL,"SLSUP+FPSUP+SLHD+P+MG","Y"),
("87","Lead Entry Monitoring MIS","/mis/sugarDataFlowMIS.php?cid=$cid&user=$misname",NULL,"OPSUP+OPHD+LTFSUP+LTFHD+P+MG","Y"),
("88","LTF MIS Report","/mis/sugarcrm_LTF_report.php?cid=$cid",NULL,"MG+TRNG+P+SLTF+LTFExc+LTFVnd+LTFSUP+LTFHD","Y"),
("89","Disposition report","/mis/disposition_report.php?cid=$cid",NULL,"MG+TRNG+P+SLMNTR+SLHD+SLSUP","Y"),
("90","Alloted MIS","/mis/allot_mis.php?cid=$cid&user=$user",NULL,"MG+TRNG+P+SLHD+SLSUP","Y"),
("91","PD Identification Efficiency MIS of Executives","/operations.php/duplicateScreening/Mis?name=$misname&cid=$cid&flag=IE_exec","/operations.php/duplicateScreening/Mis?name=$misname&cid=$cid&flag=IE_exec&outside=Y","PDSSUP+OPSHD+P+MG+TRNGOP","Y"),
("92","PD Identification Efficiency MIS of Supervisor","/operations.php/duplicateScreening/Mis?name=$misname&cid=$cid&flag=IE_sup","/operations.php/duplicateScreening/Mis?name=$misname&cid=$cid&flag=IE_sup&outside=Y","PDSSUP+OPSHD+P+MG+TRNGOP","Y"),
("93","PD Screening Executive Efficiency MIS","/operations.php/duplicateScreening/Mis?name=$misname&cid=$cid&flag=SE_exec","/operations.php/duplicateScreening/Mis?name=$misname&cid=$cid&flag=SE_exec&outside=Y","PDSSUP+OPSHD+P+MG+TRNGOP","Y"),
("94","Probable Duplicate Screening pending queue length","/mis/screeningStatusReport.php?name=$misname&cid=$cid",NULL,"PDSSUP+OPSHD+P+MG+TRNGOP","Y");
