use MIS;
CREATE TABLE LOG_DELETED_HIDDEN_IDS_FOR_SEARCH (
  PROFILEID int(11) NOT NULL,
  UPDATED_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PROFILEID),
  KEY UPDATED_TIME (UPDATED_TIME)
) ENGINE=MyISAM;
