use newjs;

DROP TABLE PICTURE_FOR_SCREEN;
DROP TABLE PICTURE_DELETE;
DROP TABLE PICTURE_TITLES;
DROP TABLE PICTURE_UPLOAD;
DROP TABLE PICTURE;
DROP TABLE PHOTOBROWSE_RANKS;
DROP TABLE PHOTOBROWSE_VALUES;

CREATE TABLE `PICTURE_FOR_SCREEN_APP` (
  `PICTUREID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) unsigned NOT NULL,
  `UPDATED_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MainPicUrl` varchar(200) DEFAULT NULL,
  `AlgoPicUrl` varchar(200) DEFAULT NULL,
  `SCREENED_PICTUREID` int(11) unsigned NOT NULL,
  PRIMARY KEY (`PICTUREID`)
) ENGINE=InnoDB;

use jsadmin;

CREATE TABLE `SCREEN_PHOTOS_FOR_APP` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ALLOTED_TO` varchar(20) DEFAULT NULL,
  `RECEIVE_DATE` datetime DEFAULT '0000-00-00 00:00:00',
  `ALLOTED_DATE` datetime DEFAULT '0000-00-00 00:00:00',
  `SUBMIT_DATE` datetime DEFAULT '0000-00-00 00:00:00',
  `STATUS` varchar(25) DEFAULT NULL,
  `PROFILEID` int(6) DEFAULT NULL,
  `USERNAME` varchar(40) NOT NULL,
  `SUBMITED_DATE` datetime DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  KEY `ASSIGNED_TO` (`ALLOTED_TO`),
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=MyISAM;

use MIS;

ALTER TABLE  `SCREEN_EFFICIENCY` ADD  `APP_PIC` INT( 6 ) DEFAULT  '0';

ALTER TABLE  `PHOTO_SCREEN_STATS` ADD  `APP_PIC` INT( 5 ) DEFAULT  '0',ADD  `APP_PIC_APPROVE` INT( 5 ) DEFAULT  '0',ADD  `APP_PIC_EDITED` INT( 5 ) DEFAULT  '0'; 
