use incentive;

CREATE TABLE `LAST_HANDLED_DATE` (
 `SOURCE_ID` int(11) NOT NULL auto_increment,
 `SOURCE_NAME` varchar(50) DEFAULT NULL,
 `DATE` datetime DEFAULT NULL,
 PRIMARY KEY (`SOURCE_ID`)
)

ALTER TABLE incentive.MONTHLY_INCENTIVE_ELIGIBILITY ADD `MODE` enum('CASH','CHEQUE','ONLINE','TT','DD','OTHER','CREDIT','CCOFFLINE','BANK_TRSFR_ONLINE','IVR') DEFAULT 'CASH', ADD `ALLOT_TIME` datetime NOT NULL;

CREATE TABLE `CRM_DAILY_ALLOT_TRACK` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROFILEID` int(11) NOT NULL DEFAULT '0',
 `ALLOTED_TO` varchar(40) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
 `ALLOT_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `RELAX_DAYS` int(11) NOT NULL DEFAULT '0',
 `DE_ALLOCATION_DT` date NOT NULL,
 `ALLOCATION_DAYS` int(11) NOT NULL,
 PRIMARY KEY (`ID`),
 KEY `PROFILEID` (`PROFILEID`),
 KEY `ALLOT_TIME` (`ALLOT_TIME`),
 KEY `DE_ALLOCATION_DT` (`DE_ALLOCATION_DT`)
)
