CREATE TABLE `IN_DIALER_PROFILE_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROFILEID` int(11) unsigned NOT NULL DEFAULT '0',
  `USERNAME` varchar(40) NOT NULL DEFAULT '',
  `ELIGIBLE` enum('Y','N') DEFAULT NULL,
  `FILTER_NAME` varchar(40) DEFAULT NULL,
  `FILTER_VALUE` varchar(40) DEFAULT NULL,
  `ENTRY_DT` date NOT NULL DEFAULT '0000-00-00',
  PRIMARY KEY (`ID`),
  KEY `ENTRY_DT` (`ENTRY_DT`),
  KEY `PROFILEID` (`PROFILEID`)
) ENGINE=InnoDB AUTO_INCREMENT=1411 DEFAULT CHARSET=latin1 AUTO_INCREMENT=1411 ;
