use billing;

ALTER TABLE billing.EXC_CALLBACK MODIFY EMAIL varchar(50) DEFAULT '',MODIFY PHONE_NUMBER varchar(12) DEFAULT '',MODIFY ENTRY_DT datetime DEFAULT '0000-00-00 00:00:00',MODIFY SERVICEID varchar(10) DEFAULT '', ADD PROFILEID int(11) AFTER ID, ADD KEY PROFILEID(`PROFILEID`),ADD KEY EMAIL(`EMAIL`),ADD KEY ENTRY_DT(`ENTRY_DT`);
