use incentive;

CREATE TABLE `PRE_ALLOCATION_LOG` (
`ID` mediumint(9) NOT NULL AUTO_INCREMENT,
`PROFILEID` int(11) unsigned NOT NULL DEFAULT '0',
`ALLOTED_TO` varchar(50) NOT NULL DEFAULT '',
`ALLOT_DT` date NOT NULL DEFAULT '0000-00-00',
`LEVEL` tinyint(3) NOT NULL,
KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1
