CREATE TABLE `SCREENING_PRIORITY` (
 `PHOTO_PAIR` char(1) NOT NULL DEFAULT 'N',
 `FTO_STATE` char(3) NOT NULL,
 `PRIORITY` int(5) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1

ALTER TABLE  `PROBABLE_DUPLICATES` ADD  `PRIORITY` INT( 3 ) DEFAULT  '0' NOT NULL AFTER  `REASON`

INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'D4', 2600);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'D3', 2500);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'D2', 2400);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'D1', 2300);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'C3', 2200);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'C2', 2100);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'C1', 2000);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'F', 1900);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'E3', 1800);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'E4', 1700);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'E5', 1600);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'E2', 1500);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'E1', 1400);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'D4', 1300);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'D3', 1200);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'D2', 1100);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'D1', 1000);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'C3', 900);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'C2', 800);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'C1', 700);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'F', 600);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'E3', 500);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'E4', 400);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'E5', 300);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'E2', 200);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'E1', 100);
INSERT INTO `SCREENING_PRIORITY` VALUES ('Y', 'G', 10);
INSERT INTO `SCREENING_PRIORITY` VALUES ('N', 'G', 0);
