-- Database: `billing`

UPDATE SERVICES SET SHOW_ONLINE='N' WHERE SERVICEID='P2' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='Y' WHERE SERVICEID='P3' LIMIT 1;

UPDATE SERVICES SET SHOW_ONLINE='N' WHERE SERVICEID='C2' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='Y' WHERE SERVICEID='C3' LIMIT 1;

UPDATE SERVICES SET SHOW_ONLINE='N' WHERE SERVICEID='T2' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='N' WHERE SERVICEID='A2' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='N' WHERE SERVICEID='M2' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='N' WHERE SERVICEID='B2' LIMIT 1;

UPDATE SERVICES SET SHOW_ONLINE='N' WHERE SERVICEID='T12' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='N' WHERE SERVICEID='A12' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='N' WHERE SERVICEID='M12' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='N' WHERE SERVICEID='B12' LIMIT 1;

UPDATE SERVICES SET SHOW_ONLINE='Y' WHERE SERVICEID='T3' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='Y' WHERE SERVICEID='A3' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='Y' WHERE SERVICEID='M3' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='Y' WHERE SERVICEID='B3' LIMIT 1;


UPDATE SERVICES SET PRICE_RS_TAX=3795,PRICE_DOL=116,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P7' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4095,PRICE_DOL=123,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P8' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4295,PRICE_DOL=129,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P9' LIMIT 1;

UPDATE SERVICES SET PRICE_DOL=136,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P10' LIMIT 1;
UPDATE SERVICES SET PRICE_DOL=143,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P11' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='N',PRICE_DOL=149,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='P12' LIMIT 1;
UPDATE SERVICES SET PRICE_DOL=169,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='PL' LIMIT 1;


UPDATE SERVICES SET PRICE_RS_TAX=4295 WHERE SERVICEID='C6' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4595,PRICE_DOL=146,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C7' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=4995,PRICE_DOL=153,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C8' LIMIT 1;
UPDATE SERVICES SET PRICE_RS_TAX=5195,PRICE_DOL=159,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C9' LIMIT 1;
UPDATE SERVICES SET PRICE_DOL=166,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C10' LIMIT 1;
UPDATE SERVICES SET PRICE_DOL=173,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C11' LIMIT 1;
UPDATE SERVICES SET SHOW_ONLINE='N',PRICE_DOL=179,PRICE_RS=ROUND(PRICE_RS_TAX/1.103,2) WHERE SERVICEID='C12' LIMIT 1;


