use newjs;

  CREATE TABLE `JPROFILE_ALERTS` (
 `PROFILEID` int(11) NOT NULL,
 `MEMB_CALLS` char(1) NOT NULL,
 `OFFER_CALLS` char(1) NOT NULL,
 `SERV_CALLS_SITE` char(1) NOT NULL,
 `SERV_CALLS_PROF` char(1) NOT NULL,
 `MEMB_MAILS` char(1) NOT NULL,
 `CONTACT_ALERT_MAILS` char(1) NOT NULL,
 `PHOTO_REQUEST_MAILS` char(1) NOT NULL,
 `SERVICE_SMS` char(1) NOT NULL,
 `SERVICE_MMS` char(1) NOT NULL,
 `SERVICE_USSD` char(1) NOT NULL,
 `PROMO_USSD` char(1) NOT NULL,
 `SERVICE_MAILS` char(1) NOT NULL,
 PRIMARY KEY  (`PROFILEID`)
) ENGINE=MyISAM; 
