jsmsPerformSuccess:
  metas:
    title:        Jeevansathi.com
  stylesheets: [-*,jsms/search/srpcss,jsms/contact_engine/contactEngine,jsms/hamburger/ham_css,jsms/common/verificationIcon_css,jsms/common/disableRightClick_css]
  javascripts: [-*,jsms/search/MobileSearchCommon,jsms/photo/photoRequestCommon_js,jsms/search/jqueryInfiniteScroll,jsms/search/JsmsSearch,jsms/search/relaxCriteria_v1@bottom,jsms/contact_engine/contactEngine_js,jsms/search/inview,jsms/hamburger/ham_js@bottom, jsms/utility/sessionStorage_js@bottom, jsms/search/viewSimilarMax@bottom,jsms/common/verificationIcon_js,jsms/common/disableRightClick_js]
  layout: jsmsMobLayout
  
jsmsMessagesSuccess:
  metas:
    title:        Jeevansathi.com
  stylesheets: [-*,jsms/search/srpcss,jsms/contact_engine/contactEngine,jsms/hamburger/ham_css,jsms/common/disableRightClick_css]
  javascripts: [-*,jsms/contact_engine/contactEngine_js,jsms/hamburger/ham_js@bottom,jsms/common/disableRightClick_js]
  layout: jsmsMobLayout

jsmsPhotoRequestSuccess:
  metas:
    title:        Jeevansathi.com
  stylesheets: [-*,jsms/search/srpcss,jsms/contact_engine/contactEngine,jsms/hamburger/ham_css,jsms/common/disableRightClick_css]
  javascripts: [-*,jsms/contact_engine/contactEngine_js,jsms/hamburger/ham_js@bottom,jsms/common/disableRightClick_js]
  layout: jsmsMobLayout

jsmsContactsViewedSuccess:
  metas:
    title:        Jeevansathi.com
  stylesheets: [-*,jsms/search/srpcss,jsms/contact_engine/contactEngine,jsms/hamburger/ham_css,jsms/common/disableRightClick_css]
  javascripts: [-*,jsms/contact_engine/contactEngine_js,jsms/hamburger/ham_js@bottom,jsms/common/disableRightClick_js]
  layout: jsmsMobLayout

indexSuccess:
  metas:
    title:        Inbox - Jeevansathi.com
  javascripts: [jspc/inbox/contactCenter@bottom,jspc/contactEngine/contactEngine,jspc/contactEngine/contactEngineButtons,jspc/common/nano]
  stylesheets: [jspc/search/srpcss,jspc/inbox/contactCenter,jspc/contactEngine/contactEngine_css,jspc/common/NProgress,jspc/common/3DotLoader]
