qualityRegistrationSuccess:
  metas:
    title:        Jeevansathi.com - MIS

  stylesheets:    [jquery_dateLists]

  javascripts:    [jquery_dateLists]
ScreeningCountMisSuccess:
  stylesheets:    [jquery_dateLists]

  javascripts:    [jquery_dateLists]
CampaignsRegistrationSuccess:
  metas:
    title:        Jeevansathi.com - MIS

  stylesheets:    [jquery_dateLists]

  javascripts:    [jquery_dateLists]