<?php
 /*
	This is auto-generated class by running lib/utils/RegEditFieldClassBuilder.php
	This class should not be updated manually.
	Created on 2016-02-02
 */
	class RegisterEditFields
	{
		/*This function will return all the fields of this page*/
    	public static function getPageFields($page,$returnArr='')
    	{
		$page_obj=new PageFields($page);
                foreach (RegistrationEnums::$pageFieldMap[$page] as $id=>$fieldName)
                {
			switch($fieldName)
			{
				case "EMAIL":
					$field=new Field(1);
					$field->setName("EMAIL");
					$field->setFieldType("text");
					$field->setConstraintClass("email");
					$field->setDependentField("");
					$field->setLabel("Email");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:EMAIL");
					$page_obj->setField(1,"","",$field);
					break;
				case "PASSWORD":
					$field=new Field(2);
					$field->setName("PASSWORD");
					$field->setFieldType("password");
					$field->setConstraintClass("password");
					$field->setDependentField("");
					$field->setLabel("Password");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:PASSWORD");
					$page_obj->setField(2,"","",$field);
					break;
				case "RELATIONSHIP":
					$field=new Field(3);
					$field->setName("RELATIONSHIP");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_req");
					$field->setDependentField("");
					$field->setLabel("Create Profile For");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:RELATION");
					$page_obj->setField(3,"","",$field);
					break;
				case "GENDER":
					$field=new Field(4);
					$field->setName("GENDER");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_req");
					$field->setDependentField("3");
					$field->setLabel("Gender");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:GENDER");
					$page_obj->setField(4,"","",$field);
					break;
				case "DTOFBIRTH":
					$field=new Field(5);
					$field->setName("DTOFBIRTH");
					$field->setFieldType("date");
					$field->setConstraintClass("dob");
					$field->setDependentField("");
					$field->setLabel("Date of Birth");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:DTOFBIRTH");
					$page_obj->setField(5,"","",$field);
					break;
				case "PINCODE":
					$field=new Field(7);
					$field->setName("PINCODE");
					$field->setFieldType("text");
					$field->setConstraintClass("pin");
					$field->setDependentField("10");
					$field->setLabel("Pincode");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:PINCODE");
					$page_obj->setField(7,"","",$field);
					break;
				case "HEIGHT":
					$field=new Field(8);
					$field->setName("HEIGHT");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_req");
					$field->setDependentField("");
					$field->setLabel("Height");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:HEIGHT");
					$page_obj->setField(8,"","",$field);
					break;
				case "COUNTRY_RES":
					$field=new Field(9);
					$field->setName("COUNTRY_RES");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_req");
					$field->setDependentField("");
					$field->setLabel("Country living in");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:COUNTRY_RES");
					$page_obj->setField(9,"","",$field);
					break;
				case "CITY_RES":
					$field=new Field(10);
					$field->setName("CITY_RES");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_req");
					$field->setDependentField("9");
					$field->setLabel("City");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:CITY_RES");
					$page_obj->setField(10,"","",$field);
					break;
				case "MSTATUS":
					$field=new Field(11);
					$field->setName("MSTATUS");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("mstatus");
					$field->setDependentField("");
					$field->setLabel("Marital Status");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:MSTATUS");
					$page_obj->setField(11,"","",$field);
					break;
				case "HAVECHILD":
					$field=new Field(12);
					$field->setName("HAVECHILD");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("havechild");
					$field->setDependentField("11");
					$field->setLabel("Have Children");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:HAVECHILD");
					$page_obj->setField(12,"","",$field);
					break;
				case "MTONGUE":
					$field=new Field(13);
					$field->setName("MTONGUE");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_req");
					$field->setDependentField("14");
					$field->setLabel("Mother Tongue");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:MTONGUE");
					$page_obj->setField(13,"","",$field);
					break;
				case "RELIGION":
					$field=new Field(14);
					$field->setName("RELIGION");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_req");
					$field->setDependentField("11");
					$field->setLabel("Religion");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:RELIGION");
					$page_obj->setField(14,"","",$field);
					break;
				case "CASTE":
					$field=new Field(15);
					$field->setName("CASTE");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("caste");
					$field->setDependentField("14");
					$field->setLabel("Caste");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:CASTE");
					$page_obj->setField(15,"","",$field);
					break;
				case "SOURCE":
					$field=new Field(16);
					$field->setName("SOURCE");
					$field->setFieldType("hidden");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:SOURCE");
					$page_obj->setField(16,"","",$field);
					break;
				case "RECORD_ID":
					$field=new Field(17);
					$field->setName("RECORD_ID");
					$field->setFieldType("hidden");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("NO_TABLE");
					$page_obj->setField(17,"","",$field);
					break;
				case "PHONE_MOB":
					$field=new Field(18);
					$field->setName("PHONE_MOB");
					$field->setFieldType("mobile");
					$field->setConstraintClass("mobile");
					$field->setDependentField("19");
					$field->setLabel("Mobile Number");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:ISD-isd,PHONE_MOB-mobile");
					$page_obj->setField(18,"","",$field);
					break;
				case "ISD":
					$field=new Field(19);
					$field->setName("ISD");
					$field->setFieldType("text");
					$field->setConstraintClass("string");
					$field->setDependentField("9");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("");
					$page_obj->setField(19,"","",$field);
					break;
				case "STD":
					$field=new Field(20);
					$field->setName("STD");
					$field->setFieldType("text");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("");
					$page_obj->setField(20,"","",$field);
					break;
				case "PHONE_RES":
					$field=new Field(21);
					$field->setName("PHONE_RES");
					$field->setFieldType("landline");
					$field->setConstraintClass("landline");
					$field->setDependentField("");
					$field->setLabel("LandLine Number");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:ISD-isd,STD-std,PHONE_RES-landline");
					$page_obj->setField(21,"","",$field);
					break;
				case "PROMO":
					$field=new Field(22);
					$field->setName("PROMO");
					$field->setFieldType("checkbox");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:PROMO");
					$page_obj->setField(22,"","",$field);
					break;
				case "TERMSANDCONDITIONS":
					$field=new Field(23);
					$field->setName("TERMSANDCONDITIONS");
					$field->setFieldType("hidden");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("NO_TABLE");
					$page_obj->setField(23,"","",$field);
					break;
				case "DIET":
					$field=new Field(24);
					$field->setName("DIET");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("Diet");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:DIET");
					$page_obj->setField(24,"","",$field);
					break;
				case "SMOKE":
					$field=new Field(25);
					$field->setName("SMOKE");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("Smoke");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:SMOKE");
					$page_obj->setField(25,"","",$field);
					break;
				case "DRINK":
					$field=new Field(26);
					$field->setName("DRINK");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("Drink");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:DRINK");
					$page_obj->setField(26,"","",$field);
					break;
				case "COMPLEXION":
					$field=new Field(27);
					$field->setName("COMPLEXION");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("Complexion");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:COMPLEXION");
					$page_obj->setField(27,"","",$field);
					break;
				case "BTYPE":
					$field=new Field(28);
					$field->setName("BTYPE");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("0");
					$field->setLabel("Body Type");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:BTYPE");
					$page_obj->setField(28,"","",$field);
					break;
				case "OCCUPATION":
					$field=new Field(30);
					$field->setName("OCCUPATION");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_req");
					$field->setDependentField("");
					$field->setLabel("Work Area*");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:OCCUPATION");
					$page_obj->setField(30,"","",$field);
					break;
				case "MANGLIK":
					$field=new Field(31);
					$field->setName("MANGLIK");
					$field->setFieldType("radio");
					$field->setConstraintClass("manglik");
					$field->setDependentField("");
					$field->setLabel("Manglik");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:MANGLIK");
					$page_obj->setField(31,"","",$field);
					break;
				case "HANDICAPPED":
					$field=new Field(32);
					$field->setName("HANDICAPPED");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("");
					$page_obj->setField(32,"","",$field);
					break;
				case "AGE":
					$field=new Field(33);
					$field->setName("AGE");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("");
					$page_obj->setField(33,"","",$field);
					break;
				case "INCOME":
					$field=new Field(34);
					$field->setName("INCOME");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_req");
					$field->setDependentField("");
					$field->setLabel("Annual Income*");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:INCOME");
					$page_obj->setField(34,"","",$field);
					break;
				case "EDU_LEVEL_NEW":
					$field=new Field(35);
					$field->setName("EDU_LEVEL_NEW");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_req");
					$field->setDependentField("");
					$field->setLabel("Highest Degree*");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:EDU_LEVEL_NEW");
					$page_obj->setField(35,"","",$field);
					break;
				case "CASTE_HIDDEN":
					$field=new Field(36);
					$field->setName("CASTE_HIDDEN");
					$field->setFieldType("hidden");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Caste Hidden");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("");
					$page_obj->setField(36,"","",$field);
					break;
				case "RES_STATUS":
					$field=new Field(37);
					$field->setName("RES_STATUS");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Resident Status");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:RES_STATUS");
					$page_obj->setField(37,"","",$field);
					break;
				case "YOURINFO":
					$field=new Field(38);
					$field->setName("YOURINFO");
					$field->setFieldType("textarea");
					$field->setConstraintClass("yourinfo");
					$field->setDependentField("");
					$field->setLabel("Write about your Education Work Family");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:YOURINFO");
					$page_obj->setField(38,"","",$field);
					break;
				case "EDUCATION":
					$field=new Field(39);
					$field->setName("EDUCATION");
					$field->setFieldType("textarea");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Educational Background");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:EDUCATION");
					$page_obj->setField(39,"","",$field);
					break;
				case "JOB_INFO":
					$field=new Field(40);
					$field->setName("JOB_INFO");
					$field->setFieldType("textarea");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Professional Background");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:JOB_INFO");
					$page_obj->setField(40,"","",$field);
					break;
				case "WORK_STATUS":
					$field=new Field(41);
					$field->setName("WORK_STATUS");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Work Status");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:WORK_STATUS");
					$page_obj->setField(41,"","",$field);
					break;
				case "HANDICAPPED":
					$field=new Field(42);
					$field->setName("HANDICAPPED");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Challenged");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:HANDICAPPED");
					$page_obj->setField(42,"","",$field);
					break;
				case "BLOOD_GROUP":
					$field=new Field(43);
					$field->setName("BLOOD_GROUP");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Blood Group");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:BLOOD_GROUP");
					$page_obj->setField(43,"","",$field);
					break;
				case "HIV":
					$field=new Field(44);
					$field->setName("HIV");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("HIV");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:HIV");
					$page_obj->setField(44,"","",$field);
					break;
				case "CONTACT":
					$field=new Field(45);
					$field->setName("CONTACT");
					$field->setFieldType("textarea");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Your Contact Address");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:CONTACT");
					$page_obj->setField(45,"","",$field);
					break;
				case "MESSENGER_ID":
					$field=new Field(46);
					$field->setName("MESSENGER_ID");
					$field->setFieldType("text");
					$field->setConstraintClass("messenger_id");
					$field->setDependentField("");
					$field->setLabel("Messenger ID");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:MESSENGER_ID");
					$page_obj->setField(46,"","",$field);
					break;
				case "SHOWMESSENGER":
					$field=new Field(47);
					$field->setName("SHOWMESSENGER");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:SHOWMESSENGER");
					$page_obj->setField(47,"","",$field);
					break;
				case "SHOWADDRESS":
					$field=new Field(48);
					$field->setName("SHOWADDRESS");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:SHOWADDRESS");
					$page_obj->setField(48,"","",$field);
					break;
				case "MESSENGER_CHANNEL":
					$field=new Field(49);
					$field->setName("MESSENGER_CHANNEL");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("messenger_channel");
					$field->setDependentField("");
					$field->setLabel("Messenger Channel");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:MESSENGER_CHANNEL");
					$page_obj->setField(49,"","",$field);
					break;
				case "P_LAGE":
					$field=new Field(50);
					$field->setName("P_LAGE");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Age");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPARTNER:P_LAGE");
					$page_obj->setField(50,"","",$field);
					break;
				case "P_HAGE":
					$field=new Field(51);
					$field->setName("P_HAGE");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("partner_age");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPARTNER:P_HAGE");
					$page_obj->setField(51,"","",$field);
					break;
				case "P_LHEIGHT":
					$field=new Field(52);
					$field->setName("P_LHEIGHT");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Height");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPARTNER:P_LHEIGHT");
					$page_obj->setField(52,"","",$field);
					break;
				case "P_HHEIGHT":
					$field=new Field(53);
					$field->setName("P_HHEIGHT");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("partner_height");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPARTNER:P_HHEIGHT");
					$page_obj->setField(53,"","",$field);
					break;
				case "P_LRS":
					$field=new Field(54);
					$field->setName("P_LRS");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPARTNER:P_LRS");
					$page_obj->setField(54,"","",$field);
					break;
				case "P_HRS":
					$field=new Field(55);
					$field->setName("P_HRS");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("partner_rupee");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPARTNER:P_HRS");
					$page_obj->setField(55,"","",$field);
					break;
				case "P_LDS":
					$field=new Field(56);
					$field->setName("P_LDS");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Annual Income");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPARTNER:P_LDS");
					$page_obj->setField(56,"","",$field);
					break;
				case "P_HDS":
					$field=new Field(57);
					$field->setName("P_HDS");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("partner_dollar");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPARTNER:P_HDS");
					$page_obj->setField(57,"","",$field);
					break;
				case "NATURE_HANDICAP":
					$field=new Field(58);
					$field->setName("NATURE_HANDICAP");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Nature of handicap");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:NATURE_HANDICAP");
					$page_obj->setField(58,"","",$field);
					break;
				case "F_AGE":
					$field=new Field(59);
					$field->setName("F_AGE");
					$field->setFieldType("checkbox");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("check Age filter is set or not");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("FILTERS:AGE");
					$page_obj->setField(59,"","",$field);
					break;
				case "F_MSTATUS":
					$field=new Field(60);
					$field->setName("F_MSTATUS");
					$field->setFieldType("checkbox");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("check Mstatus filter is set or not");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("FILTERS:MSTATUS");
					$page_obj->setField(60,"","",$field);
					break;
				case "F_RELIGION":
					$field=new Field(61);
					$field->setName("F_RELIGION");
					$field->setFieldType("checkbox");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("check RELIGION filter is set or not");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("FILTERS:RELIGION");
					$page_obj->setField(61,"","",$field);
					break;
				case "F_CASTE":
					$field=new Field(62);
					$field->setName("F_CASTE");
					$field->setFieldType("checkbox");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("check CASTE filter is set or not");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("FILTERS:CASTE");
					$page_obj->setField(62,"","",$field);
					break;
				case "F_COUNTRY_RES":
					$field=new Field(63);
					$field->setName("F_COUNTRY_RES");
					$field->setFieldType("checkbox");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("check SOUNTRY_RES filter is set or not");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("FILTERS:COUNTRY_RES");
					$page_obj->setField(63,"","",$field);
					break;
				case "F_CITY_RES":
					$field=new Field(64);
					$field->setName("F_CITY_RES");
					$field->setFieldType("checkbox");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("check CITY_RES filter is set or not");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("FILTERS:CITY_RES");
					$page_obj->setField(64,"","",$field);
					break;
				case "F_MTONGUE":
					$field=new Field(65);
					$field->setName("F_MTONGUE");
					$field->setFieldType("checkbox");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("check MTONGUE filter is set or not");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("FILTERS:MTONGUE");
					$page_obj->setField(65,"","",$field);
					break;
				case "F_INCOME":
					$field=new Field(66);
					$field->setName("F_INCOME");
					$field->setFieldType("checkbox");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("check INCOME filter is set or not");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("FILTERS:INCOME");
					$page_obj->setField(66,"","",$field);
					break;
				case "NAME_OF_USER":
					$field=new Field(67);
					$field->setName("NAME_OF_USER");
					$field->setFieldType("text");
					$field->setConstraintClass("name_of_user");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("NAME_OF_USER:NAME");
					$page_obj->setField(67,"","",$field);
					break;
				case "DISPLAYNAME":
                                        $field=new Field(127);
                                        $field->setName("DISPLAYNAME");
                                        $field->setFieldType("dropdown");
                                        $field->setConstraintClass("dropdown_not_req");
                                        $field->setDependentField("");
                                        $field->setLabel("");
                                        $field->setBlankValue("");
                                        $field->setBlankLabel("");
                                        $field->setTableName("NAME_OF_USER:DISPLAY");
                                        $page_obj->setField(127,"","",$field);
					break;
				case "SAMPRADAY":
					$field=new Field(68);
					$field->setName("SAMPRADAY");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("Sampraday");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_JAIN:SAMPRADAY");
					$page_obj->setField(68,"","",$field);
					break;
				case "FAMILY_VALUES":
					$field=new Field(69);
					$field->setName("FAMILY_VALUES");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:FAMILY_VALUES");
					$page_obj->setField(69,"","",$field);
					break;
				case "FAMILY_TYPE":
					$field=new Field(70);
					$field->setName("FAMILY_TYPE");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:FAMILY_TYPE");
					$page_obj->setField(70,"","",$field);
					break;
				case "FAMILY_STATUS":
					$field=new Field(71);
					$field->setName("FAMILY_STATUS");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:FAMILY_STATUS");
					$page_obj->setField(71,"","",$field);
					break;
				case "FAMILY_BACK":
					$field=new Field(72);
					$field->setName("FAMILY_BACK");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:FAMILY_BACK");
					$page_obj->setField(72,"","",$field);
					break;
				case "MOTHER_OCC":
					$field=new Field(73);
					$field->setName("MOTHER_OCC");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:MOTHER_OCC");
					$page_obj->setField(73,"","",$field);
					break;
				case "T_BROTHER":
					$field=new Field(74);
					$field->setName("T_BROTHER");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:T_BROTHER");
					$page_obj->setField(74,"","",$field);
					break;
				case "M_BROTHER":
					$field=new Field(75);
					$field->setName("M_BROTHER");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:M_BROTHER");
					$page_obj->setField(75,"","",$field);
					break;
				case "T_SISTER":
					$field=new Field(76);
					$field->setName("T_SISTER");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:T_SISTER");
					$page_obj->setField(76,"","",$field);
					break;
				case "M_SISTER":
					$field=new Field(77);
					$field->setName("M_SISTER");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:M_SISTER");
					$page_obj->setField(77,"","",$field);
					break;
				case "PARENT_CITY_SAME":
					$field=new Field(78);
					$field->setName("PARENT_CITY_SAME");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:PARENT_CITY_SAME");
					$page_obj->setField(78,"","",$field);
					break;
				case "FAMILYINFO":
					$field=new Field(79);
					$field->setName("FAMILYINFO");
					$field->setFieldType("textarea");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:FAMILYINFO");
					$page_obj->setField(79,"","",$field);
					break;
				case "SUBCASTE":
					$field=new Field(80);
					$field->setName("SUBCASTE");
					$field->setFieldType("text");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:SUBCASTE");
					$page_obj->setField(80,"","",$field);
					break;
				case "GOTHRA":
					$field=new Field(81);
					$field->setName("GOTHRA");
					$field->setFieldType("text");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:GOTHRA");
					$page_obj->setField(81,"","",$field);
					break;
				case "MANGLIK":
					$field=new Field(82);
					$field->setName("MANGLIK");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:MANGLIK");
					$page_obj->setField(82,"","",$field);
					break;
				case "RASHI":
					$field=new Field(83);
					$field->setName("RASHI");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:RASHI");
					$page_obj->setField(83,"","",$field);
					break;
				case "ANCESTRAL_ORIGIN":
					$field=new Field(84);
					$field->setName("ANCESTRAL_ORIGIN");
					$field->setFieldType("text");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:ANCESTRAL_ORIGIN");
					$page_obj->setField(84,"","",$field);
					break;
				case "NAKSHATRA":
					$field=new Field(85);
					$field->setName("NAKSHATRA");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:NAKSHATRA");
					$page_obj->setField(85,"","",$field);
					break;
				case "AMRITDHARI":
					$field=new Field(86);
					$field->setName("AMRITDHARI");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_SIKH:AMRITDHARI");
					$page_obj->setField(86,"","",$field);
					break;
				case "CUT_HAIR":
					$field=new Field(87);
					$field->setName("CUT_HAIR");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_SIKH:CUT_HAIR");
					$page_obj->setField(87,"","",$field);
					break;
				case "TRIM_BEARD":
					$field=new Field(88);
					$field->setName("TRIM_BEARD");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_SIKH:TRIM_BEARD");
					$page_obj->setField(88,"","",$field);
					break;
				case "WEAR_TURBAN":
					$field=new Field(89);
					$field->setName("WEAR_TURBAN");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_SIKH:WEAR_TURBAN");
					$page_obj->setField(89,"","",$field);
					break;
				case "CLEAN_SHAVEN":
					$field=new Field(90);
					$field->setName("CLEAN_SHAVEN");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_SIKH:CLEAN_SHAVEN");
					$page_obj->setField(90,"","",$field);
					break;
				case "HOROSCOPE_MATCH":
					$field=new Field(91);
					$field->setName("HOROSCOPE_MATCH");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:HOROSCOPE_MATCH");
					$page_obj->setField(91,"","",$field);
					break;
				case "MATHTHAB":
					$field=new Field(92);
					$field->setName("MATHTHAB");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:MATHTHAB");
					$page_obj->setField(92,"","",$field);
					break;
				case "NAMAZ":
					$field=new Field(93);
					$field->setName("NAMAZ");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:NAMAZ");
					$page_obj->setField(93,"","",$field);
					break;
				case "FASTING":
					$field=new Field(94);
					$field->setName("FASTING");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:FASTING");
					$page_obj->setField(94,"","",$field);
					break;
				case "ZAKAT":
					$field=new Field(95);
					$field->setName("ZAKAT");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:ZAKAT");
					$page_obj->setField(95,"","",$field);
					break;
				case "QURAN":
					$field=new Field(96);
					$field->setName("QURAN");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:QURAN");
					$page_obj->setField(96,"","",$field);
					break;
				case "UMRAH_HAJJ":
					$field=new Field(97);
					$field->setName("UMRAH_HAJJ");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:UMRAH_HAJJ");
					$page_obj->setField(97,"","",$field);
					break;
				case "SUNNAH_BEARD":
					$field=new Field(98);
					$field->setName("SUNNAH_BEARD");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:SUNNAH_BEARD");
					$page_obj->setField(98,"","",$field);
					break;
				case "SUNNAH_CAP":
					$field=new Field(99);
					$field->setName("SUNNAH_CAP");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:SUNNAH_CAP");
					$page_obj->setField(99,"","",$field);
					break;
				case "HIJAB":
					$field=new Field(100);
					$field->setName("HIJAB");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:HIJAB");
					$page_obj->setField(100,"","",$field);
					break;
				case "HIJAB_MARRIAGE":
					$field=new Field(101);
					$field->setName("HIJAB_MARRIAGE");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:HIJAB_MARRIAGE");
					$page_obj->setField(101,"","",$field);
					break;
				case "WORKING_MARRIAGE":
					$field=new Field(102);
					$field->setName("WORKING_MARRIAGE");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:WORKING_MARRIAGE");
					$page_obj->setField(102,"","",$field);
					break;
				case "SPEAK_URDU":
					$field=new Field(103);
					$field->setName("SPEAK_URDU");
					$field->setFieldType("checkbox");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:SPEAK_URDU");
					$page_obj->setField(103,"","",$field);
					break;
				case "DIOCESE":
					$field=new Field(104);
					$field->setName("DIOCESE");
					$field->setFieldType("text");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_CHRISTIAN:DIOCESE");
					$page_obj->setField(104,"","",$field);
					break;
				case "BAPTISED":
					$field=new Field(105);
					$field->setName("BAPTISED");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_CHRISTIAN:BAPTISED");
					$page_obj->setField(105,"","",$field);
					break;
				case "READ_BIBLE":
					$field=new Field(107);
					$field->setName("READ_BIBLE");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_CHRISTIAN:READ_BIBLE");
					$page_obj->setField(107,"","",$field);
					break;
				case "OFFER_TITHE":
					$field=new Field(108);
					$field->setName("OFFER_TITHE");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_CHRISTIAN:OFFER_TITHE");
					$page_obj->setField(108,"","",$field);
					break;
				case "SPREADING_GOSPEL":
					$field=new Field(109);
					$field->setName("SPREADING_GOSPEL");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_CHRISTIAN:SPREADING_GOSPEL");
					$page_obj->setField(109,"","",$field);
					break;
				case "ZARATHUSHTRI":
					$field=new Field(110);
					$field->setName("ZARATHUSHTRI");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_PARSI:ZARATHUSHTRI");
					$page_obj->setField(110,"","",$field);
					break;
				case "PARENTS_ZARATHUSHTRI":
					$field=new Field(111);
					$field->setName("PARENTS_ZARATHUSHTRI");
					$field->setFieldType("radio");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_PARSI:PARENTS_ZARATHUSHTRI");
					$page_obj->setField(111,"","",$field);
					break;
				case "SPOUSE":
					$field=new Field(113);
					$field->setName("SPOUSE");
					$field->setFieldType("textarea");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:SPOUSE");
					$page_obj->setField(113,"","",$field);
					break;
				case "REG_ID":
					$field=new Field(114);
					$field->setName("REG_ID");
					$field->setFieldType("hidden");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("NO_TABLE");
					$page_obj->setField(114,"","",$field);
					break;
				case "SHOWPHONE":
					$field=new Field(115);
					$field->setName("SHOWPHONE");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:SHOWPHONE_RES");
					$page_obj->setField(115,"","",$field);
					break;
				case "SHOWMOBILE":
					$field=new Field(116);
					$field->setName("SHOWMOBILE");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:SHOWPHONE_MOB");
					$page_obj->setField(116,"","",$field);
					break;
				case "FAMILY_INCOME":
					$field=new Field(117);
					$field->setName("FAMILY_INCOME");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("Family Income");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:FAMILY_INCOME");
					$page_obj->setField(117,"","",$field);
					break;
				case "NATIVE_COUNTRY":
					$field=new Field(118);
					$field->setName("NATIVE_COUNTRY");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("NATIVE_PLACE:NATIVE_COUNTRY");
					$page_obj->setField(118,"","",$field);
					break;
				case "NATIVE_STATE":
					$field=new Field(119);
					$field->setName("NATIVE_STATE");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("native_place");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("NATIVE_PLACE:NATIVE_STATE");
					$page_obj->setField(119,"","",$field);
					break;
				case "NATIVE_CITY":
					$field=new Field(120);
					$field->setName("NATIVE_CITY");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("native_place");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("NATIVE_PLACE:NATIVE_CITY");
					$page_obj->setField(120,"","",$field);
					break;
				case "COLLEGE":
					$field=new Field(121);
					$field->setName("COLLEGE");
					$field->setFieldType("text");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE_EDUCATION:COLLEGE");
					$page_obj->setField(121,"","",$field);
					break;
				case "PG_COLLEGE":
					$field=new Field(122);
					$field->setName("PG_COLLEGE");
					$field->setFieldType("text");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE_EDUCATION:PG_COLLEGE");
					$page_obj->setField(122,"","",$field);
					break;
				case "DEGREE_PG":
					$field=new Field(123);
					$field->setName("DEGREE_PG");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE_EDUCATION:PG_DEGREE");
					$page_obj->setField(123,"","",$field);
					break;
				case "DEGREE_UG":
					$field=new Field(124);
					$field->setName("DEGREE_UG");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("dropdown_not_req");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE_EDUCATION:UG_DEGREE");
					$page_obj->setField(124,"","",$field);
					break;
				case "OTHER_PG_DEGREE":
					$field=new Field(125);
					$field->setName("OTHER_PG_DEGREE");
					$field->setFieldType("text");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE_EDUCATION:OTHER_PG_DEGREE");
					$page_obj->setField(125,"","",$field);
					break;
				case "OTHER_UG_DEGREE":
					$field=new Field(126);
					$field->setName("OTHER_UG_DEGREE");
					$field->setFieldType("text");
					$field->setConstraintClass("string");
					$field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE_EDUCATION:OTHER_UG_DEGREE");
					$page_obj->setField(126,"","",$field);
					break;
                                case 'CASTEMUSLIM':
					$field=new Field(127);
                                        $field->setName("CASTEMUSLIM");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("sect");
                                        $field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JPROFILE:SECT");
                                        $page_obj->setField(127,"","",$field);
				break;
                                case 'JAMAAT':
					$field=new Field(128);
                                        $field->setName("JAMAAT");
					$field->setFieldType("dropdown");
					$field->setConstraintClass("jamaat");
                                        $field->setDependentField("");
					$field->setLabel("");
					$field->setBlankValue("");
					$field->setBlankLabel("");
					$field->setTableName("JP_MUSLIM:JAMAAT");
                                        $page_obj->setField(128,"","",$field);
				break;
			}
		}

		return($page_obj);
			}

			public static function getFieldArray($page)
				{
				return(RegistrationEnums::$pageFieldMap[$page]);
				}
}
