indexSuccess:
  metas:   
    canonical: https://www.jeevansathi.com/
    title: Matrimony, Marriage, Matrimonial Sites, Match Making
    verify-v1: y8P0QEbZI8rd6ckhDc6mIedNE4mlDMVDFD2MuWjjW9M=   
  stylesheets: [jspc/logout/homecss,jspc/search/searchBand]
  javascripts: [jspc/common/hslider@bottom,jspc/common/test1@bottom,jspc/logout/hpjs@bottom,jspc/search/searchDropdowns@bottom,jspc/search/searchBand@bottom]
  layout: jspcLayout

