<?php
include("connect.inc");
$db=connect_misdb();

if(authenticated($cid))
{
	if($CMDGo)
	{
		if($val=='income')
			include("income_reg_pay.php");
		elseif($val=='source')
			include("source_reg_pay.php");
		elseif($val=='city')
			include("city_reg_pay.php");
		elseif($val=='community')
			include("community_reg_pay.php");
		elseif($val=='age')
			include("age_reg_pay.php");
	}
	else
	{
		$smarty->assign("cid",$cid);
		$smarty->display("regpay_mainpage.htm");
	}
}
else
{
	$smarty->display("jsconnectError.tpl");
}
?>
