# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

indexSuccess:

  metas:
    title:        Contact Us - Jeevansathi Head Office - Match Making Office - Jeevansathi.com
    description:  Perfect match just a call away. Call NOW on 1-800-419-6299 or walk into nearest office in your city
    keywords:     Jeevansathi.com, jeevansathi contact us - contact us jeevansathi.com, jeevansathi head office, match making office, match point office, matchmaking office, matrimonial office, matrimony services, jeevansathi branch offices, jeevansathi matchmaking offices, marriage bureau addresses, matchmaking services
    language:     en
    robots:       index, follow

  stylesheets:    [contactus_css]
  javascripts:    [google_map_api_js]

JSMSContactUsSuccess:
  metas:
    title:      Contact Us
  stylesheets: [-*,jsms/hamburger/ham_css,jsms/profile/ep/mp_css,jsms/profile/ep/revamp_edit_profile_css,jsms/common/commoncss,jsms/common/mediaquery,jsms/photo/photoup,jsms/common/errorBar,jsms/settings/settings_css]
  javascripts: [-*,jquery_validate_js,jsms/utility/sessionStorage_js,jsms/hamburger/ham_js@bottom,jsms/contactus/contactus_js,jsms/common/sly]
  layout: jsmsMobLayout

JSPCContactUsSuccess:
  metas:
    title:        Jeevansathi.com
  stylesheets: [jspc/common/cssRangeSlider,jspc/common/jquerymCustomScrollbar,jspc/contactus/contactus_css]
  javascripts: [jspc/common/jqueryRangeSlider@bottom,jspc/common/photoAlbum@bottom,jspc/common/jquerymCustomScrollbarConcat@bottom,jspc/contactus/contactus_js@bottom,jsms/membership/jquery_sly@bottom]
  layout: jspcLayout
  
notificationSuccess:
    metas:
        title:  Notification
    layout: notificationLayout
