~include_partial('global/header')`
 <br>
 <body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
~if $noProfileFound`
<div align="center" ><b>No More Profiles to be Screened. Please try after some time. </b> </div>
~elseif $noPhotosFound`
<div align="center" ><b>This profile has no photos to be screened. </b> </div>
~else`
		<table width="600" border="1" cellspacing="1" cellpadding='3' ALIGN="CENTER" >
		    <tr class=label align=center>
			<td width=10%>&nbsp;Gender</td>
			<td width=10%>&nbsp;Age</td>
			<td width=10%>&nbsp;Country</td>
			<td width=10%>&nbsp;City</td>
			<td width=10%>&nbsp;Marital Status</td>
			<td width=10%>&nbsp;Ethinicty (State of Origin)</td>
			<td width=10%>&nbsp;Religion</td>
			<td width=10%>&nbsp;Caste</td>
			<td width=10%>&nbsp;Country of Birth</td>
			<td width=10%>&nbsp;City of Birth</td>
		    </tr>
		
		    <tr class=fieldsnew align=center ~if $profileData['USERPAID'] eq '1'` style="background:#00FF00;"~/if`> 
			<td>&nbsp;~$profileData['GENDER']`</td>
			<td>&nbsp;~$profileData['AGE']`</td>
			<td>&nbsp;~$profileData['COUNTRY_RES']`</td>
			<td>&nbsp;~if $profileData['CITY_RES'] neq ''` ~$profileData['CITY_RES']` ~else` Outside India ~/if`</td>
			<td>&nbsp;~$profileData['MSTATUS']`</td>
			<td>&nbsp;~$profileData['MTONGUE']`</td>
			<td>&nbsp;~$profileData['RELIGION']`</td>
			<td>&nbsp;~$profileData['CASTE']`</td>
			<td>&nbsp;~$profileData['COUNTRY_BIRTH']`</td>
			<td>&nbsp;~if $profileData['CITY_BIRTH'] neq ''` ~$profileData['CITY_BIRTH']` ~else` Not Specified ~/if`</td>
		    </tr>
		</table>
<br>
</br>
 <form name="list" enctype="multipart/form-data" action="~sfConfig::get('app_site_url')`/operations.php/photoScreening/uploadAppPhoto?cid=~$cid`" method="POST">
   <input type=hidden name="profileid" value="~$profileData['PROFILEID']`">
   <input type = "hidden" name= "emailAdd" value = "~$profileData['EMAIL']`">
   <input type=hidden name="source" value="~$source`">
   <input type=hidden name="cid" value="~$cid`">
   <input type=hidden name="username" value="~$execName`">
   <input type="hidden" name="havePhotoValue" value="~$profileData['HAVEPHOTO']`">
   <table width=760 align="CENTER" cellspacing="25" >

	<tr class="formhead" ~if $profileData['USERPAID'] eq '1'` style="background:#00FF00;"~/if`>
	<td>Username : ~$profileData['USERNAME']`</td>
	<td>Gender : <font class="red">~$profileData['GENDER']`</font></td>
	</tr>    

	<tr><td></td><td></td></tr>

   </table>
   <table border = "1" align = "center" cellspacing="25">
	<tr class="formhead" align = "center">
	<td width = "450"><b>Actual Photo (~$appPicData['MainPicActualWidth']`*~$appPicData['MainPicActualHeight']`)</b></td>
	<td width = "450"><b>APP Photo ~if $appPicData['AlgoPicUrl']`(~$appPicData['AlgoPicActualWidth']`*~$appPicData['AlgoPicActualHeight']`)~/if` generated by algorithm</b></td>
	<td></td>
	</tr>	
	<tr>
	<td width = "450" height = "600"><img src = "~sfConfig::get('app_site_url')`/operations.php/photoScreening/changeImageName?username=~$profileData['USERNAME']`&order=m&Imagefile=~$appPicData['MainPicUrl']`" border = "1" width = ~$appPicData['width']` height = ~$appPicData['height']` /></td>
	<td width = "450" height = "600" valign="top">
		<center>
		~assign var='tabIndex' value=1`
		~if $appPicData['AlgoPicUrl']`
			~assign var='case' value=1`
			<img src = "~sfConfig::get('app_site_url')`/operations.php/photoScreening/changeImageName?username=~$profileData['USERNAME']`&order=a&Imagefile=~$appPicData['AlgoPicUrl']`" border = "1" />
		~else`
			~assign var='case' value=2`
			APP Photo could not be generated. <br /><br />
			Kindly upload the APP photo (450*600)
		~/if`
		</center>
		<input type = "hidden" name = "whichCase" value = "~$case`" />
		<input type = "hidden" name = "pictureid" value = "~$appPicData['PICTUREID']`" />
		<input type = "hidden" name = "screened_pictureid" value = "~$appPicData['SCREENED_PICTUREID']`" />
	</td>
	<td>
		~if $appPicData['AlgoPicUrl']`
			<br /><br />
			<input type = "radio" name = "photoActionRadio" value = "Approve" checked = "Y" onclick = "fileInputDisplay(1);" tabIndex="~$tabIndex`" />Approve<br /><br />
			~assign var = "tabIndex" value = $tabIndex+1`
			<input type = "radio" name = "photoActionRadio" value = "Edit" onclick = "fileInputDisplay(2);" tabIndex="~$tabIndex`" />Edit<br /><br />
			~assign var = "tabIndex" value = $tabIndex+1`
			<div id = "appPhotoDiv" style = "display:none;">
				<input type = "file" name = "appPhoto" tabIndex="~$tabIndex`" />
				~assign var = "tabIndex" value = $tabIndex+1`	
			</div>
			
		~else`
			<br /><br />
			<input type = "file" name = "appPhoto" tabIndex="~$tabIndex`" />	
			~assign var = "tabIndex" value = $tabIndex+1`
		~/if`
			<br /><br />
			<input type="submit" tabIndex="~$tabIndex`" name="Submit" value="SUBMIT" onclick="return performChecks(~$case`);">&nbsp;&nbsp;&nbsp;
	</td>
    </table>
	<!--
    <table width=760 align="CENTER" cellspacing="25">
	</tr>
		<tr class = "fieldsnew" align = "CENTER">
		<td><input type="submit" tabIndex="~$tabIndex`" name="Submit" value="SUBMIT" onclick="return performChecks(~$case`);">&nbsp;&nbsp;&nbsp;</td>
		</tr>    	
   </table>-->
  </form>

~/if`
~include_partial('global/footer')`
 </body>
