mobileSuccess:
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css,mobCE_css,mobilejs_revamp]
  javascripts: [-*,mobCE_js@bottom]
  layout: moblayout
mobLogoutSuccess:
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css,mobCE_css]
  javascripts: [-*,mobCE_js@bottom]
  layout: moblayout 
MessageHandlerSuccess: 
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css,mobCE_css,mobilejs_revamp]
  javascripts: [-*,mobCE_js@bottom]
  layout: moblayout 
