page1Success:
  metas:
    title: New Profile Registration - Register Free - Jeevansathi.com
    description: Register Free at Jeevansathi.com and choose from lakhs of genuine profiles from your community, profession, location   etc.
    keywords: Jeevansathi Registration, Matrimony Registration, Matrimonial Registration, Jeevansathi.com Registration, Register    free Jeevansathi.com, Jeevansathi matrimony Registration, jeevansathi matrimonial Registration, Free matrimonial, add profile, search profiles
    google: notranslate

  stylesheets:    [-*,reg_common_css,autoSelect_css,rupeeSymbol_css]
  javascripts:    [jquery_validate_js,register_common_all_js,reg_page1_js@bottom,registration_revamp_js@bottom,noautoSelect_js@bottom,autoSelect_js@bottom,selectType_js@bottom]
  layout: _layoutReg
  
regPageSuccess:
  metas:
    title: Profile Registration - Register Free - Jeevansathi.com
    description: Register Free at Jeevansathi.com and choose from lakhs of genuine profiles from your community, profession, location   etc.
    keywords: Jeevansathi Registration, Matrimony Registration, Matrimonial Registration, Jeevansathi.com Registration, Register    free Jeevansathi.com, Jeevansathi matrimony Registration, jeevansathi matrimonial Registration, Free matrimonial, add profile, search profiles
    google: notranslate
    
  stylesheets:    [jspc/registration/registrationJspc_css]
  javascripts:    [jsms/common/history_js@bottom,jspc/registration/registrationJspc_js@bottom,jspc/common/searchDropdown_js@bottom,jspc/registration/validation_js@bottom,jspc/registration/incompleteProfileJspc_js@bottom]
  layout: jspcLayout

page2Success:
  metas:
    title: Jeevansathi.com Registration - About yourself
    description: Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
    keywords: Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services,online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    google: notranslate
    robots: noindex, nofollow
  stylesheets:    [-*,colorbox_css,reg_common_css,autoSuggest_jq_css,autoSelect_css,rupeeSymbol_css]
  javascripts:    [register_common_all_js,jquery_validate_js,registration_revamp_js@bottom,autoSuggest_jq_js,reg_page2_js@bottom,autoSelect_js@bottom]
  layout: _layoutReg

page3Success:
  metas:
    title: Jeevansathi.com Registration - Social, Family & Religious background 
    description: Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
    keywords: Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services,online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    google: notranslate
    robots: noindex, nofollow
  stylesheets:    [-*,reg_common_css,autoSuggest_jq_css,autoSelect_css,rupeeSymbol_css]
  javascripts:    [register_common_all_js,jquery_validate_js,registration_revamp_js@bottom,autoSuggest_jq_js,reg_page3_js@bottom,editNativePlace_js@bottom,autoSelect_js@bottom,selectType_Page3_js@bottom]
  layout: _layoutReg

page4Success:
  metas:
    title: Jeevansathi.com Registration - Educational, Professional & Additional details
    description: Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
    keywords: Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services,online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    google: notranslate
    #language:     en
    robots: noindex, nofollow

  stylesheets:    [-*,reg_common_css,autoSelect_css,rupeeSymbol_css]
  javascripts:    [jquery_validate_js,reg_page4_js@bottom,registration_js@bottom,advance_search_js@bottom,gadget_as_js@bottom]
  layout: _layoutReg
  
page5Success:
  metas:
    title: Jeevansathi.com Registration - Partner preferences
    description: Register for Free in Jeevansathi.com. Create your matrimonial profile and find your dream life partner. Join Jeevansathi.com today, the leading India matrimonials website in India. Search matrimonials, matrimony profiles, NRI bride and groom from our online matrimonial and matchmaking services.
    keywords: Jeevansathi.com, Indian matrimony, India, matrimony, matrimonial, matrimonials, matrimony services,online matrimonials, Indian marriage, match making, matchmaking, matchmaker, match maker, marriage bureau , matchmaking services, matrimonial profiles, bride, groom, matrimony classified.
    google: notranslate
    robots: noindex, nofollow

  stylesheets:    [-*,reg_common_css,rupeeSymbol_css]
  javascripts:    [register_common_all_js,jquery_validate_js,behaviour_js@bottom,registration_js@bottom,gadget_reg_dpp_js@bottom,regPage5_js@bottom]
  layout: _layoutReg
  
page6Success:
  metas:
    title: Jeevansathi.com Registration - Set Filters
    description: Helps users to restrict the kind of users who can contact them. Allows users to set filters based on Marital Status, Religion, Age, Language, Income, Country and City
    keywords: Set Filters, Marital Status Filter, Religion Filter, Age Filter, Language Filter, Income Filter, Country Filter, City Filter
    google: notranslate
    robots: noindex, nofollow
  
  stylesheets:    [reg_common_css,edit_layer_css,revamp_filter_css,rupeeSymbol_css,hdr_css_new@common]
  javascripts:    [registration_js,advance_search_js,gadget_as_js,revamp_filter_js]
  layout: _layoutReg

miniregSuccess:
  metas:
    title: New Profile Registration - Register Free - Jeevansathi.com
    description: Register Free at Jeevansathi.com and choose from lakhs of genuine profiles from your community, profession, location   etc.
    keywords: Jeevansathi Registration, Matrimony Registration, Matrimonial Registration, Jeevansathi.com Registration, Register    free Jeevansathi.com, Jeevansathi matrimony Registration, jeevansathi matrimonial Registration, Free matrimonial, add profile, search profiles
    google: notranslate

  stylesheets:    [reg_common_css,mini_reg_css]
  javascripts:    [register_common_all_js,jquery_validate_js,mini_reg_revamp_js,registration_revamp_js@bottom]
  layout: _layoutReg
  


jsmbPage1Success:
  metas:
    title:  Jeevansathi.com - Register your profile
    description: Register Free at Jeevansathi.com and choose from lakhs of genuine profiles from your community, profession, location   etc.
    keywords: Jeevansathi Registration, Matrimony Registration, Matrimonial Registration, Jeevansathi.com Registration, Register    free Jeevansathi.com, Jeevansathi matrimony Registration, jeevansathi matrimonial Registration, Free matrimonial, add profile, search profiles
    google: notranslate

  stylesheets: [-*,reg_common_mobile_css,mobreg_pass_css]
  javascripts: [jquery_validate_js,registration_revamp_js@bottom,jsmb_page1_js,tracking_js,showHideReg_js]
  layout: mobRegLayout

jsmbPage2Success:
  metas:
    google: notranslate
    robots: noindex, nofollow

  stylesheets: [-*,reg_common_mobile_css]
  javascripts: [tracking_js,jquery_validate_js,registration_revamp_js@bottom,jsmb_page2_js@bottom,autoMobileSelect_js@bottom,mobselectType_js@bottom]
  layout: mobRegLayout

jsmbPage3Success:
  metas:
    google: notranslate
    robots: noindex, nofollow

  stylesheets: [-*,reg_common_mobile_css]
  javascripts: [tracking_js,jquery_validate_js,jsmb_page3_js@bottom,autoMobileSelect_js@bottom,mobselectType_js@bottom]
  layout: mobRegLayout
  
jsmbPage4Success:
  metas:
    google: notranslate
    robots: noindex, nofollow

  stylesheets: [-*,reg_common_mobile_css]
  javascripts: [tracking_js,jquery_validate_js,registration_revamp_js@bottom,jsmb_page4_js@bottom]
  layout: mobRegLayout  

jsmbPage5Success:
  metas:
    google: notranslate
    robots: noindex, nofollow

  stylesheets: [-*,reg_common_mobile_css,autoSuggest_jq_css]
  javascripts: [tracking_js,jquery_validate_js,registration_revamp_js@bottom,autoSuggest_jq_js,autoMobileSelect_js@bottom,jsmb_page5_js@bottom,editNativePlace_js@bottom,mobNative_Place_selectType_js@bottom]
  layout: mobRegLayout 

customregSuccess:  
  metas:
    title: New Profile Registration - Register Free - Jeevansathi.com
  
  stylesheets: [-*,colorbox_css,common_css,reg_common_css,autoSelect_css,rupeeSymbol_css,customReg_css]
  javascripts: [jquery_validate_js@bottom,register_common_all_js@bottom,reg_page1_js@bottom,registration_revamp_js@bottom,noautoSelect_js@bottom,autoSelect_js@bottom,selectType_js@bottom,customReg_js@bottom]
  
  layout: _layoutCustomReg
newJsmsRegSuccess:
  metas:
    title:  Jeevansathi.com - Register your profile
    description: Register Free at Jeevansathi.com and choose from lakhs of genuine profiles from your community, profession, location   etc.
    keywords: Jeevansathi Registration, Matrimony Registration, Matrimonial Registration, Jeevansathi.com Registration, Register    free Jeevansathi.com, Jeevansathi matrimony Registration, jeevansathi matrimonial Registration, Free matrimonial, add profile, search profiles
    google: notranslate
  stylesheets: [-*,jsms/register/regis_css,jsms/register/reg_animate]
  javascripts: [-*,jsms/angular/registration/lib/angular_min@bottom,jsms/angular/registration/lib/angular-touch_min@bottom,jsms/angular/registration/lib/angular-route_min@bottom,jsms/angular/registration/lib/angular-animate_min@bottom,jsms/angular/registration/lib/angular-resource_min@bottom,jsms/utility/vSlider_js@bottom,jsms/common/touchswipe_js@bottom,jsms/common/disableScroll_js@bottom,jsms/utility/sessionStorage_js,jsms/utility/hamSearch_js@bottom,jsms/angular/registration/hamburger_reg_js@bottom,jsms/angular/registration/scripts/app@bottom,jsms/angular/registration/scripts/services@bottom,jsms/angular/registration/scripts/factories@bottom,jsms/angular/registration/scripts/directives@bottom,jsms/angular/registration/scripts/controllers@bottom]
  layout: jsmsMobLayout
all:
    javascripts:    [-phoneVerify_js@commonBottom]
