# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

indexSuccess:

  metas:
    title:        Jeevansathi Matrimonials-FAQ's
    description:  Perfect match just a call away. Call NOW on 1-800-419-6299 or walk into nearest office in your city
    keywords:     Jeevansathi.com, jeevansathi matrimonials-FAQ's, jeevansathi faq
    language:     en
    robots:       index, follow

  stylesheets:    []
  javascripts:    []

feedbackSuccess:

  metas:
    title:        Jeevansathi Matrimonials-Feedback
    description:  Perfect match just a call away. Call NOW on 1-800-419-6299 or walk into nearest office in your city
    keywords:     Jeevansathi.com, jeevansathi matrimonials-Feedback, jeevansathi feedback,jeevansathi query
    language:     en
    robots:       index, follow
  layout:  jspcLayout
  stylesheets:    [jspc/utility/chosen/chosen_css,jspc/faq/feedback]
  javascripts:    [jspc/utility/chosen/chosen_jquery@bottom,jspc/utility/chosen/docsupport/prism@bottom]

mobilefaqSuccess:
  stylesheets: [-*]
  javascripts: [-*]
  layout: mobRegLayout

mobilefaqconfirmSuccess:
  stylesheets: [-*]
  javascripts: [-*]
  layout: mobRegLayout
