all:
  index:
    enable_login: off
    enable_google_analytics:  on
  cancer:
    enable_login: off
    enable_google_analytics:  on
  404:
    enable_login: off
    enable_google_analytics: on
  seo_IndexTabs:
    enable_login: off
    enable_google_analytics: on
