indexSuccess:
  stylesheets:    [slider_comm_css,seo_community_css]
  javascripts:    [mootools_js,slider_comm_js,seo_community_js]
jspcIndexSuccess:
  stylesheets:    [jspc/seo/seo,jspc/logout/homecss]
  javascripts:    [jspc/seo/seo@bottom]
  layout: jspcLayout
404Success:
  metas:
    title:        404 Not Found
  stylesheets:    []
  javascripts:    []
cancerStory1:
 stylesheets:    [-*,cancer_vcare_css]
 javascripts:    [-*,tracking_js]
cancerStory2:
 stylesheets:    [-*,cancer_vcare_css]
 javascripts:    [-*,tracking_js]
cancerStory3:
 stylesheets:    [-*,cancer_vcare_css]
 javascripts:    [-*,tracking_js]
jsmb_seoSuccess:
  stylesheets: [-*]
  javascripts: [-*,mobSEO_js]
  layout: mobRegLayout
seo_mobSuccess:
  stylesheets:	[-*,jsms/common/commoncss,jsms/common/fonts,jsms/common/mediaquery,jsms/Seo/seoMobile_css]
  layout:         jsmsMobLayout
seo_IndexTabsSuccess:
  metas:
    title: "Browse Matrimony profiles by Community - Jeevansathi.com"
    description: "Find Lakhs of verified matrimony profiles that belongs to your community on Jeevansathi. Safe & Secured matchmaking with exclusive privacy. Add your profile now!"
  stylesheets:	[-*,jsms/hamburger/ham_css,jsms/common/commoncss,jsms/common/fonts,jsms/common/mediaquery,jsms/Seo/seoMobile_css]
  javascripts: [-*,jsms/hamburger/ham_js@bottom]
  layout:         jsmsMobLayout
