indexSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []

timedoutSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []
