screenRBInterestsSuccess:
  metas:
    title:        JsExclusive - Screen RB Interests

  stylesheets:    []

  javascripts:    []

followupCallerSuccess:
  metas:
    title:        JsExclusive - Follow Ups

  stylesheets:    []

  javascripts:    [jspc/crm/exclusiveFollowUps_js@bottom]

submitFollowupStatusSuccess:
  metas:
    title:        JsExclusive - Submit Follow Up Status

  stylesheets:    [jquery_dateLists]

  javascripts:    [jquery_dateLists,jspc/crm/dateSelectionField_js@bottom,jspc/crm/submitFollowUp_js@bottom]