indexSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    []

screenDocumentSuccess:
  metas:
    title:        Test Page

  stylesheets:    [operations_jeevansathi, operations_styles]

  javascripts:    [operations_validate2]